### ISSUE TITLE
Apache has not been designed to serve pages while\n\trunning as root.  

### ISSUE THREAD

**Issue by sajeetharan** [GrahamDumpleton/mod_wsgi#100]
i am trying to setup on a ubuntu 14.04 server when i tried to startup the server it says the error as follows,

root@DIGIN-IO-SRV:~# mod_wsgi-express start-server wsgi.py
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:0
Server Conf        : /tmp/mod_wsgi-localhost:8000:0/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8000:0/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8

WARNING: When running as the 'root' user, it is required that the options
'--user' and '--group' be specified to mod_wsgi-express. These should
define a non 'root' user and group under which the Apache child worker
processes and mod_wsgi daemon processes should be run. Failure to specify
these options will result in Apache and/or the mod_wsgi daemon processes
failing to start. See the mod_wsgi-express documentation for further
information on this restriction.

AH00526: Syntax error on line 17 of /tmp/mod_wsgi-localhost:8000:0/httpd.conf:
Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
root@DIGIN-IO-SRV:~# mod_wsgi-express start-server wsgi.py --port 8001
Server URL         : http://localhost:8001/
Server Root        : /tmp/mod_wsgi-localhost:8001:0
Server Conf        : /tmp/mod_wsgi-localhost:8001:0/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8001:0/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8

WARNING: When running as the 'root' user, it is required that the options
'--user' and '--group' be specified to mod_wsgi-express. These should
define a non 'root' user and group under which the Apache child worker
processes and mod_wsgi daemon processes should be run. Failure to specify
these options will result in Apache and/or the mod_wsgi daemon processes
failing to start. See the mod_wsgi-express documentation for further
information on this restriction.

AH00526: Syntax error on line 17 of /tmp/mod_wsgi-localhost:8001:0/httpd.conf:
Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
root@DIGIN-IO-SRV:~# ^C
root@DIGIN-IO-SRV:~# sudo mod_wsgi-express start-server wsgi.py --port 8001
Server URL         : http://localhost:8001/
Server Root        : /tmp/mod_wsgi-localhost:8001:0
Server Conf        : /tmp/mod_wsgi-localhost:8001:0/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8001:0/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8

WARNING: When running as the 'root' user, it is required that the options
'--user' and '--group' be specified to mod_wsgi-express. These should
define a non 'root' user and group under which the Apache child worker
processes and mod_wsgi daemon processes should be run. Failure to specify
these options will result in Apache and/or the mod_wsgi daemon processes
failing to start. See the mod_wsgi-express documentation for further
information on this restriction.

AH00526: Syntax error on line 17 of /tmp/mod_wsgi-localhost:8001:0/httpd.conf:
Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
root@DIGIN-IO-SRV:~# AH00526: Syntax error on line 17 of /tmp/mod_wsgi-localhost:8001:0/httpd.conf:
AH00526:: command not found
root@DIGIN-IO-SRV:~# Error:\tApache has not been designed to serve pages while\n\trunning as root.

**Comment by GrahamDumpleton** [comment]
This is a message out of Apache and is intended to indicate that Apache child worker processes should not be run as root. Apache itself can initially be run as root fine, but it should always be configured to drop privileges in the Apache child worker processes before doing anything. The default code in Apache will generate this warning and not run if you don't.

For a normal Apache set up, it would have been configured to set the User/Group directives to the appropriate target user for Apache child worker processes to run the child worker processes as, which for Debian systems is www-data, but can be different for other Linux distributions and MacOS X. 

As far as mod_wsgi-express goes, it can't easily know what target user/group should be used given that each system can be different, so in the specific case of when mod_wsgi-express is run as root, you must tell it via the ``--user`` and ``--group`` options what the target user/group are.

The comment tells you that you should do this as well as the documentation on the PyPi site about mod_wsgi-express.

So what you are seeing is normal given you are not passing those options when running as root.

As to running as root in the first place, you should not be doing that unless you specifically need to bind privileged ports such as default HTTP/HTTPS ports of 80/443. If you are using mod_wsgi-express for local development or experiments, then just run it as your normal user from the outset, you do not need to start it as the root user.

**Comment by sajeetharan** [comment]
Thanks now it is fine but there is another issue this happens often, what should i do?

digin@DIGIN-IO-SRV:/$ mod_wsgi-express start-server wsgi.py --port 8001
Server URL         : http://localhost:8001/
Server Root        : /tmp/mod_wsgi-localhost:8001:1000
Server Conf        : /tmp/mod_wsgi-localhost:8001:1000/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8001:1000/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:8001
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:8001
no listening sockets available, shutting down
AH00015: Unable to open logs
digin@DIGIN-IO-SRV:/$ listen 80001
listen: command not found
digin@DIGIN-IO-SRV:/$ Listen 8001

**Comment by GrahamDumpleton** [comment]
That means you already have another application trying to use port 8001. You can only have one application using a port at the one time.

**Comment by sajeetharan** [comment]
ok now i run one python script and this is the ouput
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:1000
Server Conf        : /tmp/mod_wsgi-localhost:8000:1000/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8000:1000/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8
httpd (pid 4148) already running
digin@DIGIN-IO-SRV:/var/www/scripts/modules$

when i check in browser it gives timeout. why?

**Comment by GrahamDumpleton** [comment]
What do you have in ``Executequery.py``? It has to be a valid WSGI application. You can't just give it a normal Python script which does work when it is being imported.

The 'already running' messages gives the impression you are trying to run up more than one instance of mod_wsgi-express on the same port number.

**Comment by sajeetharan** [comment]
It's a normal python script. how to make it a valid WSGI application? There are no documentation related to that.

**Comment by GrahamDumpleton** [comment]
I would suggest you go learn how to write Python web applications using one of the minimalist frameworks that exist out there. One of the best frameworks for that is Flask (http://flask.pocoo.org). Once you understand at least how to write a small web application, then you can start to look how you might convert or use an existing Python script in the context of a web application.

**Comment by sajeetharan** [comment]
ok thanks for the support :)
