### ISSUE TITLE
LD_LIBRARY_PATH and mod_wsgi

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [GrahamDumpleton/mod_wsgi#102]
Hi, I have been trying to run Django app that requires ZeroC Ice on Apache 2.2 with mod_wsgi on CentOS6 using SCL Python.

I recompiled Ice manually, then mod_wsgi plugin without any issues. In order to import Ice I need to set LD_LIBRARY_PATH. I tried to set them via SetEnv but that seems to work per request, so the process is already running when setting LD_LIBRARY_PATH.  This is equivalent to setting it in python itself, which is too late. Looks like Fcgi offers a way to do it https://stackoverflow.com/questions/2550504/setting-ld-library-path-in-apache-passenv-setenv-still-cant-find-library. How should I set LD_LIBRARY_PATH to avoid adding it to /etc/sysconfig/httpd ?

Ola

**Comment by GrahamDumpleton** [comment]
Set ``LD_RUN_PATH`` environment variable at time of compiling the Python wrapper for Ice library. See the response to your question on the mailing list:

* https://groups.google.com/d/msg/modwsgi/4PG377Mq9mc/equFvX7qAQAJ

**Comment by aleksandra-tarkowska** [comment]
@GrahamDumpleton thank you for your response on the forum. I am afraid this is not a solution as I use Ice 3.5

**Comment by GrahamDumpleton** [comment]
Can't see what the version of Ice has got to do with out. Anyway, keeping going with the discussion on the mailing list.
