### ISSUE TITLE
How to debug memory leak?

### ISSUE THREAD

**Issue by demonguy** [GrahamDumpleton/mod_wsgi#106]
I found apache memory use wiil grow up as time goes by. But I don't know how to debug because it is mod_wsgi who call my functions.
Is there any way to debug memory leak when my python scripts are called by mod_wsgi?

**Comment by GrahamDumpleton** [comment]
Working out where memory leaks occur can be complicated.

This is a question best answered on the mod_wsgi mailing list as the issue tracker isn't a place for getting general advice.

First though look at some of the memory profile packages available as WSGI middleware to see if they help. For example:

* https://pypi.python.org/pypi/Dozer

Once you have tried the various tools available, then come to the mod_wsgi mailing list if need more help.
