### ISSUE TITLE
mod_wsgi binary install documentation incomplete (setup.py missing?)

### ISSUE THREAD

**Issue by pulli23** [GrahamDumpleton/mod_wsgi#107]
I know it's not common/good practice to raise questions, but this problem is kind of halting my development completely:

The procedure for installing a mod_wsgi binary could use a big update, as I cannot follow the procedure at all (procedure: https://github.com/GrahamDumpleton/mod_wsgi/tree/develop/win32);

my steps:

- Download the latest version for windows (4.4.12 tar ball): https://github.com/GrahamDumpleton/mod_wsgi/releases/download/4.4.12/mod_wsgi-windows-4.4.12.tar.gz
- Extract correct .so file (32bit, VC10)..

...
...

Now what? Where should the (shared objects?) go? Is setup.py missing?

**Comment by GrahamDumpleton** [comment]
As much as I don't like referring to external blog posts, but feeling lazy right  now, have a look at:

* http://brugbart.com/installing-mod-wsgi-apache-windows

Just use the binaries from what you link above rather than what the post links to.
