### ISSUE TITLE
mod_wsgi-express '--allow-localhost' does not seem to have any effect

### ISSUE THREAD

**Issue by sevens** [GrahamDumpleton/mod_wsgi#108]
I'm using `mod_wsgi-express` with HTTPS for local development.  After a bit of searching and experimenting I got the following command to start `httpd` serving over HTTPS (using a proper port, using given certificate, having HTTPS enabled at all etc):
```bash
DEFAULT_OPTIONS="--document-root=${PROJECT_ROOT}/src/ --log-to-terminal --log-level info \
--server-status --access-log --startup-log"
HTTPS_OPTIONS=" --https-only \
--ssl-certificate-file ${PROJECT_ROOT}/dev/local/certs/development.crt \
--ssl-certificate-key-file ${PROJECT_ROOT}/dev/local/certs/development.key \
--https-port 8443 --server-name localhost --allow-localhost"
mod_wsgi-express start-server $DEFAULT_OPTIONS ${HTTPS_OPTIONS} --reload-on-changes ${PROJECT_ROOT}/src/wsgi.py
```

It turned out that `--allow-localhost` was required to, at least theoretically, allow anyone access to the HTTPS part of the site at all as without it only the `Deny from all` directive is active.  Using this option enables the `Allow from localhost` directive in the generated config file, however, that directive doesn't seem to do anything as even with it enabled any URL still gives a `403` response.

According to the Apache documentation (https://httpd.apache.org/docs/2.2/mod/mod_authz_host.html#allow), using `Allow from <hostname>` triggers a reverse DNS lookup on connecting client's IP address, which seems to be where it goes wrong: neither `127.0.0.1` nor `::1` resolve to `localhost`, at least not on my machine.

So I tested a bit by modifying the generated `httpd.conf` file and changing `Allow from localhost` to:
  * `Allow from 127.0.0.1`: it works as expected when connecting to `https://127.0.0.1:8443` (but not when connecting to `https://localhost:8443`, as it connects over IPv6)
  * `Allow from ::1`: it works when using `https://localhost:8443` too

Using mod_wsgi 4.4.21, Python 2.7.10 (64 bits), Apache HTTP 2.4.16 on Linux (4.1.6, 64 bits).

**Comment by GrahamDumpleton** [comment]
The allow from localhost stuff gets messy as different OS platforms treat it differently. What I find works on MacOS X may not work on Linux.

Until I have a chance to look at it I would point out that ``--server-name`` option shouldn't really be ``localhost`` as that itself may not work.

The value of that option should really the the public fully qualified name for your machine and watch what was used in the SSL certificate.

If using it just for local development and don't have a FQDN, you would be better off creating a host alias in your local hosts file for your machine IP.

```
127.0.0.1        www.example.com
```

and then use in your certificate ``www.example.com`` and also use that with ``--server-name``.

If you have found a way to make it work using extra ``Allow`` directives, you can try adding changes to a file ``extras.conf`` and then use ``--include-file extras.conf``. This will though simply place it at the end of the configuration which may not work if needs to be inside of the ``VirtualHost``.

**Comment by sevens** [comment]
I have only got https to work at all (i.e. `httpd` enabling SSL, listening on HTTPS port too, etc) when using `--server-name` but haven't looked much into it further after it worked as I was glad I got it working at all and there were too many options and  combinations to try out and see which worked and which didn't so I'm not sure if its 'required'.

The testing certificate is actually issued with a `CN` of `localhost` as it's just a self-signed cert for local development anyway and it seems to work fine (besides the `403` responses over https without conf modifications).  The browser did of course give a 'self-signed cert' warning but nothing about the hostname or anything else, just checked again to be sure.

I tried the `--include-file` alternative but I couldn't get it to work, as the relevant `Allow from localhost` part is indeed inside a `VirtualHost`.  I tried redefining that same `VirtualHost` part in the include conf but I couldn't get that to work: it either got ignored or Apache wouldn't start, depending on how much of the original conf I copied (varying from just the relevant `<VirtualHost><Location />... Allow from localhost</Location></VirtualHost>` section to most of the relevant `<VirtualHost>` block).  After a while I gave up and turned to the solution below.

For now I'm letting `mod_wsgi-express` generate the config file, then patch the config file, replacing each `Allow from localhost` with:
```apache
Allow from localhost
Allow from 127.
Allow from ::1
```
then starting apache manually (using `apachectl start -DFOREGROUND`) from my development-server startup script, which works but it's not ideal.

I will be looking into using FQDN certs in the future (my machine has one within the local LAN and it's a nicer solution anyway), just wanted to get a quick working solution first to test some other things.  I'll update this issue if using a FQDN turns up any relevant findings.

**Comment by GrahamDumpleton** [comment]
Wonder if this is a Linux thing. I can't replicate on MacOS X.

If enable ``--server-status`` you end up with a restriction of only:

```
Allow from localhost
```

and so should be able to test with that without futzing with SSL certificates, yet if I force IPV6 request using curl, it still seems to work fine without need to allow ``::1``.

```
curl -g -6 http://[::1]:8000/server-status
```

Or maybe it is only issue on SSL connection.

**Comment by GrahamDumpleton** [comment]
As to the statement:

"""
According to the Apache documentation (https://httpd.apache.org/docs/2.2/mod/mod_authz_host.html#allow), using Allow from <hostname> triggers a reverse DNS lookup on connecting client's IP address, which seems to be where it goes wrong: neither 127.0.0.1 nor ::1 resolve to localhost, at least not on my machine.
"""

This shouldn't be an issue as ``localhost`` is interpreted in special way by operating system and an actual DNS lookup wouldn't be done.

**Comment by sevens** [comment]
Hi Graham, 

Thanks for the response and further investigation.  I've been busy with other things the past weeks so haven't had time to look into it earlier.

As to your tests, I've tried them on my machine and got different results (in line with my previous findings) so it may indeed be a Linux thing, or at least a difference between it and OS X.

I started the server with only `--server-status` as you suggested (`mod_wsgi-express start-server --server-status`), and then did some tests:

```bash
$ curl -g -6 -I http://[::1]:8000/server-status
HTTP/1.1 403 Forbidden
...
$ tail -n1 /tmp/mod_wsgi-localhost:8000:1000/error_log
... [access_compat:error] [pid 13696:tid 140120738162432] [client ::1:54682] AH01797: 
client denied by server configuration: /tmp/mod_wsgi-localhost:8000:1000/htdocs/server-status
$ curl -g -6 -I http://[::1]:8000/
HTTP/1.1 200 OK
...
```

The same seems to happen when using the hostname or explicit IPv4 address:
```bash
$ curl -I http://localhost:8000/server-status
HTTP/1.1 403 Forbidden
...
$ tail -n1 /tmp/mod_wsgi-localhost:8000:1000/error_log
... [access_compat:error] [pid 13696:tid 140120737896192] [client ::1:54866] AH01797: 
client denied by server configuration: /tmp/mod_wsgi-localhost:8000:1000/htdocs/server-status
$ curl -I http://localhost:8000/
HTTP/1.1 200 OK
...

$ curl -I http://127.0.0.1:8000/server-status
HTTP/1.1 403 Forbidden
...
$ tail -n1 /tmp/mod_wsgi-localhost:8000:1000/error_log
... [access_compat:error] [pid 13696:tid 140120737629952] [client 127.0.0.1:60139] AH01797: 
client denied by server configuration: /tmp/mod_wsgi-localhost:8000:1000/htdocs/server-status
$ curl -I http://127.0.0.1:8000/
HTTP/1.1 200 OK
...
```

FYI: I'm now running Linux 4.4.6, httpd 2.4.16, Python 2.7.11 and mod_wsgi 4.5.1

**Comment by GrahamDumpleton** [comment]
What variant of Linux are you using?

I have tested now using ``--server-status`` with CentOS 7 inside of a Docker container and don't have any issue with the three variants working.

**Comment by sevens** [comment]
Ok, so that's not very consistent either then :)  I'm using Slackware64-current (glibc 2.22, gcc 5.3.0).

This got me digging a bit further and in my `/etc/hosts` I had the following two lines:
```
127.0.0.1          boxname.lan boxname localhost
::1                boxname.lan boxname localhost
```

Also, at the top there's a message which says:

> 127.0.0.1 should NEVER be named with the name of the machine.  It causes problems for some (stupid) programs, irc and reputedly talk. :^)

Since I don't run any of those programs I kept my config as it was at the time that message was added, hoping it would make network configs easier (by `boxname.lan` resolving to both its external and localnet IPs).

So as a test I changed those lines to
```
127.0.0.1          localhost
::1                localhost
```
and that fixes the problem (interestingly, using 
```
127.0.0.1          localhost boxname.lan boxname
::1                localhost boxname.lan boxname
```
also fixes the problem).

Sorry for wasting any time.

**Comment by GrahamDumpleton** [comment]
Yeah, alias of localhost for loopback devices should probably always be first.

Thanks for letting me know you worked it out. Would never have thought that could be issue in hosts file.

**Comment by VenkateshDharavath** [comment]
hello,
I'm trying to deploy my django application using mod_wsgi.
I'm able to start server and access it with localhost:8000, but i want to start it with only my ip address and my FQDN. 


    Server URL         : http://localhost:8000/
    Server Root        : /tmp/mod_wsgi-localhost:8000:1000
    Server Conf        : /tmp/mod_wsgi-localhost:8000:1000/httpd.conf
    Error Log File     : /tmp/mod_wsgi-localhost:8000:1000/error_log (warn)
    Request Capacity   : 5 (1 process * 5 threads)
    Request Timeout    : 60 (seconds)
    Startup Timeout    : 15 (seconds)
    Queue Backlog      : 100 (connections)
    Queue Timeout      : 45 (seconds)
    Server Capacity    : 20 (event/worker), 20 (prefork)
    Server Backlog     : 500 (connections)
    Locale Setting     : en_US.UTF-8

server URL shows with a port number. I want to access my site with ip only and the domain mapped to that ip address.
please help me how to do that.

**Comment by GrahamDumpleton** [comment]
@VenkateshDharavath Please don't ask new questions on closed issues. Create a new issue.
