### ISSUE TITLE
I do not konw how to do to solve the APXS problems.

### ISSUE THREAD

**Issue by ipnono** [GrahamDumpleton/mod_wsgi#110]
C:\mod_wsgi-4.4.21>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 139, in <module>
    'missing Apache httpd server packages.' % APXS)
RuntimeError: The 'apxs' command appears not to be installed or is not executabl
e. Please check the list of prerequisites in the documentation for this package
and install any missing Apache httpd server packages.

**Comment by GrahamDumpleton** [comment]
Read:

* https://github.com/GrahamDumpleton/mod_wsgi/tree/develop/win32

The method you are using to build mod_wsgi is only for UNIX/Linux systems.
