### ISSUE TITLE
Make it clear in the docs that access to the apache server is required.

### ISSUE THREAD

**Issue by TierraDelFuego** [GrahamDumpleton/mod_wsgi#111]
I tried to use this code in an htaccess only environment but failed. Please make it clear in the docs that this scenario will not work.  I thought maybe I missed something because I do see discussions around htaccess but that was a red herring I think.  If I have really missed some salient points about doing an htaccess only setup I don't know what it is.

I tried 
export APXS=/usr/bin/apxs2 

and then did a 

pip install mod_wsgi
into a pyvenv created environment.

This is a python 3.5.1 environment.

**Comment by GrahamDumpleton** [comment]
The pip installable variant of mod_wsgi is used independent of any existing Apache installation, so you wouldn't need to go anywhere need a ``.htaccess`` file of a directory for the existing Apache installation.

The purpose of ``mod_wsgi-express`` is to allow you to run up your own Apache/mod_wsgi, without touching the existing installation, on a non privileged port.

If however you still need to have the web service accessible as HTTP/HTTPS on port 80/443, you don't have a choice but to have some level of root access to the main host Apache installation and use a traditional mod_wsgi integrated with it, or disable the main Apache installation and replace it with mod_wsgi-express instance, or at the least, have someone setup the main Apache installation to proxy a VirtualHost to your separate mod_wsgi-express instance running on a non privileged port.

It is not obvious what you are wanting to do, so please explain better what you want. Also indicate whether this is your own host, a company host, or some hosting service?

**Comment by TierraDelFuego** [comment]
You have provided the wording for the docs to make it clearer to anyone that might come along to try this module. 

"mod_wsgi is usually not a standard module installed with apache installations and unless you have  root access or you are satisfied with running mod_wsgi on non-privileged ports mod_wsgi may not work for you."

You may want to provide a section with specifics for the different environments where someone may want to use mod_wsgi.

non-root only env -- limited to non-
vm/root

The other question that comes to mind is why is there so little adoption of mod_wsgi? Perhaps a short discussion of that in the docs would be useful/helpful. There seems to be a standard set of modules that most apache sites enable. Why is mod_wsgi not included? 

I filed this issue to help others that happen along to mod_wsgi. It may save them time to know exactly what the score is before trying to make it work.

**Comment by GrahamDumpleton** [comment]
Unfortunately your quote looses the distinction between mod_wsgi and mod_wsgi-express. They are sort of different things, although mod_wsgi module is used by the mod_wsgi-express wrapper.

Anyway, the docs are long overdue for updating, but have too much other stuff to do right now.

**Comment by TierraDelFuego** [comment]
No longer using this software.
