### ISSUE TITLE
Application Is Slow After Deploying to Apache

### ISSUE THREAD

**Issue by okyere** [GrahamDumpleton/mod_wsgi#112]
I created a small flask application that basically allows users to upload an excel sheet and the data is written to an Oracle database. On my tiny laptop (8 gb of ram, i5 clocked at 2.6), it run faster than when I deployed it on my production redhat server with apache. Of course I used mod_wsgi. I need the application to be faster and more responsive. Below are my specs and configurations for the redhat apache server:

Redhat 6.7
16 gb of ram

Apache:
======
Server version: Apache/2.2.15 (Unix)
Server built:   Aug 18 2015 02:00:22
Server's Module Magic Number: 20051115:25
Server loaded:  APR 1.3.9, APR-Util 1.3.9
Compiled using: APR 1.3.9, APR-Util 1.3.9
Architecture:   64-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="logs/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

This is my virtualhost for the application:
############################################################################
###########################################################################
WSGISocketPrefix /var/run/wsgi
WSGIPythonHome /WebHA/catworld/featureanalytics-443S/webpython
############################################################################
################### For fbbidataupload.cat.com
<VirtualHost *:443>

    DocumentRoot "/WebHA/catworld/featureanalytics-443S/dataupload_app/"
    ServerName fbbidataupload.cat.com
    ServerAlias fbbidataupload.cat.com
    SSLEngine On
    SSLCertificateFile /WebHA/apache/V2.2/certificates/cat.com.cert
    SSLCertificateKeyFile /WebHA/apache/V2.2/certificates/cat.com.key
    SSLCertificateChainFile /WebHA/apache/V2.2/certificates/ESSL_Intermediate_Apache.crt

    WSGIDaemonProcess fbbidataupload.cat.com user=http group=http processes=2 threads=15
    WSGIProcessGroup fbbidataupload.cat.com

    WSGIScriptAlias / /WebHA/catworld/featureanalytics-443S/dataupload_app/uploadapp.wsgi
    Alias /static /WebHA/catworld/featureanalytics-443S/dataupload_app/app/static

    <Directory /WebHA/catworld/featureanalytics-443S/dataupload_app/app/static/>
	    Order allow,deny
	    Allow from all
    </Directory>

    LogLevel info

    <Directory "/WebHA/catworld/featureanalytics-443S/dataupload_app">
	    Options FollowSymLinks Indexes MultiViews
	    AllowOverride All
	    Order allow,deny
	    Allow from all
    </Directory>

    <Location />
      AuthType CWS
      require cws-allow ManagedUsers
    </Location>
</VirtualHost>
############################################################################

So apache is prefork mpm and I'm in daemon mode for mod_wsgi. I'm especially curious about the "processes=2 threads=15". Do those affect the performance of the application? Should I set processes to 4 since I have 4 processors? What about thread? Assuming I can be greedy and decide to allocate all available resources to making this application responsive, what do I need to set these to? Will it even matter?

There's a lame php app on the server that no one uses but is fast; very responsive. I kind of inherited it (server) from someone else. I read that worker mpm might help with performance but that will not be compatible with some php modules. If changing the mpm to worker will help with performance, I'm willing to remove the php app (as it is not used) to gain that performance increase. But I also read from  a comment you made on a stackoverflow question that if I'm running in daemon mode, then it doesn't matter if the mpm is worker or prefork. Anyway, help me make this application more responsive. I can't stand that my windows laptop running the flask development server puts my redhat server to shame. Thanks

**Comment by GrahamDumpleton** [comment]
Not a question for the issue tracker, the mod_wsgi mailing list maybe. Even then it is impossible for me to recommend anything as know nothing really about your application.

I would perhaps suggest you add monitoring to your WSGI application to try and identify the bottlenecks.

Perhaps try New Relic, which provides a free tier with a initial trial with more in-depth features available.
