### ISSUE TITLE
Is this normal behaviour for mod_wsgi?

### ISSUE THREAD

**Issue by thewebdev** [GrahamDumpleton/mod_wsgi#115]
I have made a simple web page with a form that submits its data to a WSGI application. (The form is submitted once using javascript AJAX). The WSGI app uses the python logger to log errors and debugging messages in the error_log, as shown below:

```python
import logging
...
# create logger
logger = logging.getLogger('applog')
logger.setLevel(logging.WARNING)
    
# create logging handler
stream = logging.StreamHandler()
stream.setLevel(logging.WARNING)
logger.addHandler(stream)
    
logger.warning('DEBUG %d: %s', 4000, 'Processing New Request ...')
# ... sanitize form data ...
# ... save the data to the db ...
logger.warning('DEBUG %d: %s', 4000, savedinDB)
```
As the snippet shows, for testing, every time the app receives data from the form, I log that the app has received a new submission. And after the data is saved in the db, I log the ID (timestamp) of the form data saved. 

When I test the app using mod_wsgi-express (with the defaults, as shown below)

```
Mac:v2 s$ sudo mod_wsgi-express start-server --url-alias /test /Library/WebServer/Documents/theform --user _www --group _www hello.wsgi
Password:
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:0
Server Conf        : /tmp/mod_wsgi-localhost:8000:0/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8000:0/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_GB.UTF-8
```
The WSGI app does log everything in the error_log. But for every form submission, it seems to log the debug data n times request. The output of the error_log is here - https://gist.github.com/thewebdev/6ac6881686f11a682abf#file-gistfile1-txt .

As must be obvious, each form submission seems to be duplicate logging with every subsequent calls to the wsgi app. So the first form submission is logged once, the second form submission is logged twice, the third three times, the fourth request four times and so on. 

Is this a bug or am I missing something obvious about mod_wsgi or mod_wsgi-express? (I am using Mac OS X 10.10.5).

**Comment by GrahamDumpleton** [comment]
Are you sure you aren't calling ``addHandler()`` on each request?

Hard to tell without see the actual code with original indenting and relationship to WGSI application code.

In shirt though, mod_wsgi just intercepts whatever is sent to stdout/stderr and sends to Apache error log. So if there are duplicates, it is likely happening due to duplicate handler registrations in Python logging system due to how your code is set up.

**Comment by GrahamDumpleton** [comment]
BTW. The mod_wsgi mailing list is a better place for help debugging issues. The issues tracker is really for reporting actual bugs.

**Comment by thewebdev** [comment]
Ah, thanks for catching that - I just learnt about the logging module, and did not realize that each request would keep on adding handlers to the logger. Removing the handler at the end of the request fixed this. (Most logging tutorials don't seem to cover this because the basic examples are mostly for the terminals. I find using the logging module to be more elegant than using ```print >> environ['wsgi.errors'], "Debug message here"``` and feel it is more pythonic too. Perhaps future mod_wsgi documentation can address? )

(Sorry about posting here and not the mailing list - (1) I actually did think it was a bug with mod_wsgi. (2) To prevent Google from spying on me and violating my privacy and of others in my social network, I avoid all Google products. But I see that you are active on SO and SF, and will henceforth post there instead. Thanks again for your patience.)

**Comment by GrahamDumpleton** [comment]
I am no longer active on SO and SF.

Adding the handler in the WSGI application per request, even if removing it at the end, is a bad idea. This will fail in a multithreaded configuration as concurrent requests could do it at the same time.

You should only setup logging from global scope in a module.

**Comment by thewebdev** [comment]
Thanks for the tip. I am still getting my head around multi-threading and processes, and since the [logging module docs mentioned that it is thread-safe](https://docs.python.org/2/library/logging.html#thread-safety) I assumed that I could use it without having to think about threads and processes in mod_wsgi too.

**Comment by GrahamDumpleton** [comment]
That only applied to using it. Setup still must only be done once and you shouldn't go adding/removing handlers from different threads at the same time for the same thing.

**Comment by thewebdev** [comment]
If it is not too much trouble, could you briefly clarify on the appropriate way to use the SQLite3 module with mod_wsgi too? (As described in this [document](https://dev.yorhel.nl/doc/sqlaccess), I currently seem to be using the *'Thread-local connections'* approach - opening and closing the database with each WSGI request - as I was doing with the logging handler before).

**Comment by GrahamDumpleton** [comment]
That should be okay as SQLite is smart enough to maintain each connection created separately for each thread. The only thing that used to be a problem with SQLite was sharing a connection across threads. Don't know if that is still an issue now.

So if you are creating a SQLite connection at the start of a request and closing it at end of request, that is fine and normal practice.

This doesn't work for logging handlers though as the list of handlers is global and not per thread.
