### ISSUE TITLE
Client closing connection results in Apache logging response code 500

### ISSUE THREAD

**Issue by ccazabon** [GrahamDumpleton/mod_wsgi#117]
Summary:  mod_wsgi seems to cause partial transfers (connect closed by the client) to be logged by Apache as status code 500.

Using:
- mod_wsgi 4.4.21
- Apache 2.4.7-1ubuntu4.9
- Python 2.7.6

I have an application serving streaming media to clients.  The Python code returns the media stream data as fast as possible and returns/exits, so it then sits in a buffer while transferring to the remote client - I'm not sure if that buffer is managed by mod_wsgi or Apache.  The app code believes everything has been successful.

If the client closes the connection before receiving all of the data, Apache logs this in the access log as a 500 status code, with the length of the data transferred to the client, instead of a 200 code like I think it should.  This seems to be specific to mod_wsgi - if I run the test through the same vhost but bypassing the WSGI application stack (serving it as a static file through apache), the same test results in a 200 status code in the access log, with the amount of data that was transferred.

Example log entry served through Apache:

10.0.0.1 - - [29/Jan/2016:15:29:29 +0000] "GET /fcimg/dltest.zip HTTP/1.1" 200 5823856 "-" "curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3"

Example log entry served via the mod_wsgi application:

10.0.0.1 - - [29/Jan/2016:15:12:03 +0000] "GET /dltest HTTP/1.1" 500 3367448 "-" "curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3"

It would be quite helpful if these were logged with a 200 status code so they don't look like errors.

**Comment by heldergg** [comment]
I'm experiencing the same behaviour (Apache/2.2.22 mod_wsgi/4.4.21 Python/2.7.3).

**Comment by GrahamDumpleton** [comment]
Closing this as should be addressed by https://github.com/GrahamDumpleton/mod_wsgi/commit/004ae44ae46b410f3999da1a34dd11e469d98169 and will be released in mod_wsgi version 4.5.25.
