### ISSUE TITLE
Windows - mod_wsgi and Python 2.7.11

### ISSUE THREAD

**Issue by kalbermattenm** [GrahamDumpleton/mod_wsgi#118]
Hello,

I just tried to update Python (32-bit) from 2.7.10 to 2.7.11 on my Windows 7 computer.

I am running Apache 2.2.31 (32-bit) and mod_wsgi 3.5.

Since Python 2.7.11, Apache fails to start throwing error:

```
ImportError: No module named site
```

I also tried to update mod_wsgi using the latest binaries (found here https://github.com/GrahamDumpleton/mod_wsgi/releases/tag/4.4.12), but it does not change the problem.

As soon as I go back to Python 2.7.10, everything is working again...

What is happening is quite obscure for me... I already have done that quite a few times (going from Python 2.7.8 to 2.7.10) and never had this kind of problem...

Does anyone have an idea about what is going wrong ?

**Comment by bobort** [comment]
I am having the same problem.

**Comment by cgohlke** [comment]
Could be [Python issue 25824](https://bugs.python.org/issue25824). Try the [registry workaround](https://bugs.python.org/issue25824#msg256500).

**Comment by GrahamDumpleton** [comment]
Closing. When using Windows everyone should be using ``pip install mod_wsgi`` method as starting point now. Only going to deal with issues on Windows if using ``pip install`` method.
