### ISSUE TITLE
El Capitan - Fail to Configure mod_wsgi

### ISSUE THREAD

**Issue by VaniaFan** [GrahamDumpleton/mod_wsgi#121]
Hi Graham! 

I encountered exactly the same problem as in #98. 
After I run **_mod_wsgi-express module-location_**, I get the output path - **_/Library/Python/2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so_**
<img width="732" alt="httpd conf - loadmodule" src="https://cloud.githubusercontent.com/assets/9417565/13380769/3342309a-de18-11e5-97c9-0b60cbbf0f55.png">
I added the LoadModule line in httpd.conf as above. Am I supposed to run **_mod_wsgi-express install-module_** again? Or what to do?

Thank you!

Edit:
If I **_run /usr/sbin/httpd -M_** and see wsgi_module is in the loaded module list, does it mean it is successfully deployed even if I still couldn't run **_mod_wsgi-express install-module_**?

**Comment by GrahamDumpleton** [comment]
You don't need to run 'install-module'. That you have added the 'LoadModule' line manually is enough. If you see 'wsgi_module' in '-M' output you should be good to go. Did you try a hello world test and have an issue at that point?

**Comment by VaniaFan** [comment]
Hey Graham. Thank you for the quick response! Yes it works now. Thank you!
