### ISSUE TITLE
Error after apachectl graceful on 4.4.22

### ISSUE THREAD

**Issue by OGAWAHirofumi** [GrahamDumpleton/mod_wsgi#124]
By following steps,

<pre>
[connect to wsgi]
# apachectl graceful
[connect to wsgi]
</pre>

WSGI stops to work. And from following, maybe wsgi unix sock name was changed by graceful?
Is there any workaround or patch to try?

<pre>
* before graceful
# lsof|grep apache2/wsgi|head -5
apache2   22506             root   18u     unix 0xffff8800c14b3c00          0t0     862420 /var/run/apache2/wsgi.22506.0.1.sock type=STREAM
apache2   22506             root   19w      REG               0,17            0     862422 /run/apache2/wsgi.22506.0.1.lock (deleted)
apache2   22512         www-data   18u     unix 0xffff8800c14b3c00          0t0     862420 /var/run/apache2/wsgi.22506.0.1.sock type=STREAM
apache2   22512         www-data   19w      REG               0,17            0     862422 /run/apache2/wsgi.22506.0.1.lock (deleted)
apache2   22512 22652   www-data   18u     unix 0xffff8800c14b3c00          0t0     862420 /var/run/apache2/wsgi.22506.0.1.sock type=STREAM

# apachectl graceful

* GET /wsgi-path
[Sun Mar 20 03:39:40.009049 2016] [wsgi:error] [pid 22516:tid 140026339231488] (2)No such file or directory: [client x.x.x.x:x] mod_wsgi (pid=22516): Unable to connect to WSGI daemon process 'sync' on '/var/run/apache2/wsgi.22506.0.1.sock' as user with uid=33.

* after graceful
# lsof|grep apache2/wsgi|head -5
apache2   22506             root   18u     unix 0xffff88022417f800          0t0     861581 /var/run/apache2/wsgi.22506.1.1.sock type=STREAM
apache2   22506             root   19w      REG               0,17            0     861583 /run/apache2/wsgi.22506.1.1.lock (deleted)
apache2   22516         www-data   19w      REG               0,17            0     862422 /run/apache2/wsgi.22506.0.1.lock (deleted)
apache2   22516 22546   www-data   19w      REG               0,17            0     862422 /run/apache2/wsgi.22506.0.1.lock (deleted)
apache2   22516 22547   www-data   19w      REG               0,17            0     862422 /run/apache2/wsgi.22506.0.1.lock (deleted)
</pre>

**Comment by GrahamDumpleton** [comment]
What version of mod_wsgi are you using? Define better what you mean by 'WSGI stops to work'? Are you saying it permanently doesn't work and you have to stop/start Apache, or that you see a transient error but then works?

The logged messages are normal and are a corner case that occurs when performing an Apache graceful restart.

What occurs is that Apache doesn't give a grace period to the mod_wsgi daemon processes, but does for its own child worker processes which are proxying the request to the mod_wsgi daemon processes. If the Apache child worker processes were handling a keep alive connection and a subsequent request came over the same connection, it would try and connect to the mod_wsgi daemon process group on the old socket path name and you see that error. The next generation of the mod_wsgi daemon processes use a new socket path to ensure it doesn't handle requests processed by Apache child worker processes in the prior configuration. There isn't anything that can be done about it and it should be a rare event. It would not be the source of any problems.

BTW, the absolute minimum mod_wsgi version I would recommend at this time is 4.4.12. Many Linux distributions ship ancient out of date versions, which they do not support and nor do I. So ensure you are using a recent version.

**Comment by OGAWAHirofumi** [comment]
Graham Dumpleton <notifications@github.com> writes:

> What version of mod_wsgi are you using? Define better what you mean by
> 'WSGI stops to work'?

Like a subject, I tested mod-wsgi 4.4.22 version.

> Are you saying it permanently doesn't work and you have to stop/start
> Apache, or that you see a transient error but then works?

I re-tested this. And I noticed restarting browser (firefox), also fix
issue too, additionally apache restart.

> The logged messages are normal and are a corner case that occurs when
> performing an Apache graceful restart.
>
> What occurs is that Apache doesn't give a grace period to the mod_wsgi
> daemon processes, but does for its own child worker processes which
> are proxying the request to the mod_wsgi daemon processes. If the
> Apache child worker processes were handling a keep alive connection
> and a subsequent request came over the same connection, it would try
> and connect to the mod_wsgi daemon process group on the old socket
> path name and you see that error. The next generation of the mod_wsgi
> daemon processes use a new socket path to ensure it doesn't handle
> requests processed by Apache child worker processes in the prior
> configuration. There isn't anything that can be done about it and it
> should be a rare event. It would not be the source of any problems.

I'm using mod-wsgi for

	https://docs.services.mozilla.com/howtos/run-sync-1.5.html

this process. I'm not sure though, however, firefox may keep connection
for long time. (Not testing how long stay wrong state.)
-- 
OGAWA Hirofumi <hirofumi@mail.parknet.co.jp>

**Comment by OGAWAHirofumi** [comment]
> Define better what you mean by 'WSGI stops to work'?

Missed to answer this. I meant, GET method to url returns http state 503.

**Comment by GrahamDumpleton** [comment]
What was the reason for doing the 'apachectl graceful'?

If you aren't changing the Apache configuration, you may be better off signalling the mod_wsgi daemon process directly.

To do that, ensure you are using the ``display-name=%{GROUP}`` option to ``WSGIDaemonProcess``. That will mean that in ``ps`` output which are the mod_wsgi daemon processes should be clearer. Then send them a ``SIGUSR1`` signal.

That will restart them without restarting the Apache child worker processes, so you will not have an issue with socket name changing.

If you want for this restart to be somewhat graceful, set ``graceful-timeout`` option on ``WSGIDaemonProcess`` directive to how long prepared for mod_wsgi process to try and complete any current requests (while still accepting new ones), before going into normal shutdown and restart process.

**Comment by OGAWAHirofumi** [comment]
Graham Dumpleton <notifications@github.com> writes:

> What was the reason for doing the 'apachectl graceful'?

debian apache2 package installs a logrotate config, and it uses
'apachectl graceful' after log rotation.

So, actually, it needs "graceful restart" to apache, but not wsgi.
-- 
OGAWA Hirofumi <hirofumi@mail.parknet.co.jp>

**Comment by OGAWAHirofumi** [comment]
Just FYI, daily "graceful restart" was to regenerate TLS session ticket.

**Comment by GrahamDumpleton** [comment]
Closing this at this point, assuming is the known issue with keep alive connections which nothing can be done about due to how Apache manages other processes besides its own child worker processes.
