### ISSUE TITLE
Default directory for eggs should be owned by given user/group

### ISSUE THREAD

**Issue by bkabrda** [GrahamDumpleton/mod_wsgi#125]
When I run `mod_wsgi-express` as e.g. root with `--user` and/or `--group` arguments, the `python-eggs` directory is owned by `root:root`, so the given user can't write there. I think the `python-eggs` directory should be owned by given user/root by default (or there should be argument for that).

**Comment by GrahamDumpleton** [comment]
Yes. Hadn't thought of that. May be some other directories which the script creates which would have the same issue.

In the interim can only suggest you create the directory first with the correct permissions.

**Comment by GrahamDumpleton** [comment]
Fixed in commit 35734ff6baa9ee21c0fe8bc72ba62b323e4f1461 for 4.5.8. Sorry for delay.
