### ISSUE TITLE
Problem loading additional modules on Fedora

### ISSUE THREAD

**Issue by bkabrda** [GrahamDumpleton/mod_wsgi#126]
So I'm trying to load mod_auth_gssapi using the `--include-file /some/path/gssapi.conf` directive. I'm having a problem loading the module:
- The generated `httpd.conf` assumes that modules are directly under `${MOD_WSGI_MODULES_DIRECTORY}`, e.g. `${MOD_WSGI_MODULES_DIRECTORY}/mod_foo.so`
- The `LoadModule` directives in e.g. `/etc/httpd/conf.modules.d/00-base.conf` all use `modules/` prefix, so they end up being searched for under `${MOD_WSGI_MODULES_DIRECTORY}/modules/mod_foo.so` => they're not found (the path ends up being sth. like `/usr/lib64/httpd/modules/modules/mod_foo.so` - contains double `modules/` entry).

This makes it impossible to use httpd's builtin config files on Fedora, since I end up with one extra `modules` in the path for modules referenced from Fedora's httpd conf files. Not sure how other distros approach it and not sure how this could be fixed (can one provide multiple module search paths for httpd?); it should be at least documented, IMHO.

**Comment by bkabrda** [comment]
Hmm, I guess my report was inaccurate, the `${MOD_WSGI_MODULES_DIRECTORY}` only gets used explicitly in generated `httpd.conf` and doesn't influence other files. I'll have to investigate this more thoroughly tomorrow and I'll update this issue when I have better explanation why things don't work.

**Comment by GrahamDumpleton** [comment]
The intent was that ``${MOD_WSGI_MODULES_DIRECTORY}`` could be used in config snippet file included by ``--include-file``, but it wasn't really expected that you would use it with config files in the existing Apache configuration.

Because the config file is included at the end, and the structure of the generated configuration is quite specific, depending on what you want to do it may not be easy to make use of certain other Apache modules.

What exactly are you trying to do?

**Comment by bkabrda** [comment]
So I'm trying to setup mod_wsgi to use mod_auth_gssapi [1]. This is the config that I wanted to pass to `--include-file` argument of mod_wsgi-express:

```
LoadModule auth_gssapi_module '${MOD_WSGI_MODULES_DIRECTORY}/mod_auth_gssapi.so'

<Location /some/url>
    AuthType GSSAPI
    AuthName "GSSAPI Single Sign On Login"
    GssapiCredStore keytab:/etc/httpd.keytab
    Require valid-user
</Location>
```

The problem with that is that mod_auth_gssapi requires mod_authz_user, which is not added to the default `httpd.conf` generated by mod_wsgi-express. Then I found out that on Fedora mod_authz_user is included in `/etc/httpd/conf.modules.d/00-base.conf`. Not being httpd expert, I thought that this file is included in default apache installation for reason and I thought that instead of hand-including some subset of it I would just include that whole file. Obviously, that didn't work because the file doesn't use the `${MOD_WSGI_MODULES_DIRECTORY}`, so including it failed.

So I had to modify the above config by adding `LoadModule authz_user_module '${MOD_WSGI_MODULES_DIRECTORY}/mod_authz_user.so'` to the top, which seems to work. So I see 2 potential issues here:
- `/etc/httpd/conf.modules.d/00-base.conf` is ignored - I'm not sure if that's actually a problem or not. Someone who maintains apache in my distro decided to include it and load all the modules inside it, so as a non-expert user I want to do the same.
- Even if loading that conf file by default is not necessary, it'd be great to be able to load it. The developer experience of "try to run while loading this module... ok, it fails and says it requires that one; add that one and try again" is not optimal. I guess the reason is mostly that (really guessing here) modules distributed separately presume that modules from standard apache installation will be loaded automatically and so they don't even care to document list of modules that they need (but that may also be a failure of mod_auth_gssapi documentation, not sure).

[1] https://github.com/modauthgssapi/mod_auth_gssapi

**Comment by GrahamDumpleton** [comment]
Going to close this as not sure anything can do. Is not the intent that one would mix use of main system Apache configuration with mod_wsgi-express. It is also not even intended that mod_wsgi-express replace everything that you can do in a main Apache, just provide support for the main thing that Python developers need. For more complicated requirements, intent is to use main Apache and traditional way of using mod_wsgi.
