### ISSUE TITLE
Import Error: cannot import name _compare_digest in deploying flask API with anaconda python on apache2 + mod_wsgi

### ISSUE THREAD

**Issue by awhitesong** [GrahamDumpleton/mod_wsgi#127]
I am trying to deploy the flask api on apache2 server with anaconda python and mod_wsgi and facing many problems. My mod_wsgi is compiled from source with anaconda's python (setup.py) but everytime my server on browser shows error 500. In the logs `Import Error: cannot import name _compare_digest` seems to be causing the problem. 

The error log

```
[Sat Apr 02 02:23:40.700719 2016] [wsgi:error] [pid 25581:tid 140329290245888] [client xx.xx.xx.xx:60400]     import hmac, referer: http://ec2-xx-xx-xx-xx.xx-xx-xx.compute.amazonaws.com 
[Sat Apr 02 02:23:40.700727 2016] [wsgi:error] [pid 25581:tid 140329290245888] [client xx.xx.xx.xx:60400]   File "/home/ubuntu/anaconda2/lib/python2.7/hmac.py", line 8, in <module>,     referer: http://ec2-xx-xx-xx-xx.xx-xx-xx.compute.amazonaws.com
[Sat Apr 02 02:23:40.700740 2016] [wsgi:error] [pid 25581:tid 140329290245888] [client xx.xx.xx.xx:60400]     from operator import _compare_digest as compare_digest, referer: referer: http://ec2-xx-xx-xx-xx.xx-xx-xx.compute.amazonaws.com
[Sat Apr 02 02:23:40.700760 2016] [wsgi:error] [pid 25581:tid 140329290245888] [client xx.xx.xx.xx:60400] ImportError: cannot import name _compare_digest, referer: http://ec2-xx-xx-xx-xx.xx-xx-xx.compute.amazonaws.com
```

System info:
1. `lsb_release -a`
   
   ```
   Distributor ID: Ubuntu
   Description:    Ubuntu 14.04.4 LTS
   Release:        14.04
   Codename:       trusty
   ```
2.  Anaconda has python version 2.7.11 in `/home/ubuntu/anaconda2/bin` and system has python 2.7.6 in /usr/bin/

Things i've done:
1. First I purge removed `libapache2-mod-wsgi` which might cause conflicting python problems (are there any other system packages?) and then i installed mod_wsgi from source with anaconda's python. (`python setup.py install`)
2. After that, I created `wsgi.load` myself in `/etc/apache2/mods-available` which includes 
   
   ```
   LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
   ```
3. I ran `mod_wsgi-express install module`  which gave 
   
   ```
   LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi-py27.so
   WSGIPythonHome /home/ubuntu/anaconda2
   ```
   
   So my `/usr/lib/apache2/modules` also has `mod_wsgi-py27.so` along with `mod_wsgi.so` but i've included the latter one in `LoadModule`
4. I DON'T have any `mod_python` or or `python.conf` installed for any conflicts. (not sure here where i'll see `python.conf`. Also should i install these?)  
5. `wsgi.conf` includes the suitable `WSGIPythonHome` and `WSGIPythonPath`
   
   ```
   <IfModule mod_wsgi.c>
       WSGIPythonHome /home/ubuntu/anaconda2
       WSGIPythonPath /home/ubuntu/anaconda2/lib/python2.7/site-packages
   </IfModule>
   ```
6. My `default.conf` file is 
   
   <VirtualHost *:80>
       # The ServerName directive sets the request scheme, hostname and port that
       # the server uses to identify itself. This is used when creating
       # redirection URLs. In the context of virtual hosts, the ServerName
       # specifies what hostname must appear in the request's Host: header to
       # match this virtual host. For the default virtual host (this file) this
       # value is not decisive as it is used as a last resort host regardless.
       # However, you must set it for any further virtual host explicitly.
       #ServerName www.example.com
   
   ```
   ServerAdmin webmaster@localhost
   DocumentRoot /var/www/html
   WSGIDaemonProcess brands threads=5 
   WSGIScriptAlias / /var/www/html/brands/apirest.wsgi
   
   <Directory /var/www/brands>
           WSGIProcessGroup apirest
           WSGIApplicationGroup %{GLOBAL}
           Order deny,allow
           Allow from all
   </Directory>
   
   
   # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
   # error, crit, alert, emerg.
   # It is also possible to configure the loglevel for particular
   # modules, e.g.
   #LogLevel info ssl:warn
   
   ErrorLog ${APACHE_LOG_DIR}/error.log
   CustomLog ${APACHE_LOG......
   ```
7. Finally, my `apirest.wsgi` file is 
   
   ```
   import sys
   sys.path.insert(0, '/var/www/html/brands')
   from apirest import app as application
   ```

Please tell how should i be resolving this. What could be the issue with `mod_wsgi` for detecting anaconda's python? Btw anaconda's python has `_compare_digest`. I can import it separately. A lot of people online are having the same problem but there isn't any concrete solution anywhere to this. Thanks.

**Comment by GrahamDumpleton** [comment]
How did ``/usr/lib/apache2/modules/mod_wsgi.so`` get there? Running ``python setup.py install`` alone doesn't copy it there.

What do you get when you run:

```
ldd /usr/lib/apache2/modules/mod_wsgi.so
```

From what I have seen in the past, Anaconda Python does some stuff which breaks using it in embedded systems. I am not even sure it works at all. Some people say it works for them, but other say it doesn't.

**Comment by awhitesong** [comment]
Yes i was going to write mention this also. I'm not sure how `/usr/lib/apache2/modules/mod_wsgi.so` was there. I assumed throughout that `python setup.py install` created it. 
Btw i was going to mention ldd results as well.

1. For `ldd /usr/lib/apache2/modules/mod_wsgi-py27.so` it gives 

	    linux-vdso.so.1 =>  (0x00007ffdee9db000)
	    libpython2.7.so.1.0 => /home/ubuntu/anaconda2/lib/libpython2.7.so.1.0 (0x00007fc5e47b0000)
	    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc5e4592000)
	    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc5e41cd000)
	    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc5e3fc9000)
	    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fc5e3dc6000)
	    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc5e3ac0000)
	    /lib64/ld-linux-x86-64.so.2 (0x00007fc5e4dcc000)

2. With `ldd /usr/lib/apache2/modules/mod_wsgi.so` it gives

	    linux-vdso.so.1 =>  (0x00007ffcbd6ea000)
	    libpython2.7.so.1.0 => /home/ubuntu/anaconda2/lib/libpython2.7.so.1.0 (0x00007f9674218000)
	    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9673ffa000)
	    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9673c35000)
	    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9673a31000)
	    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f967382e000)
	    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9673528000)
	    /lib64/ld-linux-x86-64.so.2 (0x00007f9674835000)


I can see anaconda's python (`libpython2.7.so.1.0 => /home/ubuntu/anaconda2/lib/libpython2.7.so.1.0 (0x00007fc5e47b0000)`  linked with `mod_wsgi-py27.so` above. So at first I also tried using `mod_wsgi-py27.so` instead of `mod_wsgi.so` in `LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi-py27.so` but its again showing these errors:


    Traceback (most recent call last):
      File "/usr/lib/python2.7/site.py", line 563, in <module>main()
      File "/usr/lib/python2.7/site.py", line 545, in main
        known_paths = addusersitepackages(known_paths)
      File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
        user_site = getusersitepackages()
      File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
        user_base = getuserbase() # this will also set USER_BASE
      File "/usr/lib/python2.7/site.py", line 237, in getuserbase
        USER_BASE = get_config_var('userbase')
      File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
        return get_config_vars().get(name)
      File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
        _init_posix(_CONFIG_VARS)
      File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
        from _sysconfigdata import build_time_vars
      File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
        from _sysconfigdata_nd import *
    ImportError: No module named _sysconfigdata_nd

**Comment by GrahamDumpleton** [comment]
If you had truly removed the system packaged mod_wsgi, then the only way mod_wsgi.so would have got into the Apache modules directory, is if you had run:

```
mod_wsgi-express install-module
```

after running:

```
python setup.py install
```

Don't do that though, instead try running:

```
mod_wsgi-express module-location
```

This should output the full path to the mod_wsgi.so file which is part of the Python Anaconda installation.

In the Apache configuration, instead of using:

```
LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi-py27.so
```

replace the path of mod_wsgi.so file with the path ``module-location`` gave you.

The ``WSGIPythonHome`` directory should then be set to what ``sys.prefix`` gives when import ``sys`` and output ``sys.prefix`` from Anaconda interpreter.

You do not need ``WSGIPythonPath`` for ``site-packages``.

Also try setting:

```
WSGIRestrictEmbedded On
```

This stops interpreter being initialised in Apache child workers, which isn't necessary if using daemon mode.

Then for the daemon process, for good measure use:

```
WSGIDaemonProcess brands threads=5 python-home=/home/ubuntu/anaconda2
```

You should never see any Python exception which mentions ``/usr/lib/python2.7``. That you are tells me that Anaconda Python is not finding correct Python installation at run time if the mod_wsgi.so is truly linked against it. This has been the problem with it and why it breaks embedded systems. Is not honouring ``WSGIPythonHome`` and how mod_wsgi sets the runtime location.

As to ``ldd``, it could be lying if Anaconda setup told you to set ``LD_LIBRARY_PATH``. When you run ``ldd`` try:

```
LD_LIBRARY_PATH='' ldd /some/path/mod_wsgi.so
```

where the path is what ``module-location`` gave. That or do ``unset LD_LIBRARY_PATH`` in shell before running ``ldd``.

If that doesn't resolve to Anaconda, will need to reinstall mod_wsgi again and force retention of library location in it. Lets see what you get for above ``ldd`` first.

**Comment by awhitesong** [comment]
1. I followed exactly [these](https://www.howtoinstall.co/en/ubuntu/trusty/main/libapache2-mod-wsgi/remove) commands to remove `libapache2-mod-wsgi` and i don't have any `libapache2-mod-python` package installed. I guess this should be enough or is there a requirement to remove other packages as well? And what do you mean by `force retention of library location in it`? 

2. Running `mod_wsgi-express install-module` created only this --> `/usr/lib/apache2/modules/mod_wsgi-py27.so` where `/usr/lib/apache2/modules/mod_wsgi.so` was already present before. 

3. I tried running `mod_wsgi-express module-location` and got this:

        /home/ubuntu/anaconda2/lib/python2.7/site-packages/mod_wsgi-4.4.23-py2.7-linux-x86_64.egg/mod_wsgi/server/mod_wsgi-py27.so

    Now,
 `unset LD_LIBRARY_PATH` 
and

 1. Doing `ldd /home/ubuntu/anaconda2/lib/python2.7/site-packages/mod_wsgi-4.4.23-py2.7-linux-x86_64.egg/mod_wsgi/server/mod_wsgi-py27.so` 
gave me this `(anaconda's python)`

       	    linux-vdso.so.1 =>  (0x00007ffd2a909000)
	        libpython2.7.so.1.0 => /home/ubuntu/anaconda2/lib/libpython2.7.so.1.0 (0x00007fadd1f99000)
	        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fadd1d7b000)
	        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fadd19b6000)
	        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fadd17b2000)
	        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fadd15af000)
	        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fadd12a9000)
	        /lib64/ld-linux-x86-64.so.2 (0x00007fadd25b5000)
  2. After clearing LD_LIBRARY_PATH and Doing ` ldd /usr/lib/apache2/modules/mod_wsgi.so` (which i was using in LoadModule) is showing that `mod_wsgi.so` ISN'T linked with anaconda's python. 

	        linux-vdso.so.1 =>  (0x00007ffe5fb7e000)
	        libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fdfad93b000)
	        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdfad71d000)
	        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdfad358000)
	        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdfad13f000)
	        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdfacf3b000)
	        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fdfacd38000)
	        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdfaca32000)
	        /lib64/ld-linux-x86-64.so.2 (0x00007fdfae0d5000)

  3. `ldd /usr/lib/apache2/modules/mod_wsgi-py27.so` output is the same as (i)

4. So Finally after setting `LoadModule wsgi_module /home/ubuntu/anaconda2/lib/python2.7/site-packages/mod_wsgi-4.4.23-py2.7-linux-x86_64.egg/mod_wsgi/server/mod_wsgi-py27.so` 
and 
`WSGIDaemonProcess brands threads=5 python-home=/home/ubuntu/anaconda2` (sys.prefix is the same)
with this conf file
        
        <IfModule mod_wsgi.c>
            WSGIPythonHome /home/ubuntu/anaconda2
            WSGIPythonPath /home/ubuntu/anaconda2/lib/python2.7/site-packages
            WSGIRestrictEmbedded On
        </IfModule>

    I am getting the same error `No module named _sysconfigdata_nd` i was getting with `LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi-py27.so`

        Traceback (most recent call last):
          File "/usr/lib/python2.7/site.py", line 563, in <module>main()
          File "/usr/lib/python2.7/site.py", line 545, in main
            known_paths = addusersitepackages(known_paths)
          File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
            user_site = getusersitepackages()
          File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
            user_base = getuserbase() # this will also set USER_BASE
          File "/usr/lib/python2.7/site.py", line 237, in getuserbase
            USER_BASE = get_config_var('userbase')
          File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
            return get_config_vars().get(name)
          File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
            _init_posix(_CONFIG_VARS)
          File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
            from _sysconfigdata import build_time_vars
          File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
            from _sysconfigdata_nd import *
        ImportError: No module named _sysconfigdata_nd

I don't know why even after linking with anaconda's python (`libpython2.7.so.1.0 => /home/ubuntu/anaconda2/lib/libpython2.7.so.1.0 (0x00007fadd1f99000)` its looking at `/usr/lib/python2.7/`.  The anaconda doesn't have ` _sysconfigdata_nd` module though but the system python (`/usr/bin/`) does have it. So maybe mod_wsgi looks for system's python for the module if it doesn't find in anaconda? What should be the fix now, reinstallation?

**EDIT**: 
Also finally, before reinstalling `mod_wsgi` from source again through:

    ./configure --with-python=/home/ubuntu/anaconda2/bin/python
    LD_RUN_PATH=/home/ubuntu/anaconda2/lib make 
    LD_RUN_PATH=/home/ubuntu/anaconda2/lib make install

I tried to hack this `No module named _sysconfigdata_nd` problem. This is the [bug  in the ubuntu package](http://stackoverflow.com/questions/15608236/eclipse-and-google-app-engine-importerror-no-module-named-sysconfigdata-nd-u).

So after following the above link `no module _sysconfigdata_nd` error has gone but now i'm getting this error `Embedded mode of mod_wsgi disabled by runtime configuration`

    [Sat Apr 02 07:05:11.065612 2016] [wsgi:error] [pid 4111:tid 139629353219840] [client xx.xx.xx.xx:35292] Embedded mode of mod_wsgi disabled by runtime configuration: /var/www/html/brands/apirest.wsgi
    [Sat Apr 02 07:05:11.455348 2016] [wsgi:error] [pid 4112:tid 139629386790656] [client xx.xx.xx.xx:35292] Embedded mode of mod_wsgi disabled by runtime configuration: /var/www/html/brands/apirest.wsgi, referer: http://ec2-xx-xx-xx-xx.xx-xx-xx.compute.amazonaws.com 
    [Sat Apr 02 07:05:13.770239 2016] [wsgi:error] [pid 4111:tid 139629344827136] [client xx.xx.xx.xx:35296] Embedded mode of mod_wsgi disabled by runtime configuration: /var/www/html/brands/apirest.wsgi
    [Sat Apr 02 07:05:14.163638 2016] [wsgi:error] [pid 4111:tid 139629336434432] [client  xx.xx.xx.xx:35292] Embedded mode of mod_wsgi disabled by runtime configuration: /var/www/html/brands/apirest.wsgi, referer: http://ec2-xx-xx-xx-xx.xx-xx-xx.compute.amazonaws.com 

How should this be resolved? Thanks.

**Comment by GrahamDumpleton** [comment]
The forcing of the location I am talking about is using the ``LD_RUN_PATH`` method you used.

You are actually missing:

```
WSGIProcessGroup brands
```

Didn't notice that before. That is why got the error about restricted mode, you weren't actually delegating the application to run in daemon mode properly.

As I said before, you should not need ``WSGIPythonPath`` directive as ``site-packages`` should be found automatically.

If you want to use a Python virtual environment, use the ``python-home`` option to ``WSGIDaemonProcess`` and set to ``sys.prefix`` of that installation.

Anyway, you seem to be getting closer. Ensure you see the ``WSGIProcessGroup`` directive.

**Comment by awhitesong** [comment]
Where should i be including `WSGIProcessGroup brands` ? including it in `default.conf` `<Directory>` is producing the same errors. Should this go under `wsgi.conf`? Being really careful here.

**Comment by GrahamDumpleton** [comment]
Right after the ``WSGIDaemonProcess`` directive would be best place.

**Comment by awhitesong** [comment]
Now i'm getting 
    [Sat Apr 02 10:10:47.263085 2016] [wsgi:error] [pid 9621:tid 139747456120576] [remote     xx.xx.xx.xx:57221]     import operator
    [Sat Apr 02 10:10:47.263112 2016] [wsgi:error] [pid 9621:tid 139747456120576] [remote xx.xx.xx.xx:57221] ImportError: No module named operator
.. 
and other import errors. I guess mod_wsgi is not able to detect anaconda's `PYTHONHOME` even after mentioning with `WSGIDaemonProcess` and `.config`s . Only the packages that i include in python-path are detected i.e `PYTHONPATH` work fine but not `PYTHONHOME`. One fix might be to manually include all necessary directories in `python-path.`

I will try for the last time reinstallling from source. For that do i have to remove current installation? (as i have already tried doing `LD_RUN_PATH=/home/ubuntu/anaconda2/lib make install` on current installation and it didn't make any difference). 

Also should i install mod_python from source with anaconda's python? 

And again are the methods given [here](https://www.howtoinstall.co/en/ubuntu/trusty/main/libapache2-mod-wsgi/remove) complete to remove `libapache2-mod-wsgi` and other system packages? Or what else could be done? Thanks.

**Comment by GrahamDumpleton** [comment]
Use a WSGI hello world script. Not your full on application.

At the start of the script, print out the value of ``sys.prefix`` and ``sys.path``. Supply those.

Never install mod_python. It is totally unrelated and a dead project.

Ignore the system packaged mod_wsgi and do not install it again now you are installing mod_wsgi from source code.

Do not try and construct ``sys.path`` yourself. That is going to cause more problems than good.

**Comment by awhitesong** [comment]
Here are the sys.path and sys.prefix returned from a simple application ( after setting every path to anaconda's ).

    {

    "path" : "[ ' ', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']", 

     "prefix": "/usr"

    }

For now i'm just copying sys.path's value from anaconda's python client and adding it to sys.path in the application's brands.wsgi . This seems to work since all the anaconda's pythonpaths are included in application's sys.path now but yeah, this might cause problems later.

**Comment by GrahamDumpleton** [comment]
So Anaconda is ignoring what mod_wsgi says then about where Anaconda is installed.

Does running:

```
mod_wsgi-express start-server hello.wsgi --log-to-terminal
```

where ``hello.wsgi`` is path to the hello world WSGI file print ``sys.prefix`` and ``sys.path`` yield wrong results as well.

When running, hit the URL ``http://localhost:8000``.

**Comment by awhitesong** [comment]
No, it seems running in the localhost is giving the correct paths.

    {

      "path": "['/var/www/html/hello', '/var/www/html/hello', '/home/ubuntu/anaconda2/lib/python2.7/site-    packages/mod_wsgi-4.4.23-py2.7-linux-x86_64.egg', '/home/ubuntu/deepdetect/clients/python', '/home/ubuntu/anaconda2/lib/python27.zip', '/home/ubuntu/anaconda2/lib/python2.7', '/home/ubuntu/anaconda2/lib/python2.7/plat-linux2', '/home/ubuntu/anaconda2/lib/python2.7/lib-tk', '/home/ubuntu/anaconda2/lib/python2.7/lib-old', '/home/ubuntu/anaconda2/lib/python2.7/lib-dynload', '/home/ubuntu/anaconda2/lib/python2.7/site-packages', '/home/ubuntu/anaconda2/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg', '/home/ubuntu/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg']", 

      "prefix": "/home/ubuntu/anaconda2"

    }

**Comment by GrahamDumpleton** [comment]
If only using it for development or an adhoc site, you could always just use ``mod_wsgi-express`` then.

If really need to run on port ``80`` of the system, it is possible to disable the main system Apache and then use ``mod_wsgi-express`` in its place. There is a bit about doing this on the PyPi page for ``mod_wsgi``.

Don't really understand why Anaconda wouldn't do the correct thing if ``mod_wsgi-express`` works on command line. The issue may be that whatever changes they made, which broke embedding, meant that it instead relied on ``PATH`` being set such that Anaconda ``python`` executable is found first. This is one of the strategies Python uses, but it shouldn't override the technique mod_wsgi uses to set location using ``PYTHONHOME``.

You could always try modifying the system Apache start up scripts to set ``PATH`` in the environment so it includes the Anaconda ``bin`` directory.

**Comment by awhitesong** [comment]
Yeah. For alternatives, will try setting the `PATH` for anaconda through the Apache's startup scripts or see how `mod_wsgi` runs without Apache on port 80 as it seems `mod_wsgi` is able to get anaconda's paths on localhost.  For now, copying and adding the `sys.path` from anaconda python terminal to application's `sys.path` (in brands.wsgi) seems to work temporarily.

**Comment by GrahamDumpleton** [comment]
Closing this issue at this point. Some of the later work with mod_wsgi-express generating ``LoadFile`` directive and have people use mod_wsgi-express to bootstrap mod_wsgi in system Apache when using Anaconda Python may address this.
