### ISSUE TITLE
import theano server timeout

### ISSUE THREAD

**Issue by awhitesong** [GrahamDumpleton/mod_wsgi#128]
On deploying a flask app (containing theano for scientific calaulations) with apache2 + mod_wsgi, the line `import theano` creates a server timeout. And it works fine if I deleted the line importing theano.

By the way, if I test the website locally by simply running with python, It works fine even after importing the theano lib.

here's the error log:

    [Tue Apr 05 19:45:57.044392 2016] [core:notice] [pid 15606:tid 140448449443712] AH00094:   Command line: '/usr/sbin/apache2'
    [Tue Apr 05 19:50:59.766581 2016] [wsgi:error] [pid 16909:tid 140448347232000] [client xx.xx.xx.xxx:39886] Timeout when reading response headers from daemon process 'test':    /var/www/html/test/app.wsgi
    [Tue Apr 05 19:51:00.191099 2016] [wsgi:error] [pid 16908:tid 140448347232000] [client xx.xx.xx.xx:39888] Timeout when reading response headers from daemon process 'test': /var/www/html/test/app.wsgi

What could be the reasons and how could this be resolved?

**Comment by GrahamDumpleton** [comment]
Most likely the import of ``theaon`` is causing a deadlock resulting in the process hanging. This can occur where a Python package contains a C extension which has not been correctly implemented to work in Python sub interpreters.

Ensure that you are setting the directive:

```
WSGIApplicationGroup %{GLOBAL}
```

If you are running multiple web applications, make sure you are using daemon mode of mod_wsgi and are delegating each to a separate daemon process group, as some web applications do not like being commingled with others. That directive has the effect of forcing all applications in a process to run in the main interpreter, and thus why if have multiple applications you should use separate daemon processes for each so they aren't mixed.

For details on the deadlocking issue, see the documentation at:

* http://modwsgi.readthedocs.org/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

**Comment by GrahamDumpleton** [comment]
No further response. Closing.
