### ISSUE TITLE
Wsgi error ... ???

### ISSUE THREAD

**Issue by Ademir-Francisco-da-Silva** [GrahamDumpleton/mod_wsgi#130]
Hi,

Just take a look as follow ...

[Mon Apr 18 10:39:34.833599 2016] [wsgi:error] [pid 2032:tid 904] ERROR _ 2016-04-18 10:39:34,828 | base.* -> 2032 2672 -> Internal Server Error: /pt-br/artigos/ola-mae-estou-vivo/
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904] Traceback (most recent call last):
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\core\\handlers\\base.py", line 137, in get_response
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     response = response.render()
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\response.py", line 103, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     self.content = self.rendered_content
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\response.py", line 80, in rendered_content
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     content = template.render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\base.py", line 148, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return self._render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\test\\utils.py", line 88, in instrumented_test_render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return self.nodelist.render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\base.py", line 844, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     bit = self.render_node(node, context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\base.py", line 858, in render_node
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return node.render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\loader_tags.py", line 126, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return compiled_parent._render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\test\\utils.py", line 88, in instrumented_test_render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return self.nodelist.render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\base.py", line 844, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     bit = self.render_node(node, context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\base.py", line 858, in render_node
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return node.render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\loader_tags.py", line 65, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     result = block.nodelist.render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\base.py", line 844, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     bit = self.render_node(node, context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\template\\base.py", line 858, in render_node
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return node.render(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\contrib\\comments\\templatetags\\comments.py", line 76, in render
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     qs = self.get_queryset(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\contrib\\comments\\templatetags\\comments.py", line 81, in get_queryset
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     ctype, object_pk = self.get_target_ctype_pk(context)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\contrib\\comments\\templatetags\\comments.py", line 109, in get_target_ctype_pk
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     return ContentType.objects.get_for_model(obj), obj.pk
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\contrib\\contenttypes\\models.py", line 42, in get_for_model
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     opts = self._get_opts(model, for_concrete_model)
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]   File "C:\\Python27\\lib\\site-packages\\django-1.7.11-py2.7.egg\\django\\contrib\\contenttypes\\models.py", line 27, in _get_opts
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904]     model = model._meta.concrete_model
[Mon Apr 18 10:39:34.834599 2016] [wsgi:error] [pid 2032:tid 904] AttributeError: 'NoneType' object has no attribute '_meta'

Futher information ...
Windows 8.1_win64
Python 2.7.11_win64
Django 1.7.11_win64
Mod_wsgi 4.4.12_win64 ( mod_wsgi-py27-VC9.so )
Apache modules 2.4.18_win64 - VC14

**Comment by GrahamDumpleton** [comment]
You would be better to ask this on Django mailing list or IRC channel. I can't help you with Django specific problems.

My understanding though is that these sorts of issues arise when you have import cycles within modules for your model classes. It is not a specific problem with mod_wsgi, but is generally seen when you use it because the way that the Django development server works means that things get imported in different order. Thus may not occur with Django development server, but will occur with production WSGI servers.

**Comment by Ademir-Francisco-da-Silva** [comment]
Hmmmmm ..., OK. Thanks anyway ...

Ademir

Em 18/04/2016 20:02, Graham Dumpleton escreveu:
>
> You would be better to ask this on Django mailing list or IRC channel. 
> I can't help you with Django specific problems.
>
> My understanding though is that these sorts of issues arise when you 
> have import cycles within modules for your model classes. It is not a 
> specific problem with mod_wsgi, but is generally seen when you use it 
> because the way that the Django development server works means that 
> things get imported in different order. Thus may not occur with Django 
> development server, but will occur with production WSGI servers.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/GrahamDumpleton/mod_wsgi/issues/130#issuecomment-211621381>
>


-- 
Ademir Francisco da Silva
Skype  ...: Ademir_Francisco_da_Silva
[ CMC ] God will do me justice



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus
