### ISSUE TITLE
Apache2.4 compiled with VC14 and Python35

### ISSUE THREAD

**Issue by bryont** [GrahamDumpleton/mod_wsgi#133]
Is there a time frame when there will be precompiled binaries for Apache24 compiled with VC14 and Python35?

Or is it possible to Edit the source files to created a mod_wsgi-develop\win32\ap24py35-win64-VC14

file that can compile this?

**Comment by GrahamDumpleton** [comment]
It is highly unlikely I will be providing newer mod_wsgi binaries for Windows myself. It is just too much trouble for me to compile them. You can get newer binaries from:

* http://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

The ``.whl`` files are actually ZIP files and so can be unpacked as that.
