### ISSUE TITLE
Question: How to configure it with apache 2.4

### ISSUE THREAD

**Issue by jaroslawziolkowski** [GrahamDumpleton/mod_wsgi#135]
Hi,
I'm using Debian 8 and apache  2.4 after download package and run confiure but also 

```
APXS=.vx/bin/mod_wsgi-apxs pip install mod_wsgi

```

what I found in other issuse here I have same error that I need to 

> missing Apache httpd server packages.' % APXS

unfortunaltelly install apache2 dev package on debian is impossible for me becaise exists onlu package 2.2 
when I try do it I see error requires jes apache2-common 2.2 and installed is 2.4. 

I have no idea. Also I couldn't found any method to compile this extension.

I know, that it isn't perfect match to this module but I'd like install this one and I can't find any other help.

Thanks in advance.

**Comment by GrahamDumpleton** [comment]
What was the actual name of the 'dev' package you tried to install?

For Apache 2.4 it should be ``apache2-dev``, not older ``apache2-threaded-dev``.

* https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=apache2-dev

Either way you shouldn't be setting ``APXS`` as you are when doing ``pip install``.

**Comment by jaroslawziolkowski** [comment]
@GrahamDumpleton thanks, you're right, I had problem with my repositories list.

Doeas it normal that wien I set a2enmod wsgi then apache is restarted ok but any earlier installed pages with php not works?
Without configuration any python virtual host/

**Comment by GrahamDumpleton** [comment]
Not sure I understand the question about PHP. Enabling mod_wsgi shouldn't interfere with it. If you had existing Apache configuration snippets for PHP they should still apply unless you add mod_wsgi directives which override them in some way for a specific virtual host.

**Comment by jaroslawziolkowski** [comment]
@GrahamDumpleton no I don't use mod_wsgi directives. I have php websittes in  many configuration files. When I set a2enmod wsgi I can't see any php page on my apache but also apache don't show any errors when it start.

When I revert a2dismod wsgi pages works correct again. Very weird.

**Comment by GrahamDumpleton** [comment]
What is the ``wsgi.load`` file of the ``mods-available`` directory in the Apache configuration area?

**Comment by jaroslawziolkowski** [comment]
@GrahamDumpleton thanks for your answer
in 
/etc/apache2/mods-available/wsgi.load
is 
`LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so`

and in apache.conf
```
ServerName localhost

#ServerRoot "/etc/apache2"

PidFile ${APACHE_PID_FILE}

Timeout 300

KeepAlive On

MaxKeepAliveRequests 100

KeepAliveTimeout 5

<IfModule mpm_prefork_module>
    StartServers          5
    MinSpareServers       5
    MaxSpareServers      10
    MaxClients          150
    MaxRequestsPerChild   0
</IfModule>

<IfModule mpm_worker_module>
    StartServers          2
    MinSpareThreads      25
    MaxSpareThreads      75 
    ThreadLimit          64
    ThreadsPerChild      25
    MaxClients          150
    MaxRequestsPerChild   0
</IfModule>

<IfModule mpm_event_module>
    StartServers          2
    MinSpareThreads      25
    MaxSpareThreads      75 
    ThreadLimit          64
    ThreadsPerChild      25
    MaxClients          150
    MaxRequestsPerChild   0
</IfModule>


User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

AccessFileName .htaccess
<Files ~ "^\.ht">
    Order allow,deny
    Deny from all
    Satisfy all
</Files>

DefaultType None


HostnameLookups Off

ErrorLog ${APACHE_LOG_DIR}/error.log

LogLevel warn


Include mods-enabled/*.load
Include mods-enabled/*.conf


Include ports.conf

LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

Include conf.d/


Include sites-enabled/*

```

and example virtual host for php in /etc.apache2/sites-available (enabled)

```
<VirtualHost *:80>
  ServerName sub.example.com 
  ServerAdmin email@example.com
  DocumentRoot /var/www/html/sub.example.com/public
 ServerAlias sub.example.com
  <Directory /var/www/html/sub.example.com/public>
<IfModule sapi_apache2.c>
        php_admin_flag engine on
    </IfModule>
    <IfModule mod_php5.c>
        php_admin_flag engine on
    </IfModule>
    Options Includes FollowSymLinks MultiViews
    AllowOverride All
    DirectoryIndex index.php index.html index.html5
  </Directory>
 
  ErrorLog ${APACHE_LOG_DIR}/example.com_error.log
  LogLevel warn
  CustomLog ${APACHE_LOG_DIR}/example.com_access.log combined
 
  ErrorDocument 404 /404/
 
  SetOutputFilter DEFLATE
  SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|ico|png)$ \ no-gzip dont-vary
  SetEnvIfNoCase Request_URI \.(?:exe|t?gz|zip|bz2|sit|rar)$ \no-gzip dont-vary
  SetEnvIfNoCase Request_URI \.pdf$ no-gzip dont-vary
   
  BrowserMatch ^Mozilla/4 gzip-only-text/html
  BrowserMatch ^Mozilla/4\.0[678] no-gzip
  BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
 
</VirtualHost>

```

Thanks in advance

**Comment by GrahamDumpleton** [comment]
Do you have any static files (non PHP) under the ``DocumentRoot`` directory? Can you access such static files at least?

**Comment by jaroslawziolkowski** [comment]
@GrahamDumpleton nope, it looks on apache not working, Apache is restart without any error information but after run comman apach2 I see warn log

<img width="1297" alt="zrzut ekranu 2016-05-23 o 04 06 21" src="https://cloud.githubusercontent.com/assets/6404533/15458537/c5ed9798-209b-11e6-8d81-c44807f6549b.png">

what is interesting with same apache configuration and without wsgi all works correctly without this warnings.

**Comment by GrahamDumpleton** [comment]
Those error messages indicate that Apache isn't being started correctly.

On some Linux hosts you cannot use ``apachectl`` and must use the system init scripts or systemd control script to stop/start Apache. This is important otherwise those environment variables it is mentioning in the errors will not be set.

How are you starting/stopping Apache?

**Comment by jaroslawziolkowski** [comment]
`service apache2 start/stop`
and
`apachectl start/stop`

I use Debian 8

**Comment by GrahamDumpleton** [comment]
I would avoid using ``apachectl`` directly. If you still see those warning messages when using ``service`` script then there is something not really right with your Apache installation.

Right now it is possible that because of using ``apachectl`` directly, you could have a rather confused Apache setup. I would shut Apache down and then use ``ps`` to make sure no ``httpd` or ``apache2`` processes (not sure what Debian calls them). Then use ``service`` to start up again and see if you still get those messages.

Other than that, still not sure why simply loading mod_wsgi would cause an issue. Only possibility can thinking of is that the ``-dev`` variant of the Apache package is not the correct version for the binary runtime and so the module isn't compatible. If that was a mix of 2.2 and 2.4, then module shouldn't even load. If the header files are for an older or newer version of the runtime there could be an issue because Apache 2.4 changed the ABI in an incompatible way at one point in a way that affected mod_wsgi. The mod_wsgi code has checks to try and cope with it, but still has potential for issue.

**Comment by jaroslawziolkowski** [comment]
I've been stopped apache by 

```service apache2 stop```
ps result was

```
PID TTY          TIME CMD
 4702 pts/0    00:00:00 bash
 5555 pts/0    00:00:00 ps
```

after ```service apache2 start``` was generate same errors.

In regards to packages. I use apache 2.4 and packgages to apache 2.4 because otherwise installation is impossible by dependencies errors.

**Comment by jaroslawziolkowski** [comment]
@GrahamDumpleton 
I removed all sites from my apache and run only with 000-defaulf.conf now in error.log I have

<img width="1282" alt="zrzut ekranu 2016-05-23 o 08 16 10" src="https://cloud.githubusercontent.com/assets/6404533/15461880/d87ed250-20be-11e6-9302-c71cb654563c.png">

it looks like python version problem. But I have the sam branch and higher then required. Have you any idea what is wrong?

**Comment by jaroslawziolkowski** [comment]
I sovle the problem, after remove all sites from apache and restart I watched errors. There was problem with mod_python conflict.

Thanks for your help @GrahamDumpleton

**Comment by GrahamDumpleton** [comment]
Yeah, mod_python shouldn't be used. Am not even sure there is a version which will work with Apache 2.4. More recent versions of mod_wsgi will actually detect if mod_python is loaded at the same time and tell you that you can't use mod_python at same time. The mod_python module doesn't do multithreading properly and causes all sorts of problems.

**Comment by jaroslawziolkowski** [comment]
@GrahamDumpleton but still I have problem. I see "welcome" django page but when I set own urls still I see only original django page. For others is 404

When I set manage.py runserver all urls works.

my wsgi.py

```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "epartio_com.settings")

application = get_wsgi_application()

```

and apache configuration vhost file

```

WSGIPythonPath /var/www/python/domain_com
<VirtualHost *:80>
  ServerName sub.domain_com

  WSGIScriptAlias / /var/www/python/sub.domain_com/myapp/wsgi.py
  WSGIDaemonProcess sub.domain_com python-path=/var/www/python/sub.domain_com:/usr/lib/python2.7/dist-packages
  WSGIProcessGroup sub.domain_com
  Alias /robots.txt /var/www/python/sub.domain_com/myapp/static/robots.txt
  Alias /favicon.ico /var/www/python/sub.domain_com/myapp/static/favicon.ico
  Alias /media/ /var/www/python/sub.domain_com/myapp/media/
  Alias /static/ /var/www/python/sub.domain_com/myapp/static/

  <Directory /var/www/python/sub.domain_com/myapp>
  <Files wsgi.py>
  Require all granted
  </Files>
  </Directory>

  </VirtualHost>
```

**Comment by GrahamDumpleton** [comment]
If you make changes to your code, automatic reloading doesn't occur. You need to either touch the WSGI script file ``/var/www/python/sub.domain_com/myapp/wsgi.py`` to update the time stamp on it, or restart Apache. Were you doing either of those things after making changes?

Read:

* http://modwsgi.readthedocs.io/en/develop/user-guides/reloading-source-code.html
