### ISSUE TITLE
How to compile this with VC14?

### ISSUE THREAD

**Issue by isaacramthal** [GrahamDumpleton/mod_wsgi#138]
I downloaded the source code for mod_wsgi but I am unable to find proper documentation for compiling the same with python version **3.5.1** and Visual Studio 2015 Update 1

Is there a proper guild which we can follow to compile the above for windows x64?

**Comment by GrahamDumpleton** [comment]
I am not really in a position to keep maintaining or providing win32 versions. You can though find win32 versions at:

* http://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

These are Python wheel files, if you don't know how to use those, rename extension to ``.zip`` and use and archiver tool to extract the ``.so`` file from it.

They are a little bit behind on versions at this time, but for win32 there are no differences you would benefit from so not missing out on anything.

**Comment by isaacramthal** [comment]
I think this should resolve my problem but currently i am running 64-bit apache.  Is there a python 3.5.1 for 64-bit?

**Comment by GrahamDumpleton** [comment]
Should be available from:

* https://www.python.org/downloads/release/python-351/

They are the x86-64 installers.

**Comment by nguillermin** [comment]
Sorry to hijack this thread, but can you not install those wheel files with pip instead?

**Comment by GrahamDumpleton** [comment]
I really don't understand why they have packaged them up as ``.whl`` files as you don't really want to be installing them into your Python installation. You only want the ``.so`` file the ``.whl`` package contains and that would normally be placed in the Apache modules directory. If you do manage to install them with ``pip``, you would then have to work out where it installed it and either then copy it over to the Apache modules directory by hand, or set up the ``LoadModule`` directive in Apache for the ``wsgi_module`` to refer to wherever ``pip`` installed it.

**Comment by GrahamDumpleton** [comment]
On Windows you can now use:

```
pip install mod_wsgi
mod_wsgi module-config
```

The output from the latter is what you should include in Apache configuration.

This has only been tested with Python 3.5, Apache 2.4 (installed in C:/Apache2.4) and Windows 10.

**Comment by VSG24** [comment]
It's worth noting that no longer do compiled mod_wsgi binaries come in `.so` format, they are now compiled to `.pyd`

**Comment by GrahamDumpleton** [comment]
Which is why when using the ``pip mod_wsgi`` install method you use:

```
mod_wsgi-express module-config
```

It will should output exactly what you need to put in the Apache config file, including force loading the correct Python DLL file.

**Comment by subhashdeshmukh** [comment]
I am getting following error when I add the output of 
`mod_wsgi-express module-config` command to Apache configuration file on windows.

> httpd.exe: Syntax error on line 181 of C:/Apache24/conf/httpd.conf: Cannot load
> c:/python27/lib/site-packages/mod_wsgi/server/mod_wsgiNone into server: The spec
> ified module could not be found.

**Comment by GrahamDumpleton** [comment]
Do you really need to use Python 2.7?

Try changing ``mod_wsgiNone`` to ``mod_wsgi.pyd``.

Often that doesn't work though as is really hard to find an Apache now that is compiled with VC9 compiler. The VC14+ compiled Apache binaries don't want to always work with VC9 compiled Python and mod_wsgi. It is much better to use Python 3.6, ensuring you also have VC14 compiler.

* https://wiki.python.org/moin/WindowsCompilers
