### ISSUE TITLE
Hosting Two Different Projects with mod_wsgi-express

### ISSUE THREAD

**Issue by naveenpanwar** [GrahamDumpleton/mod_wsgi#139]
I have been using mod_wsgi as an apache module and it was serving me well, but than when I needed to deploy the python3 project on the same server I cannot do so, and I uninstalled the mod_wsgi apache module and installed it as a python package using mod_wsgi-express and I setup the script to start on system startup.

But now I need to install one more project on the same setup, so unable to find any decent answers anywhere including IRC, I turned to this.

Any decent way of hosting two sites on the same apache server on the same port ( 80 ) using mod_wsgi-express.

**Comment by GrahamDumpleton** [comment]
You would need to set up the main system Apache to act as a proxy to proxy to the two distinct instances mod_wsgi-express instances running on distinct ports.

You can find a bit of an explanation about it in:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html

That talks about the mod_wsgi-express instances running inside Docker, but you can ignore the fact that Docker is being used and the set up of the main Apache and of mod_wsgi-express is essentially the same.

Look through that and see what you can work out and let me know of any specific questions.
