### ISSUE TITLE
Undocumented WSGIDaemonProcess options

### ISSUE THREAD

**Issue by bjamesv** [GrahamDumpleton/mod_wsgi#140]
A number of WSGIDaemonProcess configuration options are not included in the documentation (http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html).

Specifically there is no information on 'connect-timeout', 'socket-timeout' options (elsewhere referenced [here](https://groups.google.com/d/msg/modwsgi/Wm2u2OVZ-OE/cN8ZYQt54qUJ) & [here](https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/docs/release-notes/version-4.1.0.rst))

Info is missing from all of: develop, stable, latest, or master doc versions.

**Comment by bjamesv** [comment]
per https://github.com/GrahamDumpleton/mod_wsgi/blob/a8c8c73/src/server/__init__.py#L291
the options without documentation appear to be:
 * graceful-timeout ([per 4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html))
 * request-timeout ([per 4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html))
 * connect-timeout ([per 4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html))
 * socket-timeout ([per 4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html))
 * queue-timeout ([per 4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html))
 * listen-backlog ([per 4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html))
 * eviction-timeout ([per 4.4.7](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.4.7.html))
 * response-buffer-size ([per 4.4.7](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.4.7.html))
 * header-buffer-size ([per 4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html))
 * supplementary-groups ([4.1.0](http://modwsgi.readthedocs.io/en/develop/release-notes/version-4.1.0.html)),

**Comment by GrahamDumpleton** [comment]
Finally updated:

* http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html
