### ISSUE TITLE
mod_wsgi windows python 3.4 (32 bit) apache 2.4 (32bit)

### ISSUE THREAD

**Issue by nicholasrpb** [GrahamDumpleton/mod_wsgi#141]
Hi Graham,

I wanted to use windows mod_wsgi, however encounter this error:
Cannot load modules/mod_wsgi.so into server: %1 is not a valid Win32 application.

Windows OS version:
Windows Server 2012 R2 64 bit

Python version:
C:\Users\f10pcs\Desktop\venv>python
Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:24:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

Apache version:
C:\Apache24\bin>httpd -v
Server version: Apache/2.4.23 (Win32)
Server built:   Jul  9 2016 11:13:35

I am using VC2010 to compile from your win32 folder
i run below command:
c:\Users\f10pcs\Downloads\mod_wsgi-4.5.3\win32>nmake -f ap24py34-win32-VC10.mk
c:\Users\f10pcs\Downloads\mod_wsgi-4.5.3\win32>nmake -f ap24py34-win32-VC10.mk i
nstall

i get wsgi_memory.obj and rename this to mod_wsgi.so.

is this action of rename this wsgi_memory.obj to mod_wsgi.so wrong?

what is the correct item to generate mod_wsgi for my python combination?

**Comment by GrahamDumpleton** [comment]
Renaming files is wrong. Details about the makefiles are given in:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/win32/README.rst

but you are probably better off at this point using binaries from:

* http://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

If you don't know what to do with a ``.whl`` file, change the extension to ``.zip`` and use an archive tool to extract the mod_wsgi.so file from it.

**Comment by nicholasrpb** [comment]
thanks

**Comment by Pechi77** [comment]
Hi, I am using windows 64 bit, but installed apache 32 bit. and downloaded mod_wsgi.so 32 bit  from  https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/modwsgi/mod_wsgi-win32-ap22py31-3.0.so

Now I am getting the below error.

httpd.exe: Syntax error on line 130 of C:/Program Files (x86)/Apache Software Foundation/Apache2.2/conf/httpd.conf: Cannot load C:/Pro
gram Files (x86)/Apache Software Foundation/Apache2.2/modules/mod_wsgi.so into server: The specified module could not be found.

**Comment by GrahamDumpleton** [comment]
Do not use any files from the old Google Code site. Those binaries are absolutely ancient. Also do not use links above. The only supported method for installing mod_wsgi on Windows now is to use ``pip install mod_wsgi``. Then use ``mod_wsgi-express module-config`` to display the config you need to include in the Apache configuration file. For further details see:

* https://pypi.python.org/pypi/mod_wsgi

You should use Python 3.6, use Apache from ApacheLounge site and have Microsoft VC14 compiler available. You should use all 64 bit versions of these.

If you have issues, create a new issue for your problem. Please do not follow up on old issues.
