### ISSUE TITLE
another segfault issue

### ISSUE THREAD

**Issue by shevitz** [GrahamDumpleton/mod_wsgi#148]
I'm having an issue with mod_wsgi express segfaulting for unknown reasons. I am working on a new Centos 6.7 VM using Vmware workstation, with python 3.5 (which I build with enable--shared). I am working in a virtualenvwrapper venv and am using cookiecutter-django to build the requirements into a clean environment via:

pip install -r requirements/local.txt (output included below)
where base.txt has the following requirements added:

# Your custom requirements go here
mod-wsgi-httpd==2.4.12.6 
mod-wsgi==4.5.4
ipython==5.1.0

If I run via:
$ mod_wsgi-express start-server  --log-to-terminal

and point my browser to localhost:8000 I get a segfault in the log. (Now what is a little weird is that the default homepage still displays):
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:501
Server Conf        : /tmp/mod_wsgi-localhost:8000:501/httpd.conf
Error Log File     : /dev/stderr (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8
[Wed Aug 17 11:11:00.712157 2016] [mpm_event:notice] [pid 5367:tid 140580330829568] AH00489: Apache/2.4.12 (Unix) mod_wsgi/4.5.4 Python/3.5.2 configured -- resuming normal operations
[Wed Aug 17 11:11:00.712314 2016] [core:notice] [pid 5367:tid 140580330829568] AH00094: Command line: 'httpd (mod_wsgi-express)  -f /tmp/mod_wsgi-localhost:8000:501/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
[Wed Aug 17 11:11:57.769489 2016] [core:notice] [pid 5367:tid 140580330829568] AH00052: child pid 5369 exit signal Segmentation fault (11)
[Wed Aug 17 11:12:10.785297 2016] [core:notice] [pid 5367:tid 140580330829568] AH00052: child pid 5394 exit signal Segmentation fault (11)

For more information, If I run with log-level DEBUG, I get:
(guidewire)$ mod_wsgi-express start-server  --log-to-terminal --log-level DEBUG
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:501
Server Conf        : /tmp/mod_wsgi-localhost:8000:501/httpd.conf
Error Log File     : /dev/stderr (DEBUG)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8
[Wed Aug 17 11:14:23.262299 2016] [wsgi:debug] [pid 5428:tid 140062113093376] src/server/mod_wsgi.c(8096): mod_wsgi (pid=5428): Socket for 'localhost:8000' is '/tmp/mod_wsgi-localhost:8000:501/wsgi.5428.0.1.sock'.
[Wed Aug 17 11:14:23.262540 2016] [wsgi:debug] [pid 5428:tid 140062113093376] src/server/mod_wsgi.c(8154): mod_wsgi (pid=5428): Listen backlog for socket '/tmp/mod_wsgi-localhost:8000:501/wsgi.5428.0.1.sock' is '100'.
[Wed Aug 17 11:14:23.263031 2016] [wsgi:info] [pid 5430:tid 140062113093376] mod_wsgi (pid=5430): Starting process 'localhost:8000' with threads=5.
[Wed Aug 17 11:14:23.263191 2016] [wsgi:debug] [pid 5430:tid 140062113093376] src/server/mod_wsgi.c(9724): mod_wsgi (pid=5430): Setting lang to en_US.UTF-8 for daemon process group localhost:8000.
[Wed Aug 17 11:14:23.263211 2016] [wsgi:debug] [pid 5430:tid 140062113093376] src/server/mod_wsgi.c(9737): mod_wsgi (pid=5430): Setting locale to en_US.UTF-8 for daemon process group localhost:8000.
[Wed Aug 17 11:14:23.263205 2016] [mpm_event:notice] [pid 5428:tid 140062113093376] AH00489: Apache/2.4.12 (Unix) mod_wsgi/4.5.4 Python/3.5.2 configured -- resuming normal operations
[Wed Aug 17 11:14:23.263221 2016] [mpm_event:info] [pid 5428:tid 140062113093376] AH00490: Server built: Aug 15 2016 11:20:58
[Wed Aug 17 11:14:23.263249 2016] [core:notice] [pid 5428:tid 140062113093376] AH00094: Command line: 'httpd (mod_wsgi-express)  -f /tmp/mod_wsgi-localhost:8000:501/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
[Wed Aug 17 11:14:23.263338 2016] [wsgi:info] [pid 5430:tid 140062113093376] mod_wsgi (pid=5430): Python home /opt/Envs/guidewire.
[Wed Aug 17 11:14:23.263503 2016] [wsgi:info] [pid 5430:tid 140062113093376] mod_wsgi (pid=5430): Initializing Python.
[Wed Aug 17 11:14:23.263746 2016] [mpm_event:debug] [pid 5431:tid 140062071686912] event.c(2006): AH02471: start_threads: Using epoll
[Wed Aug 17 11:14:23.289247 2016] [wsgi:info] [pid 5430:tid 140062113093376] mod_wsgi (pid=5430): Attach interpreter ''.
[Wed Aug 17 11:14:23.313056 2016] [wsgi:info] [pid 5430:tid 140062113093376] mod_wsgi (pid=5430): Imported 'mod_wsgi'.
[Wed Aug 17 11:14:23.313183 2016] [wsgi:info] [pid 5430:tid 140062113093376] mod_wsgi (pid=5430, process='localhost:8000', application=''): Loading WSGI script '/tmp/mod_wsgi-localhost:8000:501/handler.wsgi'.
[Wed Aug 17 11:14:23.370090 2016] [wsgi:debug] [pid 5430:tid 140061932173056] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5430): Started thread 0 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:23.370354 2016] [wsgi:debug] [pid 5430:tid 140061921683200] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5430): Started thread 1 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:23.371026 2016] [wsgi:debug] [pid 5430:tid 140061911193344] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5430): Started thread 2 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:23.371161 2016] [wsgi:debug] [pid 5430:tid 140061769201408] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5430): Started thread 3 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:23.371386 2016] [wsgi:debug] [pid 5430:tid 140061900703488] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5430): Started thread 4 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:32.651836 2016] [authz_core:debug] [pid 5431:tid 140062069823232] mod_authz_core.c(835): [client 127.0.0.1:49687] AH01628: authorization result: granted (no directives)
[Wed Aug 17 11:14:32.651988 2016] [authz_core:debug] [pid 5431:tid 140062069823232] mod_authz_core.c(835): [client 127.0.0.1:49687] AH01628: authorization result: granted (no directives)
[Wed Aug 17 11:14:32.788165 2016] [authz_core:debug] [pid 5431:tid 140062069290752] mod_authz_core.c(835): [client 127.0.0.1:49688] AH01628: authorization result: granted (no directives), referer: http://localhost:8000/
[Wed Aug 17 11:14:33.272896 2016] [core:notice] [pid 5428:tid 140062113093376] AH00052: child pid 5430 exit signal Segmentation fault (11)
[Wed Aug 17 11:14:33.272951 2016] [wsgi:info] [pid 5428:tid 140062113093376] mod_wsgi (pid=5430): Process 'localhost:8000' has died, deregister and restart it.
[Wed Aug 17 11:14:33.272959 2016] [wsgi:info] [pid 5428:tid 140062113093376] mod_wsgi (pid=5430): Process 'localhost:8000' terminated by signal 11
[Wed Aug 17 11:14:33.272967 2016] [wsgi:info] [pid 5428:tid 140062113093376] mod_wsgi (pid=5430): Process 'localhost:8000' has been deregistered and will no longer be monitored.
[Wed Aug 17 11:14:33.273470 2016] [wsgi:info] [pid 5451:tid 140062113093376] mod_wsgi (pid=5451): Starting process 'localhost:8000' with threads=5.
[Wed Aug 17 11:14:33.273651 2016] [wsgi:debug] [pid 5451:tid 140062113093376] src/server/mod_wsgi.c(9724): mod_wsgi (pid=5451): Setting lang to en_US.UTF-8 for daemon process group localhost:8000.
[Wed Aug 17 11:14:33.273675 2016] [wsgi:debug] [pid 5451:tid 140062113093376] src/server/mod_wsgi.c(9737): mod_wsgi (pid=5451): Setting locale to en_US.UTF-8 for daemon process group localhost:8000.
[Wed Aug 17 11:14:33.273823 2016] [wsgi:info] [pid 5451:tid 140062113093376] mod_wsgi (pid=5451): Python home /opt/Envs/guidewire.
[Wed Aug 17 11:14:33.273910 2016] [wsgi:info] [pid 5451:tid 140062113093376] mod_wsgi (pid=5451): Initializing Python.
[Wed Aug 17 11:14:33.305776 2016] [wsgi:info] [pid 5451:tid 140062113093376] mod_wsgi (pid=5451): Attach interpreter ''.
[Wed Aug 17 11:14:33.328874 2016] [wsgi:info] [pid 5451:tid 140062113093376] mod_wsgi (pid=5451): Imported 'mod_wsgi'.
[Wed Aug 17 11:14:33.329059 2016] [wsgi:info] [pid 5451:tid 140062113093376] mod_wsgi (pid=5451, process='localhost:8000', application=''): Loading WSGI script '/tmp/mod_wsgi-localhost:8000:501/handler.wsgi'.
[Wed Aug 17 11:14:33.389493 2016] [wsgi:debug] [pid 5451:tid 140061932173056] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5451): Started thread 0 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:33.389738 2016] [wsgi:debug] [pid 5451:tid 140061921683200] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5451): Started thread 1 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:33.390236 2016] [wsgi:debug] [pid 5451:tid 140061911193344] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5451): Started thread 2 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:33.390295 2016] [wsgi:debug] [pid 5451:tid 140061769201408] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5451): Started thread 3 in daemon process 'localhost:8000'.
[Wed Aug 17 11:14:33.390481 2016] [wsgi:debug] [pid 5451:tid 140061900703488] src/server/mod_wsgi.c(8706): mod_wsgi (pid=5451): Started thread 4 in daemon process 'localhost:8000'.

I have absolutely no idea how to proceed or help trap this.

pip install -r requirements/local.txt  (output):

(guidewire)$ pip install -r requirements/local.txt
Requirement already satisfied (use --upgrade to upgrade): wheel==0.29.0 in /opt/Envs/guidewire/lib/python3.5/site-packages (from -r requirements/base.txt (line 5))
Collecting django==1.9.9 (from -r requirements/base.txt (line 8))
  Downloading Django-1.9.9-py2.py3-none-any.whl (6.6MB)
    100% |████████████████████████████████| 6.6MB 140kB/s 
Collecting django-environ==0.4.0 (from -r requirements/base.txt (line 11))
  Downloading django-environ-0.4.0.tar.gz
Collecting whitenoise==3.2.1 (from -r requirements/base.txt (line 12))
  Downloading whitenoise-3.2.1-py2.py3-none-any.whl
Collecting django-braces==1.9.0 (from -r requirements/base.txt (line 16))
  Downloading django_braces-1.9.0-py2.py3-none-any.whl
Collecting django-crispy-forms==1.6.0 (from -r requirements/base.txt (line 17))
  Downloading django-crispy-forms-1.6.0.tar.gz (118kB)
    100% |████████████████████████████████| 122kB 3.8MB/s 
Collecting django-floppyforms==1.6.2 (from -r requirements/base.txt (line 18))
  Downloading django-floppyforms-1.6.2.tar.gz (2.4MB)
    100% |████████████████████████████████| 2.4MB 390kB/s 
Collecting django-model-utils==2.5.2 (from -r requirements/base.txt (line 21))
  Downloading django-model-utils-2.5.2.tar.gz
Collecting Pillow==3.3.0 (from -r requirements/base.txt (line 24))
  Downloading Pillow-3.3.0-cp35-cp35m-manylinux1_x86_64.whl (5.5MB)
    100% |████████████████████████████████| 5.6MB 165kB/s 
Collecting django-allauth==0.26.1 (from -r requirements/base.txt (line 28))
  Downloading django-allauth-0.26.1.tar.gz (438kB)
    100% |████████████████████████████████| 440kB 2.0MB/s 
Collecting psycopg2==2.6.2 (from -r requirements/base.txt (line 32))
  Downloading psycopg2-2.6.2.tar.gz (376kB)
    100% |████████████████████████████████| 378kB 2.3MB/s 
Collecting unicode-slugify==0.1.3 (from -r requirements/base.txt (line 35))
  Downloading unicode-slugify-0.1.3.tar.gz
Collecting django-autoslug==1.9.3 (from -r requirements/base.txt (line 36))
  Downloading django_autoslug-1.9.3-py2.py3-none-any.whl
Collecting pytz==2016.6.1 (from -r requirements/base.txt (line 39))
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 2.0MB/s 
Collecting django-redis==4.4.4 (from -r requirements/base.txt (line 42))
  Downloading django-redis-4.4.4.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 3.0MB/s 
Collecting redis>=2.10.0 (from -r requirements/base.txt (line 43))
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 6.0MB/s 
Collecting mod-wsgi-httpd==2.4.12.6 (from -r requirements/base.txt (line 53))
  Downloading mod_wsgi-httpd-2.4.12.6.tar.gz (10.8MB)
    100% |████████████████████████████████| 10.8MB 88kB/s 
Collecting mod-wsgi==4.5.4 (from -r requirements/base.txt (line 54))
  Downloading mod_wsgi-4.5.4.tar.gz (1.8MB)
    100% |████████████████████████████████| 1.8MB 564kB/s 
Collecting ipython==5.1.0 (from -r requirements/base.txt (line 55))
  Downloading ipython-5.1.0-py3-none-any.whl (747kB)
    100% |████████████████████████████████| 747kB 1.3MB/s 
Collecting coverage==4.2 (from -r requirements/local.txt (line 3))
  Downloading coverage-4.2.tar.gz (359kB)
    100% |████████████████████████████████| 368kB 2.4MB/s 
Collecting django-coverage-plugin==1.3.1 (from -r requirements/local.txt (line 4))
  Downloading django_coverage_plugin-1.3.1.tar.gz
Collecting Sphinx==1.4.5 (from -r requirements/local.txt (line 5))
  Downloading Sphinx-1.4.5-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 626kB/s 
Collecting django-extensions==1.7.1 (from -r requirements/local.txt (line 6))
  Downloading django_extensions-1.7.1-py2.py3-none-any.whl (200kB)
    100% |████████████████████████████████| 204kB 3.7MB/s 
Collecting Werkzeug==0.11.10 (from -r requirements/local.txt (line 7))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 2.9MB/s 
Collecting django-test-plus==1.0.14 (from -r requirements/local.txt (line 8))
  Downloading django-test-plus-1.0.14.tar.gz
Collecting factory_boy==2.7.0 (from -r requirements/local.txt (line 9))
  Downloading factory_boy-2.7.0-py2.py3-none-any.whl
Collecting django-debug-toolbar==1.5 (from -r requirements/local.txt (line 10))
  Downloading django_debug_toolbar-1.5-py2.py3-none-any.whl (204kB)
    100% |████████████████████████████████| 204kB 3.3MB/s 
Collecting ipdb==0.10.1 (from -r requirements/local.txt (line 13))
  Downloading ipdb-0.10.1.tar.gz
Collecting pytest-django==2.9.1 (from -r requirements/local.txt (line 15))
  Downloading pytest_django-2.9.1-py2.py3-none-any.whl
Collecting pytest-sugar==0.7.1 (from -r requirements/local.txt (line 16))
  Downloading pytest-sugar-0.7.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /opt/Envs/guidewire/lib/python3.5/site-packages (from django-environ==0.4.0->-r requirements/base.txt (line 11))
Collecting python3-openid>=3.0.8 (from django-allauth==0.26.1->-r requirements/base.txt (line 28))
  Downloading python3-openid-3.0.10.zip (365kB)
    100% |████████████████████████████████| 368kB 2.5MB/s 
Collecting requests-oauthlib>=0.3.0 (from django-allauth==0.26.1->-r requirements/base.txt (line 28))
  Downloading requests_oauthlib-0.6.2-py2.py3-none-any.whl
Collecting requests>=1.0.3 (from django-allauth==0.26.1->-r requirements/base.txt (line 28))
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 1.8MB/s 
Collecting unidecode (from unicode-slugify==0.1.3->-r requirements/base.txt (line 35))
  Downloading Unidecode-0.04.19.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 3.4MB/s 
Collecting pexpect; sys_platform != "win32" (from ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading pexpect-4.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 6.3MB/s 
Collecting simplegeneric>0.8 (from ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading simplegeneric-0.8.1.zip
Collecting decorator (from ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading decorator-4.0.10-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in /opt/Envs/guidewire/lib/python3.5/site-packages (from ipython==5.1.0->-r requirements/base.txt (line 55))
Collecting pygments (from ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |████████████████████████████████| 757kB 1.3MB/s 
Collecting traitlets>=4.2 (from ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading traitlets-4.2.2-py2.py3-none-any.whl (68kB)
    100% |████████████████████████████████| 71kB 6.7MB/s 
Collecting pickleshare (from ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.3 (from ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading prompt_toolkit-1.0.6-py3-none-any.whl (256kB)
    100% |████████████████████████████████| 266kB 3.5MB/s 
Collecting alabaster<0.8,>=0.7 (from Sphinx==1.4.5->-r requirements/local.txt (line 5))
  Downloading alabaster-0.7.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in /opt/Envs/guidewire/lib/python3.5/site-packages (from Sphinx==1.4.5->-r requirements/local.txt (line 5))
Collecting imagesize (from Sphinx==1.4.5->-r requirements/local.txt (line 5))
  Downloading imagesize-0.7.1-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from Sphinx==1.4.5->-r requirements/local.txt (line 5))
  Downloading Babel-2.3.4-py2.py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 111kB/s 
Collecting docutils>=0.11 (from Sphinx==1.4.5->-r requirements/local.txt (line 5))
  Downloading docutils-0.12-py3-none-any.whl (508kB)
    100% |████████████████████████████████| 512kB 1.9MB/s 
Collecting snowballstemmer>=1.1 (from Sphinx==1.4.5->-r requirements/local.txt (line 5))
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 3.9MB/s 
Collecting fake-factory>=0.5.0 (from factory_boy==2.7.0->-r requirements/local.txt (line 9))
  Downloading fake_factory-0.6.0-py2.py3-none-any.whl (527kB)
    100% |████████████████████████████████| 532kB 1.9MB/s 
Collecting sqlparse>=0.2.0 (from django-debug-toolbar==1.5->-r requirements/local.txt (line 10))
  Downloading sqlparse-0.2.1.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 7.0MB/s 
Collecting pytest>=2.5 (from pytest-django==2.9.1->-r requirements/local.txt (line 15))
  Downloading pytest-2.9.2-py2.py3-none-any.whl (162kB)
    100% |████████████████████████████████| 163kB 4.8MB/s 
Collecting termcolor>=1.1.0 (from pytest-sugar==0.7.1->-r requirements/local.txt (line 16))
  Downloading termcolor-1.1.0.tar.gz
Collecting defusedxml (from python3-openid>=3.0.8->django-allauth==0.26.1->-r requirements/base.txt (line 28))
  Downloading defusedxml-0.4.1.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 3.2MB/s 
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.3.0->django-allauth==0.26.1->-r requirements/base.txt (line 28))
  Downloading oauthlib-1.1.2.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 6.2MB/s 
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.2->ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.3->ipython==5.1.0->-r requirements/base.txt (line 55))
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /opt/Envs/guidewire/lib/python3.5/site-packages (from Jinja2>=2.3->Sphinx==1.4.5->-r requirements/local.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.4 in /opt/Envs/guidewire/lib/python3.5/site-packages (from fake-factory>=0.5.0->factory_boy==2.7.0->-r requirements/local.txt (line 9))
Collecting py>=1.4.29 (from pytest>=2.5->pytest-django==2.9.1->-r requirements/local.txt (line 15))
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 92kB 3.8MB/s 
Building wheels for collected packages: django-environ, django-crispy-forms, django-floppyforms, django-model-utils, django-allauth, psycopg2, unicode-slugify, django-redis, mod-wsgi-httpd, mod-wsgi, coverage, django-coverage-plugin, django-test-plus, ipdb, pytest-sugar, python3-openid, unidecode, simplegeneric, sqlparse, termcolor, defusedxml, oauthlib
  Running setup.py bdist_wheel for django-environ ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/38/0a/5e/28edb187ccf58504510b3d985389a3d2e1efe115e67e8474b7
  Running setup.py bdist_wheel for django-crispy-forms ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/9c/61/01/e9bd04eeaf26d223ebfe4f43e21ad5686bd674f4c9d7f15613
  Running setup.py bdist_wheel for django-floppyforms ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/6f/f6/a0/ffd816a7425dc980287b6240d4bd0d1c8b451098d1dc9d0234
  Running setup.py bdist_wheel for django-model-utils ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/53/68/75/6ad41da48e684b063d61cd978d13941167993028cd0beaaac2
  Running setup.py bdist_wheel for django-allauth ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/f2/5f/24/bb4402374d5f9f9ccd390ef39109ea9ee8d76897f18e4fd75d
  Running setup.py bdist_wheel for psycopg2 ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/49/47/2a/5c3f874990ce267228c2dfe7a0589f3b0651aa590e329ad382
  Running setup.py bdist_wheel for unicode-slugify ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/1f/a2/1d/092d6d9dc106fdd7b87d1777564b087f2d163838e0b6f20c8b
  Running setup.py bdist_wheel for django-redis ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/f6/07/05/09238ff556250968ec3a68193d97c1fe95c54db177777c8301
  Running setup.py bdist_wheel for mod-wsgi-httpd ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/84/5f/28/7193330be5a9c2262eda8f978cf5242e9c062030dd15b4fd5a
  Running setup.py bdist_wheel for mod-wsgi ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/e3/10/dc/b9c3e413d791fbd00cedc6dd9b37067a5fa5253472d411234b
  Running setup.py bdist_wheel for coverage ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/6f/54/a5/e7629c41b30061b18f0ccbe4be643ed4cf5329f7b2459cf9ae
  Running setup.py bdist_wheel for django-coverage-plugin ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/ae/3f/9c/f6a173a0b8f8cb6a0007b97d498685b83fea2f6bc240ad9d43
  Running setup.py bdist_wheel for django-test-plus ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/26/f6/3c/569623cd16b6271b846732dd60baf6df7fe92ffdf0e9c1b528
  Running setup.py bdist_wheel for ipdb ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/5a/5e/c3/65a9de0506eb53bf883028bcd94e3ab07d998e6902883655ae
  Running setup.py bdist_wheel for pytest-sugar ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/03/fc/01/71793edbdea99e93c5c0d209707953aef1cc84a5bb7849826e
  Running setup.py bdist_wheel for python3-openid ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/3f/c3/60/8d33268af69bd73ccf86ef88cfa03ec621288df8746848d67a
  Running setup.py bdist_wheel for unidecode ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/72/da/8f/64e7de75111e143339d331011b56b3a8186e2eb07b0b5e383b
  Running setup.py bdist_wheel for simplegeneric ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/7b/31/08/c85e74c84188cbec6a6827beec4d640f2bd78ae003dc1ec09d
  Running setup.py bdist_wheel for sqlparse ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/e2/82/57/0a192624b6d4faa1d64d2b1f0efae857496b4f35fb7e86aba1
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/de/f7/bf/1bcac7bf30549e6a4957382e2ecab04c88e513117207067b03
  Running setup.py bdist_wheel for defusedxml ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/47/d0/73/a3232f5cd866e8ce7091049aebfd537db5f9454110fc202eef
  Running setup.py bdist_wheel for oauthlib ... done
  Stored in directory: /home/nen5admin/.cache/pip/wheels/e6/be/43/e4a2ca8cb9c78fbd9b5b14b96cb7a5cc43f36bc11af5dfac5b
Successfully built django-environ django-crispy-forms django-floppyforms django-model-utils django-allauth psycopg2 unicode-slugify django-redis mod-wsgi-httpd mod-wsgi coverage django-coverage-plugin django-test-plus ipdb pytest-sugar python3-openid unidecode simplegeneric sqlparse termcolor defusedxml oauthlib
Installing collected packages: django, django-environ, whitenoise, django-braces, django-crispy-forms, django-floppyforms, django-model-utils, Pillow, defusedxml, python3-openid, requests, oauthlib, requests-oauthlib, django-allauth, psycopg2, unidecode, unicode-slugify, django-autoslug, pytz, redis, django-redis, mod-wsgi-httpd, mod-wsgi, ptyprocess, pexpect, simplegeneric, decorator, pygments, ipython-genutils, traitlets, pickleshare, wcwidth, prompt-toolkit, ipython, coverage, django-coverage-plugin, alabaster, imagesize, babel, docutils, snowballstemmer, Sphinx, django-extensions, Werkzeug, django-test-plus, fake-factory, factory-boy, sqlparse, django-debug-toolbar, ipdb, py, pytest, pytest-django, termcolor, pytest-sugar
Successfully installed Pillow-3.3.0 Sphinx-1.4.5 Werkzeug-0.11.10 alabaster-0.7.9 babel-2.3.4 coverage-4.2 decorator-4.0.10 defusedxml-0.4.1 django-1.9.9 django-allauth-0.26.1 django-autoslug-1.9.3 django-braces-1.9.0 django-coverage-plugin-1.3.1 django-crispy-forms-1.6.0 django-debug-toolbar-1.5 django-environ-0.4.0 django-extensions-1.7.1 django-floppyforms-1.6.2 django-model-utils-2.5.2 django-redis-4.4.4 django-test-plus-1.0.14 docutils-0.12 factory-boy-2.7.0 fake-factory-0.6.0 imagesize-0.7.1 ipdb-0.10.1 ipython-5.1.0 ipython-genutils-0.1.0 mod-wsgi-4.5.4 mod-wsgi-httpd-2.4.12.6 oauthlib-1.1.2 pexpect-4.2.0 pickleshare-0.7.4 prompt-toolkit-1.0.6 psycopg2-2.6.2 ptyprocess-0.5.1 py-1.4.31 pygments-2.1.3 pytest-2.9.2 pytest-django-2.9.1 pytest-sugar-0.7.1 python3-openid-3.0.10 pytz-2016.6.1 redis-2.10.5 requests-2.11.1 requests-oauthlib-0.6.2 simplegeneric-0.8.1 snowballstemmer-1.2.1 sqlparse-0.2.1 termcolor-1.1.0 traitlets-4.2.2 unicode-slugify-0.1.3 unidecode-0.4.19 wcwidth-0.1.7 whitenoise-3.2.1

Can anyone please suggest what went wrong or how I should proceed. I have absolutely no idea.

Thanks,

**Comment by GrahamDumpleton** [comment]
Use mod_wsgi 4.5.5. The 4.5.4 release was a dud and caused crashes with Python 3.

Graham

**Comment by shevitz** [comment]
That was fast! Thanks for that. Problem fixed!
