### ISSUE TITLE
Provide support for WSGIScriptAlias and WSGIScriptAliasMatch in mod_wsgi-express

### ISSUE THREAD

**Issue by coderatchet** [GrahamDumpleton/mod_wsgi#149]
our current apache server loads scripts on demand using the WSGIScriptAliasMatch Directive and I've noticed there is no interpolation for this directive anywhere in the [`server/__init__.py`](https://github.com/GrahamDumpleton/mod_wsgi/blob/48bbfd5827e2caec396c74619fdf7840711c2ee5/src/server/__init__.py) file.

Could you possibly provide support for this. 

e.g.

``` bash
    mod_wsgi-express --script-alias-match "^/ui/(.*)" "/www-root/scripts/ui.wsgi" \
                     --script-alias-match "^/cron/(.*) "/jobs/cron.wsgi"
```

or

``` bash
    mod_wsgi-express --script-alias "/assets/" "/www-root/static/assets/"
```

Excellent work @GrahamDumpleton btw

**Comment by GrahamDumpleton** [comment]
Do you want to be able to host only one WSGI application or more than one?

The first example above suggests only one and the second more than one.

If the latter and want to have more than one, what are the WSGI applications and can they all run in the same sub interpreter, or do they need to be distinct, eg. Django.

The second variant with a directory as target generally means that any script file in the directory will be interpreted as a WSGI application.

You can indirectly do that now by using the ``--add-handler`` option and a bit of magic, but by default they would all run in the same interpreter context, which some WSGI applications may not like.

**Comment by coderatchet** [comment]
Thanks for the swift response

More than one. our project is split into multiple use case domains, each represented by a WSGI application.

Although for my current project an individual interpreter would suffice, There are others that contain multiple WSGI scripts that would benefit from the modularity.

We are about to migrate multiple interacting WSGI apps from python 2.7 to 3.5 and if the interpreter were sandboxed, it would certainly ease the transition.

We do not use Django, all our request dispatching is done through a WSGI REST micro-framework our company has written called [Prestans][1]

The library provides a means of producing request handlers that comply with WSGI standards
```python
    // sub-domain-example.wsgi
    import prestans

    application = prestans.rest.RequestRouter([
        (r"/api/users/([0-9]+)", com.example.UserRequestHandler),
        (r"/api/users/([0-9]+)/thumnail", com.example.UserThumbnailHandler),
        ...
    ], application_name="example-sub-domain-api");
```

If i could WSGIScriptAliasMatch to a url path regex, I could put many of those applications on different sub paths without each of those applications having to know where they are relative to the actual domain due to the last capture group.

i.e.
```bash
    WSGIScriptAliasMatch ^/bobs-burgers/(.*) /sub-domain-api.wsgi
    WSGIScriptAliasMatch ^/bills-bread/(.*) /other-useful-api.wsgi
```

[1]:https://github.com/anomaly/prestans

**Comment by GrahamDumpleton** [comment]
Is it intentional that you wanted the full URL to be passed as ``SCRIPT_NAME`` in the WSGI per request ``environ``. This is not how things would typically be done and would have meant you would have had to make adjustments in the WSGI application to fix it up or parse it properly.

If using ``WSGIScriptAliasMatch`` you would do it as:

```
WSGIScriptAliasMatch ^/bobs-burgers/(.*) /sub-domain-api.wsgi/$1
WSGIScriptAliasMatch ^/bills-bread/(.*) /other-useful-api.wsgi/$1
```

such that ``SCRIPT_NAME`` would then be ``/bobs-burgers`` and ``PATH_INFO`` would be the rest of the URL path.

But then, if that is what is desired, you should just have used:

```
WSGIScriptAlias /bobs-burgers/ /sub-domain-api.wsgi
WSGIScriptAlias /bills-bread/ /other-useful-api.wsgi
```

and you wouldn't have needed ``WSGIScriptAliasMatch``.

Just trying to work out whether you aren't doing this in much more complicated manner than you needed to.

**Comment by GrahamDumpleton** [comment]
The way to fudge it at the moment is run ``mod_wsgi-express`` as:

```
mod_wsgi-express start-server --include-file applications.conf --application-type static /some/path/to/static/files/directory
```

Then in ``applications.conf`` use:

```
WSGIScriptAliasMatch ^/bobs-burgers/(.*) /some/path/sub-domain-api.wsgi

<Location /bobs-burgers/>
WSGIProcessGroup ${MOD_WSGI_LISTENER_HOST}:${MOD_WSGI_HTTP_PORT}
</Location>

WSGIScriptAliasMatch ^/bills-bread/(.*) /some/path/other-useful-api.wsgi

<Location /bills-bread/>
WSGIProcessGroup ${MOD_WSGI_LISTENER_HOST}:${MOD_WSGI_HTTP_PORT}
</Location>

<Directory /some/path>
Order allow,deny
Allow from all
</Directory>
```

So you are using ``mod_wsgi-express`` for the bulk of the configuration with it still managing things, but you provide a configuration file snippet with the custom bit you need.

You do need to put ``mod_wsgi-express`` into mode where just handling static files since no WSGI application mounted at root. Your applications then overlay that.

If you didn't really need ``WSGIScriptAliasMatch``, then can use ``WSGIScriptAlias`` instead. If you can use that, can be sampled to:

```
WSGIScriptAlias /bobs-burgers/ /some/path/sub-domain-api.wsgi \
    process-group=${MOD_WSGI_LISTENER_HOST}:${MOD_WSGI_HTTP_PORT}
WSGIScriptAlias /bills-bread/ /some/path/other-useful-api.wsgi \
    process-group=${MOD_WSGI_LISTENER_HOST}:${MOD_WSGI_HTTP_PORT}

<Directory /some/path>
Order allow,deny
Allow from all
</Directory>
```

Still like to know answer to prior question to determine whether ``WSGIScriptAliasMatch`` wasn't overkill.

**Comment by coderatchet** [comment]
Thank you for the detailed response.

sorry for the delayed response, I had to have a closer look at our code base before responding so I knew how to reply (I have personally just joined the team).

In short, to your prior question, yes we were being overkill. More specifically, we were requiring our users to know about where in the path their application was mounted!

our matching of URLS in Prestans is done against the request.path object (generated using webob's `Request` by concatenating __SCRIPT_NAME__ with __PATH_INFO__ which appears valid according to the [PEP 3333][1]). however that meant users needed to provide a mount aware regex like `r"/mount/more/path"` instead of a more portable `r"/more/path"`.

I've raised the [above ticket][2] to address the incorrect implementation in Prestans. Future users should use the WSGIScriptAlias Directive when performing the example behaviour and a proper match will compare against PATH_INFO, not request.path. A huge thanks for the [detailed description][3] of how this should work!

[1]:https://www.python.org/dev/peps/pep-3333/#id24
[2]:https://github.com/anomaly/prestans/issues/126
[3]:https://github.com/anomaly/prestans/issues/126#issuecomment-240632892

**Comment by coderatchet** [comment]
All being said, It would still be nice to see this functionality implemented somehow. I'll take your `--application-conf` solution for now though 👍

**Comment by GrahamDumpleton** [comment]
One of the core ideas around mod_wsgi-express is that it is only serving up one WSGI application. This makes things simpler and provides better separation and means people are more inclined to configure everything appropriate to that specific application. Where you want to run more than one WSGI application the preference is therefore to run separate mod_wsgi-express instances and have a proxy in front. The best platform for this is a PaaS which deals with it all for you in some, but you could still do it yourself. I have actually written a blog post previously about using multiple mod_wsgi-express instances behind a proxy and what was required. In that case I was promoting idea that each runs in a separate container as well, but you don't strictly need to. The posts can be found at:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

**Comment by GrahamDumpleton** [comment]
Going to close this finally. Still not inclined to make any changes to mod_wsgi-express to make it easier to host multiple applications as that isn't its intent.
