### ISSUE TITLE
mod_wsgi cannot be loaded after upgrading apache to 2.4

### ISSUE THREAD

**Issue by demonguy** [GrahamDumpleton/mod_wsgi#150]
I'm using ubuntu 14.04. And i upgrade my apache2 to 2.4 today

But mod_wsgi is not going to be loaded... I tried to recompile mod_wsgi but the problem stands still, why?

apache2: Syntax error on line 139 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/wsgi.load: Cannot load /usr/lib/apache2/modules/mod_wsgi.so into server: /usr/lib/apache2/modules/mod_wsgi.so: undefined symbol: ap_accept_lock_mech
Action 'configtest' failed.
The Apache error log may have more information.
   ...fail!

**Comment by GrahamDumpleton** [comment]
The APIs of Apache 2.2 and 2.4 are different. As such, mod_wsgi needs to be recompiled.

If you have built from source code yourself, get down the latest mod_wsgi source code, build it and then install it again.

**Comment by demonguy** [comment]
Before receive your answer, i roll back my apache2 server back to 2.2
But now i got anthoer apache2 error log:
`mod_wsgi TypeError: 'NoneType' object is not iterable`

But there is not any more information to tell me where is going wrong

**Comment by GrahamDumpleton** [comment]
If you are not seeing a full Python trace traceback, then can only guess that your WSGI application is not actually returning an iterable, but is falling out the bottom of the function and returning None.

Use the WSGI hello world:

```
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!'

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]
```

rather than your current application to test the Apache/mod_wsgi installation.

If that doesn't work can only suggest recompiling mod_wsgi from source code and reinstalling. Make sure that you have the correct Apache dev/devel package from runtime version if using system packages.

**Comment by demonguy** [comment]
Thanks, after recompiling, it's OK now.
By the way, is there any frequently-used apt-get ppa repository for downloading the pre-built binary?
It's really painful to setup building environment.

**Comment by GrahamDumpleton** [comment]
Pre compiled binaries only work if you have same versions of Apache and Python that they were built against. There are too many combinations to support. For people who only want to use precompiled binaries, the Linux distros provide packages. Those though are generally years out of date and not available for newer Python versions.

If you want a potentially easier way of running up mod_wsgi, try the pip installable version and mod_wsgi-express. You still need Apache installed, but easier to get going for development as no Apache configuration to deal with.

See:

* https://pypi.python.org/pypi/mod_wsgi
