### ISSUE TITLE
503 Service Unavailable error

### ISSUE THREAD

**Issue by dhaneshcode** [GrahamDumpleton/mod_wsgi#154]
[wsgi:error] [pid 3400] (13)Permission denied: [client xxx.xxx.xxx.xxx:xxxxx] mod_wsgi (pid=3400): Unable to connect to WSGI daemon process 'djangotest' on '/var/run/apache2/wsgi.13585.14.1.sock' as user with uid=1001. 

I'm facing the error for a long time after being updated to apache2.4. Is there any solution for this. the mod_wsgi version which i used was 4.4.21 & 4.5.6 but the same error

**Comment by GrahamDumpleton** [comment]
See:

* http://modwsgi.readthedocs.io/en/develop/user-guides/configuration-issues.html#location-of-unix-sockets

You will need to set the ``WSGISocketPrefix`` directive so that they are kept in a different directory and your system setup is disallowing the use of the directory that would normally be used.

**Comment by dhaneshcode** [comment]
Hi thanks for the reply. I had changed the directory to tmp/ and also to /var/run/ then restarted the apache. yet the same issue persist.

**Comment by GrahamDumpleton** [comment]
The only other cause for this problem is if you have swapped to using ``peruser`` or ``perchild`` or ``itk`` MPM for Apache. You can use ``itk`` MPM but you must have compiled the mod_wsgi source code against the proper header files for the ``itk`` MPM.

**Comment by dhaneshcode** [comment]
Sorry for the mistake i used /tmp/wsgi (not tmp/ it was a typing mistake)  also used /var/run/wsgi  when this issue happen yet the same result. Is this due to the changes happen in the apache upgrade from 2.2. to 2.4? is there any thing we need to note after upgrade.In between  mod_wsgi was installed from source code .

**Comment by GrahamDumpleton** [comment]
Show me the exact error message you get when you use ``WSGISocketPrefix`` with value of ``/tmp/wsgi``.

Also, can you show me what your ``WSGIDaemonProcess`` directive is, and what ``User`` and ``Group`` are set to for Apache.

Finally, what Apache MPM are you using? It isn't normal for Apache workers to run as process ID 1001.

So what do you get for:

* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#apache-build-information

This is looking more like you are using one of those non standard MPMs, but the header files for those MPMs were not installed when mod_wsgi was compiled and as such, the special change required so they can work is not compiled into mod_wsgi. The change cannot be determined dynamically at run time.

**Comment by dhaneshcode** [comment]
When i gave the WSGIDaemonProcess /tmp/wsgi the same error persist. 

[Tue Sep 06 02:13:53.398624 2016] [wsgi:error] [pid 21736] (13)Permission denied: [client xxx.xxxx.xxx.xxx:9499] mod_wsgi (pid=21736): Unable to connect to WSGI daemon process 'test_site' on '/tmp/wsgi.21730.0.1.sock' as user with uid=1001.
[Tue Sep 06 02:13:53.398964 2016] [wsgi:error] [pid 21736] (13)Permission denied: [client xxx.xxx.xxx.xxx:9499] mod_wsgi (pid=21736): Unable to connect to WSGI daemon process 'test_site' on '/tmp/wsgi.21730.0.1.sock' as user with uid=1001.

In between the default location of the WSGIDaemonProcess is /var/run/apache2 and the user and group is nobody:root 

The mpm is 

httpd -l
Compiled in modules:
  core.c
  mod_so.c
  http_core.c


did i missing something  more in mpm?

**Comment by GrahamDumpleton** [comment]
I wanted the output from ``httpd -V`` as per link.

**Comment by dhaneshcode** [comment]
httpd -V

AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/conf/httpd.conf:406
Server version: Apache/2.4.23 (cPanel)
Server built:   Aug 24 2016 19:30:51
Server's Module Magic Number: 20120211:61
Server loaded:  APR 1.5.2, APR-UTIL 1.5.2
Compiled using: APR 1.5.2, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses disabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

**Comment by GrahamDumpleton** [comment]
I can't see how your Apache is starting up as root. CPanel must have it run as your user. When Apache is running and you are getting that error, do:

```
ls -las /var/run/apache2
```

and:

```
ps auxww | grep httpd
```

Want to see who that directory is owned by, what permissions are on directory, what files are in the directory, who they are owned by and what permissions.

**Comment by dhaneshcode** [comment]
ls -las /var/run/apache2
total 4
0 drwxr-xr-x  3 nobody root    100 Sep  6 02:17 .
0 drwxr-xr-x 29 root   root   1500 Sep  6 03:30 ..
0 drwx------  2 nobody nobody   40 Aug 24 16:33 htcacheclean
4 -rw-r--r--  1 root   root      6 Sep  6 02:17 httpd.pid
0 srwx------  1 nobody root      0 Sep  6 02:17 wsgi.22172.0.1.sock


ps aux | grep httpd | grep -v grep
root     22172  0.0  0.2 199188  6272 ?        Ss   02:17   0:00 /usr/sbin/httpd -k start
nobody   22174  0.0  0.3 507188  8276 ?        Sl   02:17   0:00 /usr/sbin/httpd -k start
nobody   22175  0.0  0.4 201928  9356 ?        S    02:17   0:00 /usr/sbin/httpd -k start
nobody   22176  0.0  0.4 202064  9520 ?        S    02:17   0:00 /usr/sbin/httpd -k start
nobody   22177  0.0  0.4 201928  9436 ?        S    02:17   0:00 /usr/sbin/httpd -k start
nobody   22178  0.0  0.4 201928  9340 ?        S    02:17   0:00 /usr/sbin/httpd -k start
nobody   22179  0.0  0.4 201928  9352 ?        S    02:17   0:00 /usr/sbin/httpd -k start
nobody   26623  0.0  0.4 201928  9340 ?        S    03:10   0:00 /usr/sbin/httpd -k start

**Comment by GrahamDumpleton** [comment]
They must be doing some shenanigans to have the effective uid of the Apache worker child process be something other than nobody. What is the uid for user nobody?

The log message is generated by:

```
                ap_log_rerror(APLOG_MARK, APLOG_ERR, rv, r,
                             "mod_wsgi (pid=%d): Unable to connect to "
                             "WSGI daemon process '%s' on '%s' as user "
                             "with uid=%ld.", getpid(), daemon->name,
                             daemon->socket_path, (long)geteuid());
```

So in the log where it is saying uid=1001, then it means geteuid() is returning 1001. That usually shouldn't be the case if uid in ps output shows as nobody as nobody is usually a very high number. If they had mapped nobody to 1001 then it should have worked anyway.

Test once more and when you see the error message in the log, grab it and post it here, along with the output of running:

```
ps -o user,uid,command | grep httpd
```

I want to verify exactly which process from the logs logged the message and what both user and uid show as.

Makes no sense.

**Comment by GrahamDumpleton** [comment]
Oh and the only other thing can think of is the problem is caused by SELinux being used, but then using /tmp should have got around that unless there is strange restrictions for Apache on /tmp as well.

**Comment by GrahamDumpleton** [comment]
Does the Apache configuration contain the directive ``VHostUser`` anywhere?

**Comment by GrahamDumpleton** [comment]
Hmm, that directive is only on Solaris. Doubt you are using that.

**Comment by GrahamDumpleton** [comment]
Okay, think the option I need to get you to check for is:

```
PrivilegesMode SECURE
```

**Comment by GrahamDumpleton** [comment]
Going to implement an option something like ``privileges-mode`` for ``WSGIDaemonProcess`` to try and deal with this. Will also make happy some ITK users as well who wouldn't compile mod_wsgi against ITK header files.

If ``privileges-mode`` is set to ``FAST`` then will behave like now. If set to ``SECURE``, will give the socket ownership of same user as daemon process group. These mirror ``PrivilegesMode`` directive.

If ``SELECTIVE`` then gets more complicated as it could be either at run time. May have to get creative with gid on socket at that point. Will have to play with it. Don't like the option name or values right now, so need to come up with some other designations.

**Comment by GrahamDumpleton** [comment]
Hahaha. I have a memory like a sieve.

Add to the ``WSGIDaemonProcess`` directive the option ``socket-user=#1001``, or ``socket-user=username`` where ``username`` is the name of the user corresponding to that with ``uid`` or ``1001`` as set by the ``VHostUser`` directive.

You will likely need the more recent mod_wsgi version. Don't remember when this option was added.

**Comment by dhaneshcode** [comment]
Hi Graham. sorry for the delayed reply i'm on the middle of something that's  why i couldn't make up on time.  So the new version of the wsgi can make up this permission denied error?

**Comment by GrahamDumpleton** [comment]
That ``socket-user`` option to ``WSGIDaemonProcess`` has been present since mod_wsgi 4.4.1 so can use either of the versions you have been working with. So just add the option into your configuration as I described. No need to install any new mod_wsgi version.

**Comment by dhaneshcode** [comment]
My man Graham you are awesome. That works. Thanks a lot  and hats off to you. This saves my 2 days of frustration.

**Comment by GrahamDumpleton** [comment]
Sorry for not remembering earlier that I had already added an option specifically to deal with this. :-(

**Comment by dhaneshcode** [comment]
Its okay and we are thankful to you so much and the delay dosen't matter because we trust you. :-) :+1:

**Comment by mariohmol** [comment]
Thanks god!!!!! All the examples on web is showgin using `user` in WSGIDaemonProcess , but if you use `socket-user` instead works great!! This is very common to whm/cpanel enviroment where you  need more than 1 user making sockets!

**Comment by GrahamDumpleton** [comment]
You would still need ``user`` as that is what sets the user the daemon process runs as. The ``socket-user`` option that was added now also has to be set where the Apache child process doing the proxy changes to a specific user rather than Apache user.

**Comment by mariohmol** [comment]
Good to know.. i will just put a example how worked for me so if others get here  

In a cpanel, where create `example.com` domain it uses `example` as user and group.

 `WSGIDaemonProcess examplecom user=example group=example socket-user=example group=vidapolitica processes=5 threads=5 display-name=%{GROUP}`
