### ISSUE TITLE
Documentation unclear on effect of WSGIApplicationGroup %{GLOBAL} on daemon configurations

### ISSUE THREAD

**Issue by satiani** [GrahamDumpleton/mod_wsgi#155]
It's not clear to me from reading the documentation whether `WSGIApplicationGroup %{GLOBAL}` respects the `WSGIProcessGroup` setting or whether it means that all WSGI applications will run in the same process.

Link: http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIApplicationGroup.html

Quote:

> Any WSGI applications in the global application group will always be executed within the context of the first interpreter created by Python when it is initialised.

**Comment by GrahamDumpleton** [comment]
For now dealt with by response to same question on mailing list:

* https://groups.google.com/d/msg/modwsgi/6oMM6QpaqBQ/b1hYb5FRAgAJ

**Comment by GrahamDumpleton** [comment]
Closing. Attempt at cllarifications added in:

* https://github.com/GrahamDumpleton/mod_wsgi/commit/2233af52c3690c62bfffc3fafadfc83ebd2aeeab
* https://github.com/GrahamDumpleton/mod_wsgi/commit/a94e90792040587bf2d0954a1aa16f031ef61062
