### ISSUE TITLE
Target WSGI script cannot be loaded as Python module

### ISSUE THREAD

**Issue by narenchoudhary** [GrahamDumpleton/mod_wsgi#156]
I am trying to deploy a Django1.9.8 application on Centos6.8 system using Apache/2.2.15 and mod_wsgi4.5.6.

    $ ldd /etc/httpd/modules/mod_wsgi.so
    linux-gate.so.1 =>  (0x00bfb000)
    libpython2.7.so.1.0 => /usr/local/lib/libpython2.7.so.1.0 (0x009e9000)
    libpthread.so.0 => /lib/libpthread.so.0 (0x00188000)
	libdl.so.2 => /lib/libdl.so.2 (0x008d7000)
	libutil.so.1 => /lib/libutil.so.1 (0x00c57000)
	libm.so.6 => /lib/libm.so.6 (0x005ce000)
	libc.so.6 => /lib/libc.so.6 (0x00391000)
	/lib/ld-linux.so.2 (0x0025f000)
    
I first tried deploying a hello world application. I had to run `chcon -R -t httpd_sys_content_t hellowsgi.wsgi` after which it worked fine.

Now I'm trying to deploy a Django application using a virtualenv. 

Few points regarding that:  
1. Centos6.8 has Python 2.6. as default interpreter. I installed Python 2.7.11 *alongside* 2.6.6 with sharing enabled. Then I installed mod_wsgi from source. I compiled it with Python 2.7.11.
2. I created a virtualenv in my home directory. 

         virtualenv -p /usr/localbin/python2.7 --no-site-packages django-deploy-test

3. I then installed Django 1.9.8, created a django project, configured static files.
4. Then I created following **django.conf** file. 

        LoadModule wsgi_module modules/mod_wsgi.so
        Alias /static/ /home/ccd/code/django-deploy-test/myproject/static/
        <Directory /home/ccd/code/django-deploy-test/myproject/static/>
             Order deny,allow
             Allow from all
        </Directory>

        WSGIScriptAlias /ccd /home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py
        WSGIPythonPath /home/ccd/code/django-deploy-test/myproject:/home/ccd/code/django-deploy-test/lib/python2.7/site-packages
        WSGISocketPath /var/run/wsgi
    
        <Directory  /home/ccd/code/django-deploy-test/myproject/myproject>
            <Files wsgi.py>
                Order deny,allow
                Allow from all 
            </Files>
        </Directory>

Now my static files are loading without any permission/server issue. 
The problem is when is try `SERVER_IP/ccd/`, I run into **Internal Server Error**.

Apache error log:

    [info] mod_wsgi (pid=2561, process='', application=127.0.0.1):  Loading WSGI Script '/home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py'
    [error] mod_wsgi (pid=2561) Target WSGI script '/home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py' cannot be loaded as Python module.
    [error] Exception occurred processing WSGI script: '/home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py'
    [error] Traceback (most recent call last):
    [error]       File "/home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py" in line 12
    [error]               from django.core.wsgi import get_wsgi_application
    [error] ImportError: no module named wsgi

I think the issue is with mod_wsgi's handling of virtualenv. But I'm not able to resolve that is wrong. In [Django docs](https://docs.djangoproject.com/en/1.9/howto/deployment/wsgi/modwsgi/#using-a-virtualenv), it suggest add adding `WSGIPythonPath` directive for virtualenv. I also read [mod_wsgi docs on virtualenv](http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html), but could not understand much.

**Comment by GrahamDumpleton** [comment]
You are better off using daemon mode:

```
WSGIDaemonProcess myapp python-home=/home/ccd/code/django-deploy-test python-path=/home/ccd/code/django-deploy-test/myproject
WSGIScriptAlias /ccd /home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py process-group=myapp application-group=%{GLOBAL}
```

See:

* http://blog.dscpl.com.au/2012/10/why-are-you-using-embedded-mode-of.html

for why embedded mode is a bad idea.

Anyway, the reason you are getting an error is because it is finding an older Django version than what you are expecting.

The reason is possibly because you were trying to add ``site-packages`` with ``WSGIPythonPath`` when with embedded mode you should use ``WSGIPythonHome`` to set virtual environment location. This would have resulted in it picking up Django from main Python installation ``site-packages`` and not the virtual environment.

Since though better to use daemon mode, use the configuration above instead. Don't set ``WSGIPythonPath`` once using that daemon process config.

**Comment by GrahamDumpleton** [comment]
The article to read about using Python virtual environments is:

* http://blog.dscpl.com.au/2014/09/using-python-virtual-environments-with.html

**Comment by narenchoudhary** [comment]
Also one thing I missed in last comment is I've added following code in default *wsgi.py* file generated by Django:

    activate_this = "/home/ccd/code/django-deploy-test/bin/activate_this.py"
    execfile(activate_this, dict(__file__=activate_this))

When I do pip freeze in virtualenv I get `Django==1.9.8` which is exactly what I want. Apart from this I do not have any version of Django installed anywhere on my system.

I reconfigured **django.conf** for daemon mode:

    WSGIDaemonProcess myproject python-home=/home/ccd/code/django-deploy-test python-path=/home/ccd/code/django-deploy-test/myproject
    WSGIScriptAlias /ccd /home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py process-group=myproject application-group=%{GLOBAL}

    #WSGIScriptAlias /ccd /home/ccd/code/django-deploy-test/myproject/myproject/wsgi.py
    #WSGIPythonPath /home/ccd/code/django-deploy-test/myproject:/home/ccd/code/django-deploy-test/lib/python2.7/site-packages
 

Now I'm getting new error:

    [Tue Sep 13 23:01:22 2016] [info] mod_wsgi (pid=3059): Process 'myproject' has died, deregister and restart it.
    [Tue Sep 13 23:01:22 2016] [info] mod_wsgi (pid=3059): Process 'myproject' terminated by signal 1
    [Tue Sep 13 23:01:22 2016] [info] mod_wsgi (pid=3059): Process 'myproject' has been deregistered and will no longer be monitored.
    [Tue Sep 13 23:01:22 2016] [info] mod_wsgi (pid=3060): Starting process 'myproject' with uid=48, gid=48 and threads=15.
    [Tue Sep 13 23:01:22 2016] [info] mod_wsgi (pid=3060): Python home /home/ccd/code/django-deploy-test.
    [Tue Sep 13 23:01:22 2016] [info] mod_wsgi (pid=3060): Initializing Python.
    ImportError: No module named site
    [Tue Sep 13 23:01:23 2016] [info] mod_wsgi (pid=3060): Process 'myproject' has died, deregister and restart it.
    [Tue Sep 13 23:01:23 2016] [info] mod_wsgi (pid=3060): Process 'myproject' terminated by signal 1
    [Tue Sep 13 23:01:23 2016] [info] mod_wsgi (pid=3060): Process 'myproject' has been deregistered and will no longer be monitored.
    [Tue Sep 13 23:01:23 2016] [info] mod_wsgi (pid=3061): Starting process 'myproject' with uid=48, gid=48 and threads=15.
    [Tue Sep 13 23:01:23 2016] [info] mod_wsgi (pid=3061): Python home /home/ccd/code/django-deploy-test.
    [Tue Sep 13 23:01:23 2016] [info] mod_wsgi (pid=3061): Initializing Python.
    ImportError: No module named site

**Comment by GrahamDumpleton** [comment]
The issue is that your Python 2.7 is not actually alongside the Python 2.6 installation, but in ``/usr/local``. When Python tries to startup, it is finding ``/usr/bin/python`` and tracking back from there looking for ``/usr/lib/python2.7`` but not finding it. There startup therefore fails.

Try setting at global scope in Apache configuration:

```
/home/ccd/code/django-deploy-test
```

Better still, disabled initialisation of the Pyhon interpreter in the Apache child worker processes (embedded mode processes) and use daemon mode exclusively.

This can be done by setting at Python global scope.

```
WSGIRestrictEmbedded On
```

The ``python-home`` option to ``WSGIDaemonProcess`` should then be sufficient.

The ``python-home`` option should also mean that you don't need to manually activate the Python virtual environment in the WSGI script file.

**Comment by narenchoudhary** [comment]
It was because of SELinux.

     $ ldconfig -p | grep selinux
    libxcb-xselinux.so.0 (libc6) => /usr/lib/libxcb-xselinux.so.0
    libxcb-xselinux.so (libc6) => /usr/lib/libxcb-xselinux.so
    libselinux.so.1 (libc6) => /lib/libselinux.so.1
    libselinux.so (libc6) => /usr/lib/libselinux.so
    
Setting SELinux target security context type to `httpd_sys_content_t` solved all errors.

This solved the problem:

     $ cd /home/ccd/code/
     $ chcon -R -t httpd_sys_content_t django-deploy-test/


Now all files in *django-deploy-test/* look like:

    $ ls -Z
    drwxrwxr-x. ccd ccd unconfined_u:object_r:httpd_sys_content_t:s0 bin
    drwxrwxr-x. ccd ccd unconfined_u:object_r:httpd_sys_content_t:s0 include
    drwxrwxr-x. ccd ccd unconfined_u:object_r:httpd_sys_content_t:s0 lib
    drwxrwxr-x. ccd ccd unconfined_u:object_r:httpd_sys_content_t:s0 myproject
    -rw-rw-r--. ccd ccd unconfined_u:object_r:httpd_sys_content_t:s0 pip-selfcheck.json

Because of my very limited knowledge of SELinux context mechanism, I'm not sure if this is the right way to solve this issue.

**Comment by GrahamDumpleton** [comment]
If SELinux is going to cause a problem in this scenario, it is because you have the code under your home directory. You are better off having it under and area like ``/var/www``, or whatever it is that Apache on your system uses for sites. Am surprised you even got as far as you did given that home directories aren't usually readable to others at all and so the WSGI script file wouldn't have been able to be loaded in the first place.

**Comment by narenchoudhary** [comment]
Yes, I ran `chmod o+r` on static files and  wsgi.py file and `chmod o+rx` on`/home/ccd/`. I also might have changed read permission of some other files as well. I think the problem was SELinux and the issue has been resolved. 

This issue can be closed now. Thanks a lot for helping out.
