### ISSUE TITLE
Target WSGI script not found or unable to stat

### ISSUE THREAD

**Issue by deveshaggrawal19** [GrahamDumpleton/mod_wsgi#158]
I've enabled wsgi module and restarted the apache2. But still this error shows. Please help me out

**Comment by GrahamDumpleton** [comment]
What OS are you using? What is the mod_wsgi configuration you used? Where is the WSGI script file located?

From memory this indicates an incorrect path or issue with SELinux permissions on a system.

**Comment by deveshaggrawal19** [comment]
I'm on ubuntu 14.04 LTS. Mod_wsgi module i installed using apt-get libapache2-mod-wsgi-py3. The wsgi file is in /srv/www/buy/app/buy.wsgi, I'm using it to deveop a flask application. I've checked that selinux is not installed on my system.

**Comment by deveshaggrawal19** [comment]
Well the issue is solved now. I do not know what exactly triggered it but i think it has to with some permissions on virtualenv i guess. I'm very thankful to you for replying is such a short period of time.
