### ISSUE TITLE
previous DYLD_LIBRARY_PATH environment value (possibly all other variables as well) is empty when modified in generated apachectl script.

### ISSUE THREAD

**Issue by coderatchet** [GrahamDumpleton/mod_wsgi#159]
I am deploying a cx_Oracle dependant WSGI app so need to have my DYLD_LIBRARY_PATH set to the correct instantclient location (containing the needed dlls). I generate the apache server configuration files using mostly default settings `mod_wsgi-express setup-server ...`.

When I set my environment variables and call the script, the DYLD_LIBRARY_PATH disappears and gets replaced with the `../site-packages/mod_wsgi_packages/httpd/lib:` path. The intention of appending the previous value doesn't work and I believe this is due to the shebang env line ([6th paragraph in this answer](http://unix.stackexchange.com/a/29620/63678))

``` bash
# ./server script
set -x
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
set +x
generated-apache-server-home/apachectl $@
```

``` bash
# generated apachectl, I've placed set -x in there for debugging purposes
#!/usr/bin/env bash
...
SHLIBPATH="/path/to/venv/lib/python2.7/site-packages/mod_wsgi_packages/httpd/lib"

if [ "x$SHLIBPATH" != "x" ]; then
    set -x
    DYLD_LIBRARY_PATH="$SHLIBPATH:$DYLD_LIBRARY_PATH"
    set +x
    export DYLD_LIBRARY_PATH
fi
```

DYLD_LIBRARY_PATH is not set:

``` bash
$ ./server start
++ export DYLD_LIBRARY_PATH=/path/to/instantclient_11_2
++ DYLD_LIBRARY_PATH=/path/to/instantclient_11_2
++ set +x
+ DYLD_LIBRARY_PATH=/path/to/venv/lib/python2.7/site-packages/mod_wsgi_packages/httpd/lib:
+ set +x
```

I am in a virtualenv and can `echo $DYLD_LIBRARY_PATH` the correct value.
## UPDATE:

Also worth noting that using the `mod_wsgi-express setup-server --setenv` option has no effect:

``` bash
# generated httpd.conf
...
SetEnv 'DYLD_LIBRARY_PATH' '/path/to/instantclient_11_2'
...
```

``` python
# a python file I know is in the server
import os
print("DYLD_LIBRARY_PATH={}".format("" if "DYLD_LIBRARY_PATH" not in os.environ else os.environ["DYLD_LIBRARY_PATH"]))
```

```
#output
[Fri Oct 07 09:59:25.304172 2016...] DYLD_LIBRARY_PATH=/path/to/venv/lib/python2.7/site-packages/mod_wsgi_packages/httpd/lib:
```

**Comment by GrahamDumpleton** [comment]
Try one of the following.

In the generated directory, edit the ``envvars`` file and set and export the variable there.

Or, create your own ``envars`` file somewhere else and when running ``mod_wsgi-express setup-server`` add the option ``--envvars-script`` with an argument of the path to your ``envvars`` script file.

That said, this still may not help as believe have encountered some issue with propagating this environment variable before.

The better way is to not need to set the variable by ensuring the extension module is looking in the right place to begin with. I need to go look up what you need to do for that.

**Comment by GrahamDumpleton** [comment]
On a side note, not even sure why am using ``/usr/bin/env bash`` as I always write scripts to be compatible with ``/bin/sh``.

I can't see anything relevant in comment 6 you point out related to this. I do sort of recollect that ``/usr/bin/env`` on MacOS X is an issue with ``DYLD_LIBRARY_PATH`` as it will not propagate it. I encountered that not long back but on something completely different and not with mod_wsgi.

**Comment by coderatchet** [comment]
the first option works, however I get the following error unless i also append the previous DYLD_LIBRARY_PATH, which seems redundant

```
dyld: Library not loaded: /private/var/folders/mc/3xxw_n192xjg396rxl68hh6m0000gn/T/pip-build-D8wjgN/mod-wsgi-httpd/build/httpd/lib/libaprutil-1.0.dylib
  Referenced from: /path/to/venv/lib/python2.7/site-packages/mod_wsgi_packages/httpd/bin/httpd
  Reason: Incompatible library version: httpd requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0
```

**Comment by coderatchet** [comment]
as to your last comment, I was referring to 'paragraph' six, in the top most comment

**Comment by GrahamDumpleton** [comment]
Yes you will need to extend the ``DYLD_LIBRARY_PATH `` variable to include the original value it may have had as well.

As to the dyld warning, have you installed the ``mod_wsgi-httpd`` package by chance? Normally you wouldn't use that.

**Comment by coderatchet** [comment]
yes i have
would i need an official package instead?

**Comment by GrahamDumpleton** [comment]
Is there a problem with using the Apache httpd that Apple ships with the operating system?

**Comment by coderatchet** [comment]
not sure, I was assuming using the mod_wsgi-httpd package was the "way to do it" with mod_wsgi.

**Comment by coderatchet** [comment]
P.S. this is currently a development environment I am creating, the production version would use another apache

**Comment by coderatchet** [comment]
which upon speaking that out makes me realise it would be better simply obtaining the same production version and running with it.

**Comment by GrahamDumpleton** [comment]
It is only their for extreme cases where someone can't install Apache httpd themselves or not part of operating system already. I didn't even think I mentioned ``mod_wsgi-httpd`` on PyPi page for mod_wsgi or in any other instructions.

To clean up and start over you would need to uninstall both ``mod_wsgi`` and ``mod_wsgi-httpd`` packages. Then install just ``mod_wsgi``.

```
pip uninstall mod_wsgi mod_wsgi-httpd
pip install mod_wsgi
```

**Comment by GrahamDumpleton** [comment]
As to it not finding the library in the first place, what do you get when you run ``otool -L`` on the cx_Oracle extension module ``.so`` file? Provide results with and without ``DYLD_LIBRARY_PATH`` set.

**Comment by GrahamDumpleton** [comment]
FWIW, articles talking about how to fix the path it searches for Oracle libraries are:

* http://stackoverflow.com/questions/8158536/importing-cx-oracle-python-with-macosx
* https://blog.caseylucas.com/2013/03/03/oracle-sqlplus-and-instant-client-on-mac-osx-without-dyld_library_path/

On  a Linux system you would normally set ``LD_RUN_PATH`` to the directory at the time of compiling/installing the cx_Oracle module. There is no equivalent on MacOS X and you need to adjust the path afterwards. This is if you want to fix it permanently.

**Comment by coderatchet** [comment]
```
$ echo $DYLD_LIBRARY_PATH

$ otool -L cx_Oracle.so
cx_Oracle.so:
	/path/to/instantclient_11_2/libclntsh.dylib.11.1 (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
$ export DYLD_LIBRARY_PATH=/path/to/instantclient_11_2
$ otool -L cx_Oracle.so
cx_Oracle.so:
	/path/to/instantclient_11_2/libclntsh.dylib.11.1 (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

**Comment by GrahamDumpleton** [comment]
Did the exceptions you were getting complaining about ``cx_Oracle.so`` not resolving libraries as that looks fine. Maybe is issue with Oracle's own libraries and references between them, or are they only use a single library these days and not the numerous libraries they used to?

More discussion in this post:

* https://stevereads.com/2016/01/31/querying-oracle-databases-from-cx_oracle-under-el-capitan/

**Comment by coderatchet** [comment]
I have actually modified the references using `install_name_tool` beforehand:

```bash
INSTALL_LOCATION="/path/to/instantclient_11_2"
...
install_name_tool -change /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1 ${INSTALL_LOCATION}/libclntsh.dylib.11.1 ${VIRTUAL_ENV}/lib/python2.7/site-packages/cx_Oracle.so
install_name_tool -id ${INSTALL_LOCATION}/libclntsh.dylib.11.1 ${INSTALL_LOCATION}/libclntsh.dylib.11.1
install_name_tool -change /ade/dosulliv_ldapmac/oracle/ldap/lib/libnnz11.dylib ${INSTALL_LOCATION}/libnnz11.dylib ${INSTALL_LOCATION}/libclntsh.dylib.11.1
```
as I would receive a library not loaded error if i didn't do this.

**Comment by GrahamDumpleton** [comment]
Anyway, back to the original issue. Using ``envvars`` got around that didn't it?

I will need to look at why using ``/usr/bin/env`` in ``#!`` line when probably don't need to. Not sure that will help though given that ``/usr/bin/env`` in the ``mod_wsgi-express`` script make cause same issue with it not being propogated.

**Comment by coderatchet** [comment]
Sorry for the late reply, but yes, the issue was resolve with an envvars file

    # envvars.sh
    export DYLD_LIBRARY_PATH=~/instantclient_11_2:$DYLD_LIBRARY_PATH

**Comment by GrahamDumpleton** [comment]
I have changed generated ``apachectl`` to use ``/bin/sh``, but as suspected doesn't change anything. Only solution is to use ``envvars``.

**Comment by GrahamDumpleton** [comment]
FWIW, I had to refer back to ``/bin/bash`` as was using a bash specific feature. Only found out later when tried to deploy on a Linux system where ``/bin/sh`` didn't have it.
