### ISSUE TITLE
RFE: Support out of tree builds

### ISSUE THREAD

**Issue by opoplawski** [GrahamDumpleton/mod_wsgi#164]
For Fedora we build python2 and python3 package from the same spec.  It would be helpful in mod_wsgi supported out of source tree builds.

**Comment by GrahamDumpleton** [comment]
You will need to explain exactly what that means. If you can provide a link to an example that would also help. Thanks.

**Comment by GrahamDumpleton** [comment]
Since no further details was provided as to what exactly was required for an out of tree build I am closing this. If you can show what needs to work and how then can re-open issue again.
