### ISSUE TITLE
App stop loading after some time

### ISSUE THREAD

**Issue by mariohmol** [GrahamDumpleton/mod_wsgi#168]
Hi there!

I have one server with 3 python apps using mod_wsgi.

One app always work.. but other 2 works initially good.. but after a few minutes it stops.

It stays loading for ever and never make a response and i can see this error in the apache console

```
[Thu Nov 24 10:18:16.909356 2016] [mpm_prefork:notice] [pid 11570] AH00163: Apache/2.4.23 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_wsgi/4.5.7 Python/2.7 configured -- resuming normal operations
[Thu Nov 24 10:18:16.909381 2016] [core:notice] [pid 11570] AH00094: Command line: '/usr/sbin/httpd'
```

I tryed many different forms of configure this apps to try to see what hapens, but always the same. When I restart apache2 it back to work perfect.

Before i had some issues with MaxWorkers but i increase all the limits and the server is like 10% used, so is not the machine that cant support.

Here a example of configuration:

```
CustomLog /home/myappcom/logs/wsgi.log common
ErrorLog /home/myappcom/logs/error.log
LogLevel error

WSGIDaemonProcess myapps user=myapp group=jenkins socket-user=myapp processes=5 threads=5 display-name=%{GROUP}

WSGIScriptAlias / /home/myapp/app/visual.wsgi

WSGIApplicationGroup %{GLOBAL}
WSGIProcessGroup myapps
WSGIPassAuthorization On

<Directory /home/myapp/public_html>
 #WSGIApplicationGroup %{GLOBAL}
    Order allow,deny
    Allow from all
    </Directory>
```

Please help, dont know what more to do. Actually the only way out that i can see now is going back to Proxy apache

**Comment by mariohmol** [comment]
Tested running this apps using supervisor and cherrypy to run the apps. 
So i can acce direct using a port or via proxy in apache2. And same thing is giving with mod_proxy:
 ` [proxy_fcgi:error] [pid 21120] (70007)The timeout specified has expired: [client 191.96.249.80:47868] AH01075: Error dispatching request to : (polling`

So i guess that is not related to the mod_wsgi but to apache/centos itself.

I'm closing this issue.

If you have any tips about how to solve that? I looked in almost every log that is related with and cant see any error. 

I guess that is related with proxy connections on apache connecting to python that still open. Tryed to use keepalive false, reduce the timeout time and increse the maxworkers but same thing. It works in first 5 minute and then stop working.

Thanks!

**Comment by GrahamDumpleton** [comment]
You could try adding:

* file:///Users/graham/Projects/mod_wsgi/docs/_build/html/user-guides/debugging-techniques.html#extracting-python-stack-traces

so you can try and get Python stack traces for what process is up to in case they are deadlocking.

Is possible the deadlocking may prevent this working as well, but can still try.

**Comment by mariohmol** [comment]
Thanks for your answer!

Until now i was tracking counting of httpd process and before the number increases until get max (350) and locks down.. (easily can see that every call still open)

But the weird is that the first app loaded with mod_wsgi still working.

What i've made to make all 3 apps working:

* Changed everything to mod_proxy
* Changed the apache to use mod_mpm_worker instead mod_mpm_prefork

Will try to change them to use wsgi instead and make some test, will report here later.

Thanks again!

**Comment by GrahamDumpleton** [comment]
The large number of processes is going to be due to the backends having likely got stuck. All the requests will queue up and this causes Apache to create more child worker processes. It looks worse because you have preform MPM. That stack trace code may help to see where being stuck if that is what is happening.

Since you have recent mod_wsgi version, would also suggest you start setting timeouts on daemon process group to try and deal with it, or at least recover automatically. I actually finally updated the docs page with details on the timeout options yesterday.

* http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html

Try setting on ``WSGIDaemonProcess``:

* connect-timeout=15
* socket-timeout=60
* queue-timeout=45
* request-timeout=60

Also set ``LogLevel`` info so can see mod_wsgi log details about restarts of daemon processes and why.

If it is hitting a request timeout, mod_wsgi will attempt to log Python stack traces automatically so can see where gets stuck.

**Comment by mariohmol** [comment]
I've seen that.. thanks.. i will try to put timeouts on deamon.

Now with MPM error still there... the httpd process is very low (+-22) and keeps like that.. but now i have another error:

* AH00288: scoreboard is full, not at MaxRequestWorkers

Will try to add the timeouts and give a feedback!

**Comment by GrahamDumpleton** [comment]
I am not familiar with that error and what it means. Seems there was a bug related to that a while back, but should have been fixed.

* http://serverfault.com/questions/516373/what-is-the-meaning-of-ah00485-scoreboard-is-full-not-at-maxrequestworkers

Not sure whether mod_wsgi daemon processes blocking could create that as a side effect or not.

BTW, what are your Apache MPM settings? The settings that SO post lists.

**Comment by mariohmol** [comment]
I've been attacked.. it started in same period that i was using mod_wsgi.. i never could imagine that ... anyway its everything working good now !

Thanks for your support.  =)
