### ISSUE TITLE
Sphinx converts -- to a single en dash

### ISSUE THREAD

**Issue by james-prior** [GrahamDumpleton/mod_wsgi#170]
Sphinx converts '--' as in '''to use the "--with-apxs" option''' of https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/docs/user-guides/quick-installation-guide.rst to a single en dash character (encoded as &#8211; in HTML). The problem appears on https://modwsgi.readthedocs.io/en/develop/user-guides/quick-installation-guide.html and my local HTML files generated by Sphinx, but not on [github](https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/docs/user-guides/quick-installation-guide.rst).

I have not figured out how to escape '--', except with an inline literal as in https://github.com/james-prior/mod_wsgi/blob/jep-dev-avoiding-en-dash/docs/user-guides/quick-installation-guide.rst, which changes the appearance beyond just avoiding the en dash.

Hopefully, you know a better way.

**Comment by GrahamDumpleton** [comment]
I have been starting to change to use double back quotes for stuff like this as I update the docs. The docs were originally written for Google Code site docs format and it didn't provide a way of doing inline code formatting. So they will be become ``--with-apxs``.

**Comment by GrahamDumpleton** [comment]
Closing as thing the double dash instances were all dealt with long ago.
