### ISSUE TITLE
@rpath issue on OSX

### ISSUE THREAD

**Issue by zedrdave** [GrahamDumpleton/mod_wsgi#173]
When trying to run mod_wsgi-express with the following command on OS X (using Anaconda):

`mod_wsgi-express start-server wsgi.py`

I received the following error:

`httpd (mod_wsgi-express) : Syntax error on line 155 of /tmp/mod_wsgi-localhost:8000:501/httpd.conf: Cannot load /Users/xxx/anaconda3/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so into server: dlopen(/Users/xxx/anaconda3/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so, 10): Library not loaded: @rpath/libpython3.5m.dylib\n  Referenced from: /Users/xxx/anaconda3/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so\n  Reason: image not found`

The problem appears to be an incorrect @rpath in the library, that I was able to solve by setting a loader_path:
`install_name_tool -add_rpath @loader_path/../../../.. mod_wsgi-py35.cpython-35m-darwin.so`

I am not sure if this might be related to Anaconda (doesn't seem so), and there might be a cleaner solution, but just in case, you may want to look into it…

**Comment by GrahamDumpleton** [comment]
As far as I know this is a problem with Anaconda Python installation and how they create their Python dynamic library. It doesn't seem to affect all Anaconda Python versions though. or maybe it is the MacOS X version.

What version of Anaconda Python are you using?

What version of mod_wsgi is being used? The latest that ``pip install`` uses?

What version of MacOS X is this?

**Comment by zedrdave** [comment]
Anaconda and mod_wsgi are both the latest public version available, using Python 3.5.

OSX is 10.12.1 Sierra (I believe rpath has been introduced recently: either this version or the previous)…

**Comment by GrahamDumpleton** [comment]
In short, as I understand it, the way that Anaconda Python does it breaks using Python in an embedded system, as it is dependent on the main program, usually ``python``, setting so reference location that is used in conjunction with the Python library. This will not work when the library is embedded in Apache as you can't go changing the Apache binary to set whatever the reference path is.

**Comment by zedrdave** [comment]
OK. Then probably Anaconda should be adding @loader_path on executables, each time an environment is activated (and also by default)… or possibly keep separate copies for each environment…

In any case, I guess it's not your problem. I'll look into reporting this to the Anaconda people.

**Comment by GrahamDumpleton** [comment]
I will still have a go at trying to sort it when I get some time. I may be able to workaround it by finding some special linker option I can get Python to use when building the mod_wsgi module. Right now bit hard to look at it as am half blind from going to eye doctors so bit difficult to focus, and not just mentally. :-)

**Comment by GrahamDumpleton** [comment]
Totally forget that there is a workaround for this.

Create a file called ``envvars`` and in it add:

```
export DYLD_LIBRARY_PATH=/Users/xxx/anaconda3/lib
```

The run ``mod_wsgi-express`` with additional argument of ``--envvars envvars``.

Am close to another solution I may be happy with wouldn't require manual workaround.

**Comment by GrahamDumpleton** [comment]
Try:

```
pip install -U https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

No workaround needed.

This may only work for Python 3.5 at this point. Need to go back and look at older Python versions.

**Comment by GrahamDumpleton** [comment]
Change appears to work for Anaconda Python 2.7 as well. Also so happened that chose configuration variables that only Anaconda Python sets, so change doesn't kick in for other Python distributions.

Let me know if solves issue and after some more checks and when I finish some other work, will make a release.

**Comment by yihengli** [comment]
@GrahamDumpleton This answer saves my life.
I just installed python3.5 from brew and had the same issue. 
'''

**Comment by GrahamDumpleton** [comment]
@yihengli Are you saying you used the ``develop`` version from the GitHub repo with Brew and it worked? The change I made was Anaconda specific as far as I knew and be surprised if it worked on Brew. Or are you saying you used the ``--envvars`` workaround?

**Comment by yihengli** [comment]
@GrahamDumpleton 
Yes, I basically used
`pip3 install -U https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip`

And amazingly it works with the python3.5 I installed with `brew install python3`

MacOS 10.12.1

**Comment by GrahamDumpleton** [comment]
That was a complete accident then. That said, I knew of know issue within using Brew anyway.

Can you do me a favour and run:

```
mod_wsgi-express module-config
```

and tell me the result.

I want to confirm that it shows a ``LoadFile`` line and what the value is.

If it is what I think it is, even more surprised it worked as it is loading the Python framework direct into Apache and not the ``.dylib`` file as it does with Anaconda.

At least that is what I am guessing is happening as my Brew installation appears to be somewhat trashed and isn't working so can't properly confirm myself. Am going to have to completely uninstall all additional Python versions and Brew and start over. :-(

**Comment by yihengli** [comment]
I got
`LoadModule wsgi_module "/usr/local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so"
WSGIPythonHome "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5"`

hope this helps

**Comment by GrahamDumpleton** [comment]
If you have installed it in the last two hours, then that output indicates that the Anaconda Python change was not the reason why it now works. Just in case you managed to install it in a small time window a bit over two hours ago, can you look in ``/tmp/mod_wsgi-localhost:8000:501/httpd.conf`` and see if there is a ``LoadFile`` line in that and what its value is.

**Comment by yihengli** [comment]
<IfDefine MOD_WSGI_LOAD_PYTHON_DYLIB>
LoadFile ''
</IfDefine>

**Comment by yihengli** [comment]
And when I tried to uninstall the current one and install the original one, the syntax error came again.
```
pip3 uninstall mod_wsgi
pip3 install mod_wsgi
mod_wsgi-express start-server
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:501
Server Conf        : /tmp/mod_wsgi-localhost:8000:501/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8000:501/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_CA.UTF-8
httpd (mod_wsgi-express) : Syntax error on line 155 of /tmp/mod_wsgi-localhost:8000:501/httpd.conf: Cannot load /usr/local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so into server: dlopen(/usr/local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so, 10): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.5/Python\n  Referenced from: /usr/local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so\n  Reason: image not found
```
And there is no `loadfile` in `file:///tmp/mod_wsgi-localhost:8000:501/httpd.conf`

**Comment by GrahamDumpleton** [comment]
I have absolutely no idea then. There should not be any other notable difference.

Probably doesn't matter but I would try:

```
pip install -U --no-cache mod_wsgi
```

and see if that still fails.

If it does, take a copy of the ``httpd.conf`` file.

Then install the 'develop' one and compare the ``httpd.conf`` files.

Maybe there was a strange cached compiled version of prior version in the cache.

**Comment by yihengli** [comment]
It seems like the problems are related caches.

`pip3 install -U --no-cache mod_wsgi`
fixed the issue and the error msg won't show up any more.

**Comment by GrahamDumpleton** [comment]
That is useful to know.

What possibly happened is that the compiled version was cached, but then Python installed by brew was updated. Brew uses versioned directories for installs, so the version in the directory path possibly changed and the compiled in shared library references in the compiled cached version were then wrong. When using pip it can't know about any of that and will blindly installed the version compiled earlier which was cached.

**Comment by yihengli** [comment]
That's probably what's going on there. I did a lot of tweaks when directly compiling from the source code. (Though not work) Maybe some files were messed up at that point.

**Comment by M0rtenB** [comment]
This thread also helped me immensely. I had the error on my system with a conda-based Python 3.6 installation. Will this Anaconda-specific fix make it into the main branch?

**Comment by GrahamDumpleton** [comment]
@M0rtenB How are you compiling/installing mod_wsgi?

If you use the ``pip install`` method for building it, and using the Apache configuration snippet generated by ``mod_wsgi-express module-config`` to load mod_wsgi into Apache, then it is believed it should work fine with Anaconda Python.

You can find more details about this install method on:

* https://pypi.python.org/pypi/mod_wsgi

So I really need to know how you are installing it and what errors you are getting. As far as I know this issue should already have been closed. If you have a new problem when using the recommended install method, please create a new issue. I will look properly through this issue again later and close it as necessary.

**Comment by M0rtenB** [comment]
I just replayed my steps. I'm on MacOS 10.12.3, using Homebrew-built Apache 2.4.23. Fresh miniconda install in ~/conda.

`conda create --name py36 python=3.6`
`which pip` points to `~/conda/envs/py36/bin/pip`
`pip install mod_wsgi` (Successfully installed mod-wsgi-4.5.14)
`mod_wsgi-express module-config` prints the following

```
LoadFile "/Users/mortenb/conda/envs/py36/lib/libpython3.6m.dylib"
LoadModule wsgi_module "/Users/mortenb/conda/envs/py36/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-darwin.so"
WSGIPythonHome "/Users/mortenb/conda/envs/py36"
```

I paste these exact lines into my ´httpd.conf´, comment out all other mod_wsgi-related lines and run ´sudo apachectl restart´. This gives the following error:

```
httpd: Syntax error on line 222 of /usr/local/etc/apache2/2.4/httpd.conf: Cannot load /Users/mortenb/conda/envs/py36/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-darwin.so into server: dlopen(/Users/mortenb/conda/envs/py36/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-darwin.so, 10): Library not loaded: /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/Python\n  Referenced from: /Users/mortenb/conda/envs/py36/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-darwin.so\n  Reason: image not found
```

I then run `pip install -U https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip` and try `sudo apachectl restart`  again. This time it works.

**Comment by GrahamDumpleton** [comment]
There isn't any difference between ``develop`` branch and 4.5.14, so it shouldn't make a difference.

The image not found error generally indicates that the correct architecture (32/64 bit) is not present. All MacOS X binaries should be 64 bit these days.

So I am not sure. If you want to investigate further, can only suggest do ``pip uninstall mod_wsgi`` to uninstall it and try again. Run the uninstall multiple times until it definitely says not present.

**Comment by GrahamDumpleton** [comment]
Closing as not sure anything else I need to do at this point.

**Comment by bhargavvader** [comment]
I have the exact same problem, using OS X El Capitan 10.11.6, Python 3.5.2, and mod_wsgi version 4.6.4. I am using virtualenv as my virtual environment, and install mod_wsgi using `pip install mod_wsgi`. I also tried using `pip3 install -U --no-cache mod_wsgi`, but it doesn't solve my problem. My /tmp/mod_wsgi-localhost:8000:501/httpd.conf file is empty.
@GrahamDumpleton any idea what I can do?

**Comment by GrahamDumpleton** [comment]
Please don't ask new questions on old issues, especially closed ones.

Please create a new question and in it fully describe your problem, including details of what Python installation you are using, where it is installed, commands used to activate virtual environment, run ``pip`` etc etc, so don't have to assume what you have done, which may well be different to the above. Thanks.
