### ISSUE TITLE
MPM_Worker module enabled but pre-configuration failed

### ISSUE THREAD

**Issue by deveshaggrawal19** [GrahamDumpleton/mod_wsgi#179]
I' m developing a flask (python) application on an apache2 server. Watching your talk on PyCon to make apache2 less suck for python applications, I decided to give mpm_worker a try, but now I'm stuck because It needs recompiling of PHP. I cannot simply disable PHP because I need it for PHPMyAdmin. Can you tell me what can I do to fix this error?

**Comment by GrahamDumpleton** [comment]
Don't use worker MPM. Just ensure you are using mod_wsgi daemon mode at least. A lot of PHP stuff may not work even if rebuild PHP for worker MPM as PHP people don't build stuff with multithreading in mind and no gaurantee things would work.

**Comment by deveshaggrawal19** [comment]
Thank you for the advice, I'll work on it.
