### ISSUE TITLE
Python3 Fails a Script in Reloading Source Code

### ISSUE THREAD

**Issue by lxylxy123456** [GrahamDumpleton/mod_wsgi#182]
In [Reloading Source Code](https://modwsgi.readthedocs.io/en/develop/user-guides/reloading-source-code.html), I copied the code to detect the performing mode to my application, but Apache2 returned an error. It seems that 
`return [output]`
should be changed to 
`return [output.encode()]`
and then everything goes well. 

I am using Python 3.4.2 and Apache 2.4.10, and libapache2-mod-wsgi-py3 4.3.0-1 in Debian.

**Comment by GrahamDumpleton** [comment]
Correct. Many examples haven't been converted to work with Python 3.

Rather than encode at the last step, the literal strings can be written as:

    output = b'EMBEDDED MODE'

That will work for both Python 2 and 3.

**Comment by GrahamDumpleton** [comment]
Finally gone and updated examples in that doc and also in checking installation guide, so work with both Python 2 and 3..
