### ISSUE TITLE
'mod_wsgi.Log' object has no attribute 'name'

### ISSUE THREAD

**Issue by cjwelborn** [GrahamDumpleton/mod_wsgi#184]
The docs for Python 2/3 file-like objects don't require a `name` attribute on file-like objects. The [docs for Python 3](https://docs.python.org/3/glossary.html#term-file-object) don't even mention a `name`, and the [Python 2 docs](https://docs.python.org/2/library/stdtypes.html#file.name) only say:

> This is a read-only attribute and may not be present on all file-like objects.

It sure would be nice to have one on `mod_wsgi.Log` though. I only say that because of [this bug](https://github.com/ipython/ipython/issues/6386) I found when launching my django app. Somehow after calling `dir()` on the object a `name` attribute came up, but a call to `getattr(obj, 'name')` fails with an `AttributeError`. This sounds a lot like issue #85 (the attribute was `fileno` there).

I've worked up a [pull request](https://github.com/ipython/ipython/pull/10191) for `ipython` to get around the issue I was having with `pygments`/`ipython`, but would it be too much to ask for `mod_wsgi.Log().name`?

Honestly, anyone trying to do `getattr(filelike, 'name')` should probably be prepared for it to fail, though it failed in a very unexpected way this time (`dir()` said it was there). I also think a name would come in handy for debugging purposes. Maybe the name could be `'<wsgi.log>'` or something similar.

@GrahamDumpleton, what do you think about it?

**Comment by GrahamDumpleton** [comment]
Yeah, I can add that. Have had to add other attributes/methods to the log objects previously even though optional and code isn't supposed to assume they exist, such as``isatty()`` , which the Python docs specifically say you are not supposed to implement if the file like object is not associated with a file. You can't assume people will read docs and accomodate they don't exist though.

**Comment by cjwelborn** [comment]
Awesome, I had a feeling you would understand this better than anyone after looking at some of the past issues. Thanks 😀

**Comment by GrahamDumpleton** [comment]
Has been added. You can try the ``develop`` branch of the repo if you want, or download:

* https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip

**Comment by cjwelborn** [comment]
That was quick 😀. I'll check it out ASAP.

**Comment by GrahamDumpleton** [comment]
Released as 4.5.14 now.
