### ISSUE TITLE
MacOS 10.12  installation error

### ISSUE THREAD

**Issue by yuqingcai** [GrahamDumpleton/mod_wsgi#186]
In MacOS 10.12.2, the Apache Portable Runtime was not included, I need to build it myself and make a link to the xtoolchain as bellow:

tar -xjf apr-1.5.2.tar.bz2
tar -xjf apr-util-1.5.4.tar.bz2

cd apr-1.5.2/
./configure
make
make install
                
cd ../apr-util-1.5.4/
./configure --with-apr=/usr/local/apr
make
make install

sudo mkdir -p /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/
sudo mkdir -p /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/share/apr-1/build-1/
sudo ln -s /usr/local/apr/bin/apu-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apu-1-config
sudo ln -s /usr/local/apr/bin/apr-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config
sudo ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool  /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/share/apr-1/build-1/libtool

cd mod_wsgi-4.5.14/
./configure
make

finally, I got error: 
error: ./libtool: unknown option character `-' in: --silent

It seems that MacOS 's libtool is'nt same as the usual libtool, the compiling failed.

**Comment by GrahamDumpleton** [comment]
Use the ``pip install`` method of installing mod_wsgi to build on MacOS X Sierra and later.

* https://pypi.python.org/pypi/mod_wsgi

That is:

```
pip install mod_wsgi
```

and then:

```
mod_wsgi-express module-config
```

to get the configuration you need to add to the Apache configuration file.

Read the documentation on the PyPi site.

**Comment by yuqingcai** [comment]
OK! It works!
