### ISSUE TITLE
input stream returns more than requested 10KB

### ISSUE THREAD

**Issue by ilatypov** [GrahamDumpleton/mod_wsgi#187]
The wsgi.input stream in Apache mod_wsgi 4.5.13 with Python 2.7 returns the entire form input exceeding the requested amount of 10KB.

https://gist.github.com/ilatypov/2de85ab4dcaf186ee7e2eabe261c1e8d

The above application, when integrated with Apache, outputs the following on my pressing the Submit button,

<pre>
next chunk: 10240, received: 10241 
</pre>

This was found due to a framework not expecting wsgi.input return more bytes than requested,

https://github.com/pallets/werkzeug/issues/1068

**Comment by GrahamDumpleton** [comment]
For me, the exact program you supply outputs:

```
next chunk: 10235, received: 10235
```

If I add 5 more characters to input I get:

```
next chunk: 10240, received: 10240
```

If I add 6 more characters to input I get:

```
next chunk: 10240, received: 10240
next chunk: 1, received: 1
```

The example therefore seems to work fine for me.

Same result no matter whether I used embedded mode or daemon mode.

**Comment by ilatypov** [comment]
I got what I thought a set of binary API synched Windows VC9 builds of Python 2.7.13 from https://www.python.org/downloads/release/python-2713/ , Apache 2.4.25 from https://www.apachehaus.com/cgi-bin/download.plx , mod_wsgi 4.5.13 from http://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi.

<pre><code>
$ sha1sum /cygdrive/d/Python27/python.exe
26014f4ef2e731afe0b043d6a5fd8ffb57b3fb85 */cygdrive/d/Python27/python.exe

$ md5sum /cygdrive/c/HOME/Downloads/python-2.7.13.msi
0f057ab4490e63e528eaa4a70df711d9 */cygdrive/c/HOME/Downloads/python-2.7.13.msi

$ sha1sum /cygdrive/d/Python27/Lib/site-packages/mod_wsgi/server/mod_wsgi.pyd
a0454f3a50a74a968ab00296e2a56ddc14ab5b9e */cygdrive/d/Python27/Lib/site-packages/mod_wsgi/server/mod_wsgi.pyd

$ md5sum /cygdrive/c/HOME/Downloads/mod_wsgi-4.5.13+ap24vc9-cp27-cp27m-win32.whl
b0f236d866e3f6ac95a9b96b1bd65ba9 */cygdrive/c/HOME/Downloads/mod_wsgi-4.5.13+ap24vc9-cp27-cp27m-win32.whl

$ sha1sum /cygdrive/d/Apache24/bin/httpd.exe
20aef5b06bda3793ace8695f93e6d880a0807dcb */cygdrive/d/Apache24/bin/httpd.exe

$ md5sum /cygdrive/c/HOME/Downloads/httpd-2.4.25-x86.zip
0190f922b110abb904c80cdc12b5658a */cygdrive/c/HOME/Downloads/httpd-2.4.25-x86.zip
</code></pre>

**Comment by GrahamDumpleton** [comment]
I wouldn't use those mod_wsgi binaries. I would suggest you compile it yourself to ensure that it has been compiled for the specific Apache version you are using. If you don't then no guarantee it will work. They are definitely unlikely to work with Cygwin version of Apache.

I would also strongly recommend against Python 2.7, as there aren't recent Apache binaries which are compiled for VC9 compiler that Python 2.7 requires.

Can you use Python 3.5 instead and use the Python Software Foundation Python package?

**Comment by ilatypov** [comment]
None of these builds use Cygwin.  I will take a look at upgrading.  I was only using a web application written with Python 2 in mind.

**Comment by GrahamDumpleton** [comment]
See if you can upgrade, because if your Apache isn't cygwin version, the fact that it is Apache 2.4 means it can't have been compiled with VC9 as I know of no Apache 2.4 distributions out there which have been compiled for VC9.

If you do want to still try Python 2.7, if you have the ability to build C extension modules in Python packages, and have ``pip`` available, do the following.

Set the ``MOD_WSGI_APACHE_ROOTDIR`` environment variable to ``D:\Apache24``.

Run:

```
pip install mod_wsgi
```

Then:

```
mod_wsgi-express module-config
```

Use what is output as Apache configuration to load the mod_wsgi module that was compiled by ``pip install``.

**Comment by cgohlke** [comment]
> the fact that it is Apache 2.4 means it can't have been compiled with VC9 as I know of no Apache 2.4 distributions out there which have been compiled for VC9.

They are available at https://www.apachehaus.com/cgi-bin/download.plx#APACHE24VC09

**Comment by cgohlke** [comment]
The example hello.py works for me on Python 2.7.13 for Windows with VC9 builds from Apache Haus and mod_wsgi‑4.5.14+ap24vc9

**Comment by cgohlke** [comment]
> The example hello.py works for me on Python 2.7.13 for Windows with VC9 builds from Apache Haus and mod_wsgi‑4.5.14+ap24vc9

Ignore that. It wasn't actually running on Apache...

I can now reproduce the issue on Python 2.7.13 for Windows with VC9 builds from Apache Haus and mod_wsgi‑4.5.14+ap24vc9.

**Comment by ilatypov** [comment]
We seem to be converting a Python integer argument of stream.read(size) into a 32-bit long, then place these bytes in least significant bytes of a 64-bit apr_off_t in both 32-bit and 64-bit Windows.  

https://github.com/GrahamDumpleton/mod_wsgi/blob/master/src/server/mod_wsgi.c#L1252

Since the apr_off_t value had -1, it becomes a big negative.  

In another unexpected behaviour, line 1384 begins reading in "all the remaining data" when size is negative.

**Comment by GrahamDumpleton** [comment]
Sorry for delay, been busy with backlog of stuff after a couple of trips. Can you try:

* https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip

**Comment by ilatypov** [comment]
Thanks, it worked.

![image](https://cloud.githubusercontent.com/assets/30419/22864174/637aba28-f11a-11e6-96d1-2e1c4a1c9b3a.png)

(I followed an error message in "setup.py build" syggesting to install Microsoft's VC9 compiler for Python 2.7, saw a compiler error on missing ap_config.h and copied ap_config.h from the Apache 2.4.25 source.  I stopped Apache2.4, ran pip uninstall mod_wsgi from Command Prompt, ran setup.py install mod_wsgi, changed the pointer to mod_wsgi.pyd in my Apache httpd.conf file, then started Apache2.4).

I have couple comments:

- systems that have no HAVE_LONG_LONG will seem to be using an int size but decode a long on top of it, according to the lower-case-L "l" descriptor.  I wonder if "int size" should have read "long size".

- I saw a few warnings from the VC9 compiler on "possible loss of data",
<pre><code>src/server\mod_wsgi.c(1329) : warning C4244: 'function' : conversion from '__int64' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1341) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1347) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1364) : warning C4244: 'function' : conversion from 'apr_off_t' to 'apr_size_t', possible loss of data
src/server\mod_wsgi.c(1388) : warning C4244: 'function' : conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1429) : warning C4244: 'function' : conversion from '__int64' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1445) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1455) : warning C4244: 'function' : conversion from 'apr_off_t' to 'apr_size_t', possible loss of data
src/server\mod_wsgi.c(1481) : warning C4244: 'function' : conversion from '__int64' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1489) : warning C4244: 'function' : conversion from 'apr_off_t' to 'apr_size_t', possible loss of data
src/server\mod_wsgi.c(1512) : warning C4244: 'function' : conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1567) : warning C4244: 'function' : conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1613) : warning C4244: 'function' : conversion from 'apr_off_t' to 'apr_size_t', possible loss of data
src/server\mod_wsgi.c(1642) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1646) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1659) : warning C4244: 'function' : conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1678) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1704) : warning C4244: 'function' : conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1746) : warning C4244: 'function' : conversion from 'apr_off_t' to 'apr_size_t', possible loss of data
src/server\mod_wsgi.c(1775) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1779) : warning C4244: 'function' : conversion from 'apr_off_t' to 'size_t', possible loss of data
src/server\mod_wsgi.c(1787) : warning C4244: 'function' : conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
src/server\mod_wsgi.c(1803) : warning C4244: 'function' : conversion from 'apr_off_t' to 'Py_ssize_t', possible loss of data
</code></pre>

**Comment by GrahamDumpleton** [comment]
Fixed the ``int/long`` issue. Also applied same overall changes to ``readline()`` for ``wsgi.input`` as well as it would be similarly affected.

The warnings relate to unsigned to signed conversions. So the negative values become invalid. I believe this is okay as the ``<0`` case is always treated in a special way and so should never be passed to any of the function calls where the warning arises. I should at some point add an appropriate type cast to just to get rid of the warnings.

**Comment by GrahamDumpleton** [comment]
Hmmm, I don't think I released this. Still sitting in develop branch. Will try and release today.

**Comment by GrahamDumpleton** [comment]
Finally released.

**Comment by ilatypov** [comment]
64-bit Windows was also affected before the fix.

https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os

I guess the root cause was in a discrepancy between the "at least" data type used by PyArg_ParseTuple for "l" and the fixed width data type used by APR.  I guess the former is advanced by the C compiler efficiency, the latter seems driven by the filesystem format.
