### ISSUE TITLE
Changing AppArmor hats for mod_wsgi daemon processes per vhost

### ISSUE THREAD

**Issue by groman2** [GrahamDumpleton/mod_wsgi#191]
I'm trying to add a mod_wsgi config to Apache 2.4 that uses WSGIDaemonProcess on a per-vhost basis. I use mod_apparmor with a hand tuned Hat for every vhost.

The mod_wsgi daemons, unfortunately, stay unconfined.

Is there apparmor support in wsgi? 
If not, what's the most straightforward way of adding it?

**Comment by GrahamDumpleton** [comment]
As I understand it mod_apparmor only changes the context for a request during the period that it is being handled within the Apache child worker process. In mod_wsgi daemon mode, the requests are handled in a separate process and the Apache child worker processes are merely proxying the request.

I have no idea how one would utilise apparmor in this arrangement. Presumably you need to change context for the whole daemon process when it is first started. That would require deeper changes in mod_wsgi to be aware of apparmor system to do that. It could not be a default feature as then you are trying things to apparmor. Thus would need to be something that is optionally compiled in at build time of mod_wsgi.

The question is what are you relying on apparmor to do. One can already tell each daemon process group to run as a different user to what Apache is running as.

Only other options right now would be to run separate mod_wsgi-express instances for each vhost separate to Apache and have Apache proxy to them. You could then separately restrict what each mod_wsgi-express instance does.

A variation on that is to run each mod_wsgi-express instance in a Docker container. I have talked about that specific way of doing things in blog post previously.

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

The proxying parts of this still all apply if running mod_wsgi-express without Docker.

**Comment by groman2** [comment]
That makes sense. That's sort of what I expected. I'll take a look at proxying to a container, since I'm relying on apparmor to have an exhaustive and auditable whitelist of file system paths each vhost can access.

**Comment by GrahamDumpleton** [comment]
Going to close this at this point as not much I can do. If have any further information down the track based on anything you learnt drop a further comment with details.
