### ISSUE TITLE
How to compile from windows 7

### ISSUE THREAD

**Issue by z-z** [GrahamDumpleton/mod_wsgi#192]
Hi!

Help me, please =)
How to compile mod_wsgi for Windows 7 (WAMP 3, Apache 2.4)+Python 3.5 ??

"./configure" in source dir give error "apxs: command not found"

I installed apxs, after that in apache bin dir created file "apxs.pl"

after that

./configure --with-apxs="C:/wamp64/bin/apache/apache2.4.23/bin/apxs.pl"

checking Apache version... 2.4.23
checking for python... /c/Python35//python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: write() argument must be str, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: write() argument must be str, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: write() argument must be str, not None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: write() argument must be str, not None
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "<string>", line 1, in <module><br>
TypeError: write() argument must be str, not None
configure: creating ./config.status
config.status: creating Makefile

and

$ C:/MinGW/bin/mingw32-make
C:/wamp64/bin/apache/apache2.4.23/bin/apxs.pl -c -Ic:\Python35\include    mod_wsgi.c -Wl,-F -framework
  /nologo /MD /W3 /O2 /D WIN32 /D _WINDOWS /D NDEBUG    -I"C:\wamp64\bin\apache\
APACHE~1.23\include"  /I"c:\Python35\include"  /c /Fomod_wsgi.lo mod_wsgi.c
"/nologo" is not an internal or external command, an executable program, or a batch file.
apxs:Error: Command failed with rc=65536
.
Makefile:29: recipe for target 'mod_wsgi.la' failed
mingw32-make: *** [mod_wsgi.la] Error 1

**Comment by GrahamDumpleton** [comment]
You cannot use config/make/make install method on Windows.

If you have all the correct architecture for each thing, ie., all 64 bit, and you can pip install packages, do the following.

Set the environment variable for current shell (not globally) of 

    MOD_WSGI_APACHE_ROOTDIR="C:/wamp64/bin/apache/apache2.4.23"

Must be forwards slashes.

Then run:

    pip install mod_wsgi

Then run:

    mod_wsgi-express module-config

Take the output of that and add it to the Apache configuration file.

Restart Apache to make sure restarts.

Add configuration for your WSGI application.

Graham

**Comment by z-z** [comment]
Thank you! It works =)
