### ISSUE TITLE
pyodbc stopped working with Apache/Mod_wsgi

### ISSUE THREAD

**Issue by youxit5** [GrahamDumpleton/mod_wsgi#195]
I am deploying a Django project to a Redhat 4.8 server. One of the views retrieves some information from a SQL Server database on a different Windows server. I installed ODBC Driver 11 for SQL Server/unixODBC/pyodbc. The connection string runs successfully on Python shell inside the Virtualenv. But when running with Apache/Mod_wsgi, I got the following error:

```
('HYT00', '[HYT00] [unixODBC][Microsoft][ODBC Driver 11 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
Request Method:	GET
Request URL:	.....
Django Version:	1.10.6
Exception Type:	OperationalError
Exception Value:	
('HYT00', '[HYT00] [unixODBC][Microsoft][ODBC Driver 11 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
Exception Location:	/var/www/ProjectTest/pythonproject/rcbi/homepage/views.py in homepage, line 7
Python Executable:	
Python Version:	3.5.1
Python Path:	
['/var/www/ProjectTest/pythonproject/rcbi',
 '/var/www/ProjectTest/pythonvenv/rcbitest/lib/python3.5/site-packages',
 '/usr/local/lib/python3.5/site-packages/mod_wsgi-4.5.15-py3.5-linux-x86_64.egg',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
```

Here is the configuration of a Vhost:

```
<VirtualHost *:80>
  ServerName  ....... 
  WSGIScriptAlias /   /var/www/ProjectTest/pythonproject/rcbi/rcbi/wsgi.py 
  WSGIDaemonProcess   Testsite1  python-path=/var/www/ProjectTest/pythonproject/rcbi:/var/www/ProjectTest/pythonvenv/rcbitest/lib/python3.5/site-packages
  WSGIProcessGroup    Testsite1 
  WSGIApplicationGroup %{GLOBAL}

  <Directory /var/www/ProjectTest/pythonproject/rcbi/> 
    Order allow,deny 
    Allow from all 
    Options FollowSymLinks 
    AllowOverride None 
    Require all granted 

    <Files wsgi.py> 
      Require all granted 
    </Files> 

  </Directory>       

  Alias /static/  /var/www/ProjectTest/pythonproject/rcbi/homepage/static/ 

  <Directory /var/www/ProjectTest/pythonproject/rcbi/homepage/static/> 
    Require all granted 
  </Directory>

</VirtualHost>
```

version:

python 3.5 
pyodbc 3.1.1 (tried 3.0.10)
mod-wsgi-4.5.15

I tried to add  WSGIApplicationGroup %{GLOBAL} and still receive the same error. The server hangs for some and time out with error. I would really appreciate if you could provide some insights on this. 

Thank you

**Comment by GrahamDumpleton** [comment]
Any reason why you are using such an older pyodbc version?

The pyodbc package has a chequered history as far as working correctly under mod_wsgi.

Can you try version 4.0.8 of pyodbc?

Don't use version 4.0.9 or later, as they trigger other problems.

**Comment by GrahamDumpleton** [comment]
Hmmm, seems 4.0.8 is not available on PyPi. So that may not be possible.

**Comment by GrahamDumpleton** [comment]
I don't think it will make a difference, but just to be sure, can you change:

```
  WSGIScriptAlias /   /var/www/ProjectTest/pythonproject/rcbi/rcbi/wsgi.py 
  WSGIDaemonProcess   Testsite1  python-path=/var/www/ProjectTest/pythonproject/rcbi:/var/www/ProjectTest/pythonvenv/rcbitest/lib/python3.5/site-packages
  WSGIProcessGroup    Testsite1 
  WSGIApplicationGroup %{GLOBAL}
```

to:

```
  WSGIDaemonProcess   Testsite1  \
    python-home=/var/www/ProjectTest/pythonvenv \
    python-path=/var/www/ProjectTest/pythonproject/rcbi

  WSGIScriptAlias / /var/www/ProjectTest/pythonproject/rcbi/rcbi/wsgi.py \
    process-group=Testsite1 application-group=%{GLOBAL}
```

This uses preferred way to specify the virtual environment and also explicitly binds the WSGI application declared by the ``WSGIScriptAlias`` to the main interpreter context of the daemon processes.

Also outside of the ``VirtualHost`` add:

```
WSGIRestrictEmbedded On
```

This just makes sure that something about the configuration is causing code to execute in Apache worker processes in embedded mode and sub interpreter.

**Comment by GrahamDumpleton** [comment]
Actually, 4.0.8 is probably still there, just hidden on index page.

**Comment by youxit5** [comment]
Thank you very much for your help. I tried pyodbc 4.0.16, and it caused some issue. That's why I started from the earliest version. The problem was resolved by changing some security setting in Linux by our Server Admin..

**Comment by GrahamDumpleton** [comment]
Version 4.0.16 of pyodbc only just got released and promises to fix the sub interpreter issues. Am hoping that is the case.
