### ISSUE TITLE
Lacking of ap_config.h, apache_noprobes.h when install latest version(4.5.15) of mod_wsgi module

### ISSUE THREAD

**Issue by langdeyouhuo** [GrahamDumpleton/mod_wsgi#196]
Hi Graham,

In windows 7,
Apache 2.2(apachehaus),
when I use pip to install mod_wsgi(4.5.15) ,
it comes out the error of lacking ap_config.h, apache_noprobes.h.

when I use pip to install mod_wsgi(4.5.0),
it comes out the error of 'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.

Could you please help me about this? Thank you very much.

Best Regards
langdeyouhuo

**Comment by GrahamDumpleton** [comment]
Your Apache installation must be in one of the following directories:

* C:/Apache22
* C:/Apache24
* C:/Apache

I can only verify ApacheLounge distro working. Some other distros do not include header files and can't be used to compile additional modules.

If your Apache is in a different directory, temporarily set the environment variable ``MOD_WSGI_APACHE_ROOTDIR`` to the location of the root of the Apache installation. That is, the directory which contains the ``include`` and ``lib`` directories. The path must be specified with POSIX style forward slashes, not backslashes. The environment variable needs to be set when running ``pip install mod_wsgi``, but isn't needed after that.

When done, run:

```
mod_wsgi-express module-config
```
to generate the configuration you should then include in the ``httpd.conf`` of the Apache distribution. You cannot use ``mod_wsgi-express start-server`` on Windows.

**Comment by langdeyouhuo** [comment]
Thank you very much! It makes sense.

**Comment by GrahamDumpleton** [comment]
Let me know if you sort it out and I will close the issue. Thanks.

**Comment by GrahamDumpleton** [comment]
Closed as no further response. Assuming was resolved.
