### ISSUE TITLE
Default values for the options of WSGIDaemonProcess

### ISSUE THREAD

**Issue by archatas** [GrahamDumpleton/mod_wsgi#197]
Can you please add the default values for all options in WSGIDaemonProcess in the [documentation](http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html)?

That would make it easier to orientate what values we are talking about: bytes, KB or MB; seconds or minutes.

If the defaults don't exist for all options, can you then add several reasonable examples of configurations for different types of websites: regular small website, fast performant, with heavy load?

**Comment by GrahamDumpleton** [comment]
Which options in particular are you talking about? From a read through the options, all those which have some sort of default value have a text description about what that default is. Where a default isn't mentioned the options don't doing anything by default.

For my view on what are reasonable values to override options, see what ``mod_wsgi-express`` does. That is, did ``pip install mod_wsgi`` and then run ``mod_wsgi-express start-server --help`` and also run ``mod_wsgi-express start-server`` and look at the generated ``httpd.conf`` file it uses.

**Comment by archatas** [comment]
I have just tried to run mod_wsgi in embedded mode and it really shows the defaults in the help and verbose output of `mod_wsgi-express start-server`. Thanks for explanation.

Just when someone uses the daemon mode (which is mentioned by default in Django documentation) and goes directly to the documentation of WSGIDaemonProcess, it's not clear what are the reasonable values for the following options: `restart-interval`, `maximum-requests`, `inactivity-timeout`, `request-timeout`, `startup-timeout`, `graceful-timeout`, `eviction-timeout`, `socket-timeout`, `queue-timeout`, `cpu-time-limit`, `memory-limit`, `virtual-memory-limit`, `receive-buffer-size`, `send-buffer-size`, `response-socket-timeout`. It would be helpful to have those default values also mentioned in the documentation.

**Comment by GrahamDumpleton** [comment]
Added a list of options to use as starting point based on what ``mod_wsgi-express`` uses in:

* http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html

Closing this issue now.
