### ISSUE TITLE
WSGIDontWriteBytecode option not recognized under Python 3

### ISSUE THREAD

**Issue by robhancocksed** [GrahamDumpleton/mod_wsgi#199]
The WSGIDontWriteBytecode directive is not being recognized when using Python 3 with mod_wsgi. Looking at the source code, it appears that the code that processes this option is conditional on "#if PY_MAJOR_VERSION == 2" and will not be built when using Python 3.

**Comment by GrahamDumpleton** [comment]
That code would have been added when Python 3.2 or earlier was all that existed. In whatever version it was, that capability didn't exist. I see that it is now in Python 3.3 and later at least. So need to update code to enable for Python 3.3+.

**Comment by GrahamDumpleton** [comment]
Change made in develop branch for later 4.5.16 release.
