### ISSUE TITLE
windows64,python3.5,  mod_wsgi can work?

### ISSUE THREAD

**Issue by zzngb** [GrahamDumpleton/mod_wsgi#200]
i wanted to use mod_wsgi in windows64 and python3.5.but i don't find mod_wsgi.so anywhere.

**Comment by GrahamDumpleton** [comment]
You can compile it yourself if you have the correct MS compiler and can install Python packages using ``pip``.

* https://wiki.python.org/moin/WindowsCompilers

Ensure you have Apache 2.4 under ``C:\Apache24``, or set ``MOD_WSGI_APACHE_ROOTDIR`` environment variable to where it is located, then run:

```
pip install mod_wsgi
```

Then run:

```
mod_wsgi-express module-config
```

That will generate the configuration you need to add to Apache configuration file to load mod_wsgi.

Then add configuration for your specific WSGI application.

I would recommend Apache from:

* https://www.apachelounge.com/

**Comment by zzngb** [comment]
thank you very much,i solved the problem using your mothod.thank you again.
