### ISSUE TITLE
apache flask and python3.6 - need help!

### ISSUE THREAD

**Issue by priyachakka26** [GrahamDumpleton/mod_wsgi#203]
Hi - 

I am trying to invoke flask app on the apache server . I have installed all the corresponding software . But seems like because of various versions of python that got installed I am getting issue like below and I am not able to resolve it . I would really appreciate all your time and help in getting this resolved . 

I have a Linux environment,so I have used the below command and installed apache

 yum install httpd

Server version: Apache/2.4.6 (CentOS)

2.installed python3.6 
 
  yum -y install python36u
  python3.6 -V
  yum -y install python36u-pip
  yum -y install python36u-devel
  pip3.6 install mod_wsgi
  pip3.6 install Flask

3.when I do the

ldd mod_wsgi.so 

linux-vdso.so.1 =>  (0x00007ffca49f4000)
	libpython3.6m.so.1.0 => /lib64/libpython3.6m.so.1.0 (0x00007fe69f878000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe69f65b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe69f29a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe69f096000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fe69ee92000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe69eb90000)
	/lib64/ld-linux-x86-64.so.2 (0x0000562eb60ec000)

so it is pointing to the right python 

4.in the httpd.conf file : 

WSGIPythonHome "/usr/local/bin/python3.6"
WSGIPythonPath /usr/local/lib/python3.6/site-packages/:/usr/local/lib/python3.6:/usr/local/bin/python3.6 
WSGIDaemonProcess test python-home=/usr/local/lib/python3.6 python-path=/usr/local/lib/python3.6
WSGIProcessGroup test
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias /flasktest /etl/XXX/src/scripts/test/test.wsgi
WSGIRestrictEmbedded On

<Directory /etl/XXX/src/scripts/test>
    Order deny,allow
    Allow from all
    Require all granted
</Directory>

5.I am running as root 

but still I get the problem of : 

Wed May 24 19:21:11.479638 2017] [mpm_prefork:notice] [pid 29714] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/4.5.15 Python/3.6 configured -- resuming normal operations
[Wed May 24 19:21:11.479680 2017] [core:notice] [pid 29714] AH00094: Command line: 'httpd'
[Wed May 24 19:21:17.304048 2017] [wsgi:error] [pid 29715] ['/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib64/python36.zip', '/usr/local/lib/python3.6/lib64/python3.6', '/usr/local/lib/python3.6/lib64/python3.6/lib-dynload']
[Wed May 24 19:21:17.304167 2017] [wsgi:error] [pid 29715] ['/etl/XXX/src/scripts/test', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib64/python36.zip', '/usr/local/lib/python3.6/lib64/python3.6', '/usr/local/lib/python3.6/lib64/python3.6/lib-dynload']
[Wed May 24 19:21:17.305220 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956] mod_wsgi (pid=29715): Target WSGI script '/etl/XXX/src/scripts/test/test.wsgi' cannot be loaded as Python module.
[Wed May 24 19:21:17.305328 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956] mod_wsgi (pid=29715): Exception occurred processing WSGI script '/etl/XXX/src/scripts/test/test.wsgi'.
[Wed May 24 19:21:17.311542 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956] Traceback (most recent call last):
[Wed May 24 19:21:17.311577 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956]   File "/etl/XXX/src/scripts/test/test.wsgi", line 8, in <module>
[Wed May 24 19:21:17.311581 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956]     from test import app
[Wed May 24 19:21:17.311585 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956]   File "/etl/XXX/src/scripts/test/test.py", line 1, in <module>
[Wed May 24 19:21:17.311586 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956]     from flask import Flask, request
[Wed May 24 19:21:17.311596 2017] [wsgi:error] [pid 29715] [remote 172.17.0.3:41956] ModuleNotFoundError: No module named 'flask'

my scripts are in the : /etl/XXX/src/scripts/test/

test.py : 

```
from flask import Flask, request 
app = Flask(__name__) 
@app.route('/hello') 
def hello_world(): 
  name = request.args.get('name','') 
  return 'Hello ' + name + '!' 
if __name__ == '__main__': 
  app.run() 
```

test.wsgi:

```
import sys 

print(sys.path)
#Expand Python classes path with your app's path 
sys.path.insert(0, '/etl/coda/src/scripts/test') 

print(sys.path)
from test import app

application=app 
```

**Comment by GrahamDumpleton** [comment]
As you are using the ``pip`` installation method to bootstrap a system Apache installation, you should run:

```
mod_wsgi-express module-config
```

to get the directives to include in the Apache configuration to load the mod_wsgi module and set up Python location correctly.

If you use that output, since you installed mod_wsgi in a Python virtual environment to start with, you should only need to then add:

```
WSGIDaemonProcess test
WSGIScriptAlias /flasktest /etl/XXX/src/scripts/test/test.wsgi process-group=test application-group=%{GLOBAL}
WSGIRestrictEmbedded On
```

Do though ensure you review the documentation for setting up a Python virtual environment anyway, as you were giving the options incorrect paths.

See:

* http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by GrahamDumpleton** [comment]
Closing as no followup, so assuming problem resolved.
