### ISSUE TITLE
Compatilibity error?

### ISSUE THREAD

**Issue by ddd-malay** [GrahamDumpleton/mod_wsgi#205]
Hi!

I am getting following error:
Starting httpd: httpd: Syntax error on line 202 of /etc/httpd/conf/httpd.conf: Cannot load XXX/site-packages/mod_wsgi/server/mod_wsgi-py34.cpython-34m.so into server: XXX/site-packages/mod_wsgi/server/mod_wsgi-py34.cpython-34m.so: undefined symbol: ap_unixd_config
                                                           [FAILED]

Apache 2.2.15
Python 3.4
using pip install mod_wsgi (in virtualenv)

I understand that mod_wsgi should be looking for unixd_config and not ap_unixd_config. How to proceed?

Thanks.

**Comment by GrahamDumpleton** [comment]
Your Apache version is too old.

Is there are a reason you are using such an old Apache 2.2 version, and not latest Apache 2.2 or even Apache 2.4.

**Comment by GrahamDumpleton** [comment]
I should also add that the underlying cause is likely because the Linux distro has possibly backported patches to Apache, but the way that has been done it has broken all modules which require the Apache code version mechanism to be used properly.

In the mod_wsgi code you will find:

```
#if !AP_MODULE_MAGIC_AT_LEAST(20081201,0)
#define ap_unixd_config unixd_config
#endif
```

So for older Apache versions the symbol ``ap_unixd_config`` is mapped to the old name for it.

Problem is that a back ported patch for Apache has updated the version numbers that ``AP_MODULE_MAGIC_AT_LEAST`` looks at even though it left out various changes in between the base version and what the patch came from. So any modules which depend on a version number check for anything in between will fail.

All you can do if you cannot update Apache is to change the mod_wsgi code and change the above to just:

```
#define ap_unixd_config unixd_config
```

That is, remove the version check.

**Comment by ddd-malay** [comment]
Thanks very much.

Could you also direct to the location of file for mod_wsgi?

We are using OpenVZ virtualization and unable to upgrade Apache. Looking
forward to change VPS.
On 27 May 2017 11:33 a.m., "Graham Dumpleton" <notifications@github.com>
wrote:

I should also add that the underlying cause is likely because the Linux
distro has possibly backported patches to Apache, but the way that has been
done it has broken all modules which require the Apache code version
mechanism to be used properly.

In the mod_wsgi code you will find:

#if !AP_MODULE_MAGIC_AT_LEAST(20081201,0)
#define ap_unixd_config unixd_config
#endif

So for older Apache versions the symbol ap_unixd_config is mapped to the
old name for it.

Problem is that a back ported patch for Apache has updated the version
numbers that AP_MODULE_MAGIC_AT_LEAST looks at even though it left out
various changes in between the base version and what the patch came from.
So any modules which depend on a version number check for anything in
between will fail.

All you can do if you cannot update Apache is to change the mod_wsgi code
and change the above to just:

#define ap_unixd_config unixd_config

That is, remove the version check.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GrahamDumpleton/mod_wsgi/issues/205#issuecomment-304430670>,
or mute the thread

**Comment by GrahamDumpleton** [comment]
Don't understand exactly what you are asking when you say:

> Could you also direct to the location of file for mod_wsgi?

**Comment by ddd-malay** [comment]
It may be silly. I could not find where to make the changes suggested by you. When you say "mod_wsgi code", which file you are referring to?

Thanks.

**Comment by GrahamDumpleton** [comment]
The source code is available from this Git repository. The file is ``src/server/wsgi_apache.h``. You would have to make the change and then compile it. As you are using ``pip`` install method, you could checkout the repo, make the change and then run ``pip install .`` in the top level directory.

**Comment by ddd-malay** [comment]
Thanks. That was helpful.

When I tried to check installation using mod_wsgi-express start-server, it returned:
httpd (mod_wsgi-express) : Syntax error on line 3 of /tmp/mod_wsgi-localhost:8000:500/httpd.conf: Cannot load XXX/site-packages/mod_wsgi_packages/httpd/modules/mod_version.so into server: XXX/site-packages/mod_wsgi_packages/httpd/modules/mod_version.so: cannot open shared object file: No such file or directory

**Comment by GrahamDumpleton** [comment]
Did you install ``mod_wsgi-httpd`` at some point? Was that intentional?

**Comment by ddd-malay** [comment]
Yes. It was intentional. Although later found out that it was not required.
Removed it.

**Comment by GrahamDumpleton** [comment]
If you are still having that problem after it was removed, then it wasn't removed properly. Ensure you run ``pip uninstall mod_wsgi-httpd`` until it says nothing installed.

**Comment by ddd-malay** [comment]
Its working now. Thanks for your patience.

I have a query. For reference, I am listing down the steps in sequential order.

1. sudo yum remove httpd httpd-devel
2. activate virtualenv
3. pip uninstall mod_wsgi-httpd
4. pip uninstall mod_wsgi
5. sudo yum install httpd httpd-devel
6. pip install mod_wsgi
7. sudo find / -name "wsgi_apache.h" : no file returned
8. pip unistall mod_wsgi
9. download tar file, extract it
10. make suggested changes in src/server/wsgi_apache.h
11. python setup.py install
12. deactivate virtualenv
13. sudo service httpd restart

It worked. My query is about step #7. What did I miss?

**Comment by GrahamDumpleton** [comment]
You didn't miss anything. ``pip`` installs source code to a temporary directory and removes it after installation is done (or if it fails).

Presumably you also ran ``mod_wsgi module-config`` to get what you needed to include in the Apache configuration file to have mod_wsgi loaded. Plus, configured mod_wsgi in Apache configuration to load your WSGI application.

**Comment by GrahamDumpleton** [comment]
Closing this as assumed all resolved now.
