### ISSUE TITLE
Error when trying to run mod_wsgi-express start-server

### ISSUE THREAD

**Issue by anechita** [GrahamDumpleton/mod_wsgi#208]
I installed mod_wsgi using pip on my mac running OSX 10.12.5 and anaconda python 3.5.3. When I try to launch the mod_wsgi-express test server if fails with the following error:

`httpd (mod_wsgi-express) : Syntax error on line 159 of /tmp/mod_wsgi-localhost:8000:501/httpd.conf: Cannot load /Users/xxx/anaconda/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so into server: dlopen(/Users/xxx/anaconda/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so, 10): Library not loaded: /Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libgcc_s.1.dylib\n  Referenced from: /Users/xxx/anaconda/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so\n  Reason: image not found`

I'm at a loss to what this means, especially the repeated "placehold" stuff. Also, this references a /Users/ray directory, which is confusing since that is not my username.

**Comment by GrahamDumpleton** [comment]
What version of Anaconda Python are you using? Is it recent?

The Anaconda Python folks are very good at breaking the ability to use their distro in an embedded system. I thought I had sufficient workarounds in place to address all known problems. This error message seems to be another related problem, but I haven't see this specific one before.

At a guess though, it looks like Anaconda Python is now even ignoring system gcc libraries and using their own, as well as system OpenSSL libraries (which I did know about). If this is the case, then Anaconda Python is once again unusable with mod_wsgi within Apache and this time there may not be a solution.

**Comment by anechita** [comment]
I'm using 4.3.22.

**Comment by GrahamDumpleton** [comment]
Are you able to try with 4.4.0?

**Comment by anechita** [comment]
I just uninstalled anaconda followed by a clean install of 4.4.0 and that seems to have fixed it. It worked perfectly the first time I installed via pip.

**Comment by GrahamDumpleton** [comment]
Excellent. Was starting to get worried enough that was forever broken that started ranting on Twitter about the problems. I will close this issue then. Thanks for letting me know.

BTW, do be aware though that when using Anaconda Python, you will not be able to use SSL features of Apache to handle secure connection termination. This is because the Anaconda Python OpenSSL libraries are incompatible with system OpenSSL libraries and use of mod_ssl in Apache will cause system OpenSSL libraries to be used, causing any use of SSL in Python to break.
