### ISSUE TITLE
Hop-By-Hop Headers between WSGI and Apache

### ISSUE THREAD

**Issue by pradeepks** [GrahamDumpleton/mod_wsgi#209]
I am developing an application and flow is something like this

**FLOW**
Client->APACHE->WSGI APP  -> WebSocket(NoVNC)
WSGI script is  basically proxying for websocket so I can authenticate session.

WebSocket uses HTTP for authentication and uses following headers.
Following Headers are sent from WSGIAPP-> Websocket(NOVNC)

**Request Headers**
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:Upgrade
Host:x.x.x.x:port
Origin:https://x.x.x.x:port
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:aCZSE+XwI9wT8lnjfNK7iQ==
Sec-WebSocket-Protocol:binary, base64
Sec-WebSocket-Version:13
Upgrade:websocket

I am able to connect from WSGIAPP->websockify and after authentication it generates
the following http response headers
**Response Headers**
Connection:Upgrade
Date:Wed, 28 Jun 2017 14:30:00 GMT
Sec-WebSocket-Accept:CBH7KVq0KEruYFH44dRxgH2eBko=
Sec-WebSocket-Protocol:binary
Server:WebSockify Python/2.7.5
Upgrade:websocket

When I give back this response from WSGI APP to Apache , it looks APACHE doesn't like and
complains internal server error.

I know Upgrade, Connection are considered as 'hop-by-headers' as per WSGI Spec. But not 
sure how it is implemented in wsgi module and apache.  

Is there any workaround this issue ?

**Comment by GrahamDumpleton** [comment]
The WSGI specification, nor typical way Apache is used, really support both way HTTP traffic at the same time. You cannot therefore proxy web sockets via a WSGI compliant server. For Apache, only way to proxy web sockets properly is using web socket specific proxying support in Apache, or a separate Apache module purpose built for web sockets.

**Comment by pradeepks** [comment]
Yes, apache uses mod_ws_tunnel for proxying web sockets.  But only problem with it is it doesn't support authentication using existing session information, although it provides other mechanisms- password, sqldb. Need to explore other alternatives of achieving the same.

**Comment by pradeepks** [comment]
But in case of websockets, only auth part of websockets happens through HTTP and later 2 way communication(Data Traffic)  happens through websocket protocol, packets doesn't even come to Apache/WSGI.  So this is not exactly 2 way communication of HTTP.

**Comment by GrahamDumpleton** [comment]
WSGI specification followed CGI which effectively required the complete request content to be consumed before a response can be sent, with the size of the request content needing to be known in advance. Implementations tend to be based around that model, which generally makes it impossible to support the idea of reading partial inbound content, return partial outbound content, go back and read more inbound content, return more outbound content etc. There is also no concept in WSGI of being able to upgrade a connection and so WSGI servers don't support being able to disable any components deal with data flow which are specific to normal HTTP data flow.

**Comment by GrahamDumpleton** [comment]
Closing at this point. There is separate work being done on whether mod_wsgi can support ASGI but it would still be high level and no access to hop by hop headers, as shouldn't be necessary.
