### ISSUE TITLE
Get *.so file after installing mod_wsgi with pip

### ISSUE THREAD

**Issue by alexvelickiy** [GrahamDumpleton/mod_wsgi#213]
Hi, 

I've successfully installed mod_wsgi with pip. Where can I find or how can I get mod_wsgi.so file to load it as module in apache conf?

**Comment by GrahamDumpleton** [comment]
As documented in section "Connecting into Apache installation" of:

* https://pypi.python.org/pypi/mod_wsgi

run:

```
mod_wsgi-express module-config
```

The output of that command is what you should put in the Apache configuration file to load the mod_wsgi module.

You still need to then configure it to load your specific WSGI application.
