### ISSUE TITLE
Restart the apache problem 

### ISSUE THREAD

**Issue by absolve** [GrahamDumpleton/mod_wsgi#215]
I used apache + Django + Mod_wsgi  on Windows to develop projects .When the project is complete ,I found that on window when I restart apache,There will be more httpd.exe in the process list .
![image](https://user-images.githubusercontent.com/6998235/29199989-23551360-7e84-11e7-9b0d-facf8a6b740a.png)
![image](https://user-images.githubusercontent.com/6998235/29200005-40dda744-7e84-11e7-9949-d345f1e48a60.png)
When I stop apache, there's an httd.exe left in the list of processes 
![image](https://user-images.githubusercontent.com/6998235/29200049-b0e517ca-7e84-11e7-89d4-15eb0cfa43c5.png)
![image](https://user-images.githubusercontent.com/6998235/29200053-b8aa56e6-7e84-11e7-97b6-6325bbe0c52e.png)
Restarting multiple times will have more progress 
I installed mod_wsgi with PIP . apache(2.4.27),Django(1.10),python(2.7.13),cx-Oracle (5.3)
All of them are vc9 compilations,32 bit.
You have to stop and start the service

**Comment by GrahamDumpleton** [comment]
And what happens if you use a WSGI hello world program, with not additional packages being used such as Django or cx_Oracle?

Whose Apache distribution are you using?

**Comment by absolve** [comment]
I downloaded apache from the https://www.apachehaus.com/cgi-bin/download.plx#APACHE24VC09 website .,32 bit vc9.
I tested hello.wsgi program I found an interesting phenomenon .
After the first boot service ,I visited the local website .
Restart the apache service ,add an HTTP. Exe process ...
![image](https://user-images.githubusercontent.com/6998235/29202986-c325f1b4-7e9f-11e7-9800-f080904d9feb.png)
After refreshing the site, it's gone .

**Comment by GrahamDumpleton** [comment]
I only trust the Apache distribution from www.apachelounge.com. That is the only one I tested with. For some other Apache distributions you can't even compile the module as they are missing header files.

**Comment by absolve** [comment]
There is no vc9 compilation  version on the apachelounge website .The 2.7 version on the python website is a vc9 compilation .
I copied the .h file from apache which was downloaded from apachelounge website. You can compile it.

**Comment by GrahamDumpleton** [comment]
You cannot copy the header files from one Apache distribution to another and be sure it works. At least one file is generated based on the specific Apache version and machine configuration used when compilation was done. If you take that to a different Apache binary distribution, there is no guarantee that it will be compatible. So if you are using header files from ApacheLounge in order to be able to compile the module with ApacheHaus, this could be the source of your problems.

Why can't you use Python 3.6? There is usually no good reason to still be using Python 2.7.

**Comment by absolve** [comment]
Because the project was completed using py2.7,If upgrading to py3x could cause some problems .
I'm going to try py3x first .
best wish.

**Comment by GrahamDumpleton** [comment]
Another reason you can get that error is if you installed Python for only your own user and not the whole system. This can occur when use a service manager like you are as it wants to run Apache as a separate user and will not have access to the Python you installed as just your own user.

**Comment by absolve** [comment]
I found the source of the problem. In the python file,I wrote a heartbeat thread.
In the threading.thread run () function，The code looks like this，
def run(self):  
		while(1):
			......
			time.sleep(30)
It's a dead cycle. I use it this way.
UserHeart=MyHeartThread()
UserHeart.start()
The thread setDaemon (True) function is not used. When you restart apache, The process will not exit.
It's going to cause this problem,But the exact principle is not very clear.

**Comment by GrahamDumpleton** [comment]
When the Python interpreter is being destroyed, it will wait on non daemon threads to exit first. It will not wait on daemon threads.

When you create a thread, unless you call ``setDaemon()`` with some value, it will inherit the attribute from the thread it is created in. So if you create a thread from a daemon thread, but don't flag it as such, then it will still be a daemon thread.

If pre-loading of the WSGI script file is enabled, then that thread would be a non daemon thread, so if you start a thread as a side effect of loading the WSGI script file, but don't mark it as a daemon thread, it will also be marked as a non daemon thread in that case. This would cause issues on process shutdown.

If pre-loading of the WSGI script file was not enabled, and so the WSGI script file was loaded on the first request, that thread is a daemon thread and so thread created as side effect of loading the WSGI script file would also be a daemon thread. Thus shouldn't see an issue.

I can only surmise you must have configured mod_wsgi in a way to preload the WSGI script file. That in combination with not marking the thread as daemon would cause the issue.

What doesn't make sense though, is that Apache should have a fail safe whereby if the process doesn't shutdown within 5 seconds, it will forcibly kill it. This occurs on UNIX systems at least. I don't know about Windows, but maybe it doesn't have the fail safe to kill off the worker process on a restart.

**Comment by absolve** [comment]
Thank you very much for your reply,The explanation is very detailed.
best wish.
