### ISSUE TITLE
mod_wsgi-express silently fails starting

### ISSUE THREAD

**Issue by frague59** [GrahamDumpleton/mod_wsgi#216]
Hi, 

From https://stackoverflow.com/questions/45617886/mod-wsgi-express-service-not-stating

I'm trying to use mod_wsgi-express for a django project. This project will be served through a "main" server wild) instance of apache as proxy. My purpose is to serve a python 3 application with a mod_wsgi for python 2 installed on the "main" apache server. (I've many apps on the same server)

I've created a systemd service which should launch the mod_wsgi-express instance, using my own service files :

https://gist.github.com/frague59/87529fc28b098dd116f09be92cf66af0

and env :

https://gist.github.com/frague59/8de1d03800042db95c82452af280dffe

I've to mention that those scripts works on another server, same distro, same version (debian oldstable), but with mod_wsgi 4.5.15

... but the mod_wsgi-express does not start : no error message, no log...

I've noticed that a dir is created in tmp:

```
/tmp/mod_wsgi-127.0.0.1:8081:993
```

I've tried to start the apachectl from here:

```sh
# cd /tmp/mod_wsgi-127.0.0.1:8081:993
# apachectl configtest
```

And I have a weird message:

```
AH00526: Syntax error on line 241 of /tmp/mod_wsgi-127.0.0.1:8081:993/httpd.conf:
Invalid option to WSGI daemon process definition.
```

I posts the generated httpd.conf file for example:

https://gist.github.com/frague59/a6d8d26b704565b39f7352a7c16e07d3

Error seems to be around:

send-buffer-size=0 \

I've set a --send-buffer-size 1024 on the StartExec .service file, and it fixes the problem...

+ Is the default value **0** relevant ?
+ Is the options parsing relevant, as **0** avoid the server to start silently ? 

Thanks !

**Comment by frague59** [comment]
I've updates the gist: 

+ https://gist.github.com/frague59/87529fc28b098dd116f09be92cf66af0 : service file
+ https://gist.github.com/frague59/8de1d03800042db95c82452af280dffe : service env file

**Comment by GrahamDumpleton** [comment]
Have you redone it using ``--server-root``?

There is nothing wrong with the syntax of that file when I verify it against my own Apache/mod_wsgi.

Also, run this command repeatedly.

```
pip uninstall mod_wsgi
pip uninstall mod_wsgi-httpd
```

until it says there is nothing to uninstall.

Then install again using:

```
pip install mod_wsgi
```

You may have a Python installation or virtual environment which is screwed up in some way and is somehow finding an old mod_wsgi.so from an old version.

**Comment by GrahamDumpleton** [comment]
Closing as no followup by OP.
