### ISSUE TITLE
Python 2.7, xampp, windows 7, mod_wsgi, Failed to build mod_wsgi

### ISSUE THREAD

**Issue by Fayjovi** [GrahamDumpleton/mod_wsgi#219]
Hi,

I've been trying to install mod_wsgi in python for last 2 weeks but still no solution. following are details for my setup
Python 2.7
Xampp apache 2.4.23
windows 7

Previsouly i has python installed with anaconda and i tried your instruction but got the error ValueError: \x escape

then i downloaded from your link and followed the instruction ran mod_wsgi-express module-config and add the configuration in apache conf file. Unfortunately apache failed to start.
I unistalled anaconda and install python 2.7. tried installing with pip but got the error "Failed to build mod_wsgi"

Please can you help me i tried search everywhere but couldnt get solution. There is no documentation on how to properly installed or why this error is dislaying. Please guide me.

**Comment by GrahamDumpleton** [comment]
Sorry, this got buried in my inbox due to being busy.

Is there a specific reason you are using Python 2.7 and not 3.6. Things go more smoothly with 3.6. Some people have issues with 2.7. Also, it isn't readily possible to find Apache 2.4 compiled for same VC9 compiled that Python 2.7 requires. If the compiler version doesn't match, it reduces chances it will work.

**Comment by Fayjovi** [comment]
Thanks Graham for your response.
Actually i just started to learn Python and the tutorial i followed suggests to use 2.7. I though i should get the basic first from earlier version and after getting some understanding i would switch to Python 3. I started with CGI and did some pages that worked well. 

Only reason i wanted to use WSGI is to use Python without any Framework but i think it doesnt work that way so i decided to try Django. Need your advice should i start Django or stick to WSGI?? 
Again thanks for your reply.

**Comment by GrahamDumpleton** [comment]
For something simple I would suggest using Flask.

Either way, I would recommend against trying to do anything with raw WSGI. There are so many corner cases and gotchas to writing raw WSGI properly. It is better to use at least a small WSGI framework such as Flask to do all the hard work for you.

**Comment by Fayjovi** [comment]
Thank you very much Graham for your response and guidance. I choose Django and i think its a good way to learning.
