### ISSUE TITLE
variable presistance across sessions

### ISSUE THREAD

**Issue by birdmw** [GrahamDumpleton/mod_wsgi#221]
previously when using mod_wsgi, I could store a global variable (object) and edit it between user sessions. Now, suddenly that persistence is lost. I can't find any support on this topic. Is there something in Apache which can trigger a WSGI file to be reloaded anew with each successive call as opposed to the behavior where variables persist between multiple user requests over time?

**Comment by GrahamDumpleton** [comment]
I believe I answer this on:

* https://stackoverflow.com/questions/46049599/apache-mod-wsgi-python-variable-persistance
