### ISSUE TITLE
Failing to install mod_wsgi

### ISSUE THREAD

**Issue by manatoshadhikari** [GrahamDumpleton/mod_wsgi#223]
I am trying to install mod_wsgi in windows8.1 64 bit machine,
But failing to install using command pip install mod_wsgi

running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  creating build\temp.win-amd64-3.6\Release\src\server
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\Apache24/include -Ic:\users\administrator\appdata\local\programs\python\python36\include -Ic:\users\administrator\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\winrt\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\winrt\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\winrt\um" "-IC:\Program Files (x86)\Windows Kits\10\include\winrt\winrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.6\Release\src/server\mod_wsgi.obj
  mod_wsgi.c
  c:\users\administrator\appdata\local\temp\pip-build-0rf5lzte\mod-wsgi\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws2tcpip.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 

But on searching for the file 'ws2tcpip.h' I could find the same, but in a different path. On checking for the path in Windows Kit , I find that it is having 8.1, 10 and NETFXDK, but I have successfully installed the same in Windows10 machine which is having WIndows Kit 8.1 and 10.
Probably it is a path issue, but cant figure out how to set the correct path to:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe

**Comment by GrahamDumpleton** [comment]
Check that you have the right compiler components installed. See https://github.com/GrahamDumpleton/mod_wsgi/issues/194

**Comment by manatoshadhikari** [comment]
Yes I did checked it has the write component installed, even i did uninstall and installed is again from the link mentioned in the above comment. But still I have the same error.
I my system when I check I find the 3 different version of Visual studio is there

**Comment by GrahamDumpleton** [comment]
I don't know too much about compiling stuff on Windows. Are there any environment variables set which may be overriding the include search path and so interfering with the Python distutils/setuptools package?

**Comment by bgsuello** [comment]
I also have this issue in trying to **update** my current version of mod_wsgi.
And solve it by configuring _**Visual C++ Build Tools path**_:

_`PS C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>`_**` .\vcvarsall.bat amd64_x86`**

where:  _**amd64_x86**_ is my system architecture.

and then: **`pip install mod_wsgi --upgrade`** 
```
Collecting mod_wsgi
  Using cached mod_wsgi-4.5.18.tar.gz
Installing collected packages: mod-wsgi
  Found existing installation: mod-wsgi 4.5.17
    Uninstalling mod-wsgi-4.5.17:
      Successfully uninstalled mod-wsgi-4.5.17
  Running setup.py install for mod-wsgi ... done
Successfully installed mod-wsgi-4.5.18
```

My setup:

- Windows 10 x64 v1701 OS build 15063.608
- Python 3.6.0 x64
- Visual C++ 2017 Build Tools
- mod_wsgi-4.5.18
- Server version: Apache/2.4.27 (Win32)
  Apache Lounge VC14 Server built:   Jul  9 2017 11:48:22

**Comment by GrahamDumpleton** [comment]
No further followup from OP so closing.
