### ISSUE TITLE
Keep getting Target WSGI script cannot be loaded as Python module.

### ISSUE THREAD

**Issue by vtigranv** [GrahamDumpleton/mod_wsgi#224]
All app is working on Python3 and pip3
Ubuntu 16.04
Apache 2.4.18
Flask 0.12.2
Python 3.5.2

To run virtualnenv: `pip3 install virtualenv`

**wsgi.load** (content copied from `mod_wsgi-express module-config` )
```
LoadModule wsgi_module "/usr/local/lib/python3.5/dist-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr/"
```

**Virtual host conf:**
```
<VirtualHost *>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    ServerName fronty.com
    ServerAdmin info@fronty.com

    WSGIDaemonProcess fronty user=www-data group=www-data threads=5 python-home=/var/www/html/fronty/venv
    WSGIScriptAlias / /var/www/fronty.wsgi
    # WSGIRestrictEmbedded On

    <Location /var/www/html/fronty>
      WSGIProcessGroup fronty
      WSGIApplicationGroup %{GLOBAL}
      Require all granted
    </Location>
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

**fronty.wsgi**
```
#!/var/www/html/fronty/venv/bin/python3.5
import sys
sys.path.append('/usr/local/lib/python3.5/dist-packages/')
activate_this = '/var/www/html/fronty/venv/bin/activate_this.py'
with open(activate_this) as file_:
    exec(file_.read(), dict(__file__=activate_this))

from fronty import app as application
```

**Apache log errors:**
```
[mpm_event:notice] AH00491: caught SIGTERM, shutting down
[mpm_event:notice] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.5.18 Python/3.5 configured -- resuming normal operations
[core:notice] AH00094: Command line: '/usr/sbin/apache2'


mod_wsgi (pid=17027): Target WSGI script '/var/www/fronty.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=17027): Exception occurred processing WSGI script '/var/www/fronty.wsgi'.
Traceback (most recent call last):
  File "/var/www/fronty.wsgi", line 21, in <module>
    from fronty import app as application
ImportError: No module named 'fronty'
```

**Comment by GrahamDumpleton** [comment]
Use the ``python-path`` option to ``WSGIDaemonProcess`` to tell mod_wsgi where the parent directory of the ``fronty`` package is.

You don't need:

```
activate_this = '/var/www/html/fronty/venv/bin/activate_this.py'
with open(activate_this) as file_:
    exec(file_.read(), dict(__file__=activate_this))
```

as that is what ``python-home`` option to ``WSGIDaemonProcess`` does.

This looks suspiciously wrong:

```
sys.path.append('/usr/local/lib/python3.5/dist-packages/')
```

If you are using a Python virtual environment, you should install any packages into it. You should not be still trying to use the system Python packages as that could cause conflicts over versions of packages.

**Comment by vtigranv** [comment]
Thanks a lot for reply.
Actually when I move .wsgi file near to the folder /fronty it started to work. Not sure whether it's correct or not, but it works now :)

And also made the changes you mentioned
Thanks again for help!

**Comment by GrahamDumpleton** [comment]
Move where the ``.wsgi`` file is shouldn't have made a difference as modules will not be searched relative to it. The ``python-path`` has to be set and no way to avoid it. Anyway, at least it is working.
