### ISSUE TITLE
 Cannot load /etc/httpd/modules/mod_wsgi.so into server: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rushipatel-delight** [GrahamDumpleton/mod_wsgi#225]
I am running RHEL server and top of it i have different version of python.
Since i am same machine i have copied the python files as i dont need to compile the files again i just copiedd that to new server and also copied the mod_wsgi.so from previous machine and edited the bachrc file to point to the python 2.7 interpreter.
If i do ldd  i can see the file too
 ldd /etc/httpd/modules/mod_wsgi.so
        linux-vdso.so.1 =>  (0x00007ffe63d0e000)
        libpython2.7.so.1.0 => /frame/frame_src/frame_config/python/Python-2.7.10/lib/libpython2.7.so.1.0 (0x00007f60cd610000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f60cd3e8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f60cd1e4000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f60ccfe1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f60ccd5c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f60cc9c8000)
        /lib64/ld-linux-x86-64.so.2 (0x00000030a3e00000)

**Comment by GrahamDumpleton** [comment]
What did you add to the ``bashrc`` file?

Whatever you put in that will be ignored by Apache/mod_wsgi, but I want to see what you add so I can understand better what you are doing.

As is, it looks like the target machine doesn't even have Python 2.7 installed on it.

**Comment by rushipatel-delight** [comment]
this is what i have in bashrc file 


alias python=/frame/frame_src/frame_config/python/Python-2.7.10/bin/python2.7
alias pip=/frame/frame_src/frame_config/python/Python-2.7.10/bin/pip
alias easy_install=/frame/frame_src/frame_config/python/Python-2.7.10/bin/easy_install-2.7

export PYTHONPATH=/frame/frame_src/frame_config/python/Python-2.7.10/lib
export LD_LIBRARY_PATH=/frame/frame_src/frame_config/python/Python-2.7.10/lib

export PYTHONHOME=/frame/frame_src/frame_config/python/Python-2.7.10
export PYTHON_EGG_CACHE=/frame/frame_src/python_eggs/main.python-eggs

**Comment by GrahamDumpleton** [comment]
As I said, all of that will be ignored.

You could try adding:

```
LoadFile /frame/frame_src/frame_config/python/Python-2.7.10/lib/libpython2.7.so.1.0
```

just before the ``LoadModule`` line for ``wsgi_module`` and:

```
WSGIPythonHome frame/frame_src/frame_config/python/Python-2.7.10
```

after the ``LoadModule`` line.

Otherwise you have to recompile mod_wsgi and ensure ``LD_RUN_PATH`` is set at the time of compilation to the library directory where Python library will be. See:

* http://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#unable-to-find-python-shared-library

**Comment by rushipatel-delight** [comment]
Thanks it worked
