### ISSUE TITLE
Truncated or oversized response headers received from daemon process 'my process'

### ISSUE THREAD

**Issue by alexvelickiy** [GrahamDumpleton/mod_wsgi#226]
Hi, 

The json.loads function where I pass a JSON-string of length 4187288 causes WSGI error:
`Truncated or oversized response headers received from daemon process 'my process'`

**Comment by alexvelickiy** [comment]
Is it possible that this is due to OS memory limit hit?

**Comment by GrahamDumpleton** [comment]
Check the main Apache error log to see if you see a segmentation fault message, or other message indicating the process may have crashed. See:

```
LogLevel info
```

to have mod_wsgi log extra details about process restarts. That may tell you why the process was restarted and connection to daemon process lost.

**Comment by Richard-Wang-USF** [comment]
I went into same issue and it turns out 'my process' run out of memory.

**Comment by GrahamDumpleton** [comment]
Closing as no followup from OP.
