### ISSUE TITLE
WSGI error - Resource temporarily unavailable, HTTP status 503

### ISSUE THREAD

**Issue by romulomfranca** [GrahamDumpleton/mod_wsgi#228]
Hello! We are having problems with our service. The message is "Resource temporarily unavailable, 503". We have an application in Python e Django.

We update the server instance on AWS. The current server is configured as follows:
- Server version: Apache/2.4.27 (Ubuntu)
- mod_wsgi 4.5.17
- Python 3.6
- Django 1.11.5

CPU and Memory aren't overloaded. 

**Instance EC2:**
- t2.medium (2 core, 4 gb RAM)
- CPU Average: < 20%
- RAM Used Average: ~200MB

**Instância RDS:**
- PostgreSQL 9.5.4
- t2.small (1 core, 2 gb RAM)
- CPU Average: < 40%
- RAM Used Average: ~500MB

We've tried all configurations mentioned in the topic: https://github.com/GrahamDumpleton/mod_wsgi/issues/181

```
WSGIDaemonProcess trac processes=6 threads=1 restart-interval=1500 response-socket-timeout=7 display-name=%{GROUP}
```

Even we update all settings mentioned  in the topic and others topics as: 
https://groups.google.com/forum/#!topic/modwsgi/-kPH_mwyilw

```
request-timeout=10
```

 The error persists. All attempts without success.

I get this in the error.log:

> [wsgi:error] [pid 21399:tid 140274344871680] (11)Resource temporarily unavailable: [client 172.68.27.190:18983] mod_wsgi (pid=21399): Unable to connect to WSGI daemon process 'site' on '/var/run/wsgi.21137.0.1.sock' after multiple attempts as listener backlog limit was exceeded.

Can you help us?

**Our current Virtual Host File**

```
<VirtualHost *:443>
        ServerName my.site.com

        DocumentRoot /var/www/site

        ErrorLog ${APACHE_LOG_DIR}/error-site-ssl.log
        CustomLog ${APACHE_LOG_DIR}/access-site-ssl.log combined

        WSGIScriptAlias / /var/www/site/myapp/myapp/wsgi.py
        WSGIDaemonProcess site python-path=/var/www/site:/var/www/site/env/lib/python3.6/site-packages home=/var/www/site request-timeout=10  
        WSGIProcessGroup site
        WSGIApplicationGroup %{GLOBAL}

        WSGIPassAuthorization On

        SSLEngine on
        SSLCertificateFile /etc/apache2/certificates/mysite.pem
        SSLCertificateKeyFile /etc/apache2/certificates/mysite.key
</VirtualHost>
```

**/etc/apache2/apache2.conf**
```
...
WSGISocketPrefix /var/run/wsgi
```

**Comment by GrahamDumpleton** [comment]
What is the rate of requests you are getting?

What is ``Timeout`` set to in the Apache configuration file?

The error indicates that the WSGI application is overloaded and has reached capacity, but worse is that there are also potentially 100 requests also still queued up.

That or you have many requests which are hanging and not completing, blocking the process and so eventually new requests backlog in the queue until you have more than 100.

**Comment by romulomfranca** [comment]
@GrahamDumpleton 

**Rate of requests:** around 20.000 per hour                        
The **timeout** is 300 (default of Apache)

Is there any configuration option that allows to increase the capacity of the wsgi application?

Thank you.

**Comment by GrahamDumpleton** [comment]
Are you having to restart Apache, or the daemon processes to recover from the error, or is the issue transient and resolves itself?

**Comment by romulomfranca** [comment]
The error appears again within 3 to 10 minutes after restarting Apache.

**Comment by GrahamDumpleton** [comment]
Yes, but is the only way to recover to restart Apache. In other words, is Apache completely hung and does not recover?

**Comment by GrahamDumpleton** [comment]
Also incorporate this code into your application:

* http://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#extracting-python-stack-traces

You will have to update it to work with Python 3.

Everything so far indicates that your code is blocking. That debugging code will allow you to dump out stack traces if where your code is blocking.

**Comment by GrahamDumpleton** [comment]
That is only working because you are causing a process restart before you run out of threads in the thread pool. Use that code to dump stack traces to work out what requests are doing when processes has fully blocked.

**Comment by juliolvfilho** [comment]
Thanks, I will do it right now

**Comment by juliolvfilho** [comment]
Well, I wasn't able to incorporate [that code](http://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#extracting-python-stack-traces) for debug the python stack traces.
However I managed to do it with [this](https://gist.github.com/albertoalcolea/1a41d1676ae36a43ca2d).

I don't think the following exception is related to the problem, but here is the only one that occured:
```
 Traceback (most recent call last):
   File "/var/www/site/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
     rel_obj = getattr(instance, self.cache_name)
 AttributeError: 'Rank' object has no attribute '_account_cache'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/var/www/site/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/var/www/site/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/var/www/site/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 90, in view
     return self.dispatch(request, *args, **kwargs)
   File "/var/www/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
     response = self.handle_exception(exc)
   File "/var/www/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/var/www/site/env/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
     response = handler(request, *args, **kwargs)
   File "/var/www/site/myapp/myapp/views.py", line 226, in list
     'name': functions.get_user_rank_name(r.account),
   File "/var/www/site/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 184, in __get__
     rel_obj = self.get_object(instance)
   File "/var/www/site/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 295, in get_object
     return super(ForwardOneToOneDescriptor, self).get_object(instance)
   File "/var/www/site/env/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 159, in get_object
     return qs.get(self.field.get_reverse_related_filter(instance))
   File "/var/www/site/env/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
     self.model._meta.object_name
 myapp.models.DoesNotExist: Account matching query does not exist.
```
apparently this exception was related to one of ours Django ORM (maybe it only has occurred due to the frequent Apache restarts)

Also, I'd like to mention that using the parameters mentioned above (processess, threads, graceful-timeout, maximum-requests and restart-interval) decreased the rate of errors at Apache that hung it, but the error below is much more frequent:

> [Thu Sep 21 17:54:50.461656 2017] [wsgi:error] [pid 5516:tid 140558810953472] [client 172.68.26.81:16027] Truncated or oversized response headers received from daemon process 'site': /var/www/site/myapp/myapp/wsgi.py

Do you happen to know how to incorporate [your debuging code](http://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#extracting-python-stack-traces) into wsgi.py of Django 1.10+ in order for us to better analyze this issue?

**Comment by GrahamDumpleton** [comment]
The Python 3 variant of the code to use is as follows. You should only need to add this to the end of the ``wsgi.py`` file. If you are having an issue explain what the problem is.

```
import os
import sys
import time
import signal
import threading
import atexit
import queue
import traceback

FILE = '/tmp/dump-stack-traces.txt'

_interval = 1.0

_running = False
_queue = queue.Queue()
_lock = threading.Lock()

def _stacktraces():
    code = []
    for threadId, stack in sys._current_frames().items():
        code.append("\n# ProcessId: %s" % os.getpid())
        code.append("# ThreadID: %s" % threadId)
        for filename, lineno, name, line in traceback.extract_stack(stack):
            code.append('File: "%s", line %d, in %s' % (filename,
                    lineno, name))
            if line:
                code.append("  %s" % (line.strip()))

    for line in code:
        print(line)

try:
    mtime = os.path.getmtime(FILE)
except:
    mtime = None

def _monitor():
    while 1:
        global mtime

        try:
            current = os.path.getmtime(FILE)
        except:
            current = None

        if current != mtime:
            mtime = current
            _stacktraces()

        # Go to sleep for specified interval.

        try:
            return _queue.get(timeout=_interval)
        except:
            pass

_thread = threading.Thread(target=_monitor)
_thread.setDaemon(True)

def _exiting():
    try:
        _queue.put(True)
    except:
        pass
    _thread.join()

atexit.register(_exiting)

def _start(interval=1.0):
    global _interval
    if interval < _interval:
        _interval = interval

    global _running
    _lock.acquire()
    if not _running:
        prefix = 'monitor (pid=%d):' % os.getpid()
        print('%s Starting stack trace monitor.' % prefix)
        _running = True
        _thread.start()
    _lock.release()

_start()
```

**Comment by GrahamDumpleton** [comment]
As to the error about truncated responses, that is further evidence that your requests are hanging in your code. The message indicates the daemon process was forcibly restarted when there were still requests which hadn't completed.

**Comment by romulomfranca** [comment]
Júlio incorporated the code into our application. The log is listed bellow: 

```
[Thu Sep 21 20:19:46.647871 2017] [wsgi:error] [pid 3832:tid 140656531117824] monitor (pid=3832): Starting stack trace monitor.
[Thu Sep 21 20:36:50.677960 2017] [wsgi:error] [pid 4851:tid 139801445459712] (11)Resource temporarily unavailable: [client 172.68.26.81:31565] mod_wsgi (pid=4851): Unable to connect to WSGI daemon process 'site' on '/var/run/wsgi.4626.0.1.sock' after multiple attempts as listener backlog limit was exceeded.
[Thu Sep 21 20:36:50.780769 2017] [wsgi:error] [pid 4740:tid 139801504208640] (11)Resource temporarily unavailable: [client 172.68.25.128:10317] mod_wsgi (pid=4740): Unable to connect to WSGI daemon process 'site' on '/var/run/wsgi.4626.0.1.sock' after multiple attempts as listener backlog limit was exceeded.
[Thu Sep 21 20:36:51.168631 2017] [wsgi:error] [pid 4710:tid 139800891868928] (11)Resource temporarily unavailable: [client 172.68.26.147:15775] mod_wsgi (pid=4710): Unable to connect to WSGI daemon process 'site' on '/var/run/wsgi.4626.0.1.sock' after multiple attempts as listener backlog limit was exceeded.
[Thu Sep 21 20:36:51.289452 2017] [wsgi:error] [pid 4740:tid 139801685145344] (11)Resource temporarily unavailable: [client 172.68.27.52:24937] mod_wsgi (pid=4740): Unable to connect to WSGI daemon process 'site' on '/var/run/wsgi.4626.0.1.sock' after multiple attempts as listener backlog limit was exceeded.
[Thu Sep 21 20:36:51.413455 2017] [wsgi:error] [pid 4851:tid 139801529386752] (11)Resource temporarily unavailable: [client 172.68.27.118:11694] mod_wsgi (pid=4851): Unable to connect to WSGI daemon process 'site' on '/var/run/wsgi.4626.0.1.sock' after multiple attempts as listener backlog limit was exceeded.
[...]
```
The 503 errors only stop when Apache is restarted.

**Comment by GrahamDumpleton** [comment]
Go back and read:

* http://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#extracting-python-stack-traces

The idea is that once you start seeing the errors, create or touch the file:

```
/tmp/dump-stack-traces.txt
```

Creating the file, or modifying its time stamp, will cause the code to dump out the stack traces of where each request handler is currently executing code. You can then analyse the stacks traces to see if the requests are always getting stuck in a certain place, such as on a thread lock, or on a database query or request to some other backend service.

The code by itself doesn't output anything until you touch the file.

So wait for the errors and then run:

```
touch /tmp/dump-stack-traces.txt
```

**Comment by juliolvfilho** [comment]
I did created the `/tmp/dump-stack-traces.txt` file but nothing different was printed on error log.
I also tried to change the timestamp of this file `echo 'a' > /tmp/dump-stack-traces.txt` when the errors was occurring, but nothing different was printed too.

**Comment by juliolvfilho** [comment]
Hello Graham, first thank you for your help and attention to our problem.
continuing the previous message, I changed the if statement in the code for always print the stack trace, independently of the dump-stack-traces.txt file.
Then, I collected several lines from the dump log while the error was happening in search of something that was delaying the application.
I was hoping to find multiple log lines in only one part of the code, indicating that part was holding the application a little longer than normal, but I did not find anything that pointed to this.

Do you think the result could be different if we used ngnix with uWSGI? Or would the result probably be the same?

**Comment by GrahamDumpleton** [comment]
Changing the WSGI server will not necessarily change anything if you have a problem in your code. If you aren't seeing a specific point where things are blocking, it could well be that your code is running, but looping and not returning.

Try adding instead the following code to your ``wsgi.py`` file. This will try and identify which URLs are causing long running requests by monitoring them to completion. This will help to confirm whether this is the issue or not. The statistics output can also be used to track capacity utilisation as another way of tracking it.

So try that and see if you do have long running requests and then can dig more into some of the statistics it generates. 

```
import time
import threading
import os
import mod_wsgi

current_requests = {}

def event_handler(name, **kwargs):
    if name == 'request_started':
        environ = kwargs['request_environ']

        request_data = mod_wsgi.request_data()
        request_data['environ'] = environ
        request_data['tracked'] = False

        request_id = environ['mod_wsgi.request_id']

        current_requests[request_id] = (environ, kwargs, request_data)

    elif name == 'request_finished':
        request_data = mod_wsgi.request_data()
        environ = request_data['environ']
        request_id = environ['mod_wsgi.request_id']
        del current_requests[request_id]

        if request_data['tracked']:
            print('FINISHED %s %s %s' % (request_id, kwargs['application_time'], environ['REQUEST_URI']))

mod_wsgi.subscribe_events(event_handler)

last_metrics = None

def monitor(*args):
    global last_metrics

    while True:
        current_metrics = mod_wsgi.process_metrics()

        if last_metrics is not None:
            cpu_user_time = (current_metrics['cpu_user_time'] -
                    last_metrics['cpu_user_time'])
            cpu_system_time = (current_metrics['cpu_system_time'] -
                    last_metrics['cpu_system_time'])

            request_busy_time = (current_metrics['request_busy_time'] -
                    last_metrics['request_busy_time'])

            request_threads = current_metrics['request_threads']

            # report data

            item = {}
            item['time'] = time.time()
            item['measurement'] = 'process'
            item['process_group'] = mod_wsgi.process_group
            item['process_id'] = os.getpid()

            fields = {}

            fields['cpu_user_time'] = cpu_user_time
            fields['cpu_system_time'] = cpu_system_time

            fields['request_busy_time'] = request_busy_time
            fields['request_busy_usage'] = (request_busy_time /
                    mod_wsgi.threads_per_process)

            fields['threads_per_process'] = mod_wsgi.threads_per_process
            fields['request_threads'] = request_threads

            item['fields'] = fields

            now = time.time()

            header = False
            for request_id, (environ, kwargs, request_data) in list(current_requests.items()):
                running_duration = now - kwargs['application_start']
                # Dump data for requests running longer than 2.0 seconds.
                if running_duration > 2.0:
                    if not header:
                        print('STATISTICS', item)
                        header = True
                    request_data['tracked'] = True
                    print('RUNNING %s %s %s' % (request_id, running_duration, environ['REQUEST_URI']))

        last_metrics = current_metrics

        current_time = current_metrics['current_time']
        delay = max(0, (current_time + 1.0) - time.time())
        time.sleep(delay)

thread = threading.Thread(target=monitor)
thread.setDaemon(True)
thread.start()
```

**Comment by juliolvfilho** [comment]
Hi, Graham
Thank You very much for your script!
Because of it I realized that the delay wasn't in a single point on our code but in almost all requests.
One of the particularities of wsgi is that it is synchronous, isn't it? 
That caused that even simple requests took too long to process due to more complex requests. 
I believe that this problem wouldn't occur if the server behave asynchronically for every request.
So, our solution was to utilize Load Balancer on AWS, after that all the 503 error was gone :-)

Despite that, we believe we shouldn't appeal to this kind of solution due to our low number of users and requests/sec.
How should we configure the wsgi in order to obtain a better performance?

Thanks in advance.

**Comment by GrahamDumpleton** [comment]
Although WSGI is synchronous and not even driven, that doesn't mean only one request can run at a time. You still have multiple threads in a process and so you can still have concurrent requests running.

Multithreading only becomes an issue if your application code is heavily CPU intensive, causing contention issues with the Python global interpreter lock.

Another problem you can have is poor design of your code in that you use thread mutex locks to block large sections of code so only one thread can run in that code at the same time. If this is done poorly then multithreading isn't as effective.

Finally, you could just be trying to handle too much in one process or host and so should if host still has resources, spread across multiple processes, or if host overloaded, use multiple hosts.

Go watch:

* https://www.youtube.com/watch?v=SGleKfigMsk

where I explain these sorts of issues.

**Comment by GrahamDumpleton** [comment]
Am going to close this issue out now. Reopen if there is a need to further followup.

**Comment by PUSHPENDERSINGH786** [comment]
Sep 26 13:00:10.820620 2018] [wsgi:error] [pid 16437:tid 140055662294784] [client 125.164.2.88:42818] Timeout when reading response headers from daemon process 'adidas': /home/Python-/adidas/adidas/wsgi.py
[Wed Sep 26 13:11:02.654857 2018] [wsgi:error] [pid 16437:tid 140055759935232] [client 189.126.68.46:42117] Timeout when reading response headers from daemon process 'adidas': /home/Python-/adidas/adidas/wsgi.py
[Wed Sep 26 13:26:36.482650 2018] [wsgi:error] [pid 16437:tid 140055637116672] [client 61.176.220.76:39758] Timeout when reading response headers from daemon process 'adidas': /home/Python-/adidas/adidas/wsgi.py
[Wed Sep 26 13:29:22.664656 2018] [wsgi:error] [pid 16437:tid 140055768327936] [client 183.205.143.137:35250] Timeout when reading response headers from daemon process 'adidas': /home/Python-/adidas/adidas/wsgi.py, referer: http://www.ijntv.cn/
[Wed Sep 26 13:43:31.798002 2018] [wsgi:error] [pid 16437:tid 140055620331264] [client 58.218.213.44:42402] Timeout when reading response headers from daemon process 'adidas': /home/Python-/adidas/adidas/wsgi.py



Please advice it's getting timeout ...gateway time out  504

**Comment by GrahamDumpleton** [comment]
@PUSHPENDERSINGH786 Create a new issue if still have problems, don't ask questions on existing issues, especially closed ones. Also ensure you are setting ``WSGIApplicationGroup %{GLOBAL}``.

**Comment by PUSHPENDERSINGH786** [comment]
Resolved, thanks for your support.

**Comment by daVincere** [comment]
Hey @GrahamDumpleton thank you for replying so graciously to all these questions. We are facing similar issues and I believe this thread can help us recover from it.

Thank you for your generosity. Cheers!
