### ISSUE TITLE
Option to not rotate daemon listener socket on restarts.

### ISSUE THREAD

**Issue by GrahamDumpleton** [GrahamDumpleton/mod_wsgi#229]
See:

* https://stackoverflow.com/questions/46463199/2no-such-file-or-directory-mod-wsgi-unable-to-connect-to-wsgi-daemon-proces

Very rarely comes up, but an option to not rotate listener socket on restarts for daemon processes might be useful in some cases. Need to consider it.

**Comment by GrahamDumpleton** [comment]
Closing this issue out since change will be in version 4.5.25.

**Comment by Turgon37** [comment]
Hello, I do not see the 4.5.25 release in release page or in git's tags. Can you be more precise about the "change" you have talk about, thanks

**Comment by GrahamDumpleton** [comment]
Use the latest version. There is no good reason to use an older version. Version 4.5.25 probably became 4.6.0. The latest is 4.6.5 and probably a 4.6.6 soon.

**Comment by Turgon37** [comment]
Thanks for your feedback.
I'm on Debian stretch, I'm lock on  4.5.11 release, I've applied the "Keepalive Off" patch on my Apaches until the Debian buster version is released

**Comment by GrahamDumpleton** [comment]
You do understand that Debian packaged releases of mod_wsgi are unsupported. Debian doesn't provide support for them.
