### ISSUE TITLE
mod_wsgi (pid=32322): Exception occurred processing WSGI script '/var/www/html/example/example.wsgi'.

### ISSUE THREAD

**Issue by mahesm4** [GrahamDumpleton/mod_wsgi#230]
Hello Graham Dumpleton,

I have been trying to run my flask application but getting the 500 internal server error

Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   May  9 2017 11:21:32

mod_wsgi 3.4
Python 2.7.5
Flask 0.10.1

Directory structure:
/var/www/html/example
example.py
example.wsgi
__init__.py
DEV_WCC0004.xml

static/
roles.JPG
Logo.JPG
index.JPG

templates/
index.html
test.html

Below is my httpd.conf file entry:
LoadModule wsgi_module modules/mod_wsgi.so
DocumentRoot "/var/www/html"
WSGIDaemonProcess example threads=5
WSGIScriptAlias / /var/www/html/example/example.wsgi
 
<Directory example>
    WSGIProcessGroup example
    WSGIApplicationGroup %{GLOBAL}
    Order deny,allow
    Allow from all
</Directory>
#
# Relax access to content within /var/www.
#
<Directory "/var/www">
    AllowOverride None
    # Allow open access:
    Require all granted
</Directory>

**Comment by GrahamDumpleton** [comment]
Have you looked in the Apache error for details of why the error is occurring? if it is an issue with loading the WSGI script file, it will appear there.

If it is an error from within your application code, then temporarily enable debug mode of Flask by adding at the end of the WSGI script file:

```
application.debug = True
```

That should hopefully tell Flask to display details of the exception back in the browser.

When the issue has been identified that way, remove that debug setting and investigate how you configure flask to log details of exceptions to the terminal (stdout/stderr) by default so their details will be logged in the Apache error log.

**Comment by mahesm4** [comment]
Thanks for the quick response Graham. I did enable the trace in application.

**Found the below in the httpd log:**
[Tue Oct 03 08:10:17.241809 2017] [:error] [pid 23647] [client 49.11.78.60:57410] mod_wsgi (pid=23647): Target WSGI script '/var/www/html/example/example.wsgi' cannot be loaded as Python module.
[Tue Oct 03 08:10:17.241935 2017] [:error] [pid 23647] [client 49.11.78.60:57410] mod_wsgi (pid=23647): Exception occurred processing WSGI script '/var/www/html/example/example.wsgi'.
[Tue Oct 03 08:10:17.242016 2017] [:error] [pid 23647] [client 49.11.78.60:57410] Traceback (most recent call last):
[Tue Oct 03 08:10:17.242783 2017] [:error] [pid 23647] [client 49.11.78.60:57410]   File "/var/www/html/example/example.wsgi", line 4, in <module>
[Tue Oct 03 08:10:17.242996 2017] [:error] [pid 23647] [client 49.11.78.60:57410]     from example import app as application
[Tue Oct 03 08:10:17.243014 2017] [:error] [pid 23647] [client 49.11.78.60:57410]   File "/var/www/html/example/example.py", line 7, in <module>
[Tue Oct 03 08:10:17.243121 2017] [:error] [pid 23647] [client 49.11.78.60:57410]     tree2 = ET.parse("PAT_WCC0004.xml")
[Tue Oct 03 08:10:17.243142 2017] [:error] [pid 23647] [client 49.11.78.60:57410]   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
[Tue Oct 03 08:10:17.243658 2017] [:error] [pid 23647] [client 49.11.78.60:57410]     tree.parse(source, parser)
[Tue Oct 03 08:10:17.243676 2017] [:error] [pid 23647] [client 49.11.78.60:57410]   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 647, in parse
[Tue Oct 03 08:10:17.243705 2017] [:error] [pid 23647] [client 49.11.78.60:57410]     source = open(source, "rb")
[Tue Oct 03 08:10:17.243771 2017] [:error] [pid 23647] [client 49.11.78.60:57410] IOError: [Errno 2] No such file or directory: 'PAT_WCC0004.xml'

**Contents of example.wgi file:**
import sys
sys.path.insert(0, '/var/www/html/example')

from example import app as application

**My investigation:**
1. I have placed the required xml files in the same current directory as the execution file example.py
2. The code works only if I keep the first file DEV_WCC0004.xml but not when I just rename this xml file as PAT_WCC0004.xml and PROD_WCC0004.xml and try to run the flask application.
4. The second & third set of for loops (to parse the xml files -PAT_WCC0004.xml and PROD_WCC0004.xml ) breaks the whole application with 500 internal server error. If I just keep the first set of for loop inside the /echo --> application works perfectly fine.

****`Code inside the python script example.py:`****

from flask import Flask, request, render_template
import xml.etree.ElementTree as ET

tree1 = ET.parse("/var/www/html/example/DEV_WCC0004.xml")
root1 = tree1.getroot()

tree2 = ET.parse("PAT_WCC0004.xml")
root2 = tree2.getroot()

tree3 = ET.parse("PROD_WCC0004.xml")
root3 = tree3.getroot()

app = Flask(__name__)

@app.route("/")
def landing():
    return render_template('index.html')


@app.route("/echo", methods=['POST'])
def echo():
    details1 = []
    details2 = []

    for member in root1.findall('Add'):
        for submember in member.iter('GlobalUser'):
            for username in submember.iter('UserName'):
                if username.text == request.form['text'].lower():
                    details1.append(username.text)
                    for groupname in submember.iter('GroupMembership'):
                        details2.append(groupname.text)

    for member in root2.findall('Add'):
        for submember in member.iter('GlobalUser'):
            for username in submember.iter('UserName'):
                if username.text == request.form['text'].lower():
                    details3.append(username.text)
                    for groupname in submember.iter('GroupMembership'):
                        details4.append(groupname.text)

    for member in root3.findall('Add'):
        for submember in member.iter('GlobalUser'):
            for username in submember.iter('UserName'):
                if username.text == request.form['text'].lower():
                    details5.append(username.text)
                    for groupname in submember.iter('GroupMembership'):
                        details6.append(groupname.text)


    return render_template('result.html', details1=details1, details2=details2)

if __name__ == "__main__":
    app.run(debug=True)

**Comment by mahesm4** [comment]
Thanks for the quick response Graham. I did enable the trace in application and updated the path of the required files and the application  now works fine without the above error in logs anymore.


****`Updated path for the XML files in the python script example.py:`****

from flask import Flask, request, render_template
import xml.etree.ElementTree as ET

tree1 = ET.parse("/var/www/html/example/DEV_WCC0004.xml")
root1 = tree1.getroot()

tree2 = ET.parse("/var/www/html/example/PAT_WCC0004.xml")
root2 = tree2.getroot()

tree3 = ET.parse("/var/www/html/example/PROD_WCC0004.xml")
root3 = tree3.getroot()

It works now !!! Yaaaaaaaayyyyyyyy!!!

**Comment by GrahamDumpleton** [comment]
This issue:

* http://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#application-working-directory

Might be worthwhile reading through that page for other application issues that can arise.

Also take note of suggestion in that section about not hardwiring absolute paths, but calculating them relative to some anchor, possibly relative to ``os.path.dirname(__file__)``.

**Comment by mahesm4** [comment]
Thanks Graham. I will definitely try to use the os.path.dirname(__file__) in conjunction with os.path.join() going forward.
