### ISSUE TITLE
Apache crashes when running with mod_wsgi (Python 3.5 64 bit, Windows 7)

### ISSUE THREAD

**Issue by SebastianFree** [GrahamDumpleton/mod_wsgi#235]
We are using Python 3.5 (which is compiled using VC14), so I installed Apache Lounge 2.4.29 compiled with VC14. This is all on Windows 7. Both, Python and Apache, are 64 bit.

Installing mod_wsgi through pip worked fine. Running 'mod_wsgi-express module-config' returned a path with I added to the httpd.conf file like this:

```
LoadModule wsgi_module "c:/absolute/path/to/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp35-win_amd64.pyd"

WSGIScriptAlias / "c:/absolute/path/to/app/sub_dir/wsgi.py"
WSGIPythonHome "c:/absolute/path/to/venv/scripts"
WSGIPythonPath "c:/absolute/path/to/app"

<Directory 'c:/absolute/path/to/app/sub_dir">
<Files wsgi.py>
Require all granted
</Files>
</Directory>
```

when running httpd, the following error appears and terminates Apache:

> "Apache HTTP Server has stopped working"
> Problem event name: APPCRASH
> Application name: httpd.exe
> Application version: 2.4.29.0
> Fault module name: ucrtbase.dll
> Fault module version: 10.10.10240.16390

Do you have any clue as to what might cause this or what I could try to debug? Thanks!

**Comment by SebastianFree** [comment]
I managed to find the problem. When installing Python, do not allow Python to set the PATH!
Because with the PATH enabled, pip install mod_wsgi in a venv will seem to work fine, yet it doesn't. Using a virtual environment when installing mod_wsgi will still use the global Python repo!

So, when referencing the .pyd file in httpd.conf pointing to the venv as well as setting WSGIPythonHome to the venv, we actually have a pyd file that was compiled using the global Python installation and a venv that has nothing to do with it. However, mod_wsgi requires the same Python repo to be used everywhere. This is not the case, even though it looks like it. Windows then throws this weird error that also has nothing to do with the actual cause.

The only workaround for now is to use the global Python repo for everything. Then there are no issues.

**Comment by GrahamDumpleton** [comment]
Did you use ``mod_wsgi-express module-config`` after using ``pip install mod_wsgi`` to generate the config you should use in the Apache config file? That should generate a ``LoadFile`` line as well but I don't see you had one in the configuration.

**Comment by SebastianFree** [comment]
Yes, I only used mod_wsgi-express. With the faulty build it did not generate the LoadFile line, however now when using the global Python repo it does.
