### ISSUE TITLE
mod_wsgi with Apple MacOS

### ISSUE THREAD

**Issue by montao** [GrahamDumpleton/mod_wsgi#238]
We use the brew installed version of Apache httpd and compiled mod_wsgi from source from this repository. It worked. But the other ways didn't work. We couldn't use the pre-installed Apache httpd with Apple Macos and we couldn't use pip or brew to install mod_wsgi, we got an error msg by the linker. 

Is this the official way of making it work or did we do it wrong?

We don't use mod_wsgi-express because we need to combine with mod_perl as well.

**Comment by GrahamDumpleton** [comment]
On MacOS X you need the full Xcode and as well the Xcode command line tools. Did you have both installed?

You must also use the ``pip install`` method to compile mod_wsgi from source code on MacOS X with Apple httpd. You cannot use configure/make/make install method. Once you have compiled using ``pip install``, you run ``mod_wsgi-express module-config`` to generate configuration snippet to include in the Apache configuration file to have mod_wsgi module loaded. This allows you to use it combination with mod_perl.

See:

* https://pypi.python.org/pypi/mod_wsgi

for more details on installing on MacOS X and integrating into manually configured Apache.

Finally, what version of MacOS X are you using? There may be a chance it doesn't work with very latest MacOS X and latest Xcode. I haven't been able to verify myself as yet.

**Comment by GrahamDumpleton** [comment]
Bit of history on how Apple screws things up.

Last time they supplied ``apxs``, but didn't supply ``apr-1-config`` and ``apu-1-config``. Result was it all broke.

So the code could check for config files for ``apr-1-config`` and ``apu-1-config`` and if they didn't exist, I would work out where Apache and APR header files were installed and provide them to build explicitly.

Problem is that Apple now doesn't even include ``apxs`` at all, so it fails before even gets to the workaround.

I need to work out now how I can workaround the lack of ``apxs`` as was still relying on getting some information from it.

Apple hates developers.

**Comment by GrahamDumpleton** [comment]
Can you try:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

My old laptop which has MacOS X High Sierra has severe hardware problems due to logic board problems and can't currently get it to boot to test. Am trying to update a second even older laptop to latest OS, but not sure if it meets minimum hardware requirements. Clicking on download from App Store doesn't seem to do anything, no error and no progress for download showing. :-(

I had to doctor up what I think are required changes using a MacOS X Sierra laptop.

**Comment by montao** [comment]
Thank you for the answers. We are going to try everything you suggest (but it is already working when we built it from source). I think that we used "latest version" of nearly everything (MacOS, Apache httpd, mod_wsgi).

**Comment by GrahamDumpleton** [comment]
Yeah, if you installed your own Apache from source, you wouldn't have an issue as that would provide ``apxs``.

I almost done with upgrading my spare laptop now, so will be able to check it works soon.

**Comment by GrahamDumpleton** [comment]
Had to tweak a couple of extra things, but version in repo now appears to work on plain MacOS X High Sierra with Xcode app and command line tools, and Apple Python and Apache. Will do a release later.
