### ISSUE TITLE
Error Occurred during make

### ISSUE THREAD

**Issue by stevenang** [GrahamDumpleton/mod_wsgi#240]
I encountered an error during make process.
Here is the details of the error:

/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bytesobject.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct
' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
apxs:Error: Command failed with rc=65536
.
Makefile:31: recipe for target 'src/server/mod_wsgi.la' failed
make: *** [src/server/mod_wsgi.la] Error 1

Can anyone help to solve this issue?

My Environment:

Google cloud Eninger with Debian 9 installed.
Apache 2.4
Python 3.6.3

Thank you and good day.

**Comment by GrahamDumpleton** [comment]
Variation on:

* http://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#mixing-32-bit-and-64-bit-packages

You need to install Python with a shared library.

See also discussion in:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Ignore that it talks about Docker as is still relevant to normal host.
