### ISSUE TITLE
Serving flask app in sub folder using wsgi

### ISSUE THREAD

**Issue by havardl** [GrahamDumpleton/mod_wsgi#241]
Hi,

I'm trying to configure Apache to allow for the following setup: 

One (normal) Apache alias pointing to /site/ and a WSGIScriptAlias pointing to /site/api/

The /site/ will serve my regular site, and the /site/api/ will serve my flask application. I've been trying out different combinations of Alias and WSGIScriptAlias, but it seems that Alias is overwriting the WSGIScriptAlias rule. 

Any ideas on how this might be possible to accomplish?

**Comment by GrahamDumpleton** [comment]
For a start try:

```
AliasMatch ^/site/(!api/) /some/path
WSGIScriptAlias /site/api/ /some/path/app.wsgi
```

There are other ways it could be done, but depends on why you are using ``Alias`` on sub path to begin with.

**Comment by GrahamDumpleton** [comment]
Assuming this is all good now.
