### ISSUE TITLE
intallation error mod_wsgi on windows 10 for wamp

### ISSUE THREAD

**Issue by koala-lava** [GrahamDumpleton/mod_wsgi#242]
Im having an error that I don't understand hope im writting it in the right place.  Im using latest versions of python, wamp. 

`Command "d:\virtualenvs\autozap\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\IBM\\AppData\\Local\\Temp\\pip-build-l4v_e5pt\\mod-wsgi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\IBM\AppData\Local\Temp\pip-__belg1h-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\virtualenvs\autozap\include\site\python3.6\mod-wsgi" failed with error code 1 in C:\Users\IBM\AppData\Local\Temp\pip-build-l4v_e5pt\mod-wsgi\`

Also there are warnings of this kind(many of them):
`mod_wsgi.c
    c:\program files (x86)\python36-32\include\pyconfig.h(321): warning C4005: PLATFORM: изменение макроопределения
    d:\wamp64\bin\apache\apache2.4.27\include\os.h(44): note: см. предыдущее определение "PLATFORM"
    src/server\mod_wsgi.c(1329): warning C4244: функция: преобразование "__int64" в "Py_ssize_t", возможна потеря данных`

The errors appear no matter it's global python installation or virtual environment OR its standalone apache installation(not WAMP)

**Comment by GrahamDumpleton** [comment]
It is the errors before the first error above which need to see. That first error is ``pip`` saying it failed, but not what caused it. So find an 'error' messages from the compiler, ignore the 'warnings'.

**Comment by koala-lava** [comment]
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2`

**Comment by GrahamDumpleton** [comment]
Before that one. That is the outcome of the compiler, again not the actual error which caused it to fail. Can you give like the couple of dozen lines from before that so have more of the messages, if not all the messages?

**Comment by koala-lava** [comment]
Ok, here is a paragraph
`wsgi_interp.c
    d:\wamp64\bin\apache\apache2.4.27\include\os.h(44): warning C4005: PLATFORM: изменение макроопределения
    c:\program files (x86)\python36-32\include\pyconfig.h(321): note: см. предыдущее определение "PLATFORM"
    src/server\wsgi_interp.c(1999): error C2065: wsgi_daemon_shutdown: необъявленный идентификатор
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2`

**Comment by GrahamDumpleton** [comment]
Can you use:

```
pip install mod_wsgi==4.5.20
```

The latest 4.5.21 release has broken Windows builds.

I'll need to fix it tomorrow though as is late here now. Using 4.5.20 should work.

**Comment by koala-lava** [comment]
`build\lib.win32-3.6\mod_wsgi\server\mod_wsgi.cp36-win32.pyd : fatal error LNK1120: эхЁрчЁх°хээ√ї тэх°эшї ¤ыхьхэЄют: 101`
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120`

Also there's a red line when installing `Failed building wheel for mod-wsgi` though it's also aplies to pip install mod_wsgi

**Comment by koala-lava** [comment]
the same error with 4.5.19

**Comment by montao** [comment]
Use 4.5.17. I use mod_wsgi 4.5.17 with Windows 10 and it works. If needed I can provide you with my configuration details:
```
 .\httpd.exe -version
Server version: Apache/2.4.27 (Win64)
Apache Lounge VC15 Server built:   Jul  7 2017 12:46:00
```
Once Apache is up and running, I install mod_wsgi and it is this exact version
`
mod-wsgi (4.5.17+ap24vc14)`

**Comment by GrahamDumpleton** [comment]
There should have been no issue with 4.5.20, the problem was only introduced in 4.5.21. Unfortunately you keep showing the final error state of the compiler or pip and not the actual error that occurred to cause the compiler to fail. This makes it hard to verify what caused any issue.

Either, way the issue has been rectified in 4.5.22 so try installing that. If you are having issues with something like wheels, make sure you have installed the latest versions of ``pip``, ``setuptools`` and ``wheel``.

**Comment by koala-lava** [comment]
@GrahamDumpleton results of running 4.5.20 version

```mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_brigade_flatten@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_thread_mutex_create@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_ipsubnet_test@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pool_cleanup_register@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_md5@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_time_now@0"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_itoa@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_server_banner@0"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_hash_set@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_hook_translate_name@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_hash_make@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_add_common_vars@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_str_tolower@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_set_content_length@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_scoreboard_image"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_mpm_query@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_palloc@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_satisfies@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_getword_conf@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pstrndup@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_threadkey_private_create@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_hash_overlay@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_remote_host@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_document_root@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_some_auth_required@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_no2slash@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_brigade_create@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_strerror@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_table_make@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_check_cmd_context@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_brigade_destroy@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_table_elts@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_brigade@24"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_array_push@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_server_port@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_brigade_cleanup@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_array_append@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_scoreboard_global@0"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_ipsubnet_create@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pstrdup@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_strtoi64@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_limit_req_body@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_table_add@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_escape_html2@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_thread_mutex_lock@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_sockaddr_info_get@24"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_hook_handler@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_register_provider@20"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_discard_request_body@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pool_userdata_set@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_find_path_info@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_regexec@20"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_pregsub@20"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_transient_create@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_add_version_component@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_psprintf"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_hook_access_checker@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_add_cgi_vars@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_table_unset@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_psignature@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_thread_mutex_unlock@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_allow_options@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_server_name@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_hook_child_init@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_dynamic_fn_retrieve@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_set_content_type@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_log_error_"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pool_userdata_get@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pstrcat"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_flush_create@4"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_type_eos"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_off_t_toa@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_log_rerror_"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_array_make@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_hash_get@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_hook_post_config@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_table_get@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_run_generate_log_id@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_pass_brigade@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pstrmemdup@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_table_setn@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_pregcomp@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_stat@16"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_array_cat@8"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_table_set@12"
    mod_wsgi.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_pool_cleanup_null"
    wsgi_apache.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_conv_utf8_to_ucs2@16"
    wsgi_buckets.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_shared_make@20"
    wsgi_buckets.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_shared_copy"
    wsgi_buckets.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_free"
    wsgi_buckets.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_alloc"
    wsgi_buckets.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_shared_destroy@4"
    wsgi_buckets.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_bucket_shared_split"
    wsgi_interp.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_show_mpm@0"
    wsgi_interp.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_server_description@0"
    wsgi_interp.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_server_built@0"
    wsgi_metrics.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_scoreboard_process@4"
    wsgi_metrics.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_get_scoreboard_worker_from_indexes@8"
    wsgi_metrics.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__ap_exists_scoreboard_image@0"
    wsgi_thread.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_threadkey_private_get@8"
    wsgi_thread.obj : error LNK2001: эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы "__imp__apr_threadkey_private_set@8"
    build\lib.win32-3.6\mod_wsgi\server\mod_wsgi.cp36-win32.pyd : fatal error LNK1120: эхЁрчЁх°хээ√ї тэх°эшї ¤ыхьхэЄют: 101
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120```

**Comment by GrahamDumpleton** [comment]
What Apache distro are you using? I only recommend ApacheLounge distro. Some of the others will not work as they are missing bits that allow you to build third party Apache modules.

**Comment by GrahamDumpleton** [comment]
You also need to ensure you have 64 bit version of Apache, Python and MS C compilers. You can't have some being 32 bit. Don't think 32 bit alone works anymore on Windows.

**Comment by GrahamDumpleton** [comment]
As said before, new version is out, use the latest, which is 4.5.22. No need to specify a version. You will still see the issues with Apache though.

**Comment by koala-lava** [comment]
It looks like wampserver uses ApacheLounge already
```Server version: Apache/2.4.27 (Win64)
Apache Lounge VC15 Server built:   Jul  7 2017 12:46:00```
Installing 4.5.17 version didn't help, got the same error as for 4.5.20 version

**Comment by GrahamDumpleton** [comment]
If you have checked that you are using 64 bit for everything, issue maybe that you are using VC15 compiled version of Apache and/or MS C compiler.

When you are using Python 3.6, you need to have VC14 MS C compiler and VC14 Apache.

* https://wiki.python.org/moin/WindowsCompilers

**Comment by koala-lava** [comment]
I didn't wanted to configure all those packages as WAMP already does this for me, but it seems inevitable :) As I understand WAMP uses ApacheLounge compiled with VC15, assuming this line 
```Apache Lounge VC15 Server built:   Jul  7 2017 12:46:00```
I think I should try this one https://www.apachelounge.com/download/VC14/

P.S. I find it's complicated in windows, I usually use linux and never had this kind of problems. I was Installing literally every tool from Visual Studio Build Tools 2017 and 2015, until I saw that Apache also should be VC14.

**Comment by GrahamDumpleton** [comment]
Yep, Windows is a huge pain. I would rather not support it at all if I could. Linux in containers much better way of doing things these days.

**Comment by montao** [comment]
@koala-lava You and I use the same version of Apache (Apache Lounge). I can confirm that mod_wsgi is working with that version. I can even try and upgrade to latest version to see if it works. It might be some other configuration issue that you are experiencing. I suggest that you try a clean install, get Apache Lounge and check carefully all versions of your configurations. 

If you need I can provide any details of my setup for reference. I didn't experience the linker error you're getting. 

@GrahamDumpleton I agree that Linux is much easier than the others to get native code working. But my laptop uses Win10-specific drivers for biometric locks and native code is (1) faster than Linux in a VM and native code is (2) easier to deploy to. Therefore we have migrated our development VMs to native installations for MacOS and Ms-Windows.

**Comment by koala-lava** [comment]
Although @GrahamDumpleton already wrote about this I was pretty sure I had 64 bit version of python(never made such errors earlier), but I had 32 bit version of it. I was reading my earlier comment and noticed this line:
`c:\program files (x86)\python36-32\include\pyconfig.h(321): note: см. предыдущее определение "PLATFORM"`

I didn't have to install VC 14 standalone version of ApacheLounge, I've installed it on Wamp, it works by far. 

So this issue can be closed as it's primarily my fault and I even blamed windows and it's numerous compilers for it(still wouldn't make it on linux since I don't have to download an installer by hand).

I'm developing in Arch and deploying to Windows 10 :smiley:

**Comment by GrahamDumpleton** [comment]
Great to here you worked it out.

**Comment by eswarsubra** [comment]
Hi both thanks for the post. I ran into the same issue and just installed the 64bit version of py and all worked out well.
