### ISSUE TITLE
[Resolved] Error pip installing mod_wsgi Windows 10 python3.6.3 venv Apache 2.4.29

### ISSUE THREAD

**Issue by fzzylogic** [GrahamDumpleton/mod_wsgi#245]
I'm on Windows 10.0.15063 with Python 3.6.3 and the Apache 2.4.29 Win64 installed to default location from apachelounge and installed MSVC 14. Set up a virtual env with venv (python -m venv env). Installing mod_wsgi was failing with a link.exe error: 

    LINK : fatal error LNK1181: cannot open input file 'c:\users\me\project\env\scripts/libs/python36.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

I noticed python36.lib didn't actually exist in env/Scripts/ and that the only place it existed on my system was C:\Program Files\Python36\libs, so i copied that libs folder to env/Scripts, after which 'pip install mod_wsgi' successfully installed mod_wsgi-4.5.22. 

Not sure if venv is wrong or it's something mod_wsgi might need to know about, so just mentioning it here. Anyway, hope it's useful to someone.

**Comment by GrahamDumpleton** [comment]
I would be making sure you had up to date version of ``virtualenv`` for creating the virtual environment, and then latest ``pip``, ``setuptools`` installed in the virtual environment.

**Comment by fzzylogic** [comment]
Thanks for the feedback, appreciate it. Good point. Pip and setuptools are the latest, however i was using pythons built in venv instead of the separate virtualenv package. Tested with the virtualenv package and there was no problem.

**Comment by kenculate** [comment]
same issue here,
I am using python 3.6.8, with venv, pip and setuptools are up to date, 
and can you tell me why it is point to my venv libs, shouldn't this be my python_home?
here is my error, 
 
    LINK : fatal error LNK1181: cannot open input file 'd:\development\lemoncore\venv\scripts/libs/python36.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\development\lemoncore\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1.LE
M\\AppData\\Local\\Temp\\3\\pip-install-_24w2ox7\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1.LEM\\AppData\\Local\\Temp\\3\\pip-install-_24w2ox7\\mod-wsgi\\setup.py'
"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --reco
rd 'C:\Users\ADMINI~1.LEM\AppData\Local\Temp\3\pip-record-xl2e4ono\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\development\lemoncore\ven
v\include\site\python3.6\mod-wsgi' Check the logs for full command output.

**Comment by fzzylogic** [comment]
@kenculate Fwiw, what worked for me at the time as suggested by Graham was using the external virtualenv package, not python 3's built in venv.

**Comment by Yabk** [comment]
Hi, I am having the same problem.
Python 3.7.6 32bit
pip, virtualenv and setuptools are up to date
pip 20.0.2
virtualenv 20.0.1
setuptools 45.2.0

I am missing the python37.lib:
`LINK : fatal error LNK1181: cannot open input file 'c:\path\to\project\venv\scripts\libs\python37.lib'`

The virtualenv vas created using virtualenv package, not built-in venv.

**Comment by GrahamDumpleton** [comment]
Try:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

**Comment by Yabk** [comment]
@GrahamDumpleton It worked!
Thanks a lot!

**Comment by nofrim-es** [comment]
Thank you Mr. GrahamDumpleton. It worked ! Many thanks.

**Comment by GrahamDumpleton** [comment]
You shouldn't be using the `develop.zip` version like this for this issue any more since updated version was released some time back. Thus normally installed version would work the same.
