### ISSUE TITLE
mod_wsgi broken on OpenIndiana

### ISSUE THREAD

**Issue by grueni** [GrahamDumpleton/mod_wsgi#246]
The service pkg/depot uses mod_wsgi.

mod_wsgi shows this error in the logfile.
[Thu Nov 23 17:34:21.653747 2017] [wsgi:error] [pid 1728] (22)Invalid argument: [client 10.xx.xxx.xxx:45507] mod_wsgi (pid=1728): Unable to send request details to WSGI daemon process 'pkgdepot' on '/var/run/pkg/depot/wsgi.1723.0.1.sock'

This patch solves the problem.

```patch
--- mod_wsgi-4.5.22/src/server/mod_wsgi.c.~1~ 2017-11-16 11:41:17.000000000 +0000
+++ mod_wsgi-4.5.22/src/server/mod_wsgi.c 2017-11-24 18:33:50.712849662 +0000
@@ -10639,7 +10639,7 @@
 }

 static apr_status_t wsgi_socket_sendv_limit(apr_socket_t *sock,
-        struct iovec *vec, size_t nvec)
+        struct iovec *vec, int nvec)
 {
     apr_status_t rv;
     apr_size_t written = 0;
@@ -10695,7 +10695,7 @@
 }

 static apr_status_t wsgi_socket_sendv(apr_socket_t *sock, struct iovec *vec,
-                                      size_t nvec)
+                                      int nvec)
 {
 #if defined(_SC_IOV_MAX)
     static size_t iov_max = 0;
```

**Comment by pyhalov** [comment]
size_t is unsigned. 
Can it be related to this code: https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/mod_wsgi.c#L10712 ?

**Comment by GrahamDumpleton** [comment]
Solaris has a really small iovec size limit, which is partly why all this code exists in the first place. Looks like I tried to clean up and get rid of signed/unsigned compiler warnings at one point by switching to unsigned . values and missed that termination check would then fail. :-(

**Comment by grueni** [comment]
I implemented the patch from pyhalov  and it works.

**Comment by GrahamDumpleton** [comment]
Sorry for not getting to this. I was very busy that week and then was off overseas at a conference. Only just realised I never incorporated the patch. Will get onto this shortly.
