### ISSUE TITLE
Install error in bash on Windows 10

### ISSUE THREAD

**Issue by krmarien** [GrahamDumpleton/mod_wsgi#249]
In bash on Windows 10 I get the following error during install:
```
Traceback (most recent call last):
  File "/tmp/easy_install-cxlqMb/mod_wsgi-4.5.22/setup.py", line 301, in <module>
    INCLUDEDIR = get_apxs_config('INCLUDEDIR')
  File "/tmp/easy_install-cxlqMb/mod_wsgi-4.5.22/setup.py", line 273, in get_apxs_config
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The actual issue is that the apxs command is not available (forgot to install apache2-dev)
I would expect that mod_wsgi would throw a nice error. But that is currently not the issue due to the wrong condition over here: [setup.py#L164](https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/setup.py#L164)

Should the latest condition `not WITHOUT_APXS` be removed?

**Comment by GrahamDumpleton** [comment]
It is probably actually meant to be:

```
if WITHOUT_APXS and not WITH_WINDOWS_APACHE and not WITH_MACOSX_APACHE:
```

Looks like I stuffed up change a month back.

**Comment by GrahamDumpleton** [comment]
Try installing 4.5.23.

**Comment by krmarien** [comment]
Thanks
