### ISSUE TITLE
Deployment of a Django Project - Apache24 localhost freezing after setting up mod_wsgi

### ISSUE THREAD

**Issue by merjekrepo** [GrahamDumpleton/mod_wsgi#251]
I want to deploy my development project to the production but unfortunately I get stuck with mod_wsgi issues. These are the steps I applied:

Installed python
Installed django 
Installed the Apache24.

Run this command in the cmd window: 
`set MOD_WSGI_APACHE_ROOTDIR=C:/Apache24`

Then run this on the cmd window:
`pip install wsgi`

Then run this on the cmd window:
`mod_wsgi-express module-config`

I got the following output:
LoadFile "c:/users/administrator/appdata/local/programs/python/python36/python36.dll"
LoadModule wsgi_module "c:/users/administrator/appdata/local/programs/python/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/users/administrator/appdata/local/programs/python/python36"

Everything is fine so far. Then in the httpd.conf file, I put in these lines:

```
LoadModule wsgi_module "c:/users/administrator/appdata/local/programs/python/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"

WSGIScriptAlias / "C:/Users/Administrator/Documents/merjek/merjek/wsgi.py"
WSGIPythonHome "c:/users/administrator/appdata/local/programs/python/python36"
WSGIPythonPath "C:/Users/Administrator/Documents/merjek"

Alias /static/ C:/Users/Administrator/Documents/merjek/static/

<Directory C:/Users/Administrator/Documents/merjek/static>
          Require all granted
</Directory>

<Directory C:/Users/Administrator/Documents/merjek>
          <Files wsgi.py>
               Require all granted
          </Files>
</Directory>
```

Unfortunately it freezes as shown below after re-starting the apache server:

![localhost_apache24_freezing](https://user-images.githubusercontent.com/12020185/33790902-38fec732-dc4a-11e7-91e9-fc52e7293c81.JPG)

I would be glad for help.

**Comment by GrahamDumpleton** [comment]
Try it with a WSGI hello world, not Django.

If that works, try setting:

```
WSGIApplicationGroup %{GLOBAL}
```

This can be needed if you are using Python packages with C extensions that don't work in Python sub interpreters.

**Comment by merjekrepo** [comment]
Hi Graham, thanks for quick response. I tried the WSGI hell world sample you suggested but it didn't work out. 

Here are the steps I applied:

I've generated documents and wsgi-scripts folders under C:/Apache24/htdocs

I've put in the following code in the myapp.wsgi file under C:/Apache24/htdocs/wsgi-scripts
```
def application(environ, start_response):
    status = '200 OK'
    output = 'Hello World!\n'
    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)
    return [output]
```

Then I put this into the httpd-vhosts.conf file:
```
<VirtualHost *:80>
    ServerName localhost

    DocumentRoot c:/Apache24/htdocs/documents
    <Directory c:/Apache24/htdocs/documents>
    Order allow,deny
    Allow from all
    </Directory>

    WSGIScriptAlias /myapp c:/Apache24/htdocs/wsgi-scripts/myapp.wsgi
    <Directory c:/Apache24/htdocs/wsgi-scripts>
    Order allow,deny
    Allow from all
    </Directory>
</VirtualHost>
```

The Virtual hosts line is commented out in the httpd.conf file
```
# Virtual hosts
Include conf/extra/httpd-vhosts.conf
```
And of course I've removed everything related with django from the httpd.conf file.

Then after re-starting the apache server, I got the following error:
Invalid command 'WSGIScriptAlias', perhaps misspelled or ...

![wsgiscriptalias_bug](https://user-images.githubusercontent.com/12020185/33792216-8af68542-dc5f-11e7-92b4-15e53ed9c007.JPG)

**Comment by GrahamDumpleton** [comment]
You still have to include the output from running ``mod_wsgi-express module-config``. That is needed to load mod_wsgi. That output must be a global scope of the Apache configuration file (outside of VirtualHost), and early on just after where other Apache modules are loaded.

**Comment by merjekrepo** [comment]
Well, I no longer get that error when I put the output below:

```
LoadFile "c:/users/administrator/appdata/local/programs/python/python36/python36.dll"
LoadModule wsgi_module "c:/users/administrator/appdata/local/programs/python/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/users/administrator/appdata/local/programs/python/python36"
```

However, I now get the following error:

![internal_server_error](https://user-images.githubusercontent.com/12020185/33792704-7a1ed438-dc6c-11e7-8771-ff4632c0503e.JPG)

When I check the error.log file in the logs folder, I see the following error outputs:
`mod_wsgi (pid=5864): Exception occurred processing WSGI script 'C:/Apache24/htdocs/wsgi-scripts/myapp.wsgi'`
`TypeError: sequence of byte string values expected, value of type str found\r`

Any idea why I am getting this and how I can resolve this issue?

**Comment by GrahamDumpleton** [comment]
That is because your code is for a Python 2 WSGI application. It should be:

```
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!\n'
    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)
    return [output]
```

That is, the output should be a byte string.

Anyway, it shows that it is working fine.

As I said originally, as it is working, add:

```
WSGIApplicationGroup %{GLOBAL}
```

to your original mod_wsgi configuration used for Django.

Read the docs at:

* http://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

as to why.

**Comment by merjekrepo** [comment]
Ok, I've found the solution to that from here:
https://stackoverflow.com/questions/34838443/typeerror-sequence-of-byte-string-values-expected-value-of-type-str-found

So, I've replaced the code above with (just put b in front of Hello World string, seems it is about encoding):

```
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!\n'
    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)
    return [output]
```
Then after commenting `#Include conf/extra/httpd-vhosts.conf`, I've put the 

`WSGIApplicationGroup %{GLOBAL} `

in the httpd.conf file along with django related settings above and it worked :)

Many thank Graham. You helped me a lot.

**Comment by emmetarries** [comment]
@GrahamDumpleton I just want to say that I've spent hours trying to figure out why WSGI/Django/Apache wouldn't work. I could get everything to work separately, but not together. Once I added the `WSGIApplicationGroup %{GLOBAL}` line, voila! Thank you so much!!

**Comment by edvinmolla** [comment]
Could someone point out where I should include WSGIApplicationGroup %{GLOBAL} ?

**Comment by kleebauer** [comment]
@GrahamDumpleton Thank you so much! 

I spent hours trouble shooting. I would be interesting what the effect of WSGIApplicationGroup %{GLOBAL} is and what logic/meaning behind is.

**Comment by GrahamDumpleton** [comment]
It makes it equivalent to what happens when running command line Python. That is, runs code in main interpreter context rather than a secondary Python sub interpreter of the same process. See:

See: https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGIApplicationGroup.html
See: https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#python-simplified-gil-state-api
