### ISSUE TITLE
compressing JSON responses with mod_wsgi-express --compress-response

### ISSUE THREAD

**Issue by ned2** [GrahamDumpleton/mod_wsgi#254]
Is there a specific reason why --compress-response does not compress `application/json` responses? It seems like an obvious one to target, but I don't have heaps of experience here, so possibly there's a clear reason why this would be a bad default.

If this is not something that would be considered for adding to the `--compress-response` behavior, what's the best way to go about adding that bit of config. I'm running `mod_wsgi-express` from a bash script, so something that could be bundled up into such a script is what I'm looking for.

**Comment by GrahamDumpleton** [comment]
Yeah, I probably should add it.

In the mean time you can create a file called ``httpd.conf`` where you run ``mod_wsgi-express`` and add to it:

```
<IfDefine MOD_WSGI_COMPRESS_RESPONSES>
AddOutputFilterByType DEFLATE application/json
</IfDefine>
```

Then run ``mod_wsgi-express`` with additional option:

```
--include-file httpd.conf
```

The contents of that file will be included at the end of the generated content.

**Comment by ned2** [comment]
Ah fantastic, worked a charm. Thanks heaps :)

**Comment by GrahamDumpleton** [comment]
Added in https://github.com/GrahamDumpleton/mod_wsgi/commit/b114137eecfec8ba5078f3c69178da24ebd6d101 for next version.

**Comment by GrahamDumpleton** [comment]
Closing this issue out since change will be in version 4.5.25.
