### ISSUE TITLE
WSGIScriptAliasMatch process-group gives Invalid option

### ISSUE THREAD

**Issue by ancc** [GrahamDumpleton/mod_wsgi#256]
Based on documentation WSGIScriptAliasMatch supports
options process-group and application-group.
However when specifying those options, apache gives error:
Invalid option to WSGI script alias definition.

Without options it works.

Apache version 2.2.15
mod_wsgi version 4.5.24
python version 2.7
OS: Centos 6.8

**Comment by GrahamDumpleton** [comment]
Can you cut and paste the exact configuration you are using? Don't just type it again, I want to see the exact characters you are using in case you have wrong quote types or other funny characters.

**Comment by ancc** [comment]
No special characters are used, shortest example which produces the error.

```
LoadModule wsgi_module modules/mod_wsgi.so
WSGISocketPrefix /var/run/wsgi
DocumentRoot /var/www/
WSGIDaemonProcess test processes=1 threads=1

WSGIProcessGroup test
WSGIScriptAliasMatch ^/test /var/www/test.wsgi process-group=test
```
and running service httpd restart, output is:


```
Stopping httpd:                                            [  OK  ]
Starting httpd: Syntax error on line 7 of /etc/httpd/conf.d/test.conf:
Invalid option to WSGI script alias definition.                                                           [FAILED]
```


When removing process-group=test then no errors.

**Comment by GrahamDumpleton** [comment]
The documentation is actually wrong.

Those options were never supported on ``WSGIScriptAliasMatch`` for reasons I can't exactly remember. About a month ago I was updating docs for ``WSGIScriptAlias``, which didn't document ``process-group`` and ``application-group`` options, and wrongly applied the documentation changes to ``WSGIScriptAliasMatch`` as well.

I have to now go back and remember why those options weren't supported on ``WSGIScriptAliasMatch``. I can partly remember one reason why they aren't but need to dig deeper.

**Comment by ancc** [comment]
I found a way using AliasMatch (for serving static files) and WSGIScriptAlias which solved my problem.

**Comment by GrahamDumpleton** [comment]
I am still looking at why the options can't be supported, but wasn't even sure why you were trying to use ``WSGIScriptAliasMatch`` anyway. Using:

```
WSGIScriptAliasMatch ^/test /var/www/test.wsgi process-group=test
```

is the same as saying:

```
WSGIScriptAlias /test /var/www/test.wsgi process-group=test
```

How does ``AliasMatch`` come into your final solution? Can you show the complete config you are using now?

**Comment by ancc** [comment]
I have static filed as subfolders :(
/test/js
/test/css
/test/img
but application itself is /test
I needed that only if the request is exactly /test then wsgi script handles it and test/js, test/css etc. are served by apache as-is.

For that, in the beginning I used 
WSGIScriptAliasMatch ^/test/?$ ..... to handle it. Later found that apache AliasMatch is handled before WSGIScriptAlias.

finally 
AliasMatch ^/test/((img|js|css).*)  /var/www/test/htdocs/$1
WSGIScriptAlias /test /var/www/test.wsgi process-group=test  

Now /test/img, test/js, test/css as served as-is by apache and /test is handled by test.wsgi

**Comment by GrahamDumpleton** [comment]
Yep, usually you would use ``Alias`` and ``AliasMatch`` to handle static files that overlap as ``Alias`` directives take precedence:

* http://modwsgi.readthedocs.io/en/develop/user-guides/configuration-guidelines.html#hosting-of-static-files

The alternative is to set up the WSGI application as a fallback resource when no static files match. That is a bit trickier as you can't use Apache's own ``FallbackResource`` directive and I haven't been able to find an easy way to implement a ``WSGIFallbackResource`` directive which will always work. For doing it manually, see towards end of this section in documentation:

* http://modwsgi.readthedocs.io/en/develop/user-guides/configuration-guidelines.html#the-apache-alias-directive

I should have another got at working out whether can implement at ``WSGIFallbackResource``. I can probably make it work, but with proviso that can't be used of using mod_rewrite to do strange things.

**Comment by GrahamDumpleton** [comment]
The reason that ``process-group`` and ``application-group`` was originally disallowed on ``WSGIScriptAliasMatch`` was to avoid having to deal with what to do when both were specified. For ``WSGIScriptAlias`` having both triggered pre-loading of the WSGI script file, but for ``WSGIScriptAliasMatch`` you can have replacements in the WSGI script file path based on what was matched in the URL pattern. Eg.

```
WSGIScriptAliasMatch ^/wsgi-scripts/([^/]+) /web/wsgi-scripts/$1.wsgi
```

The value of ``$1`` can't be known when the process starts up so not possible to pre-load. For that reason the options where probably simply not allowed.

It seems at this point it would be better to allow the options, but just not record it in list of things to pre-load if both defined. So would be known limitation that they don't trigger pre-loading.

The alternative is to search the WSGI script file path and if it includes ``$``, then don't add to list of things to pre-load. That means can still have pre-loading where substitution not being done.

**Comment by GrahamDumpleton** [comment]
Support for ``process-group`` and ``application-group`` on ``WSGIScriptAliasMatch`` added in https://github.com/GrahamDumpleton/mod_wsgi/commit/6c8d06092f619fb67cebb707e205b5f7d3db106a.

**Comment by GrahamDumpleton** [comment]
Closing this issue out since change will be in version 4.5.25.
