### ISSUE TITLE
mod_wsgi installation failed on Windows 10 , Anaconda Python 3.6 , XAAMP 

### ISSUE THREAD

**Issue by nishanttayal** [GrahamDumpleton/mod_wsgi#264]
I am trying to install mod_wsgi using pip on 64-bit machine and facing the below error

    mod_wsgi.obj : warning LNK4197: export 'PyInit_mod_wsgi' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.6\Release\src/server\mod_wsgi.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\src/server\mod_wsgi.cp36-win_amd64.exp
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_brigade_flatten
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_thread_mutex_create
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_ipsubnet_test
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pool_cleanup_register
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_md5
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_time_now
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_itoa
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_server_banner
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_hash_set
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_hook_translate_name
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_hash_make
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_add_common_vars
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_str_tolower
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_set_content_length
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_scoreboard_image
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_mpm_query
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_palloc
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_satisfies
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_getword_conf
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pstrndup
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_threadkey_private_create
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_hash_overlay
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_remote_host
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_document_root
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_some_auth_required
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_no2slash
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_brigade_create
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_strerror
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_table_make
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_check_cmd_context
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_brigade_destroy
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_table_elts
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_brigade
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_array_push
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_server_port
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_brigade_cleanup
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_array_append
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_scoreboard_global
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_ipsubnet_create
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pstrdup
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_strtoi64
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_limit_req_body
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_table_add
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_escape_html2
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_thread_mutex_lock
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_sockaddr_info_get
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_hook_handler
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_register_provider
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_discard_request_body
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pool_userdata_set
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_find_path_info
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_regexec
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_pregsub
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_transient_create
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_add_version_component
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_psprintf
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_hook_access_checker
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_add_cgi_vars
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_table_unset
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_psignature
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_thread_mutex_unlock
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_allow_options
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_server_name
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_hook_child_init
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_dynamic_fn_retrieve
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_set_content_type
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_log_error_
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pool_userdata_get
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pstrcat
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_flush_create
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_type_eos
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_off_t_toa
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_log_rerror_
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_array_make
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_hash_get
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_hook_post_config
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_table_get
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_run_generate_log_id
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_pass_brigade
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pstrmemdup
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_table_setn
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_pregcomp
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_stat
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_array_cat
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_table_set
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pool_cleanup_null
    wsgi_apache.obj : error LNK2001: unresolved external symbol __imp_apr_conv_utf8_to_ucs2
    wsgi_buckets.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_shared_make
    wsgi_buckets.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_shared_copy
    wsgi_buckets.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_free
    wsgi_buckets.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_alloc
    wsgi_buckets.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_shared_destroy
    wsgi_buckets.obj : error LNK2001: unresolved external symbol __imp_apr_bucket_shared_split
    wsgi_interp.obj : error LNK2001: unresolved external symbol __imp_ap_show_mpm
    wsgi_interp.obj : error LNK2001: unresolved external symbol __imp_ap_get_server_description
    wsgi_interp.obj : error LNK2001: unresolved external symbol __imp_ap_get_server_built
    wsgi_metrics.obj : error LNK2001: unresolved external symbol __imp_ap_get_scoreboard_process
    wsgi_metrics.obj : error LNK2001: unresolved external symbol __imp_ap_get_scoreboard_worker_from_indexes
    wsgi_metrics.obj : error LNK2001: unresolved external symbol __imp_ap_exists_scoreboard_image
    wsgi_thread.obj : error LNK2001: unresolved external symbol __imp_apr_threadkey_private_get
    wsgi_thread.obj : error LNK2001: unresolved external symbol __imp_apr_threadkey_private_set
    build\lib.win-amd64-3.6\mod_wsgi\server\mod_wsgi.cp36-win_amd64.pyd : fatal error LNK1120: 101 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

I have tried reinstalling Visual Studio but its of no help.

**Comment by GrahamDumpleton** [comment]
What Apache binary distribution are you using? Some of them cannot be used. The only one that is recommended is ApacheLounge distribution.

Other things to ensure.

* Use Python 3.6. Don't use Python 2.7.
* Ensure Python is 64 bit.
* Ensure Apache is 64 bit.
* Ensure you have 64 bit MS C/C++ VC14.

**Comment by GuntarsLuta** [comment]
Same error:
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120`

**Comment by nishanttayal** [comment]
Thanks, @GrahamDumpleton.
XAAMP was having 32-bit Apache by default which was creating the problem. Also, i have not used forward slashes while defining the path of MOD_WSGI_APACHE_ROOT.

@GuntarsLuta XAAMP comes with 32-bit Apache so you can download 64 bit Apache from the web and replace the XAAMP apache folder with 64-bit binaries. Hope it helps!

**Comment by GrahamDumpleton** [comment]
@GuntarsLuta What you quote is only the final compiler exit code message and not the actual error description. Need to see all the messages that come before to confirm whether is the same issue. If you haven't solved it still, create a separate issue for you problem. I will close this issue now since @nishanttayal appears to have solved their issue.
