### ISSUE TITLE
Cannot load modules/mod_wsgi.so into server: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nik6018** [GrahamDumpleton/mod_wsgi#267]
Hi,

I feel really dumb opening an issue for this topic as this has been covered on multiple other issue and websites.

But all the solutions mentioned didn't work for me.

I have compiled my Python at the following directory: `/usr/local/apps/python2/`

So **libpython2.7.so.1.0** is present in the following directory

```
ls /usr/local/apps/python2/lib/
libpython2.7.so  libpython2.7.so.1.0  pkgconfig  python2.7
```

So I used the following commands while compiling Mod_wsgi

```
./configure --prefix=/usr/local/apps/apache2/modules \
--with-apxs=/usr/local/apps/apache2/bin/apxs \
--with-python=/usr/local/apps/python2/bin/python

LD_RUN_PATH=/usr/local/apps/python2/lib/ make

make install
```

but still while restarting Apache I face the following error:

> httpd: Syntax error on line 690 of /usr/local/apps/apache2/etc/httpd.conf: Syntax error on line 2 of /usr/local/apps/apache2/etc/conf.d/wsgi.conf: Cannot load modules/mod_wsgi.so into server: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

Can you please point me in the right direction on how should I fix this issue.

**Comment by GrahamDumpleton** [comment]
Make sure you did a ``make distclean`` if you built code once, found problem and then tried to rebuild it with ``LD_RUN_PATH`` set. The existing ``mod_wsgi.so`` would be used.

You can see what ``mod_wsgi.so`` is linking by running ``ldd`` on the ``mod_wsgi.so`` file.

If all else fails, add before the ``LoadModule`` line in Apache:

```
LoadFile /usr/local/apps/python2/lib/libpython2.7.so
```

**Comment by nik6018** [comment]
> If all else fails, add before the LoadModule line in Apache:
> `LoadFile /usr/local/apps/python2/lib/libpython2.7.so`

Thanks, Graham it worked.

But why this is an issue if I am specifying the right path while configuring?

Also, is my `--prefix` correct should I build it in Apache's module or Python's lib directory?

**Comment by GrahamDumpleton** [comment]
The question is whether running ``ldd`` on the ``mod_wsgi.so``, with ``LD_LIBRARY_PATH`` environment unset if it was set, show the correct library being found. If it wasn't then ``LD_RUN_PATH`` wasn't set or not set correctly when it was compiled.

If you had built it once and had problem and not done at least a ``make clean`` before rebuilding with ``LD_RUN_PATH`` set, it wouldn't have actually rebuilt it and would have used previously compiled one.

So suggest do ``make distclean``, run configure again, and then ``make`` with ``LD_RUN_PATH`` set. See if the ``mod_wsgi.so`` down under the ``.libs`` directory shows correct result for ``ldd``.

**Comment by GrahamDumpleton** [comment]
Closing as workaround with ``LoadFile`` worked and no further followup around why proper way of doing this didn't work as expected.
