### ISSUE TITLE
unable to access mod_wsgi.git repo

### ISSUE THREAD

**Issue by thainlnguyen** [GrahamDumpleton/mod_wsgi#270]
Hello Graham,
I have a Jenkins build that does a git clone of your repo and builds the mod_wsgi.so, but lately my build has failed with this error message below: 

`fatal: unable to access 'https://github.com/GrahamDumpleton/mod_wsgi.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

It has not failed before. Am I using an old version of a Git client?

Thanks!
ThaiN

**Comment by GrahamDumpleton** [comment]
GitHub has removed support for older SSL/TLS versions. This was originally announced start of last year.

* https://githubengineering.com/crypto-deprecation-notice/

with another update last September.

* https://githubengineering.com/crypto-deprecation-notice-update-1/

They finally cut them off on February 8th. Notice at top of page at:

* https://githubengineering.com/

**Comment by thainlnguyen** [comment]
thank you very much for your feedback!
