### ISSUE TITLE
Still Stuck and Spinning

### ISSUE THREAD

**Issue by PythonNubie** [GrahamDumpleton/mod_wsgi#271]
Hello world, I am trying to host a flask/python web application on a Apache Centos 7 server. I am very much a newbie to this and very frustrated. Any help and guidence is appreciated.

This is the issue i am running into are the following:

Error Log
 AH01215: (8)Exec format error: exec of '/var/www/MyApp/run.py' failed
 End of script output before headers: run.py

.WSGI FIle:
#!/opt/MyApp/bin/python3
import sys
from MyApp import MyApp as application
sys.path.insert(0,"/opt/MyApp/lib/python3.4/site-packages/")

Run.py
#!/opt/MyApp/lib/python3.4
from flask import Flask

MyApp= Flask(__name__)

@MyApp.route('/')
def homepage():
	return "Hello world, if you see me it works"
 
if __name__ == "__main__":
	 (debug=True)

Httpd.Conf(This code is at the end of HTTPD.CONF)
<VirtualHost *:80>
WSGIDaemonProcess MyApp threads=5
WSGIScriptAlias / /var/www/MyApp/flasktool.wsgi

<Directory /opt/MyApp/lib/python3.4/site-packages>
    WSGIProcessGroup MyApp
    WSGIApplicationGroup %{GLOBAL}
    Order deny,allow
    Allow from all
</Directory>
</VirtualHost>

**Comment by GrahamDumpleton** [comment]
Something in your Apache configuration has the ``.wsgi`` extension, or the directory where it is located, to be handled as a CGI script.

**Comment by PythonNubie** [comment]
Thank you for responding...  I do have a .wsgi file. I am not using cgi. Is it possible to disable CGI?

**Comment by PythonNubie** [comment]
Or can I remove this"AddHandler cgi-script .cgi .py"

**Comment by GrahamDumpleton** [comment]
Comment out any ``AddHandler`` or ``SetHandler`` for ``cgi-script``. Also find any place which has ``Options ExecCGI`` for a directory. These all enable CGI scripts in some way. It could also be because of FASTCGI, so look for any configuration related to that as well.

**Comment by PythonNubie** [comment]
Yay! that worked thank you!!! Now, the only thing that is not giving an error is the fact that my page shows all the python/flask code instead of "Hello World" in the log it says:

AH02282: No slotmem from mod_heartmonitor
[Wed Feb 28 18:09:05.777079 2018] [mpm_prefork:notice] [pid 70516] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations

**Comment by GrahamDumpleton** [comment]
Which means your ``VirtualHost`` is being ignored. You don't have a ``ServerName`` directive in it and so it will not be matched. If you have default ``VirtualHost`` still enabled, it will use that instead. If you have nothing else on the server, try adding your stuff inside of the default ``VirtualHost``.

**Comment by PythonNubie** [comment]
ok... so is this correct

<VirtualHost *:80>
ServerName 68.105.000.68
WSGIScriptAlias / /var/www/rfc/flasktool.wsgi
<Directory /opt/MyApp/lib/python3.4/site-packages>
    WSGIProcessGroup rfc
    WSGIApplicationGroup %{GLOBAL}
    Order deny,allow
    Allow from all
</Directory>
</VirtualHost>

**Comment by GrahamDumpleton** [comment]
``ServerName`` shouldn't be an IP address. It has to be the hostname you would use in the URL. If you are accessing the server using ``127.0.0.1``, ``localhost`` or some other IP address, then your configuration must be part of the first (default) ``VirtualHost`` definition. Otherwise, don't use ``VirtualHost`` at all if don't need name based virtual hosting to host multiple sites.

**Comment by PythonNubie** [comment]
type in:
WSGIScriptAlias / /var/www/Myapp/flasktool.wsgi

**Comment by GrahamDumpleton** [comment]
You actually need:

```
WSGIDaemonProcess MyApp threads=5
WSGIProcessGroup MyApp
WSGIApplicationGroup %{GLOBAL}

WSGIScriptAlias / /var/www/Myapp/flasktool.wsgi

<Directory /var/www/Myapp/>
Require all granted
</Directory>
```

I had been ignoring fact you didn't have correct ``Directory> block for now.

**Comment by PythonNubie** [comment]
ok, so what do i do about the server name its a dev server? can i alias the ip?

**Comment by GrahamDumpleton** [comment]
If it is a local dev systems and you want to still use ``VirtualHost``, you put the config in the first (default) ``VirtualHost`` in the Apache configuration. When any ``VirtualHost`` exists and name based matching can't be done, it will fall back to using the first ``VirtualHost``.

Otherwise, add a new hostname entry in ``/etc/hosts`` mapping to 127.0.0.1, which isn't ``localhost``, which is special.

You could also rely in ``nip.io`` and use:

```
ServerName 127.0.0.1.nip.io
```

and use ``127.0.0.1.nip.io`` as hostname in the URL.

**Comment by PythonNubie** [comment]
ok, so in the  my hosts file this is what i have on my remote server

	127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4

68.105.000.68  lab-MyApp-01.sw.biz.com lab-MyApp-01

**Comment by GrahamDumpleton** [comment]
Try:

```
ServerName lab-MyApp-01.sw.biz.com
```

and then use URL of:

```
http://lab-MyApp-01.sw.biz.com/
```

**Comment by PythonNubie** [comment]
lol I have to laugh at this point...

"server DNS address could not be found."
looking this up now





Lisa Hale | Commercial Tools
9300 Arrowpoint Blvd
Charlotte | NC 28273
Office: 704.969.1947 | Cell: 980.266.5155
[Charter]

**Comment by PythonNubie** [comment]
lol I have to laugh at this point... 

"server DNS address could not be found." 
looking this up now

**Comment by GrahamDumpleton** [comment]
Then use just:

```
ServerName lab-MyApp-01
```

and:

```
http://lab-MyApp-01/
```

**Comment by GrahamDumpleton** [comment]
Or the ``nip.io`` method as already given.

**Comment by PythonNubie** [comment]
Ok, that works.. 1 last question... what caused all my code to show?
instead of "Hello World"
from flask import Flask

MyApp= Flask(name)

@MyApp.route('/')
def homepage():
return "Hello world, if you see me it works"

if name == "main":
(debug=True)

**Comment by GrahamDumpleton** [comment]
You possibly had the file under the ``DocumentRoot`` directory for the Apache server. That is usually a bad idea because a stuff up in configuration means someone could download your code if they use a URL which maps to the code file.

**Comment by PythonNubie** [comment]
You have been a great help. I am 10x's closer than i have been in weeks. I am working on that last issue.. Thank you again.

**Comment by PythonNubie** [comment]
So i have been researching and my document root error, But the same thing happens even if i comment out the document root..Could something cause that?

**Comment by GrahamDumpleton** [comment]
Closing since you opened a new issue.
