### ISSUE TITLE
Apache client denied error (AH01630) although content is served correctly

### ISSUE THREAD

**Issue by ek1m92** [GrahamDumpleton/mod_wsgi#272]
Hey there,

I'm hosting a [flask app](https://github.com/rgalanakis/hostthedocs) through mod_wsgi-express using mod_wsgi-docker. I'm using two options: `--url-alias` to let apache serve some static content directly and `--mount-point` in order to serve the app not on root but under a subdirectory (namely "/htd"). Everything's working perfectly but I've noticed some odd activity in the apache log.

There are two cases where a message like the following shows up, although the page is served as intended:
`[authz_core:error] [pid 16:tid 140123041498880] [client ip:port] AH01630: client denied by server configuration: /tmp/mod_wsgi-localhost:80:0/htdocs/latest, referer: http://localhost:port/htd/`
"latest" stems from the app dynamically creating a redirect to a statically hosted document. The redirect happens without a hitch but at some point, apache seems to try to serve a static document from the default DocumentRoot.
The other case where this is happening involves javascript files on the landing page that, again, are served and executed flawlessly despite the error.

I'm pretty sure I must be missing something rather basic but I couldn't find a "solution" to this on my own after spending quite some time with the problem. Of course, I'll happily provide more information as needed, but I didn't want to include more details than I figured necessary.

**Comment by GrahamDumpleton** [comment]
What is the full command line so can see what ``--url-alias`` is being passed with?

**Comment by ek1m92** [comment]
I have overwritten mod_wsgi-docker's `Entrypoint` (I'm using the 3.5 onbuild version) to be able to use bash features to what, after variable expansion, becomes:
`mod_wsgi-docker-start --mount-point "/htd" --url-alias "/htd/docfiles" "/usr/local/www/docfiles"`
The behaviour I've described happens using just the `--mount-point` option as well, though.

**Comment by GrahamDumpleton** [comment]
Can you use ``pip freeze`` to work out what ``mod_wsgi`` package version is installed. I don't keep docker image up to date and don't recommend its use. It is like defaulting to an older version and you need to pin it to latest version in your ``requirements.txt`` file.

**Comment by ek1m92** [comment]
I have tried both using the latest version within the docker container as well as installing it directly via pip running on Ubuntu 16.04.4 LTS using Apache 2.4.18. Unfortunately, the problem persists.

Regarding the docker image: do you see any immediate problems with using it with updated version parameters apart from the fact you're not actively maintaining it any more?

**Comment by ek1m92** [comment]
Sorry for the delayed reply.
Thanks for the pointers! I get that the quirks of url redirection could explain the error. What still confuses me is the fact that the content is served perfectly despite these messages.
Unfortunately, I won't get around to investigating this further at this time, which is why I'll close the issue for now. Again, thanks for your help!

**Comment by GrahamDumpleton** [comment]
Where does the word ``latest`` even appear in the code? It is a strange name for a resource to be requesting.

**Comment by ek1m92** [comment]
It's a flask route that redirects to the latest version of a resource. It should actually be `/RESOURCE/latest`.
Maybe it makes more sense to look at the other example? The javascript and css referenced [here](https://github.com/rgalanakis/hostthedocs/blob/2cd0b9bd40fe8ec84c1bd63a2d0f294f0b4c59fd/hostthedocs/templates/base.html) trigger the same error but are apperently accessed and used as intended from the static directory within the app's directory.
