### ISSUE TITLE
Apache is showing the code in the run.py file instead of running the script

### ISSUE THREAD

**Issue by PythonNubie** [GrahamDumpleton/mod_wsgi#273]
So i have been researching why Apache is showing the code in the run.py file instead of running the script.  But the same thing happens even if I comment out the document root..  Some how the pages is serving up the files as static content instead of passing the request to uwsgi and then to Python to be executed. Below is my httpd.conf file

LoadModule lbmethod_heartbeat_module modules/mod_lbmethod_heartbeat.so
LoadModule wsgi_module modules/mod_wsgi.so

DocumentRoot "/var/www/MyApp/"
<Directory "/var/www/MyApp">
    AllowOverride None
   Require all granted
</Directory>

ScriptAlias 
ScriptAlias /MyApp/  "/var/www/MyApp/"

<Directory "/var/www/MyApp">
      AllowOverride None
    Options None
     Order allow,deny
    Allow from all
    #Require all granted
</Directory>

http.Conf
<VirtualHost *:80>
ServerName 00.105.335.68.nip.io
WSGIDaemonProcess rfc threads=5
WSGIProcessGroup rfc
WSGIApplicationGroup %{GLOBAL}

WSGIScriptAlias / /var/www/rfc/flasktool.wsgi
<Directory /var/www/rfc/flasktool.wsgi>
Require all granted
  Order allow,deny
  Allow from all
</Directory>
</VirtualHost>

How can i fix this??

Thank you in advance

**Comment by GrahamDumpleton** [comment]
What is the URL you are making the request with?

**Comment by PythonNubie** [comment]
I am using the ip.nip.io as suggested.

**Comment by GrahamDumpleton** [comment]
If all you want is WSGI applications, you should not have the ``AddHandler`` line, nor the ``ScriptAlias`` lines.

The URL you should be using is just:

```
http://ip.nip.io/
```

Your URL is mapping to the CGI script directory, although overriding ``AddHandler`` for an invalid handler means that it would fallback to handling as a static file and return the code.

**Comment by GrahamDumpleton** [comment]
Closing as no further followup. Re-open if still having the original issue.
