### ISSUE TITLE
 Bad Gateway 502 error.

### ISSUE THREAD

**Issue by PythonNubie** [GrahamDumpleton/mod_wsgi#276]
I am attempting to configure Nginx to run my flask/python application on a Linux Centos 7 server. I am getting a Bad Gateway 502 error.

I am new to using Nginx so I am hoping I am going the right direction. Here are my files.

*****MyApp.ini******

[uwsgi]
module = wsgi

master = true
processes = 5

****MyApp.sock****

[uwsgi]
module = wsgi

master = true
processes = 5

socket = MyApp.sock
chmod-socket = 664
vacuum = true

die-on-term = true

****Nginx.Conf*****

#03/02/2018
#Added the server information below

    server {
    listen 8000;
    server_name 78.105.158.68;

      location / {
        include uwsgi_params;
        uwsgi_pass unix:/var/www/MyApp/MyApp.sock;
    }
}

 server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
       root         /var/www/MyApp;
}

location / {
            uwsgi_pass unix:/var/www/myapp/MyApp/MyApp.sock;
            uwsgi_param UWSGI_TOUCH_RELOAD /var/www/MyApp/MyApp.sock;
            include uwsgi_params;

**Comment by GrahamDumpleton** [comment]
This is the issue tracker for mod_wsgi, not uWSGI. You will need to seek out a help forum or issue tracker for uWSGI.
