### ISSUE TITLE
Unable to install on windows 7 - ap_config_auto.h: No such file or directory

### ISSUE THREAD

**Issue by vladlee098** [GrahamDumpleton/mod_wsgi#277]
Hello Graham,

I'm getting below error when trying to run 'pip install mod_wsgi' on windows 7. This header file does not exist in Apache lounge package as well. Is there anyway to fix this?

PS. Apache directory name is default - 'c:\Apache24'

Thank you
Vlad

\temp.win-amd64-3.6\Release\src\server\mod_wsgi.o
    In file included from c:\Apache24/include/httpd.h:44:0,
                     from src/server\wsgi_apache.h:42,
                     from src/server\mod_wsgi.c:21:
    c:\Apache24/include/ap_config.h:138:28: fatal error: ap_config_auto.h: No such file or directory
    compilation terminated.

**Comment by GrahamDumpleton** [comment]
Are you using standard Windows environment, or are you trying to do this under cygwin or something else?

The ``ap_config.h`` header file has:

```
#if (!defined(WIN32) && !defined(NETWARE)) || defined(__MINGW32__)
#include "ap_config_auto.h"
#endif
```

So it should not be trying to include ``ap_config_auto.h`` on Windows if the compiler environment is set up correctly, as ``WIN32`` would be defined.

**Comment by vladlee098** [comment]
I have both installed on my machine. Is there any preference, I  did not find any in the docs. Should I just define WIN32 environment variable?

Thank you,
Vlad

**Comment by GrahamDumpleton** [comment]
You should not use cygwin and setting WIN32 environment variable will not do anything as that doesn't change the compiler flags. If you have things installed properly it should just work. Make sure you aren't using cygwin Python and compiler.

**Comment by GrahamDumpleton** [comment]
Closing since no followup. Open if still an issue.

**Comment by vladlee098** [comment]
Sorry for the delay, I was out for a week. I've removed cygwin from path and added vcvars.bat which usually has all the settings you need. Still no luck though, while error is different (see below). I run compilation via 'python setup.py build' command, but with pip install output is the same. 

Thank you for any suggestions,
Vlad

mod_wsgi.c
c:\users\u6013333\appdata\local\continuum\anaconda3\include\pyconfig.h(307): warning C4005: 'PLATFORM': macro redefinition
c:\apache24\include\os.h(42): note: see previous definition of 'PLATFORM'
src/server\mod_wsgi.c(471): warning C4267: 'initializing': conversion from 'size_t' to 'long', possible loss of data
src/server\mod_wsgi.c(472): warning C4267: 'initializing': conversion from 'size_t' to 'long', possible loss of data
src/server\mod_wsgi.c(580): warning C4267: '=': conversion from 'size_t' to 'long', possible loss of data
src/server\mod_wsgi.c(729): warning C4267: '=': conversion from 'size_t' to 'long', possible loss of data
src/server\mod_wsgi.c(775): warning C4267: '=': conversion from 'size_t' to 'long', possible loss of data
src/server\mod_wsgi.c(1860): warning C4244: '=': conversion from 'Py_ssize_t' to 'long', possible loss of data
src/server\mod_wsgi.c(3434): warning C4244: '=': conversion from 'Py_ssize_t' to 'long', possible loss of data
src/server\mod_wsgi.c(4251): error C2065: 'wsgi_daemon_process': undeclared identifier
src/server\mod_wsgi.c(4417): error C2065: 'wsgi_daemon_process': undeclared identifier
src/server\mod_wsgi.c(4417): error C2223: left of '->group' must point to struct/union
src/server\mod_wsgi.c(6052): warning C4244: 'return': conversion from '__int64' to 'long', possible loss of data
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
