### ISSUE TITLE
 fatal error C1083: Cannot open include file: 'httpd.h': No such file or directory

### ISSUE THREAD

**Issue by sirajalam049** [GrahamDumpleton/mod_wsgi#278]
I was installing mod_wsgi module in windows 10 64 bit and have wamp already installed.
Everything was fine but after copying so many files I got an error:

` fatal error C1083: Cannot open include file: 'httpd.h': No such file or directory`

I have read [this](https://github.com/GrahamDumpleton/mod_wsgi/issues/194) and installed the build tools. But I don't know what's wrong here.

**Comment by GrahamDumpleton** [comment]
When you say WAMP, which Apache distribution are you talking about? Various Apache distributions for Window do not include the necessary Apache header files and libraries to allow you to build third party Apache modules. The only one I test with and know works is the ApacheLounge distribution.

**Comment by sirajalam049** [comment]
Sorry, sir, I don't know which apache distribution is installed on my machine with wamp. Neither I know how to find out. Can you please assist me to find out which distribution is installed. 
And if not correct distro is installed, so what am I supposed to do in that case?

Currently, I'm using [this](http://www.wampserver.com/en/) wamp server.
http://www.wampserver.com/en/

THanks for reply.  :)

**Comment by GrahamDumpleton** [comment]
As I already said, the only one that I know works for sure is ApacheLounge (https://www.apachelounge.com/). Try using it.

**Comment by sirajalam049** [comment]
Is it going to make some problem if I use two apache in a single machine? Do I need to uninstall the wamp server now?

**Comment by GrahamDumpleton** [comment]
You just can't have them both running at the same time and trying to use the same port for accepting connections. By default they would use port 80. If you change one to use port 8080 and then use the port number in URLs when accessing it, that will work.

**Comment by sirajalam049** [comment]
OK, please don't close this thread now. Let me do the steps, and If they'll work, I'll let you know.

**Comment by sirajalam049** [comment]
I uninstalled the wamp server package and installed each software (apache, mysql, php) manually. I'm no longer having this `http.h` missing error.

Thank You

**Comment by Karuhanga** [comment]
Using the apache lounge version helped clear this. Also, ensure your MOD_WSGI_APACHE_ROOTDIR path variable is set to the apache folder. Mine was pointing to the Apache24/bin folder.

**Comment by JeetR** [comment]
Thanks Every one this helped i just downloaded apache from apachefriends and saved it in c
I made changes as pointed by Karuhanga and it has successfully installed mod_wsgi

**Comment by girishlc** [comment]
Make sure that you have the apache in the right folder. It gives the same error even if you have the wrong path in Apache.

Correct path:
C:\Apache24\bin

**Comment by GrahamDumpleton** [comment]
You should use forward slashes, not backward slashes in path when setting `MOD_WSGI_APACHE_ROOTDIR`. Backward slashes may not work, perhaps depending on the shell you are using.

**Comment by sidgitind** [comment]
> Make sure that you have the apache in the right folder. It gives the same error even if you have the wrong path in Apache.
> 
> Correct path:
> C:\Apache24\bin

I was able to get it working...
by changing the folder to C:\wamp64\bin\apache\apache2.4.41 instead of C:\wamp64\bin\apache\apache2.4.41\bin.
The httpd.h folder is in C:\wamp64\bin\apache\apache2.4.41\include folder. Having bin in the path doesnt help the program find this file. Thanks

**Comment by muzaman** [comment]
Thanks, it is important:
1. Download Apache from https://www.apachelounge.com/
2. Unpack it to c:\Apache24
3. Set environment variable MOD_WSGI_APACHE_ROOTDIR = c:\Apache24
4. pip install mod_wsgi

**Comment by GrahamDumpleton** [comment]
You should use backslash when setting variable. Use:

```
MOD_WSGI_APACHE_ROOTDIR=c:/Apache24
```

Backslashes will be interpreted as character escapes and you will have problems.
