### ISSUE TITLE
Wrong default value for queue-timeout

### ISSUE THREAD

**Issue by albertca** [GrahamDumpleton/mod_wsgi#280]
queue-timeout defaults to 45 seconds:

https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/__init__.py#L2127

Yet its help says the default is 30 seconds:

https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/__init__.py#L2131

**Comment by GrahamDumpleton** [comment]
Fixed, thanks. https://github.com/GrahamDumpleton/mod_wsgi/commit/6df8f9cd4356ba80e9f415052a500c12d665fea2
