### ISSUE TITLE
4.6.2 Python 3.6 problems

### ISSUE THREAD

**Issue by tximpa91** [GrahamDumpleton/mod_wsgi#282]
I compile my configure my Python with ./configure --enable-shared --enable-optimizations  LDFLAGS="-Wl,--rpath=/usr/local/lib" later make Install after that i download the 4.6.2 Package and set ./configure --with-apxs=/usr/bin/apxs  --with-python=/usr/local/bin/python3 and Install perfect but i can load mod_wsgi Cannot load /usr/lib64/apache2/modules/mod_wsgi.so into server: libpython3.6m.so.1.0:

This not happen with 4.6.1 version of the Package.

**Comment by GrahamDumpleton** [comment]
You appear to have truncated the error messages. I need to see all of the messages.

Also read:

* http://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#unable-to-find-python-shared-library

You likely aren't setting ``LD_RUN_PATH`` environment variable at compile time, which is needed when using configure/make/make install method when Python is not in a standard location.

Better still, use the ``pip install`` method of installing mod_wsgi. See:

* https://pypi.python.org/pypi/mod_wsgi

**Comment by tximpa91** [comment]
But if i Install the Package 4.6.2 it doesn't gave me any problems is kind of odd

**Comment by GrahamDumpleton** [comment]
Did you mean to say 4.6.1 then?

The difference between 4.6.1 and 4.6.2 is very minor and shouldn't affect ability to find the shared library.

I really need to see the full messages so can verify whether issue is that can't find shared library, or that it is complaining about a undefined symbol. There are changes ready for 4.6.3 relating to undefined symbols, but  one is for Python 2.6, and the other Windows, so shouldn't be relevant.

**Comment by tximpa91** [comment]
Sorry yes 4.6.1 i put de LDFLAGS in the configure of the Package and type ldconfig after the make Install and now is all okey with 4.6.2

**Comment by GrahamDumpleton** [comment]
Defining it when building Python doesn't help mod_wsgi as mod_wsgi doesn't run the ``python`` executable, it links the shared library. For mod_wsgi you would use:

```
./configure --with-apxs=/usr/bin/apxs --with-python=/usr/local/bin/python3
LD_RUN_PATH=/usr/local/lib make
make install
```

Note that ``LD_RUN_PATH`` is set on same line as ``make`` is run. That isn't a typo.

If you use ``pip install`` it does that setting of ``LD_RUN_PATH`` under the covers for you when doing the build.

**Comment by tximpa91** [comment]
Thanks with this method it also work to.

Thank you very much
