### ISSUE TITLE
 Exception TypeError: "'NoneType' object is not callable"

### ISSUE THREAD

**Issue by Velu-Narasimman** [GrahamDumpleton/mod_wsgi#283]
Hi Graham,

I had a strange behaviour in my application, image, css, js files were not loaded when I upgraded to http2. When I examined the logs I found the below error was logged more frequently.
    ` [Thu Mar 15 17:19:10.511977 2018] [wsgi:error] [pid 19707:tid 140401406551808] [client 172.24.188.116:43497] IOError: Apache/mod_wsgi client connection closed., referer: https://example.com/PMO/myprojects"`
After googling, I found your answer saying that it was a bug and will be fixed as part of mod_wsgi 4.5.25.
Then I downloaded and installed mod_wsgi 4.6.2 from this github repo. That solved my problem and css, js, images files were loaded without fail. But the error is still logged into my log files.

Now I am seeing some more errors in my log and my app is taking more time to load. Below are the errors,
`
[Thu Mar 15 17:18:57.552814 2018] [wsgi:info] [pid 18135:tid 139724774999936] mod_wsgi (pid=18135): Terminating Python.
[Thu Mar 15 17:18:57.607437 2018] [wsgi:error] [pid 18134:tid 139724774999936] Exception TypeError: "'NoneType' object is not callable" in <bound method PooledConnection.__del__ of <trac.db.pool.PooledConnection object at 0x7f13f7886368>> ignored
[Thu Mar 15 17:18:57.621463 2018] [wsgi:info] [pid 18134:tid 139724774999936] mod_wsgi (pid=18134): Python has shutdown.
[Thu Mar 15 17:18:57.624662 2018] [wsgi:error] [pid 18135:tid 139724774999936] Exception TypeError: "'NoneType' object is not callable" in <bound method PooledConnection.__del__ of <trac.db.pool.PooledConnection object at 0x7f13f3a2d940>> ignored
[Thu Mar 15 17:18:57.633320 2018] [wsgi:error] [pid 18135:tid 139724774999936] Exception TypeError: "'NoneType' object is not callable" in <bound method PooledConnection.__del__ of <trac.db.pool.PooledConnection object at 0x7f13f2ba9d60>> ignored
[Thu Mar 15 17:18:57.636423 2018] [wsgi:error] [pid 18135:tid 139724774999936] Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method WSDL.__del__ of <SOAPpy.wstools.WSDLTools.WSDL instance at 0x7f13f2e5d0e0>> ignored
[Thu Mar 15 17:18:57.643506 2018] [wsgi:info] [pid 18135:tid 139724774999936] mod_wsgi (pid=18135): Python has shutdown.
` 
I have no idea on what was wrong and how to solve these, please help me.

**Comment by GrahamDumpleton** [comment]
Can you point to where I said that was a bug that would be fixed in 4.5.25 (actually ended up being 4.6.0). That message can arise for various reasons totally unrelated to any changes made in 4.6.0. You may be confusing issues with a very specific use case with whatever issue you were having.

The new errors you are getting is because you are running daemon type threads in Python. When the Python interpreter is being destroyed on process shutdown, there is no way to kill off those threads first. During the destruction of the Python interpreter, one of the things it does is override attribute lookup against modules so ``None`` objects are returned. This means that if those threads wake up and start running, they can find that stuff they want to use has turned to ``None`` objects. This is all just part of how Python works and as far as I know can affect normal command line Python as well. You don't see it as much in command line Python because threads in that usually inherit non daemon property and so Python will attempt to wait on them to finish on shutdown.

The only way to try and avoid the messages showing up is to register an ``atexit`` callback which notifies threads to stop and wait for them to stop, before returning from the callback. That way they will be stopped when Python interpreter is destroyed.

**Comment by Velu-Narasimman** [comment]
Sorry if that confused you!, And fortunately I had bookmarked that url and here it is...
[https://github.com/GrahamDumpleton/mod_wsgi/issues/117](url)  at the bottom of that page you have mentioned that it will be released in mod_wsgi version 4.5.25.

And here you can see the `[wsgi:error]` messages that were logged in my log file.
`
[Thu Mar 15 16:30:04.524451 2018] [wsgi:error] [pid 18134:tid 139724471936768] [client 172.24.188.116:59712] IOError: Apache/mod_wsgi client connection closed., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.524892 2018] [wsgi:error] [pid 18134:tid 139724354438912] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.524920 2018] [wsgi:error] [pid 18134:tid 139724354438912] [client 172.24.188.116:59712] IOError: Apache/mod_wsgi client connection closed., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.584559 2018] [wsgi:error] [pid 18134:tid 139724463544064] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.584601 2018] [wsgi:error] [pid 18134:tid 139724463544064] [client 172.24.188.116:59712] IOError: Apache/mod_wsgi client connection closed., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.705530 2018] [wsgi:error] [pid 18134:tid 139724455151360] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.705841 2018] [wsgi:error] [pid 18134:tid 139724455151360] [client 172.24.188.116:59712] IOError: Apache/mod_wsgi client connection closed., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.706053 2018] [wsgi:error] [pid 18134:tid 139724497114880] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.707064 2018] [wsgi:error] [pid 18134:tid 139724497114880] [client 172.24.188.116:59712] IOError: Apache/mod_wsgi client connection closed., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.763198 2018] [wsgi:error] [pid 18134:tid 139724488722176] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.763565 2018] [wsgi:error] [pid 18134:tid 139724488722176] [client 172.24.188.116:59712] IOError: Apache/mod_wsgi client connection closed., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.875914 2018] [wsgi:error] [pid 18134:tid 139724388009728] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.931163 2018] [wsgi:error] [pid 18134:tid 139724421580544] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.931242 2018] [wsgi:error] [pid 18134:tid 139724421580544] [client 172.24.188.116:59712] IOError: Apache/mod_wsgi client connection closed., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
[Thu Mar 15 16:30:04.931749 2018] [wsgi:error] [pid 18134:tid 139724480329472] [client 172.24.188.116:59712] mod_wsgi (pid=18134): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'., referer: https://traclocal.aspiresys.com/Nashira/timesheet/weekly
`

Please help me to understand them and give me idea to get rid of these.

Thank you!

**Comment by GrahamDumpleton** [comment]
Sorry for slow reply. This got lost during a busy patch.

Are you using embedded mode or daemon mode of mod_wsgi?

**Comment by Velu-Narasimman** [comment]
I am not sure what is embedded mode or daemon mode actually is, well, please explain it if you could. When I executed the command `apache2ctl -M` I found that mod_wsgi is shared ` wsgi_module (shared)`.

**Comment by GrahamDumpleton** [comment]
Are you using ``WSGIDaemonProcess`` and ``WSGIProccessGroup`` directives, or ``process-group`` option of ``WSGIScriptAlias``?

* http://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html
* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#embedded-or-daemon-mode

**Comment by Velu-Narasimman** [comment]
Nope, I have used the directives say, `WSGIApplicationGroup %{GLOBAL}` and `WSGIScriptAlias / /path/to/the_wsgi_conf_file` not more than those two directives.

**Comment by GrahamDumpleton** [comment]
It is always recommended to use daemon mode unless you know enough that it isn't the right thing to use.

* http://blog.dscpl.com.au/2012/10/why-are-you-using-embedded-mode-of.html

There are a bunch of options you can set for timeouts etc when in daemon mode that will make your site more robust.

* https://www.youtube.com/watch?v=H6Q3l11fjU0

**Comment by GrahamDumpleton** [comment]
Closing on assumption that nothing further can be done for this issue.
