### ISSUE TITLE
Django project on Windows 7, Target WSGI script cannot be loaded as Python module

### ISSUE THREAD

**Issue by XHBP63** [GrahamDumpleton/mod_wsgi#285]
My setup:
- Windows 7 64-bit installed on virtual machine on company's network
- Python 3.6 (64-bit)
- Apache 2.4 from Apache Lounge
- mod_wsgi version 4.5.24, because according to comments here (https://stackoverflow.com/questions/49264061/pip-install-mod-wsgi-failed-window-server-12-python-3-6-4-64-bit-vc14) version 4.6 does not work on Windows, and it wasn't installing for me
- VC14 or 15, I'm not sure, I installed from here: http://landinghub.visualstudio.com/visual-cpp-build-tools

I think right now my problem is either that my versions don't match or that my Apache config is not set up correctly. Here is what I added to my httpd.conf:
```
LoadFile "c:/program files/python36/python36.dll"
LoadModule wsgi_module "c:/program files/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/program files/python36"

WSGIScriptAlias / "C:/Apache24/htdocs/BenchmarkingSiteDjango/wsgi.py"
WSGIPythonPath "C:/Apache24/htdocs/BenchmarkingSiteDjango"

<Directory "C:/Apache24/htdocs/BenchmarkingSiteDjango">
<Files wsgi.py>
Require all granted
</Files>
</Directory>
```

And here is what my Apache error.log shows:

> [Tue Mar 27 12:07:54.541104 2018] [mpm_winnt:notice] [pid 6004:tid 476] AH00455: Apache/2.4.29 (Win64) mod_wsgi/4.5.24 Python/3.6 configured -- resuming normal operations
> [Tue Mar 27 12:07:54.542104 2018] [mpm_winnt:notice] [pid 6004:tid 476] AH00456: Apache Lounge VC15 Server built: Nov  3 2017 11:12:00
> [Tue Mar 27 12:07:54.542104 2018] [core:notice] [pid 6004:tid 476] AH00094: Command line: 'C:\\Apache24\\bin\\httpd.exe -d C:/Apache24'
> [Tue Mar 27 12:07:54.548104 2018] [mpm_winnt:notice] [pid 6004:tid 476] AH00418: Parent: Created child process 7952
> [Tue Mar 27 12:07:55.880104 2018] [mpm_winnt:notice] [pid 7952:tid 504] AH00354: Child: Starting 64 worker threads.
> **[Tue Mar 27 12:08:20.516104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440] mod_wsgi (pid=7952): Target WSGI script 'C:/Apache24/htdocs/BenchmarkingSiteDjango/wsgi.py' cannot be loaded as Python module.**
> [Tue Mar 27 12:08:20.516104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440] mod_wsgi (pid=7952): Exception occurred processing WSGI script 'C:/Apache24/htdocs/BenchmarkingSiteDjango/wsgi.py'.
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440] Traceback (most recent call last):\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "C:/Apache24/htdocs/BenchmarkingSiteDjango/wsgi.py", line 16, in <module>\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]     application = get_wsgi_application()\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "C:\\Program Files\\Python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]     django.setup(set_prefix=False)\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "C:\\Program Files\\Python36\\lib\\site-packages\\django\\__init__.py", line 19, in setup\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "C:\\Program Files\\Python36\\lib\\site-packages\\django\\conf\\__init__.py", line 56, in __getattr__\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]     self._setup(name)\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "C:\\Program Files\\Python36\\lib\\site-packages\\django\\conf\\__init__.py", line 43, in _setup\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]     self._wrapped = Settings(settings_module)\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "C:\\Program Files\\Python36\\lib\\site-packages\\django\\conf\\__init__.py", line 106, in __init__\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]     mod = importlib.import_module(self.SETTINGS_MODULE)\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "C:\\Program Files\\Python36\\lib\\importlib\\__init__.py", line 126, in import_module\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]     return _bootstrap._gcd_import(name[level:], package, level)\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
> [Tue Mar 27 12:08:20.519104 2018] [wsgi:error] [pid 7952:tid 1008] [client 10.61.35.50:61440] ModuleNotFoundError: No module named 'BenchmarkingSiteDjango'\r

Thank you for any help you can offer!

**Comment by GrahamDumpleton** [comment]
Because of where you have put your project code, you should be using:

```
WSGIPythonPath "C:/Apache24/htdocs/BenchmarkingSiteDjango"
```

Note though that it is a bad idea to place your project code under that ``htdocs`` directory. This is because that is the Apache ``DocumentRoot`` directory. If you were to comment out ``WSGIScriptAlias``, someone could download your source code. So better to put your project code elsewhere as there is no reason for it to be under ``DocumentRoot``.

**Comment by XHBP63** [comment]
Isn't that what I had for WSGIPythonPath already though? Thanks for that info about the DocumentRoot though, I moved everything to a folder on the C drive called "Site". Now my conf file looks like this:
```
LoadFile "c:/program files/python36/python36.dll"
LoadModule wsgi_module "c:/program files/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/program files/python36"

WSGIScriptAlias / "C:/Site/BenchmarkingSiteDjango/wsgi.py"
WSGIPythonPath "C:/Site/BenchmarkingSiteDjango"

<Directory "C:/Site/BenchmarkingSiteDjango">
<Files wsgi.py>
Require all granted
</Files>
</Directory>
```
And I get the same error in the Apache log.

**Comment by XHBP63** [comment]
And this is my wsgi.py file:
```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "BenchmarkingSiteDjango.settings")

application = get_wsgi_application()
```

**Comment by GrahamDumpleton** [comment]
Hmmm, I did a stupid cut and paste above with actually then editing it.

I said to use:

```
WSGIPythonPath "C:/Apache24/htdocs/BenchmarkingSiteDjango"
```

but that was what you were using. I meant to say:

```
WSGIPythonPath "C:/Apache24/htdocs"
```

The directory needs to be the parent directory to where the package for the Django project code is.

So based on your changed configuration, should be:

```
WSGIPythonPath "C:/Site"
```

**Comment by GrahamDumpleton** [comment]
Closing. No further followup. Presuming that issue was resolved.
