### ISSUE TITLE
Document usage with Pipenv

### ISSUE THREAD

**Issue by voidus** [GrahamDumpleton/mod_wsgi#286]
Pipenv[1] is the officially recommended environment manager for application projects[2], so it would be great to include an "official way" to deploy project that use Pipenv on mod_wsgi.

[1] https://pipenv.readthedocs.io/en/latest/
[2] https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies

**Comment by GrahamDumpleton** [comment]
Is there anything specific that is strange enough that needs documenting? It creates a virtual environment under the covers, so the normal step of using ``sys.prefix`` value with ``WSGIPythonHome`` or ``python-home`` should still apply, correct? Or are you suggesting there are additional steps now required?

**Comment by voidus** [comment]
I guess what made me looking for additional docs is that pipenv controls where the virtualenv will be located. When it is created directly, I decided it's location, which allowed us to use a well-known location which is referenced in the WSGIDaemonProcess directive.

This is probably not the right place to look for that kind of information, so I'm going to close this.

For reference, to get the location of the virtual environment when using pipenv, you can use `pipenv --venv` (this is basically the same as sys.prefix)

For our deployment, I decided to manually create a virtual environment and use pipenv inside that. (When used inside an existing env, pipenv uses that instead of managing it itself)

**Comment by GrahamDumpleton** [comment]
> When used inside an existing env, pipenv uses that instead of managing it itself

Actually, ``pipenv`` in some cases used to do nasty things and remove the virtual environment when you tried that.

* https://github.com/pypa/pipenv/issues/819

:-)

**Comment by voidus** [comment]
Wow, thank you for bringing this to my attention!
