### ISSUE TITLE
Unable to append path to root url

### ISSUE THREAD

**Issue by pmc2010** [GrahamDumpleton/mod_wsgi#289]
I think this is similar to #149 . I am trying to configure apache to run on my local machine with the root url being 127.0.0.1/domportal rather than 127.0.0.1.  The reason for this is that I will be deploying the application to a server that hosts multiple sites.  I need to be able to test out Django url reverse to make sure the urls will point to domain.com/domportal/destination_page and not domain.com/destination_page.

I set up a separate .conf file that looks like this:
WSGIScriptAlias /domportal /path/to/wsgi_local.py
WSGIProcessGroup ${MOD_WSGI_LISTENER_HOST}:${MOD_WSGI_HTTP_PORT}

Alias /domportal/media /path/to/media/
Alias /domportal/static /path/to/assets/

<Directory /path/to/media>
    #Order allow,deny
    #Allow from all
    Require all granted
</Directory>

<Directory /path/to/assets>
    #Order allow,deny
    #Allow from all
    Require all granted
</Directory>

<Directory /path/to/document/root>
    <Files wsgi_local.py>
        #Order allow,deny
        #Allow from all
        Require all granted
    </Files>
</Directory>

It kind of works, but not really.  The startup command I am using is:
mod_wsgi-express start-server /path/to/wsgi_local.py --port 8080 --include-file /path/to/wsgi_httpd.conf --server-root /tmp/wsgi

When I use that command, it looks like everything is fine, but when I look at the source code, I can see that the static files are actually referencing /static/file.css rather than /domportal/static/file.css.

If I run this command:
mod_wsgi-express start-server --port 8080 --include-file /path/to/wsgi_httpd.conf --server-root /tmp/wsgi

the page doesn't render because there are no longer static files located at /static/file.css.

This is different from the server behavior.  On the server, the same application is configured in a similar manner (except it is configured on apache, not on mod_wsgi-express, and when I view the source code, it shows the static links as /domportal/file.css.

Is there a way to start up the mod_wsgi-express server so that all urls start with /domportal/ ?  i.e. that the root url is seen by Django as http://127.0.0.1/domportal/ rather than http://127.0.0.1/ ?

**Comment by GrahamDumpleton** [comment]
You can run ``mod_wsgi-express start-server --help`` to see all the options.

In this case you want:

```
--mount-point /domportal
```

**Comment by pmc2010** [comment]
That doesn't seem to change anything.  I tried the following:
mod_wsgi-express start-server /path/to/wsgi_local.py --port 8080 --mount-point /domportal

But the static file links in the page source code don't show /domportal at the start of their path.

Same thing if I try this command:
mod_wsgi-express start-server --port 8080 --mount-point /domportal --include-file /path/to/wsgi_httpd.conf

**Comment by GrahamDumpleton** [comment]
If you are using Django, you also need to override ``STATIC_URL`` in the Django settings file to add ``/domportal`` in front. Django doesn't automatically change that when application is mounted at a sub URL. That is, for static assets , it ignores the value of ``SCRIPT_NAME`` which is passed in.

So even if you are using ``--url-alias /domportal/static .../some/path/to/static/files``, or have put the static files under the sub directory ``domportal/static`` of the ``htdocs`` directory of ``mod_wsgi-express``, if you don't change ``STATIC_URL`` then Django will generate the wrong URLs.

**Comment by pmc2010** [comment]
I’m not sure that that is required. On our production machine we have 2 servers running concurrently: Django’s runserver which is running on port 8080 and has base url domain.com:8080, and an Apache version that has base url domain.com/domportal. Both versions are sharing the same Django codebase and using the same Django settings file.
When I look at the “view source” in my browser for the site running on the Django server the static files don’t show domportal. When I look at the Apache site and view source, I see domportal at the beginning of the links. The only difference then would be the Apache configuration.
The reason I am trying to get this to work is so I can have both sites up temporarily until I finish testing the Apache site.
And I want to replicate it on my laptop so I can make fixes targeted to the Apache version and make sure it works the same locally both for Apache and Django server.

**Comment by GrahamDumpleton** [comment]
When you use the Django development server, it will serve static files for you. If using ``mod_wsgi-express`` you need to use ``--url-alias`` to specify where the static files are, or have the static files under the default document root, or alternate directory specified by ``--document-root``, to serve them, unless you are using Whitenoise middleware.

Are you doing any of those?

Details in:

* http://blog.dscpl.com.au/2015/04/introducing-modwsgi-express.html
* http://blog.dscpl.com.au/2015/04/using-modwsgi-express-with-django.html

**Comment by pmc2010** [comment]
Turns out there was a slight discrepancy between the settings file I was using on production and the settings file I was using locally.  Once I aligned them, it worked locally.  Thank you for your help!
