### ISSUE TITLE
Pypy3 support

### ISSUE THREAD

**Issue by thierryba** [GrahamDumpleton/mod_wsgi#290]
I've just tried to compile mod_wsgi and it seems it can't be done using pypy3. I tried on mac with a home-brew build of pypy3. Is that support planned any time soon?

**Comment by GrahamDumpleton** [comment]
You can only use CPython with mod_wsgi. You cannot use pypy. The mod_wsgi code is basically all C code. There will never be support for pypy as it is not possible.
