### ISSUE TITLE
Regression with "urllib.parse.unquote" and mod_wsgi 4.6.x

### ISSUE THREAD

**Issue by jcea** [GrahamDumpleton/mod_wsgi#292]
Under mod_wsgi 4.6.x, "urllib.parse.unquote()" creates latin-1/raw (no encoding) instead of "utf-8" (the declared default in the documentation).

From the command line I see this (correct behavior):

```
Python 3.6.4 (default, Feb  7 2018, 15:09:44) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import unquote
>>> unquote('Debates%20T%C3%B3picos%20y%20Ut%C3%B3picos%20-%2020180326%2021:00.opus')
'Debates Tópicos y Utópicos - 20180326 21:00.opus'
```

"utf-8" encoding. Good.

Doing the same inside mod_wsgi (daemon mode) I get this incorrectly encoded string:

```
Debates TÃ³picos y UtÃ³picos - 20180402 21:00.opus
```

Notice the failure to correctly encode the tildes. The result is "utf-8" but encoded with "latin-1" (no encoding), or something similar.

At first I thought mod_wsgi 4.6.4 had a regression with lang/encoding. I use this in my Apache configuration, following http://blog.dscpl.com.au/2014/09/setting-lang-and-lcall-when-using.html :

```
WSGIDaemonProcess jcea threads=16 display-name=%{GROUP} python-path=/home/wsgi/home=/home/wsgi/ stack-size=524288 lang='en_US.UTF-8' locale='en_US.UTF-8'
```

But doing this inside my wsgi script:

```
print(locale.getdefaultlocale(), locale.getpreferredencoding(), file=f)
```

I get the right values: ```('en_US', 'UTF-8') UTF-8```.

The code used to worked under 4.5.x. It stopped working at 4.6.x. Tested up to 4.6.4.

My current workaround in my code is:

```
-    fichero = unquote(componentes[-1])
+    fichero = unquote(componentes[-1], encoding='latin-1')
+    fichero =fichero.encode('latin-1').decode('utf-8')
```

Ugly as hell but it works.

**Comment by GrahamDumpleton** [comment]
How are you using the value of ``fichero``?

If I use:

```
def application(environ, start_response):
    status = '200 OK'

    from urllib.parse import unquote
    output = unquote('Debates%20T%C3%B3picos%20y%20Ut%C3%B3picos%20-%2020180326%2021:00.opus')
    output = output.encode('UTF-8')

    response_headers = [('Content-type', 'text/plain; charset=UTF-8'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]
```

I see the correct response in the browser for both 4.5.24 and 4.6.4.

Important is to ensure that ``charset`` is set in content type response header. Even when I don't and browser interprets it wrongly, still see same result in both versions.

Note, don't rely on using ``print()`` and looking at the value in the Apache error logs and Apache shows it in a strange way, likely as Latin-1 bytes.

**Comment by jcea** [comment]
I use it for "open" a file in the local filesystem:

The workaround to my code is (showing usage):

```
--- a/ansible/roles/web/files/wsgi/wsgi.py
+++ b/ansible/roles/web/files/wsgi/wsgi.py
@@ -458,7 +458,12 @@
     componentes = uri.split('/')
 
     token = componentes[-2]
-    fichero = unquote(componentes[-1])
+    fichero = unquote(componentes[-1], encoding='latin-1')
+    fichero =fichero.encode('latin-1').decode('utf-8')
+    with open("/tmp/z.txt", "w", encoding='utf-8') as f:
+        import locale
+        print(locale.getdefaultlocale(), locale.getpreferredencoding(), file=f)
+        print(fichero, file=f)
     fichero = pathlib.Path('/media/INTERNO/grabaciones') / fichero
     tipo = fichero.suffix
     fichero = fichero.with_suffix('.opus')
`
```

**Comment by jcea** [comment]
OK; I have found the issue: A library I was using changed from using ```environ['REQUEST_URI']``` to use now  ```environ['SCRIPT_NAME'] + PATH_environ['PATH_INFO']```.

I see this in the environment:

```
...
'REQUEST_URI': '/download/50243965332557670656124045506460/Debates%20T%C3%B3picos%20y%20Ut%C3%B3picos%20-%2020180402%2021:00.opus',
'PATH_INFO': '/download/50243965332557670656124045506460/Debates TÃ³picos y UtÃ³picos - 20180402 21:00.opus',
'mod_wsgi.path_info': '/download/50243965332557670656124045506460/Debates TÃ³picos y UtÃ³picos - 20180402 21:00.opus',
...
```

At first, I would expect PATH_INFO to be decoded as UTF-8. But:

- PEP 3333 contains this language:

    all "strings" referred to in this specification must contain only code points representable in ISO-8859-1 encoding (\u0000 through \u00FF, inclusive)

- Stale (I don't know corresponding URL in the new docs) <https://code.google.com/archive/p/modwsgi/wikis/SupportForPython3X.wiki> says:

   For the CGI variables contained in the WSGI environment, the values of the variables are native strings. Where native strings are unicode strings, ISO-8859-1 encoding would be used such that the original character data is preserved and as necessary the unicode string can be converted back to bytes and thence decoded to unicode again using a different encoding.

So I consider this issue settled. I close this bug as a "not a bug". Now I have to "bug" the upstream library that did the change.

Thanks!.

**Comment by GrahamDumpleton** [comment]
Thanks for letting me know. Using ``REQUEST_URI`` is somewhat dangerous because it hasn't been decoded or had path normalisation done on it. Worst thing you can do is use it in raw form to match file system paths which are serving up to users without cleaning it up yourself as can be used for path traversal attacks. So is actually good to see they have stopped using it.

**Comment by jcea** [comment]
Path normalization... interesting...

I am currently patching the library as:

```
   uri = environ['PATH_INFO']

    # No es un bug, ver
    # https://github.com/GrahamDumpleton/mod_wsgi/issues/292
    uri = uri.encode('latin-1').decode('utf-8')
```

So the rest of the code doesn't need to worry about this.

Yes, I know I can crash it with invalid utf-8. Not a problem in my use case.

**Comment by GrahamDumpleton** [comment]
FWIW, by path normalisation, I mean more than just ``%`` decoding and conversion to Unicode.

```
>>> import posixpath
>>> posixpath.normpath('/a/b/c/../d')
'/a/b/d'
>>> posixpath.normpath('/../../../etc/passwd')
'/etc/passwd'
```

So you want to use ``posixpath.normpath()`` on the URL path to eliminate ``../`` and ``./``. This is so you don't join a path with ``../`` in it to a base directory and allow a user to traverse outside of it, if that path was then used in mapping to file system.

This is if using ``REQUEST_URI``. If a WSGI server is not already doing this for ``PATH_INFO`` then it is arguably broken. In the case of mod_wsgi, it is actually Apache web server which does the normalisation and so mod_wsgi gets ``PATH_INFO`` in already normalised form.
