### ISSUE TITLE
No module named site

### ISSUE THREAD

**Issue by tejinderper** [GrahamDumpleton/mod_wsgi#293]
Hi

I have googled all the threads related to this error but I don't seem to have different python versions for compiled so file and actual virtual env file, here is the output of the ldd on .so file:

libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f51b936d000)

And here is my apache app config:

```
Alias /static /home/centos/Projects/sps/staticfiles
<Directory /home/centos/Projects/sps/staticfiles>
  Require all granted
</Directory>

<Directory /home/centos/Projects/sps/config>
  <Files wsgi.py>
      Require all granted
   </Files>
 </Directory>

WSGIDaemonProcess sps python-home=/home/centos/venvs/sps python-path=/home/centos/Projects/sps
WSGIProcessGroup sps
WSGIScriptAlias / /home/centos/Projects/sps/config/wsgi.py process-group=sps
```

I am using django 1.11 to for the application latest mod_wsgi python package

**Comment by GrahamDumpleton** [comment]
From the command line, when you activate the Python virtual environment and run ``python``, what do you get when run in the interpreter:

```
import sys
print(sys.prefix)
```

Also, what do you get for:

```
ls -lasd /home/centos
```

Home directories on some operating system distributions are not readable by others and so you can't put your project and virtual environment under your home directory. Better to put under a directory such as ``/var/www/myproject``.

**Comment by tejinderper** [comment]
Getting different error this time:

[Thu Apr 19 13:52:39.155055 2018] [:error] [pid 2002] [remote 127.0.0.1:140] mod_wsgi (pid=2002): Target WSGI script '/var/www/sps/config/wsgi.py' cannot be loaded as Python module.
[Thu Apr 19 13:52:39.155078 2018] [:error] [pid 2002] [remote 127.0.0.1:140] mod_wsgi (pid=2002): Exception occurred processing WSGI script '/var/www/sps/config/wsgi.py'.
[Thu Apr 19 13:52:39.155093 2018] [:error] [pid 2002] [remote 127.0.0.1:140] Traceback (most recent call last):
[Thu Apr 19 13:52:39.155107 2018] [:error] [pid 2002] [remote 127.0.0.1:140]   File "/var/www/sps/config/wsgi.py", line 37, in <module>
[Thu Apr 19 13:52:39.155132 2018] [:error] [pid 2002] [remote 127.0.0.1:140]     application = get_wsgi_application()
[Thu Apr 19 13:52:39.155137 2018] [:error] [pid 2002] [remote 127.0.0.1:140]   File "/var/www/sps/env/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Thu Apr 19 13:52:39.155150 2018] [:error] [pid 2002] [remote 127.0.0.1:140]     django.setup(set_prefix=False)
[Thu Apr 19 13:52:39.155154 2018] [:error] [pid 2002] [remote 127.0.0.1:140]   File "/var/www/sps/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
[Thu Apr 19 13:52:39.155161 2018] [:error] [pid 2002] [remote 127.0.0.1:140]     apps.populate(settings.INSTALLED_APPS)
[Thu Apr 19 13:52:39.155165 2018] [:error] [pid 2002] [remote 127.0.0.1:140]   File "/var/www/sps/env/lib/python2.7/site-packages/django/apps/registry.py", line 78, in populate
[Thu Apr 19 13:52:39.155172 2018] [:error] [pid 2002] [remote 127.0.0.1:140]     raise RuntimeError("populate() isn't reentrant")
[Thu Apr 19 13:52:39.155184 2018] [:error] [pid 2002] [remote 127.0.0.1:140] RuntimeError: populate() isn't reentrant

I ran the semenage command as well:
semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/sps/(/.*)?"
restorecon -Rv "/var/www/sps"

I made /var/www/sps/config/wsgi.py executable as well

Please guide

Thanks

**Comment by GrahamDumpleton** [comment]
You need to go back in the logs and find the very first error message after processes were restarted. The ``populate() isn't reentrant`` error is from subsequent requests, and not the very first one which describes the real cause.

**Comment by tejinderper** [comment]
Thanks a lot for your help, it turns out i did not have permissions on the psycopg libs modules in the virtual env, had to run semanage fcontext -a -t httpd_sys_script_exec_t command on the modules. Seems to be working fine now. Thanks again
