### ISSUE TITLE
Error in running Django project with apache, getting Failed to exec python script file in wsgi.py

### ISSUE THREAD

**Issue by tanweer123** [GrahamDumpleton/mod_wsgi#294]
I'm keep getting Exception occurred processing WSGI script '/var/www/html/Datalake/Datalake/wsgi.py'  and Failed to exec Python script file '/var/www/html/Datalake/Datalake/wsgi.py'. and lastly its saying ModuleNotFoundError: No module named 'django' in wsgi.py file, line 12. 
I searched a lot but no case worked for me. I don't know what mistake i'm doing .
below is my apache conf file.
[httpd.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/1883744/httpd.txt)

and some part of my apache error_log file
atalake/wsgi.py'.
[Fri Apr 06 06:47:53.168225 2018] [wsgi:error] [pid 31669] [client ip:59796] mod_wsgi (pid=31669): Exception occurred processing WSGI script '/var/www/html/Datalake/Datalake/wsgi.py'.
[Fri Apr 06 06:47:53.168403 2018] [wsgi:error] [pid 31669] [client ip:59796] Traceback (most recent call last):
[Fri Apr 06 06:47:53.168461 2018] [wsgi:error] [pid 31669] [client ip:59796]   File "/var/www/html/Datalake/Datalake/wsgi.py", line 12, in <module>
[Fri Apr 06 06:47:53.168476 2018] [wsgi:error] [pid 31669] [client ip:59796]     from django.core.wsgi import get_wsgi_application
[Fri Apr 06 06:47:53.168523 2018] [wsgi:error] [pid 31669] [client ip:59796] ModuleNotFoundError: No module named 'django'
[Fri Apr 06 07:18:30.408224 2018] [wsgi:error] [pid 31673] [client ip:59940] mod_wsgi (pid=31673): Failed to exec Python script file '/var/www/html/Datalake/Datalake/wsgi.py'.
[Fri Apr 06 07:18:30.408300 2018] [wsgi:error] [pid 31673] [client ip:59940] mod_wsgi (pid=31673): Exception occurred processing WSGI script '/var/www/html/Datalake/Datalake/wsgi.py'.
[Fri Apr 06 07:18:30.408440 2018] [wsgi:error] [pid 31673] [client ip:59940] Traceback (most recent call last):
[Fri Apr 06 07:18:30.408485 2018] [wsgi:error] [pid 31673] [client ip:59940]   File "/var/www/html/Datalake/Datalake/wsgi.py", line 12, in <module>
[Fri Apr 06 07:18:30.408493 2018] [wsgi:error] [pid 31673] [client ip:59940]     from django.core.wsgi import get_wsgi_application
[Fri Apr 06 07:18:30.408516 2018] [wsgi:error] [pid 31673] [client ip:59940] ModuleNotFoundError: No module named 'django'
 
and browser throwing 500 Internal Server Error.

Please help me out this. And let me know if i'm missing anything to share

**Comment by GrahamDumpleton** [comment]
Your mod_wsgi is most likely not compiled for the same version of Python that your Python virtual environment was created for. They MUST be the same. Verify what version of Python mod_wsgi was compiled for.

* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-installation-in-use

**Comment by GrahamDumpleton** [comment]
Do you by chance still have a system version of mod_wsgi package installed and enabled?

I really need to see the output from the test script in the section of that document I posted to confirm what is being used.

Also check permissions of directories/files under ``/home/tibil/first/venv`` especially in ``/home/tibil/first/venv/lib/python2.6/site-packages/`` to make sure they would be readable to any user.

**Comment by tanweer123** [comment]
Hi Graham,
sorry for late reply.
The output of those test WSGI scripts are 

sys.version = '3.6.3 (default, Jan  4 2018, 16:40:53) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]'
sys.prefix = '/'

and,

sys.path = ['/lib64/python36.zip', '/lib64/python3.6', '/lib64/python3.6/lib-dynload', '/lib64/python3.6/site-packages', '/lib/python3.6/site-packages']

And the permissions of the files under /home/tibil/first/venv/lib/python3.6/site-packages are 

drwxr-xr-x   3 root  root     96 Apr  9 09:50 certifi
drwxr-xr-x   2 root  root    150 Apr  9 09:50 certifi-2018.1.18.dist-info
drwxr-xr-x   4 root  root   4096 Apr  9 09:50 chardet
drwxr-xr-x   2 root  root    155 Apr  9 09:50 chardet-3.0.4.dist-info
drwxr-xr-x. 19 tibil apache 4096 Apr  9 03:46 django
drwxr-xr-x.  2 tibil apache  174 Apr  9 03:46 Django-2.0.2.dist-info
drwxr-xr-x   2 root  root    150 Apr  9 09:49 djangorestframework-3.8.2.dist-info
-rw-r--r--.  1 tibil apache  126 Apr  9 03:44 easy_install.py
drwxr-xr-x   3 root  root    174 Apr  9 09:50 idna
drwxr-xr-x   2 root  root    131 Apr  9 09:50 idna-2.6.dist-info
drwxr-xr-x. 11 tibil apache 4096 Apr  9 03:44 pip
drwxr-xr-x.  2 tibil apache  155 Apr  9 03:44 pip-9.0.1.dist-info
drwxr-xr-x.  5 tibil apache   73 Apr  9 03:44 pkg_resources
drwxr-xr-x.  2 tibil apache   41 Apr  9 03:44 __pycache__
drwxr-xr-x.  4 tibil apache  150 Apr  9 03:46 pytz
drwxr-xr-x.  2 tibil apache  147 Apr  9 03:46 pytz-2018.3.dist-info
drwxr-xr-x  10 root  root   4096 Apr  9 09:49 rest_framework
drwxr-xr-x   3 root  root     44 Apr  9 09:49 schedule
drwxr-xr-x   2 root  root    131 Apr  9 09:49 schedule-0.5.0.dist-info
drwxr-xr-x.  5 tibil apache 4096 Apr  9 03:44 setuptools
drwxr-xr-x.  2 tibil apache  199 Apr  9 03:44 setuptools-28.8.0.dist-info
drwxr-xr-x   6 root  root    272 Apr  9 09:50 urllib3
drwxr-xr-x   2 root  root    131 Apr  9 09:50 urllib3-1.22.dist-info

Is anything wrong in these file permissions?
Thanks

**Comment by GrahamDumpleton** [comment]
What do you get for:

```
ls -lasd /home/tibil
ls -lasd /home/tibil/first
ls -lasd /home/tibil/first/venv
```

If you are on a Red Hat type OS, your home directory is usually not going to be readable to others and so the Apache user can't see anything under it.

**Comment by tanweer123** [comment]
Yes, i'm using CentOS 7, but i've given apache group to my home directory and virtualenv. 
This is the output of command you mentioned above
4 drwx--x---. 7 tibil apache 4096 Apr 10 02:48 /home/tibil
0 drwxr-xr-x. 5 tibil apache 100 Apr 10 07:13 /home/tibil/venv

yesterday i recreated my venv, now no first directory is there. But error log is still same.
Thanks.

**Comment by GrahamDumpleton** [comment]
The permissions on your home directory likely aren't sufficient as you don't give read access, execute access may not be enough. You really shouldn't change your home directory to have group ``apache``. Put the virtual environment and any project code under your home directory under ``/var/www/project`` instead.

**Comment by tanweer123** [comment]
I placed my project inside home directory and now the home directory also having rwx permission to other group.
4 drwxrwxr-x. 6 tibil apache 4096 Apr 11 02:43 /home/tibil/
 
and contents of home directory looks like this
drwxr-xr-x  9 tibil apache      160 Apr  9 09:27 Datalake
drwxr-xr-x. 7 tibil tibil      4096 Apr  9 07:52 mod_wsgi-4.6.3
-rwxr-xr-x  1 tibil apache      405 Apr  9 10:00 script.wsgi
drwxr-xr-x. 5 tibil apache      100 Apr 10 07:13 venv

**Comment by GrahamDumpleton** [comment]
I said to put it all under ``/var/www/project`` instead, not under your home directory.

There is also a chance that Apache cannot read stuff under your home directory regardless of permissions due to SELinux restrictions. That is why putting it all under ``/var/www/project`` is better.

**Comment by tanweer123** [comment]
I placed virtual environment and project code under /var/www/myproject directory.
And SELinux is disabled too. But still getting same error.

**Comment by GrahamDumpleton** [comment]
Was this ever resolved?

**Comment by rbelew** [comment]
hello Graham,  thanks first for your exemplary support of mod_wsgi. i've found your doc, patient replies here, SO, GG, ...  and read many of them.  but i still have an issue just like the one listed here.

i'm installing on an AWS ubuntu 16.04 instance.  after following your hints here https://stackoverflow.com/a/44915354,  i've replaced the system mod_wsgi with the newer mod_wsgi.  `mod_wsgi-express module-config` produces `LoadModule wsgi_module "/home/rik/.local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so"`

i've added this to the config file included by apache. after an apache restart, I now get this line in its error log:

`AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.6.4 Python/3.5 configured -- resuming normal operations`

all versions see correct?

but then on first attempt to hit the server i get:

```
	mod_wsgi (pid=10266): Failed to exec Python script file '.../wsgi.py'

	Traceback (most recent call last):
	File ".../wsgi.py", line 17, in <module>
	from django.core.wsgi import get_wsgi_application
	ImportError: No module named 'django'
```
i put this `for f in sys.path: print(f)` just before the troublesome import in `wsgi.py` and it shows:

```
	.../.local/lib/python3.5/site-packages
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages
```
but when i check to see where django is install:

```
	% python3
	Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import django
	>>> django.__file__
	'.../.local/lib/python3.5/site-packages/django/__init__.py'
```
it seems mod_wsgi should be able to find it in my `site-packages`.  any ideas what the issue is?
thanks again.

**Comment by GrahamDumpleton** [comment]
Please don't post new questions on old issues. Create a new one. FWIW though, your code runs as the Apache user, not you, so it isn't going to look in your personal site-packages directory. Create a separate virtual environment and use it. https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html
