### ISSUE TITLE
Getting Apache to launch Flask application

### ISSUE THREAD

**Issue by user7766666** [GrahamDumpleton/mod_wsgi#295]
Hello Graham,

This thread is a continuation of https://github.com/GrahamDumpleton/mod_wsgi/issues/275 . I had to let the flask development rest for a short while, picking it up once again.

I have made the changes you requested, by changing ServerName to the following:

```
<VirtualHost *:80>
ServerName http://127.0.0.1.nip.io/flasktest
WSGIScriptAlias /flasktest /var/www/html/flasktest/flasktest.wsgi
WSGIPythonPath /usr/lib64/
WSGIDaemonProcess flasktest
ErrorLog /var/www/html/flasktest/error.log
<Directory /var/www/html/flasktest>
  WSGIProcessGroup flasktest
  WSGIApplicationGroup %{GLOBAL} 
  Order deny,allow
        Allow from all
</Directory>
</VirtualHost>
WSGIRestrictEmbedded On

```

When accessing http://127.0.0.0.1/flasktest, the webbrowser says that a connection can't be established. I don't get any error messages from either Apache or mod_wsgi.

Running the Flask app as 'flask run --host=0.0.0.0 --port=80' works just fine.

**Comment by GrahamDumpleton** [comment]
``ServerName`` should be:

```
ServerName 127.0.0.1.nip.io
```

Also, don't use:

```
http://127.0.0.0.1/flasktest
```

in your browser, use:

```
http://127.0.0.1.nip.io/flasktest
```

The same host name as ``ServerName`` uses.

You shouldn't need:

```
WSGIPythonPath /usr/lib64/
```

**Comment by user7766666** [comment]
Updated changes as you mentioned

´´´
<VirtualHost *:80>
ServerName 127.0.0.1.nip.io
WSGIScriptAlias /flasktest /var/www/html/flasktest/flasktest.wsgi
WSGIDaemonProcess flasktest
ErrorLog /var/www/html/flasktest/error.log
<Directory /var/www/html/flasktest>
  WSGIProcessGroup flasktest
  WSGIApplicationGroup %{GLOBAL} 
  Order deny,allow
        Allow from all
</Directory>
</VirtualHost>
WSGIRestrictEmbedded On

´´´
Still getting the same behaviour. I think I need to explain a little bit further the Apache server I'm using for my test code. It is an internal server we are using where I'm uploading my code, it is not the local machine where I write my code. So I can't use http://127.0.0.1.nip.io/flasktest, rather I'm using http://our.internal.network/flasktest.

An additional thing I think could be giving me problems is that the webserver automatically changes all my http:// requests to https://

Looking at a similar webserver in our network and the content of its .conf file shows AuthName, AuthBasicProvider, AuthType, AuthDAPURL options. I'm guessing this could be a reason for my problem? The webserver expects me to use https?

But I can't find anything in /etc/httpd/conf/httpd.conf to prove that.

**Comment by user7766666** [comment]
I just made a fast test to use my code in /var/www/cgi-bin (without using Flask) and there was no problem using either http or https. So that can't be the problem.

This is getting really frustrating, is there an option to enable more logging for Apache/Flask applications? Even though I specify ErrorLog /var/www/html/flasktest/error.log in flasktest.conf, I just get nothing. I get the impression that Apache is not executing my flasktest.py code at all. I would really like to see what Apache and mod_wsgi are trying to do.

**Comment by GrahamDumpleton** [comment]
You can increase Apache logging using:

```
LogLevel debug
```

Make sure you check main Apache error log and not just ``VirtualHost`` log.

You can enable extra mod_wsgi debug logging using:

```
WSGIVerboseDebugging On
```

You can capture request and response using something like what is explained in:

* http://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#tracking-request-and-response

BTW, you can still use ``nip.io``. Just use the internal network IP address that host is none by on network instead of ``127.0.0.1``. It will take any IP address and resolves to that IP. For example:

```
192.168.178.1.nip.io
```

and:

```
http://192.168.178.1.nip.io/flasktest
```

**Comment by user7766666** [comment]
Made the following changes after a lot of reading through different Flask/Apache tutorials. I moved my flasktest.conf file to /etc/httpd/conf.d/ and it seems like Apache recognizes my requests to http://X.X.X.X.nip.io/flasktest

I get the following errors in /var/log/httpd/error_log

´´´
[Wed Apr 25 16:44:17 2018] [info] mod_ssl/2.2.15 compiled against Server: Apache/2.2.15, Library: OpenSSL/1.0.1e-fips
[Wed Apr 25 16:44:17 2018] [debug] src/server/mod_wsgi.c(10308): mod_wsgi (pid=1808): Reset default user for daemon process group 'flasktest' to uid=48.
[Wed Apr 25 16:44:17 2018] [debug] src/server/mod_wsgi.c(10317): mod_wsgi (pid=1808): Reset default group for daemon process group 'flasktest' to gid=48.
[Wed Apr 25 16:44:17 2018] [debug] src/server/mod_wsgi.c(8298): mod_wsgi (pid=1808): Socket for 'flasktest' is '/etc/httpd/logs/wsgi.1808.0.1.sock'.
[Wed Apr 25 16:44:17 2018] [debug] src/server/mod_wsgi.c(8356): mod_wsgi (pid=1808): Listen backlog for socket '/etc/httpd/logs/wsgi.1808.0.1.sock' is '100'.
[Wed Apr 25 16:44:17 2018] [info] mod_wsgi (pid=1810): Starting process 'flasktest' with uid=48, gid=48 and threads=15.
[Wed Apr 25 16:44:17 2018] [info] mod_wsgi (pid=1810): Initializing Python.
´´´

From /var/www/html/flasktest/error.log

´´´
[Wed Apr 25 16:44:17 2018] [debug] src/server/mod_wsgi.c(10171): mod_wsgi (pid=1810): Process 'flasktest' logging to '150.132.206.198.nip.io'.
[Wed Apr 25 16:44:26 2018] [error] [client 150.132.87.94] (13)Permission denied: mod_wsgi (pid=1811): Unable to connect to WSGI daemon process 'flasktest' on '/etc/httpd/logs/wsgi.1808.0.1.sock' as user with uid=48.
[Wed Apr 25 16:44:37 2018] [error] [client 150.132.87.94] (13)Permission denied: mod_wsgi (pid=1812): Unable to connect to WSGI daemon process 'flasktest' on '/etc/httpd/logs/wsgi.1808.0.1.sock' as user with uid=48.
[Wed Apr 25 16:44:57 2018] [error] [client 150.132.87.94] (13)Permission denied: mod_wsgi (pid=1816): Unable to connect to WSGI daemon process 'flasktest' on '/etc/httpd/logs/wsgi.1808.0.1.sock' as user with uid
´´´

flasktest.py seems to be running with uid=48. But Apache can't seem to run as it as uid=48. It seems like this problem is related to access rights or some other privilege setting?

**Comment by GrahamDumpleton** [comment]
It can be one of two things. The most likely is that operating system restricts permissions on ``/etc/httpd/logs`` so only accessible to ``root``. This issue is described in:

* http://modwsgi.readthedocs.io/en/develop/user-guides/configuration-issues.html#location-of-unix-sockets

You will need to override ``WSGISocketPrefix`` directive to specify directory which Apache can use for the socket.

**Comment by user7766666** [comment]
I followed the instructions from the link and the error messages are gone.

When accessing http://x.x.x.x.nip.io/flasktest

I get the following in the logs:

wsgi log:

```
[Thu Apr 26 11:49:54 2018] [debug] src/server/mod_wsgi.c(10171): mod_wsgi (pid=132726): Process 'flasktest' logging to '150.132.206.198.nip.io'.
```
Apache log:

```
 Apr 26 11:49:54 2018] [info] mod_wsgi (pid=132726): Initializing Python.
[Thu Apr 26 11:49:57 2018] [debug] src/server/mod_wsgi.c(11709): mod_wsgi (pid=126733): Request server was '150.132.206.198.nip.io|0'
```

Apache seems to handle the request. But I'm surprised that wsgi only reports logging. The webbrowser responds with "Not found The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

I find it strange that Apache  reports the request as '150.132.206.198.nip.io|0. What does the 0 at the end mean? Can't get any good explanations from Google.

**Comment by GrahamDumpleton** [comment]
That request details you quote is an internal thing related to mod_wsgi, it is not the URL path. If you want to the URL path, look at the Apache access log, not error log.

The problem you are going to be having at this point is going to be how you have set up routes in your Flask application. Can you show the routes definition/function prototype for your request handlers? You should not be setting up the route in your code as ``/flasktest``. You should be setting it up as root of the site.

**Comment by user7766666** [comment]
I actually had 
@app.route('/flasktest')

which has now been changed to only '/'

current code of flasktest.py

´´´´

from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
      return 'Hello, World!'

if __name__ == "__main__":
    app.run(debug=True)

´´´´

Still having 

Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

/var/log/httpd/access_log

150.132.87.94 - - [09/May/2018:11:05:31 +0200] "GET /flasktest/ HTTP/1.1" 404 233 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"

**Comment by GrahamDumpleton** [comment]
Thanks for letting me know you worked it out, I will close this issue then.
