### ISSUE TITLE
segmentation fault error while communicating with C layer..

### ISSUE THREAD

**Issue by maijaz01** [GrahamDumpleton/mod_wsgi#296]
I have Django Python project, with this I have build a simple rest API, which talk to C layer which read hardware details and gives to me the H/W details.
Now issue is with local host its working, but the same thing is trowing error while running with Apache + mod_wsgi.

Error : AH00052 -child pid exit signal segment ion fault 
is this some permission issue which i have not given to mod_wsgi
Can you please help me on this

**Comment by GrahamDumpleton** [comment]
Show you Apache configuration for mod_wsgi.

If you are not using mod_wsgi daemon mode, make sure you are using it. Also ensure you are using:

```
WSGIApplicationGroup %{GLOBAL}
```

as works around issues with many C extension modules for Python which haven't been written in a way to run in Python sub interpreters, and which can as a result crash.

* http://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api
