### ISSUE TITLE
Windows Build: mod_wsgi-4.6.4-cp27-cp27m-win_amd64.whl vs mod_wsgi-4.6.4-cp36-cp36m-win_amd64.whl

### ISSUE THREAD

**Issue by ascholtz** [GrahamDumpleton/mod_wsgi#297]
Hello,

When I build 4.6.4 on Windows on 3.6-64 I get a nicely named "mod_wsgi.cp36-win_amd64.pyd"
and output from mod_wsgi-express.exe module-location or module-config will look like:
`c:\pythonprojects\36\mod_wsgi\env\lib\site-packages\mod_wsgi\server\mod_wsgi.cp36-win_amd64.pyd`

When I build 4.6.4 on Windows but on 2.7-64 I get just a "mod_wsgi.pyd"
and output from mod_wsgi-express.exe module-location or module-config will look like:
`c:\pythonprojects\27\mod_wsgi\env\lib\site-packages\mod_wsgi\server\mod_wsgiNone`

Seems like on 2,7 the filename versioning gets lost due to a trailing None..

**Comment by GrahamDumpleton** [comment]
Yes, I am aware of the issue on Python 2.7. I have tried half a dozen times or more to engage people who have seen it to do various checks to help me work out what needs to change in the code, but have had no success in getting any help, so haven't given up.

You can manually change ``None`` to ``.pyd`` in the configuration.

Even then, getting older Python 2.7 working seems to be hit and miss. It isn't possible to find a recent Apache which has been compiled with the correct compiler that Python 2.7 needs. So things don't work. That or people aren't installing the correct compiler to build mod_wsgi with, also must be the same as Python 2.7 requires. Or people are mixing 32 bit and 64 bit compilers and programs.

All up, you are much better just using Python 3.6 as well as 64 bit versions of everything as that works well.

**Comment by GrahamDumpleton** [comment]
Closing. Until someone steps up and helps me sort out the issue with extension showing as ``None`` when using Python 2.7 on Windows, but much can do. Issue is here as record at least so people know about it.
