### ISSUE TITLE
runmodwsgi --setup-only error

### ISSUE THREAD

**Issue by umaparvat** [GrahamDumpleton/mod_wsgi#298]
HI ,

i'm using mod_wsgi in anaconda python 3.6.1. Created a virtualenv. 

The application is grapite master branch code. 

when i try to run the below command, it throws error as below
`python manage.py collectstatic --no-input --settings=graphite.settings&& python manage.py runmodwsgi --settings=graphite.settings --setup-only --port=5000 --user watd02 --group watd02 --locale C.UTF-8 --log-to-terminal --log-level "debug" --access-log`

The error is below

`0 static files copied to '/opt/graphite/static', 409 unmodified.
Successfully ran command.
None
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/graphite/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/graphite/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/graphite/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/graphite/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/graphite/venv/lib/python3.6/site-packages/mod_wsgi/server/management/commands/runmodwsgi.py", line 72, in handle
    fields = wsgi_application.split('.')
AttributeError: 'NoneType' object has no attribute 'split'
`

vituralenvironment list of packages
` pip freeze
attrs==17.4.0
Automat==0.6.0
cachetools==2.0.1
cairocffi==0.8.0
carbon==1.1.3
ceres==1.1.0
cffi==1.11.5
constantly==15.1.0
Django==1.11.12
django-tagging==0.4.6
fadvise==4.0.0
graphite-web==1.2.0
gunicorn==19.7.1
hyperlink==18.0.0
idna==2.6
incremental==17.5.0
mod-wsgi==4.6.4
pycparser==2.18
pyparsing==2.2.0
python-memcached==1.59
pytz==2018.4
scandir==1.7
six==1.11.0
Twisted==17.9.0
txAMQP==0.8.0
urllib3==1.22
whisper==1.1.3
whitenoise==3.3.1
zope.interface==4.4.3
`

**Comment by GrahamDumpleton** [comment]
Two possibilities.

Your Django settings file isn't setting:

```
WSGI_APPLICATION
```

variable.

This could be because you originally created your Django project in a really old version and have progressivlye migrated it to newer Django versions where ``WSGI_APPLICATION`` setting was introduced.

Or, you have restructured how your Django settings are organised from a single file, or a multi file setup, with dev/prod options, and somehow lost that setting in the process, or have it at the wrong level in the module hierarchy.

What do you get if you run:

```
python manage.py diffsettings
```

Does ``WSGI_APPLICATION`` appear?

**Comment by umaparvat** [comment]
WSGI_APPLICATION didn't appear. 

output of `python manage.py diffsettings`

`WEBAPP_DIR = '/opt/graphite/webapp'  ###
WEBAPP_VERSION = '1.1.3'  ###
WEB_DIR = '/opt/graphite/webapp/graphite'  ###
WHISPER_DIR = '/opt/graphite/storage/whisper'  ###
WHITELIST_FILE = '/opt/graphite/storage/lists/whitelist'  ###
`

Earlier versions of graphite  doesn't have manage.py . the  [master branch](https://github.com/graphite-project/graphite-web) was cloned to the /opt/graphite/ .   under webapp/graphite/app_settings.py file , i've added `mod_wsgi.servers` in the installed_apps column.

`INSTALLED_APPS = (
  'graphite.account',
  'graphite.browser',
  'graphite.composer',
  'graphite.dashboard',
  'graphite.events',
  'graphite.functions',
  'graphite.metrics',
  'graphite.render',
  'graphite.tags',
  'graphite.url_shortener',
  'graphite.whitelist',
  'django.contrib.auth',
  'django.contrib.sessions',
  'django.contrib.admin',
  'django.contrib.contenttypes',
  'django.contrib.staticfiles',
  'tagging',
  'mod_wsgi.server',
)
`

there is a graphite.wsgi file under /opt/graphite/conf . do i  have to add that as WSGI_APPLICATION=/opt/graphite/conf/graphite.wsgi  in the app_settings.py file ?

the content of graphite.wsgi

`import sys
sys.path.append('/opt/graphite/webapp')
sys.path.append('/opt/graphite/lib')
from graphite.wsgi import application
`

Tried it through apache graphite-vhost.conf file too.

the apache user is watd02, group is watd02 . 

the virtual environment is /opt/graphite/venv .
`ll venv/
total 4
drwxr-xr-x 3 watd02 root 4096 Apr 11 19:50 bin
drwxr-xr-x 2 watd02 root   23 Apr 10 17:06 include
drwxr-xr-x 3 watd02 root   22 Apr 10 17:06 lib
`
i've added the WSGIPYTHONPATH /opt/graphite/venv:/opt/graphite/webapp:/opt/graphite/lib

It gives error as 
`No such file or directory: mod_wsgi (pid=31591): Unable to stat Python home /opt/graphite/venv:/opt/graphite/webapp:/opt/graphite/lib. Python interpreter may not be able to be initialized correctly. Verify the supplied path and access permissions for whole of the path.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
`

the content of graphite-vhost.conf file

`WSGISocketPrefix /opt/graphite/storage/run/wsgi
<VirtualHost *:8443>
        ServerName xxx.yyy.zzz.www
        DocumentRoot "/opt/graphite/webapp"
        ErrorLog /opt/graphite/storage/log/webapp/error.log
        CustomLog /opt/graphite/storage/log/webapp/access.log common
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Methods "GET, OPTIONS"
        Header set Access-Control-Allow-Headers "origin, authorization, accept"

        # I've found that an equal number of processes & threads tends
        # to show the best performance for Graphite (ymmv).
        WSGIDaemonProcess graphe python-path='/opt/graphite/webapp:/opt/graphite/lib:/opt/graphite/venv/lib/python3.6/site-packages' processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120
        WSGIProcessGroup graphe
        WSGIApplicationGroup %{GLOBAL}
        WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphe application-group=%{GLOBAL}

        # XXX You will need to create this file! There is a graphite.wsgi.example
        # file in this directory that you can safely use, just copy it to graphite.wgsi
        WSGIScriptAlias / /opt/graphite/conf/graphite.wsgi


        #Â| XXX To serve static files, either:
        # * Install the whitenoise Python package (pip install whitenoise)
        # * Collect static files in a directory by running:
        #     django-admin.py collectstatic --noinput --settings=graphite.settings
        #   And set an alias to serve static files with Apache:
        Alias /static/ /opt/graphite/static/
        Alias /media/ "/opt/graphite/venv/lib/python3.6/site-packages/django/contrib/admin/static/"
        RedirectMatch ^/admin(.*)admin/([^/]+)/([^/]+)$ /media/$2/$3
        <Location "/media/">
                SetHandler None
                Require all granted
        </Location>

        #Alias /static/ "/usr/local/lib/python2.7/site-packages/django/contrib/admin/static/"
        <Location "/static/">
                SetHandler None
                Require all granted
        </Location>

        ########################
        # URL-prefixed install #
        ########################
        # If using URL_PREFIX in local_settings for URL-prefixed install (that is not located at "/"))
        # your WSGIScriptAlias line should look like the following (e.g. URL_PREFX="/graphite"

         #WSGIScriptAlias /graphite /opt/graphite/conf/graphite.wsgi/graphite
         Alias /content /opt/graphite/webapp/content
          <Location "/content/">
                SetHandler None
                Require all granted
         </Location>


        # XXX In order for the django admin site media to work you
        # must change @DJANGO_ROOT@ to be the path to your django
        # installation, which is probably something like:
        # /usr/lib/python2.6/site-packages/django
        #Alias /media/ "@DJANGO_ROOT@/contrib/admin/media/"
        #<Location "/media">
        #       SetHandler None
        #</Location>
        # The graphite.wsgi file has to be accessible by apache. It won't
        # be visible to clients because of the DocumentRoot though.
        <Directory /opt/graphite/conf/>
                Options All
                AllowOverride All
                Require all granted
        </Directory>

</VirtualHost>

`

The content of httpd.conf
`
Listen 8443
Include conf.d/graphite-vhost.conf
`

Apache web page is also not loading

**Comment by GrahamDumpleton** [comment]
What is in ``graphite.wsgi``.

The ``WSGI_APPLICATION`` variable has to be a module path, not a file system path.

For a Django project it is usually something like ``myproject.wsgi``. This corresponds to the ``myproject/wsgi.py`` file created when a new Django project is created.

**Comment by GrahamDumpleton** [comment]
Ahh, you did include it. Missed it because of bad formatting.

Try setting:

```
WSGI_APPLICATION = 'graphite.wsgi'
```

**Comment by GrahamDumpleton** [comment]
You may still have issues because Graphite possibly breaks Django conventions for where things are. Thus may fail because:

```
sys.path.append('/opt/graphite/webapp')
sys.path.append('/opt/graphite/lib')
```

aren't being set.

These would need to be added using ``--python-path`` option.

**Comment by umaparvat** [comment]
it's fixed now . I've added WSGI_APPLICATION = graphite.wsgi in settings.py file 
and commented sys.path lines in graphite.wsgi
`
import sys 
#sys.path.append('/opt/graphite/webapp') 
#sys.path.append('/opt/graphite/lib') 
from graphite.wsgi import application`

The apache graphite-vhost.conf  works well .
`
WSGISocketPrefix /opt/graphite/storage/run/wsgi
<VirtualHost  *:8443>
ServerName xxx.yyy.zzz.www
DocumentRoot "/opt/graphite/webapp"
ErrorLog /opt/graphite/storage/log/webapp/error.log
CustomLog /opt/graphite/storage/log/webapp/access.log common
Header set Access-Control-Allow-Origin ""
Header set Access-Control-Allow-Methods "GET, OPTIONS"
Header set Access-Control-Allow-Headers "origin, authorization, accept"
# I've found that an equal number of processes & threads tends
# t show the best performance for Graphite (ymmv).
WSGIDaemonProcess graphe python-path='/opt/graphite/webapp:/opt/graphite/lib:/opt/graphite/venv/lib/python3.6/site-packages' processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120
    WSGIProcessGroup graphe
    WSGIApplicationGroup %{GLOBAL}
    WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphe application-group=%{GLOBAL}

    # XXX You will need to create this file! There is a graphite.wsgi.example
    # file in this directory that you can safely use, just copy it to graphite.wgsi
    WSGIScriptAlias / /opt/graphite/conf/graphite.wsgi


    #Â| XXX To serve static files, either:
    # * Install the whitenoise Python package (pip install whitenoise)
    # * Collect static files in a directory by running:
    #     django-admin.py collectstatic --noinput --settings=graphite.settings
    #   And set an alias to serve static files with Apache:
    Alias /static/ /opt/graphite/static/
    Alias /media/ "/opt/graphite/venv/lib/python3.6/site-packages/django/contrib/admin/static/"
    RedirectMatch ^/admin(.*)admin/([^/]+)/([^/]+)$ /media/$2/$3
    <Location "/media/">
            SetHandler None
            Require all granted
    </Location>

    #Alias /static/ "/usr/local/lib/python2.7/site-packages/django/contrib/admin/static/"
    <Location "/static/">
            SetHandler None
            Require all granted
    </Location>

    ########################
    # URL-prefixed install #
    ########################
    # If using URL_PREFIX in local_settings for URL-prefixed install (that is not located at "/"))
    # your WSGIScriptAlias line should look like the following (e.g. URL_PREFX="/graphite"

     #WSGIScriptAlias /graphite /opt/graphite/conf/graphite.wsgi/graphite
     Alias /content /opt/graphite/webapp/content
      <Location "/content/">
            SetHandler None
            Require all granted
     </Location>


    # XXX In order for the django admin site media to work you
    # must change @DJANGO_ROOT@ to be the path to your django
    # installation, which is probably something like:
    # /usr/lib/python2.6/site-packages/django
    #Alias /media/ "@DJANGO_ROOT@/contrib/admin/media/"
    #<Location "/media">
    #       SetHandler None
    #</Location>
    # The graphite.wsgi file has to be accessible by apache. It won't
    # be visible to clients because of the DocumentRoot though.
    <Directory /opt/graphite/conf/>
            Options All
            AllowOverride All
            Require all granted
    </Directory>
</VirtualHost>
`

**Comment by GrahamDumpleton** [comment]
I am a bit confused at this point. That ``WSGI_APPLICATION`` variable would only be required if using ``mod_wsgi-express``. Since you are using manual configuration of Apache, you shouldn't need it.

What the issue really was that you added ``'mod_wsgi.server'`` to ``INSTALLED_APPS`` when you didn't need to.

**Comment by GrahamDumpleton** [comment]
If you only use ``pip install mod_wsgi`` to compile/install the ``mod_wsgi.so`` file, and are not actually running ``python manage.py runmodwsgi`` for Django, you do not need to add ``mod_wsgi.server`` to ``INSTALLED_APPS`` is what I am saying. You appear to be manually configuring system Apache, so thus can't see that you are using ``python manage.py runmodwsgi`` which required it.
