### ISSUE TITLE
Looking for a work around for deploying flask app on apache 

### ISSUE THREAD

**Issue by namanb5** [GrahamDumpleton/mod_wsgi#299]
Hi
I am trying to deploy a simple flask app on apache using mod_wsgi in windows using python 2.7 from last 5-6 days but unable to do so.
After all the research and digging through the past issues on your page, I came to a conclusion that if I want to use python 2.7 then I have to go for apache VC 9 version which has been deprecated on the official website. I can't use any other higher version of python due to project requirements.

Please let me know if there is any work around if I want to deploy a flask app on my windows machine using apache. Or if there is something else I can do as this project is really important to me.

**Comment by GrahamDumpleton** [comment]
It is a grey area.

Technically for older MS C compiler runtime versions you shouldn't mix binaries from different runtime versions.

That said, some people have managed to get something working with VC14 Apache and VC9 Python/mod_wsgi. The parts of the C application binary interface (ABI) used between Apache and mod_wsgi is very minimal and doesn't involve passing C library data structures which would cause ABI version problems.

So a lot of the problems simply come done to ensuring you have the correct versions of the MS C compiler.

I would start out with:

* 64 bit Python
* 64 bit VC9 MS C compiler. See https://wiki.python.org/moin/WindowsCompilers
* 64 bit VC14 Apache

Use the ``pip install mod_wsgi`` method to build the ``mod_wsgi`` module for Apache.

Run ``mod_wsgi-express module-config`` to generate the config to load into Apache. The generated value could be wrong and may need to fix up the extension used on the ``mod_wsgi`` module filename.

Don't enable mod_ssl in Apache when trying to get it working initially. Deal with that later if really need HTTPS support.

So is a case of trying. The most important is ensuring that you got the VC9 compiler and is 64 bit as for all other components. Problem is there is 4 different VC9 compiler packages from Microsoft and I don't know if a particular has more success than another, so you may have to experiment with working out which is the one that might work.

**Comment by namanb5** [comment]
Thank you Graham for such a prompt response.
I will try it out. You can close this issue. :)

**Comment by GrahamDumpleton** [comment]
Okay, closing for now. Let me know how it works out.
