### ISSUE TITLE
Issue when conda environment specified by path, not name

### ISSUE THREAD

**Issue by agjino** [GrahamDumpleton/mod_wsgi#300]
I have a conda environment under
`/condahttpenv/luna-django`

I didn't place it under /home since everything is set up under the root account. When I source the environment and install mod_wsgi and do the necessary setup under Apache 2.4, Apache fails to start.

`service apache2 start`

shows the following generic error:

> Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.

journalctl doesn't have any useful info other than the wsgi module failed to load (the specific version)

However, running:

`strace -Ff apachectl start`

> [pid 10719] open("/root/anaconda3/envs/luna-django/lib/tls/x86_64/libpython3.6m.so.1.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

It's searching in the wrong directory! It's assuming the env is on home.

**Comment by GrahamDumpleton** [comment]
Does the file:

```
/root/anaconda3/envs/luna-django/lib/tls/x86_64/libpython3.6m.so.1.0
```

actually exist?

The problem with sticking stuff under ``/root`` is that the user that Apache is running as when it tries to load modules, can't see in ``/root`` as only the ``root`` user can see in that directory.

It is usually a very bad idea to install packages you need access to under ``/root``.

**Comment by agjino** [comment]
No, it does not Because it exists on:

`/condahhtpenv/luna-django/lib/tls/x86_64/libpython3.6m.so.1.0`

For the exact reason you described I moved the env outside of home. But from the logs looks like mod_wsgi expects to find it under home. This is an environment created with --path, not --name.

Now that I think of it, it may actually be a conda issue. I just don't know enough about Python yet to understand how these environments are resolved.

For others hacing this issue, I solved this by appending `/condahttpenv/luna-django/lib` and another failing directory to /etc/ld.so.conf and reloading by deleting ld.so.cache and running `ldconfig`

**Comment by GrahamDumpleton** [comment]
When you say moved, did you literally move it, or did you re-create it. Virtual environments are not usually relocatable.

Anyway, it can be a problem with Anconda Python being able to find its shared library. The easiest solution is to add just before the ``LoadModule`` line for mod_wsgi:

```
LoadFile /condahhtpenv/luna-django/lib/tls/x86_64/libpython3.6m.so.1.0
```

where the path is that to the shared library.

If you had used ``pip install mod_wsgi`` to install mod_wsgi, and then run ``mod_wsgi-express module-config`` to get the Apache configuration you use, it should have generated an appropriate ``LoadFile`` directive to be used.

Did you use this method to install it, or did you build manually from source code using configure/make/make install?

**Comment by agjino** [comment]
Your method with LoadFile works! Thank you! I don't need to pollute the lib paths now.

As for my config, I **created** the environment with _--prefix_, not _--name__. I did not copy or move anything. I did use pip for the module, but I don't think `module-config` generated a LoadFile, only a LoadModule. I tried again now and it only generated the LoadModule directive.
