### ISSUE TITLE
apachectl bash errors

### ISSUE THREAD

**Issue by fitzg2** [GrahamDumpleton/mod_wsgi#301]
/var/tmp/project/apachectl: line 43: id: command not found
/var/tmp/project/apachectl: line 43: [: too many arguments

Line 43:
```
if [ `id -u` = "0" -a ${MOD_WSGI_USER} = "root" ]; then
    cat << EOF

WARNING: When running as the 'root' user, it is required that the options
'--user' and '--group' be specified to mod_wsgi-express. These should
define a non 'root' user and group under which the Apache child worker
processes and mod_wsgi daemon processes should be run. Failure to specify
these options will result in Apache and/or the mod_wsgi daemon processes
failing to start. See the mod_wsgi-express documentation for further
information on this restriction.

EOF

fi
```

**Comment by GrahamDumpleton** [comment]
If the ``id`` command is missing, your ``PATH`` must be broken. The ``id`` command would be in ``/usr/bin`` or ``/bin`` and both those directories should be in ``PATH`` or many things will not work.

**Comment by fitzg2** [comment]
Yep. It's inside a virtualenv so that binary isn't there. Feel free to close.

**Comment by GrahamDumpleton** [comment]
That a virtualenv is used is nothing to do with it. The ``id`` program is a program that should be on the operating system. You must have somehow overwritten the default ``PATH``. Anyway, will close as this shouldn't be an issue with mod_wsgi, but your user environment.

**Comment by fitzg2** [comment]
It kinda has something to do with it because my `PATH` IS the virtualenv bin folder so..

**Comment by GrahamDumpleton** [comment]
``PATH`` should not be a single directory. It should be a list of directories.

If you create a brand new shell and go:

```
echo $PATH
```

you should see that it is a list of directories separate by ':'.

If you need to add the virtual environment ``bin`` directory, you would use:

```
PATH=$PATH:/some/path/venv/bin
```

Note how it extends the ``PATH``. You should NOT use:

```
PATH=/some/path/venv/bin
```

Better still, you shouldn't even be adding the ``bin`` directory to ``PATH`` yourself. Usually you would run:

```
. /some/path/venv/bin/activate
```

This adjust your user environment so you are then using the virtual environment, including updating your ``PATH``.

How are you setting ``PATH``?

**Comment by fitzg2** [comment]
It was a ''shotgun'' approach to make things work a long time ago with supervisor

```
environment = HOME="/var/www/project/env/bin"
environment = PATH="/var/www/project/env/bin"
```

And it's working so far. You are right though.
