### ISSUE TITLE
issue while installing mod_wsgi in windows 10

### ISSUE THREAD

**Issue by maijaz01** [GrahamDumpleton/mod_wsgi#303]
Hi Graham, 
I am trying to install mod_wsgi4.5.20 in my windows 10 system its throwing error .. 

 building 'mod_wsgi.server.mod_wsgi' extension
  error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Windows Kits\\10\\lib'

  ----------------------------------------
  Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
  Running setup.py install for mod-wsgi ... error
    Complete output from command c:\users\administrator\documents\poc_test\omclap\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-req-build-66s4pka1\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-6r6jtvn_\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\administrator\documents\poc_test\omclap\include\site\python3.5\mod-wsgi:
    c:\users\administrator\appdata\local\programs\python\python35\Lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\mod_wsgi
    copying src\__init__.py -> build\lib.win-amd64-3.5\mod_wsgi
    creating build\lib.win-amd64-3.5\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win-amd64-3.5\mod_wsgi\server
    copying src\server\environ.py -> build\lib.win-amd64-3.5\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win-amd64-3.5\mod_wsgi\server
    creating build\lib.win-amd64-3.5\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win-amd64-3.5\mod_wsgi\server\management
    creating build\lib.win-amd64-3.5\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.5\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.5\mod_wsgi\server\management\commands
    creating build\lib.win-amd64-3.5\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.5\mod_wsgi\docs
    creating build\lib.win-amd64-3.5\mod_wsgi\images
    copying images\__init__.py -> build\lib.win-amd64-3.5\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.5\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Windows Kits\\10\\lib'

    ----------------------------------------
Command "c:\users\administrator\documents\poc_test\omclap\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-req-build-66s4pka1\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-6r6jtvn_\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\administrator\documents\poc_test\omclap\include\site\python3.5\mod-wsgi" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-66s4pka1\

is it dependent on any GCC or visual studio...
Please let me know ..

**Comment by maijaz01** [comment]
i am installing in virtualenv which is pointing to python3.5..
command using is pip install mod_wsgi==4.5.20

**Comment by GrahamDumpleton** [comment]
You need to use VisualStudio compiler for the specific Python version you are using. See:

* https://wiki.python.org/moin/WindowsCompilers

**Comment by GrahamDumpleton** [comment]
Also, don't use 4.5.20. You can use latest version. You don't need to use older version.

**Comment by maijaz01** [comment]
You mean i need to install visual studio 2015 or you mean i need to install visual studio build tool.

**Comment by GrahamDumpleton** [comment]
It is your choice. If you don't need full Visual Studio, install the build tools version.

**Comment by maijaz01** [comment]
Thanks It worked for windows 10 we need build tool i have downloaded VS 2015  Build..
Thanks buddy
