### ISSUE TITLE
I need precompiled binary for windows 10

### ISSUE THREAD

**Issue by maijaz01** [GrahamDumpleton/mod_wsgi#304]
Hi,

I need pre-compiled binary for windows while installing the mod_wsgi its throwing error.
i looked into you one of blog (https://github.com/GrahamDumpleton/mod_wsgi-docs/blob/master/download-the-software.rst) it says need pre compiled binary but there are links for only python 2.x,
i am using python 3.5 can you please help me on this.
I am using python 3.5 and apache 2,4

**Comment by GrahamDumpleton** [comment]
I don't provide precompiled binaries because there are too many variations. The safest thing to do is to compile it yourself. If you have the correct MS C compiler installed, and Apache in location expected, you can use ``pip install mod_wsgi`` to build it and then run ``mod_wsgi-express module-config`` to generate the config you need to add to Apache to load it.

Few quick tips. Use all 64 bit binaries. Use Apache from ApacheLounge. Ensure you have the correct MS C compiler for the Python version you want to use:

* https://wiki.python.org/moin/WindowsCompilers

If you think you have all the right bits, explain what errors you are getting when installing it.

**Comment by GrahamDumpleton** [comment]
One more thing. That docs link you are using isn't the correct one. That repo actually needs to be deleted.

See:

* https://pypi.org/project/mod_wsgi/

**Comment by maijaz01** [comment]
but for me while installing only by(pip install mod_wsgi), its throwing error saying that " Microsoft Visual C++ 14.0 is required" it get resolved by installing the VC2015 and build tools but it seems its around 6GB its too big. now i don't understand what dependency its having i just want to install only those package.

**Comment by GrahamDumpleton** [comment]
You can try binaries at:

* https://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

but they have nothing to do with me.

**Comment by maijaz01** [comment]
this is Unofficial Windows Binaries is it  for LTS

**Comment by maijaz01** [comment]
I don't understand how it get installed with those binary it did not asked for any VC15 build tool.
however i  downloaded you repo from git and run the setup.py file its saying same thing.
even a you says in one blog if its .whl just rename and make .zip and make so but before that i was trying to see what exactly this .zip is having after extracting i don;t find any such thing.

**Comment by GrahamDumpleton** [comment]
The only people who offer any support for mod_wsgi is Red Hat who provide it as a supported package as part of Red Hat Enterprise Linux. They don't provide a recent version though. There is no supported version of mod_wsgi for Windows, nor Linux distributions such as Debian and Ubuntu. They may package it for those Linux distributions, but they don't support it. Not sure why you are expecting to get an LTS version. If you want a supported version you would need to pay someone for that support.

As to install the ``.whl`` file. If you have an up to date version of ``pip``, you should be able to download it and do:

```
pip install mod_wsgi‑4.6.4+ap24vc14‑cp35‑cp35m‑win_amd64.whl
```

You shouldn't need to rename it.

I don't know if they use my way of compiling mod_wsgi, they didn't use to. If they now do, you should then be able to run ``mod_wsgi-express module-config`` to get the configuration to include in Apache. If they don't, then you are going to have to find where the ``mod_wsgi.so`` is in what was installed and copy that to your Apache module directory and then configure Apache to load it. I have no idea how there package are built.

**Comment by maijaz01** [comment]
Ok, now help me to understand on which package mod_wsgi is dependent when we install mod_wsgi in windows, while it throw error for installing the VC2015, and its 1.4GB around after this installation is works so may I know what exact package it on dependent so i can install directly. Because, this "mod_wsgi‑4.6.4+ap24vc14‑cp35‑cp35m‑win_amd64.whl" file is just 2.9MB. and it has installed. so my understanding is there is something this .whl is having which is directly installing mod_wsgi.

**Comment by GrahamDumpleton** [comment]
I don't really understand what you are asking. The compiler tool chain is huge because it provides lots of lots of stuff for the compiler. The compiled mod_wsgi is small but there isn't much code that goes in to it. The compiled module will depend on some DLLs but it is likely they are already installed on your system.

**Comment by maijaz01** [comment]
If this DLL is already installed then pip install mod_wsgi also should work !!! however this is not.
but with that particulate .whl file its working.
so that is my question how its being installed with this .whl file.

**Comment by maijaz01** [comment]
so you mean to say this .whl file is compliled and its already having the dependent dll files to install mod_wsgi. ????

**Comment by GrahamDumpleton** [comment]
If you run ``pip install mod_wsgi``, it runs the MS C compiler to compile the C code in it to create the equivalent of a DLL. The ``.whl`` file is the output from having done this, so the compilation is already down for you by the person who is providing the ``.whl`` file.

Either way, you end up with an Apache module. It will depend on some other DLLs, but they are ones which are usually part of what is installed with the operating system already.

**Comment by maijaz01** [comment]
So that means if I install only MS C compiler that should work???

**Comment by maijaz01** [comment]
how i can bundle the compiled mod_wsgi as that .whl ??
I have licensed MS so I can compile in my machine and give it to the other person so he don't need to install MS C compiler.
can you please help me on this???

**Comment by GrahamDumpleton** [comment]
Have you tried just supplying the ``.whl`` file alone? As I said above:

> It will depend on some other DLLs, but they are ones which are usually part of what is installed with the operating system already.

So if you are using recent Python version, the DLLs you need are most likely already on the Windows box without needing to install MS C compiler.

**Comment by maijaz01** [comment]
No i can't use unofficial files, so i was thinking that if i can make same .whl file from my system so it would be helpful.
that alone .whl file works but its unofficial

**Comment by GrahamDumpleton** [comment]
Okay, I thought you were trying not to install MS compiler at all even on your own machine.

So with the wheel package installed as well:

* https://wheel.readthedocs.io/en/stable/

run:

```
pip wheel --wheel-dir=wheelhouse mod_wsgi
```

and see if you get a ``.whl`` file in the ``wheelhouse`` directory.

Give that to the other person without MS compiler and see if it works.

**Comment by maijaz01** [comment]
No I have The MS Compiler in my machine but, as i am giving it to other person i don't want him to install MS compile.

**Comment by maijaz01** [comment]
This works.... Thanks
This is just bundling all the mod_wsgi package to .whl package so I am able to install in windows wihtout having MS C compiler 
This was very very helpful @GrahamDumpleton I really appreciate your  support nice talking to you.
