### ISSUE TITLE
from django.core.wsgi import get_wsgi_application ModuleNotFoundError: No module named 'django' with httpd, centos 7

### ISSUE THREAD

**Issue by akshayk10128** [GrahamDumpleton/mod_wsgi#308]
Hi, I am still not able to resolve this with django rest framework and centos 7 and python 3.6 .This is my django.conf

```
WSGIScriptAlias / /venv/core/core/wsgi.py
WSGIPythonHome /venv
WSGIPythonPath /venv/core/core

<Directory /venv/core/core>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>

WSGIDaemonProcess core python-path=/venv/core/core/ python-home=/venv
WSGIProcessGroup core
```

**Comment by akshayk10128** [comment]
This is my wsgi.py file in django project repo : 

import os,sys

exec(open("/venv/bin/activate_this.py").read(), {'__file__': "/venv/bin/activate_this.py"})

sys.path.append('/venv/core/core')

# add the virtualenv site-packages path to the sys.path
sys.path.append('/venv/lib/python3.6/site-packages')

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ipan_core.settings")

application = get_wsgi_application()

**Comment by akshayk10128** [comment]
Error log files : 
[mpm_prefork:notice] [pid 22418] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/4.6.4 Python/3.6 configured -- resuming normal operations
[Wed May 02 10:31:34.054712 2018] [core:notice] [pid 22418] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed May 02 10:31:36.514895 2018] [wsgi:error] [pid 22419] [remote 125.63.68.155:27751] mod_wsgi (pid=22419): Failed to exec Python script file '/ipan_env/ipan_prod/NST_IAP_IPAN_Web_Project/ipan_core/ipan_core/wsgi.py'.
[Wed May 02 10:31:36.514941 2018] [wsgi:error] [pid 22419] [remote 125.63.68.155:27751] mod_wsgi (pid=22419): Exception occurred processing WSGI script '/ipan_env/ipan_prod/NST_IAP_IPAN_Web_Project/ipan_core/ipan_core/wsgi.py'.
[Wed May 02 10:31:36.515136 2018] [wsgi:error] [pid 22419] [remote 125.63.68.155:27751] Traceback (most recent call last):
[Wed May 02 10:31:36.515159 2018] [wsgi:error] [pid 22419] [remote 125.63.68.155:27751]   File "/ipan_env/ipan_prod/NST_IAP_IPAN_Web_Project/ipan_core/ipan_core/wsgi.py", line 37, in <module>
[Wed May 02 10:31:36.515181 2018] [wsgi:error] [pid 22419] [remote 125.63.68.155:27751]     from django.core.wsgi import get_wsgi_application
[Wed May 02 10:31:36.515215 2018] [wsgi:error] [pid 22419] [remote 125.63.68.155:27751] ModuleNotFoundError: No module named 'django'

**Comment by GrahamDumpleton** [comment]
When you activate the Python virtual environment from the command line and run ``python``, what do you get when you enter:

```
import sys
print(sys.prefix)
```

Please don't modify the paths you give me. You appear to have done that in the configuration snippets you gave me as they don't match what the log is showing for the WSGI script file path. It makes it impossible to validate whether you are using the correct paths.

Also, what do you get for:

```
import django
print(django.__file__)
```

**Comment by akshayk10128** [comment]
Python 3.6.4 (default, Dec 19 2017, 14:48:12)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.prefix)
/ipan_env
>>> import django
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'django'
>>> print(django.__file__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'django' is not defined
>>>

**Comment by GrahamDumpleton** [comment]
Which says that Django hasn't even been installed in the virtual environment. Once you have it installed, then you should use ``/ipan_env`` as the value for ``WSGIPythonHome`` and ``python-home``.

**Comment by akshayk10128** [comment]
But when i use sudo from command line , django gets imorted. Is it a permission issue?

**Comment by akshayk10128** [comment]
My Project run fine when i use sudo python3.6 manage.py runserver but gives import error without using sudo.

**Comment by GrahamDumpleton** [comment]
Do not create your virtual environment as ``root`` using ``sudo``. Also do not install packages into it as ``root`` using ``sudo``. The user that Apache runs your code as will not be able to access stuff if ``root`` applies restrictive permissions. Is also a bad idea to install stuff directly under ``/`` directory.

Create a directory something like ``/var/www/project``. Change the ownership to you. Put in that directory the virtual environment and your project code with everything owned by you. Directories and files need to be accessible to other users so that the Apache user can access it. Install packages into the virtual environment as you. Set up mod_wsgi to use your project from that location.

Always run ``python manage.py runserver`` during development as you, never as ``root``.

**Comment by akshayk10128** [comment]
After giving proper permissions its fixed and working.
Thanks

**Comment by lenheard** [comment]
I have to apologies... but I just cant get this right... I am probably reading over the correct answer
I went through many... many.. google articles and this one seems to be the closest to my problem. Please ... if you can help me 

my apache2 sites-available lenwsgi.conf

[lenwsgi.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2278137/lenwsgi.conf.txt)



now my wsgi.py path = /home/kallie/ftp/files/AI

[wsgi .txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2278110/wsgi.txt)



the apache2 error log

[apache2_error_log.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2278083/apache2_error_log.txt)

my file structure
![image](https://user-images.githubusercontent.com/25828249/43961010-209ce680-9cb4-11e8-83bf-34153b9b1c44.png)

my python ( main environment )
![image](https://user-images.githubusercontent.com/25828249/43961353-fdbf0200-9cb4-11e8-8206-cb4ef8fa9c52.png)

python virtual environment (env)
![image](https://user-images.githubusercontent.com/25828249/43961409-31019100-9cb5-11e8-9ffe-c50d2a2ddc6f.png)

django stuff
![image](https://user-images.githubusercontent.com/25828249/43961482-65754d00-9cb5-11e8-9f92-4b163b25f5a1.png)

Thank you in advance
Len

**Comment by GrahamDumpleton** [comment]
Please don't post requests for help on existing issues. Create a new issue. Before you create a new issue, ensure that you have read verified what version of Python your mod_wsgi is compiled for:

* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-installation-in-use

and ensure using a Python virtual environment, that packages you need are installed in it, and then you have configured mod_wsgi to use it in the recommend way:

* http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

That also notes how you should specify where your application source code is.

**Comment by lj16888619** [comment]
uwsgi  --python-version

**Comment by piterkey** [comment]
> uwsgi --python-version
maybe you mean
_uwsgi --version_

**Comment by lahirusamaraweera** [comment]
> After giving proper permissions its fixed and working.
> Thanks man!

What was the permission you give?
