### ISSUE TITLE
Makefile:31: recipe for target 'src/server/mod_wsgi.la' failed

### ISSUE THREAD

**Issue by madcowtricks** [GrahamDumpleton/mod_wsgi#309]
I'm using Ubuntu 16.04,  I've compiled Python3.6.5, apache 2.4.33, APR 1.6.3, APR-util 1.6.1,APR-iconv 1.2.2, and pcre.  
I used "./configure --enable-optimizations  --enable-share --with-threads" to build Python
I used  "./configure --prefix=/usr/local/apache2 --exec-prefix=/usr/local/apache2 \
                               --datadir=/usr/local/apache2  --with-pcre=/usr/local/pcre" 
to configure the apache build.

I  then tried sudo pip install mod_wsgi to install from PyPi and got "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-d8kvpiwu/mod-wsgi/".  
So I got the source from github.
I used " ./configure --prefix=/usr/local/apache2 --exec-prefix=/usr/local/apache2 \
                                --datadir=/usr/local/apache2  --with-apxs=/usr/local/apache2/bin/apxs \
                                --with-python=/usr/local/bin/python3"
and then when I typed make and get:
"/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
apxs:Error: Command failed with rc=65536
Makefile:31: recipe for target 'src/server/mod_wsgi.la' failed
make: *** [src/server/mod_wsgi.la] Error 1"

I specified --with-apxs=/usr/local/apache2/bin/apxs and when i do "which apxs" it returns "/usr/local/apache2/bin/apxs".  So what did I miss?
mark

**Comment by madcowtricks** [comment]
Answered my own question.  I am somewhat dyslexic, I had not noticed that when I configured my python build I typed "enable-share" instead of "enable-shared".  Making that change in the python build and mod_wsgi was smooth sailing to build

**Comment by GrahamDumpleton** [comment]
Beat me to it. Was just about to point that out. :-)

Thanks for letting me know you got it going now.
