### ISSUE TITLE
configure: error: C compiler cannot create executables on Mac OSX 10.11

### ISSUE THREAD

**Issue by sitalk** [GrahamDumpleton/mod_wsgi#310]
There seems to be a problem after running configure on Mac OSX 10.11 (Xcode 8.2):

`./configure`
`checking for apxs2... no`
`checking for apxs... /usr/sbin/apxs`
`checking for gcc... gcc`
`checking whether the C compiler works... no`
`configure: error: in '/Downloads/mod_wsgi-4.6.4':`
`configure: error: C compiler cannot create executables`
`See 'config.log' for more details`

Here is what the config.log says:

`InstalledDir:`   `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`
`configure:2285: $? = 0`
`configure:2274: gcc -V >&5`
`clang: error: argument to '-V' is missing (expected 1 value)`
`clang: error: no input files`
`configure:2285: $? = 1`
`configure:2274: gcc -qversion >&5`
`clang: error: unknown argument: '-qversion'`
`clang: error: no input files`
`configure:2285: $? = 1`
`configure:2305: checking whether the C compiler works`
`configure:2327: gcc -Qunused-arguments -Qunused-argumentssource  conftest.c  >&5`
`clang: error: unknown argument: '-Qunused-argumentssource'`
`configure:2331: $? = 1`
`configure:2369: result: no`
`configure: failed program was:`
`| /* confdefs.h */`
`| #define PACKAGE_NAME ""`
`| #define PACKAGE_TARNAME ""`
`| #define PACKAGE_VERSION ""`
`| #define PACKAGE_STRING ""`
`| #define PACKAGE_BUGREPORT ""`
`| #define PACKAGE_URL ""`
`| /* end confdefs.h.  */`

**Comment by GrahamDumpleton** [comment]
You cannot use the configure/make/make install installation method on MacOS X as Apple stopped shipping all the applications required to be able to compile third party Apache modules. You need to use the ``pip install`` method. See:

* https://pypi.org/project/mod_wsgi/
