### ISSUE TITLE
pip install, error, Failed building wheel for mod-wsgi

### ISSUE THREAD

**Issue by sitalk** [GrahamDumpleton/mod_wsgi#311]
pip install mod_wsgi fails on Mac OS X 10.11. 

It gives the following errors:

`clang: error: unknown argument: '-Qunused-argumentssource'`
`error: command 'clang' failed with exit status 1`
`Failed building wheel for mod-wsgi`

 `clang: error: unknown argument: '-Qunused-argumentssource'`
 `error: command 'clang' failed with exit status 1`
    
    ----------------------------------------

`Command "/usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools,` `tokenize;__file__='/private/var/folders/sv/c2ypb1vd7y5gr30k2tsmcy440000gn/T/pip-install-KMr45_/`
`mod-wsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');`
`f.close();exec(compile(code, __file__, 'exec'))" install --record` `/private/var/folders/sv/c2ypb1vd7y5gr30k2tsmcy440000gn/T/pip-record-gTYkUI/install-record.txt` 
`--single-version-externally-managed --compile" failed with error code 1 in` `/private/var/folders/sv/c2ypb1vd7y5gr30k2tsmcy440000gn/T/pip-install-KMr45_/mod-wsgi/`

**Comment by GrahamDumpleton** [comment]
What distribution of Python is that? Or have you compiled Python from source code yourself?

I am assuming the option is ``-Qunused-arguments`` but somewhere along the line options are being munged together. I don't believe mod_wsgi would be the source of the ``source`` value which is getting added.

BTW, why do you need to use such an old macOS version?

**Comment by GrahamDumpleton** [comment]
Closing. Received no further followup. Ultimately this is a mismatch between what compiler product/version Python was compiled for and what is being used to compile mod_wsgi.
