### ISSUE TITLE
chunked transfer encoding

### ISSUE THREAD

**Issue by Velu-Narasimman** [GrahamDumpleton/mod_wsgi#312]
I am using mod_wsgi version 4.6.2, in embedded mode until now. But thinking to switch to daemon mode of mod_wsgi. When I run test plans on Jmeter on my python application,  I am getting errors in Jmeter. When I looked into the apache error log file, I fond the following lines are logged whenever I run it.

`[Mon May 14 15:42:02.788688 2018] [wsgi:error] [pid 3721:tid 139954912843520] [client 172.24.188.116:41585] Received request requiring chunked transfer encoding, but optional support for chunked transfer encoding has not been enabled.: /usr/share/trac/trac.wsgi` 

What is a chunked encoding? how shall I enable it? and what would be its impact?

**Comment by GrahamDumpleton** [comment]
Docs for ``WSGIChunkedRequest`` finally added.

* http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIChunkedRequest.html
