### ISSUE TITLE
Update mod_wsgi on ubuntu 16.04

### ISSUE THREAD

**Issue by bilalbaqar** [GrahamDumpleton/mod_wsgi#315]
The mod_wsgi version available on Ubuntu 16.04 is `4.3.0-1.1` which is quite old. Any chance that can be updated?

https://packages.ubuntu.com/search?suite=xenial&keywords=libapache2-mod-wsgi

**Comment by GrahamDumpleton** [comment]
Totally out of my control. That is up to Debian and Ubuntu distribution maintainers and history says you can be stuck with older versions for a few years or more on those distributions. They will never update the version except when releasing a new version of their whole distribution. This is why in part I recommend never using the package which comes with those distributions. It is always out of date and also unsupported.

The easier way to keep up to date is to use the ``pip install`` method of installing mod_wsgi. See:

* https://pypi.org/project/mod_wsgi/

**Comment by bilalbaqar** [comment]
Understood. Thanks.
