### ISSUE TITLE
Online manual is outdated

### ISSUE THREAD

**Issue by tkzv** [GrahamDumpleton/mod_wsgi#318]
The section https://modwsgi.readthedocs.io/en/develop/user-guides/configuration-guidelines.html#the-wsgiscriptalias-directive suggests a config:
```
<Directory /usr/local/wsgi/scripts>
Order allow,deny
Allow from all
</Directory>
```
This is fine for Apache 2.2, but results in error 403 for Apache 2.4. I found that new Apache requires the line 
```
Require all granted
```

There probably are more such errors. I don't know enough about Apache or WSGI to spot them.

**Comment by GrahamDumpleton** [comment]
Finally updated in docs like:

* http://modwsgi.readthedocs.io/en/develop/user-guides/configuration-guidelines.html
* http://modwsgi.readthedocs.io/en/develop/user-guides/quick-configuration-guide.html
