### ISSUE TITLE
WSGI Process looking for site-packages at wrong location

### ISSUE THREAD

**Issue by nerdyator** [GrahamDumpleton/mod_wsgi#322]
Hello,
I deployed my django app over AWS ElasticBeanstalk. Then after several days I started getting error as mentioned in following question:
[https://serverfault.com/questions/884469/mod-wsgi-call-to-site-addsitedir-failed-on-aws-elastic-beanstalk-python-3](https://serverfault.com/questions/884469/mod-wsgi-call-to-site-addsitedir-failed-on-aws-elastic-beanstalk-python-3)

I upgraded mod_wsgi 3.5 to 4.4.21.

but then I started getting error of "populate() isn't a reentrant." which is caused by wrong site-packages path.

WSGI Process is trying to find site-packages at `/opt/python/run/venv/local/lib/python3.6/site-packages/django` where as it should go to `/opt/python/run/venv/lib/python3.6/site-packages/django`.

**Comment by GrahamDumpleton** [comment]
The ``populate() isn't a reentrant.`` error is a secondary error message. Go back through the logs to find an earlier error message from immediately after the process was restarted that code is trying to load in. That will tell you the true error.
