### ISSUE TITLE
403 error on root when using --mount-point

### ISSUE THREAD

**Issue by temaput** [GrahamDumpleton/mod_wsgi#329]
Hello!

I'm just starting to use mod_wsgi, so I'm probably wrong, but...
Shouldn't line 706 at server/__init__.py be

<Directory '%(document_root)s'>
instead of
<Directory '%(server_root)s'>
?

The issue is when i say --mount-point /api then I get config saying:

---------------------------------
DocumentRoot '/tmp/mod_wsgi-localhost:8000:0/htdocs'

<Directory '/tmp/mod_wsgi-localhost:8000:0'>
Require all granted
\</Directory>

<Directory '/tmp/mod_wsgi-localhost:8000:0/htdocs/api'>
Require all granted
\</Directory>

---------------------------------

So there is no access granted to /tmp/mod_wsgi-localhost:8000:0/htdocs and I get 403 at the root

**Comment by temaput** [comment]
Hi! Thanks for reply!
I'm using your mod_wsgi-docker image with python 3.5
I have exactly the same intructions as you stated (in my original post I just omitted some lines, sorry).

My scenario is that i'm using Apache for serving wsgi at mount-point (which is /api in my case), plus I want it to serve some static from the root of site. So that i can get index.html with my React SPA sitting at / and talking to django rest framework at /api. 
I thought that mount-point was desined to let me do exactly that sort of thing, but when I say mod_wsgi-express --mount-point /api ..., I get 

1. Django working at /api just fine 
2. 403 forbidden at / (the index.html is there, I checked)

My thought was thats because there is no `Require all granted` instruction for document_root.

I actually developed some workaround with --allow-redefine All, putting `Require all granted` .htaccess to the document-root folder but it seems sort of hacky...

Am I using --mount-point wrong?

**Comment by GrahamDumpleton** [comment]
No you could be right. I probably never considered that one would still want to serve static files like that. The mount point option was originally added to support when the WSGI application had to be at a sub URL behind a proxy. Let me have a think about it.

**Comment by GrahamDumpleton** [comment]
Are you able to test with ``develop`` version out of:

* https://github.com/GrahamDumpleton/mod_wsgi

IOW:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

Change made in https://github.com/GrahamDumpleton/mod_wsgi/commit/df1eda851c804c7a3944d7422461eb90e9535d8e

Thanks.

**Comment by temaput** [comment]
I've just tested my environment with new version of mod_wsgi (4.6.5) and can confirm that the issue is gone.
Thank you! 

My mod_wsgi-express args are now --document-root /ui
