### ISSUE TITLE
Installing mod_wsgi on Windows

### ISSUE THREAD

**Issue by Funicellia** [GrahamDumpleton/mod_wsgi#331]
Hi Graham,
I'm trying to install mod_wsgi on Windows 2008 server: when I run the command

`pip install mod_wsgi `

I get this error

`error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools"`

My configuration is:

- Apache 2.4.33 win64-VC11 downloaded from https://www.apachelounge.com/download/
- Python 3.6 64 bit (python-3.6.5-amd64)
- I have also installed vc runtime downloaded from https://aka.ms/vs/15/release/VC_redist.x64.exe

Can you please give me an advice
Thanks

Aldo

**Comment by GrahamDumpleton** [comment]
You need VC14 compiler, not VC15. Links in:

* https://wiki.python.org/moin/WindowsCompilers

Ensure you are using 64 bit versions of Apache, Python and the compiler.

**Comment by Funicellia** [comment]
I find a solution: I download c++ build tools from here https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe?fixForIE=.exe

Then, I open a command shell "VC2015  x64 native command tool" and launch
`pip install mod_wsgi`

And it works fine.

Thanks
