### ISSUE TITLE
Do we have a full solution for mod_wsgi installation on High Sierra

### ISSUE THREAD

**Issue by michael172849** [GrahamDumpleton/mod_wsgi#333]
I have read a bit about the previous issues and I found many of them the same as the one I am having. Basically it's still the problem that Apple have changed there built-in Apache.
But I cannot find a clear, from-the-begining solution on this problem.

Like do we still have to install full Xcode? Do we need to install the Apache from homebrew in order to use apxs?

**Comment by GrahamDumpleton** [comment]
You still want to install Xcode command line tools and full Xcode application.

Then using ``pip install mod_wsgi`` method as described in:

* https://pypi.org/project/mod_wsgi/

The PyPi page explains the requirements.

**Comment by michael172849** [comment]
OK. I was thinking if I could avoid downloading a 5.3GB app for this. :( I will update if I come into other issue with pip install method. 
Thank you for the quick reply.

**Comment by GrahamDumpleton** [comment]
Unfortunately it is tricky for me to supply binary wheels because it is dependent on Apache and macOS version. So no good solution but to download Xcode if want to use Apple Apache. As you mention, alternative is to use Homebrew for gcc and Apache, but then that still downloads quite a bit as well.

**Comment by michael172849** [comment]
Thank you for your help. It seems that after installing full Xcode on High Sierra does work with the pip install method.
