### ISSUE TITLE
undefined symbol: SSL_get0_alpn_selected

### ISSUE THREAD

**Issue by augustodn** [GrahamDumpleton/mod_wsgi#334]
Hi there!,
After compiling mod_wsgi 4.6.4 with python 3.5, also manually compiled I have this result whenever I try to restart apache with the mod enabled:

# service apache2 restart 
apache2: Syntax error on line 244 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/wsgi.load: Cannot load /usr/lib/apache2/modules/mod_wsgi.so into server: /usr/lib/apache2/modules/mod_wsgi.so: undefined symbol: **SSL_get0_alpn_selected**
Action 'configtest' failed.
The Apache error log may have more information.
 failed!

Not further information in the apache error log (/var/log/apache/error.log).

This is my setup:
Debian 7.11 (wheezy)
Python 3.5.2 manually compiled (since not supported through repositories) 
I might have installed openssl library manually too at the moment of python compilation. I'm clarifying this because the error seems to be related to it.
Apache 2.2.22-13 (Debian package)
mod_wsgi 4.6.4
I'm using a virtual environment with python 3.5.2 + Django 1.11. The testing web server works fine.

I tried also installing mod_wsgi through pip with the same results. In this case, this is the error involved:

apache2 (mod_wsgi-express): Syntax error on line 159 of /tmp/mod_wsgi-localhost:8000:0/httpd.conf: Cannot load /root/.virtualenvs/django/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-i386-linux-gnu.so into server: /root/.virtualenvs/django/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-i386-linux-gnu.so: undefined symbol: **hypot**

Thanks for your help in advance

**Comment by GrahamDumpleton** [comment]
Odd message as mod_wsgi doesn't itself use SSL libraries.

Where is your Python 3.5.2 installed?

Is there a system Python 3.5 package installed of earlier patch level?

What do you get when you do the test:

* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-shared-library

Are you loading mod_ssl into Apache and are you actually hosting secure sites with Apache?

**Comment by augustodn** [comment]
Graham, thanks for your reply. Find my answers below:
Python 3.5.2 is installed in /usr/local/bin/
Python 3.2 (installed by default with deb package) in /usr/bin

After running the test what I get is this:
```
# ldd mod_wsgi.so
	linux-gate.so.1 =>  (0xb7701000)
	libpthread.so.0 => /lib/i386-linux-gnu/i686/cmov/libpthread.so.0 (0xb7384000)
	libdl.so.2 => /lib/i386-linux-gnu/i686/cmov/libdl.so.2 (0xb7380000)
	libutil.so.1 => /lib/i386-linux-gnu/i686/cmov/libutil.so.1 (0xb737b000)
	librt.so.1 => /lib/i386-linux-gnu/i686/cmov/librt.so.1 (0xb7372000)
	libm.so.6 => /lib/i386-linux-gnu/i686/cmov/libm.so.6 (0xb734c000)
	libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xb71e4000)
	/lib/ld-linux.so.2 (0xb7702000)
```
Seems like it's not linked to any python version as the documentation suggests. By the other side this is the folder where the python libraries reside:

```
/usr/local/lib# ll
total 13M
-r-xr-xr-x  1 root staff  13M jun 12 14:02 libpython3.5m.a
drwxr-sr-x  2 root staff 4,0K jun 12 14:03 pkgconfig
drwxrwsr-x  4 root staff 4,0K feb  9 11:07 python2.6
drwxrwsr-x  4 root staff 4,0K feb  9 11:06 python2.7
drwxrwsr-x  3 root staff 4,0K sep  7  2017 python3.2
drwxr-sr-x 36 root staff 4,0K jun 12 14:02 python3.5

```
Finally, I'm not loading mod_ssl into Apache at all.
Thanks for your help!

**Comment by GrahamDumpleton** [comment]
When you install Python from source code, you need to ensure a shared library for Python is built. The option to ``configure`` for Python you need is ``--enable-shared``.

See also guidelines in the post at:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Ignore that it talks about Docker, all same applies.
