### ISSUE TITLE
Target WSGI script '.../wsgi.py' cannot be loaded as Python module.

### ISSUE THREAD

**Issue by zzm88** [GrahamDumpleton/mod_wsgi#335]
> [Fri Jun 29 10:48:38.006728 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346] mod_wsgi (pid=12999): Target WSGI script '/home/zzm/getsms/example/example/wsgi.py' cannot be loaded as Python module.
> [Fri Jun 29 10:48:38.006888 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346] mod_wsgi (pid=12999): Exception occurred processing WSGI script '/home/zzm/getsms/example/example/wsgi.py'.
> [Fri Jun 29 10:48:38.006963 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346] Traceback (most recent call last):
> [Fri Jun 29 10:48:38.007046 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/home/zzm/getsms/example/example/wsgi.py", line 12, in <module>
> [Fri Jun 29 10:48:38.007133 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django.core.wsgi import get_wsgi_application
> [Fri Jun 29 10:48:38.007194 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django/core/wsgi.py", line 2, in <module>
> [Fri Jun 29 10:48:38.007283 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django.core.handlers.wsgi import WSGIHandler
> [Fri Jun 29 10:48:38.007344 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 8, in <module>
> [Fri Jun 29 10:48:38.007416 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django import http
> [Fri Jun 29 10:48:38.007478 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django/http/__init__.py", line 5, in <module>
> [Fri Jun 29 10:48:38.007550 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django.http.response import (
> [Fri Jun 29 10:48:38.007593 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django/http/response.py", line 13, in <module>
> [Fri Jun 29 10:48:38.007635 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django.core.serializers.json import DjangoJSONEncoder
> [Fri Jun 29 10:48:38.007669 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 23, in <module>
> [Fri Jun 29 10:48:38.007739 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django.core.serializers.base import SerializerDoesNotExist
> [Fri Jun 29 10:48:38.007776 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 4, in <module>
> [Fri Jun 29 10:48:38.007818 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django.db import models
> [Fri Jun 29 10:48:38.007851 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]   File "/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 2, in <module>
> [Fri Jun 29 10:48:38.007890 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346]     from django.db.models import signals
> [Fri Jun 29 10:48:38.007935 2018] [:error] [pid 12999:tid 140251663496960] [remote 38.106.23.97:5346] ImportError: cannot import name signals
> 

my.conf
```
<VirtualHost *:80>
    ServerAdmin webmaster@mydomain.com
    ServerName www.getsms.club
    ServerAlias getsms.club
    
    WSGIDaemonProcess getsms python-home=/var/www/.virtualenvs/getsms/ python-path=/home/zzm/getsms/ 
    WSGIProcessGroup getsms
    WSGIScriptAlias / /home/zzm/getsms/example/example/wsgi.py process-group=getsms
    
    <Directory /home/zzm/getsms/example/example/>
    <Files wsgi.py>
        Require all granted
    </Files>
    </Directory>
</VirtualHost>
```

**Comment by GrahamDumpleton** [comment]
From doing a bit of a Google, often this is because of permissions issues on files.

Check under the directory:

```
/var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django
```

and make sure all the file system permissions look reasonable.

Can possibly run:

```
find /var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django -name '*.py' -exec chmod 0644 {} \;
find /var/www/.virtualenvs/getsms/local/lib/python2.7/site-packages/django -type d -exec chmod 0755 {} \;
```

To make sure files and directories all readable.

Also check permissions on anything in your project code.

Also check that your mod_wsgi is compiled for same Python X.Y version as your virtual environment is created from.

* http://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-installation-in-use
