### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by GitEasonXu** [GrahamDumpleton/mod_wsgi#336]
## Platform
**`Ubuntu 14.04`**
**`Anaconda3:Python3.5`**
**`Apache2.4.7`**
**`mod_wsgi-4.6.4`**

## Install step
- 1 `sudo apt-get install apache2`
- 2 `sudo apt-get install apache2-dev`
- 3 build mod_wsgi  
     - `./configure`  
     -  `LD_RUN_PATH=/home/xu/anaconda3/lib make`  
     - `sudo make install`  
     **output is**:  
     ```     
    Libraries have been installed in:
   /usr/lib/apache2/modules
   If you ever happen to want to link against installed libraries
   in a given directory, LIBDIR, you must either use libtool, and
   specify the full pathname of the library, or use the `-LLIBDIR'
   flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'
   See any operating system documentation about shared libraries for
   more information, such as the ld(1) and ld.so(8) manual pages.
   ----------------------------------------------------------------------
  chmod 644 /usr/lib/apache2/modules/mod_wsgi.so
     ```   
- 4 Config Apache2
    - `sudo vi /etc/apache2/sites-available/rest-api.conf`   
       ```   
       <VirtualHost *:80>
		ServerName 192.168.1.176
		ServerAdmin xu@gmail.com
		WSGIScriptAlias / /var/www/keras-complete-rest-api/rest_api_app.wsgi
		WSGIDaemonProcess flaskapp python-path=/home/xu/anaconda3/lib/python3.5/site-packages 

		<Directory /var/www/keras-complete-rest-api/>
			Order allow,deny
			Allow from all
		</Directory>

		ErrorLog ${APACHE_LOG_DIR}/error.log
		LogLevel warn
		CustomLog ${APACHE_LOG_DIR}/access.log combined
       </VirtualHost>   
       ```   
- 5 `sudo a2dissite 000-default.conf`   
     `sudo a2ensite rest-api.conf`   
     `sudo service apache2 restart`

## Finally, testing  
    There is nothing in the browser, so I cat the `error.log`, it show that:    

    ```
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Fatal Python error: Py_Initialize: Unable to get the locale encoding   
    ImportError: No module named 'encodings'   
    Current thread 0x00007f1702599780 (most recent call first):
    ```

I found a lot of relevant answers on the Internet, but I still can't solve it.So I am asking for help.

**Comment by GrahamDumpleton** [comment]
You should not use ``python-path`` to point at ``site-packages``. You should use ``python-home`` to point at the root of the virtual environment. So for a start try using:

```
WSGIDaemonProcess flaskapp python-home=/home/xu/anaconda3
```

You are also missing:

```
WSGIProcessGroup flaskapp
```

The daemon process group wasn't even being used.

It is also recommended you add:

```
WSGIRestrictEmbedded On
```

immediately after the ``LoadModule`` line for ``wsgi_module``.

This turns off embedded mode and ensures you are using daemon mode.

For more details on setting up a virtual environment see:

* http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by GitEasonXu** [comment]
@GrahamDumpleton Good suggestion, thank you very much!!

**Comment by GrahamDumpleton** [comment]
Okay, will close this now. If encounter new problems create a new issue.
