### ISSUE TITLE
mod_wsgi install failed in windows server 2008 r2 sp1 

### ISSUE THREAD

**Issue by pythonBoyho** [GrahamDumpleton/mod_wsgi#337]
I can't install mod_wsgi cuz "ap_config_auto.h: No such file or directory"
but as you can see below my enviroment, everything is 64bit but still failed to install.. 

My enviroment is below. 

os : windows server 2008 r2 sp1 64bit
python : 3.6.4 (Anaconda 64 bit Installed)
apache : Apache 2.4.33 Win64 (standAlone version get in apachelounge)
mod_wsgi : mod_wsgi-4.5.24.tar.gz (cuz I've read 4.6.x versions have a problem with install on windows)

installed apache in c:\Apache24 and if I execute server, it works well. I can see "It Works"
And I try to install mod_wsgi-4.5.24.tar.gz. but install failed.. see this error below. 

pip install mod_wsgi-4.5.24.tar.gz
Processing d:\dev\keras\mod_wsgi-4.5.24.tar.gz
Building wheels for collected packages: mod-wsgi
  Running setup.py bdist_wheel for mod-wsgi ... error
  Complete output from command C:\ProgramData\Anaconda3\envs\venv\python.exe -u
-c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\T
emp\\2\\pip-2a1rjvf_-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__
);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'ex
ec'))" bdist_wheel -d C:\Users\ADMINI~1\AppData\Local\Temp\2\tmpvgi2jcc0pip-whee
l- --python-tag cp36:
  C:\ProgramData\Anaconda3\envs\venv\lib\distutils\dist.py:261: UserWarning: Unk
nown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\mod_wsgi
  copying src\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi
  creating build\lib.win-amd64-3.6\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win-amd64-3.6\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win-amd64-3.6\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi\server
  creating build\lib.win-amd64-3.6\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi\
server\management
  creating build\lib.win-amd64-3.6\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.
6\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.6\
mod_wsgi\server\management\commands
  creating build\lib.win-amd64-3.6\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi\docs
  creating build\lib.win-amd64-3.6\mod_wsgi\images
  copying images\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.6\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  creating build\temp.win-amd64-3.6\Release\src\server
  C:\ProgramData\Anaconda3\envs\venv\Library\mingw-w64\bin\gcc.exe -mdll -O -Wal
l -DMS_WIN64 -Ic:\Apache24/include -IC:\ProgramData\Anaconda3\envs\venv\include
-IC:\ProgramData\Anaconda3\envs\venv\include -c src/server\mod_wsgi.c -o build\t
emp.win-amd64-3.6\Release\src\server\mod_wsgi.o
  In file included from c:\Apache24/include/httpd.h:44:0,
                   from src/server\wsgi_apache.h:42,
                   from src/server\mod_wsgi.c:21:
  c:\Apache24/include/ap_config.h:138:28: fatal error: ap_config_auto.h: No such
 file or directory
  compilation terminated.
  error: command 'C:\\ProgramData\\Anaconda3\\envs\\venv\\Library\\mingw-w64\\bi
n\\gcc.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
  Running setup.py install for mod-wsgi ... error
    Complete output from command C:\ProgramData\Anaconda3\envs\venv\python.exe -
u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\
\Temp\\2\\pip-2a1rjvf_-build\\setup.py';f=getattr(tokenize, 'open', open)(__file
__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, '
exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-inj8rngj-re
cord\install-record.txt --single-version-externally-managed --compile:
    C:\ProgramData\Anaconda3\envs\venv\lib\distutils\dist.py:261: UserWarning: U
nknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\mod_wsgi
    copying src\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi
    creating build\lib.win-amd64-3.6\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win-amd64-3.6\mod_wsgi\server

    copying src\server\environ.py -> build\lib.win-amd64-3.6\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi\server
    creating build\lib.win-amd64-3.6\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win-amd64-3.6\mod_wsg
i\server\management
    creating build\lib.win-amd64-3.6\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-
3.6\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.
6\mod_wsgi\server\management\commands
    creating build\lib.win-amd64-3.6\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi\doc
s
    creating build\lib.win-amd64-3.6\mod_wsgi\images
    copying images\__init__.py -> build\lib.win-amd64-3.6\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.6\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\src\server
    C:\ProgramData\Anaconda3\envs\venv\Library\mingw-w64\bin\gcc.exe -mdll -O -W
all -DMS_WIN64 -Ic:\Apache24/include -IC:\ProgramData\Anaconda3\envs\venv\includ
e -IC:\ProgramData\Anaconda3\envs\venv\include -c src/server\mod_wsgi.c -o build
\temp.win-amd64-3.6\Release\src\server\mod_wsgi.o
    In file included from c:\Apache24/include/httpd.h:44:0,
                     from src/server\wsgi_apache.h:42,
                     from src/server\mod_wsgi.c:21:
    c:\Apache24/include/ap_config.h:138:28: fatal error: ap_config_auto.h: No su
ch file or directory
    compilation terminated.
    error: command 'C:\\ProgramData\\Anaconda3\\envs\\venv\\Library\\mingw-w64\\
bin\\gcc.exe' failed with exit status 1

    ----------------------------------------
Command "C:\ProgramData\Anaconda3\envs\venv\python.exe -u -c "import setuptools,
 tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-2a1rjvf_-b
uild\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replac
e('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --recor
d C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-inj8rngj-record\install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in C:\Us
ers\ADMINI~1\AppData\Local\Temp\2\pip-2a1rjvf_-build\

I find some people's question about ap_config_auto.h. and they solved this problem to set all enviroment applications versions 64 or 32 bit. but I already did it. everything is 64 bit applications.. 

and here is my windows path. Is there anything should I have to add or remove some path? Its not problem then How can I install mod_wsgi?? please help me. 
C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files (x86)\Intel\Composer XE 2011 SP1\redist\intel64\mkl;C:\Program Files (x86)\Intel\Composer XE 2011 SP1\redist\ia32\mkl;%C_EM64T_REDIST12%redist\intel64\compiler;%C_IA32_REDIST12%redist\ia32\compiler;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Dell\SysMgt\oma\bin;C:\Program Files (x86)\Dell\SysMgt\shared\bin;C:\Program Files (x86)\Dell\SysMgt\idrac;C:\java\Apache-Subversion-1.8.5\bin;C:\application\apache-ant-1.9.0\bin;C:\TIBCO\TIBRV\BIN;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Graphviz2.38\bin;%JAVA_HOME%\bin;

**Comment by GrahamDumpleton** [comment]
But what Apache distribution are you using? Some of those going under the MAMP name do not provide the required files to allow you to build additional Apache modules. Only the Apache distribution from ApacheLounge is known for sure to work if building mod_wsgi yourself using ``pip install`` method.

**Comment by pythonBoyho** [comment]
Im not sure Apache distribution what I using, but I download that this url. https://www.apachelounge.com/download/ 
and downloaded 'Apache 2.4 binaries VC15.' (Apache 2.4.33 Win64 : httpd-2.4.33-win64-VC15.zip)     
Am I downloaded wrong Apache distribution?

**Comment by GrahamDumpleton** [comment]
That is the ApacheLounge distribution.

You are hitting a different issue then, which is that for whatever reason, the MS C compiler you have installed, or how it is activated in your environment, is not resulting in it being correct identified as being on the WIN32 platform.

The code in the header file is:

```
#if (!defined(WIN32) && !defined(NETWARE)) || defined(__MINGW32__)
#include "ap_config_auto.h"
#endif
#include "ap_config_layout.h"
```

The ``WIN32`` variable should be defined, meaning it should include ``ap_config_layout.h`` and not ``ap_config_auto.h``.

Have seen this issue once before from memory. I don't recollect whether that person let me know if they solved it.

Because you are using Python 3.6, you need to be using the MS VC14 C compiler.

* https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Build_Tools_for_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29

What compiler version are you using?

**Comment by pythonBoyho** [comment]
I installed Visual C++ Redistributable 2017 (x64). So I think I using VC14 compiler. but after I installed that, I did not restart server. could be this caused that error?

**Comment by GrahamDumpleton** [comment]
Not normally. But are you using the command terminal created using menu item under compiler menus. Usually that ensures all the environment is set up correctly. If using a different way of creating command shell, but not everything is setup correctly.

**Comment by GrahamDumpleton** [comment]
It has been a very long time since I have used windows, but my recollection is that when you install the MS C compiler, especially if using the Visual Studio version, it will add new menu entries for the various tools installed. One of those is a menu item which creates you a command terminal which has had the appropriate batch script run to add all the MS C compiler variables to your environment so that when the compiler is run, things are found correctly.

If you are using Anaconda Python though, the issue may be that it has broken the compiler flags configuration in some way so that the correct flags aren't supplied.

**Comment by pythonBoyho** [comment]
I found something on ap_config.h. 

```
#include "os.h"
#if (!defined(WIN32) && !defined(NETWARE)) || defined(__MINGW32__)
#include "ap_config_auto.h"
#endif
#include "ap_config_layout.h"
```

when I edit ap_config.h. like this...
```
#include "os.h"
#if defined(__MINGW32__)
#include "ap_config_auto.h"
#endif
#include "ap_config_layout.h"
```

it occurs same error that I asked : could not find 'ap_config_auto.h'
but when I edit this way.. 
```
#include "os.h"
#if defined(!defined(WIN32) && !defined(NETWARE))
#include "ap_config_auto.h"
#endif
#include "ap_config_layout.h"
```

that occurs another error.. not could not find 'ap_config_auto.h'
so I think my problem is __MINGW32__ 
but I dont know what is __MINGW32__  and how can I fix it??

**Comment by GrahamDumpleton** [comment]
``__MINGW32__`` is:

* http://www.mingw.org/

So looks like it is picking up the wrong compiler.

Unless Anaconda has now really broken everything by bundling/using that compiler.

```
\ProgramData\Anaconda3\Library\mingw-w64\bin
```

If that is the case, you just will not be able to use Anaconda Python with mod_wsgi on Windows any more and will only be able to use Python from the Python Software Foundation (PSF).

* https://www.python.org/downloads/

**Comment by GrahamDumpleton** [comment]
You are getting Anaconda Python from following?

* https://www.anaconda.com/download/#windows

**Comment by GrahamDumpleton** [comment]
According to:

* https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#using-your-customized-compiler-package-with-conda-build-3

It says:

> On Windows the Python ecosystem uses the Microsoft Visual C compilers, while the R ecosystem uses the Mingw compilers.

Based on what you are seeing, I am not sure how true that is.

**Comment by GrahamDumpleton** [comment]
As per:

* https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#using-your-customized-compiler-package-with-conda-build-3

what does ``conda_build_config.yaml`` contain if can find it?

**Comment by pythonBoyho** [comment]
I find it but every python packages have conda_build_config.yaml.. I dont know which file should I look at it. so I decided install new Python 3.6.4(64bit) and try to install mod_wsgi 
and got a new Error : microsoft visual c++ 14.0 is required. get it with microsoft visual c++ build tools 

but as you know I already installed Visual C++ Redistributable 2017 (x64)... should I download and install microsoft visual c++ build tools ??

**Comment by GrahamDumpleton** [comment]
You need to be careful with what package you install. Some only have the libraries needed by apps compiled with the full package. When you say ``Redistributable`` it sounds a bit like that may be what you have.

I only know that the links in page at:

* https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Build_Tools_for_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29

are definitely the right one for compilers.

**Comment by pythonBoyho** [comment]
Finally I setup mod_wsgi. I setup same thing in my private PC and Copy and Paste Apache server, Python virtual enviroment to my work Server. Its not clear way to setup, but it works well and Im very happy. thanks for your help.
