### ISSUE TITLE
mod_wsgi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Trevirirus** [GrahamDumpleton/mod_wsgi#338]
Hi,

i have compiled the latest release today and when im trying to restart the apache server the following is promted to the console:

> apache2: Syntax error on line 230 of /etc/apache2/apache2.conf: Syntax error on line 2 of /etc/apache2/httpd.conf: Cannot load modules/mod_wsgi.so into server: /etc/apache2/modules/mod_wsgi.so: cannot open shared object file: No such file or directory

inside my **apache2.conf** i import my **httpd.conf** file:

```
# load  and configure mod_wsgi:

LoadModule wsgi_module modules/mod_wsgi.so

WSGIScriptAlias /mapproxy /mnt/0a0caead-2478-405e-9924-90617b1656f7/itvs_osm/itvs_wmts/conf/config.py

WSGIApplicationGroup %{GLOBAL}

<Directory /mnt/0a0caead-2478-405e-9924-90617b1656f7/itvs_osm/itvs_wmts/> 
    #Allow from all
    Order Deny,allow
    Require all granted
</Directory>

```
I installed apacha via [https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-18-04](url)

where is my error?

**Comment by GrahamDumpleton** [comment]
What method did you use to compile and install the latest mod_wsgi release? What were the commands you ran to do that?

**Comment by Trevirirus** [comment]
the quick guide commands:
````
./configure
make
sudo make install

**Comment by GrahamDumpleton** [comment]
Does ``/etc/apache2/modules/mod_wsgi.so`` exist?

Rerun the ``make install`` and capture the output so can see where it installed the module.

BTW, often better to use the ``pip install`` method.

* https://pypi.org/project/mod_wsgi/

**Comment by Trevirirus** [comment]
yeah the file is there.
I also run the pip command. Before running the python command the file was there.
The output of the `make install` is:

> /usr/bin/apxs2 -i -S LIBEXECDIR=/usr/lib/apache2/modules -n 'mod_wsgi' src/server/mod_wsgi.la
/usr/share/apache2/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1.0/build/libtool' src/server/mod_wsgi.la /usr/lib/apache2/modules
/usr/share/apr-1.0/build/libtool --mode=install install src/server/mod_wsgi.la /usr/lib/apache2/modules/
libtool: install: install src/server/.libs/mod_wsgi.so /usr/lib/apache2/modules/mod_wsgi.so
libtool: install: install src/server/.libs/mod_wsgi.lai /usr/lib/apache2/modules/mod_wsgi.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/lib/apache2/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/lib/apache2/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
chmod 644 /usr/lib/apache2/modules/mod_wsgi.so

**Comment by GrahamDumpleton** [comment]
For whatever reason, your Apache installation isn't set up such that ``modules`` is a sub directory of the Apache root directory. You will need to use:

```
LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
```

**Comment by Trevirirus** [comment]
Okay thank you that's working now.

**Comment by artforlife** [comment]
I am experiencing a similar issue. 

```
sudo apachectl restart
apache2: Syntax error on line 146 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/wsgi.load: Cannot load /usr/lib/apache2/modules/mod_wsgi.so into server: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Action 'restart' failed.
The Apache error log may have more information.
```

However, the .SO file is actually within the directory in question:

```
user@machine: ~/mod_wsgi-4.6.5$ ls /usr/lib/apache2/modules/mod_wsgi.so
/usr/lib/apache2/modules/mod_wsgi.so
```

**Comment by GrahamDumpleton** [comment]
The message is saying it can't find `libpython3.7m.so.1.0` not the `mod_wsgi.so` file. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#unable-to-find-python-shared-library

In short, you are trying to use a Python installation in a non standard location, so you need to tell the build where it is. You can also fudge things by adding:

```
LoadFile /some/path/libpython3.7m.so.1.0
```

before the `LoadModule` line, where `/some/path` is replaced with the directory where Python library was installed.

You may also need to set `WSGIPythonHome` directory to be what `sys.prefix` is set to for Python since not in standard location.

**Comment by artforlife** [comment]
Thank you.

When I search the entire HDD for that library, I get this:

ubuntu@machine:~$ sudo find / -type f -name "libpython3.7m.so.1.0"
/home/ubuntu/miniconda3/envs/project-web/lib/libpython3.7m.so.1.0
/home/ubuntu/miniconda3/pkgs/python-3.7.6-h0371630_2/lib/libpython3.7m.so.1.0
/home/ubuntu/miniconda3/pkgs/python-3.7.4-h265db76_1/lib/libpython3.7m.so.1.0
/home/ubuntu/miniconda3/lib/libpython3.7m.so.1.0

That is, when I originally installed this Python, I did it using the following [steps](https://thecustomizewindows.com/2017/10/install-miniconda-ubuntucentos/) with the purpose of installing Miniconda. I then ran into issues deploying a Django app using a Miniconda-created virtual environment. 

Somewhere on SO, I found your recommendation for rebuilding the MOD_WSGI with the same version of Python as the one installed on the machine. That is where I am getting stuck.

**Comment by artforlife** [comment]
I was able to build MOD_WSGI and restart the Apache successfully. As you mentioned, it took adding `LoadFile` into the `mod_wsgi.load` file to get the thing working properly. Copying Python library's shared object file into `/lib`, `/usr/lib`, `/usr/local/lib` had no effect.

**Comment by GrahamDumpleton** [comment]
Using `LoadFile` is best and possibly only way that things will work when using Anaconda Python as they keep somehow mucking up link of the shared libraries when use in embedded systems.

Also do be aware that if using Anaconda Python you cannot use `mod_ssl` or PHP in the same Apache, as Anaconda ships their own copies of libraries which conflict with system libraries and so using those Apache modules will cause crashes in Python applications.

**Comment by artforlife** [comment]
Thanks for the heads-up. Does this mean that there is currently no way to use an Anaconda environment and have the app run HTTPS, assuming it is served via Apache? Would switching to venv environment be all that is needed to avoid that trouble?

**Comment by GrahamDumpleton** [comment]
The only way to use Apache to terminate HTTPS connections, and use mod_wsgi when using Anaconda Python, is to use mod_wsgi-express to run a separate Apache/mod_wsgi instance and then configure the main Apache instance to accept HTTPS and proxy to the separate mod_wsgi-express instance of Apache/mod_wsgi.

Just reiterating, this is a problem caused by Anaconda Python and not the fault of Apache or mod_wsgi. In general, unless you have a specific need for conda packages, I wouldn't use Anaconda Python for web applications, use the system Python instead.

**Comment by VenkateshDharavath** [comment]
I'm facing the same issue, could you please provide me any documentation on how to install python with shared libraries enabled properly?

**Comment by GrahamDumpleton** [comment]
Did you read the comments above? It gives links to documentation and also provides an alternate method using `LoadFile` that can be necessary in some cases.

**Comment by mushoti** [comment]
Thank you Graham LoadFile worked fine RHEL

**Comment by Mahbuba-Tasmin** [comment]
@artforlife how did you get Anaconda python to load Apache? I have tried using LoadFile as well and disabled SELinux, still it shows "cannot open shared object file: No such file or directory" error when starting apache server. I am running on Miniconda3 and have compiled mod_wsgi in the same environment. I am attaching my config file here, if anyone can shed some light on it , this will be very helpful.

`LoadFile wsgi_module "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so"
ServerName localhost
<VirtualHost *:80>
    ServerAlias chatbotv1
    WSGIDaemonProcess chatbotv1  user=apache group=apache python-home=/var/www/chatbotv1/miniconda3
    WSGIScriptAlias / /var/www/chatbotv1/chatbotv1.wsgi
    <Directory /var/www/chatbotv1>
        Require all granted
    </Directory>
    Alias /static /var/www/chatbotv1/static
    <Directory /var/www/chatbotv1/static>
        Require all granted
    </Directory>
    DocumentRoot /var/www/chatbotv1
    ErrorLog /var/www/chatbotv1/log/error.log
    CustomLog /var/www/chatbotv1/log/requests.log combined

</VirtualHost>
WSGIPythonHome "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow"
`

**Comment by GrahamDumpleton** [comment]
What do you get when you run:

```
ls -las /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
```

and:

```
ls -las /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server
```

I believe the loading of the file should be done by Apache when running as `root`, but if for some reason that isn't the case due to how Apache is being run, then it is important that the file and all directories down to it are accessible to user loading is done as.

**Comment by Mahbuba-Tasmin** [comment]
Here's the outcome of the above two commands:
![conda-apache-loaderror](https://user-images.githubusercontent.com/69891263/94769101-0e6ded00-03d3-11eb-8780-9b6b2a7b4995.png)

**Comment by GrahamDumpleton** [comment]
When installing ``mod_wsgi`` using ``pip install``, try using the options ``--no-cache-dir -U``. The problem could be that you installed mod_wsgi once for Python in different virtual environment or when Anaconda was installed at different location and so reference is to wrong location for where the Anaconda Python library is. So is complaining about that. You may be able to test that idea by running:

```
ldd /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
```

What do you get?

Anaconda Python also has in the past screwed up things so that its own shared libraries aren't found at runtime correctly unless you tell build where they are.

**Comment by GrahamDumpleton** [comment]
FWIW, Anaconda Python is no end of problems. If you don't specifically need it, use Python Software Foundation Python distribution.

**Comment by Mahbuba-Tasmin** [comment]
You are right, I got an error **libpython3.8.so.1.0 => not found**

(conda-tensorflow) [root@DEV-AI02 ~]# ldd /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffd97bcf000)
        libpython3.8.so.1.0 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f93fe961000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f93fe593000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f93feb7d000)

**Comment by GrahamDumpleton** [comment]
Find where the ``libpython3.8.so.1.0`` file is located, and add a line:

```
LoadFile /some/path/libpython3.8.so.1.0
```

before the ``LoadFile`` line for the mod_wsgi.so file.

Obviously replace ``/some/path`` with actual path.

**Comment by Mahbuba-Tasmin** [comment]
I have updated the config file, now getting this error. mod-wsgi can't access libpython at lib folder inside conda. 

![libpython_notfound](https://user-images.githubusercontent.com/69891263/94773525-c3a5a280-03dd-11eb-9259-6e90c3d9f0c2.png)

**Comment by GrahamDumpleton** [comment]
You don't want the `libpython3.8.so.1.0` in the virtual environment, you want the one from your main Anaconda Python installation.

**Comment by Mahbuba-Tasmin** [comment]
Correct, I have tried using libpython from conda-python installation.  **libpython3.8.so.1.0** is still missing. Do I need to edit library path in Centos for this? 

`LoadFile /var/www/chatbotv1/miniconda3/lib/libpython3.8.so.1.0
LoadFile wsgi_module "/var/www/chatbotv1/miniconda3/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so"
ServerName localhost
<VirtualHost *:80>
    ServerAlias chatbotv1
    WSGIDaemonProcess chatbotv1  user=apache group=apache python-home=/var/www/chatbotv1/miniconda3
    WSGIScriptAlias / /var/www/chatbotv1/chatbotv1.wsgi
    <Directory /var/www/chatbotv1>
        Require all granted
    </Directory>
    Alias /static /var/www/chatbotv1/static
    <Directory /var/www/chatbotv1/static>
        Require all granted
    </Directory>
    DocumentRoot /var/www/chatbotv1
    ErrorLog /var/www/chatbotv1/log/error.log
    CustomLog /var/www/chatbotv1/log/requests.log combined

</VirtualHost>
WSGIPythonHome "/var/www/chatbotv1/miniconda3"`

![conda-libpython](https://user-images.githubusercontent.com/69891263/94776819-3a459e80-03e4-11eb-918b-410013daccd9.png)

**Comment by GrahamDumpleton** [comment]
What ``ldd`` shows has nothing to do with the Apache configuration. The question is whether Apache works after making that change, not ``ldd``?

For ``ldd`` you would need to run:

```
LD_LIBRARY__PATH=/var/www/chatbotv1/miniconda3/lib ldd /var/www/chatbotv1/miniconda3/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
```

to test it.
