### ISSUE TITLE
(13)Permission denied: mod_wsgi (pid=48367): Unable to stat Python home /root/.local/share/virtualenvs/public_html-LXoYCNQz. Python interpreter may not be able to be initialized correctly. Verify the supplied path and access permissions for whole of the path.

### ISSUE THREAD

**Issue by gautamyadavs** [GrahamDumpleton/mod_wsgi#339]
I have been trying to remove ImportError: No module named 'encodings' since yesterday while deploying django website on my college server. I have tried normal installation and also wsgi_express in the virtual environment. I have also given all permissions using sudo chmod 777 to the folder containing the webapp. I'm using pipenv for the virtual environment

This is my error.log
![12](https://user-images.githubusercontent.com/25340998/42562455-60879d2e-8519-11e8-8f79-1b5105bf81f3.png)

My wsgi_express.load file is
`LoadModule wsgi_module /root/.local/share/virtualenvs/public_html-LXoYCNQz/lib/python3.4/site-packages/mod_wsgi/server/mod_wsgi-py34.cpython-34m.so`

And my wsgi_express.conf is
```
WSGIRestrictEmbedded On
WSGIApplicationGroup %{GLOBAL}
# Django site
Alias /index.txt /home/intern2/public_html/index.txt
WSGIScriptAlias / /home/intern2/public_html/wiki/wsgi.py
WSGIDaemonProcess public_html python-home=/root/.local/share/virtualenvs/public_html-LXoYCNQz
WSGIProcessGroup public_html
Alias /static /home/intern2/public_html/static
<Directory /home/intern2/public_html/static>
        Require all granted
</Directory>

<Directory /home/intern2/public_html/wiki>
        <Files wsgi.py>
                Require all granted
        </Files>
</Directory>
```

**Comment by GrahamDumpleton** [comment]
You should put anything under ``/root``. Only the ``root`` user will be able to access it. The Apache user can't and so things break when Python is initialised.

**Comment by gautamyadavs** [comment]
should I then delete the virtual environment and make it from the user account?

**Comment by GrahamDumpleton** [comment]
Is the home directory of the user accessible to others? That is another trap.

Usually better to put stuff under ``/var/www/project`` where sure Apache user can access things.

**Comment by gautamyadavs** [comment]
I ran `chmod 777 /home/usr` to grant read and write access to all users

**Comment by GrahamDumpleton** [comment]
Is always a bad idea to grant ``777`` access on files and directories. You possibly only need ``755`` on your home directory, and only if it was previously ``750``.

**Comment by gautamyadavs** [comment]
okay I have moved everything from root to the user but now another error is coming

![dsds](https://user-images.githubusercontent.com/25340998/42564780-46bbdabc-851f-11e8-929b-99739927ded0.png)

And when I'm going to the domain http://172.16.112.151/~intern2/ 500 Internal Server Error is written there.

**Comment by GrahamDumpleton** [comment]
There is no error message there. If there is no error message in the Apache error logs from when you made the request, it is likely an error from the web framework you are using, and the web framework has not been set up to log errors.

What web framework are you using? Does it have a debug mode you can enable so it displays the error in the browser?

**Comment by gautamyadavs** [comment]
I'm using Django and it's DEBUG variable is set to True

**Comment by GrahamDumpleton** [comment]
Then check your log file again for an error.

Are you sure the log file you included is all there is? There is nothing in what you show to indicate that mod_wsgi even handled the request. If it had, there would have been a message indicating when mod_wsgi loaded your WSGI script file.

Does you Apache setup use any ``VirtualHost`` definitions?

**Comment by gautamyadavs** [comment]
There's no error in the error log. 
I don't know what this means 'apache setup use any VirtualHost definitions' but I tried placing the lines in wsgi_express.conf in <VirtualHost *:80> and nothing changed.

Even I think there should have been any indication of further processing so I'm trying to set some paths in wsgi.py file in my Django application. Maybe that will work.

**Comment by GrahamDumpleton** [comment]
Tail the Apache access log and see if the Apache is even receiving the requests.

**Comment by gautamyadavs** [comment]
okay, there's some import error but I have no idea where it's occurring so I'll try and correct it.

![sd](https://user-images.githubusercontent.com/25340998/42567821-b14739c2-8528-11e8-8b17-a6339b6b1a62.png)

**Comment by GrahamDumpleton** [comment]
Possibly you have mucked up arguments in your url rules. Have given a file name for template or something where expecting to be given name of view handler.

**Comment by gautamyadavs** [comment]
My domain is this https://202.141.80.42/~intern2/ and http://www.iitg.ac.in/cseweb/wikiproject/ for running my server but when i run in localhost I can access my urls using localhost/admin, etc.. but when I'm trying to access https://202.141.80.42/~intern2/admin error 404 Not Found is coming.
The requested URL /~intern2/admin was not found on this server. Any idea what should I change??

**Comment by GrahamDumpleton** [comment]
You shouldn't be using ``https://202.141.80.42/~intern2/``. Should be just ``https://202.141.80.42/``

**Comment by gautamyadavs** [comment]
it's my college server so they gave me access to that on the internal server and for external access they gave me `http://www.iitg.ac.in/cseweb/wikiproject/`

**Comment by GrahamDumpleton** [comment]
Unless ``http://www.iitg.ac.in/cseweb/wikiproject/`` is setup as a proxy to the separate server, can't see how that helps. If they have set it up for a proxy, you need to know how they are proxying the request.

**Comment by olamide226** [comment]
Im currently expressing the same error any luck??

**Comment by GrahamDumpleton** [comment]
@olamide226 Rather than comment on an existing issue, please create a new issue and provide all the details of your particular problem.
