### ISSUE TITLE
wsgi:error  Truncated or oversized response headers received from daemon process

### ISSUE THREAD

**Issue by tximpa91** [GrahamDumpleton/mod_wsgi#340]
Hi i am encountering a problem recently:

 [wsgi:error] [pid 4305] [client 1.1.1.10:9787] Truncated or oversized response headers received from daemon process
Later i add these line on my configuration in Apache WSGIApplicationGroup %{GLOBAL} and this new error appear.

[wsgi:error] [pid 11012:tid 139747424249600] [remote 88.0.194.133:49835]   """)

Can i have some help.

Kind Regards

**Comment by GrahamDumpleton** [comment]
That doesn't necessarily indicate an error. That could be an errant ``print()`` statement in your code. Anything that comes out in log as ``wsgi:error``, if not an obvious error message from mod_wsgi, is something that your application has written to ``stderr`` or ``stdout``.

Did your web request actually fail?

**Comment by tximpa91** [comment]
Yes the web request is failing with a 500 but now writing in any logs (odd).

receive-buffer-size=nnn

send-buffer-size=nnn

these directives the n is in bytes  or mb ??

**Comment by tximpa91** [comment]
i have django with logs enabled and not writing nothing, this is trigger when i make a get that return a lot of data

**Comment by GrahamDumpleton** [comment]
So you have loggers set up like:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}
```

such that it logs to ``console``?

**Comment by tximpa91** [comment]
Like this
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s  %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': '/home/rateandgrade_app/api.rateandgrade.com/virtualapirestcorp/bin/apirestcorporate/log/error_log.log'
        },
        'altadis_blue': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'simple',
            'filename': '/home/rateandgrade_app/api.rateandgrade.com/virtualapirestcorp/bin/apirestcorporate/log/altadis_blue.log'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file','mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'altadis_blue_logger': {
            'handlers': ['altadis_blue'],
            'level': 'INFO',
        }
    }
}

**Comment by GrahamDumpleton** [comment]
What is ``LogLevel`` set to in Apache configuration? Ensure is set to ``info`` if is set to ``warn``. Then see if mod_wsgi logs anything about daemon processes crashing or being restarted. Also check the main Apache error log (not VirtualHost) for any error messages at time of 500, such as ``Segmentation Fault``.

**Comment by hartwork** [comment]
With `LogLevel info` I get `malloc(): invalid size (unsorted)` in the logs now:

```
[Tue Jan 01 17:56:44.371189 2019] [wsgi:info] [pid 7930] mod_wsgi (pid=7930): Attach interpreter ''.
[Tue Jan 01 17:56:44.373364 2019] [wsgi:info] [pid 7930] [remote xxx.xxx.xxx.xxx:yyyyy] mod_wsgi (pid=7930, process='myapp', application=''): Loading Python script file '/var/www/.../app.wsgi'.
malloc(): invalid size (unsorted)
[Tue Jan 01 17:56:44.393388 2019] [wsgi:error] [pid 7917] [client xxx.xxx.xxx.xxx:yyyyy] Truncated or oversized response headers received from daemon process 'myapp': /var/www/.../app.wsgi
```

**Comment by ned2** [comment]
In case this is helpful for anyone landing on this issue, I was seeing this issue when one of the daemon processes was being killed due to hitting memory limits.

**Comment by GrahamDumpleton** [comment]
Can also be caused by a buggy third party extension module which isn't using Python memory or reference counting APIs properly. Can also be caused by a third party extension module breaking when run in a Python sub interpreter. But was the ``malloc()`` issue even related to the original issue given is new person. Confused.
