### ISSUE TITLE
Apache2 mod_wsgi is ignoring venv

### ISSUE THREAD

**Issue by DefinitelyNotRoot** [GrahamDumpleton/mod_wsgi#344]
Hello,

Sorry but yes, again this issue.
I want to run my application written in Python3.5 on Apache2.4 with mod_wsgi installed by pip3.5 install mod_wsgi. Apache using mod_wsgi still want to use default python in the system and not the one from the venv. @GrahamDumpleton Could you please advise me? How to make it run? 

**Error msg:**
[Wed Jul 18 13:09:15.499413 2018] [wsgi:error] [pid 31454] [client 127.0.0.1:38442] Traceback (most recent call last):
[Wed Jul 18 13:09:15.499490 2018] [wsgi:error] [pid 31454] [client 127.0.0.1:38442]   File "/var/www/FlaskApp/flaskapp.wsgi", line 10, in <module>
[Wed Jul 18 13:09:15.499542 2018] [wsgi:error] [pid 31454] [client 127.0.0.1:38442]     from FlaskApp import app as application
[Wed Jul 18 13:09:15.499573 2018] [wsgi:error] [pid 31454] [client 127.0.0.1:38442]   File "/var/www/FlaskApp/FlaskApp/__init__.py", line 2, in <module>
[Wed Jul 18 13:09:15.499597 2018] [wsgi:error] [pid 31454] [client 127.0.0.1:38442]     from flask import Flask
[Wed Jul 18 13:09:15.499655 2018] [wsgi:error] [pid 31454] [client 127.0.0.1:38442] **ImportError: No module named 'flask'**

**My Settings:**

```
├── FlaskApp
│   ├── __init__.py
│   ├── static
│   ├── templates
│   └── yourenvironment
│       ├── bin
│       ├── include
│       ├── lib
│       ├── lib64 -> lib
│       ├── pip-selfcheck.json
│       ├── pyvenv.cfg
│       └── share
└── flaskapp.wsgi
```

cat FlaskApp.conf 
```
<VirtualHost *:80>
        ServerName mywebsite.com
        ServerAdmin admin@mywebsite.com
        WSGIScriptAlias / /var/www/FlaskApp/flaskapp.wsgi
        <Directory /var/www/FlaskApp/FlaskApp/>
        	Require all granted
	</Directory>
        Alias /static /var/www/FlaskApp/FlaskApp/static
        <Directory /var/www/FlaskApp/FlaskApp/static/>
            Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        WSGIDaemonProcess FlaskApp python-home=/var/www/FlaskApp/FlaskApp/yourenvironment python-path=/var/www/FlaskApp/FlaskApp/yourenvironment/lib/python3.5/site-packages
</VirtualHost>
```

cat **mods-enabled/wsgi.load** 
```
LoadModule wsgi_module "/usr/lib/apache2/modules/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"

```
pip3 install mod_wsgi
`Requirement already satisfied: mod_wsgi in /usr/local/lib/python3.5/dist-packages (4.6.4)`

mod_wsgi-express module-config
```
LoadModule wsgi_module "/usr/local/lib/python3.5/dist-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"
```

(**yourenvironment**)  python3 
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>> exit()
```
(yourenvironment)  

cat flaskapp.wsgi 
```
#!/var/www/FlaskApp/FlaskApp/yourenvironment/bin/python3                                                        

import sys
import logging
logging.basicConfig(stream=sys.stderr)
sys.path.insert(0,"/var/www/FlaskApp/")
print(sys.path)
print(sys.prefix)

from FlaskApp import app as application
application.secret_key = 'Add your secret key'

```

cat __init__.py 
```
#!/var/www/FlaskApp/FlaskApp/yourenvironment/bin/python3
from flask import Flask
app = Flask(__name__)
@app.route("/")
def hello():
    return "Please, please work!"
if __name__ == "__main__":
    app.run()
```

**Comment by DefinitelyNotRoot** [comment]
I created virtual env with python -m venv before, and now I just tried with virtualenv and it is working.

**Comment by cr-solutions** [comment]
I have the same issue with python 3.10 on Ubuntu.
Any solution for this?

**Comment by GrahamDumpleton** [comment]
@cr-solutions Please create a new issue and properly describe your specific issue and provide details about the directory used for the virtual environment, what mod_wsgi configuration you used and what error you are getting, where error messages were displayed and what exactly they were, etc. It is impossible to guess without knowing such details for your case.
