### ISSUE TITLE
by entering  command mod_wsgi-express module-config i am getting this error

### ISSUE THREAD

**Issue by opteamix-pkumar** [GrahamDumpleton/mod_wsgi#345]
C:\Users\pkumar>mod_wsgi-express module-config
Traceback (most recent call last):
  File "e:\pythonpro\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\pythonpro\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\pythonpro\Scripts\mod_wsgi-express.exe\__main__.py", line 5, in <module>
  File "e:\pythonpro\lib\site-packages\mod_wsgi\server\__init__.py", line 24, in <module>
    from . import apxs_config
  File "e:\pythonpro\lib\site-packages\mod_wsgi\server\apxs_config.py", line 27
    LIBEXECDIR = 'C:\Users\pkumar\Desktop\servers\Apache24/lib'
                ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by opteamix-pkumar** [comment]
hey git not allowing to upload a python file so i am just copy and paste inside a text file
[apxs_config.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2219041/apxs_config.txt)

**Comment by GrahamDumpleton** [comment]
Did you set ``MOD_WSGI_APACHE_ROOTDIR`` environment variable? If you did, you must use forward slashes, not back slashes in the path name.

**Comment by opteamix-pkumar** [comment]
hey fine now i am not getting this error but i am getting this? what is this?

C:\Users\pkumar>mod_wsgi-express module-config
LoadFile "e:/pythonpro/python36.dll"
LoadModule wsgi_module "e:/pythonpro/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "e:/pythonpro"

**Comment by GrahamDumpleton** [comment]
That is what you need to copy into the Apache configuration file to load the mod_wsgi module. You then need to configure Apache with details of your WSGI application.

See:

* https://pypi.org/project/mod_wsgi/

It explains the ``module-config`` step at the end.

How you configure it for your WSGI application then depends on what framework you may be using.

For a hello world application, which is always a good idea to test with first, see:

* http://modwsgi.readthedocs.io/en/develop/user-guides/quick-configuration-guide.html

**Comment by opteamix-pkumar** [comment]
i have to paste this complete thing in Apache httpd.conf file????

LoadFile "e:/pythonpro/python36.dll"
LoadModule wsgi_module "e:/pythonpro/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "e:/pythonpro"

**Comment by GrahamDumpleton** [comment]
Yes. It is the instructions to Apache as to how to load the Python library and then the mod_wsgi module. The last line is so Python knows where your Python installation is located.

You still then have to configure things to know about your WSGI application as the last link described.

**Comment by opteamix-pkumar** [comment]
hi this complete thing i pasted in httpd.conf file but when i am  running http://localhost:8080/  i am getting  
Forbidden
You don't have permission to access / on this server.
i am  trying to configure django project with apache

LoadFile "e:/pythonpro/python36.dll"
LoadModule wsgi_module "e:/pythonpro/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "e:/pythonpro"


WSGIScriptAlias / "C/Users/pkumar/Desktop/SDP/workspace/MyProjects/SDP/wsgi.py"
WSGIPythonHome  "C:/Users/pkumar/Desktop/SDP/workspace/sdp-site"
WSGIPythonPath "C:/Users/pkumar/Desktop/SDP/workspace/MyProjects"

<Directory "C:/Users/pkumar/Desktop/SDP/workspace/MyProjects/SDP" >
<Files wsgi.py>
Require all granted

</Files>
</Directory>

**Comment by opteamix-pkumar** [comment]
hi man can you look once my httpd confg file? i am windows 10
[httpd.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2226964/httpd.txt)

**Comment by GrahamDumpleton** [comment]
You need to restore the ``httpd.conf`` file back to what it was and add the extra bits for mod_wsgi at the end. The default ``httpd.conf`` file sets up a lot of defaults which are needed for things to work properly.

**Comment by opteamix-pkumar** [comment]
i restore the file what else i should i add it's not working for me again the same error
[httpd.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2227432/httpd.txt)

LoadFile "e:/pythonpro/python36.dll"
LoadModule wsgi_module "e:/pythonpro/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "e:/pythonpro"

WSGIScriptAlias / "C/Users/pkumar/Desktop/SDP/workspace/MyProjects/SDP/wsgi.py"
WSGIPythonHome  "C:/Users/pkumar/Desktop/SDP/workspace/sdp-site"
WSGIPythonPath "C:/Users/pkumar/Desktop/SDP/workspace/MyProjects"

<Directory "C:/Users/pkumar/Desktop/SDP/workspace/MyProjects/SDP" >
<Files wsgi.py>
Require all granted
</Files>
</Directory>

**Comment by GrahamDumpleton** [comment]
Next thing is to add to the very end of the file some garbage characters to cause a syntax error when it is parsed. A line which literally says ``GARBAGE`` will do. Then restart Apache and confirm that Apache fails to restart. This will confirm the file is actually being read.

Also, how is Apache being run. Are you running it as yourself, or is it being run by some system service?

**Comment by opteamix-pkumar** [comment]
ya when i add the garabage in the end of file that time Apache service fails to start.
i am runnning Apachev services by going to windows services
<img width="960" alt="windows service" src="https://user-images.githubusercontent.com/18262170/43195377-8858226a-9022-11e8-9b1a-260a996c4784.png">

**Comment by GrahamDumpleton** [comment]
The issue is likely that the service can't read files out of your user directory. Suggest you try creating the virtual environment, and application code in directory outside of your user directory.

**Comment by opteamix-pkumar** [comment]
oh thanks man its working thanks lot

**Comment by nishtha03** [comment]
Hey i am facing same issue..could you pls help me out

**Comment by GrahamDumpleton** [comment]
Create a new issue and provide the details for your specific problem from scratch. When you ask on an existing issue and provide no details about your specific case it isn't possible to help you. Your issue may not even be the same thing.

**Comment by nishtha03** [comment]
LoadModule wsgi_module "c:/users/bisp 123/appdata/local/programs/python/python37-32/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win32.pyd"
WSGIScriptAlias / "c:/xampp/htdocs/Integration/Integration/wsgi.py"
WSGIPythonHome "c:/users/bisp 123/appdata/local/programs/python/python37-32"
WSGIPythonPath "c:/xampp/htdocs/Integration"



Alias /media/c:/xampp/htdocs/Integration/media/
Alias /static/c:/xampp/htdocs/Integration/upload/static/

<Directory c:/xampp/htdocs/Integration/static>  Require all granted</Directory>

<Directory c:/xampp/htdocs/Integration/media>  Require all granted</Directory>

<Directory c:/xampp/htdocs/Integration> 
<files wsgi.py> 
Require all granted</files>
</Directory>

this is my http.conf file code for python..after adding this my xampp server is stop

**Comment by GrahamDumpleton** [comment]
I asked if you could create a new issue, not add to this one. What you added also doesn't explain your specific problem, with the errors you are getting and what you are doing at the time to get the errors. So please create a new issue and add all relevant information, the configuration alone isn't enough to tell me anything about your problem.

**Comment by GrahamDumpleton** [comment]
One thing I will say, Python doesn't usually like having spaces in your user name ``bisp 123``. It will break things. So that may well be your problem.

**Comment by Tirumalesh8686** [comment]
I have a very similar doubt.....

(base) D:\Tirumalesh\dev\myapp\Flask\Scripts>mod_wsgi-express module-config
Traceback (most recent call last):
  File "c:\users\lucid\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lucid\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Tirumalesh\dev\myapp\Flask\Scripts\mod_wsgi-express.exe\__main__.py",
 line 5, in <module>
  File "d:\tirumalesh\dev\myapp\flask\lib\site-packages\mod_wsgi\server\__init__
.py", line 25, in <module>
    from . import apxs_config
  File "d:\tirumalesh\dev\myapp\flask\lib\site-packages\mod_wsgi\server\apxs_con
fig.py", line 27
    LIBEXECDIR = 'C:\Users\lucid\Apache24/lib'
                ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in positio
n 2-3: truncated \UXXXXXXXX escape


Attach a copy of e:\pythonpro\lib\site-packages\mod_wsgi\server\apxs_config.py. Don't cut and paste content, actually attach it as need to see the raw original.

U have replied saying we need to attach a copy of this,
 where exactly this .py file needs to be copied and in what way is it helping to resolve the issue....

**Comment by nishtha03** [comment]
you need to modify this line

LIBEXECDIR = 'C:\Users\lucid\Apache24/lib'
to
LIBEXECDIR = 'C:/Users/lucid/Apache24/lib'

**Comment by GrahamDumpleton** [comment]
As mentioned above somewhere, when setting `MOD_WSGI_APACHE_ROOTDIR` you must use forward slashes, not back slashes. Re install with `pip` and use `--no-cache-dir` to ensure any pre-built version in the cache is ignored.

**Comment by Tirumalesh8686** [comment]
Hello.....
Iam following this link "https://medium.com/@madumalt/flask-app-deployment-in-windows-apache-server-mod-wsgi-82e1cfeeb2ed" to deploy flask app in windows........

1)Usually this was in my http-vhosts.conf file:

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "${SRVROOT}/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ServerAlias www.dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error.log"
    CustomLog "logs/dummy-host2.example.com-access.log" common
</VirtualHost>

and I added server name, WSGIScriptAlias, directory to it so that it look like this:

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "${SRVROOT}/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ServerAlias www.dummy-host2.example.com

    ServerName localhost:5000	
    WSGIScriptAlias / D:\Tirumalesh\dev\text_basic\index\web.wsgi         
    <Directory D:\Tirumalesh\dev\text_basic\index>                        
		Require all granted
    </Directory>
	
    ErrorLog "logs/dummy-host2.example.com-error.log"
    CustomLog "logs/dummy-host2.example.com-access.log" common
</VirtualHost>

2) and I have added this(below) in my httpd.conf(in the very end of file) which is the output coming from "mod-wsgi-express module-config" and I have included "Include conf/extra/httpd-vhosts.conf" (virtual hosts) in my httpd.conf file

LoadFile "c:/users/lucid/anaconda3/python37.dll"
LoadModule wsgi_module "c:/users/lucid/anaconda3/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "c:/users/lucid/anaconda3"

3)**Next i create a web.wsgi file with the following content** 

import sys
sys.path.insert(0, 'D:\Tirumalesh\dev\text_basic')
from text_basic import app as application

4)And my python file is "text_basic.py" (whose name must be same as my .wsgi file) 

from flask import Flask
 app = Flask(__name__)
 @app.route("/")
 def hello():
     return "Hello World"
 if __name__ == "__main__":
     app.run()

Now how i can check whether my python code in flask app is deployed to apache server
How to check that????

**Comment by Tirumalesh8686** [comment]
> Hey i am facing same issue..could you pls help me out



> you need to modify this line
> 
> LIBEXECDIR = 'C:\Users\lucid\Apache24/lib'
> to
> LIBEXECDIR = 'C:/Users/lucid/Apache24/lib'

Below i have mentioned my another doubt....could u please help me in resolving

**Comment by GrahamDumpleton** [comment]
@Tirumalesh8686 Please create a NEW issue for any issue you are having and don't post followups on a closed issue even if it appears it may be the same, as it could be that it isn't. In the new issue, provide full details on your problem. Also ensure you heeded comment above where if setting `MOD_WSGI_APACHE_ROOTDIR` to specify where Apache is installed, that you use forward slashes, not backward slashes.

**Comment by Chaney08** [comment]
Just wanted to say thanks @GrahamDumpleton for your above responses - Very detailed and helpful, I needed to reinstall mod_wsgi after putting backslashes in path instead of forward slashes, one of your comments above addressed this issue and saved my hair from turning grey.

**Comment by meenabm** [comment]
Hi ..apache is not running after configuring httpd.conf file. I have made sure that my path for root dir has forward slashes. can someone help here

**Comment by GrahamDumpleton** [comment]
@meenabm Please create a new issue with all the details, including what steps you have taken, Apache distro used, Python version, how you installed mod_wsgi, configuration for mod_wsgi used etc. Don't ask new questions as comments on existing issues.
