### ISSUE TITLE
RuntimeError: response has not been started

### ISSUE THREAD

**Issue by Velu-Narasimman** [GrahamDumpleton/mod_wsgi#346]
I am getting this new `[wsgi:error]`  in my apache error log. Actually, I post a form to  a URL  then  from there I redirect the request to another URL.  At that redirection, I am getting this 500 Internal server error in browser. So I checked up my apache for errors, I found the below error, 

`[Fri Jul 27 08:37:02.904727 2018] [wsgi:error] [pid 2034:tid 139830585378560] [remote 172.24.188.116:4836] mod_wsgi (pid=2034): Exception occurred processing WSGI script '/usr/share/trac/trac.wsgi'.
[Fri Jul 27 08:37:02.904799 2018] [wsgi:error] [pid 2034:tid 139830585378560] [remote 172.24.188.116:4836] RuntimeError: response has not been started`

I am not getting what is going wrong here, can anyone help me to fix this?

**Comment by GrahamDumpleton** [comment]
For a plain old WSGI application that means ``start_response()`` was never called with status and headers.
