### ISSUE TITLE
DLL initialization routine failed

### ISSUE THREAD

**Issue by mucuspigboy** [GrahamDumpleton/mod_wsgi#347]
Dear Mr Dumpleton,

I saw your reply to "Apache LoadModule issue #234". I have pretty much the same setup as the original poster, except that I'm using Flask (instead of Django), and mod_wsgi v4.6.4 (instead of 4.5.20). As you can guess, I'm also having the same problem.

Based on your reply, I changed the value of LoadModule so that "None" became ".pyd". Then, I got this error when I checked the syntax of the httpd.conf file:

> httpd -t
httpd: Syntax error on line 185 of C:/Apache24/conf/httpd.conf: Cannot load c:/python27/lib/site-packages/mod_wsgi/server/mod_wsgi.pyd into server: A dynamic link library (DLL) initialization routine failed.

Is this what you were referring to when you said "Even if using correct architecture for each, is a chance will still not work as there is Python 2.7 requires everything to be compiled with VC9 compiler, but Apache likely isn't as is hard to get Apache distro that still uses VC9."

Or am I doing something else inane?

Thanks,
p

**Comment by GrahamDumpleton** [comment]
I can't say for sure, but I would expect it is more likely to fail later in use due to compiler version differences than on loading of the module. So your issue could be something entirely different. I actually don't recollect ever seeing that specific error message before, unless the OS is being better about its messages these days.

Any reason you can't just use Python 3.6?

**Comment by mucuspigboy** [comment]
> Any reason you can't just use Python 3.6?

No, apart from fear of the unknown :)

Anyway, I ended up taking the plunge and used Python 3.6, and that solved the problem. You said in one of your earlier posts that you weren't too familiar with setting things up on Windows, so allow me to share my experience with you in case somebody comes to you with the same problem.

Installing Python36 is not a problem - but the hurdle is that in all of the online docs, it says something like "...make sure you install Python for ALL users..."

The f**king problem on Windows is that the installer gives you an option that says "Install launcher for all users (recommended)". Of course, you will check that option, and the installer happily goes about its business. The confusing part is that if you do it this way, it will put Python in your /users/usr/blah/blah/blah directory - usually NOT where stuff for ALL users is put (those are usually put in C:\Program Files).

If you uninstall and reinstall - this time explicitly putting it in C:\Program Files - you will get Python functionality, but run into a whole world of problems when you do pip install mod_wsgi (i.e. permission problems).

To compound things, the installer also has a "custom install" option. If you go into that, there's an explicit checkbox that says "Install for all users". If you do this, you will also run into permission problems when you try to install mod_wsgi.

Eventually, I just ended up doing it the dumb default way, and that finally let me successfully pip install mod_wsgi (I had to download .NET 4.5.1 and Visual Studio C++ compilers, though - but I think that's a problem with my system).

Sorry for taking up too much of your time. Your taking the time to write back is much appreciated!
Thanks,
p

**Comment by GrahamDumpleton** [comment]
On the all users issue, the installer has likely changed. I haven't done it myself for many Python versions. Those comments were probably how things were back in Python 2.6.

You always need the compiler to match your Python version as I don't supply binary wheels as is too hard. There are binary wheels at:

* https://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

They just aren't mine. They also can't be pip installed from that location and instead need to downloaded and then run something like ``pip install ./mod_wsgi‑4.6.4+ap24vc14‑cp36‑cp36m‑win_amd64.whl``.
