### ISSUE TITLE
mod_wsgi-express not installed with mod_wsgi ?

### ISSUE THREAD

**Issue by AnashaDevil** [GrahamDumpleton/mod_wsgi#349]
Hi all,

I've followed this tut to install mod_wsgi on window, for my WAMP environment : 

`C:\Users\Annabelle>py -m pip install mod_wsgi
Collecting mod_wsgi
  Using cached https://files.pythonhosted.org/packages/9e/37/dd336068ece37c43957aa337f25c59a9a6afa98086e5507908a2d21ab807/mod_wsgi-4.6.4.tar.gz
Installing collected packages: mod-wsgi
  Running setup.py install for mod-wsgi ... done
Successfully installed mod-wsgi-4.6.4`

As mentioned here and in the official doc of mod_wsgi

> To use the Apache mod_wsgi module from where pip install placed it, run the command mod_wsgi-express module-config.

Her I go then : 
`C:\Users\Annabelle>mod_wsgi-express module-config
'mod_wsgi-express' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.`

Soooo... What seemed to be just as simple as that is actually a headache...

I am totally new to python, and I don't even know where to look. I've found the mod_wsgi module in the apache install folder, but no *.so file, and nothing refering to mod_wsgi-express...

What am I supposed to install / do now ?

Thanks for your help :)

**Comment by GrahamDumpleton** [comment]
Sorry, this slipped through the cracks and I missed it as I was on overseas trip at the time. The error indicates that you don't have your path set correctly so that programs installed in the scripts directory of Python are found when run.

**Comment by williamguomd** [comment]
Hi Graham, I am experienced the same issue when try to deploy a flask web service onto a Windows server. You said "you don't have your path set correctly so that programs installed in the scripts directory of Python are found when run.", could you be specific how should I set the path correctly?

Thanks!

**Comment by GrahamDumpleton** [comment]
I don't use Windows, so no I can't help beyond that. All I can suggest is that you try uninstalling and reinstalling Python and checking Python installation docs to see whether you did all you were meant to. Beyond that suggestion can only suggest you ask on StackOverflow. Explain your problem in full there, indicating that scripts installed when installing a Python package aren't then being found when run.

**Comment by gyvasileciorna** [comment]
have same problem,  did someone found the solution on windows?

**Comment by gyvasileciorna** [comment]
actually I had a typo: I typed mod-wsgi-express module-config instead of mod_wsgi-express module-config. P.S related to first question you need to run this command while on the site-packages folder. You need to cd into that directory first. Hope it helps!
