### ISSUE TITLE
Silent Limit of 107 Characters on Socket Path causes Weird Errors

### ISSUE THREAD

**Issue by drcapulet** [GrahamDumpleton/mod_wsgi#35]
Due to the `UNIX_PATH_MAX` defined on the `struct sockaddr_un`:

```
#define UNIX_PATH_MAX    108

struct sockaddr_un {
    sa_family_t sun_family;               /* AF_UNIX */
    char        sun_path[UNIX_PATH_MAX];  /* pathname */
};
```

There is a limit of 107 (108 including the null byte) on the length of a path for a socket - but when the [bind](https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/mod_wsgi.c#L7302) is called, the silently truncated path starts causing problems, and you start seeing `-1 EADDRINUSE (Address already in use)` errors in the strace.

This happens when `WSGISocketPrefix` is set to a path that might be shorter than 107 characters, but can be longer once the extra information is added (like pid and extension). However the log outputs the full path when it says it can't bind to the socket. As a result, Apache just hangs when talking to WSGI.

This only affects Daemon mode.

While the underlying system can't be changed, it'd probably be useful to somehow catch this weird edge case.

Here's the `strace` output if you're curious:

```
$ strace -f ./bin/apache
...
7619  bind(8, {sa_family=AF_FILE, path="/some-really-long-path-that-hits-a-linux-max-and-that-also-happens-to-include-a-gitsha-digest/apache/run/ws"}, 110) = -1 EADDRINUSE (Address already in use)
7619  unlink("/some-really-long-path-that-hits-a-linux-max-and-that-also-happens-to-include-a-gitsha-digest/apache/run/wsgitest.7619.0.1.sock") = -1 ENOENT (No such file or directory)
7619  bind(8, {sa_family=AF_FILE, path="/some-really-long-path-that-hits-a-linux-max-and-that-also-happens-to-include-a-gitsha-digest/apache/run/ws"}, 110) = -1 EADDRINUSE (Address already in use)
7633  connect(11, {sa_family=AF_FILE, path="/some-really-long-path-that-hits-a-linux-max-and-that-also-happens-to-include-a-gitsha-digest/apache/run/ws"}, 110) = -1 ECONNREFUSED (Connection refused)
...
```

And the log:

```
src/server/mod_wsgi.c(7267): mod_wsgi (pid=7370): Socket for 'graphite-w-otsdb' is '/some-really-long-path-that-hits-a-linux-max-and-that-also-happens-to-include-a-gitsha-digest/apache/run/wsgi.7370.0.1.sock'.
(98)Address already in use: mod_wsgi (pid=7370): Removing stale unix domain socket '/some-really-long-path-that-hits-a-linux-max-and-that-also-happens-to-include-a-gitsha-digest/apache/run/wsgi.7370.0.1.sock'.
(98)Address already in use: mod_wsgi (pid=7370): Couldn't bind unix domain socket '/some-really-long-path-that-hits-a-linux-max-and-that-also-happens-to-include-a-gitsha-digest/apache/run/wsgi.7370.0.1.sock'.
```

**Comment by GrahamDumpleton** [comment]
Closing this. Finally added updated warnings in https://github.com/GrahamDumpleton/mod_wsgi/commit/1af480a60d538802ba1173ea3c920371ecaa6fbc. Will be released in 4.5.25.
