### ISSUE TITLE
Strings are incorrectly escaped when logged/output via mod_wsgi.Log

### ISSUE THREAD

**Issue by SpoonMeiser** [GrahamDumpleton/mod_wsgi#350]
mod_wsgi arranges for `sys.stderr` to refer to a `mod_wsgi.Log` instance. Text written to this gets output as though its `repr` was written, which causes it to appear as though it were double-escaped.

Simple reproducer:

*app.wsgi:*
```
import sys,json


def application(environ, start_response):
    log_message = json.dumps({'test': '"test"'})
    sys.stderr.write(log_message)

    status = '200 OK'
    output = 'Hello World!\n'
    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)
    return [output]
```

This is simply the 'hello world' app with the minor addition of writing a JSON string written to `sys.stderr` (which will actually be a `mod_wsgi.Log`)

*Dockerfile:*
```
FROM grahamdumpleton/mod-wsgi-docker:python-2.7-onbuild
CMD [ "app.wsgi" ]
```

When run, and accessed, we see this output:

```
[Mon Aug 13 16:09:44.387244 2018] [wsgi:error] [pid 17:tid 139669426108160] [remote 172.17.0.1:59464] {"test": "\\"test\\""}
```

The JSON string is no longer valid JSON as it's been double-escaped. The actual string should be `{"test": "\"test\""}` - there is no reason for the backslashes to be escaped in the output.

We're deploying an application that uses structured logging that is consumed by an ELK stack. _Most_ log lines are perfectly fine, but when examples like I provided here happen, usually strings containing double quotes, we end up with broken JSON that cannot be parsed.

**Comment by GrahamDumpleton** [comment]
Apache sends log output through this:

```
AP_DECLARE(apr_size_t) ap_escape_errorlog_item(char *dest, const char *source,
                                               apr_size_t buflen)
{
    unsigned char *d, *ep;
    const unsigned char *s;

    if (!source || !buflen) { /* be safe */
        return 0;
    }

    d = (unsigned char *)dest;
    s = (const unsigned char *)source;
    ep = d + buflen - 1;

    for (; d < ep && *s; ++s) {

        if (TEST_CHAR(*s, T_ESCAPE_LOGITEM)) {
            *d++ = '\\';
            if (d >= ep) {
                --d;
                break;
            }

            switch(*s) {
            case '\b':
                *d++ = 'b';
                break;
            case '\n':
                *d++ = 'n';
                break;
            case '\r':
                *d++ = 'r';
                break;
            case '\t':
                *d++ = 't';
                break;
            case '\v':
                *d++ = 'v';
                break;
            case '\\':
                *d++ = *s;
                break;
            case '"': /* no need for this in error log */
                d[-1] = *s;
                break;
            default:
                if (d >= ep - 2) {
                    ep = --d; /* break the for loop as well */
                    break;
                }
                c2x(*s, 'x', d);
                d += 3;
            }
        }
        else {
            *d++ = *s;
        }
    }
    *d = '\0';

    return (d - (unsigned char *)dest);
}
```

Apache regards inclusion of certain characters in the log file as problematic as far as security goes. I don't know the reasons why, but there is a note that gives a clue in:

* http://httpd.apache.org/docs/current/mod/mod_log_config.html

where is says:

> For security reasons, starting with version 2.0.46, non-printable and other special characters in %r, %i and %o are escaped using \xhh sequences, where hh stands for the hexadecimal representation of the raw byte. Exceptions from this rule are " and \, which are escaped by prepending a backslash, and all whitespace characters, which are written in their C-style notation (\n, \t, etc). In versions prior to 2.0.46, no escaping was performed on these strings so you had to be quite careful when dealing with raw log files.

This relates to use of special format codes, but it is applying the same transformation to those as has previously done for log messages themselves. So for whatever reason, these characters are regarded as being unsafe for some reason.

BTW, you have to be careful of what you log and expect to be able to parse as Apache logging will truncate messages at about 8000 characters. So you can't have really long lines and expect to get it all.

Where logging is important, you are better off using Python logging module and direct logging module messages to some special logging service directly.

**Comment by SpoonMeiser** [comment]
We do use python logging - I just wrote directly to stderr here for the sake of brevity.

As far as I understand it, logging to stderr is pretty much standard for containerised applications, and doing so lets container orchestration platforms consume logs from the things they're running in a consistent way (`docker logs`, for example, will show you the output from the contained application).

For our case, we want to be able to link python logging to stderr. We don't have any benefit from Apache being in the loop in this case (error log format is just `%M`). However, I don't know if this is possible using `mod_wsgi`?

I guess the traditional use case of `mod_wsgi` this behaviour makes sense. Maybe this issue would be better as a feature request on `mod_wsgi-docker` to provide some way of logging directly to stderr without involving Apache. Unless there already is a way I'm not aware of?

**Comment by GrahamDumpleton** [comment]
Hmmm, ``mod_wsgi-docker`` image isn't being looked after really any more.

If you need to send to stdout/stderr of the container, bypassing Apache, you would need to open and write to:

```
/proc/self/fd/1
/proc/self/fd/2
```

**Comment by GrahamDumpleton** [comment]
Whoops, wrong. Meant:

```
/proc/1/fd/1
/proc/1/fd/2
```

**Comment by GrahamDumpleton** [comment]
Actually, is probably safer to use:

```
/proc/self/fd/1
/proc/self/fd/2
```

This is because under Kubernetes, if you have multiple containers in a pod, the process ID 1 is actually a mini init process manager which sits above all containers. I don't remember how the pid namespaces work and whether that process would have an entry under ``/proc``. So safer to use ``/proc/self``. This should still be fine as Apache output still get mapped to container stdout/stderr, unless something strange being done to redirect output from Apache to a file, independent of its own logging file setup.
