### ISSUE TITLE
[wsgi:error] [pid 2902] [client 89.64.22.95:40574] Timeout when reading response headers from daemon process...

### ISSUE THREAD

**Issue by pwozniak1986** [GrahamDumpleton/mod_wsgi#352]
I'm running apache 2.4.10 under debian 8.11.

I have some webapges running in a typical way served on different domains. Each site has its own folder in var/www/html. Apache maps domain to right directory by .conf files inside sites-enabled folder with a virtual host setting.

For one of domains (i.e. mydomain.com) i wanted to add a django app in a subdomain (my_app.mydomain.com). App project is located in /home/my_project directory.

For this project I utilize virtual environment with python 3.4. Using this env I installed django and build mod-wsgi from sources.

I added another .conf file to apaches sites-enabled folder with a VirtualHost *:80 node:
```
ServerName my_app.mydomain.com
ServerAlias mydomain.com
ServerAdmin webmaster@example.com

DocumentRoot /home/my_project/my_app

WSGIDaemonProcess stage_app processes=2 threads=15 python-home=/home/venv/venv/lib/python3.4/site-packages python-path=/home/my_project/my_app
WSGIProcessGroup stage_app

WSGIScriptAlias / /home/my_project/my_project/wsgi.py process-group=my_app

    <Directory /home/my_project/my_project/>
        Require all granted
    </Directory>

    Alias /media/ /home/my_project/my_app/media/

    <Directory /home/my_project/my_app>
        Require all granted
    </Directory>

 ErrorLog /home/my_project/error.log
 CustomLog /home/my_project/access.log combined
```

I have added following lines to apache2.conf 
```
LoadModule wsgi_module modules/mod_wsgi.so
WSGIApplicationGroup %{GLOBAL}
```
Also checked several other options but with no luck... I'm always getting timout error:
`[wsgi:error] [pid 7396] [client 89.64.22.95:40409] Timeout when reading response headers from daemon process 'my_app': /home/my_project/my_project/wsgi.py`

wsgi.py is autogenerated by django. I didn`t add anything there

**Comment by GrahamDumpleton** [comment]
Sorry for slow reply, totally missed this in amongst a few overseas trips been on over last few months.

Did you resolve this.

One thing wrong with your config is that you are using:

```
python-home=/home/venv/venv/lib/python3.4/site-packages
```

This is wrong.

The value of ``python-home`` should not be the ``site-packages`` directory. It should have same as ``sys.prefix`` for Python when run. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

As to the timeout, it means your application is taking to long to handle the request. This could be because it deadlocked, or is waiting on backend service.

What is ``Timeout`` directive set to in your configuration?

**Comment by erronny** [comment]
i face same issues

[Sat Oct 02 21:44:33.724702 2021] [wsgi:error] [pid 218181:tid 139902742185728] [client 157.35.8.244:42096] Timeout when reading response headers from daemon process 'main': /var/www/public_html/main/wsgi.py
[Sat Oct 02 21:45:04.190714 2021] [wsgi:error] [pid 218181:tid 139902733793024] [client 157.35.8.244:42094] Timeout when reading response headers from daemon process 'main': /var/www/public_html/main/wsgi.py
[Sat Oct 02 21:46:12.212718 2021] [wsgi:error] [pid 218552:tid 140106125014784] [client 157.35.8.244:42140] Timeout when reading response headers from daemon process 'main': /var/www/public_html/main/wsgi.py
[Sat Oct 02 21:47:12.775728 2021] [wsgi:error] [pid 218552:tid 140106116622080] [client 157.35.8.244:42140] Timeout when reading response headers from daemon process 'main': /var/www/public_html/main/wsgi.py, referer: http://3.109.245.1/

**Comment by GrahamDumpleton** [comment]
@erronny This issue is closed. Please create a new one which includes more information about how you are using mod_wsgi, the configuration used etc. It is impossible to tell anything just from the information that you have provided.

**Comment by erronny** [comment]
thanks man this article solve my problem
https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

the problem was I put python virtual env file in another directory. 
It solves when i put my virtual env folder in my root directory. 
restarted apache server 
now it running
