### ISSUE TITLE
Failed to exec Python script file

### ISSUE THREAD

**Issue by iwinjobi19** [GrahamDumpleton/mod_wsgi#354]
Hi Graham,

I have looked through as many reported issues you helped with, but none fixed my problem so far.
I have included the log information from the apache error.log.

[Sun Aug 26 19:46:16.224975 2018] [mpm_prefork:notice] [pid 27726] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.6.4 Python/3.7 configured -- resuming normal operations
[Sun Aug 26 19:46:16.225059 2018] [core:notice] [pid 27726] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 26 19:46:23.637294 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416] mod_wsgi (pid=27729): Failed to exec Python script file '/var/www/newproject/myproject/myproject/wsgi.py'.
[Sun Aug 26 19:46:23.637351 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416] mod_wsgi (pid=27729): Exception occurred processing WSGI script '/var/www/newproject/myproject/myproject/wsgi.py'.
[Sun Aug 26 19:46:23.637788 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416] Traceback (most recent call last):
[Sun Aug 26 19:46:23.637837 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "/var/www/newproject/myproject/myproject/wsgi.py", line 16, in <module>
[Sun Aug 26 19:46:23.637842 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]     application = get_wsgi_application()
[Sun Aug 26 19:46:23.637849 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Aug 26 19:46:23.637852 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]     django.setup(set_prefix=False)
[Sun Aug 26 19:46:23.637857 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
[Sun Aug 26 19:46:23.637860 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sun Aug 26 19:46:23.637865 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Sun Aug 26 19:46:23.637868 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]     self._setup(name)
[Sun Aug 26 19:46:23.637873 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
[Sun Aug 26 19:46:23.637876 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]     self._wrapped = Settings(settings_module)
[Sun Aug 26 19:46:23.637880 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
[Sun Aug 26 19:46:23.637883 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Aug 26 19:46:23.637888 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "/var/www/newproject/python37/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sun Aug 26 19:46:23.637890 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]     return _bootstrap._gcd_import(name[level:], package, level)
[Sun Aug 26 19:46:23.637895 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sun Aug 26 19:46:23.637900 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sun Aug 26 19:46:23.637905 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Sun Aug 26 19:46:23.637910 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Sun Aug 26 19:46:23.637915 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sun Aug 26 19:46:23.637920 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sun Aug 26 19:46:23.637925 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sun Aug 26 19:46:23.637959 2018] [wsgi:error] [pid 27729] [remote 127.0.0.1:52416] ModuleNotFoundError: No module named 'myproject'
[Sun Aug 26 19:46:29.709120 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418] mod_wsgi (pid=27730): Failed to exec Python script file '/var/www/newproject/myproject/myproject/wsgi.py'.
[Sun Aug 26 19:46:29.709171 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418] mod_wsgi (pid=27730): Exception occurred processing WSGI script '/var/www/newproject/myproject/myproject/wsgi.py'.
[Sun Aug 26 19:46:29.709668 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418] Traceback (most recent call last):
[Sun Aug 26 19:46:29.709745 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "/var/www/newproject/myproject/myproject/wsgi.py", line 16, in <module>
[Sun Aug 26 19:46:29.709752 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]     application = get_wsgi_application()
[Sun Aug 26 19:46:29.709760 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Aug 26 19:46:29.709763 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]     django.setup(set_prefix=False)
[Sun Aug 26 19:46:29.709769 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
[Sun Aug 26 19:46:29.709772 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sun Aug 26 19:46:29.709778 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Sun Aug 26 19:46:29.709781 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]     self._setup(name)
[Sun Aug 26 19:46:29.709786 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
[Sun Aug 26 19:46:29.709789 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]     self._wrapped = Settings(settings_module)
[Sun Aug 26 19:46:29.709794 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "/var/www/newproject/python37/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
[Sun Aug 26 19:46:29.709797 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Aug 26 19:46:29.709802 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "/var/www/newproject/python37/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sun Aug 26 19:46:29.709805 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]     return _bootstrap._gcd_import(name[level:], package, level)
[Sun Aug 26 19:46:29.709810 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sun Aug 26 19:46:29.709815 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sun Aug 26 19:46:29.709820 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Sun Aug 26 19:46:29.709826 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Sun Aug 26 19:46:29.709831 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sun Aug 26 19:46:29.709836 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sun Aug 26 19:46:29.709841 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sun Aug 26 19:46:29.709884 2018] [wsgi:error] [pid 27730] [remote 127.0.0.1:52418] ModuleNotFoundError: No module named 'myproject'

**Comment by GrahamDumpleton** [comment]
How are you setting ``sys.path`` so that mod_wsgi knows where your project is?

Show your mod_wsgi configuration from Apache config file.

**Comment by iwinjobi19** [comment]
<IfModule mod_ssl.c>
<VirtualHost *:443>

	ServerName www.mysite
	ServerAdmin webmaster@mysite.com
	ServerAlias mysite


	DocumentRoot /var/www/mysite
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	Alias /static var/www/newproject/static
	


	<Directory /var/www/newproject/static>
        Require all granted
    </Directory>

    <Directory /var/www/newproject/myproject/myproject>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
        
    <Directory /var/www/newproject/myproject>
        Require all granted
    </Directory>


	WSGIDaemonProcess mysite processes=2 threads=15 python-home=var/www/newproject/python37 user=www-data group=www-data 
	WSGIProcessGroup mysite

	WSGIScriptAlias /myapp /var/www/wsgi-scripts/app.wsgi 
    WSGIScriptAlias / /var/www/newproject/myproject/myproject/wsgi.py
    

RewriteEngine on
ServerAlias mysite
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/mysite/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mysite/privkey.pem
</VirtualHost>
</IfModule>

**Comment by GrahamDumpleton** [comment]
You are not setting ``python-path`` option to ``WSGIDaemonProcess`` to tell it where you project code is, as explained in Django docs.

* https://docs.djangoproject.com/en/2.1/howto/deployment/wsgi/modwsgi/#using-mod-wsgi-daemon-mode

So you likely need to add:

```
python-path=/var/www/newproject/myproject
```

BTW, you don't need:

```
user=www-data group=www-data
```

That will be default anyway.

**Comment by iwinjobi19** [comment]
Thank you. Works now.
