### ISSUE TITLE
cannot run pyvirtualdisplay

### ISSUE THREAD

**Issue by Swordyjohn** [GrahamDumpleton/mod_wsgi#355]
I am trying to run pyvirtualdisplay as part of a WSGI app. I have Xfvb installed, my 000-default.conf file:

<VirtualHost *:80>
    # The ServerName directive sets the request scheme, hostname and port that
    # the server uses to identify itself. This is used when creating
    # redirection URLs. In the context of virtual hosts, the ServerName
    # specifies what hostname must appear in the request's Host: header to
    # match this virtual host. For the default virtual host (this file) this
    # value is not decisive as it is used as a last resort host regardless.
    # However, you must set it for any further virtual host explicitly.
    #ServerName www.example.com

    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    WSGIDaemonProcess flaskapp user=ubuntu threads=5
    WSGIScriptAlias / /var/www/html/flaskapp/flaskapp.wsgi
    <Directory flaskapp>
        WSGIProcessGroup flaskapp
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
    # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
    # error, crit, alert, emerg.
    # It is also possible to configure the loglevel for particular
    # modules, e.g.
    #LogLevel info ssl:warn

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    # For most configuration files from conf-available/, which are
    # enabled or disabled at a global level, it is possible to
    # include a line for only one particular virtual host. For example the
    # following line enables the CGI configuration for this host only
    # after it has been globally disabled with "a2disconf".
    #Include conf-available/serve-cgi-bin.conf
</VirtualHost>
    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet

my code :

    from flask import Flask
    from pyvirtualdisplay import Display

    app = Flask(__name__)

    @app.route('/')
    def crawl_sc():
        display = Display(visible=0, size=(1920, 999))
        display.start()
        display.stop()
        return 'ran'
    if __name__ == '__main__':
        app.run(debug=True)`
when I run this through the WSGI it just continually loads, but there are no errors in the error.log. I am using an AWS EC2 with Ubuntu 16.04 and Apache 2.4.18, mod_wsgi 4.6.4 & Python 3.6.

**Comment by GrahamDumpleton** [comment]
At a guess it may be because you have:

```
<Directory flaskapp>
    WSGIProcessGroup flaskapp
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
</Directory>
```

That should for a start be:

```
<Directory /var/www/html/flaskapp>
    WSGIProcessGroup flaskapp
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
</Directory>
```

It is possibly trying to load in embedded mode and not the main interpreter due to being wrong, and the module being imported will not work except in main interpreter and hangs.

Suggest uncomment the ``LogLevel`` line so ``info`` is used. That way it will show if the WSGI script is being loaded and in which mode/interpreter context.

**Comment by Swordyjohn** [comment]
Thank you Graham! That did it, could not get logLevel info to work but changing the flaskapp to /var/www/html/flaskapp did the trick! I think i need to use an EC2 with larger compute power however, but you solved my problem. Thank you!
