### ISSUE TITLE
Apache client denied error (AH01630) although content is served correctly. Same problem as  #272

### ISSUE THREAD

**Issue by qlands** [GrahamDumpleton/mod_wsgi#356]
I have the same problem described in #272 However I am using proxy pass from HTTPS to HTTP.
I am using mod-wsgi==4.6.4. Here are some details:

**Configuration of mod-wsgi-express:**
`mod_wsgi-express setup-server /opt/climmob/apache.wsgi --user www-data --group www-data --server-root /opt/climmob_wsgi --port 6543 --host 172.31.41.128 --mount-point /climmob3 --trust-proxy-header X-Forwarded-Port --trust-proxy-header X-Forwarded-Scheme`

**Apache configuration:**
```
<VirtualHost *:443>
       ServerAdmin webmaster@localhost
       DocumentRoot /var/www/html
       ErrorLog ${APACHE_LOG_DIR}/error.log
       CustomLog ${APACHE_LOG_DIR}/access.log combined
       SSLEngine On
       SSLCertificateFile /etc/apache2/ssl/certificate.crt
       SSLCertificateKeyFile /etc/apache2/ssl/private.key
       SSLCACertificateFile /etc/apache2/ssl/ca_bundle.crt
       <Location />
               SSLRenegBufferSize 10486000
               SSLRequireSSL On
               SSLVerifyClient optional
               SSLVerifyDepth 1
               SSLOptions +StdEnvVars +StrictRequire
       </Location>

       ServerAdmin webmaster@localhost
       DocumentRoot /var/www/html

       ProxyRequests Off
       ProxyPreserveHost On

       ProxyPass           /climmob3    http://172.31.41.128:6543/climmob3
       ProxyPassReverse    /climmob3    http://172.31.41.128:6543/climmob3

       <Proxy *>
           allow from all
       </Proxy>
       ProxyTimeout 1200

       RequestHeader set X-Forwarded-Port 443
       RequestHeader set X-Forwarded-Scheme https


</VirtualHost>
```
**The error is for example:**
`[Thu Aug 30 20:25:49.439401 2018] [authz_core:error] [pid 19275:tid 139784586405632] [client 172.31.41.128:53024] AH01630: client denied by server configuration: /opt/climmob_wsgi/htdocs/001, referer: https://climmob.net/climmob3/project/001/registry/cancel`

**The code declaring such route is:**
`routes.append(addRoute('cancelregistry', '/project/{projectid}/registry/cancel', cancelRegistry_view, 'project/cancelregistry.jinja2'))`

I tried by adding a / at the end of the ProxyPass but I get the same.

**Comment by GrahamDumpleton** [comment]
Try with latest version in repo:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

The fix hasn't actually been released.

**Comment by GrahamDumpleton** [comment]
I believe mod_wsgi 4.6.5 addressed this so closing.
