### ISSUE TITLE
mod_wsgi on MacOS

### ISSUE THREAD

**Issue by anares** [GrahamDumpleton/mod_wsgi#357]
Hello, 
I am trying to configure mod_wsgi with Apache provided by macOS. I installed it using "pipe install". Now I get the following:

Ivaylos-iMac:hello yosifov$ source venv/bin/activate
(venv) Ivaylos-iMac:hello yosifov$ mod_wsgi-express start-server
Server URL         : http://localhost:8000/
Server Root        : /var/folders/ph/zsvkq03d77xg_nv4c6j64vkc0000gn/T/mod_wsgi-localhost:8000:501
Server Conf        : /var/folders/ph/zsvkq03d77xg_nv4c6j64vkc0000gn/T/mod_wsgi-localhost:8000:501/httpd.conf
Error Log File     : /var/folders/ph/zsvkq03d77xg_nv4c6j64vkc0000gn/T/mod_wsgi-localhost:8000:501/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8
httpd (mod_wsgi-express) : Syntax error on line 159 of /var/folders/ph/zsvkq03d77xg_nv4c6j64vkc0000gn/T/mod_wsgi-localhost:8000:501/httpd.conf: Cannot load /Users/yosifov/Sites/hello/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-darwin.so into server: dlopen(/Users/yosifov/Sites/hello/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-darwin.so, 10): no suitable image found.  Did find:\n\t/Users/yosifov/Sites/hello/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-darwin.so: code signature in (/Users/yosifov/Sites/hello/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.\n\t/Users/yosifov/Sites/hello/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-darwin.so: stat() failed with errno=22

**Comment by GrahamDumpleton** [comment]
Which macOS version are you using?

**Comment by anares** [comment]
Mojave preview

**Comment by GrahamDumpleton** [comment]
Was worried that may be the case. With every new macOS version, Apple has been making it harder and harder to use third party modules with their Apache installation. I just don't have an answer at this point since I am still on 10.13.

**Comment by anares** [comment]
Shall I assume, the if I go back to 10.13, everything would be ok?

**Comment by GrahamDumpleton** [comment]
I have never seen that issue on 10.13.

**Comment by markburgessstl** [comment]
Same problem here with Mojave final release

**Comment by mibadika** [comment]
What should i do to setup my virtual hosts? I try to 'mod_wsgi-express start-server --include-file /Users/myhome/virtual-host.conf', but i just see the 'Malt Whiskey' page...

**Comment by GrahamDumpleton** [comment]
@mibadika Please don't ask questions on arbitrary issues. If want to have a discussion, better to use the mailing list:

* https://modwsgi.readthedocs.io/en/develop/finding-help.html

You are though going about using ``mod_wsgi-express`` the completely wrong way. It already does all the set up of the configuration for you. It would be very rare that you would need to provide it additional configuration manually.

For some examples see:

* http://blog.dscpl.com.au/2015/04/introducing-modwsgi-express.html

**Comment by iwellaway** [comment]
Hi, having just returned to a Mac Django app using mod_wsgi after a few months, the server has been updated to mojave and I'm getting the same error as those above. It was all working, and now apache won't start due to the code signature issue with mod_wsgi.

I've tried installing mod_wsgi-httpd but can't get this to work. Are there any other fixes?

Thanks

**Comment by GrahamDumpleton** [comment]
When using ``mod_wsgi-httpd`` after having previously installed ``mod_wsgi``, ensure you do:

```
pip uninstall mod_wsgi
pip uninstall mod_wsgi-httpd
pip install mod_wsgi-httpd
pip install --no-cache-dir mod_wsgi
```

It is important to use ``--no-cache-dir`` when ``pip`` installing ``mod_wsgi`` in this case, else it will use the precompiled binaries from the build against Apple Apache.

You should then be able to run:

```
mod_wsgi-express start-server
```

Note that this method doesn't help you with using Apple Apache. There is no way now of using Apple Apache on Mojave, unless someone can work out what is required to add an add-hoc signature to a compiled mod_wsgi binary.

So you have to use ``mod_wsgi-express``.

If you really want to do manual Apache configuration, use HomeBrew Apache instead.

```
brew install httpd
APXS=/usr/local/sbin/apxs pip install --no-cache-dir mod_wsgi
```

Then run:

```
mod_wsgi-express module-config
```

and take the output of that and add it to the HomeBrew Apache configuration to load mod_wsgi, configure if for your WGSI application, and then use HomeBrew Apache instead of the Apple Apache.

**Comment by iwellaway** [comment]
Thanks for this. I've tried this but get stuck on the:

pip install mod_wsgi_httpd

The error I get is:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-uQwqxn/mod-wsgi-httpd/setup.py", line 77, in <module>
        raise RuntimeError('Failed to build APR.')
    RuntimeError: Failed to build APR.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-uQwqxn/mod-wsgi-httpd/

**Comment by GrahamDumpleton** [comment]
Can you try with ``-v`` option to ``pip install``. Add the option multiple times if necessary until it shows the actual low level compiler or script error from the build.

**Comment by iwellaway** [comment]
Thanks Graham. I've tried this and attached the verbose output. Does it shed any light on what's going on?
[output.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2772551/output.txt)

**Comment by GrahamDumpleton** [comment]
You need at least the XCode command line tools installed, or gcc from HomeBrew. Do you have one of those?

**Comment by iwellaway** [comment]
Yes I’ve got the CommandLineTools installed. Do I need to do something else to include them in the installation?

**Comment by GrahamDumpleton** [comment]
If you run ``cc -v`` what does it say?

**Comment by GrahamDumpleton** [comment]
More so, ``gcc -v``.

**Comment by iwellaway** [comment]
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by iwellaway** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.4.0/5.1.0/lto-wrapper
Target: x86_64-apple-darwin14.4.0
Configured with: ../gcc-5.1.0/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 5.1.0 (GCC)

**Comment by iwellaway** [comment]
[output2.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2772766/output2.txt)

Seems to have got a bit further. I've attached the output.

**Comment by GrahamDumpleton** [comment]
Still not sure. I don't have HomeBrew gcc installed at all and just use Apple cc. When have HomeBrew gcc installed, there may be some conflict. The ``/lib/cpp`` shouldn't exist. What do you get when you run:

```
ls -las /lib/cpp
```

**Comment by iwellaway** [comment]
ls: /lib/cpp: No such file or directory

Is it worth removing homebrew if I can?

**Comment by GrahamDumpleton** [comment]
I would only try:

```
brew uninstall gcc
```

Can always reinstall it.

**Comment by stanchovy** [comment]
I just resolved this issue, I'm on Mojave and ran into this same infuriating issue with Mac's unsigned binary nonsense.
@GrahamDumpleton your solution didn't quite work for me but it helped me realize that the issue was with using the Apache that was shipped with MacOS. The pip generated mod_wsgi.so for some reason had issues: "Symbol not found: _apr_file_info_get$INODE64\n"
I adapted your solution and here's what did work:
1. brew install httpd
2. Follow your guide at https://modwsgi.readthedocs.io/en/develop/user-guides/quick-installation-guide.html to build mod_wsgi.so from scratch
- download and untar
- ./configure
- make
- make install
3. Point http.conf to that .so with `LoadModule [.so file]`
4. Bounce apache

Thanks again for the help.

**Comment by groverabhinav** [comment]
@stanchovy  - How to point ./configure to right apache and python

**Comment by stanchovy** [comment]
@groverabhinav what I mean is in your terminal type in "which python" -- make sure the binary it lists is the right python you expected, and "which apachectl" -- same here -- it should be the correct binary you were expecting that you plan to be using to running your application on.

**Comment by GrahamDumpleton** [comment]
Run ``./configure --help`` and it explains the options.

Specifically, look at the options ``--with-apxs`` and ``--with-python``.

These override what will be found in ``PATH``.

**Comment by kcrawford** [comment]
Build seems to want to find items in /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/

And also /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun

Neither of these exist if you only have Command Line tools installed and not full Xcode.  And the toolchain isn't there for current Xcode.

If apr-1-config and apu-1-config are in /usr/local/bin, the following workaround seemed to work for getting it to build. (creating missing directories and symlinking in the binaries)

```
mkdir -p /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/
ln -s /usr/local/bin/apr-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/
ln -s /usr/local/bin/apu-1-config /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apu-1-config
mkdir -p /Applications/Xcode.app/Contents/Developer/usr/bin/
ln -s /usr/bin/xcrun /Applications/Xcode.app/Contents/Developer/usr/bin/
xcode-select -s /Library/Developer/CommandLineTools/
```
xcode-select was necessary because it defaulted to /Applications/Xcode.app once I created that directory.  (I only have Command Line Tools for Xcode installed.)

**Comment by GrahamDumpleton** [comment]
You can’t use the configure/make/make install method of installation on macOS unless using Homebrew for everything and set APXS environment variable to apxs from Homebrew Apache.

You can use pip install method, but you still can’t use Apache from Apple and must install Apache yourself or use Apache from Homebrew.

You must have Xcode command line tools and Xcode app installed if you want to use Apple compiler, alternatively use Homebrew compiler with Homebrew Apache.

With changes made by Apple over last few OS versions it is impossible to get it working on macOS using just Apple software.

**Comment by kcrawford** [comment]
Apologies. On the workaround above I was working remotely on a 10.12.x OS.  Forgot it was 10.12.

**Comment by agautam92** [comment]
Thank You @GrahamDumpleton .
Appreciate it.
You have been very helpful.

**Comment by david-f** [comment]
I do not have to use Apple Apache (and gave up trying to use it) and so tried the mod_wsgi-httpd & mod_wsgi workaround, however the pip install or some other part of the process still seems to be searching for Apple Apache?!

I am running Mojave 10.14.6 and tried the install in a Python 3.7 conda env ("KBDJ37"). Here is the output from my attempt:

=================
(KBDJ37) Uist:mod_wsgi-4.6.5 dcf$ pip install --no-cache-dir mod_wsgi-httpd mod_wsgi
Collecting mod_wsgi-httpd
  Downloading https://files.pythonhosted.org/packages/a3/ae/d86c2dfa1247f94d36c90e0053aaaa3671a801e084470963ccdfdd148314/mod_wsgi-httpd-2.4.39.1.tar.gz (12.9MB)
     |████████████████████████████████| 12.9MB 1.5MB/s 
Collecting mod_wsgi
  Downloading https://files.pythonhosted.org/packages/25/d8/1df4ba9c051cd88e02971814f0867274a8ac821baf983b6778dacd6e31f7/mod_wsgi-4.6.8.tar.gz (490kB)
     |████████████████████████████████| 491kB 12.8MB/s 
    ERROR: Command errored out with exit status 1:
     command: /anaconda3/envs/KBDJ37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3s/dy3jl3ld7qx06v0txkktjbb80000gn/T/pip-install-rl8wfcpz/mod-wsgi/setup.py'"'"'; __file__='"'"'/private/var/folders/3s/dy3jl3ld7qx06v0txkktjbb80000gn/T/pip-install-rl8wfcpz/mod-wsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3s/dy3jl3ld7qx06v0txkktjbb80000gn/T/pip-install-rl8wfcpz/mod-wsgi/pip-egg-info
         cwd: /private/var/folders/3s/dy3jl3ld7qx06v0txkktjbb80000gn/T/pip-install-rl8wfcpz/mod-wsgi/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3s/dy3jl3ld7qx06v0txkktjbb80000gn/T/pip-install-rl8wfcpz/mod-wsgi/setup.py", line 338, in <module>
        raise RuntimeError('No Apache installation can be found, do you '
    RuntimeError: No Apache installation can be found, do you have the full Apple Xcode installed. It is not enough to have just the xcode command line tools installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(KBDJ37) Uist:mod_wsgi-4.6.5 dcf$ 
=================

Any suggestions about what to try next?
Thank-you in advance.
David

**Comment by GrahamDumpleton** [comment]
Install just `mod-wsgi-httpd` first. Then as separate command install `mod_wsgi`.

**Comment by david-f** [comment]
Separating the installs was successful, thank-you much!
David

**Comment by GrahamDumpleton** [comment]
FWIW, if really need to make use of ``mod_wsgi-httpd``, you can now use ``mod_wsgi-standalone`` package and it will install things in a way that will first trigger ``mod_wsgi-httpd`` such that is then available when ``mod_wsgi`` package installed. IOW, don't list ``mod_wsgi`` or ``mod_wsgi-httpd`` in a ``requirements.txt`` file, list just ``mod_wsgi-standalone``.
