### ISSUE TITLE
mod_wsgi cant find MYSQL but its installed in my venv

### ISSUE THREAD

**Issue by TAUFEEQ1** [GrahamDumpleton/mod_wsgi#358]
error.log
[Sun Sep 09 18:59:27.698841 2018] [core:notice] [pid 15230] AH00094: Command line: '/usr/sbin/apache2'
[Sun Sep 09 15:59:34.988019 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712] mod_wsgi (pid=15234): Target WSGI script '/home/nsamba/projects/global/project_manager/project_manager/manager/manager/wsgi.py' cannot be loaded as Python module.
[Sun Sep 09 15:59:34.988174 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712] mod_wsgi (pid=15234): Exception occurred processing WSGI script '/home/nsamba/projects/global/project_manager/project_manager/manager/manager/wsgi.py'.
[Sun Sep 09 15:59:34.993102 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712] Traceback (most recent call last):
[Sun Sep 09 15:59:34.993188 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]   File "/home/nsamba/projects/global/project_manager/project_manager/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
[Sun Sep 09 15:59:34.993201 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]     import MySQLdb as Database
[Sun Sep 09 15:59:34.993225 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]   File "/home/nsamba/projects/global/project_manager/project_manager/lib/python3.6/site-packages/MySQLdb/__init__.py", line 18, in <module>
[Sun Sep 09 15:59:34.993237 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]     import _mysql
[Sun Sep 09 15:59:34.993283 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712] ImportError: No module named '_mysql'
[Sun Sep 09 15:59:34.993315 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]
[Sun Sep 09 15:59:34.993326 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712] The above exception was the direct cause of the following exception:
[Sun Sep 09 15:59:34.993336 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]
[Sun Sep 09 15:59:34.993359 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712] Traceback (most recent call last):
[Sun Sep 09 15:59:34.993564 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]   File "/home/nsamba/projects/global/project_manager/project_manager/manager/manager/wsgi.py", line 20, in <module>
[Sun Sep 09 15:59:34.993576 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]     application = get_wsgi_application()
[Sun Sep 09 15:59:34.993600 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]   File "/home/nsamba/projects/global/project_manager/project_manager/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Sep 09 15:59:34.993612 2018] [wsgi:error] [pid 15234] [remote 127.0.0.1:55712]     django.setup(set_prefix=False)

**Comment by GrahamDumpleton** [comment]
How did you install mod_wsgi?

What Python version is mod_wsgi for?

What Python version are you expecting to use? It must be same as mod_wsgi is built for.

Are you using a Python virtual environment? How did you configure mod_wsgi to use that.

Most likely you are trying to force mod_wsgi to use a Python virtual environment for a different Python version than it was compiled for. Another possibility is that your MySQL libraries are in a strange place and when installing the MySQL client package, it wasn't built such that the libraries could be found. If using main Apache installation, you cannot rely on ``LD_LIBRARY_PATH`` in user environment.

**Comment by TAUFEEQ1** [comment]
I found there was a version conflict in mysqlclient and "_mysql" lib which i addressed by unistalling mysqlclient client and matching the versions.

I also found that my mod_wsgi is compiled for python3.5 and my virtual environment is running python3.6. There isnt much difference in python3.6 and python3.5 . But for future referrence , if i can compile mod_wsgi for python3.6, how would i configure Apache for this new mod? 
Thank you for all the support!

**Comment by GrahamDumpleton** [comment]
There may be not much difference in Python code between 3.5 and 3.6, but compiled binary extensions cannot be shared between them. This is why you cannot mix mod_wsgi compiled for 3.5 with a virtual environment for 3.6.

As to the question "how would i configure Apache for this new mod", I am not sure what you are asking. If you have built mod_wsgi with 3.6, your virtual environment is 3.6 and thus any Python packages you installed into the virtual environment are 3.6, then you are good to go.

Get everything working with same Python version first and then we can see if there is still an issue that needs to be solved.

**Comment by GrahamDumpleton** [comment]
Was this resolved?

**Comment by TAUFEEQ1** [comment]
Oh yeah it was resolved,i downgraded my python,am really sorry i forgot to update and close this thread
