### ISSUE TITLE
syntax error when use connect-timeout, socket-timeout

### ISSUE THREAD

**Issue by haulpd** [GrahamDumpleton/mod_wsgi#360]
Dear Dev, 

I have config WSGIDaemonProcess with option is connect-timeout=30 socket-timeout=60 then restart apache but it failed.
I received error: 
 AH00526: Syntax error on line 6 of /etc/httpd/conf.d/priceboard-market.conf:

I used apache 
```
Server version: Apache/2.4.6 (CentOS)
Server built:   Jun 27 2018 13:48:59
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     worker
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
```
and `mod_wsgi-3.4-13.el7_5.1.x86_64` on CentOS 7

My WSGIDaemonProcess like:
`WSGIDaemonProcess apache processes=2 threads=20 request-timeout=60 socket-timeout=60 connect-timeout=30 python-path=/usr/lib64/python3.4/site-packages:/usr/local/lib64/python3.6/site-packages:/usr/local/lib/python3.6/site-packages`

Thanks.

**Comment by GrahamDumpleton** [comment]
Your mod_wsgi version is ancient, way more than 5+ years old and 50+ versions behind. Use latest version.
