### ISSUE TITLE
Invalid MaxMemFree value: 64

### ISSUE THREAD

**Issue by GreenFerret95** [GrahamDumpleton/mod_wsgi#362]
Running the command mod_wsgi-express start-server, or python manage.py runmodwsgi through Django gives the following output.

Using Python 3.6.6 in Virtual Environment, Django 2.1.2

```
mod_wsgi-express start-server 
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:121907
Server Conf        : /tmp/mod_wsgi-localhost:8000:121907/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8000:121907/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8
AH00526: Syntax error on line 186 of /tmp/mod_wsgi-localhost:8000:121907/httpd.conf:
Invalid MaxMemFree value: 64
```

Apache Server Information

```
$ httpd -V
[Tue Oct 16 13:40:50.661841 2018] [so:warn] [pid 8340] AH01574: module auth_openidc_module is already loaded, skipping
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   May 28 2018 16:19:32
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
```

**Comment by GrahamDumpleton** [comment]
Can you include from ``/tmp/mod_wsgi-localhost:8000:121907/httpd.conf`` that part of the configuration, including half dozen lines before and after. I don't know why this would occur as the ``MaxMemFree`` directive exists back to Apache 2.2 and has always taken an integer for Kbytes.

**Comment by GreenFerret95** [comment]
```
<IfDefine MOD_WSGI_CGID_SCRIPT>
<IfModule !cgid_module>
LoadModule cgid_module '${MOD_WSGI_MODULES_DIRECTORY}/mod_cgid.so'
</IfModule>
</IfDefine>

<IfDefine MOD_WSGI_CGI_SCRIPT>
<IfModule !cgi_module>
LoadModule cgi_module '${MOD_WSGI_MODULES_DIRECTORY}/mod_cgi.so'
</IfModule>
</IfDefine>

<IfVersion < 2.4>
DefaultType text/plain
</IfVersion>

TypesConfig '/etc/mime.types'

HostnameLookups Off
MaxMemFree 64
Timeout 60
ListenBacklog 500

<IfDefine MOD_WSGI_WITH_HTTP2>
Protocols h2 h2c http/1.1
</IfDefine>

<IfVersion >= 2.2.15>
RequestReadTimeout header=15-30,MinRate=500 body=15,MinRate=500
</IfVersion>

LimitRequestBody 10485760

<Directory />
    AllowOverride None
<IfVersion < 2.4>
    Order deny,allow
    Deny from all
</IfVersion>
<IfVersion >= 2.4>
    Require all denied
</IfVersion>
</Directory>

```

**Comment by GrahamDumpleton** [comment]
That doesn't make a lot of sense. Only thing can think of is that SELinux is enabled and the SELinux profile is set up in some sort of strange way that is causing an issue. I can't see how though as that value isn't used to set any system level config and is purely a value that is used internally in Apache when checking memory use of internal memory pools which Apache libraries manage. What version of RHEL are you using?

**Comment by GreenFerret95** [comment]
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by GreenFerret95** [comment]
Issue not resolved but no longer relevant as a different path was taken

**Comment by pjmichalski** [comment]
I experienced this exact issue today when running python manage.py runmodwsgi. Oddly, I've been using mod_wsgi for a few weeks now and didn't have this issue until today. I made a few changes in my Django code, but nothing related to the settings (just changed some views and html templates). Did you ever figure out what caused this error?

**Comment by pjmichalski** [comment]
It looks like GreenFerret95 got around this issue by running as root. Unfortunately, I don't have root privileges on my company server, so I need another solution.

**Comment by GrahamDumpleton** [comment]
@pjmichalski What OS variant/version are you using? What Apache version? If RHEL/CentOS, is SELinux enabled?

**Comment by pjmichalski** [comment]
Hi @GrahamDumpleton , thanks for responding so quickly! OS is CentOS 7. Apache version 2.4.6. SELinux is disabled. 
Again, everything was working fine for over a month before this problem popped up on Friday. I asked one of our sys admins if they made any changes recently which might affect Apache. He said he re-installed the system Apache on Monday, but didn't think that would affect the instance I was running for Django. Just to be safe I uninstalled and reinstalled mod_wsgi, but that didn't help. He said the only other recent change was installing some packages to give a better desktop experience over VNC (yum groupinstall "MATE Desktop"), but he didn't think that would affect Apache.
Please let me know if I can provide any other information to help debug the issue.
(By the way, you've made an amazing package. Thanks for helping out all of us who know Python and Django, but don't know the first thing about Apache.)

**Comment by pjmichalski** [comment]
In case someone else lands here after encountering this bug, here's how to get around it: 
1) Run runmodwsgi with the --setup-only flag.
2) Go to the httpd.conf file created by the previous command, and delete the line with MaxMemFree.
3) Specify the location of your django settings file by setting the DJANGO_SETTINGS_MODULE environment variable. (export DJANGO_SETTINGS_MODULE=yourapp.settings.prod, for example.) 
4) Start the apache server using the apachectl executable created in step 1: /path/to/apachectl start
