### ISSUE TITLE
mod_wsgi in python 3.6.4 and apache 2.4 in xampp 3.2.2 in Windows Server 2012 R2

### ISSUE THREAD

**Issue by josh-cajina** [GrahamDumpleton/mod_wsgi#366]
I am trying to mount a DJANGO 2.0 application in XAMPP 3.2.2 (Apache 2.4) in Windows 2012 R2.

I installed mod_wsgi via pip (global installation).

I executed the command mod_wsgi-express module-config in console, which gave me the following result:

```
LoadFile "c: / program files (x86) /python36-32/python36.dll"
LoadModule wsgi_module "c: / program files (x86) /python36-32/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win32.pyd"
WSGIPythonHome "c: / program files (x86) / python36-32"

The settings that I currently have in my httpd.conf are:

# Python Modules
LoadFile "c: / program files (x86) /python36-32/python36.dll"
LoadModule wsgi_module "c: / program files (x86) /python36-32/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win32.pyd"

# Virtual Host Python App
<VirtualHost *: 7070>
ServerName localhost
<Directory "D: / path / src / django_app">
<Files wsgi.py>
    Requires all granted
  </ Files>
</ Directory>
WSGIPythonPath "D: \ path \ virtualenv \ djangoapp_env \ Scripts"
WSGIScriptAlias ​​/ djangoapp "D: /path/src/django_app/django_app/wsgi.py"
</ VirtualHost>
```

My goal is to have multiple DJANGO applications under Apache, and all of them with their corresponding virtual environment along with their dependencies. But I can not get Apache to run and show me my application.

Apparently all the settings run fine, as long as you remove the WSGIPythonPath line. But the browser (Chrome) responds with an internal server error.

I would greatly appreciate your support.

**Comment by GrahamDumpleton** [comment]
Don't use backslashes, use UNIX/POSIX style forward slashes in the paths. You also shouldn't have spaces in those paths as you seem to, although that may be cut and paste issue.

Also, ``WSGIPythonPath`` would need to be parent directory to you project, so likely needs to be:

```
WSGIPythonPath /path/src/django_app
```

If you have a virtual environment, you should be using ``WSGIPythonHome`` to refer to it. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

If not using a Python virtual environment, you must still include in your config the ``WSGIPythonHome`` line that ``mod_wsgi-express module-config`` output.

Beyond those suggestions, can't help you unless you show the errors from the Apache error log from when you make the web request against the application.
