### ISSUE TITLE
Error 10053: MySQL server has gone away - occurs after running for app. 12 hours

### ISSUE THREAD

**Issue by mbsEU** [GrahamDumpleton/mod_wsgi#367]
I have server running an api which is working fine when I restart the apache service.
But it stops to work after approximately 12 hours and reports an internal error.

I have not been able to interpret what is causing the fault.

**System**
Windows 7
Wampserver64
- Apache 2.4.33
- MariaDB 10.2.14
Python 3.6

**Error log from apache2:**

> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] ERROR in app: Exception on /product_structure/JBU [GET]\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] Traceback (most recent call last):\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\pymysql\\connections.py", line 708, in _write_bytes\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  self._sock.sendall(data)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] \r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] During handling of the above exception, another exception occurred:\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] \r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] Traceback (most recent call last):\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\flask\\app.py", line 2292, in wsgi_app\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  response = self.full_dispatch_request()\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\flask\\app.py", line 1815, in full_dispatch_request\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  rv = self.handle_user_exception(e)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\flask\\app.py", line 1718, in handle_user_exception\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  reraise(exc_type, exc_value, tb)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\flask\\_compat.py", line 35, in reraise\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  raise value\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\flask\\app.py", line 1813, in full_dispatch_request\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  rv = self.dispatch_request()\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\flask\\app.py", line 1799, in dispatch_request\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  return self.view_functions[rule.endpoint](**req.view_args)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:/websites/api\\api.py", line 29, in product_structure\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  cursor_product_structure_select.execute(sql_product_structure_select, f_product_code)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\pymysql\\cursors.py", line 170, in execute\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  result = self._query(query)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\pymysql\\cursors.py", line 328, in _query\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  conn.query(q)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\pymysql\\connections.py", line 515, in query\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  self._execute_command(COMMAND.COM_QUERY, sql)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\pymysql\\connections.py", line 766, in _execute_command\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  self._write_bytes(packet)\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] File "c:\\anaconda3\\envs\\webapi\\lib\\site-packages\\pymysql\\connections.py", line 713, in _write_bytes\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080]  "MySQL server has gone away (%r)" % (e,))\r
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
> [Thu Oct 25 07:28:48.858023 2018] [wsgi:error] [pid 3476:tid 1080] \r

**Comment by GrahamDumpleton** [comment]
Would look like you are trying to preserve a connection to the database, but the database is closing it after some time, or network issue means connection is dropped.

Your application code should be resilient to database connections being dropped.

This is highly unlikely to be anything to do with mod_wsgi.

**Comment by mbsEU** [comment]
I had declared the connection as a global which I was then using in my functions.
It was my initial though that the whole of the py-file was opened every time a call was made, but that is not the case.
I have change the functions so that I connect every time from within my functions.
That did the trick.
