### ISSUE TITLE
ValueError: unsupported hash type  md5 sha1 sha224 sha256 sha384  sha512 

### ISSUE THREAD

**Issue by saytik** [GrahamDumpleton/mod_wsgi#368]
Apache/2.4.35 + mod_wsgi 4.6.4 + Python 2.7.15

Python compiled in /opt/python/2.7.15
mod_wsgi    ./configure  --with-python=/opt/python/2.7.15/bin/python

`# ldd /etc/httpd/modules/mod_wsgi.so 
	linux-vdso.so.1 =>  (0x00007ffc58bfe000)
	libpython2.7.so.1.0 => /opt/python/2.7.15/lib/libpython2.7.so.1.0 (0x00007f374b031000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f374ae14000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f374ac10000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f374aa0d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f374a789000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f374a3f5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f374b651000)`

I have different django sites on  a few servers.  And All sites have the same problem ... When apache is restarted - sites are  working. But when i graceful  apache process or when i touch wsgi.py script - apache gives me 500 internal error. And site work again when apache is restarted. 

Configuration:

`<IfModule mod_wsgi.c>
WSGIDaemonProcess DOMAIN_ssl display-name=%{GROUP} user=MYUSER group=MYUSER socket-user=MYUSER home=/home/MYUSER/dj/sites/DOMAIN processes=1 threads=4 maximum-requests=500 lang='ru_RU.utf8' locale='ru_RU.utf8' python-path=/home/MYUSER/dj/.venv/lib/python2.7/site-packages python-home=/home/MYUSER/dj/.venv

WSGIProcessGroup DOMAIN_ssl
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / /home/MYUSER/dj/sites/DOMAIN/project_src/wsgi.py
</IfModule>`

The following logs in apache error log when i touch wsgi.py:

`[Sun Oct 28 23:04:11.515119 2018] [wsgi:error] [pid 1226] ERROR:root:code for hash md5 was not found.
[Sun Oct 28 23:04:11.515152 2018] [wsgi:error] [pid 1226] Traceback (most recent call last):
[Sun Oct 28 23:04:11.515156 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 147, in <module>
[Sun Oct 28 23:04:11.515160 2018] [wsgi:error] [pid 1226]     globals()[__func_name] = __get_hash(__func_name)
[Sun Oct 28 23:04:11.515163 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
[Sun Oct 28 23:04:11.515167 2018] [wsgi:error] [pid 1226]     return __get_builtin_constructor(name)
[Sun Oct 28 23:04:11.515170 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
[Sun Oct 28 23:04:11.515173 2018] [wsgi:error] [pid 1226]     raise ValueError('unsupported hash type ' + name)
[Sun Oct 28 23:04:11.515177 2018] [wsgi:error] [pid 1226] ValueError: unsupported hash type md5
[Sun Oct 28 23:04:11.515398 2018] [wsgi:error] [pid 1226] ERROR:root:code for hash sha1 was not found.
[Sun Oct 28 23:04:11.515406 2018] [wsgi:error] [pid 1226] Traceback (most recent call last):
[Sun Oct 28 23:04:11.515410 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 147, in <module>
[Sun Oct 28 23:04:11.515413 2018] [wsgi:error] [pid 1226]     globals()[__func_name] = __get_hash(__func_name)
[Sun Oct 28 23:04:11.515417 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
[Sun Oct 28 23:04:11.515420 2018] [wsgi:error] [pid 1226]     return __get_builtin_constructor(name)
[Sun Oct 28 23:04:11.515423 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
[Sun Oct 28 23:04:11.515427 2018] [wsgi:error] [pid 1226]     raise ValueError('unsupported hash type ' + name)
[Sun Oct 28 23:04:11.515430 2018] [wsgi:error] [pid 1226] ValueError: unsupported hash type sha1
[Sun Oct 28 23:04:11.515637 2018] [wsgi:error] [pid 1226] ERROR:root:code for hash sha224 was not found.
[Sun Oct 28 23:04:11.515645 2018] [wsgi:error] [pid 1226] Traceback (most recent call last):
[Sun Oct 28 23:04:11.515648 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 147, in <module>
[Sun Oct 28 23:04:11.515652 2018] [wsgi:error] [pid 1226]     globals()[__func_name] = __get_hash(__func_name)
[Sun Oct 28 23:04:11.515655 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
[Sun Oct 28 23:04:11.515659 2018] [wsgi:error] [pid 1226]     return __get_builtin_constructor(name)
[Sun Oct 28 23:04:11.515662 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
[Sun Oct 28 23:04:11.515666 2018] [wsgi:error] [pid 1226]     raise ValueError('unsupported hash type ' + name)
[Sun Oct 28 23:04:11.515679 2018] [wsgi:error] [pid 1226] ValueError: unsupported hash type sha224
[Sun Oct 28 23:04:11.515877 2018] [wsgi:error] [pid 1226] ERROR:root:code for hash sha256 was not found.
[Sun Oct 28 23:04:11.515885 2018] [wsgi:error] [pid 1226] Traceback (most recent call last):
[Sun Oct 28 23:04:11.515888 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 147, in <module>
[Sun Oct 28 23:04:11.515892 2018] [wsgi:error] [pid 1226]     globals()[__func_name] = __get_hash(__func_name)
[Sun Oct 28 23:04:11.515895 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
[Sun Oct 28 23:04:11.515898 2018] [wsgi:error] [pid 1226]     return __get_builtin_constructor(name)
[Sun Oct 28 23:04:11.515901 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
[Sun Oct 28 23:04:11.515904 2018] [wsgi:error] [pid 1226]     raise ValueError('unsupported hash type ' + name)
[Sun Oct 28 23:04:11.515907 2018] [wsgi:error] [pid 1226] ValueError: unsupported hash type sha256
[Sun Oct 28 23:04:11.516127 2018] [wsgi:error] [pid 1226] ERROR:root:code for hash sha384 was not found.
[Sun Oct 28 23:04:11.516135 2018] [wsgi:error] [pid 1226] Traceback (most recent call last):
[Sun Oct 28 23:04:11.516138 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 147, in <module>
[Sun Oct 28 23:04:11.516142 2018] [wsgi:error] [pid 1226]     globals()[__func_name] = __get_hash(__func_name)
[Sun Oct 28 23:04:11.516145 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
[Sun Oct 28 23:04:11.516148 2018] [wsgi:error] [pid 1226]     return __get_builtin_constructor(name)
[Sun Oct 28 23:04:11.516151 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
[Sun Oct 28 23:04:11.516154 2018] [wsgi:error] [pid 1226]     raise ValueError('unsupported hash type ' + name)
[Sun Oct 28 23:04:11.516157 2018] [wsgi:error] [pid 1226] ValueError: unsupported hash type sha384
[Sun Oct 28 23:04:11.516335 2018] [wsgi:error] [pid 1226] ERROR:root:code for hash sha512 was not found.
[Sun Oct 28 23:04:11.516343 2018] [wsgi:error] [pid 1226] Traceback (most recent call last):
[Sun Oct 28 23:04:11.516346 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 147, in <module>
[Sun Oct 28 23:04:11.516349 2018] [wsgi:error] [pid 1226]     globals()[__func_name] = __get_hash(__func_name)
[Sun Oct 28 23:04:11.516352 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
[Sun Oct 28 23:04:11.516355 2018] [wsgi:error] [pid 1226]     return __get_builtin_constructor(name)
[Sun Oct 28 23:04:11.516359 2018] [wsgi:error] [pid 1226]   File "/opt/python/2.7.15/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
[Sun Oct 28 23:04:11.516362 2018] [wsgi:error] [pid 1226]     raise ValueError('unsupported hash type ' + name)
[Sun Oct 28 23:04:11.516365 2018] [wsgi:error] [pid 1226] ValueError: unsupported hash type sha512
[Sun Oct 28 23:04:11.869362 2018] [wsgi:error] [pid 1226] mod_wsgi (pid=1226): Failed to exec Python script file '/home/MYUSER/dj/sites/DOMAIN/project_src/wsgi.py'.
[Sun Oct 28 23:04:11.869397 2018] [wsgi:error] [pid 1226] mod_wsgi (pid=1226): Exception occurred processing WSGI script '/home/MYUSER/dj/sites/DOMAIN/project_src/wsgi.py'.
[Sun Oct 28 23:04:11.869414 2018] [wsgi:error] [pid 1226] Traceback (most recent call last):
[Sun Oct 28 23:04:11.869436 2018] [wsgi:error] [pid 1226]  File "/home/MYUSER/dj/sites/DOMAIN/project_src/wsgi.py", line 14, in <module>
[Sun Oct 28 23:04:11.869486 2018] [wsgi:error] [pid 1226] application = get_wsgi_application()
[Sun Oct 28 23:04:11.869508 2018] [wsgi:error] [pid 1226] File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Sun Oct 28 23:04:11.894517 2018] [wsgi:error] [pid 1226] django.setup(set_prefix=False)
[Sun Oct 28 23:04:11.973430 2018] [wsgi:error] [pid 1226] File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
[Sun Oct 28 23:04:12.122771 2018] [wsgi:error] [pid 1226]     apps.populate(settings.INSTALLED_APPS)
[Sun Oct 28 23:04:12.122812 2018] [wsgi:error] [pid 1226]    File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
[Sun Oct 28 23:04:12.136394 2018] [wsgi:error] [pid 1226]     app_config.import_models()
[Sun Oct 28 23:04:12.136425 2018] [wsgi:error] [pid 1226]    File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
[Sun Oct 28 23:04:12.140620 2018] [wsgi:error] [pid 1226]    self.models_module = import_module(models_module_name)
[Sun Oct 28 23:04:12.140635 2018] [wsgi:error] [pid 1226]  File "/opt/python/2.7.15/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Oct 28 23:04:12.140679 2018] [wsgi:error] [pid 1226]    __import__(name)
[Sun Oct 28 23:04:12.140690 2018] [wsgi:error] [pid 1226]   File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
[Sun Oct 28 23:04:12.152320 2018] [wsgi:error] [pid 1226]    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
[Sun Oct 28 23:04:12.152335 2018] [wsgi:error] [pid 1226]    File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 10, in <module>
[Sun Oct 28 23:04:12.165133 2018] [wsgi:error] [pid 1226]   from django.contrib.auth.hashers import (
[Sun Oct 28 23:04:12.165146 2018] [wsgi:error] [pid 1226]    File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 241, in <module>
[Sun Oct 28 23:04:12.176028 2018] [wsgi:error] [pid 1226]    class PBKDF2PasswordHasher(BasePasswordHasher):
[Sun Oct 28 23:04:12.176051 2018] [wsgi:error] [pid 1226]    File "/home/MYUSER/dj/.venv/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 251, in PBKDF2PasswordHasher
[Sun Oct 28 23:04:12.176086 2018] [wsgi:error] [pid 1226]    digest = hashlib.sha256
[Sun Oct 28 23:04:12.176107 2018] [wsgi:error] [pid 1226]  AttributeError: 'module' object has no attribute 'sha256'

`

**Comment by GrahamDumpleton** [comment]
Usually caused by loading mod_php, or some other third party Apache module, into the same Apache and it drags in an incompatible version of a hash library, which gets picked up and used in preference to what Python was compiled for.

Are you using mod_php for Apache?

**Comment by saytik** [comment]
yes, it is WHM/Cpanel shared hosting. We provide low cost shared hosting for php and django-python applications.

**Comment by saytik** [comment]
Does  some solutions exist  to use mod_wsgi and mod_php together ?

**Comment by GrahamDumpleton** [comment]
They will work fine if PHP and Python are both compiled with the same hash libraries, SSL libraries etc. It is when they are compiled against different versions of the library that problems occur. You can also have issues when you build Python yourself and don't tell it it should use system versions of libraries and it instead falls back to some sort of internal version. Finally, you need to make sure when not using system Python, that mod_wsgi is build to use the Python library from your separate installation and not fallback to using system Python library.

So question is, where have you got this Python version from since it isn't system Python. If you are trying to use Anaconda Python or other Python distro which ships with its own copies of system libraries, you will have problems. Anaconda Python in particular has become pretty well useless for use in embedded systems where the system it is embedded in uses system libraries instead.

**Comment by saytik** [comment]
I build python by myself:
`
./configure --prefix=/opt/python/2.7.15 --enable-shared --enable-optimizations
make && make install 
echo /opt/python/2.7.15/lib >  /etc/ld.so.conf.d/python.conf 
ldconfig
`

then i build mod_wsgi:
`
./configure --with-python=/opt/python/2.7.15/bin/python
`

**Comment by GrahamDumpleton** [comment]
Ignore that it mentions docker, read:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Compare that to how you built it, paying attention to what options the system Python was built with.

**Comment by saytik** [comment]
Thank you very much !
The problem has been fixed. Cpanel builds apache with it's own openssl package ea-openssl-1.0.2p-1.1.1.cpanel.x86_64.  But i compiled python with centos system openssl package. 

I have re-compiled  python with cpanel openssl-devel pachage and now all are working fine after reloading.

`yum install ea-openssl-devel`
`LD_LIBRARY_PATH=/opt/cpanel/ea-openssl/lib64  ./configure --prefix=/opt/python/2.7.15 --enable-shared --enable-optimizations && make && make install `

**Comment by GrahamDumpleton** [comment]
When you use ``LD_LIBRARY_PATH`` at build time, it means you also have to potentially supply it at run time so shared libraries can be found. If you need things to look in a different directory, you are better off using ``LD_RUN_PATH`` at build time as well if necessary so location is coded into the applications so it knows where to find them at run time without setting ``LD_LIBRARY_PATH``.

**Comment by saytik** [comment]
I can not repeat the setting on another server ...
does not compile with /opt/cpanel/ea-openssl
It builds without ssl and hashlib  when i remove system openssl-devel 
I am finding why it can't build with ea-openssl-devel-1.0.2p-1.1.1.cpanel.x86_64
