### ISSUE TITLE
Not able to read env variable set in bashrc

### ISSUE THREAD

**Issue by deepakshinde18** [GrahamDumpleton/mod_wsgi#371]
We have set env variable in bashrc and same we are reading in flask app. But after hosting it with apache mod_wsgi, application not able to read env variable. eg. we are reading XYZ variable set in bashrc as os.environ.get('XYZ') in flask app.

**Comment by GrahamDumpleton** [comment]
If Apache is run from system startup scripts, it is started as root and thenswitches to the Apache user. It will never read your personal bashrc or environment settings. You will need to set any special environment variables from the WSGI script file.

Do not though, that special environment variables such as ``LD_LIBRARY_PATH`` can be set in this way.

**Comment by deepakshinde18** [comment]
We are running apache manually with apache user and for same user we have set variables in bashrc

**Comment by GrahamDumpleton** [comment]
How are you starting it as the Apache user? Running what command? How did you become the Apache user?

Usually you can't start it manually as the actual Apache user if you have it as the system Apache and expect it to use standard HTTP ports.
