### ISSUE TITLE
WampServer x 64bit ,Apache2.4, Python3.7 x64bit, Django

### ISSUE THREAD

**Issue by pinli111** [GrahamDumpleton/mod_wsgi#373]
I am trying to develop django in wamp server in Window 10. 

I installed mod_wsgi via pip (global installation).

I executed the command mod_wsgi-express module-config in console, which gave me the following result:

LoadFile "c:/.../python37/python37.dll"
LoadModule wsgi_module "c:/.../mod_wsgi/server/mod_wsgi_cp37-win_amd64.pyd"

and I copy these two line in httpd.conf
and i get this error in apache.error.log

AH00455: Apache/2.4.35 (Win64) PHP/7.2.10 mod_wsgi/4.6.5 Python/3.7 configured -- resuming normal operations
[Tue Nov 27 18:35:05.538446 2018] [mpm_winnt:notice] [pid 7228:tid 756] AH00456: Apache Lounge VC15 Server built: Sep 19 2018 16:08:47
[Tue Nov 27 18:35:05.538446 2018] [core:notice] [pid 7228:tid 756] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.35\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.35'
[Tue Nov 27 18:35:05.566430 2018] [mpm_winnt:notice] [pid 7228:tid 756] AH00418: Parent: Created child process 3284
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings' Current thread 0x00002344 (most recent call first):
[Tue Nov 27 18:35:08.793572 2018] [mpm_winnt:crit] [pid 7228:tid 756] AH00419: master_main: create child process failed. Exiting.

I think I almost there to make django run but it stop here cause wamp server 2 of 3 services is running...
Hopefully you can give me some idea. @GrahamDumpleton Thanks.

**Comment by GrahamDumpleton** [comment]
Am pretty sure that ``module-config`` should have output a ``WSGIPythonHome`` directive as well which you need to include. If you don't you can see this problem.

What was the remainder of the configuration you added to Apache?

**Comment by pinli111** [comment]
![command_prompt_for_apache](https://user-images.githubusercontent.com/36152475/49077926-9040dc80-f277-11e8-89d3-994fbdb4c69c.PNG)

Yes. it has output. 
LoadFile "C:/Users/Pin Li/AppData/Local/Programs/Python/Python37/python37.dll"
LoadModule wsgi_module "C:/Users/Pin Li/AppData/Local/Programs/Python/Python37/Lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"

This is the additional 2 lines added into the httpd.conf after i downloaded wamp.
[httpd.conf(1).txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2619611/httpd.conf.1.txt)
Perhaps you can have a look for my conf file.

**Comment by GrahamDumpleton** [comment]
As I said, you have failed to include the ``WSGIPythonHome`` line output by ``module-config`` in the Apache config file. Make sure you include it.

You also may find things will not work due to having a space in your user name. There are certain things in Python that will not work when in a directory which is a sub directory of another directory with the space in the name.

Use a Python virtual environment in a directory outside of your user directory, where no path element has a space in the name. Install mod_wsgi and your application into that virtual environment instead.

**Comment by pinli111** [comment]
Hi it works after include WSGIPythonHome line. Thanks.
So for now if i want to link my django apps that had been develop, I need to follow

 **Using mod_wsgi-express with Django** In the project description?
As beforehand I added these to the httpd.conf but it does not work.
![image](https://user-images.githubusercontent.com/36152475/49079304-2f1b0800-f27b-11e8-80d1-adfec6fcf34e.png)

**Comment by GrahamDumpleton** [comment]
From memory, sort of looks right, but make sure you use double quotes around those paths with spaces in them, otherwise Apache may not like them and give a configuration error. Eg.,

```
Alias /media/ "C:/Users/Pin Li/Desktop/Tutorial/mysite/media/"
```

**Comment by pinli111** [comment]
Thank you very much. But there is new error which is Internal server error 500.
with these error in apache log:
mod_wsgi (pid=9700): Failed to exec Python script file 'C:/Users/Pin Li/Desktop/Tutorial/mysite/mysite/wsgi.py'.
[Tue Nov 27 21:16:06.432959 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518] mod_wsgi (pid=9700): Exception occurred processing WSGI script 'C:/Users/Pin Li/Desktop/Tutorial/mysite/mysite/wsgi.py'.
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518] Traceback (most recent call last):\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "C:/Users/Pin Li/Desktop/Tutorial/mysite/mysite/wsgi.py", line 16, in <module>\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]     application = get_wsgi_application()\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "C:\\Users\\Pin Li\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]     django.setup(set_prefix=False)\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "C:\\Users\\Pin Li\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\django\\__init__.py", line 19, in setup\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "C:\\Users\\Pin Li\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\django\\conf\\__init__.py", line 57, in __getattr__\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]     self._setup(name)\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "C:\\Users\\Pin Li\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\django\\conf\\__init__.py", line 44, in _setup\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]     self._wrapped = Settings(settings_module)\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "C:\\Users\\Pin Li\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\django\\conf\\__init__.py", line 107, in __init__\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]     mod = importlib.import_module(self.SETTINGS_MODULE)\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "C:\\Users\\Pin Li\\AppData\\Local\\Programs\\Python\\Python37\\lib\\importlib\\__init__.py", line 127, in import_module\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked\r
[Tue Nov 27 21:16:06.458097 2018] [wsgi:error] [pid 9700:tid 1312] [client ::1:65518] ModuleNotFoundError: No module named 'mysite'\r

Do you know what`s wrong with this ?

**Comment by GrahamDumpleton** [comment]
You haven't set ``WSGIPythonPath`` to tell mod_wsgi where your project code is.

**Comment by lenheard** [comment]
I'm sure you are tired of answering this question... but I just can't get rid of this problem...
Any assistance will be apreciated

[Thu Dec 26 12:27:09.163073 2019] [mpm_winnt:crit] [pid 7200:tid 648] AH00419: master_main: create child process failed. Exiting.
[Thu Dec 26 12:37:36.062001 2019] [mpm_winnt:notice] [pid 14104:tid 688] AH00455: Apache/2.4.41 (Win64) mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Thu Dec 26 12:37:36.062977 2019] [mpm_winnt:notice] [pid 14104:tid 688] AH00456: Apache Lounge VS16 Server built: Aug  9 2019 16:46:32
[Thu Dec 26 12:37:36.062977 2019] [core:notice] [pid 14104:tid 688] AH00094: Command line: 'C:\\Apache24\\bin\\httpd.exe -d C:/Apache24'
[Thu Dec 26 12:37:36.065906 2019] [mpm_winnt:notice] [pid 14104:tid 688] AH00418: Parent: Created child process 15520
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: **No module named 'encodings'**

**mod_wsgi-express output...**
(venv) C:\Dev\Django\spsm>mod_wsgi-express module-config
LoadModule wsgi_module "c:/dev/django/spsm/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/dev/django/spsm/venv"

(venv) C:\Dev\Django\spsm>


**Here is my httpd.conf..**

.
.
LoadFile "c:/Dev/python36/python36.dll"
LoadModule wsgi_module "c:/dev/django/spsm/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/dev/django/spsm/venv/"

    Alias /static /Dev/Django/spsm/static
    <Directory /Dev/Django/spsm/static>
        Require all granted
    </Directory>
    Alias /media /Dev/Django/spsm/media
    <Directory /Dev/Django/spsm/media>
        Require all granted
    </Directory>
    <Directory /Dev/Django/spsm>
        Require all granted
    </Directory>
    <Directory /Dev/Django/spsm/spsm>
            Require all granted
    </Directory>
    WSGIScriptAlias / "/Dev/Django/spsm/spsm/wsgi.py"
	WSGIPythonPath "c:/Dev/Django/spsm/venv/;c:/Dev/Django/spsm/venv/Lib/site-packages/;c:/Dev/Django/spsm/venv/scripts/;c:/Dev/Django/spsm/"

**My directory structure...:**
C:\Dev\Django\spsm
├── dashboard
|  ├── admin.py
|  ├── apps.py
|  ├── migrations
|  ├── models.py
|  ├── templates
|  ├── tests.py
|  ├── urls.py
|  ├── views.py
|  ├── __init__.py
|  └── __pycache__
├── manage.py
├── spsm
|  ├── settings.py
|  ├── urls.py
|  ├── wsgi.py
|  ├── __init__.py
|  └── __pycache__
├── static
├── venv
|  ├── Lib
|  └── Scripts
└── media

**Comment by lenheard** [comment]
Thank you... I cracked it..!!!
with the help from https://github.com/GrahamDumpleton/mod_wsgi/issues/245

The problem was actually with PyCharm. It creates the virtualenv for you when you create a new project... But sadly incorrect.

So.. I installed virtualenv and created my venv with 'virtualenv venv

Then all of a sudden 'pip install mod_wsgi' installed successfully and 'Apache HTTP Server' started up just fine
Thank you very much..!!
