### ISSUE TITLE
[Wed Nov 28 13:24:59.479577 2018] [wsgi:error] [pid 4612:tid 1080] [client 192.168.10.254:50052] UnicodeEncodeError: 'charmap' codec can't encode characters in position 1886-1891: character maps to <undefined>\r

### ISSUE THREAD

**Issue by am2222** [GrahamDumpleton/mod_wsgi#375]
Hi,
I have faced this error on one of the server's which I have used mod_wsgi with python 3.6 and Django 2.1.1 and Apache 4.2 64bit , My problem is the fact that My site only works with specific URLs and others return 404 error, while this error appears only when I use apache and mod_wsgi and when I switch to Django's development server (the one which runs on 8000 port) this error disappears and works fine, even when I run apache and test with '127.0.0.1' on port 80 which is apache's port It works fine but if I use the server's IP it shows this error.
Could this be due to mod_wsgi error? Or I have to investigate somewhere else to find the solution?
thanks

**Comment by GrahamDumpleton** [comment]
It is more likely due to wrong Apache configuration, or setting up Django routes in a way which doesn't match the Apache configuration. Impossible to guess without seeing the Apache configuration for mod_wsgi you used, as well as what you have for Django ``urls.py`` file. Finally, are you hosting only one Python web application with mod_wsgi, or more than one?

**Comment by am2222** [comment]
@GrahamDumpleton  thanks very much for your reply. well I am using one python web application on the server. The reason why I am confused is that for example these urls has different responses

`http://127.0.0.1:8000/geosuite/disabledlistajax/?draw=7&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=family&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=number&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=nationalcode&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=10&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=address&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=disabled_id&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=id&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1543645502583`

The above one works fine as it uses django's development server

`http://127.0.0.1/geosuite/disabledlistajax/?draw=7&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=family&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=number&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=nationalcode&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=10&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=address&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=disabled_id&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=id&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1543645502583`
this one works fine. It is configured and uses Apache (127.0.0.1:80)

`http://*.*.*.*:8084/geosuite/disabledlistajax/?draw=7&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=family&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=number&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=nationalcode&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=10&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=address&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=disabled_id&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=id&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1543645502583`
This returns 404, I am just using my servers ip wich is mapped on apaches ip and and port (127.0.0.1:80)


`http://*.*.*.*:8084/geosuite/disabledlistajax/`
this one works fine again.

This situation is true for my post requests too. 

here is my `urls.py`

`urlpatterns = [
                  re_path(r'reports/(?P<id>.*)$', Report),
                  re_path(r'reports_geojson/$', getreports_geojson, name='getreports_geojson'),
                  re_path(r'load_report/(?P<id>.*)$', load_report, name='load_report'),
                  re_path(r'reporters/(?P<id>.*)$', Reporter),
                  re_path(r'reportlistajax/$', ReportListAjax, name='ReportListAjax'),
                  re_path(r'disabledlistajax/$', DisabledListAjax, name='DisabledListAjax'),

                  re_path(r'geosuite/mnguserreportslist/$', mnguserreports, name='mnguserreports'),
                  re_path(r'geosuite/mngdisabled/$', mngdisabled, name='mngdisabled'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)`

I can provide apache's configuration too if it is needed

**Comment by GrahamDumpleton** [comment]
I need to see the parts of Apache configuration you added for mod_wsgi. I don't need the whole Apache configuration.

**Comment by am2222** [comment]
[error.log](https://github.com/GrahamDumpleton/mod_wsgi/files/2635653/error.log)

this is apache's log error and also its configuration

```

LoadModule wsgi_module "c:/program files/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/program files/python36"
Alias /static/ D:/Django/DjangoFreamwork/gasnetwork/GasNetwork/staticfiles/

<Directory D:/Django/DjangoFreamwork/gasnetwork/GasNetwork/>
    AllowOverride none
    Require all granted
</Directory>




# this can go in either server config, virtual host, directory or .htaccess
WSGIPassAuthorization On

WSGIScriptAlias /  D:/Django/DjangoFreamwork/gasnetwork/GasNetwork/GasNetwork/wsgi.py
WSGIPythonPath D:/Django/DjangoFreamwork/gasnetwork/GasNetwork/GasNetwork/

<Directory D:/Django/DjangoFreamwork/gasnetwork/GasNetwork/GasNetwork/>
<Files wsgi.py>
Require all granted
</Files>
</Directory>

ProxyRequests Off
<Proxy /geoserver>
   Order deny,allow
   Allow from all
</Proxy>
ProxyPass /geoserver http://localhost:8080/geoserver
ProxyPassReverse  /geoserver http://localhost:8080/geoserver
ProxyPreserveHost On
```

**Comment by GrahamDumpleton** [comment]
Why are you using port 8084 in some requests?

Are you template errors with accessing undefined variables and character encoding issues occurring (being logged), for the same request.

**Comment by am2222** [comment]
@GrahamDumpleton the difference in ports is due to servers administrator's configuration. they have mapped 8084 on port 80 of my virtual machine. yes they are for the same request but I am confused why they work on 127.0.0.1 which uses apache too but they do not work on server's ip?

**Comment by GrahamDumpleton** [comment]
Are you watching the access log of Apache to see if you request is even handled. Maybe 8084 doesn't map to the host/port you think it does and is hitting some other server.

**Comment by GrahamDumpleton** [comment]
I can only suggest you temporarily change the Apache configuration to have ``WSGIScriptAlias`` point at a test WSGI application that displays back the request. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#displaying-request-environment

You can then verify whether the request arrives as you expect it to.

**Comment by GrahamDumpleton** [comment]
Actually, use:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/tests/environ.wsgi

The example in docs is still Python 2.

**Comment by am2222** [comment]
@GrahamDumpleton thanks very much, I'll check and report the results, thanks

**Comment by am2222** [comment]
@GrahamDumpleton thanks, the fact was that the server's firewall was blocking requests, now it is working, thanks
