### ISSUE TITLE
wsgi_module not found on windows

### ISSUE THREAD

**Issue by mostafa8026** [GrahamDumpleton/mod_wsgi#377]
After installing the **mod_wsgi** with `pip` correctly, and inserted its config related stuff to the **http.conf (apache)**. The wsgi_module was loaded successfully as shown in the log below:

> **[Mon Dec 10 10:39:39.048697 2018] [wsgi:info] [pid 16708:tid 692]** mod_wsgi (pid=16708): Python home c:/users/.../appdata/local/programs/python/python37.

> **[Mon Dec 10 10:39:39.048697 2018] [wsgi:info] [pid 16708:tid 692]** mod_wsgi (pid=16708): Initializing Python.

> **[Mon Dec 10 10:39:39.081683 2018] [wsgi:info] [pid 16708:tid 692]** mod_wsgi (pid=16708): Attach interpreter ''.

> **[Mon Dec 10 10:39:39.084682 2018] [wsgi:info] [pid 16708:tid 692]** mod_wsgi (pid=16708): Adding 'E:/projects/python/...' to path.

>**[Mon Dec 10 10:39:39.089662 2018] [wsgi:info] [pid 16708:tid 692]** mod_wsgi (pid=16708): Imported 'mod_wsgi'.

But at the apache modules, the wsgi_module says *No module file* as shown in the picture below:

[![enter image description here][1]][1]

And when I click on the *wsgi_module*, this output is displayed:

> There is 'LoadModule wsgi_module modules/mod_wsgi.so' line in
> httpd.conf file but there no 'mod_wsgi.so' file in
> apachex.y.z/modules/ directory.

It is my http.conf lines which are associated with the mod_wsgi:

    LoadFile "c:/users/.../appdata/local/programs/python/python37/python37.dll"
    LoadModule wsgi_module "c:/users/.../appdata/local/programs/python/python37/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
    WSGIPythonHome "c:/users/.../appdata/local/programs/python/python37"
    WSGIPythonPath "E:/projects/python/..."
    WSGIScriptAlias /scripts "E:/projects/python/.../.../wsgi.py"

    DocumentRoot "E:\\projects\\python\\...\\...\\..."
    <Directory "E:\\projects\\python\\...\\...\\...">
    	<Files wsgi.py>
    		Allow From all
    	</Files>
        #
        # Possible values for the Options directive are "None", "All",
        # or any combination of:
        #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
        #
        # Note that "MultiViews" must be named *explicitly* --- "Options All"
        # doesn't give it to you.
        #
        # The Options directive is both complicated and important.  Please see
        # http://httpd.apache.org/docs/2.4/mod/core.html#options
        # for more information.
        #
        Options +Indexes +FollowSymLinks +Multiviews +ExecCGI
    
        #
        # AllowOverride controls what directives may be placed in .htaccess files.
        # It can be "All", "None", or any combination of the keywords:
        #   AllowOverride FileInfo AuthConfig Limit
        #
        AllowOverride all
    	Allow From all
    
        #
        # Controls who can get stuff from this server.
        #
    	#   onlineoffline tag - don't remove
        Require local
    </Directory>

  [1]: https://i.stack.imgur.com/k6y5d.png

**Comment by GrahamDumpleton** [comment]
Which suggests you may have both:

```
LoadModule wsgi_module modules/mod_wsgi.so
```

and:

```
LoadModule wsgi_module "c:/users/.../appdata/local/programs/python/python37/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
```

in your Apache configuration file. If you don't have the first line, then it is probably just the GUI admin tool for your Apache distribution being stupid in that it assumes the modules will always be in the Apache modules directory, whereas ``LoadModule`` can technically load them from anywhere.

**Comment by mostafa8026** [comment]
I finally set up the mod_wsgi module, but the 500 internal server occurred. with this error log:

> No module named 'dspDjango'

**Comment by GrahamDumpleton** [comment]
Which means that if it is a module installed using ``pip install``, that the ``WSGIPythonHome`` isn't pointing at the Python installation or Python virtual environment it is installed in.

If a local package/module in your project, then ``WSGIPythonPath`` is pointing at the location for your project correctly.

**Comment by mostafa8026** [comment]
thank for your comment, but I still can't start it. I just don't know where is the error. :((

**Comment by GrahamDumpleton** [comment]
Where is ``dspDjango`` installed?

From command line if you run Python interpreter and enter:

```
import dspDjango
print(dspDjango.__file__)
```

what do you get?

**Comment by mostafa8026** [comment]
thanks for your response, I handle this situation with WSGIScriptAlias and adding handler for WSGI-script. but I confront a new problem which I open a new issue #380 .

**Comment by mostafa8026** [comment]
Thanks for your response, My problem has been resolved and no need to keep this issue open.

**Comment by RicardoSantosDeveloper** [comment]
@mostafa8026 How did you solve the problem with "wsgi_module not found on windows" ?
I'm having the same problem.

**Comment by GrahamDumpleton** [comment]
Please don’t ask about fresh problems of your own on existing issues. Create a new issue and provide all details on your problem on the new issue.

**Comment by mostafa8026** [comment]
@RicardoSantosDeveloper , I can solve the problems with the help of @GrahamDumpleton , just review the answers and if you can't find your solution, please ask it with more details in a new issue.
