### ISSUE TITLE
FileNotFoundError at /path/ with WSGI/Apache

### ISSUE THREAD

**Issue by floriancartuta** [GrahamDumpleton/mod_wsgi#381]
Hello,

**Context:** Have set-up a small site in Django where the user upload a file, it is then processed and results can be downloaded. Everything works fine when I am doing this from Django directly, but when I access my app from Apache, I get a '[Errno 2] No such file or directory' when the application is looking for uploaded file ('test_OK.csv') into an upload directory. The main app page is accessed successfully also from Apache, the problem appears when trying to upload the file.
I am using Apache+Django+mod_wsgi.

Although I saved myself the file to be processed ('test_OK.csv') into ~/forecast/upload/ directory, still I get same error. So, considering that from Django everything works fine and the problem only appears when I access from Apache, I assume that the difference is made by mod_wsgi.  

> FileNotFoundError at /forecast/upload/
[Errno 2] No such file or directory: 'upload/test_OK.csv'
Request Method: 	POST
Request URL: 	http://localhost/forecast/upload/
Django Version: 	2.1.4
Exception Type: 	FileNotFoundError
Exception Value: 	
[Errno 2] No such file or directory: 'upload/test_OK.csv'
Exception Location: 	/home/florian/workdev/myproject/forecast/views.py in handle_uploaded_file, line 59

**Traceback:**

File "/home/florian/workdev/venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)
File "/home/florian/workdev/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)
File "/home/florian/workdev/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/florian/workdev/myproject/forecast/views.py" in upload
  26.         handle_uploaded_file(request.FILES['file'], str(request.FILES['file']),period)
File "/home/florian/workdev/myproject/forecast/views.py" in handle_uploaded_file
  59.     with open('upload/' + filename, 'wb+') as destination:
Exception Type: FileNotFoundError at /forecast/upload/
Exception Value: [Errno 2] No such file or directory: 'upload/test_OK.csv'

florian@desktop:~/workdev/myproject$ tail -n 10 /var/log/apache2/error.log
[Thu Dec 20 03:36:19.461848 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]   File "/home/florian/workdev/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Thu Dec 20 03:36:19.461855 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]     response = self.process_exception_by_middleware(e, request)
[Thu Dec 20 03:36:19.461861 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]   File "/home/florian/workdev/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Thu Dec 20 03:36:19.461868 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Dec 20 03:36:19.461874 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]   File "/home/florian/workdev/myproject/forecast/views.py", line 26, in upload
[Thu Dec 20 03:36:19.461880 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]     handle_uploaded_file(request.FILES['file'], str(request.FILES['file']),period)
[Thu Dec 20 03:36:19.461887 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]   File "/home/florian/workdev/myproject/forecast/views.py", line 59, in handle_uploaded_file
[Thu Dec 20 03:36:19.461893 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340]     with open('upload/' + filename, 'wb+') as destination:
[Thu Dec 20 03:36:19.461902 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340] FileNotFoundError: [Errno 2] No such file or directory: 'upload/test_OK.csv'
[Thu Dec 20 03:36:19.461941 2018] [wsgi:error] [pid 5532:tid 140031663744768] [remote 127.0.0.1:38340] 
florian@desktop:~/workdev/myproject$

**Comment by GrahamDumpleton** [comment]
Read:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#application-working-directory

You need to construct absolute pathnames for files, you can't use a relative path as the current working directory of the process is usually not where your code is.

**Comment by floriancartuta** [comment]
Thanks, I will dig into.

**Comment by floriancartuta** [comment]
Hello, I replaced all paths with absolute paths. There is some progress but now I have another and more strange issue: the file processing function starts to work (I can see in the error.log) and then hangs and it timeout
florian@desktop:~$ tail -n 10 /var/log/apache2/error.log
[Thu Dec 20 19:04:39.350072 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32796]     
[Thu Dec 20 19:04:39.350077 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32796]   """, UserWarning)
[Thu Dec 20 19:04:39.472676 2018] [wsgi:error] [pid 10808:tid 139702485468928] [remote ::1:32796] Not Found: /forecast/logo.jpg
[Thu Dec 20 19:04:48.804213 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32800] forecast
[Thu Dec 20 19:04:48.808798 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32800] file  test_OK.csv
[Thu Dec 20 19:04:48.808860 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32800] filename  test_OK.csv
[Thu Dec 20 19:04:48.809113 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32800] history: /home/florian/workdev/myproject/upload/test_OK.csv
[Thu Dec 20 19:04:48.836754 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32800] **<<Starting:>>  AB**
[Thu Dec 20 19:04:48.867147 2018] [wsgi:error] [pid 10808:tid 139702586263296] [remote ::1:32800] Fit ARIMA: order=(1, 1, 1) seasonal_order=(1, 1, 1, 12); AIC=nan, BIC=nan, Fit time=nan seconds
[Thu Dec 20 21:09:48.932874 2018] [wsgi:error] [pid 10811:tid 139702611441408] [client ::1:32800] **Timeout when reading response headers from daemon process** 'myproject': /home/florian/workdev/myproject/myproject/wsgi.py, referer: http://localhost/forecast/

>

**Comment by floriancartuta** [comment]
I did find a solution on https://stackoverflow.com/questions/40413171/django-webfaction-timeout-when-reading-response-headers-from-daemon-process

**Comment by GrahamDumpleton** [comment]
I will close this issue now then since you seem to have it working.
