### ISSUE TITLE
undefined symbol: _Py_ZeroStruct 

### ISSUE THREAD

**Issue by hbfl** [GrahamDumpleton/mod_wsgi#385]
with apache2-2.4.37 and Python-3.6.5, apache cannot load mod_wsgi.so into the server, this Problem is with a 32bit and 64bit build. With Python-2.7.15 no Problem

Please can you help with this issue
Thanks

**Comment by hbfl** [comment]
ohh, mod_wsgi version 4.5.8 and latest 4.6.5

**Comment by GrahamDumpleton** [comment]
Ensure the following:

* That Apache/Python/mod_wsgi are all compiled for either 32 bit or 64 bit. Don't mix them.
* That mod_wsgi is compiled for the same Python version as any Python virtual environment being used. You cannot force mod_wsgi compiled for Python 2.7 to use a Python virtual environment created using Python 3.6.
* That if using Python compiled from source code, that it was installed with shared library support.
* That if using a Python installation in non standard location, that ``LD_RUN_PATH`` was set when mod_wsgi was compiled so that location of library directory for the non standard location is known, and that a system Python of same version is not incorrectly being picked.

Other than that, state whether using system Python and what version it is. State whether using Python virtual environment and what Python version it was created from.

**Comment by hbfl** [comment]
Sorry, but my english is not so good
I use system Python, mod_wsgi was always  from apache load

python was build from source with shared library support, python was installed in the standard location

/usr/lib{64}/python3.6

I grep over the source 3.6.5, no symbol found
BUILD/Python-3.6.5> grep -R '_Py_ZeroStruct' *
BUILD/Python-3.6.5> 

but in Python 2.7.15 it was found
BUILD/Python-2.7.15> grep -R '_Py_ZeroStruct' *
Include/boolobject.h:PyAPI_DATA(PyIntObject) _Py_ZeroStruct, _Py_TrueStruct;
Include/boolobject.h:#define Py_False ((PyObject *) &_Py_ZeroStruct)
Include/intobject.h:_Py_TrueStruct and _Py_ZeroStruct in boolobject.h; don't use this.

Binary file libpython2.7.so.1.0 matches

**Comment by GrahamDumpleton** [comment]
Just to clarify, you say you are using system Python, but also seem to indicate that you built Python from source code and installed it in the standard location. If you have overwritten the real system Python with one compiled from source code, you will cause lots of problems. You should never install Python from source code yourself and install it under ``/usr``. Is this what you did?

**Comment by hbfl** [comment]
Include/boolobject.h

in python2.7 
/* Don't use these directly */
PyAPI_DATA(PyIntObject) _Py_ZeroStruct, _Py_TrueStruct;

in python3.? 
/* Don't use these directly */
PyAPI_DATA(struct _longobject) _Py_FalseStruct, _Py_TrueStruct;

**Comment by hbfl** [comment]
I installed python always clear, I maintained this project many years and have in the past no problems with python and mod_wsgi, Now we will switch over to python3 and have a missing symbol

**Comment by GrahamDumpleton** [comment]
Find the ``mod_wsgi.so`` file and from in the directory it is located in, run:

```
ldd mod_wsgi.so
```

Can you do that much for me.

**Comment by hbfl** [comment]
eis:/ # ldd /var/lib/apache2-mod_wsgi/python3/mod_wsgi.so 
        linux-vdso.so.1 (0x00007fff60195000)
        libpython3.6m.so.1.0 => /usr/lib64/libpython3.6m.so.1.0 (0x00007ff86a801000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff86a5e4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff86a3e0000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007ff86a1dd000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff869edf000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff869b38000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff86afa5000)

**Comment by GrahamDumpleton** [comment]
Now run:

```
nm /var/lib/apache2-mod_wsgi/python3/mod_wsgi.so | grep Py_ZeroStruct
```

**Comment by hbfl** [comment]
OK, but why crasht  apache with python3 

eis:/ # nm /var/lib/apache2-mod_wsgi/python3/mod_wsgi.so | grep Py_ZeroStruct
                 U _Py_ZeroStruct

**Comment by hbfl** [comment]
in python3 that symbol is missing

eis:/ # nm /usr/lib64/libpython2.7.so.1.0|  grep Py_ZeroStruct
nm: /usr/lib64/libpython2.7.so.1.0: no symbols

eis:/ # nm /usr/lib64/libpython3.6m.so.1.0 |  grep Py_ZeroStruct
eis:/ #

**Comment by hbfl** [comment]
eis:/ # nm /var/lib/apache2-mod_wsgi/python2/mod_wsgi.so | grep Py_ZeroStruct
nm: /var/lib/apache2-mod_wsgi/python2/mod_wsgi.so: no symbols
eis:/ # 

eis:/ # strings  /usr/lib64/libpython3.6m.so.1.0 |  grep Py_ZeroStructeis:/ # strings  /usr/lib64/libpython2.7.so.1.0 |  grep Py_ZeroStruct
_Py_ZeroStruct
eis:/ #

**Comment by hbfl** [comment]
OK, Thanks for your time, I fond the mistake, I droped the python2-dev package and so I see that the python.h comes from python2, grrr

Thanks, thanks
