### ISSUE TITLE
RHEL: httpd: Syntax error on line 55 of /etc/httpd/conf/httpd.conf: Cannot load /etc/httpd/modules/mod_wsgi.so into server: libpython3.6m.so.rh-python36-1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pitamganai** [GrahamDumpleton/mod_wsgi#386]
Hello,
I have RHEL7.

**I have installed mod_wsgi**
`[root@ mod_wsgi-4.6.5]# make install
/bin/apxs -i -S LIBEXECDIR=/usr/lib64/httpd/modules -n 'mod_wsgi' src/server/mod_wsgi.la
/usr/lib64/httpd/build/instdso.sh SH_LIBTOOL='/usr/lib64/apr-1/build/libtool' src/server/mod_wsgi.la /usr/lib64/httpd/modules
/usr/lib64/apr-1/build/libtool --mode=install install src/server/mod_wsgi.la /usr/lib64/httpd/modules/
libtool: install: install src/server/.libs/mod_wsgi.so /usr/lib64/httpd/modules/mod_wsgi.so
libtool: install: install src/server/.libs/mod_wsgi.lai /usr/lib64/httpd/modules/mod_wsgi.la
libtool: install: install src/server/.libs/mod_wsgi.a /usr/lib64/httpd/modules/mod_wsgi.a
libtool: install: chmod 644 /usr/lib64/httpd/modules/mod_wsgi.a
libtool: install: ranlib /usr/lib64/httpd/modules/mod_wsgi.a
libtool: finish: PATH="/opt/rh/rh-python36/root/usr/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/sbin" ldconf                                                   ig -n /usr/lib64/httpd/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/lib64/httpd/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
chmod 755 /usr/lib64/httpd/modules/mod_wsgi.so
`
**Python 3.6 is installed in the /opt/rh/ directory.
Got this while as output of where is python3**
` whereis python3
python3: /usr/local/bin/python3.7-config /usr/local/bin/python3 /usr/local/bin/python3.7m /usr/local/lib/python3.7 /opt/rh/rh-python36/root/usr/bin/python3.6m-x86_64-config /opt/rh/rh-python36/root/usr/bin/python3.6m /opt/rh/rh-python36/root/usr/bin/python3.6-config /opt/rh/rh-python36/root/usr/bin/python3 /opt/rh/rh-python36/root/usr/bin/python3.6m-config /opt/rh/rh-python36/root/usr/bin/python3.6`

**Getting the following error while I am starting httpd server:**
`Dec 29 04:05:47 server systemd[1]: Starting The Apache HTTP Server...
Dec 29 04:05:47 server httpd[29499]: httpd: Syntax error on line 55 of /etc/httpd/conf/httpd.conf: Cannot load /etc/httpd/modules/mod_wsgi.so into server: libpython3.6m.so.rh-python36-1.0: cannot open shared object file: No such file or directory
Dec 29 04:05:47 server systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Dec 29 04:05:47 server kill[29501]: kill: cannot find process ""
Dec 29 04:05:47 server systemd[1]: httpd.service: control process exited, code=exited status=1
Dec 29 04:05:47 server systemd[1]: Failed to start The Apache HTTP Server.
Dec 29 04:05:47 server systemd[1]: Unit httpd.service entered failed state.
Dec 29 04:05:47 server systemd[1]: httpd.service failed.
[root@ conf]# cd /usr/local/lib
`
How can we proceed with this.
Please let me know If I need to provide any more information on it.

**Comment by GrahamDumpleton** [comment]
As the message says, and as is mentioned for the problem in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#unable-to-find-python-shared-library

you need to set the ``LD_RUN_PATH`` environment variable during linking to include the directory where the Python shared library is located.

Thus set ``LD_RUN_PATH`` in same command as the ``make install``. You must though do a ``make clean`` just in case it doesn't relink without rebuilding.

```
make clean
LD_RUN_PATH=/opt/rh/rh-python36/root/usr/lib64 make install
```
