### ISSUE TITLE
RHEL :  mod_wsgi (pid=6388): Failed to exec Python script file '/var/www/yourapplication/yourapplication.wsgi'

### ISSUE THREAD

**Issue by pitamganai** [GrahamDumpleton/mod_wsgi#387]
Hell Graham,

I am getting this error at the time of wsgi file is getting loaded to activate virtualenv .

 [Sun Dec 30 15:54:23.156461 2018] [wsgi:error] [pid 6388] [client ] mod_wsgi (pid=6388): Failed to exec Python script file '/var/www/yourapplication/yourapplication.wsgi'.
[Sun Dec 30 15:54:23.156527 2018] [wsgi:error] [pid 6388] [client ] mod_wsgi (pid=6388): Exception occurred processing WSGI script '/var/www/yourapplication/yourapplication.wsgi'.
[Sun Dec 30 15:54:23.157697 2018] [wsgi:error] [pid 6388] [client] Traceback (most recent call last):
[Sun Dec 30 15:54:23.157744 2018] [wsgi:error] [pid 6388] [client ]   File "/var/www/yourapplication/yourapplication.wsgi", line 8, in <module>
[Sun Dec 30 15:54:23.157751 2018] [wsgi:error] [pid 6388] [client ]     from yourapplication import app
[Sun Dec 30 15:54:23.157761 2018] [wsgi:error] [pid 6388] [client ]   File "/var/www/yourapplication/yourapplication.py", line 15, in <module>
[Sun Dec 30 15:54:23.157766 2018] [wsgi:error] [pid 6388] [client]     import pandas as pd
[Sun Dec 30 15:54:23.157774 2018] [wsgi:error] [pid 6388] [client]   File "/var/www/yourapplication/venv/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
[Sun Dec 30  2018] [wsgi:error] [pid 6388] [client 146.215.174.155:54747]     "Missing required dependencies {0}".format(missing_dependencies))
[Sun Dec 30 15:54:23.157802 2018] [wsgi:error] [pid 6388] [client ] ImportError: Missing required dependencies ['numpy']
[root@usculslmwb01v logs]# cd /var/www/yourapplication

My .Wsgi setting is :+1: 
activate_this = '/var/www/yourapplication/venv/bin/activate_this.py'
with open(activate_this) as file_:
    exec(file_.read(), dict(__file__=activate_this))

import sys
sys.path.insert(0, '/var/www/yourapplication')

from yourapplication import app

It seems it is not able to activate virtualenv.
Please let me know if I have to provide any information.

**Comment by GrahamDumpleton** [comment]
For the recommended way of using Python virtual environment see:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

Using ``activate_this`` should be last resort option.

Also ensure using mod_wsgi compiled for same Python version as being used, and preferably use daemon mode of mod_wsgi if you aren't doing so currently. Finally, ensure that the user Apache runs as has access to directories/files for the Python virtual environment.

**Comment by pitamganai** [comment]
Hello Graham,
Looking at the error log I think virual environment is being activated .

[Mon Dec 31 06:24:44.377027 2018] [mpm_prefork:notice] [pid 13134] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Dec 31 06:24:50.044852 2018] [core:notice] [pid 13356] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Dec 31 06:24:50.045730 2018] [suexec:notice] [pid 13356] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Dec 31 06:24:50.055617 2018] [so:warn] [pid 13356] AH01574: module wsgi_module is already loaded, skipping
[Mon Dec 31 06:24:50.058982 2018] [auth_digest:notice] [pid 13356] AH01757: generating secret for digest authentication ...
[Mon Dec 31 06:24:50.059755 2018] [lbmethod_heartbeat:notice] [pid 13356] AH02282: No slotmem from mod_heartmonitor
[Mon Dec 31 06:24:50.063367 2018] [mpm_prefork:notice] [pid 13356] AH00163: Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/4.6.5 Python/3.6 configured -- resuming normal operations
[Mon Dec 31 06:24:50.063392 2018] [core:notice] [pid 13356] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Dec 31 06:24:58.963810 2018] [wsgi:error] [pid 13361] [client ] mod_wsgi (pid=13361): Failed to exec Python script file '/var/www/yourapplication/yourapplication.wsgi'.
[Mon Dec 31 06:24:58.963879 2018] [wsgi:error] [pid 13361] [client ] mod_wsgi (pid=13361): Exception occurred processing WSGI script '/var/www/yourapplication/yourapplication.wsgi'.
[Mon Dec 31 06:24:58.964631 2018] [wsgi:error] [pid 13361] [client ] Traceback (most recent call last):
[Mon Dec 31 06:24:58.964663 2018] [wsgi:error] [pid 13361] [client ]   File "/var/www/yourapplication/yourapplication.wsgi", line 8, in <module>
[Mon Dec 31 06:24:58.964668 2018] [wsgi:error] [pid 13361] [client ]     from yourapplication import app
[Mon Dec 31 06:24:58.964674 2018] [wsgi:error] [pid 13361] [client ]   File "/var/www/yourapplication/yourapplication.py", line 15, in <module>
[Mon Dec 31 06:24:58.964677 2018] [wsgi:error] [pid 13361] [client ]     import pandas as pd
[Mon Dec 31 06:24:58.964682 2018] [wsgi:error] [pid 13361] [client]   File "/var/www/yourapplication/venv/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
[Mon Dec 31 06:24:58.964685 2018] [wsgi:error] [pid 13361] [client]     "Missing required dependencies {0}".format(missing_dependencies))
[Mon Dec 31 06:24:58.964700 2018] [wsgi:error] [pid 13361] [client] ImportError: Missing required dependencies ['numpy']
[Mon Dec 31 06:27:55.850586 2018] [wsgi:error] [pid 13358] [client ] mod_wsgi (pid=13358): Failed to exec Python script file '/var/www/yourapplication/yourapplication.wsgi'


because pandas is trying to trying to be loaded from virtual env ...
[Mon Dec 31 06:24:58.964682 2018] [wsgi:error] [pid 13361] [client]   File "/var/www/yourapplication/venv/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>


I have run the application in native mode as well but it working fine. Not sure why pandas is getting dependency error on numpy.

My pandas version - 0.23.4
numpy version -1.12.0b1
I have installed them offline.

**Comment by pitamganai** [comment]
Hello Graham,
The warning of loading wsgi_module is gone now  as it was being loaded from .conf file inside  module.conf.d directory. but now no log is coming to the /etc/httpd/conf.d/logs/error_log and access_lof file.

here is the yourapplication.wsgi file content

`python_home = '/var/www/yourapplication/sonyvenv'

import sys
import site

# Calculate path to site-packages directory.

python_version = '.'.join(map(str, sys.version_info[:2]))
site_packages = python_home + '/lib/python%s/site-packages' % python_version

# Add the site-packages directory.

site.addsitedir(site_packages)
from yourapplication import app   `

and here is my mod_wsgi.conf file content.

`<VirtualHost *:80>
    ServerName USCULSLMWB01v.am.sony.com
    WSGIDaemonProcess yourapplication user=user1 group=group1 threads=5

    WSGIScriptAlias / /var/www/yourapplication/yourapplication.wsgi
    WSGIScriptReloading On
    <Directory /var/www/yourapplication>
        WSGIProcessGroup yourapplication
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>
</VirtualHost>`

**Comment by pitamganai** [comment]
Now I have the below error

[Tue Jan 01 06:23:03.409273 2019] [wsgi:error] [pid 29907] [remote 61245] Traceback (most recent call last):
[Tue Jan 01 06:23:03.409316 2019] [wsgi:error] [pid 29907] [remote 61245]   File "/var/www/yourapplication/yourapplication.wsgi", line 14, in <module>
[Tue Jan 01 06:23:03.409325 2019] [wsgi:error] [pid 29907] [remote 61245]     from yourapplication_old import application
[Tue Jan 01 06:23:03.409350 2019] [wsgi:error] [pid 29907] [remote 61245] ModuleNotFoundError: No module named 'yourapplication_old'
[Tue Jan 01 06:23:03.665261 2019] [wsgi:error] [pid 29907] [remote 61254] mod_wsgi (pid=29907): Failed to exec Python script file '/var/www/yourapplication/yourapplication.wsgi'.
[Tue Jan 01 06:23:03.665309 2019] [wsgi:error] [pid 29907] [remote 61254] mod_wsgi (pid=29907): Exception occurred processing WSGI script '/var/www/yourapplication/yourapplication.wsgi'.
[Tue Jan 01 06:23:03.665381 2019] [wsgi:error] [pid 29907] [remote 61254] Traceback (most recent call last):
[Tue Jan 01 06:23:03.665401 2019] [wsgi:error] [pid 29907] [remote 61254]   File "/var/www/yourapplication/yourapplication.wsgi", line 14, in <module>
[Tue Jan 01 06:23:03.665405 2019] [wsgi:error] [pid 29907] [remote :61254]     from yourapplication_old import application
[Tue Jan 01 06:23:03.665419 2019] [wsgi:error] [pid 29907] [remote ] ModuleNotFoundError: No module named 'yourapplication_old'

my application path is /var/www/yourapplication/yourapplication_old.py
and wsgi script library path is /var/www/yourapplication/yourapplication.wsgi

**Comment by GrahamDumpleton** [comment]
You need to tell mod_wsgi where your application code is.

See the ``python-path`` option to ``WSGIDaemonProcess``.

The use of ``site.addsitedir()`` is also not the preferred method for indicating the location of the virtual environment. Use the ``python-home`` open described in the docs for virtual environments.

**Comment by pitamganai** [comment]
Once i am starting httpd server
getting the error like this.

[Tue Jan 01 16:26:23.275076 2019] [mpm_prefork:notice] [pid 30786] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Jan 01 16:29:15.680977 2019] [core:notice] [pid 32033] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Tue Jan 01 16:29:15.682395 2019] [suexec:notice] [pid 32033] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Jan 01 16:29:15.704398 2019] [auth_digest:notice] [pid 32033] AH01757: generating secret for digest authentication ...
[Tue Jan 01 16:29:15.705390 2019] [lbmethod_heartbeat:notice] [pid 32033] AH02282: No slotmem from mod_heartmonitor
[Tue Jan 01 16:29:15.709374 2019] [mpm_prefork:notice] [pid 32033] AH00163: Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/4.6.5 Python/3.6 configured -- resuming normal operations
[Tue Jan 01 16:29:15.709410 2019] [core:notice] [pid 32033] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f41e1566880 (most recent call first):
[Tue Jan 01 16:29:16.710525 2019] [core:notice] [pid 32033] AH00052: child pid 32034 exit signal Aborted (6)
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

**Comment by GrahamDumpleton** [comment]
Where back to you not picking up the virtual environment, or mixing Python installations again.

Show me your current config and how you are referencing the virtual environment.

Also add at global scope, before any ``VirtualHost`` if you have one, not in it:

```
WSGIRestrictEmbedded On
```

This will trigger an error on requests in case where your configuration is wrong and you are delegating to the daemon process group correctly.

**Comment by pitamganai** [comment]
Here is my configuration in mod_wsgi.conf file

<VirtualHost *:80>
    ServerName USCULSLMWB01v.am.sony.com
    WSGIDaemonProcess yourapplication python-path=/var/www/yourapplication python-home=/var/www/yourapplication/venv user=user1 group=group1 threads=5
    WSGIScriptAlias / /var/www/yourapplication/yourapplication.wsgi
    WSGIScriptReloading On
    <Directory /var/www/yourapplication>
        WSGIProcessGroup yourapplication
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>
</VirtualHost>

And here is my content of /var/www/yourapplication/yourapplication.wsgi--

from yourapplication_old import application

**Comment by pitamganai** [comment]
Now mod_wsgi.conf is looking like this. I am not getting 

WSGIRestrictEmbedded On
<VirtualHost *:80>
ServerName USCULSLMWB01v.am.sony.com
WSGIDaemonProcess yourapplication python-path=/var/www/yourapplication python-home=/var/www/yourapplication/venv user=user1 group=group1 threads=5
WSGIScriptAlias / /var/www/yourapplication/yourapplication.wsgi
WSGIScriptReloading On
<Directory /var/www/yourapplication>
WSGIProcessGroup yourapplication
WSGIApplicationGroup %{GLOBAL}
Order deny,allow
Allow from all
<VirtualHost>

but I am not getting the below error

` Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings' `

But application is not reachable from browser and no error log is coming now.

**Comment by pitamganai** [comment]
It seems it is pointing to same path  which is for python3.6
[root@server modules]# ldd mod_wsgi.so
        linux-vdso.so.1 =>  (0x00007ffea07ea000)
        libpython3.6m.so.rh-python36-1.0 => /opt/rh/rh-python36/root/usr/lib64/l                                                                                                               ibpython3.6m.so.rh-python36-1.0 (0x00007fbd1b9e4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbd1b7c8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fbd1b5c4000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fbd1b3c1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fbd1b0bf000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fbd1acf2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbd1c146000)
[root@server modules]# source scl_source enable rh-python36
[root@server modules]# python3
Python 3.6.3 (default, Jan  9 2018, 10:19:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.prefix)
/opt/rh/rh-python36/root/usr
>>> exit()

Is the issue being caused by software collection command   I am issuing manually to enable python3.6 bash? might be this not being used while python is referred by wsgi(might be it is referring to system default python 2.7) ..  Just guessing

**Comment by GrahamDumpleton** [comment]
When you ran ``ldd`, was ``LD_LIBRARY_PATH`` environment variable already set?

How was this mod_wsgi module compiled in the first place? The Software Collections Library (SCL) doesn't include a compiled mod_wsgi package that I know of, so you must have built it yourself. Apologies if we dealt with that part in prior discussion somewhere, I have a bad memory.

Is ``user1`` the actual owner of all directories/files under the directory ``/var/www/yourapplication``?

**Comment by pitamganai** [comment]
Now it seems configuration is good. But I have come back to first error again

[Wed Jan 02 07:03:32.061228 2019] [wsgi:error] [pid 2562] [remote ] mod_wsgi (pid=2562): Failed to exec Python script file '/var/www/yourapplication/yourapplication.wsgi'.
[Wed Jan 02 07:03:32.061322 2019] [wsgi:error] [pid 2562] [remote ] mod_wsgi (pid=2562): Exception occurred processing WSGI script '/var/www/yourapplication/yourapplication.wsgi'.
[Wed Jan 02 07:03:32.062051 2019] [wsgi:error] [pid 2562] [remote ] Traceback (most recent call last):
[Wed Jan 02 07:03:32.062080 2019] [wsgi:error] [pid 2562] [remote ]   File "/var/www/yourapplication/yourapplication.wsgi", line 14, in <module>
[Wed Jan 02 07:03:32.062085 2019] [wsgi:error] [pid 2562] [remote ]     from yourapplication import app
[Wed Jan 02 07:03:32.062091 2019] [wsgi:error] [pid 2562] [remote ]   File "/var/www/yourapplication/yourapplication.py", line 15, in <module>
[Wed Jan 02 07:03:32.062095 2019] [wsgi:error] [pid 2562] [remote ]     import pandas as pd
[Wed Jan 02 07:03:32.062100 2019] [wsgi:error] [pid 2562] [remote ]   File "/var/www/yourapplication/venv/lib64/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
[Wed Jan 02 07:03:32.062103 2019] [wsgi:error] [pid 2562] [remote ]     "Missing required dependencies {0}".format(missing_dependencies))
[Wed Jan 02 07:03:32.062117 2019] [wsgi:error] [pid 2562] [remote ] ImportError: Missing required dependencies ['numpy']

as per pandas docs .. there should be NumPy: 1.9.0 or higher to make pandas work.
But I have numpy  1.12.0b1  in my system. 

I was unable to install numpy latest version as there was no *tar.gz file. so I installed 1.12.0b1 but not sure why it is giving this error. Any Idea on this?

**Comment by pitamganai** [comment]
It seems we are almost there. I have upgraded numpy to v 1.15 but getting permission denied error for `multiarray.cpython-36m-x86_64-linux-gnu.so`  module . python is unable to import this module

I am getting this error..
[Wed Jan 02 09:09:42.614683 2019] [wsgi:error] [pid 3023] [remote]     raise ImportError(msg)
[Wed Jan 02 09:09:42.614693 2019] [wsgi:error] [pid 3023] [remote] ImportError:
[Wed Jan 02 09:09:42.614697 2019] [wsgi:error] [pid 3023] [remote] Importing the multiarray numpy extension module failed.  Most
[Wed Jan 02 09:09:42.614700 2019] [wsgi:error] [pid 3023] [remote] likely you are trying to import a failed build of numpy.
[Wed Jan 02 09:09:42.614704 2019] [wsgi:error] [pid 3023] [remote] If you're working with a numpy git repo, try `git clean -xdf` (removes all
[Wed Jan 02 09:09:42.614709 2019] [wsgi:error] [pid 3023] [remote] files not under version control).  Otherwise reinstall numpy.
[Wed Jan 02 09:09:42.614712 2019] [wsgi:error] [pid 3023] [remote]
[Wed Jan 02 09:09:42.614716 2019] [wsgi:error] [pid 3023] [remote] Original error was: /var/www/yourapplication/venv/lib64/python3.6/site-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Permission denied
[Wed Jan 02 09:09:42.614720 2019] [wsgi:error] [pid 3023] [remote]
[Wed Jan 02 09:14:08.039215 2019] [wsgi:error] [pid 3023] [remote] mod_wsgi (pid=3023): Failed to exec Python script file '/var/www/yourapplication/yourapplication.wsgi'.
[Wed Jan 02 09:14:08.039287 2019] [wsgi:error] [pid 3023] [remote] mod_wsgi (pid=3023): Exception occurred processing WSGI script '/var/www/yourapplication/yourapplication.wsgi'.
[Wed Jan 02 09:14:08.039503 2019] [wsgi:error] [pid 3023] [remote] Traceback (most recent call last):
[Wed Jan 02 09:14:08.039527 2019] [wsgi:error] [pid 3023] [remote]   File "/var/www/yourapplication/venv/lib64/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
[Wed Jan 02 09:14:08.039531 2019] [wsgi:error] [pid 3023] [remote]     from . import multiarray
[Wed Jan 02 09:14:08.039547 2019] [wsgi:error] [pid 3023] [remote] ImportError: /var/www/yourapplication/venv/lib64/python3.6/site-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Permission denied
the owner of the all files and the directory is user1.

**Comment by pitamganai** [comment]
It is working fine now.. 
Thanks a lot Graham... Learnt a lot for you and this issue..

**Comment by GrahamDumpleton** [comment]
What was the final change you made? The last error sometimes is indicative of SELinux profile issues.

**Comment by pitamganai** [comment]
Yes that's correct...

**Comment by GrahamDumpleton** [comment]
Okay, I will close this issue for now then and we will see how you go. Thanks for being patient as we worked it out.

**Comment by pitamganai** [comment]
I changed it from embedding to permissive.
