### ISSUE TITLE
error mac when mod_wsgi-express start-server

### ISSUE THREAD

**Issue by nlp4whp** [GrahamDumpleton/mod_wsgi#388]
Hello, 
here is a error when I try this

`$ mod_wsgi-express start-server`

`httpd (mod_wsgi-express) : Syntax error on line 156 of /var/tmp/mod_wsgi-localhost:8000:501/httpd.conf: Cannot load /Users/henrywhp/anaconda3/envs/nlp/lib/libpython3.5m.dylib into server: dlopen(/Users/henrywhp/anaconda3/envs/nlp/lib/libpython3.5m.dylib, 10): no suitable image found.  Did find:\n\t/Users/henrywhp/anaconda3/envs/nlp/lib/libpython3.5m.dylib: code signature in (/Users/henrywhp/anaconda3/envs/nlp/lib/libpython3.5m.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.\n\t/Users/henrywhp/anaconda3/envs/nlp/lib/libpython3.5m.dylib: stat() failed with errno=22
`
I have no idea how to fix it. pls give me some advice...thank you

here's my running env :
mac os: 10.14
python:3.5
Apache:2.4.34

**Comment by GrahamDumpleton** [comment]
You can't use Apple supplied Apache server on macOS 10.14. They made it unusable for third party Apache modules unless they are signed by approved Apple developer. No one has told me how they can be ad-hoc signed so could be worked as yet.

Your choices are to use Homebrew to install Apache and use it.

An alternative is you can try:

```
pip uninstall mod_wsgi
pip install mod_wsgi-httpd
pip install mod_wsgi
```

This installs Apache from source code into the Python installation. You can only use ``mod_wsgi-express start-server`` this way and can't integrate mod_wsgi into Apache and do manual configuration.

* https://pypi.org/project/mod_wsgi-httpd/

**Comment by nlp4whp** [comment]
> You can't use Apple supplied Apache server on macOS 10.14. They made it unusable for third party Apache modules unless they are signed by approved Apple developer. No one has told me how they can be ad-hoc signed so could be worked as yet.
> 
> Your choices are to use Homebrew to install Apache and use it.
> 
> An alternative is you can try:
> 
> ```
> pip uninstall mod_wsgi
> pip install mod_wsgi-httpd
> pip install mod_wsgi
> ```
> This installs Apache from source code into the Python installation. You can only use `mod_wsgi-express start-server` this way and can't integrate mod_wsgi into Apache and do manual configuration.
> 
> * https://pypi.org/project/mod_wsgi-httpd/

let me try it now, thanks a loooooot !

**Comment by nlp4whp** [comment]
> You can't use Apple supplied Apache server on macOS 10.14. They made it unusable for third party Apache modules unless they are signed by approved Apple developer. No one has told me how they can be ad-hoc signed so could be worked as yet.
> 
> Your choices are to use Homebrew to install Apache and use it.
> 
> An alternative is you can try:
> 
> ```
> pip uninstall mod_wsgi
> pip install mod_wsgi-httpd
> pip install mod_wsgi
> ```
> This installs Apache from source code into the Python installation. You can only use `mod_wsgi-express start-server` this way and can't integrate mod_wsgi into Apache and do manual configuration.
> 
> * https://pypi.org/project/mod_wsgi-httpd/

**Comment by nlp4whp** [comment]
> > You can't use Apple supplied Apache server on macOS 10.14. They made it unusable for third party Apache modules unless they are signed by approved Apple developer. No one has told me how they can be ad-hoc signed so could be worked as yet.
> > Your choices are to use Homebrew to install Apache and use it.
> > An alternative is you can try:
> > ```
> > pip uninstall mod_wsgi
> > pip install mod_wsgi-httpd
> > pip install mod_wsgi
> > ```
> > This installs Apache from source code into the Python installation. You can only use `mod_wsgi-express start-server` this way and can't integrate mod_wsgi into Apache and do manual configuration.
> > 
> > * https://pypi.org/project/mod_wsgi-httpd/

reinstall apache from Homebrew cannot solve it, but this from you helps me solve it

`pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip`

**Comment by GrahamDumpleton** [comment]
If you use Homebrew, you need to make sure you set ``APXS`` environment variable when running ``configure`` to the Homebrew version. If you don't do that you will not get any further.

Doing ``pip install`` with that URL would be no different to doing ``pip install mod_wsgi``. Either way, as far as I know you still can't use it in Apache from Apple. Not sure if ``mod_wsgi-express start-server`` works either still with Apache from Apple. So no idea what you are suggesting was the solution.
