### ISSUE TITLE
Error using mod_wsgi-express for Django

### ISSUE THREAD

**Issue by andyb3** [GrahamDumpleton/mod_wsgi#389]
Hi,

I'm attempting to serve a django app using `python manage.py runmodwsgi`

I am getting a 500 Internal Server Error.

Where can I find the error logs to try and figure out what's going wrong?

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>

Many thanks,
Andy

**Comment by GrahamDumpleton** [comment]
You need to look in the error log file for the details. Or run with ``--log-to-terminal`` option so errors display on terminal so you can see them.

**Comment by andyb3** [comment]
`--log-to-terminal` did the trick, thanks for the help!

Do I need to do anything special to make mod_wsgi-express work with a Django app installed within a conda environment?

I sourced the environment in the terminal then ran `python manage.py runmodwsgi`, however the error I'm getting is a python `ImportError: No module named...` suggesting it's running outside of the conda envrionment.

**Comment by GrahamDumpleton** [comment]
Was ``mod_wsgi`` installed into the Conda environment using ``pip``? It has to be installed into the virtual environment you are using.

**Comment by andyb3** [comment]
Yes I installed using `pip install mod_wsgi` with the environment active.

 In the error message above it appears to be using mod_wsgi installed within the correct environment (gel2mdt)
`[Fri Jan 04 09:26:34.623448 2019] [wsgi:error] [pid 12927:tid 140196157249408]   File "/home/mokaguys/miniconda2/envs/gel2mdt/lib/python3.6/site-packages/mod_wsgi/server/__init__.py", line 1395, in __init__`

**Comment by GrahamDumpleton** [comment]
From the command line, if you run Python after activating the virtual environment, what do you get when in the interpreter:

```
import gelweb
print(gelweb.__file__)
```

Anaconda does various things which screw things up. I generally have workarounds in place. I need to think about what they were and what to ask. Tell me what you get for that for now. I will be heading off to sleep soon though.

**Comment by andyb3** [comment]
Thanks for the assistance! It's greatly appreciated. This is the output I get from the above command:

```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gelweb
>>> print(gelweb.__file__)
/home/mokaguys/Apps/GeL2MDT/gelweb/gelweb/__init__.py
>>>
```

**Comment by GrahamDumpleton** [comment]
Is ``/home/mokaguys/Apps/GeL2MDT/gelweb`` the Django project directory?

Have you changed the structure of how the Django settings file is handled? Did you correct the calculation of ``BASE_DIR`` in it if you moved it down one directory level.

From memory it relies in using ``BASE_DIR`` to work out where your project is. If you haven't fixed this up correctly if you changed from normal Django settings file structure, it will not find your project code.

**Comment by andyb3** [comment]
You're right!! That was the issue. I adjusted the BASE_DIR path and now it's working!

Interestingly it was running fine using the inbuilt Django dev server, which had made me assume the settings file was correct, but clearly not!

Thank you for all your help! Have a great weekend.

**Comment by GrahamDumpleton** [comment]
The Django ``runserver`` doesn't rely on the value of ``BASE_DIR``. It relies on the fact that command line Python will add the directory ``manage.py`` is in to the Python module search path. Can't rely on that with ``mod_wsgi-express`` because is embedded system and so it needs to rely on ``BASE_DIR`` to know parent directory to the project. If ``BASE_DIR`` is not present it makes a guess, but again, if someone has moved location of ``settings.py`` to lower directory, that fallback will not work either. So need to rely on ``BASE_DIR`` being correct.

**Comment by andyb3** [comment]
Ah I see! That makes sense. Thanks again for all your help.
