### ISSUE TITLE
AttributeError: module 'mod_wsgi' has no attribute 'subscribe_events'

### ISSUE THREAD

**Issue by arafay993** [GrahamDumpleton/mod_wsgi#392]
Hi, I am using django 2.0, python 3.5, apache2, mod_wsgi. But my site is performing very slow. For finding the cause of the issue, I have embedded script as suggested by Graham Dumpleton in this link https://github.com/GrahamDumpleton/mod_wsgi/issues/228#issuecomment-331365102
But I am facing following error:
AttributeError: module 'mod_wsgi' has no attribute 'subscribe_events'. Any help would be much appreciated

**Comment by GrahamDumpleton** [comment]
You are most likely using a version of mod_wsgi which is too old. Many Linux distributions ship quite old mod_wsgi versions. You should always avoid the mod_wsgi the Linux distribution ships and compile it yourself from source code.

So, what version of mod_wsgi are you using?

**Comment by arafay993** [comment]
Many thanks for your reply. I have installed mod_wsgi in my python3.5 also and has version mod-wsgi==4.6.5. I have previously installed in linux mint using following command:
sudo apt-get install libapache2-mod-wsgi-py3

**Comment by GrahamDumpleton** [comment]
Installing using ``pip install mod_wsgi`` into your Python installation is different to what Apache may be using. If you have installed ``libapache2-mod-wsgi-py3`` then Apache would be using that. So you need to know what version of mod_wsgi ``libapache2-mod-wsgi-py3`` is.

**Comment by arafay993** [comment]
I am not been able to find out which version of mod_wsgi has been used by libapache2-mod-wsgi-py3? can you tell me please?

**Comment by GrahamDumpleton** [comment]
Try instructions in:

* https://stackoverflow.com/questions/18885820/how-to-check-the-version-before-install-packages-using-apt-get

to work out version of package.

**Comment by arafay993** [comment]
Thanks, libapache2-mod-wsgi-py3 version is 4.3.0-1

**Comment by GrahamDumpleton** [comment]
Too old. See if they have a very recent version. Otherwise you will need to uninstall ``libapache2-mod-wsgi-py3`` and configure Apache to use the version you installed into your Python using ``pip``. Details in:

* https://pypi.org/project/mod_wsgi/

See section 'Connecting into Apache installation' near bottom.
