### ISSUE TITLE
AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/mod_wsgi-localhost:8080:0/httpd.conf

### ISSUE THREAD

**Issue by YooYongGil** [GrahamDumpleton/mod_wsgi#393]
I am a Korean web developer. I will speak in advance. I am Korean.
I would appreciate your understanding if you can not speak English.
--------------------------------------------------------------------------------------------------------
root@TOTOBOT:/var/www/html/mysite# mod_wsgi-express start-server --user=www-data --group=www-data --port=8080 /var/www/html/mysite/mysite/wsgi.py
Server URL         : http://localhost:8080/
Server Root        : /tmp/mod_wsgi-localhost:8080:0
Server Conf        : /tmp/mod_wsgi-localhost:8080:0/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8080:0/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8

---------------------------------------------------------------------------------------------------
On the Web, the connection is good. However, there is no API connection to the kakao platform.
I have analyzed the error.log in / tmp / mod_wsgi-localhost: 8080: 0.
Again, the connection is good on the web.  The TELNET and PING commands also work well.

[Mon Jan 21 17:21:41.319836 2019] [core:warn] [pid 10751:tid 139778681853824] AH00098: pid file /tmp/mod_wsgi-localhost:8080:0/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jan 21 17:21:41.320393 2019] [mpm_event:notice] [pid 10751:tid 139778681853824] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/4.6.5 Python/3.4 configured -- resuming normal operations
[Mon Jan 21 17:21:41.320432 2019] [core:notice] [pid 10751:tid 139778681853824] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/mod_wsgi-localhost:8080:0/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'

-------------------------------------------------------------------------------------------------------------
I think there is a problem with /tmp/mod_wsgi-localhost:8080:0/httpd.conf 

[error_log.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2778254/error_log.txt)
[httpd.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2778256/httpd.conf.txt)
[wsgi.py.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/2778259/wsgi.py.txt)

**Comment by YooYongGil** [comment]
![default](https://user-images.githubusercontent.com/44956972/51470768-2bf25300-1db8-11e9-8b32-7208fdaef303.JPG)


Connecting with the CURL command causes encoding problems.
However, w3m http: // localhost: 8080 command will connect.

and,
In django, do you want to test it locally with the python mange.py runserver command?

**Comment by YooYongGil** [comment]
This is my current server address. When you connect from the outside, you have entered your own IP: 8080. Connection from outside will be successful. My server IP is open to the public, but I am very curious about the error_log in /tmp/mod_wsgi-localhost:8080:0/httpd.conf.
![default](https://user-images.githubusercontent.com/44956972/51472063-c4d69d80-1dbb-11e9-8743-8f3491667a78.JPG)

**Comment by GrahamDumpleton** [comment]
If you are talking about the error:

```
[Mon Jan 21 17:21:41.319836 2019] [core:warn] [pid 10751:tid 139778681853824] AH00098: pid file /tmp/mod_wsgi-localhost:8080:0/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
```

it isn't something that is usually a problem. It usually indicates that Apache was killed using ``SIGKILL`` signal instead of ``SIGTERM`` and as a result Apache was denied the opportunity to shutdown properly and clean things up.

**Comment by YooYongGil** [comment]
![default](https://user-images.githubusercontent.com/44956972/51472514-0582e680-1dbd-11e9-8f75-7675768283b0.JPG)

I ended it by pressing Ctrl + c and ran it again as shown.

![2](https://user-images.githubusercontent.com/44956972/51472617-5d215200-1dbd-11e9-826d-c85a4793e725.JPG)
I initialized the error_log file and reopened it.

**Comment by GrahamDumpleton** [comment]
Which looks fine and normal, so I am not sure I understand what problem it is that you are asking about.

Also, can you avoid closing and re-opening the issue each time. If using the GitHub web interface, just click on the Green Comment button and it should add the comment but not close it.
