### ISSUE TITLE
mac os + apache 2.4.33 + python 3.7.2 + django 2.1.5 + mod_wsgi 4.6.5 (Site can't be reached)

### ISSUE THREAD

**Issue by abijithmg** [GrahamDumpleton/mod_wsgi#396]
Hey Graham,

We are facing issues in running the server(Site can't be reached) after python upgrade from 2.x to 3.7.2 Our server config:

* Mac OS 10.13.6 (High Sierra)
* Apache 2.4.33 custom installation
* Python 3.7.2 (Brew install python3)
* Django 2.1.5 (Installed via pip inside python 3 env)
* mod_wsgi 4.6.5 (Installed via pip inside python 3 env)

I have added the following two lines(mod_wsgi-express module-config) in httpd.conf file replacing the 2.7 references: 
`LoadModule wsgi_module "/../ENV3/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-darwin.so"  `
`WSGIPythonHome "/../ENV3" `

Also in httpd-vhosts.conf:  
`WSGIDaemonProcess mysite.com processes=2 threads=15 display-name=%{GROUP} python-home=/Library/WebServer/Documents/ENV3 python-path=/Library/WebServer/Documents/mysite` 
 `WSGIProcessGroup mysite.com  ` 
`WSGIScriptAlias / /Library/WebServer/Documents/mysite/wsgi.py`

After restarting the server, when we hit the URL in the browser the page continues to load for a while(2-5 mins) and later displays "This site can’t be reached"

It would be great if you can guide us with valuable suggestions. Thanks!

**Comment by abijithmg** [comment]
Yes, I used `mod_wsgi-express module-config` to generate these two lines:
`LoadModule wsgi_module "/../MASP_ENV3/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-darwin.so" `
`WSGIPythonHome "/../MASP_ENV3" `
Correspondingly, I have added these two lines in `httpd.conf` file and removed the 2.7 references.

As per your recommendation `WSGIApplicationGroup %{GLOBAL}` is already present in the file and also this statement `WSGIPassAuthorization On`

Coming to logs, I have constantly monitored `apache error_log and access_log files` using tail command. No logs are being logged in both files when the server URL is hit in the browser. The page loads for 2-5 mins and later displays "This site can’t be reached"

Should I upgrade the apache version to `2.4.38`?    Will, that resolves the issue?

**Comment by GrahamDumpleton** [comment]
What are you using in the URL, a hostname, an IP address, or localhost/127.0.0.1? If there is nothing even in the access log, sounds more like your request is not even getting to the server, possibly blocked by a firewall such as Little Snitch.

**Comment by GrahamDumpleton** [comment]
Even with ``LogLevel`` set to ``debug`` are you sure you get nothing in the Apache error logs when making a request against it.

**Comment by abijithmg** [comment]
oh ok. Currently, it is set to `LogLevel warn` 
Let me change it to `debug` and monitor what's happening. Thanks for the suggestions till now.

**Comment by abijithmg** [comment]
Hey Graham,
Here are the logs, when i set apache LogLevel from warn to debug:
```
Current thread 0x00007fff9e944380 (most recent call first):
[Wed Feb 06 19:41:49.388932 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60563 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.388995 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60563
[Wed Feb 06 19:41:49.389046 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60561 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389073 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60561
[Wed Feb 06 19:41:49.389101 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60557 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389137 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60557
[Wed Feb 06 19:41:49.389178 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60553 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389206 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60553
[Wed Feb 06 19:41:49.389233 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60552 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389265 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60552
[Wed Feb 06 19:41:49.389286 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60551 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389302 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60551
[Wed Feb 06 19:41:49.389323 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60550 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389344 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60550
[Wed Feb 06 19:41:49.388739 2019] [wsgi:info] [pid 60566:tid 140735853904768] mod_wsgi (pid=60566): Initializing Python.
[Wed Feb 06 19:41:49.389079 2019] [wsgi:info] [pid 60567:tid 140735853904768] mod_wsgi (pid=60567): Python home /Library/WebServer/Documents/MASP_ENV3/lib/python3.7.
[Wed Feb 06 19:41:49.389509 2019] [wsgi:info] [pid 60567:tid 140735853904768] mod_wsgi (pid=60567): Initializing Python.
[Wed Feb 06 19:41:49.389370 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60560 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389562 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60560
[Wed Feb 06 19:41:49.389597 2019] [core:notice] [pid 1010:tid 140735853904768] AH00052: child pid 60549 exit signal Abort trap (6)
[Wed Feb 06 19:41:49.389741 2019] [core:error] [pid 1010:tid 140735853904768] AH00546: no record of generation 0 of exiting child 60549
[Wed Feb 06 19:41:49.389918 2019] [wsgi:info] [pid 60569:tid 140735853904768] mod_wsgi (pid=60569): Starting process 'appsecure.accenture.com' with uid=1, gid=1 and threads=15.
[Wed Feb 06 19:41:49.390239 2019] [wsgi:info] [pid 60568:tid 140735853904768] mod_wsgi (pid=60568): Python home /Library/WebServer/Documents/MASP_ENV3/lib/python3.7.
[Wed Feb 06 19:41:49.390336 2019] [wsgi:info] [pid 60568:tid 140735853904768] mod_wsgi (pid=60568): Initializing Python.
[Wed Feb 06 19:41:49.392127 2019] [wsgi:info] [pid 60569:tid 140735853904768] mod_wsgi (pid=60569): Python home /Library/WebServer/Documents/MASP_ENV3/lib/python3.7.
[Wed Feb 06 19:41:49.392267 2019] [wsgi:info] [pid 60569:tid 140735853904768] mod_wsgi (pid=60569): Initializing Python.
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fff9e944380 (most recent call first):
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

httpd-vhosts.conf:

```
<VirtualHost *:80>
    Redirect permanent / https://mysite.com
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot "/Library/WebServer/Documents/DigitalSecurityFramework"
    #DocumentRoot "/Library/WebServer/Documents/DigitalSecurityFramework/support"
    Alias /static/ /Library/WebServer/Documents/DigitalSecurityFramework/static/
    Alias /uploads/ /Library/WebServer/Documents/DigitalSecurityFramework/uploads/
    ServerName mysite.com
    SSLEngine on
    SSLCertificateFile "/Users/digitalsecurity/dsf_ssl_crt_keys/mysite_com.crt"
    SSLCertificateKeyFile "/Users/digitalsecurity/dsf_ssl_crt_keys/mysite_com.key"
    SSLCertificateChainFile "/Users/digitalsecurity/dsf_ssl_crt_keys/DigiCertCA.crt"

    ServerAdmin appsecure.dev@mysite.com

    ErrorLog /var/log/apache2/dsf_error.log
    TransferLog /var/log/apache2/dsf_access.log

    #<Directory "/Library/WebServer/Documents/DigitalSecurityFramework/support">
    #    Order deny,allow
    #    Allow from all
    #    Require all granted
    #</Directory>

    <Directory "/Library/WebServer/Documents/DigitalSecurityFramework/static">
        Require all granted
    </Directory>

    <Directory "/Library/WebServer/Documents/DigitalSecurityFramework/uploads">
        Require all granted
    </Directory>

    <Directory "/Library/WebServer/Documents/DigitalSecurityFramework/DigitalSecurity">
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
   # WSGIDaemonProcess mysite.com processes=2 threads=15 display-name=%{GROUP} python-home=/Library/WebServer/Documents/MASP_ENV3/lib/python3.7 python-path=/Library/WebServer/Documents/DigitalSecurityFramework
    WSGIDaemonProcess mysite.com processes=2 threads=15 display-name=%{GROUP} python-path=/Library/WebServer/Documents/DigitalSecurityFramework:/Library/WebServer/Documents/MASP_ENV3/lib/python3.7/site-packages
    WSGIProcessGroup mysite.com
    WSGIScriptAlias / /Library/WebServer/Documents/DigitalSecurityFramework/DigitalSecurity/wsgi.py
</VirtualHost>
```

**Comment by GrahamDumpleton** [comment]
The message:

```
Python home /Library/WebServer/Documents/MASP_ENV3/lib/python3.7
```

says your configuration is wrong.

The value of ``WSGIPythonHome`` or ``python-home``, if it needs to be set, is supposed to be the value of ``sys.prefix``, which is the root of the installation, not the library directory. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#location-of-the-virtual-environment
* https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#multiple-python-versions

If it is wrong, it will not be able to find the ``encodings`` module or ``site`` module.

Also, when changing configuration in this situation, make sure you complete stop Apache, don't do a reload/restart.

Finally, since using daemon mode, ensure you disable embedded mode by using:

```
WSGIRestrictEmbedded On
```

at global scope in Apache config file.

**Comment by abijithmg** [comment]
Thanks a lot, Graham. It's working now after I moved the virtual env location to Mac OS's python3 installation directory.

**Comment by GrahamDumpleton** [comment]
I'll assume everything is good now then and will close this issue.
