### ISSUE TITLE
Pip Error Installing Obspy

### ISSUE THREAD

**Issue by neos1004** [GrahamDumpleton/mod_wsgi#398]
Hi, I tried to install obspy in WIndows 10 using Python 3.7 64-bit.
I did it like this....

C:\Users\Novrizal>pip install obspy
Collecting obspy
  Downloading https://files.pythonhosted.org/packages/b4/fa/87a6b3612d7060c585cb0aec518ede6a75fc5b002897d3991633d857fc19/obspy-1.1.1.zip (23.9MB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 23.9MB 14kB/s
Requirement already satisfied: future>=0.12.4 in c:\users\novrizal\appdata\roaming\python\python37\site-packages\future-0.17.1-py3.7.egg (from obspy) (0.17.1)
Requirement already satisfied: numpy>=1.6.1 in c:\users\novrizal\appdata\roaming\python\python37\site-packages (from obspy) (1.16.1)
.
.
.
.
.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\program files\python37\libs /LIBPATH:c:\program files\python37\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64 /EXPORT:PyInit_libgse2_Windows_64bit_py37 build\temp.win-amd64-3.7\Release\obspy\io\gse2\src\GSE_UTI\gse_functions.obj /OUT:build\lib.win-amd64-3.7\obspy\lib\libgse2_Windows_64bit_py37.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\obspy\io\gse2\src\GSE_UTI\libgse2_Windows_64bit_py37.cp37-win_amd64.lib
    LINK : error LNK2001: unresolved external symbol PyInit_libgse2_Windows_64bit_py37
    build\temp.win-amd64-3.7\Release\obspy\io\gse2\src\GSE_UTI\libgse2_Windows_64bit_py37.cp37-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\program files\python37\libs /LIBPATH:c:\program files\python37\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64 /EXPORT:PyInit_libgse2_Windows_64bit_py37 build\temp.win-amd64-3.7\Release\obspy\io\gse2\src\GSE_UTI\gse_functions.obj /OUT:build\lib.win-amd64-3.7\obspy\lib\libgse2_Windows_64bit_py37.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\obspy\io\gse2\src\GSE_UTI\libgse2_Windows_64bit_py37.cp37-win_amd64.lib" failed with exit status 1120

    ----------------------------------------
Command ""c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Novrizal\\AppData\\Local\\Temp\\pip-install-hqhd7mll\\obspy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Novrizal\AppData\Local\Temp\pip-record-un4x966m\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Novrizal\AppData\Local\Temp\pip-install-hqhd7mll\obspy\

C:\Users\Novrizal>

**Comment by GrahamDumpleton** [comment]
I can't see that this has anything to do with ``mod_wsgi``. You would be better off asking on StackOverflow or any support channel for ``obspy``.
