### ISSUE TITLE
mod_wsgi-4.2.7 doesn't compile with Python 3.5 on debian

### ISSUE THREAD

**Issue by soumen0** [GrahamDumpleton/mod_wsgi#399]
Hi Graham

As mentioned in my[ earlier post](https://github.com/GrahamDumpleton/mod_wsgi/issues/24#issuecomment-465761876), I did compiled with Python3.5 and it didn't work

friday@debianLabV1:~/mod_wsgi-4.6.5$ ls -ltr
total 244

-rw-r--r-- 1 friday friday  21887 Aug 14  2018 setup.py
-rw-r--r-- 1 friday friday  17383 Aug 14  2018 README.rst
-rw-r--r-- 1 friday friday    441 Aug 14  2018 MANIFEST.in
-rw-r--r-- 1 friday friday   1534 Aug 14  2018 Makefile.in
-rw-r--r-- 1 friday friday  11358 Aug 14  2018 LICENSE
-rw-r--r-- 1 friday friday    303 Aug 14  2018 CREDITS.rst
-rw-r--r-- 1 friday friday   7678 Aug 14  2018 configure.ac
-rwxr-xr-x 1 friday friday 120693 Aug 14  2018 configure
drwxr-xr-x 2 friday friday   4096 Oct 22 09:28 win32
drwxr-xr-x 2 friday friday   4096 Oct 22 09:28 tests
drwxr-xr-x 3 friday friday   4096 Oct 22 09:28 src
-rw-r--r-- 1 friday friday     59 Oct 22 09:28 setup.cfg
-rw-r--r-- 1 friday friday  21855 Oct 22 09:28 PKG-INFO
drwxr-xr-x 2 friday friday   4096 Oct 22 09:28 images
drwxr-xr-x 3 friday friday   4096 Oct 22 09:28 docs

friday@debianLabV1:~/mod_wsgi-4.6.5$ sudo ./configure --with-python=/usr/lib/python3.5

checking for apxs2... /usr/bin/apxs2
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for prctl... yes
checking Apache version... 2.4.25
./configure: line 2849: /usr/lib/python3.5: Is a directory
./configure: line 2853: /usr/lib/python3.5: Is a directory
./configure: line 2861: /usr/lib/python3.5: Is a directory
./configure: line 2866: /usr/lib/python3.5: Is a directory
./configure: line 2880: /usr/lib/python3.5: Is a directory
./configure: line 2884: /usr/lib/python3.5: Is a directory
./configure: line 2887: /usr/lib/python3.5: Is a directory
./configure: line 2890: /usr/lib/python3.5: Is a directory
./configure: line 2893: /usr/lib/python3.5: Is a directory
./configure: line 2919: /usr/lib/python3.5: Is a directory
./configure: line 2922: /usr/lib/python3.5: Is a directory
configure: creating ./config.status
config.status: creating Makefile
friday@debianLabV1:~/mod_wsgi-4.6.5$ sudo make
/usr/bin/apxs2 -c  -Wc,-g -Wc,-O2  src/server/mod_wsgi.c src/server/wsgi_*.c -L -L  -lpython
/usr/share/apr-1.0/build/libtool  --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -pipe -g -O2 -fdebug-prefix-map=/build/apache2-2.4.25=. -fstack-protector-strong -Wformat -Werror=format-security  -DBUILD_DATETIME='"2018-11-03T18:46:19"' -Wdate-time -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -g -O2  -c -o src/server/mod_wsgi.lo src/server/mod_wsgi.c && touch src/server/mod_wsgi.slo
libtool: compile:  x86_64-linux-gnu-gcc -pipe -g -O2 -fdebug-prefix-map=/build/apache2-2.4.25=. -fstack-protector-strong -Wformat -Werror=format-security -DBUILD_DATETIME=\"2018-11-03T18:46:19\" -Wdate-time -D_FORTIFY_SOURCE=2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2 -I/usr/include/apr-1.0 -I/usr/include/apr-1.0 -I/usr/include -g -O2 -c src/server/mod_wsgi.c  -fPIC -DPIC -o src/server/.libs/mod_wsgi.o
In file included from src/server/mod_wsgi.c:22:0:
src/server/wsgi_python.h:24:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
apxs:Error: Command failed with rc=65536
.
Makefile:31: recipe for target 'src/server/mod_wsgi.la' failed
make: *** [src/server/mod_wsgi.la] Error 1

**Comment by GrahamDumpleton** [comment]
You are not supposed to give the ``--with-python`` option the library path, it should be the name of the ``python`` program, or the full path to the program binary. Thus:

```
./configure --with-python=/usr/bin/python3.5
```
