### ISSUE TITLE
write error IOTimedOut

### ISSUE THREAD

**Issue by diablo2cain** [GrahamDumpleton/mod_wsgi#400]
Error below? how to fix?

![error](https://user-images.githubusercontent.com/48177224/53694613-4b997580-3d7f-11e9-9442-d30aed4f2e27.jpg)

**Comment by GrahamDumpleton** [comment]
This appears to have nothing to do with mod_wsgi, which is what this issue tracker is for. Suggest you use StackOverflow web site instead.
