### ISSUE TITLE
wsgi.input read extremly slow

### ISSUE THREAD

**Issue by yoch** [GrahamDumpleton/mod_wsgi#401]
Hi,

Uploading files (approx 2 Mb) to my WSGI application is extremly slow.

I investigated with cProfile, and it seems that it's related to mod_wsgi (method 'read' of 'mod_wsgi.Input' objects takes 0.5s per call).

Here is the profiler output (cumulative sort):

```
    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
         1    0.000    0.000   34.790   34.790 /home/ux/lib/python3/site-packages/bottle.py:1100(files)
         1    0.000    0.000   34.790   34.790 /home/ux/lib/python3/site-packages/bottle.py:1208(POST)
         1    0.000    0.000   34.692   34.692 /home/ux/lib/python3/site-packages/bottle.py:1190(body)
         1    0.001    0.001   34.692   34.692 /home/ux/lib/python3/site-packages/bottle.py:1161(_body)
        61    0.000    0.000   34.683    0.569 /home/ux/lib/python3/site-packages/bottle.py:1126(_iter_body)
        60   34.683    0.578   34.683    0.578 {method 'read' of 'mod_wsgi.Input' objects}
       2/1    0.000    0.000    0.098    0.098 /usr/lib/python3/cgi.py:405(__init__)
         1    0.000    0.000    0.098    0.098 /usr/lib/python3/cgi.py:683(read_multi)
```

What's going on there ?

**Note**: I'm using Apache/2.4.29 (Ubuntu) mod_wsgi/4.5.17 Python/3.6.

Here is my apache config:

```
WSGIDaemonProcess api user=ux group=ux python-home=/home/ux display-name='%{GROUP}' threads=16 maximum-requests=10000
WSGIScriptAlias /api /home/ux/api.wsgi process-group=api application-group=api
```

**Comment by GrahamDumpleton** [comment]
But what is your Apache MPM config and what MPM are you using? How heavily loaded is your site? Are you trying to do a stress test where you are swamping your web server with way more requests that it would normally realistically handle? What are your HTTP clients, mobile devices on potentially slow networks?

Another contributing factor is if your web server is under load, whether your application is CPU bound in some actions. Also, Python profiler could itself be interfering with things.

For getting this level of detail, you should use the mod_wsgi event mechanism to get details on each request on completion. This will tell you how much data was transferred in reading request content, in how many calls and how long it spent in reading the content. See:

* http://blog.dscpl.com.au/2015/06/implementing-request-monitoring-within.html

**Comment by yoch** [comment]
I'm using Apache event MPM, with default values. This is a test server (EC2 instance), not under particular load, and I'm using postman to send requests. But this can be related to network issue, I'll going to investigate this.

Thank you
