### ISSUE TITLE
Binary File For Apache/2.4.38 (Win32) + Python 3.7.1

### ISSUE THREAD

**Issue by ashujangra** [GrahamDumpleton/mod_wsgi#402]
Hi Team

I am using Apache/2.4.38 (Win32) (Apache Lounge VC15 Server built:   Jan 18 2019 12:31:19) and Python 3.7.1. I would like to deploy my flask app which must need compiled version of wsgi. In your documentation its just python VC10 and Apache VC10

Can you please help me on this.

**Comment by ashujangra** [comment]
Hi any update

**Comment by GrahamDumpleton** [comment]
Any sort of official binaries haven't been supplied for many years. See instead:

* https://www.lfd.uci.edu/~gohlke/pythonlibs/#mod_wsgi

Those are nothing to do with me though so can't help you with them.

The recommended thing to do is to build the binary yourself using ``pip install mod_wsgi``. See:

* https://pypi.org/project/mod_wsgi/
