### ISSUE TITLE
Target WSGI script '/var/www/backend/backend/wsgi.py' cannot be loaded as Python module.

### ISSUE THREAD

**Issue by JintoAntony** [GrahamDumpleton/mod_wsgi#403]
Complete error log : 
Target WSGI script '/var/www/backend/backend/wsgi.py' cannot be loaded as Python module.
[Wed Mar 27 06:32:18.619787 2019] [wsgi:error] [pid 19449] [remote 27.61.34.125:16372] mod_wsgi (pid=19449): Exception occurred processing WSGI script '/var/www/backend/backend/wsgi.py'.
[Wed Mar 27 06:32:18.619952 2019] [wsgi:error] [pid 19449] [remote 27.61.34.125:16372] Traceback (most recent call last):
[Wed Mar 27 06:32:18.620009 2019] [wsgi:error] [pid 19449] [remote 27.61.34.125:16372]   File "/var/www/backend/backend/wsgi.py", line 12, in <module>
[Wed Mar 27 06:32:18.620027 2019] [wsgi:error] [pid 19449] [remote 27.61.34.125:16372]     from django.core.wsgi import get_wsgi_application
[Wed Mar 27 06:32:18.620075 2019] [wsgi:error] [pid 19449] [remote 27.61.34.125:16372] ImportError: No module named 'django'

wsgi.py 
import os
from django.core.wsgi import get_wsgi_application
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
application = get_wsgi_application()

apache virtual host:
Listen 81
<VirtualHost *:81>
            WSGIDaemonProcess backendapp python-home=/var/www/backend/venv python-path=/var/www/backend
            WSGIProcessGroup backendapp
            WSGIScriptAlias / /var/www/backend/backend/wsgi.py
            ErrorLog /var/www/backend/error.log
            CustomLog /var/www/backend/access.log combined
        </VirtualHost>

Using Ubuntu 16.04 and Python3.6.

**Comment by GrahamDumpleton** [comment]
If Django is installed in that virtual environment, this is usually due to one of two things.

* The Python virtual environment was created using a different version of Python than mod_wsgi was compiled for.

* The directory/file permissions on the Python virtual environment are such that the Apache user cannot read the contents of the virtual environment.

**Comment by JintoAntony** [comment]
mod_wsgi uses python 3.5 and virtual enviroment uses python 3.6. Is that will be a problem ?

**Comment by GrahamDumpleton** [comment]
You can't mix versions like that. You must use a mod_wsgi compiled for Python 3.6. The documentation explains this in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#virtual-environment-and-python-version

**Comment by JintoAntony** [comment]
Ok. I did compiled mod_wsgi using python3.6 and updated the lib on apache mods. Now I am getting an error like Truncated or oversized response headers received from daemon process 'backendapp': /var/www/backend/backend/wsgi.py, referer: http://185.183.182.202:8000/.

Look like mod_wsgi bug. isn't it ..? 

Updated wsgi.load file witht eh following :
#LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
LoadModule wsgi_module "/usr/local/lib/python3.6/dist-packages/mod_wsgi-4.6.5-py3.6-linux-x86_64.egg/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"

**Comment by GrahamDumpleton** [comment]
Check your main Apache error log, not any virtual host error log if you have one. Do you find an error message about "Segmentation Fault" or other indication of a crash at the time.

Enable ``LogLevel`` in Apache to ``info`` rather than ``warn`` or ``err`` and capture the new mod_wsgi log messages that show can verify what happened at that time in respect of process replacement.

**Comment by JintoAntony** [comment]
Yes. I'm getting segmentation fault. 'AH00052: child pid 11043 exit signal Segmentation fault (11)'.

**Comment by GrahamDumpleton** [comment]
Any chance you can do what is explained in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb

to capture where it is crashing.

There seems to be an increase at the moment with Python or binary Python wheels being compiled against incompatible version of OpenSSL libraries compared to what Apache is linked against.

If you aren't using SSL with Apache, ensure you don't enable mod_ssl in Apache. If not using PHP, ensure you don't enable mod_php in Apache.

**Comment by JintoAntony** [comment]
ssl is disabled and mod_php is not using on this server.

**Comment by GrahamDumpleton** [comment]
Forgot the most important suggestion. Add:

```
WSGIApplicationGroup %{GLOBAL}
```

There are various third party Python packages that do not work properly in Python sub interpreters and they will crash as a result. These are problems in those packages. Forcing the use of the main interpreter context using that directive will address the problem.

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

**Comment by JintoAntony** [comment]
Hi, Already added. Also, tried with process and threads. not working.

**Comment by GrahamDumpleton** [comment]
I need to see the ``info`` level logging when using the ``WSGIApplicationGroup`` directive. If you can get the stack trace as well, even better.

**Comment by GrahamDumpleton** [comment]
Discussion died. Assuming issue was solved or gave up. Closing issue.

**Comment by Sunag3** [comment]
I am getting this error , even mod_wsgi is properly configured for latest python3 version, please help

[Wed Oct 21 20:05:27.647795 2020] [wsgi:error] [pid 18952] [remote ::1:58744] mod_wsgi (pid=18952): Target WSGI script '/var/www/project/bookmarks/bookmarks/wsgi.py' cannot be loaded as Python module.
[Wed Oct 21 20:05:27.647992 2020] [wsgi:error] [pid 18952] [remote ::1:58744] mod_wsgi (pid=18952): Exception occurred processing WSGI script '/var/www/project/bookmarks/bookmarks/wsgi.py'.
[Wed Oct 21 20:05:27.650639 2020] [wsgi:error] [pid 18952] [remote ::1:58744] Traceback (most recent call last):
[Wed Oct 21 20:05:27.650807 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "/var/www/project/bookmarks/bookmarks/wsgi.py", line 16, in <module>
[Wed Oct 21 20:05:27.650820 2020] [wsgi:error] [pid 18952] [remote ::1:58744]     application = get_wsgi_application()
[Wed Oct 21 20:05:27.650846 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "/var/www/project/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Oct 21 20:05:27.650855 2020] [wsgi:error] [pid 18952] [remote ::1:58744]     django.setup(set_prefix=False)
[Wed Oct 21 20:05:27.650881 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "/var/www/project/venv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
[Wed Oct 21 20:05:27.650890 2020] [wsgi:error] [pid 18952] [remote ::1:58744]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Wed Oct 21 20:05:27.650907 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "/var/www/project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
[Wed Oct 21 20:05:27.650920 2020] [wsgi:error] [pid 18952] [remote ::1:58744]     self._setup(name)
[Wed Oct 21 20:05:27.650936 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "/var/www/project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
[Wed Oct 21 20:05:27.650944 2020] [wsgi:error] [pid 18952] [remote ::1:58744]     self._wrapped = Settings(settings_module)
[Wed Oct 21 20:05:27.650959 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "/var/www/project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
[Wed Oct 21 20:05:27.650967 2020] [wsgi:error] [pid 18952] [remote ::1:58744]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Wed Oct 21 20:05:27.650982 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[Wed Oct 21 20:05:27.650990 2020] [wsgi:error] [pid 18952] [remote ::1:58744]     return _bootstrap._gcd_import(name[level:], package, level)
[Wed Oct 21 20:05:27.651005 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Wed Oct 21 20:05:27.651020 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Wed Oct 21 20:05:27.651054 2020] [wsgi:error] [pid 18952] [remote ::1:58744]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Wed Oct 21 20:05:27.651103 2020] [wsgi:error] [pid 18952] [remote ::1:58744] ModuleNotFoundError: No module named 'bookmarks.settings'

----------------------------------------
django.conf file

<VirtualHost *:80>
        ServerName 192.168.225.45
        DocumentRoot /var/www/

        Alias /static /var/www/project/bookmarks/static
        <Directory "/var/www/project/bookmarks/static">
                Options FollowSymLinks
                Order allow,deny
                Allow from all
                Require all granted
        </Directory>


        WSGIDaemonProcess project python-path=/var/www/project:/var/www/project/venv/lib/python3.6/site-packages
        WSGIProcessGroup project
        WSGIScriptAlias / /var/www/project/bookmarks/bookmarks/wsgi.py

        <Directory /var/www/project/bookmarks/bookmarks>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>
</VirtualHost>

**Comment by GrahamDumpleton** [comment]
@Sunag3 Please don't ask new questions as comments on existing issues, especially closed ones. If you have a new problem, you should create a new issue. That said, unless you have a strange directory layout you should be using:

```
WSGIDaemonProcess project python-home=/var/www/project/venv python-path=/var/www/project/bookmarks
WSGIProcessGroup project
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / /var/www/project/bookmarks/bookmarks/wsgi.py
```

Check again:

* https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/modwsgi/
* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

The ``WSGIApplicationGroup`` is to force use of the main Python interpreter and although not a reason for your problem, is good practice.
