### ISSUE TITLE
'Truncated or oversized response headers received from daemon process' using custom OpenSSL wrapper

### ISSUE THREAD

**Issue by nottheend** [GrahamDumpleton/mod_wsgi#404]
**Aim:**
[django](https://www.djangoproject.com/) up and running using a [custom OpenSSL Wrapper called nassl](https://github.com/nabla-c0d3/nassl)

**Versions:**
- Apache/2.4.6 (CentOS)
- OpenSSL/1.0.2k-fips
- mod_wsgi/4.6.2
- Python/3.6 

**Error:**
- WSGIDaemonProcess crashes on each request delivering a html-document
- Apache-Log:
```
[10:47:35] [wsgi:error] [pid 923] [client 10.0.37.12:38304] Truncated or oversized response headers received from daemon process 'appname': /home/user/appname/appname/wsgi.py
[10:47:35] [core:notice] [pid 919] AH00052: child pid 920 exit signal Segmentation fault (11)
[10:47:35] [wsgi:info] [pid 919] mod_wsgi (pid=920): Process 'appname' has died, deregister and restart it.
[10:47:35] [wsgi:info] [pid 919] mod_wsgi (pid=920): Process 'appname' terminated by signal 11
[10:47:35] [wsgi:info] [pid 919] mod_wsgi (pid=920): Process 'appname' has been deregistered and will no longer be monitored.
[10:47:35] [wsgi:info] [pid 944] mod_wsgi (pid=944): Initializing Python.
[10:47:35] [wsgi:info] [pid 945] mod_wsgi (pid=945): Initializing Python.
[10:47:35] [wsgi:info] [pid 946] mod_wsgi (pid=946): Starting process 'appname' with uid=48, gid=48 and threads=5.
```

- Debugging output [GDB](https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb):
```
(gdb) cont
Continuing.
Detaching after fork from child process 8297.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fbf5c7f8700 (LWP 8266)]
0x00007fbf77100956 in __strcmp_sse2 () from /lib64/libc.so.6
```

- [Here is full stack trace created with GDB](https://gist.github.com/nottheend/a3678c7eda8881c485deb27a654a45b6)

**Background info:** The application written with django is using the OpenSSL-Wrapper nassl. In this case essential to use nassl for a web application. Therefore it is also installed in the virtual python environment. Possibly the Version Python could be changed to another Python3-Version

Is there a chance to use django and nassl both in the python environment, served by mod_wsgi?

_Issue transferred from https://github.com/GrahamDumpleton/mod_wsgi/issues/390#issuecomment-477042028_

**Comment by GrahamDumpleton** [comment]
Try not installing ``nassl`` from PyPi as precompiled binary wheel. Instead of listing ``nassl`` in ``requirements.txt``, add:

```
-e git+https://github.com/nabla-c0d3/nassl/tree/2.1.2#egg=nassl
```

This will mean it is compiled for your specific OpenSSL libraries on your system

The problem with binary wheels is they will not work if they were compiled against an incompatible version of the OpenSSL libraries compare to what you system has deployed. This is a problem which keeps arising with the OpenSSl libraries.

**Comment by nottheend** [comment]
**Tried to compile `nassl`** with the suggested line in `requirements.txt`, but failed:
```
gcc: error: src/nassl/deps/zlib-1.2.11/libz.a: No such file or directory
    error: command 'gcc' failed with exit status 1
```
Seems that `gcc` is not available.

**Tried another way:**
Using [Linuxbrew](https://docs.brew.sh/Homebrew-on-Linux) it is possible to create a virtual environment with [pipenv](https://pipenv.readthedocs.io/en/latest/). Following the [nassl documentation](https://github.com/nabla-c0d3/nassl/) the libraries can be build successfully with `invoke build.all`
Installing remaining dependencies via `pip install -r requirements.txt` also works.

Deploying this newly created virtual environment fails with 
```
[14:50] [wsgi:info] [pid 9450] mod_wsgi (pid=9450): Initializing Python.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```

In the newly created environment `Python 3.7.3` is used, but the `mod_wsgi` version has been compiled for `Pyhton 3.6`

Could this problem been worked around?

**Comment by GrahamDumpleton** [comment]
You can't use a Python virtual environment for one Python version, with mod_wsgi compiled for a different Python version. That is why initialisation fails. You will need to rebuild mod_wsgi from source code to use the same Python version. You can try the ``pip install`` method. See:

* https://pypi.org/project/mod_wsgi/

**Comment by nottheend** [comment]
- [x] Rebuilt `mod_wsgi` successfully for `Python 3.7.3` using `pip install`

- [x] By following the [documentation](https://pypi.org/project/mod_wsgi/)-section _Using mod_wsgi-express with Django_ `python manage.py runmodwsgi` serves the project well 

- [x] Further, apache is configured using this command:
```
python manage.py runmodwsgi --setup-only --port=80 \
    --user www-data --group www-data \
    --server-root=/etc/mod_wsgi-express-80
```

- [x] Apache is starting correctly and log is free of errors

**Problem**: actual django project is not being served. Instead, apache is serving welcome-page.

**Which kind of config** is necessary to server django-project in this case?

PS: Tried some config mentioned in [django-documentation](https://docs.djangoproject.com/en/2.2/howto/deployment/wsgi/modwsgi/), but didn't work.

**Comment by GrahamDumpleton** [comment]
You can't have ``mod_wsgi-express`` use port 80 if you still have the system Apache running. In other words, both can't be running at the same time using the same port. If you still need the system Apache running, you will need to run ``mod_wsgi-express`` on an alternate port and have the system Apache proxy to it.

That said, you haven't even run ``mod_wsgi-express``. The command you ran creates a configuration, but it is totally separate from the system Apache. You still need to run:

```
/etc/mod_wsgi-express-80/apachectl start
```

As noted above, you can't do that if the system Apache is still running, so you either have to set up a proxy arrangement, or disable the system Apache so it isn't started.

**Comment by nottheend** [comment]
Running `sudo /etc/mod_wsgi-express-80/apachectl start` solved the problem.

Great work. Thanks.

Wonderful :tada:

**Comment by GrahamDumpleton** [comment]
Note that you will still need to integrate that into systemd or other system init scripts to have it automatically started on system boot if want to use that permanently.
