### ISSUE TITLE
[wsgi:error]ImportError: cannot import name 'global_settings'

### ISSUE THREAD

**Issue by cold1746** [GrahamDumpleton/mod_wsgi#405]
Hi,

I want to run my django project in my ubuntu 14.04 machine
my dango version is 2.1.7,my apache is 2.4.2
and my python verson is 3.7.2.
the same is running fine on my windows 7 machine
and my apache log goes like this.
and im not able to figure out  this error. 

[Thu Mar 28 14:13:54.486966 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268] Traceback (most recent call last):
[Thu Mar 28 14:13:54.487006 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]   File "/var/www/s2/curereporterproject/curereporterproject/wsgi.py", line 12, in <module>
[Thu Mar 28 14:13:54.487012 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]     from django.core.wsgi import get_wsgi_application
[Thu Mar 28 14:13:54.487035 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 2, in <module>
[Thu Mar 28 14:13:54.487040 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]     from django.core.handlers.wsgi import WSGIHandler
[Thu Mar 28 14:13:54.487062 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 6, in <module>
[Thu Mar 28 14:13:54.487067 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]     from django.conf import settings
[Thu Mar 28 14:13:54.487087 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 15, in <module>
[Thu Mar 28 14:13:54.487092 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268]     from django.conf import global_settings
[Thu Mar 28 14:13:54.487111 2019] [wsgi:error] [pid 28869:tid 140493474395904] [remote 192.168.1.71:33268] ImportError: cannot import name 'global_settings'.

**Comment by GrahamDumpleton** [comment]
Can you provide the config for mod_wsgi in Apache you are using? Are you using a Python virtual environment, and if yes, where is it located?

At a guess, you may not have setup a reference to your virtual environment correctly where you have installed the Django version you want. As a result it is falling back to an different Django version than expect installed in system Python packages directory.

Another possibility is that your mod_wsgi is not compiled for Python 3.7, but a different version, and again not picking up the correct Django package.

Finally, could be a permissions issue with Apache user not being able to read things.

**Comment by cold1746** [comment]
thanks,
No i'm not using a python virtual environment
i have 2 apache server running on my machine 
one as apache2 and other one as apache2-s2 both doesnt have mod_wsgi cofiguration file
and also i have multiple pythons installed on this machine 2.7, 3.4, 3.7.2.
im trying to run my project on apache2-s2

my django wsgi.py looks like this

`import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "curereporterproject.settings")

application = get_wsgi_application()`

and 

my           looks like this

**Comment by GrahamDumpleton** [comment]
What happens if at the start of your WSGI script file you add:

```
import django.conf
print('django.conf.__file__', django.conf.__file__)
```

What is logged in the Apache log file?

When you look at that file path, is it the file you expect? Does the file and directories have permissions such as Apache user could read them?

**Comment by cold1746** [comment]
i solved the problem by completly removing python 3.7 from my ubuntu

and also i changed the permissions of project 
using chmod -R 755

thanks
