### ISSUE TITLE
Truncated or oversized response headers received from daemon process

### ISSUE THREAD

**Issue by vikasrawal** [GrahamDumpleton/mod_wsgi#406]
I am aware that this problem has been mentioned in several threads. I have followed them for last three days, and I do not seem to be making any headway. I shall be really grateful if somebody could help me figure this out.

I have a django application, with only an admin interface (no public pages). When I use django's own testing server (python3 manage.py runserver), everything works fine. But with apache2+mod_wsgi I get this error.

I have installed mod_wsgi using pip, so it is compiled for the right version of python (3.7).

I have removed php modules from apache, so those are not the cause of trouble.

These are the python libraries installed in my virtualenv

```
atomicwrites==1.3.0
attrs==19.1.0
coverage==4.5.3
Django==2.2
django-debug-toolbar==1.11
django-extensions==2.1.6
django-gm2m==0.6.1
django-multiselectfield==0.1.8
more-itertools==7.0.0
pbr==5.1.3
pkg-resources==0.0.0
pluggy==0.9.0
psycopg2-binary==2.7.7
py==1.8.0
pytest==4.4.0
pytest-cov==2.6.1
pytest-splinter==2.0.1
python-monkey-business==1.0.0
pytz==2018.9
six==1.12.0
splinter==0.10.0
sqlparse==0.3.0
tenacity==5.0.3
urllib3==1.24.1
whitenoise==4.1.2

```

My apache wsgi.py is:

```
"""
WSGI config for mysurvey project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ["DJANGO_SETTINGS_MODULE"] = "mysurvey.settings"

application = get_wsgi_application()

```

I have added these to my virtual host config file

```
WSGIDaemonProcess mysurvey python-home=/var/www/mysurvey/env python-path=/var/www/mysurvey
        WSGIProcessGroup mysurvey
        WSGIScriptAlias / /var/www/mysurvey/mysurvey/wsgi.py

```

This is what the apache error log shows (LogLevel in apache config is "info")

Truncated or oversized response headers received from daemon process 'mysurvey': /var/www/myurvey/mysurvey/wsgi.py, referer: http://mydomain.in/admin/login/?next=/admin/
[Wed Apr 03 14:09:25.797946 2019] [core:notice] [pid 5478] AH00052: child pid 5552 exit signal Segmentation fault (11)
[Wed Apr 03 14:09:25.798021 2019] [wsgi:info] [pid 5478] mod_wsgi (pid=5552): Process 'mysurvey' has died, deregister and restart it.
[Wed Apr 03 14:09:25.798027 2019] [wsgi:info] [pid 5478] mod_wsgi (pid=5552): Process 'mysurvey' terminated by signal 11
[Wed Apr 03 14:09:25.798032 2019] [wsgi:info] [pid 5478] mod_wsgi (pid=5552): Process 'mysurvey' has been deregistered and will no longer be monitored.
[Wed Apr 03 14:09:25.799782 2019] [wsgi:info] [pid 5743] mod_wsgi (pid=5743): Starting process 'mysurvey' with uid=33, gid=33 and threads=15.
[Wed Apr 03 14:09:25.800135 2019] [wsgi:info] [pid 5743] mod_wsgi (pid=5743): Python home /var/www/mysurvey/env.
[Wed Apr 03 14:09:25.800186 2019] [wsgi:info] [pid 5743] mod_wsgi (pid=5743): Initializing Python.
[Wed Apr 03 14:09:25.812142 2019] [wsgi:info] [pid 5743] mod_wsgi (pid=5743): Attach interpreter ''.
[Wed Apr 03 14:09:25.816440 2019] [wsgi:info] [pid 5743] mod_wsgi (pid=5743): Adding '/var/www/mysurvey' to path.

**Comment by GrahamDumpleton** [comment]
The suggestion you seem to have missed, and which would have been mentioned in any case where daemon processes were crashing, is to add:

```
WSGIApplicationGroup %{GLOBAL}
```

See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

**Comment by vikasrawal** [comment]
Thanks a ton for responding so quickly.

I have tried this too. In my virtualhost specification:

 ```
    WSGIDaemonProcess mysurvey python-home=/var/www/mysurvey/env python-path=/var/www/mysurvey
        WSGIProcessGroup %{GLOBAL} 
        WSGIProcessGroup mysurvey
        WSGIScriptAlias / /var/www/ssersurvey/mysurvey/wsgi.py`
```

But this has no effect on the brhaviour.

Vikas

**Comment by GrahamDumpleton** [comment]
That isn't what I wrote. I had ``WSGIApplicationGroup``, not ``WSGIProcessGroup``.

**Comment by vikasrawal** [comment]
Sorry, I missed that. Have tried that too. Still the same.

```
 WSGIDaemonProcess mysurvey python-home=/var/www/mysurvey/env python-path=/var/www/mysurvey
WSGIApplicationGroup %{GLOBAL} 
WSGIProcessGroup mysurvey
WSGIScriptAlias / /var/www/ssersurvey/mysurvey/wsgi.py
```

**Comment by vikasrawal** [comment]
Strangely, it crashes when I try to login to django admin. The login page is served fine. But nothing else.

**Comment by GrahamDumpleton** [comment]
If you can, don't use the binary wheel package for ``psycopg2``? Try using the source package if you can.

Also, are you using system Python 3.7, or Anaconda Python? Do you have mod_ssl enabled in Apache?

**Comment by vikasrawal** [comment]
You must be superhuman to respond so promptly. Thanks a lot.

I am using system python 3.7.
mod_ssl is enabled. Is that a problem?
I had earlier installed psycopg2 using pip but I kept getting this warning that I should shift to psycopg2-binary. So I did. Should I go back to 'pip install psycopg2', or a manual compiling (configure, make etc...)?

Vikas

**Comment by vikasrawal** [comment]
BTW, this application was working fine with python3.6. But then for some reason, I upgraded. And then all hell broke loose. I have, of course, recompiled mod_wsgi using pip for the new python. But...

**Comment by GrahamDumpleton** [comment]
If not using ``mod_ssl``, disable it. If that doesn't solve it, try going back to ``pip install psycopg2``.

The concern is that the binary wheel for ``psycopg2`` has been compiled for an incompatible set of SSL libraries than Apache is using.

Ultimately, not going to know why things crash unless you can capture a stack trace. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb

**Comment by vikasrawal** [comment]
Disabled mod_ssl and gone back to psycopg2. No luck.
With psycopg2, I get this:
`UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.`

I tried gdb but was unable to do so. My server runs debian. The location of apache2 binary is /usr/sbin/apache2. So I modified your instructions and did "gdb /usr/sbin/apache2".
but then, when I do run -X, I get this.
```
Starting program: /usr/sbin/apache2 -X
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Thu Apr 04 04:25:30.112793 2019] [core:warn] [pid 16147] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot
[Inferior 1 (process 16147) exited with code 01]
```

**Comment by GrahamDumpleton** [comment]
Use the procedure further down for gdb, to attach to a running mod_wsgi daemon process.

**Comment by vikasrawal** [comment]
I am about to board a flight. Let me get back to this on arrival and report. Thanks a ton.

Vikas

**Comment by GrahamDumpleton** [comment]
I get on a flight mid next week and then on holidays, so hopefully can sort out before then. :-)

**Comment by vikasrawal** [comment]
A clean reinstall of the os, and apache2 and everything did the trick. I guess there was some garbage that needed to go. Thanks a lot for your patience.
