### ISSUE TITLE
Increasing timeout on mod_wsgi-express fails

### ISSUE THREAD

**Issue by alesrosina** [GrahamDumpleton/mod_wsgi#407]
Hello Graham,

I am playing around with Weblate and OpenShift - and since you also contributed to that repo, I am asking you here if I am doing sth wrong.

The issue is, in this deployment we are using `mod_wsgi-express` and I am trying to increase timeout, since some operations can take a long time (even a few hours). I did set all the above timeouts to (ridiculous) high values:

```
--socket-timeout 21600
--queue-timeout 21600
--request-timeout 21600
--connect-timeout 21600
--header-timeout 21600
--startup-timeout 21600
--shutdown-timeout 21600
--graceful-timeout 21600
--body-timeout 21600
--response-socket-timeout 21600
--deadlock-timeout 21600
--inactivity-timeout 21600
--header-max-timeout 36000
```

When the server is started, I am getting this output, so I guess settings should take effect:
```
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 21600 (seconds)
Startup Timeout    : 21600 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 21600 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog : 500 (connections)
```

But i am still getting timeout of 30 seconds, if operation takes longer than that.

What am I doing wrong?

**Comment by GrahamDumpleton** [comment]
Running such long running requests is generally a bad idea. You will very quickly run out of server capacity if a handful of long running requests arrive at the same time.

That said, enable access logging using ``--access-log`` option, and ensure log level is set to ``info`` rather than ``err`` or ``warn``, using ``--log-level`` option. Would then need to see access logs and error logs for when request and timeout occur. Also need to know the exact error message and HTTP response code the browser reports.

**Comment by alesrosina** [comment]
@GrahamDumpleton  Yes, I agree - this is just a temporary hack and a proper solution is already in the making (parallelization of actual app). But I still need this, since otherwise the app is not working for our scenario.

Anyway, I've added the logging, and this is the output:
```
ip.removed - - [05/Apr/2019:08:15:00 +0000] "POST /create/component/ HTTP/1.1" 200 17003
ip.removed - - [05/Apr/2019:08:15:02 +0000] "GET /static/CACHE/css/813796e0e087.css HTTP/1.1" 304 -
ip.removed - - [05/Apr/2019:08:15:02 +0000] "GET /static/CACHE/js/a4f337cc22e0.js HTTP/1.1" 304 -
ip.removed - - [05/Apr/2019:08:15:02 +0000] "GET /js/i18n/ HTTP/1.1" 200 3223
ip.removed - - [05/Apr/2019:08:15:02 +0000] "GET /static/weblate-128.png HTTP/1.1" 200 956
ip.removed - - [05/Apr/2019:08:15:03 +0000] "GET /static/CACHE/css/chartist.css.map HTTP/1.1" 404 231
[Fri Apr 05 08:15:03.341822 2019] [core:info] [pid 56:tid 140690065233664] [client ip.removed:40462] AH00128: File does not exist: /opt/app-root/src/wsgi/static/CACHE/css/chartist.css.map
[Fri Apr 05 08:15:24.145029 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component: updating repository
[Fri Apr 05 08:15:25.446703 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component: update took 1.30 seconds
[Fri Apr 05 08:15:25.611242 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component: rebase remote into repo
[Fri Apr 05 08:15:36.170483 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component: updating repository
[Fri Apr 05 08:15:42.629328 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component: update took 6.46 seconds
[Fri Apr 05 08:15:42.650115 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] DEBUG test_project/test_component: skipped push: nothing to push
[Fri Apr 05 08:15:42.745956 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component: rebase remote into repo
[Fri Apr 05 08:15:43.477266 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component: checking locale/en.po (en) [1/22]
[Fri Apr 05 08:15:43.485946 2019] [wsgi:error] [pid 55:tid 140689718757120] [remote ip.removed:49914] INFO test_project/test_component/en: processing locale/en.po, new file
```
this are request headers:
```
POST /create/component/ HTTP/1.1
Host: my-weblate-site-weblate-test.horizondev.cloud
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://weblate.my-test-url.com/
Content-Type: multipart/form-data; boundary=---------------------------102517011819159476761552693833
Content-Length: 2638
Connection: keep-alive
Cookie: [removed]; sessionid=[removed]
Upgrade-Insecure-Requests: 1
```
and this are response headers:
```
HTTP/1.0 504 Gateway Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html
```
and the content of response is:
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

**Comment by GrahamDumpleton** [comment]
The line:

```
ip.removed - - [05/Apr/2019:08:15:00 +0000] "POST /create/component/ HTTP/1.1" 200 17003
```

because it has a 200 response, suggests the request did complete, and that it wasn't a timeout in Apache or mod_wsgi.

The issue is more likely that the haproxy in OpenShift, which routes the external request through to your application instance, has a timeout of its own of 30 seconds.

I just wanted to confirm what the logs said before I pointed at haproxy being the issue. I couldn't remember what timeouts the haproxy might have.

Also suggest using:

```
--access-log-format "%h %l %u %t \"%r\" %>s %b %D"
```

The ``%D`` at end of the format will add an extra value to the access log showing how long the request took in micro seconds. You can use this to confirm how long it ran for before returning a 200.

**Comment by alesrosina** [comment]
Hey, thanks for this hint - it really looks like haproxy thing. Any hints on where to set this? I am also a bit new with this openshift thingy...

**Comment by GrahamDumpleton** [comment]
https://docs.openshift.com/container-platform/3.11/install_config/configuring_routing.html

**Comment by alesrosina** [comment]
@GrahamDumpleton thank you very much! This is exactly what was it - so I will close this issue, since it is actually not relevant to `mod_wsgi-express'.

Thanks again!
