### ISSUE TITLE
Is mod_wsgi necessary for pgadmin4 on tumbleweed ?

### ISSUE THREAD

**Issue by voronamanga** [GrahamDumpleton/mod_wsgi#408]
Hi,
after installing pgadmin4, which ran nevertheless a couple hours without any problems, I could not start apache2 this morning, with the error
`httpd-prefork: Syntax error on line 227 of /etc/apache2/httpd.conf: Syntax error on line 32 of /etc/apache2/vhosts.d/00_default.conf: Syntax error on line 1 of /etc/apache2/conf.d/pgadmin4.conf: Cannot load modules/mod_wsgi.so into server: /srv/www/modules/mod_wsgi.so: cannot open shared object file: No such file or directory`
Actually, there is no directory named 'module' in '/srv/www', and beyond, no mod_wsgi.so on my system. 
So I just renamed pgadmin4.conf to pgadmin4.conf.bak, which at least allows me to run apache2. The weird thing is that pgadmin4 seems to still work well in my browser ! 
What would you suggest me ? Getting rid of pgadmin4.conf which tries to LoadModule mod_wsgi if it's useless ? Installing the appropriate package apache2-mod_wsgi (or apache2-mod_wsgi-python3 ????) ? 
Thanks and have a nice day.

**Comment by GrahamDumpleton** [comment]
What is “tumbleweed”? Is that a hosting service and you have installed pgadmin as an option through their hosting service control panel?

**Comment by voronamanga** [comment]
Thanks for such a quick answer. No, I meant OpenSuse Tumbleweed, which is a Linux distribution OpenSuse's "always up-to-date" system ) and just like the usual way you install packages with their dependencies. So I could install pgadmin4 without mod_wsgi package ... but pgadmin4.conf needs mod_wsgi ... and pgadmin4 seems to be running without it. I forgot to mention that I want to use pgadmin4 for the development stage of web site, so the server is on localhost.

**Comment by GrahamDumpleton** [comment]
Since the issue seems to related to the OpenSuse distro, I think you may need to raise it with them on whatever forum they use to discuss their packages. I know nothing about how they package stuff and what they are trying to do so anything I tell you would be a complete guess.

**Comment by voronamanga** [comment]
OK, it sounds logical, I'm heading to OpenSuse Forums then. Thanks anyway.
