### ISSUE TITLE
[pip:mod_wsgi]Command "/usr/local/bin/python3.7 -u -c "import setuptools..failed with error code 1 in /tmp/pip-install-azo8566k/mod-wsgi/

### ISSUE THREAD

**Issue by patelkhelan11** [GrahamDumpleton/mod_wsgi#409]
System information,

Python version : 3.7.2 (installed and compiled manually)
System : CentOS 7

Command:,
` pip install  mod_wsgi`

First it gives below warning in the logs,
```
WARNING: The Python installation you are using does not appear to have
  been installed with a shared library, or in the case of MacOS X, as a
  framework. Where these are not present, the compilation of mod_wsgi may
  fail, or if it does succeed, will result in extra memory being used by
  all processes at run time as a result of the static library needing to
  be loaded in its entirety to every process. It is highly recommended
  that you reinstall the Python installation being used from source code,
  supplying the '--enable-shared' option to the 'configure' script when
  configuring the source code prior to building and installing it.
```
Error:
```
 /usr/bin/ld: final link failed: Nonrepresentable section on output
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for mod-wsgi

/usr/bin/ld: final link failed: Nonrepresentable section on output
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-
azo8566k/mod-wsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n',
 '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xwkvqvlo/install-
record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-
azo8566k/mod-wsgi/

```
Has anyone encountered same error or does it mean I have to re-install python (with any special configs) or any other alternative? Thanks!

**Comment by GrahamDumpleton** [comment]
Python must be installed with a shared library if using it in embedded systems that rely on dynamic loading.

See details in:

http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

for how to install it with a shared library, as well as other good practices you should use. Ignore that post mentions docker, is still relevant.

**Comment by VenkateshDharavath** [comment]
OS: Centos 7
Python version: 3.7
I've installed python with a shared library enabled.

    Python 3.7.4 (default, Jan 19 2020, 10:53:45)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from ctypes.util import find_library
    >>> find_library("m")
    'libm.so.6'
    >>> exit()
    [muser@ip-148-72-211-244 opt]$ whereis libm.so.6
    libm.so: /usr/lib64/libm.so.6 /usr/lib64/libm.so
    [muser@ip-148-72-211-244 opt]$ export LD_LIBRARY_PATH=/usr/lib64/

I thought it is not looking at where the libraries are at runtime so, I've done this and tried installing but it still gives the same error.
please suggest a solution.
thank you.

**Comment by GrahamDumpleton** [comment]
@VenkateshDharavath Please don't raise questions about your new issue on an existing issue. Go back and create a new issue and properly explain your problem with details of what you were doing, commands you can ran errors you got and where the errors were logged. Do that in a new issue. Thanks.

Closing original issue as presume response addressed the problem.
