### ISSUE TITLE
ssl-enabled mod_wsgi-express with self-compiled psycopg2

### ISSUE THREAD

**Issue by nottheend** [GrahamDumpleton/mod_wsgi#411]
**Setup:**
- Apache/2.4.6 (CentOS)
- mod_wsgi/4.6.5 _compiled from source (details in issue https://github.com/GrahamDumpleton/mod_wsgi/issues/404)_
- Python/3.7
- OpenSSL/1.0.2k-fips 
- configuration created with command
```python manage.py runmodwsgi --port=80 --https-port=443 --ssl-certificate-file /etc/letsencrypt/live/mydomain.com/fullchain.pem --ssl-certificate-key-file /etc/letsencrypt/live/mydomain.com/privkey.pem --ssl-certificate-chain-file /etc/letsencrypt/live/mydomain.com/fullchain.pem --https-only --server-name mydomain.com --user www-data --group www-data --server-root=/etc/mod_wsgi-express --setup-only```
inspired by doc-section [Using mod_wsgi-express with Django](https://pypi.org/project/mod_wsgi/)

**Error:**
- Apache-log:
`[Apr 15] [core:notice] [pid 17878:tid 140664258979968] AH00052: child pid 17879 exit signal Segmentation fault (11)`
- Error message is printed with high frequency, seems like Apache is crashing on startup

**Tried:**
- [getting debugging-message with gdb](https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb) `sudo gdb /path/to/apache/`, but don't know how to get correct path. `whereis httpd` just catches system-wide installation
- Modified the configuration according to the [discussion mentioned in issue #266](https://github.com/GrahamDumpleton/mod_wsgi/issues/266), but no success

**Aim:**
- Apache ssl-enabled serving django-application

**Comment by GrahamDumpleton** [comment]
Are you using psycopg2-binary package in your virtual environment?

Add `—log-level info` capture logs to confirm whether it is daemon processes.

**Comment by nottheend** [comment]
Yes, using psycopg2-binary in version `psycopg2-binary==2.8.1`

Recreating server config with additional parameter `--log-level info` shows following (one cycle):
```
[13:56:50] [mpm_event:notice] [pid 18786:tid 140178788993152] AH00489: Apache/2.4.6 (CentOS) mod_wsgi/4.6.5 Python/3.7 OpenSSL/1.0.2k-fips configured -- resuming normal operations
[13:56:50] [mpm_event:info] [pid 18786:tid 140178788993152] AH00490: Server built: Nov  5 2018 01:47:09
[13:56:50] [core:notice] [pid 18786:tid 140178788993152] AH00094: Command line: 'httpd (mod_wsgi-express) -f /etc/mod_wsgi-express/httpd.conf -D MOD_WSGI_VIRTUAL_HOST -D MOD_WSGI_WITH_HTTPS -D MOD_WSGI_CERTIFICATE_CHAIN -D MOD_WSGI_HTTPS_ONLY -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE'
[13:56:50] [wsgi:info] [pid 18787:tid 140178788993152] mod_wsgi (pid=18787): Python home /home/user/.local/share/virtualenvs/nassl-uqWMtY-j.
[13:56:50] [wsgi:info] [pid 18787:tid 140178788993152] mod_wsgi (pid=18787): Initializing Python.
[13:56:50] [wsgi:info] [pid 18787:tid 140178788993152] mod_wsgi (pid=18787): Attach interpreter ''.
[13:56:50] [wsgi:info] [pid 18787:tid 140178788993152] mod_wsgi (pid=18787): Imported 'mod_wsgi'.
[13:56:50] [wsgi:info] [pid 18787:tid 140178788993152] mod_wsgi (pid=18787, process='localhost:80', application=''): Loading Python script file '/etc/mod_wsgi-express/handler.wsgi'.
[13:56:52] [wsgi:info] [pid 18786:tid 140178788993152] mod_wsgi (pid=18787): Process 'localhost:80' has died but server is being stopped, deregister it.
[13:56:52] [wsgi:info] [pid 18786:tid 140178788993152] mod_wsgi (pid=18787): Process 'localhost:80' has been deregistered and will no longer be monitored.
[13:56:52] [core:info] [pid 18786:tid 140178788993152] AH00096: removed PID file /etc/mod_wsgi-express/httpd.pid (pid=18786)
```

**Comment by GrahamDumpleton** [comment]
Can you change psycopg2-binary to psycopg2 and build it from source code rather than use the binary package. There is something possibly suspect with the binary package which causes it to crash when using Python embedded in Apache.

**Comment by nottheend** [comment]
After meeting [build prerequisites](http://initd.org/psycopg/docs/install.html), building is successful:
`Successfully installed psycopg2-2.8.2`

But running `python manage.py help` throws
```
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: libpq.so.5: cannot open shared object file: No such file or directory
```

Adding correct path of libpq.so.5 to `PATH` variable, shows missing of libpq.so.10

Therefore I'm not sure, if I'm on the right track.

**Comment by GrahamDumpleton** [comment]
Use the `—no-cache` option with `pip install`. Looks like you may have old version of binary cached.

**Comment by GrahamDumpleton** [comment]
Also run `find / -name ‘libpq.so.*’` and post output for what Postgres library versions it found. You could have mismatched versions of postgres and postgres-dev system packages installed. That may not be names of them as not sure what your system calls Postgres packages

**Comment by nottheend** [comment]
Full output of  `find / -name ‘libpq.so.*’`

```
/usr/lib64/libpq.so.5
/usr/lib64/libpq.so.5.5
/usr/pgsql-10/lib/libpq.so.5
/usr/pgsql-10/lib/libpq.so.5.10
```

**Comment by GrahamDumpleton** [comment]
Do you know where files under /usr/pgsql-10 came from? They appear to be conflicting version to those in system lib directory and maybe the build has linked to them, but because in non standard directory, they are not found at runtime.

You can’t set PATH to say where shared libraries are, that only works on Windows. On Linux systems you would use LD_LIBRARY_PATH.

**Comment by nottheend** [comment]
Files under `/usr/pgsql-10` were created by `sudo yum install postgresql10-server`

After review, it has been figured out that is not necessary to install postgresql version 10.

Therefore: system-packages have been updated by running
`sudo yum install postgresql-server postgresql-contrib postgresql-devel`

Error-message persists after re-building `psycopg2`:
`libpq.so.5: cannot open shared object file: No such file or directory`

**Comment by nottheend** [comment]
Setting `export LD_LIBRARY_PATH=/usr/lib64` results in another error:

```
django.core.exceptions.ImproperlyConfigured:
Error loading psycopg2 module:
/home/user/.local/share/virtualenvs/ ... /psycopg2/_psycopg.cpython-37m-x86_64-linux-gnu.so:
undefined symbol: PQconninfo
```

**Comment by GrahamDumpleton** [comment]
You have SELinux enabled?

**Comment by nottheend** [comment]
Indeed, I have.

As a first try: Couldn't find `AVC` in logfile `/var/log/audit/audit.log` while being in _Permissive_ mode

**Comment by nottheend** [comment]
**Confirmed:** SELinux does not interfere here.


Built `mod_wsgi`, `psycopg2` and `nassl` again against pgsql-9-files ([instead version 10](https://github.com/GrahamDumpleton/mod_wsgi/issues/411#issuecomment-486153303))

Results in slightly different error-message:

```
django.core.exceptions.ImproperlyConfigured:
Error loading psycopg2 module: /home/linuxbrew/.linuxbrew/lib/librt.so.1:
symbol __recv, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

**Comment by GrahamDumpleton** [comment]
LinuxBrew may be the issue based on that error. That is, if LinuxBrew has its own versions of some system libraries, such as `librt`, you will have problems if some things build against original system libraries and others against LinuxBrew variants. Aim to use only system libraries.
