### ISSUE TITLE
exit signal Segmentation fault (11), possible coredump

### ISSUE THREAD

**Issue by Shaileshbg1** [GrahamDumpleton/mod_wsgi#412]
Hello,

I have pip installed mod_wsgi (4.6.5) on python3.6 and I am using mod_wsgi-express start-server for hosting my flask web app on apache web server. My application is in a docker container and when I run it I get an error message stating:

`[Fri Apr 12 11:08:45.479175 2019] [mpm_event:notice] [pid 1:tid 139625471580032] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.6.5 Python/3.6 configured -- resuming normal operations
[Fri Apr 12 11:08:45.479250 2019] [core:notice] [pid 1:tid 139625471580032] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/mod_wsgi-localhost:9090:999/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
[Fri Apr 12 11:08:46.480404 2019] [core:notice] [pid 1:tid 139625471580032] AH00051: child pid 162 exit signal Segmentation fault (11), possible coredump in /tmp/mod_wsgi-localhost:9090:999
[Fri Apr 12 11:08:47.481882 2019] [core:notice] [pid 1:tid 139625471580032] AH00051: child pid 177 exit signal Segmentation fault (11), possible coredump in /tmp/mod_wsgi-localhost:9090:999
`

On another issue, it was suggested to set 
`WSGIApplicationGroup %{GLOBAL}`
in Apache configuration file. 

But the way I understood mod_wsgi-express is that; directly from the command line, we can spin up a standalone instance of Apache, with an auto-generated configuration with no need of the user to define any Apache configuration. So I have not defined any apache configuration and I am using the default "000-default.conf." I am very new to this domain and I do not understand on how to proceed now.

Looking forward to hearing back from you.

Regards,
Shailesh

**Comment by GrahamDumpleton** [comment]
What OS base image are you using? Are you using Postgres? 

If you are using certain OS versions with older Postgres client version or incompatible SSL libraries installed, it appears that using psycopg2-binary package will cause crashes. You need to install psycopg2 source package instead.

You don’t need to set The application group as mod_wsgi-express if using that, will do it for you in the configuration you are using.

**Comment by Shaileshbg1** [comment]
Hello,

Thank you for your reply. I am using Ubuntu:16.04 as my base image and I am not using Postgres. 

My flask application has just one resource call, to a visualization application called Paraview. I have the whole paraview binary copied onto my docker container and PYTHONPATH set to the required .py libraries.

This is my wsgi file:
`#! /usr/bin/python3.6

import sys

##Add this file path to sys.path in order to import app
sys.path.insert(0, "/postProcess_app/")

##Create an application 
from postProcessing_flask import app as application
`

This is my flask application
`from flask import Flask, request
from flask_restful import Resource, Api
import os, sys
from postProcessing import call_paraview

app = Flask(__name__)
api = Api(app)

class HelloWorld(Resource):
    def get(self):
        return{'about':'Hello World!'}

class Paraview(Resource):
    def post(self):
        call_paraview()
        return {'msg': 'success'}, 200

api.add_resource(HelloWorld, '/')
api.add_resource(Paraview, '/postProcess')

if __name__ == '__main__':
    app.run(host="0.0.0.0",port=9090,debug=True)
`

This is my Docker file where I have defined my binaries and PYTHONPATH
`# #Post processing: setting up paraview binaries and flask application

ARG BASE_IMAGE=base_image:0.1
FROM ${BASE_IMAGE}
ENV DEBIAN_FRONTEND=noninteractive

## Create post processing application directory
USER root
WORKDIR /postProcess_app
####################################################################################
## Set up paraview-osmesa binary

##RUN ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py /usr/lib/python2.7/

ENV LD_LIBRARY_PATH="/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib"

ENV PYTHONPATH="/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib:/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib/python2.7/site-packages:/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib/python2.7/site-packages/vtkmodules"
###################################################################################
## Start the apache/mod_wsgi server to receive requests and pass it to flask post processing web framework

USER niramai

EXPOSE 9090

CMD ["/bin/bash", "-i", "-c", "mod_wsgi-express start-server postProcessing_flask.wsgi --port 9090 --socket-timeout 600" ]``


The paraview libraries which I am invoking is in python2.7 site-packages and I am using flask in python 3.6, is the version mismatch causing the error? I look forward to hearing back from you.

Regards,
Shailesh

**Comment by GrahamDumpleton** [comment]
You cannot mix binary Python versions. So using a Python 2.7 site packages with Python 3.6, especially where there are Python packages with C the extensions, will result in crashes or other strange behaviour. So use the one Python version. Avoid system packages for extra Python packages and install packages using pip into your Python installation or virtual environment for the version you want to use.

**Comment by Shaileshbg1** [comment]
Hello,

Thank you for your reply. 
Since paraview binaries are in Python 2.7 it would be helpful if I stick with that version, but when I try to call paraview from mod_wsgi/flask built on python2.7 I get an error:

ImportError: No module named time

This, as I understand, is because I am missing the directories where the C extension modules, including the time module, are located. 

But when I call import time in python terminal it is able to import it and also when I try to locate the .so files using the command "locate time", it points me to the right location. So somewhere mod_wsgi/flask is not able to locate the time module. Can you suggest how I can "show" the path of the time module to mod_wsgi/flask. I have tried PYTHONPATH and LD_LIBRARY_PATH but to no avail. Or is there any other way in which I can solve this issue. Any suggestion would be very helpful and greatly appreciated. Looking forward to hearing back from you.

**Comment by GrahamDumpleton** [comment]
Are you installing mod_wsgi package using pip into the main Python 2.7 installation, or are you using a virtual environment? You should not be using Python 3.6 at all. You should not need to override PYTHONPATH or LD_LIBRARY_PATH at all if you have installed things correctly. An error to import time module usually indicates you are mixing Python versions, or maybe that you are using self installed Python version in non standard location and shared library not found at run time correctly. Where is the Python 2.7 you are using installed?

**Comment by Shaileshbg1** [comment]
Thank you for your reply. 

1) Are you installing mod_wsgi package using pip into the main Python 2.7 installation, or are you using a virtual environment? 
  I am building this in a docker container and I have used pip to install mod_wsgi package onto the python 2.7 installation, I do not have any virtual environments.

2) You should not be using Python 3.6 at all.
    I do not have Python3 installed in the container 

3) maybe that you are using self installed Python version in non standard location and shared library not found at run time correctly
   Please find below the Dockerfile which I have used. I have removed PYTHONPATH and LD_LIBRARY_PATH related to python and only have directed it to the ParaView python modules. I have a symbolic link created as it solved one of the errors.

`FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive

USER root
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y \
    python \
    python2.7 \
    python2.7-dev \
    lsof \
    apache2 \
    apache2-dev \
    vim

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python get-pip.py
RUN pip install -U "setuptools==3.4.1"

## pip install necessary python packages
RUN pip install \
            Flask \
            flask-restful \
            boto3 \
            requests \
            mod_wsgi 


###################################################################################
## Start dumb_init as pid 1, to prevent any weird behaviour.
ADD https://github.com/Yelp/dumb-init/releases/download/v1.1.1/dumb-init_1.1.1_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init

## Default user is root, which could cause issues in case of a breakout.
RUN groupadd -r niramai && useradd -m -r -g niramai niramai

WORKDIR /postProcess_app

ENV LD_LIBRARY_PATH="/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib"

ENV PYTHONPATH="/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib:/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib/python2.7/site-packages:/postProcess_app/ParaView-5.6.0-osmesa-MPI-Linux-64bit/lib/python2.7/site-packages/vtkmodules"


RUN ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py /usr/lib/python2.7/

USER niramai

COPY --chown=niramai:niramai . .

EXPOSE 9090

CMD ["dumb-init", "mod_wsgi-express", "start-server", "postProcessing_flask.wsgi", "--port", "9090", "--socket-timeout", "600" ]`

4)  Where is the Python 2.7 you are using installed?
     When I run the command 'which python' inside the container I get "/usr/bin/python", my default python version is Python 2.7.12 and itts executable is located in "/usr/bin/python2.7"

The error msg which I get is:
`[Mon Apr 22 23:19:46.890303 2019] [wsgi:error] [pid 67:tid 139967659431808] mod_wsgi (pid=67): Failed to exec Python script file '/tmp/mod_wsgi-localhost:9090:999/handler.wsgi'.
[Mon Apr 22 23:19:46.890342 2019] [wsgi:error] [pid 67:tid 139967659431808] mod_wsgi (pid=67): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:9090:999/handler.wsgi'.
[Mon Apr 22 23:19:46.890359 2019] [wsgi:error] [pid 67:tid 139967659431808] Traceback (most recent call last):
[Mon Apr 22 23:19:46.890377 2019] [wsgi:error] [pid 67:tid 139967659431808]   File "/tmp/mod_wsgi-localhost:9090:999/handler.wsgi", line 5, in <module>
[Mon Apr 22 23:19:46.890449 2019] [wsgi:error] [pid 67:tid 139967659431808]     import time
[Mon Apr 22 23:19:46.890469 2019] [wsgi:error] [pid 67:tid 139967659431808] ImportError: No module named time
`

**Comment by GrahamDumpleton** [comment]
What is the Python installation/virtual environment that Parkview is being imported from by specifying PYTHONPATH?

You cannot mix a site-packages directory from another Python installation even of the same version, unless you are 100% sure it is compatible and was configured with same configure options when that Python installation was built and installed. A Python built from source code using default configure options will not be compatible with Linux system Python, nor will any binary packages installed into it’s site-packages directory.

I have talked about this issue and how to work out correct options for configure when doing custom built Python in:

http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Why aren’t you doing a pip install of ParaView into the main 2.7 installation from source code? That is the safest way to install it.

BTW, you don’t need dumb init when CMD is running mod_wsgi-express as Apache does what 8s required of process ID 1 already.

**Comment by Shaileshbg1** [comment]
Hi,

Thank you for your reply. There is no pip install of ParaView so I built the required binaries of ParaView on python 3.6.8. This solved my problem, hence closing the issue.

Regards,
Shailesh
