### ISSUE TITLE
After installation, no mod_wsgi.so generated

### ISSUE THREAD

**Issue by LouisU** [GrahamDumpleton/mod_wsgi#413]
`
[root@e2e3d3692570 /]# ls  
4.6.5.tar.gz  boot  etc  lib   media  mod_wsgi-4.6.5  proc  root      sbin  sys  usr

[root@e2e3d3692570 /]cd mod_wsgi-4.6.5/

[root@e2e3d3692570 mod_wsgi-4.6.5]# ls
CREDITS.rst  LICENSE  MANIFEST.in  Makefile.in  README.rst  configure  configure.ac  docs  images  setup.py  src  tests  tox.ini  win32

[root@e2e3d3692570 mod_wsgi-4.6.5]# ./configure --with-apxs=/usr/bin/apxs --with-python=/usr/local/bin/python3

[root@e2e3d3692570 mod_wsgi-4.6.5]# make&&make install
....completed

[root@e2e3d3692570 mod_wsgi-4.6.5]# find / -name *mod_wsgi*  
/mod_wsgi-4.6.5
/mod_wsgi-4.6.5/src/server/mod_wsgi.o
/mod_wsgi-4.6.5/src/server/mod_wsgi.c
/mod_wsgi-4.6.5/src/server/mod_wsgi.lo
/mod_wsgi-4.6.5/src/server/mod_wsgi.slo
/mod_wsgi-4.6.5/src/server/.libs/mod_wsgi.o
`
After installation, no mod_wsgi.so generated.  Why this happened ？

**Comment by GrahamDumpleton** [comment]
It is created by running make install and is placed in the Apache modules directory. Have you looked there? I cant tell you what the Apache modules directory is as it is dependent on what Linux distro you are using, or where you have Apache installed.

You might want to instead look at the pip install method. See the mod_wsgi page on PyPi.
