### ISSUE TITLE
Windows 8.x - mod_wsgi with WampServer 3.1.7 64bit and Python 64bit 3.7.3 crashing Apache 2.4.37

### ISSUE THREAD

**Issue by ScottyBond** [GrahamDumpleton/mod_wsgi#414]
and I'm sure it's something I am not doing correctly. Very new to this environment and I'm hacking at it with a big machete.

LoadModule wsgi_module "c:/users/xxx/appdata/local/programs/python/python37/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "c:/users/xxx/appdata/local/programs/python/python37"

I have added the above to the C:\wamp64\bin\apache\apache2.4.37\conf\httpd.conf file which causes Apache to crash (2 of 3 services running in Wamp). When I comment out the lines, Apache runs.

Note:
The Local account on on the computer runs Apache and there appears to be a separate Apache installation in the root of C: - Apache24. I am focused on the embedded Apache install in Wamp - C:\wamp64\bin\apache\apache2.4.37

Any help would be greatly appreciated!

**Comment by GrahamDumpleton** [comment]
The build has likely used the Apache in the root directory c:/apache24 as that is default place it looks. You cannot use that binary with a different Apache distribution installed in your local directory.
    
In general you also cannot seem to use WAMP Apache as it is missing bits to build modules against. Use ApacheLounge Apache, which possibly is what one in root directory is based on directory name it is installed in.
