### ISSUE TITLE
restart-interval=nnn No time unit defined in docs

### ISSUE THREAD

**Issue by geonyoro** [GrahamDumpleton/mod_wsgi#415]
What is the time unit in docs? The use of nnn is normally with numbers. sss helps us know it's seconds. SO what is t?

**Comment by GrahamDumpleton** [comment]
It is seconds as integer.

Like other time based options it should indeed use sss and explicitly mention units in docs. I cant change this right now, but will try and update it other coming weeks when have access to do so again.

**Comment by GrahamDumpleton** [comment]
Have updated the docs now, so should be reflected in 'develop' docs once rebuild done.
