### ISSUE TITLE
windows 10, Anaconda, XAMPP: mod_wsgi not loading Django (ImportError: DLL load failed: The specified module could not be found)

### ISSUE THREAD

**Issue by kvacha13** [GrahamDumpleton/mod_wsgi#417]
Hi,
I've been trying to use mod_wsgi with Django served on windows Apache server for the last 2 weeks but withour success. The following are details of my software confiuration:
Windows 10 (x64; 10.0.18362)
Anaconda:
           conda version : 4.6.14
           conda-build version : 3.17.6
           python version : 3.7.1.final.0 (x64)
           platform : win-64
 XAMPP (ApacheFriends XAMPP Version 7.3.4 installed by xampp-windows-x64-7.3.4-0-VC15-installer.exe):
  + Apache 2.4.39 (x64)
  + MariaDB 10.1.38
  + PHP 7.3.4 (VC15 X86 64bit thread safe) + PEAR
  + phpMyAdmin 4.8.5
  + OpenSSL 1.1.0g
MOD_WSGI: installed by pip install mod_wsgi-4.6.5+ap24vc15-cp37-cp37m-win_amd64.whl
Django version 2.1.7, final (installed by pip install django).
I've created simple(tutorial) Django project in E:/xampp/htdocs and it runs ok on python server (pyhton manage.py runserver). 
Following mod_wsgi and apache configuration instruction from this link (https://pypi.org/project/mod_wsgi/) I've set these configuration:
1. in httpd.conf: LoadFile, LoadModule wsgi_module, WSGIPythonHome pathes set to the values retrived by mod_wsgi-express module-config command.
2. httpd-vhosts: 
     WSGIScriptAlias /django "E:/xampp/htdocs/mysite/mysite/wsgi.py"
     WSGIPythonPath  "E:/xampp/htdocs/mysite"
<VirtualHost *:80>
     <Directory "E:/xampp/htdocs/mysite/mysite">
          Require all granted
     </Directory> 
   <Directory "E:/xampp/htdocs/mysite/mysite">
         <Files wsgi.py>
            Require all granted
         </Files>
   </Directory>    
</VirtualHost>
-------------------------
The problem is that Apache fails to load Django page with error 500:
  Server error!
   The server encountered an internal error and was unable to complete your request. Either the 
   server is overloaded or there was an error in a CGI script.
   If you think this is a server error, please contact the webmaster.
   Error 500
   127.0.0.1
   Apache/2.4.39 (Win64) OpenSSL/1.1.1b mod_wsgi/4.6.5 Python/3.7 PHP/
The apache error/log file gives following lines:

mod_wsgi (pid=4616): Failed to exec Python script file   'E:/xampp/htdocs/mysite/mysite/wsgi.py'.
--
mod_wsgi (pid=4616): Exception occurred processing WSGI script   'E:/xampp/htdocs/mysite/mysite/wsgi.py'.
Traceback (most recent call last):\r
File "E:/xampp/htdocs/mysite/mysite/wsgi.py", line 18,   in <module>\r
application = get_wsgi_application()\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\core\\wsgi.py",   line 12, in get_wsgi_application\r
django.setup(set_prefix=False)\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\__init__.py",   line 24, in setup\r
apps.populate(settings.INSTALLED_APPS)\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\apps\\registry.py",   line 112, in populate\r
app_config.import_models()\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\apps\\config.py",   line 198, in import_models\r
self.models_module = import_module(models_module_name)\r
File   "c:\\users\\kvach\\anaconda3\\lib\\importlib\\__init__.py", line   127, in import_module\r
return _bootstrap._gcd_import(name[level:], package, level)\r
File "<frozen importlib._bootstrap>", line 1006,   in _gcd_import\r
File "<frozen importlib._bootstrap>", line 983,   in _find_and_load\r
File "<frozen importlib._bootstrap>", line 967,   in _find_and_load_unlocked\r
File "<frozen importlib._bootstrap>", line 677,   in _load_unlocked\r
File "<frozen importlib._bootstrap_external>",   line 728, in exec_module\r
File "<frozen importlib._bootstrap>", line 219,   in _call_with_frames_removed\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\contrib\\auth\\models.py",   line 2, in <module>\r
from django.contrib.auth.base_user import AbstractBaseUser,   BaseUserManager\r
File "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\contrib\\auth\\base_user.py",   line 47, in <module>\r
class AbstractBaseUser(models.Model):\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\db\\models\\base.py",   line 101, in __new__\r
new_class.add_to_class('_meta', Options(meta, app_label))\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\db\\models\\base.py",   line 305, in add_to_class\r
value.contribute_to_class(cls, name)\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\db\\models\\options.py",   line 203, in contribute_to_class\r
self.db_table = truncate_name(self.db_table,   connection.ops.max_name_length())\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\db\\__init__.py",   line 33, in __getattr__\r
return getattr(connections[DEFAULT_DB_ALIAS], item)\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\db\\utils.py",   line 202, in __getitem__\r
backend = load_backend(db['ENGINE'])\r
File   "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\db\\utils.py",   line 110, in load_backend\r
return import_module('%s.base' % backend_name)\r
File   "c:\\users\\kvach\\anaconda3\\lib\\importlib\\__init__.py", line   127, in import_module\r
return _bootstrap._gcd_import(name[level:], package, level)\r
File "c:\\users\\kvach\\anaconda3\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py",   line 10, in <module>\r
from sqlite3 import dbapi2 as Database\r
File   "c:\\users\\kvach\\anaconda3\\lib\\sqlite3\\__init__.py", line 23,   in <module>\r
from sqlite3.dbapi2 import *\r
File   "c:\\users\\kvach\\anaconda3\\lib\\sqlite3\\dbapi2.py", line 27, in   <module>\r
from _sqlite3 import *\r
ImportError: DLL load failed: The specified module could not be   found.\r

Any suggestions would be appreciated. I've tried different configurations (including confiugration of apache, mod_wsgi, pythonpath) but without success.

**Comment by GrahamDumpleton** [comment]
The recommended Apache distribution to use is:

* https://www.apachelounge.com/

Other distributions often don't work as they are missing bits which allow compilation of third party Apache modules.

Anaconda Python also often doesn't work as Anaconda Python doesn't work properly in embedded systems such as Apache because Anaconda Python bundles versions of libraries that can be incompatible with same named library already linked into Apache or PHP. So the error could well indicate a conflict with PHP.

Usually you can't use Anaconda Python if you also must use PHP, or if you need mod_ssl. Can you try without PHP and mod_ssl enabled?

**Comment by kvacha13** [comment]
Hi Graham,
Thank you for your feedback.
I've tried to disable mod_ssl in httpd.conf by #-ing LoadModule "mod_ssl" and #-ing "Include conf/extra/httpd-ssl.conf" (withouth #-ing include ssl.conf" server refuses to load) but problem remained.
You also mentioned to disable PHP, but i did not quite understand where to do it (in httpd.conf there was no PHP module at all).
Finally, I decided to install apache from lounge. I donwloaded and installed it into separate directory on my e drive. I moved all my Django projects and server configuration settings from xampp/htdocs to apache24/htdocs. Everything including Django worked great. Pitty, i've lost almost 2 weeks to fix the problem that now seems to be related particularly to  XAMPP...
By the way, do you know if there is any way to replace xampp apache by the apache24 from launge? xamm has nice control panel when it comes to restarting and reseting server configuration.
Anyway, thank you for your help. 
BR,

**Comment by kvacha13** [comment]
Dear Graham,
I want to share with you very interesting finding: as I said mod_wsgi worked perfectly with apache2.4 being installed from lounge. But then i found that if httpd is added to windows services (httpd -k install), the mod_wsgi fails to load Django pages and apache error.log shows the exact same errors of  "from _sqlite3 import *\r ImportError: DLL load failed: The specified module could not be found.\r". Uninstalling apache service and just running server occasionaly by httpd.exe, everyhting starts wokring OK. his is so wierd. this might have been the same issue with xampp server (i will try reinstalling xampp these days  and try disabling apache from services).
In the meantime, any suggestions, how to make it work while having it installed as service? Thanks.

**Comment by GrahamDumpleton** [comment]
When run as a service, it is usually run as some special user. It is possible that special user doesn't have the appropriate access to directories where things are located. It is strange though that the issue would be the sqlite3 DLL. Do you know where that is located?

**Comment by kvacha13** [comment]
I've  searched sqlite.dll on my pc and got many results. But at least they are found on tfollowing locations:
1. C:/ProgramFiles
2. C:/users/myUser/Anaconda3/Library/bin
3. c:/ProgramFiles/Mysql
4. E:\Microsoft_Visual_Studio_Symlink\Microsoft Visual Studio\Shared\Python36_64\DLLs

**Comment by kvacha13** [comment]
I've just checked the running apache process and when the server is started by the windows services it runs as SYSTEM user. If I stop the service (windows services) and run it by httpd.exe, then apache process runs as "Local_USER". But its really strange why SYSTEM user cannot load any .dll while local user can do it.

**Comment by GrahamDumpleton** [comment]
Because `C:/users/myUser/Anaconda3/Library/bin` will not be in `Path` of the system user. Likely that is only in the `Path` of your user.

**Comment by kvacha13** [comment]
Having added  "C: \ Users \ myUser \ Anaconda3 \ Library \ bin" in the Path solved the problem. Strange, however, that “C: / users / myUser / Anaconda3 / Library / bin” was written in PYTHONPATH, and I thought it had the same meaning as having it in PATH. Now it seems that for the same reason, XAMPP failed to load sqlite3.dll and, as a result, the Django pages. Many thanks for the help and your efforts.. mod_wsgi is really great work. Thanks.

**Comment by GrahamDumpleton** [comment]
On Windows, `Path` is used to work out where DLLs can be loaded from. `PYTHONPATH` is only for Python modules/packages, not any DLLs that C extensions they provide try to load.

If all is good, can I close this issue now?

**Comment by kvacha13** [comment]
Thank you Graham.. Now I will remember this rule of PATHs for sure. The problem is solved and sure, it can be closed. Again, thank you for your help.
