### ISSUE TITLE
Django+Ubuntu+Apache2 Fatal Python Error: Py_Initialize: Unable to get locale encoding ModuleNotFoundError

### ISSUE THREAD

**Issue by jeydurai** [GrahamDumpleton/mod_wsgi#418]
With this title, umpteen issues are there and have been addressed to. But, having gone through almost everything, I couldn't fix my problem

I have an apache2 virtual host set up for Rails. I am trying set up the similar for Django app using mod_wsgi with the guidelines.

<VirtualHost *:80>
  ServerName ip_address
  DocumentRoot /var/www/my_site
  WSGIScriptAlias /myapp /var/www/my_site/myapp/wsgi.py
  WSGIDaemonProcess my_site python-home=/var/www/my_site/env python-path=/var/www/my_site
  WSGIProcessGroup my_site
  <Directory /var/www/my_site/myapp>
    <Files wsgi.py>
      AllowOverride all
      Allow from all
      Require all granted
    </Files>
    AllowOverride all
    Allow from all
    Require all granted
    Options FollowSymlinks
  </Directory>

  Alias /static /var/www/my_site/static
  Alias /images /var/www/my_site/static/images
  Alias /favicon.ico /var/www/my_site/static

  <Directory /var/www/my_site/myapp/static>
    Allow from all
    Require all granted
  </Directory>
  ErrorLog /var/www/my_site/logs/error.log
  CustomLog /var/www/my_site/logs/access.log combined
</VirtualHost>

**Comment by GrahamDumpleton** [comment]
This can happen for a couple of reasons.

* The mod_wsgi module is compiled for a different version of Python, or a different installation of Python, than that which the virtual environment is created against.

* The Apache user cannot read directories/files from the virtual environment of Python installation you are using, when it is a self installed Python or in a non standard location.

How was mod_wsgi installed, a system package, or from source code using makefile, or pip? If the system package, what version of Python is it for?

What Python version are you using and where is it installed?

**Comment by jeydurai** [comment]
my python version is Python 3.7 (/home/mycompany/anaconda3)
mod_wsgi was installed using sudo apt install libapache2-mod-wsgi-py3
my projects directory is /var/www/my_site, which has been given sudo chmod -R a+rwx
Virtual environment location is /var/www/my_site/env

**Comment by jeydurai** [comment]
mod_wsgi is system package of which version --- mod_wsgi/4.5.17 Python3.6 configured

**Comment by GrahamDumpleton** [comment]
You cannot point mod_wsgi compiled for Python 3.6 at a virtual environment using Python 3.7.

You will need to uninstall system mod_wsgi and install mod_wsgi using ``pip install`` method and then manually configure Apache to use it instead.

* https://pypi.org/project/mod_wsgi/
* environments.html#virtual-environment-and-python-version

**Comment by jeydurai** [comment]
Successful! Thank you so much. I have been able to set it up.
