### ISSUE TITLE
Errors with mod_wsgi and Apache 2.4

### ISSUE THREAD

**Issue by wolffcaleb** [GrahamDumpleton/mod_wsgi#420]
I'm running into an issue with configuring mod_wsgi for Python 3.6 and Apache 2.4. It causes the following error in my httpd error logs: 

> mod_wsgi: Target WSGI script cannot be loaded as Python module.
> mod_wsgi: Exception occurred processing WSGI script
> File in <module>
> from django.core.wsgi import get_wsgi_application
> ImportError: No module named django.core.wsgi

- I've removed the filenames and line numbers because I believe they are irrelevant in this case.
- I have a virtual environment and I am not using the Daemon setup. 
- I am using RedHat Linux 7

Any help with this would be greatly appreciated. 

Thanks!
Caleb

**Comment by GrahamDumpleton** [comment]
Looks like this issue completely slipped through the net. Problem would have been one of the following:

* The mod_wsgi module was built for different Python version that virtual environment used.
* The Django package was installed in user site packages using ``pip --user``, but where that is ignored when using mod_wsgi.
* The mod_wsgi configuration didn't point at the virtual environment where Django was installed.
