### ISSUE TITLE
WSGI_CONTROL_SCRIPT hardcoded /bin/bash

### ISSUE THREAD

**Issue by derekschrock** [GrahamDumpleton/mod_wsgi#421]
When running on a system (FreeBSD) that doesn't have `/bin/bash` the WSGI_CONTROL_SCRIPT script fails.

Should this be a passable executable like gdb/httpd/rotatelogs `--program-executable`?

The simplest however (maybe breaking?) is to change `/bin/bash` to `/usr/bin/env bash`:

https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/__init__.py#L1761

I can submit a pull request for either or.

**Comment by GrahamDumpleton** [comment]
Can you try with:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

and see if that works for you.

**Comment by derekschrock** [comment]
Yes, that works.  Thanks.
