### ISSUE TITLE
Using a combination of WSGIProcessGroup and WSGIApplicationGroup for multiple virtual hosts, some hosts not running

### ISSUE THREAD

**Issue by orkuva** [GrahamDumpleton/mod_wsgi#422]
This app was made by some other developers long ago and I do not completely understand the WSGI parts, but will try to explain as best as I can. The issue is making me crazy and I have to fix all of this. 

A few related apps are running on apache virtual hosts within daemon mode. Python version is 2.7 and Django is 1.5. The site runs fine for `WSGIApplicationGroup %{GLOBAL} ` defined under every `<Location>`. 
The problem I'm having is that the first site works fine when I navigate to it, but any other site also goes to the first defined site at the root location `/`, whenever I type in `/archive` for example. I think it is happening because I need to specify which site belongs to which Application Group, and I don't know how to do that. My virtual hosts file is copied below, with email and IP address redacted:

```

NameVirtualHost *:80
NameVirtualHost *:443

<VirtualHost *:80>
        ServerAdmin <my email goes here>
        ServerName <my server IP address goes here>
        </VirtualHost>

WSGISocketPrefix run/wsgi

WSGIDaemonProcess staging_dwm_py python-path=/var/www/staging_dwm:/var/www/staging_dwm/env/lib/python2.7/site-packages
WSGIDaemonProcess dwm_py python-path=/var/www/dwm:/var/www/dwm/dwmenv/lib/python2.7/site-packages
WSGIDaemonProcess staging_dwm_py2 python-path=/var/www/staging_dwm2:/var/www/staging_dwm2/dwmenv/lib/python2.7/site-packages
WSGIDaemonProcess dwm_py2 python-path=/var/www/dwm2:/var/www/dwm2/env/lib/python2.7/site-packages

<VirtualHost *:443>
        ServerAdmin <my email>
        ServerName <my server IP address>
        SSLEngine On

        Alias /staging/static/ /var/www/staging_dwm/public/static/
        <Directory /var/www/staging_dwm/public/static>
                #Order allow,deny
                #Allow from all
                Require all granted
                </Directory>
        WSGIScriptAlias /staging /var/www/staging_dwm/app/wsgi.py
        WSGIPassAuthorization On
        <Directory /var/www/staging_dwm/app>
                #Order allow,deny
                #Allow from all
                Require all granted
                </Directory>
        
Alias /archive/static/ /var/www/staging_dwm2/public/static/
        <Directory /var/www/staging_dwm2/public/static>
                #Order allow,deny
                #Allow from all
                Require all granted
                </Directory>

        WSGIScriptAlias /archive /var/www/staging_dwm2/app/wsgi.py
        WSGIPassAuthorization On
        <Directory /var/www/staging_dwm2/app>
                #Order allow,deny
                #Allow from all
                Require all granted
                </Directory>

        Alias /static/ /var/www/dwm/public/static/
        <Directory /var/www/dwm/public/static>
                #Order allow,deny
                #Allow from all
                Require all granted
                </Directory>
        WSGIScriptAlias / /var/www/dwm/app/wsgi.py
        WSGIPassAuthorization On
        <Directory /var/www/dwm/app>
                #Order allow,deny
                #Allow from all
                Require all granted
                </Directory>

        <Location />
                #WSGIProcessGroup dwm_py
                WSGIApplicationGroup %{GLOBAL}

                </Location>
        <Location /staging>
                #WSGIProcessGroup staging_dwm_py
                WSGIApplicationGroup %{GLOBAL}
                </Location>
        <Location /archive>
                WSGIProcessGroup staging_dwm_py2
                #WSGIApplicationGroup %{GLOBAL}
                </Location>

        </VirtualHost> 
```

Can someone please check this virtual host configuration and see what I have done wrong? It works fine with `WSGIApplicationGroup %{GLOBAL}`, but then only the main subsite at `/` site works, so if I use `WSGIProcessGroup` to distinguish between two different sub sites (like I have done above), the subsite at `/archive` doesn't work and the apache error logs say that there was a script timeout.

**Comment by GrahamDumpleton** [comment]
A few things. Don't use ``python-path`` with ``site-packages`` to specify the location of the Python virtual environment. Use ``python-home`` with the root of the virtual environment instead. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

The order of your location directives will not result in the desire you want. The nested paths must be first. By having ``/`` first, it will always be selected and take precedence. Use:

```
        <Location /staging>
                #WSGIProcessGroup staging_dwm_py
                WSGIApplicationGroup %{GLOBAL}
                </Location>
        <Location /archive>
                WSGIProcessGroup staging_dwm_py2
                #WSGIApplicationGroup %{GLOBAL}
                </Location>

        <Location />
                #WSGIProcessGroup dwm_py
                WSGIApplicationGroup %{GLOBAL}

                </Location>
```

Better still don't use ``WSGIProcessGroup`` and ``WSGIApplicationGroup`` in ``Location`` directives. Would always discourage that.

A better approach is to delete the ``Location`` directives and what they contain, and instead modify the ``WSGIScriptAlias`` directives so you have:

```
WSGIScriptAlias /staging /var/www/staging_dwm/app/wsgi.py process-group=staging_dwm_py application-group=%{GLOBAL}
WSGIScriptAlias /archive /var/www/staging_dwm2/app/wsgi.py process-group=staging_dwm_py2 application-group=%{GLOBAL}
WSGIScriptAlias /  /var/www/dwm/app/wsgi.py process-group=dwm_py application-group=%{GLOBAL}
```

There is no point defining ``WSGIPassAuthorization`` more than once at same scope with same value. The last one always applies anyway. Thus only need it once.

The ``ServerName`` directive shouldn't be an IP address. It should be the fully qualified hostname. If IP address is working, it is only because you have only the one ``VirtualHost`` and when it fails name based lookup for virtual hosts, it is falling back to using the first ``VirtualHost`` it found.

If you need to handle requests for multiple hostnames, use different ``VirtualHost`` definitions.

**Comment by orkuva** [comment]
Thank you, I tried it, but it's still not working. My file looks like this at the moment:


```
NameVirtualHost *:80
NameVirtualHost *:443

<VirtualHost *:80>
	ServerAdmin <email>
	ServerName <IP addresS>
	#Redirect permanent / https://dwm2.med.virginia.edu/
	</VirtualHost>


WSGISocketPrefix run/wsgi

WSGIDaemonProcess staging_dwm_py python-home=/var/www/staging_dwm:/var/www/staging_dwm/env
WSGIDaemonProcess dwm_py python-home=/var/www/dwm/dwmenv
WSGIDaemonProcess staging_dwm_py2 python-home=/var/www/staging_dwm2/dwmenv


<VirtualHost *:443>
	ServerAdmin pmy@virginia.edu
	ServerName 52.203.13.178
	SSLEngine On

	##### Staging Site #####

	Alias /staging/static/ /var/www/staging_dwm/public/static/
	<Directory /var/www/staging_dwm/public/static>
		#Order allow,deny
		#Allow from all
		Require all granted
	</Directory>
	WSGIScriptAlias /staging /var/www/staging_dwm/app/wsgi.py process-group=staging_dwm_py application-group=%{GLOBAL}

	<Directory /var/www/staging_dwm/app>
		#Order allow,deny
		#Allow from all
		Require all granted
	</Directory>
    
    ##### Archive Site ######

    Alias /archive/static/ /var/www/staging_dwm2/public/static/
	<Directory /var/www/staging_dwm2/public/static>
		#Order allow,deny
		#Allow from all
		Require all granted
	</Directory>

	WSGIScriptAlias /archive /var/www/staging_dwm2/app/wsgi.py process-group=staging_dwm_py2 application-group=%{GLOBAL}
	
	#WSGIPassAuthorization On
	<Directory /var/www/staging_dwm2/app>
		#Order allow,deny
		#Allow from all
		Require all granted
	</Directory>
        
	
	##### Main Site ######

	Alias /static/ /var/www/dwm/public/static/
	<Directory /var/www/dwm/public/static>
		#Order allow,deny
		#Allow from all
		Require all granted
	</Directory>
	
	WSGIScriptAlias /  /var/www/dwm/app/wsgi.py process-group=dwm_py application-group=%{GLOBAL}
	WSGIPassAuthorization On
	<Directory /var/www/dwm/app>
		#Order allow,deny
		#Allow from all
		Require all granted
	</Directory>
	

	</VirtualHost>

```

**Comment by orkuva** [comment]
I have semi-fixed the issue using the following virtual host configuration. Now I am able to run both production and staging site, but one at a time after apache starts. After starting apache, if I go to the prod site first and login, it works fine. but if I go to the staging site and try to login (it does go till the login page), it keeps on loading in the browser and apache logs show a timeout.
 
_However_,  if I restart apache and go to the staging site first and login, it works fine. But then if I navigate to the prod site, it takes me to the login page, but after I try to login it keeps loading and shows a timeout error in apache logs after a while. I'll open a separate issue for that. 

Pasting current virtual host config below:

```

NameVirtualHost *:80
NameVirtualHost *:443

<VirtualHost *:80>
	ServerAdmin <my-email>
	ServerName <my-prod-website>
	Redirect permanent / <my-https-website>/
</VirtualHost>

WSGISocketPrefix run/wsgi

WSGIDaemonProcess dwm_py python-home=/var/www/dwm/dwmenv

<VirtualHost *:443>
	ServerAdmin <my-email>
	ServerName <my-website>
	SSLEngine On

##### Archive Site #######    
    Alias /archive/static/ /var/www/staging_dwm2/public/static/
	<Directory /var/www/staging_dwm2/public/static>
		Require all granted
	</Directory>
	WSGIScriptAlias /archive /var/www/staging_dwm2/app/wsgi.py
	<Directory /var/www/staging_dwm2/app>
		Require all granted
	</Directory>
       
 #### Main Site ##### 
	Alias /static/ /var/www/dwm/public/static/
	<Directory /var/www/dwm/public/static>
		Require all granted
	</Directory>
	WSGIScriptAlias / /var/www/dwm/app/wsgi.py
	WSGIPassAuthorization On
	<Directory /var/www/dwm/app>
		Require all granted
	</Directory>
</VirtualHost> 

```

**Comment by tharun-reddy** [comment]
Have you figured out the issue. I am facing a similar problem where I have two django projects running. Each of them hangs when I try to access the other.

**Comment by GrahamDumpleton** [comment]
Please create a new issue and describe your particular problem. Don't post on old closed issues.

Also read:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

Ensure you are using daemon mode, one Django application per daemon mode process group and that you are forcing use of the main interpreter for each as per that link.
