### ISSUE TITLE
How to solve the error target script cannot be loaded as python module when django app deploy without port number

### ISSUE THREAD

**Issue by shelza1305** [GrahamDumpleton/mod_wsgi#424]
000-default.conf
<VirtualHost *:80>
    ServerName djangoapp.tk
    ServerAlias www.djangoapp.tk

    ErrorLog ${APACHE_LOG_DIR}/mysite-error.log
    CustomLog ${APACHE_LOG_DIR}/mysite-access.log combined

    WSGIDaemonProcess new_project python-path=/var/www/html/project/new_project/  python-home=/var/www/html/project/myvenv/
    WSGIApplicationGroup %{GLOBAL}
    WSGIProcessGroup new_project
    WSGIScriptAlias / /var/www/html/project/new_project/new_project/wsgi.py

  <Directory />
      #Options FollowSymLinks
      Options Indexes FollowSymLinks
      Require all granted
  </Directory>
  <Directory /var/www/html/project/new_project/new_project/>
            WSGIScriptAlias / /var/www/html/project/new_project/new_project/wsgi.py

 </Directory>

    

</VirtualHost>

wsgi.py

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'new_project.settings')

application = get_wsgi_application()

When i restart apache server,it gives me internal server error(500) i.e. Target WSGI scripts cannot be loaded as python module.

**Comment by GrahamDumpleton** [comment]
To solve this, you would need to look at the Python error and traceback in the error log file, which appears after the "Target WSGI script cannot be loaded as python module" and work out what the problem is from that. You haven't supplied what that error traceback and message is, so I can't help with it. If the error changes after the first request to the process to one that mentions that Django initialisation is not re-entrant, ensure you look at the first Python error message produced by a request to the process as that will show the real cause of the problem.

**Comment by shelza1305** [comment]
This is the error i got
[Mon May 13 11:25:52.750080 2019] [wsgi:error] [pid 4785:tid 139901621262080] [remote 103.8.116.143:61281] mod_wsgi (pid=4785): Target WSGI script '/var/www/html/project/new_project/new_project/wsgi.py' cannot be loaded as Python module.
[Mon May 13 11:25:52.750124 2019] [wsgi:error] [pid 4785:tid 139901621262080] [remote 103.8.116.143:61281] mod_wsgi (pid=4785): Exception occurred processing WSGI script '/var/www/html/project/new_project/new_project/wsgi.py'.
[Mon May 13 11:25:52.750196 2019] [wsgi:error] [pid 4785:tid 139901621262080] [remote 103.8.116.143:61281] Traceback (most recent call last):
[Mon May 13 11:25:52.750219 2019] [wsgi:error] [pid 4785:tid 139901621262080] [remote 103.8.116.143:61281]   File "/var/www/html/project/new_project/new_project/wsgi.py", line 12, in <module>
[Mon May 13 11:25:52.750233 2019] [wsgi:error] [pid 4785:tid 139901621262080] [remote 103.8.116.143:61281]     from django.core.wsgi import get_wsgi_application
[Mon May 13 11:25:52.750250 2019] [wsgi:error] [pid 4785:tid 139901621262080] [remote 103.8.116.143:61281] ImportError: No module named 'django'

**Comment by GrahamDumpleton** [comment]
Possible reasons are:

* Django is not installed in the virtual environment located at `/var/www/html/project/myvenv/`.

* The permissions on directories/files in `/var/www/html/project/myvenv/` are such that Apache user cannot read them.

* The virtual environment located at `/var/www/html/project/myvenv/` isn't constructed from the same Python version as the Python installation mod_wsgi was compiled for.

**Comment by shelza1305** [comment]
in virtual evironment..django folder is there
how to give permissions on directories /var/www/html/project/myvenv so that apache can read them
i am using same python versioni.e python3

**Comment by shelza1305** [comment]
for installation python i use these commands:
sudo apt-get install python3.6
python3
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
sudo update-alternatives --config python3
sudo apt-get install python3-pip
for mod_wsgi installation,use this command:
sudo apt-get install libapache2-mod-wsgi-py3
for installation of virtual environment
 sudo apt install python3.6-venv   
python3 -m venv myvenv  
 source myvenv/bin/activate
Please check if there is mismatch of version

**Comment by GrahamDumpleton** [comment]
To determine which version of Python mod_wsgi is compiled for, find the `mod_wsgi.so` file in the Apache modules directory, and from that directory run:

```
ldd mod_wsgi.so
```

What do you get?

To confirm what version of Python the virtual environment is using, run:

```
/var/www/html/project/myvenv/bin/python -V
```

What do you get?

Both mod_wsgi and the virtual environment both need to use Python 3.5, or both need to use Python 3.6. One cannot be 3.5 and the other 3.6. So saying both are Python 3 is not enough.

To verify that Django is actually installed, run:

```
/var/www/html/project/myvenv/bin/python
```

and at the interpreter prompt run:

```
import django
print(django.__file__)
```

To verify Apache user can access Django run:

```
sudo -u wwwserv /var/www/html/project/myvenv/bin/python
```

and at the interpreter prompt run as above.

What do you get?

Note that you will need to change `wwwserv` to what ever the name of the Apache user on your system.

If all that looks okay, the problem may be that AppArmor is enabled, but not set up with sensible defaults for Apache and so cannot read the directory where everything is installed.

**Comment by shelza1305** [comment]
ubuntu@ip-172-31-6-178:/etc/apache2$ ldd mod_wsgi.so
ldd: ./mod_wsgi.so: No such file or directory

(myvenv) ubuntu@ip-172-31-6-178:/var/www/html/project$ /var/www/html/project/myvenv/bin/python -V
Python 3.6.8
>>> import django
>>> print(django.__file__)
/var/www/html/project/myvenv/lib/python3.6/site-packages/django/__init__.py

(myvenv) ubuntu@ip-172-31-6-178:/var/www/html/project$ sudo -u www-data /var/www/html/project/myvenv/bin/python
Python 3.6.8 (default, May  7 2019, 14:58:50)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> print(django.__file__)
/var/www/html/project/myvenv/lib/python3.6/site-packages/django/__init__.py

**Comment by GrahamDumpleton** [comment]
As I already mentioned, you need to be in the Apache modules directory when you run `ldd`. So find the `mod_wsgi.so` file and make sure you are in that directory. I don't know how Ubuntu lays out the Apache directory, but it may be `/etc/apache2/modules`, but it may not be.

**Comment by shelza1305** [comment]
(myvenv) ubuntu@ip-172-31-6-178:/usr/lib/apache2/modules$ ldd mod_wsgi.so
        linux-vdso.so.1 =>  (0x00007ffc5ef2f000)
        libpython3.5m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0 (0x00007f9d5586c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9d5564f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9d55285000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f9d5505c000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9d54e42000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9d54c3e000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f9d54a3b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9d54732000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9d56126000)

**Comment by GrahamDumpleton** [comment]
So your mod_wsgi is compiled for Python 3.5. Your virtual environment is for Python 3.6. You need mod_wsgi compiled for Python 3.6 as a result. You cannot mix versions.

**Comment by shelza1305** [comment]
how to enable mod-wsgi is compiled for python 3.6?

**Comment by shelza1305** [comment]
i uninstall this package sudo apt-get remove libapache2-mod-wsgi-py3
and install pip install mod_wsgi
then it gives me error in my configuration files:
Invalid command 'mod_wsgi-express', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by shelza1305** [comment]
Invalid command 'WSGIDaemonProcess', perhaps misspelled or defined by a module not included in the server configuration

**Comment by shelza1305** [comment]
for solving this error,,,i just use sudo a2enmod wsgi
the module enabled and gives me error:
 Syntax error on line 1 of /etc/apache2/mods-enabled/wsgi.load: Cannot load /usr/lib/apache2/modules/mod_wsgi.so into server: /usr/lib/apache2/modules/mod_wsgi.so: cannot open shared object file: No such file or directory

**Comment by GrahamDumpleton** [comment]
You don't put the `mod_wsgi-express` command in the Apache config. You run:


```
mod_wsgi-express module-config
```

and copy the output from that into the `wsgi.load` file (I think that is the name), in the `modules-available` directory of Apache. The file shouldn't exist if you removed the system package for mod_wsgi. If it does exist, ensure system package is removed, or otherwise remove existing contents of the file before you add the output of `mod_wsgi-express module-config` to that file.

You should then be able to run:

```
a2enmod wsgi
```

You still need to configure Apache for your specific WSGI application.

**Comment by shelza1305** [comment]
its working..Thank so much for your help..
but i want to ask how static files work in django..if i give path in settings.py:
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
  then how static folder works

**Comment by GrahamDumpleton** [comment]
Check out the Django documentation on how to configure Apache to host static files.

https://docs.djangoproject.com/en/2.2/howto/deployment/wsgi/modwsgi/#serving-files

**Comment by shelza1305** [comment]
ok..i ll check this tutorial..
Really Thank you for your help...:)

**Comment by fspider** [comment]
Can you please help with this issue?

```
mod_wsgi (pid=2401): Target WSGI script '/var/www/html/autoIPTV/autoIPTV/wsgi.py' cannot be loaded as Python module.
[Thu Oct 14 20:03:04.145920 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] mod_wsgi (pid=2401): Exception occurred processing WSGI script '/var/www/html/autoIPTV/autoIPTV/wsgi.py'.
[Thu Oct 14 20:03:04.146388 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] Traceback (most recent call last):
[Thu Oct 14 20:03:04.146455 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/MySQLdb/__init__.py", line 18, in <module>
[Thu Oct 14 20:03:04.146466 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     from . import _mysql
[Thu Oct 14 20:03:04.146489 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] ImportError: cannot import name '_mysql'
[Thu Oct 14 20:03:04.146506 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] 
[Thu Oct 14 20:03:04.146512 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] During handling of the above exception, another exception occurred:
[Thu Oct 14 20:03:04.146517 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] 
[Thu Oct 14 20:03:04.146527 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] Traceback (most recent call last):
[Thu Oct 14 20:03:04.146677 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/autoIPTV/autoIPTV/wsgi.py", line 18, in <module>
[Thu Oct 14 20:03:04.146702 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     application = get_wsgi_application()
[Thu Oct 14 20:03:04.146718 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Oct 14 20:03:04.146725 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     django.setup(set_prefix=False)
[Thu Oct 14 20:03:04.146736 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
[Thu Oct 14 20:03:04.146742 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     apps.populate(settings.INSTALLED_APPS)
[Thu Oct 14 20:03:04.146753 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/apps/registry.py", line 115, in populate
[Thu Oct 14 20:03:04.146762 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     app_config.import_models()
[Thu Oct 14 20:03:04.146773 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
[Thu Oct 14 20:03:04.146801 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     self.models_module = import_module(models_module_name)
[Thu Oct 14 20:03:04.146814 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Thu Oct 14 20:03:04.146821 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Oct 14 20:03:04.146831 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Thu Oct 14 20:03:04.146845 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Thu Oct 14 20:03:04.146856 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[Thu Oct 14 20:03:04.146868 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[Thu Oct 14 20:03:04.146879 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[Thu Oct 14 20:03:04.146890 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Thu Oct 14 20:03:04.146901 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/autoIPTV/adminApp/models.py", line 8, in <module>
[Thu Oct 14 20:03:04.146907 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     from django.contrib.auth.models import User
[Thu Oct 14 20:03:04.146918 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
[Thu Oct 14 20:03:04.146924 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
[Thu Oct 14 20:03:04.146935 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
[Thu Oct 14 20:03:04.146942 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     class AbstractBaseUser(models.Model):
[Thu Oct 14 20:03:04.146952 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/db/models/base.py", line 122, in __new__
[Thu Oct 14 20:03:04.146959 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     new_class.add_to_class('_meta', Options(meta, app_label))
[Thu Oct 14 20:03:04.146969 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
[Thu Oct 14 20:03:04.146975 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     value.contribute_to_class(cls, name)
[Thu Oct 14 20:03:04.146996 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/db/models/options.py", line 206, in contribute_to_class
[Thu Oct 14 20:03:04.147012 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
[Thu Oct 14 20:03:04.147026 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
[Thu Oct 14 20:03:04.147033 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     return getattr(connections[DEFAULT_DB_ALIAS], item)
[Thu Oct 14 20:03:04.147043 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/db/utils.py", line 214, in __getitem__
[Thu Oct 14 20:03:04.147050 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     backend = load_backend(db['ENGINE'])
[Thu Oct 14 20:03:04.147067 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
[Thu Oct 14 20:03:04.147075 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     return import_module('%s.base' % backend_name)
[Thu Oct 14 20:03:04.147086 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Thu Oct 14 20:03:04.147092 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Oct 14 20:03:04.147103 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
[Thu Oct 14 20:03:04.147111 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     import MySQLdb as Database
[Thu Oct 14 20:03:04.147121 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/MySQLdb/__init__.py", line 24, in <module>
[Thu Oct 14 20:03:04.147127 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205]     version_info, _mysql.version_info, _mysql.__file__
[Thu Oct 14 20:03:04.147149 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:19205] NameError: name '_mysql' is not defined
[Thu Oct 14 20:03:04.560683 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:4968] mod_wsgi (pid=2401): Target WSGI script '/var/www/html/autoIPTV/autoIPTV/wsgi.py' cannot be loaded as Python module.
[Thu Oct 14 20:03:04.560968 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:4968] mod_wsgi (pid=2401): Exception occurred processing WSGI script '/var/www/html/autoIPTV/autoIPTV/wsgi.py'.
[Thu Oct 14 20:03:04.561508 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:4968] Traceback (most recent call last):
[Thu Oct 14 20:03:04.561643 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:4968]   File "/var/www/html/envAutoIPTV/lib/python3.8/site-packages/MySQLdb/__init__.py", line 18, in <module>
[Thu Oct 14 20:03:04.561739 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:4968]     from . import _mysql
[Thu Oct 14 20:03:04.561855 2021] [wsgi:error] [pid 2401] [remote 104.227.23.10:4968] ImportError: cannot import name '_mysql'

```

**Comment by NilanjPatel** [comment]
> You don't put the `mod_wsgi-express` command in the Apache config. You run:
> 
> ```
> mod_wsgi-express module-config
> ```
> 
> and copy the output from that into the `wsgi.load` file (I think that is the name), in the `modules-available` directory of Apache. The file shouldn't exist if you removed the system package for mod_wsgi. If it does exist, ensure system package is removed, or otherwise remove existing contents of the file before you add the output of `mod_wsgi-express module-config` to that file.
> 
> You should then be able to run:
> 
> ```
> a2enmod wsgi
> ```
> 
> You still need to configure Apache for your specific WSGI application.

Can you please tell me in which file should put output of this comment, if you can specify the file name and location.

**Comment by NilanjPatel** [comment]
I follow this and it is working now.

https://medium.com/@garethbjohnson/serve-python-3-7-with-mod-wsgi-on-ubuntu-16-d9c7ab79e03a
