### ISSUE TITLE
mod_wsgi-express   FreeBSD 12

### ISSUE THREAD

**Issue by forsgear** [GrahamDumpleton/mod_wsgi#425]
Hello , 
I try to use  mod_wsgi-express  on  FreeBSD 12 , Appache2.4 , Python 3.7
and I  faced with error  for all version after  4.5.7    ,  4.5.7  works . I faced only a problem. it was error with  mime.type file , which was  in different location instead of  that mod_wsgi-express  wants.
4.5.8.  after running  mod_wsgi-express start-server , system shows setup-server information and 
"exec: -a: not found "

All more recent versions  show the next   after running  mod_wsgi-express start-server
(first - this is my venv )

shows setup-server information and 

Traceback (most recent call last):
File "/usr/first/bin/mod_wsgi==4.6.5", line 11 , in <module>
   load_entry_point('mod-wsgi==4.6.5', 'console_scripts', 'mos_wsgi-express')()
File "/usr/first/lib/python3.7/site-packages/mod-wsgi/server/__init__.py", line 3578, in main  cmd_start_server(args) 
File "/usr/first/lib/python3.7/site-packages/mod-wsgi/server/__init__.py", line 3432, in cmd_start_server
os.execl(executable, executable, 'start', '-DFOREGROUND')
File "usr/local/lib/python3.7/os.py", line 539, in execl 
  execv(file, args)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by GrahamDumpleton** [comment]
Likely because FreeBSD 12 doesn't have `/bin/bash`. See https://github.com/GrahamDumpleton/mod_wsgi/issues/421

**Comment by GrahamDumpleton** [comment]
Can you try with:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

and see if that works for you.

**Comment by forsgear** [comment]
Yes , it works!
