### ISSUE TITLE
[client 127.0.0.1:39178] mod_wsgi (pid=32633): Target WSGI script '/var/www/budbit/stockAdmin/stockAdmin/wsgi.py' cannot be loaded as Python module.

### ISSUE THREAD

**Issue by xianytt** [GrahamDumpleton/mod_wsgi#426]
I'm try to deploy virtual host my django project into apache2 via mod_wsgi WSGIDaemon method, i'm using centos 7 and i'm getting following error.

[Wed May 22 13:49:01.688360 2019] [wsgi:error] [pid 32633:tid 140181873059584] [client 127.0.0.1:39178] mod_wsgi (pid=32633): Target WSGI script '/var/www/budbit/stockAdmin/stockAdmin/wsgi.py' cannot be loaded as Python module.
[Wed May 22 13:49:01.688437 2019] [wsgi:error] [pid 32633:tid 140181873059584] [client 127.0.0.1:39178] mod_wsgi (pid=32633): Exception occurred processing WSGI script '/var/www/budbit/stockAdmin/stockAdmin/wsgi.py'.
[Wed May 22 13:49:01.688519 2019] [wsgi:error] [pid 32633:tid 140181873059584] [client 127.0.0.1:39178] Traceback (most recent call last):
[Wed May 22 13:49:01.688541 2019] [wsgi:error] [pid 32633:tid 140181873059584] [client 127.0.0.1:39178]   File "/var/www/budbit/stockAdmin/stockAdmin/wsgi.py", line 12, in <module>
[Wed May 22 13:49:01.688544 2019] [wsgi:error] [pid 32633:tid 140181873059584] [client 127.0.0.1:39178]     from django.core.wsgi import get_wsgi_application
[Wed May 22 13:49:01.688558 2019] [wsgi:error] [pid 32633:tid 140181873059584] [client 127.0.0.1:39178] ModuleNotFoundError: No module named 'django'

Here my httpd.conf file:
LoadModule wsgi_module modules/mod_wsgi.so
WSGIPythonHome /home/env/pyweb

<VirtualHost *:80>
    DocumentRoot  "/var/www/budbit/stockAdmin"
    WSGIScriptAlias  / "/var/www/budbit/stockAdmin/stockAdmin/wsgi.py"
    <Directory  /var/www/budbit/stockAdmin/static>
        Require all granted
    </Directory>
    <Directory  /var/www/budbit/stockAdmin>
        AllowOverride all
        Require all granted
    </Directory>
</VirtualHost>

Here my wsgi.py file:

import os,sys

from django.core.wsgi import get_wsgi_application

sys.path.append('/var/www/budbit/stockAdmin')

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'stockAdmin.settings')

application = get_wsgi_application()

**Comment by GrahamDumpleton** [comment]
Possible reasons are:

* The `/home/env/` directory is not readable to Apache user. What do you get for `ls -lasd /home/env/`?

* The version of Python used to create the virtual environment `/home/env/pyweb` is different to what mod_wsgi was compiled for. What version of Python is mod_wsgi compiled for? What does `ldd mod_wsgi.so` output when run in the directory where the Apache modules are installed?

* You have SELinux enabled and it is blocking access to `/home/env/`.

You also aren't using daemon mode as you suggest you are. There is no configuration in what you show for that.

**Comment by xianytt** [comment]
(pyweb) [root@ckdata bin]# ls -lasd /home/env/
4 drwxr-xr-x 3 root root 4096 Apr 23 17:28 /home/env/
(pyweb) [root@ckdata bin]# setenforce 0
setenforce: SELinux is disabled

(pyweb) [root@ckdata bin]# /home/env/pyweb/bin/python -V
Python 3.6.5
(pyweb) [root@ckdata bin]# ldd /usr/local/apache24/modules/mod_wsgi.so 
	linux-vdso.so.1 =>  (0x00007ffdfbd14000)
	libpython3.6m.so.1.0 => /lib64/libpython3.6m.so.1.0 (0x00007fc9b0082000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc9afe66000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc9afc62000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fc9afa5f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc9af75d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc9af390000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc9b07e5000)


i am using same python versioni.e python3

**Comment by GrahamDumpleton** [comment]
How come your Apache is in `/usr/local/apache24` and not using system Apache? You are definitely using the one under `/usr/local/apache24`?

Try also this:

```
source /home/env/pyweb/bin/activate
python -c 'import django; print(django.__file__)'
```

Then do that again, but after first doing:

```
sudo -u apache bash
```

If your Apache user is not `apache`, use the actual user.

The second time, you are seeing if the Apache user can access the module.

**Comment by xianytt** [comment]
When I try these commands, it shows
/home/env/pyweb/lib/python3.6/site-packages/django/__init__.py，
I restarted the apache service, but it is still an old problem.

**Comment by xianytt** [comment]
Thanks for your reply and consideration.
I modified it according to your proposal and found that the restart will appear.
[Wed May 22 16:30:48.328239 2019] [mpm_event:notice] [pid 14972:tid 140182119180160] AH00494: SIGHUP received. Attempting to restart
[Wed May 22 16:30:48.333648 2019] [mpm_event:notice] [pid 14972:tid 140182119180160] AH00489: Apache/2.4.39 (Unix) mod_wsgi/4.5.7 Python/3.6 configured -- resuming normal operations
[Wed May 22 16:30:48.333676 2019] [core:notice] [pid 14972:tid 140182119180160] AH00094: Command line: '/usr/local/apache24//bin/httpd'

**Comment by GrahamDumpleton** [comment]
If import the `django` import in your `wsgi.py` file you add:

```
print(sys.path)
```

What does it show in the logs?

**Comment by GrahamDumpleton** [comment]
No further followup so assumed sorted it out or gave up. Closing issue.
