### ISSUE TITLE
can we run django and php site in same domain using apache server

### ISSUE THREAD

**Issue by nishtha03** [GrahamDumpleton/mod_wsgi#428]

**Comment by GrahamDumpleton** [comment]
See: 

* http://blog.dscpl.com.au/2014/09/hosting-php-web-applications-in.html

**Comment by nishtha03** [comment]
i unerstood but i am little confused that how to set in httpconf file..this is what i am doing

<VirtualHost *:80>
    LoadModule wsgi_module "c:/python/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win32.pyd"
    DocumentRoot "D:/django/django-env/myproject"
    ServerName localhost
    WSGIScriptAlias / "D:/django/django-env/myproject/myproject/wsgi.py"
    <Directory "D:/django/django-env/myproject/myproject">
       Require all granted
        
    </Directory>
    
 DocumentRoot "C:/xampp/htdocs/paperclip"
   
</VirtualHost>

django project works..but php code does'nt

**Comment by GrahamDumpleton** [comment]
All I can suggest is to read the post again. It mentions your exact problem. Quoting the post:

> The primary problem if it isn't obvious is that using 'WSGIScriptAlias' for '/' means that all requests to the site are being hijacked and sent into the Python web application. In other words, it would shadow any existing PHP web application that may be hosted out of the document directory for the web server.

The blog post then goes on to explain your options, which is to host the Django application at a sub URL, or use a more complicated configuration where requests will only get passed through to Django, if the URL doesn't map to a PHP resource. That later option also requires some fixups to be done on the `wsgi.py` file of Django.

**Comment by nishtha03** [comment]
DocumentRoot /var/www/html
<Directory /var/www/html>
Options ExecCGI
DirectoryIndex index.py index.php
AddHandler application/x-httpd-php .php
AddHandler wsgi-script .py
</Directory>


hey what is the index.py file in that code..actually i am able to run php coe but when i redirect to django its shows only 1st page

**Comment by GrahamDumpleton** [comment]
The post explains it:

> That is, you can now simply drop Python code files with a '.py' extension into the directory and they would be executed as Python code when a URL mapped to that file. So if instead of 'index.php' you had 'index.py', accessing the URL for the directory, Apache in seeing that 'index.py' now exists, would use that to serve the request rather than 'index.php'. If the URL instead explicitly referenced a '.py' file by name, then that would be executed to handle the request instead.

Anything in `DirectoryIndex` would be tried as means to serve a request against the directory. See more in the Apache docs.

http://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryindex

You aren't going to be relying on it, so remove `index.py` from `DirectoryIndex` if that is what you are using.

**Comment by nishtha03** [comment]
hey i am able to run run php and django using suburl..now the problem is when i am trying to access django project every timee need to add a suburl in every django urls..how can fix it

**Comment by GrahamDumpleton** [comment]
You should not be hard coding paths in your html templates or code. For templates you should use `url`. See:

* https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#url

There is a similar function for in code.

When you use this correctly, any sub URL mount point will be automatically added at the start of generated paths.

**Comment by nishtha03** [comment]
done..thank you

**Comment by juni05** [comment]
> done..thank you

Can you guide me how did you managed to host both sites under same domain. it would be highly appreciated! Thankyou!

**Comment by GrahamDumpleton** [comment]
I already provided the link with details above. Did you read:

* http://blog.dscpl.com.au/2014/09/hosting-php-web-applications-in.html

**Comment by NilanjPatel** [comment]
> done..thank you

can you provide solution for this.

**Comment by GrahamDumpleton** [comment]
@NilanjPatel Don't know how many times need to say this about this issue. Read the linked blog post. Unless you provided actual details about your problem it is impossible to provide any solution as I can't guess how you have things setup, or what error/problem you have. Create a new issue with all details specific to your problem if the blog post doesn't help.

**Comment by NilanjPatel** [comment]
yes. you already posted it. But as this person did it for specifically Django application. it would be great and time saving for me. as I am quite new with this field. no worries. I really appreciate your contribution. I will post separately with the error.

**Comment by Chandan975** [comment]
like two project 1) django project and 2) laravel project both are run same domain and one directory how

**Comment by GrahamDumpleton** [comment]
@Chandan975 What did you actually try to use based on the linked blog post about it?
