### ISSUE TITLE
can not deploy django in apache with centos 7

### ISSUE THREAD

**Issue by KuroSol** [GrahamDumpleton/mod_wsgi#432]
I tried many ways and ask my server management sounds like I have wsgi_mode enable and run Django in runserver I set my SQL database as well python 3.6 
but still, I can not use Django in the subdomain I made
http://imhtest.zporta.com/test.wsgi its work well 
http://imhtest.zporta.com/test_db.py connect to database
but i have my django in 
http://imhtest.zporta.com/django1
and my project is in
http://imhtest.zporta.com/django1/project1
but still i can not get anything
i made django.wsgi in sub domain and still get error 
http://imhtest.zporta.com/django.wsgi
please help me i trid it for about 2 month but no result :(
the log error latlly is like this 
 [Thu May 30 06:11:56.807532 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980] mod_wsgi (pid=16227): Failed to exec Python script file '/home/zporta6/imhtest.zporta.com/django.wsgi'., referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807559 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980] mod_wsgi (pid=16227): Exception occurred processing WSGI script '/home/zporta6/imhtest.zporta.com/django.wsgi'., referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807574 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980] Traceback (most recent call last):, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807584 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/home/zporta6/imhtest.zporta.com/django.wsgi", line 10, in <module>, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807619 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     application = django.core.handlers.wsgi.WSGIHandler(), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807628 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807678 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     self.load_middleware(), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807685 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 80, in load_middleware, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807736 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     middleware = import_string(middleware_path), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807743 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807781 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     module = import_module(module_path), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807787 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807810 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     __import__(name), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807816 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/contrib/auth/middleware.py", line 4, in <module>, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807849 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     from django.contrib.auth.backends import RemoteUserBackend, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807854 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/contrib/auth/backends.py", line 4, in <module>, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807892 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     from django.contrib.auth.models import Permission, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807898 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807970 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.807976 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808009 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     class AbstractBaseUser(models.Model):, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808015 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 110, in __new__, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808238 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     app_config = apps.get_containing_app_config(module), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808244 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 247, in get_containing_app_config, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808315 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     self.check_apps_ready(), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808321 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]   File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 125, in check_apps_ready, referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808331 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980]     raise AppRegistryNotReady("Apps aren't loaded yet."), referer: http://imhtest.zporta.com/
[Thu May 30 06:11:56.808339 2019] [wsgi:error] [pid 16227:tid 47892811679488] [client 223.24.152.13:58980] AppRegistryNotReady: Apps aren't loaded yet., referer: http://imhtest.zporta.com/

my pre_virtualhost_global.confGlobal for http.conf is 
LoadModule wsgi_module "/usr/lib64/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"
AddHandler wsgi-script .wsgi
<Directory home/zporta6/imhtest.zporta.com/django1/project1>
<Files wsgi.py>
Order deny,allow
Allow from all
</Files>
</Directory>

what should i do really please help me !!!

**Comment by GrahamDumpleton** [comment]
Sorry for the slow reply. Google sent the notification email for this issue to SPAM folder.

For Django, once you have mod_wsgi loaded into Apache, see the Django documentation on how to add Django to the Apache configuration.

* https://docs.djangoproject.com/en/2.2/howto/deployment/wsgi/modwsgi/

Your current approach of trying to use ``AddHandler`` is not a good way of going back it. So check the Django docs.
