### ISSUE TITLE
Django application hosting with apache using mod_wsgi not accessible through server domain but accessible through server IP

### ISSUE THREAD

**Issue by Khushali22** [GrahamDumpleton/mod_wsgi#433]
I am trying to deploy my django apps on apache server using wsgi mod. But my issue is i can access my django application through server IP, but i cant access same through server domain name. By using server domain name, it is listing down files inside that folder.
000-default.conf file:-

```
<VirtualHost *:80>
         ServerAdmin xyz@gmail.com
        ServerName domainname.com
        ServerAlias www.domainname.com
	#DocumentRoot /var/www/html
	
	Alias /demo_shopify_python/static /var/www/html/demo_shopify_python/static
        <Directory /var/www/html/demo_shopify_python/static>
                Require all granted
        </Directory>

        WSGIDaemonProcess demo_shopify_python python-home=/var/www/html/demo_shopify_python/virtual python-path=/var/www/html/demo_shopify_python
        WSGIProcessGroup demo_shopify_python
        WSGIScriptAlias /demo_shopify_python /var/www/html/demo_shopify_python/demo_shopify_python/wsgi.py process-group=demo_shopify_python application-group=%{GLOBAL}

        <Directory /var/www/html/demo_shopify_python/demo_shopify_python>
                <Files wsgi.py>
                     Require all granted
                </Files>
        </Directory>

	Alias /static /var/www/html/myproject/static
        <Directory /var/www/html/myproject/static>
                Require all granted
        </Directory>

        WSGIDaemonProcess myproject python-home=/var/www/html/myproject/myprojectenv python-path=/var/www/html/myproject
        WSGIProcessGroup myproject
        WSGIScriptAlias /myproject /var/www/html/myproject/myproject/wsgi.py process-group=myproject application-group=%{GLOBAL}

        <Directory /var/www/html/myproject/myproject>
                <Files wsgi.py>
                     Require all granted
                </Files>
        </Directory>

        LogLevel info

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

  
	RewriteEngine on
       RewriteCond %{SERVER_NAME} =www.domainname.com [OR]
      RewriteCond %{SERVER_NAME} =domainname.com
     RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

Nothing in apache server logs except i found this on logs:-

```
[wsgi:warn] [pid 2178] mod_wsgi: Compiled for Python/3.5.1+.
[wsgi:warn] [pid 2178] mod_wsgi: Runtime using Python/3.5.2.
versions:- mod_wsgi/4.3.0 Python/3.5.2
```

Any help is much appreciated!!
Thanks!

**Comment by GrahamDumpleton** [comment]
You have a rewrite rule for the hostname:

```
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

So you are redirecting to HTTPS on port 443 for those hostnames. So everything in that virtual host would be getting ignored in that case. The rewrite rule doesn't match when use IP.

**Comment by Khushali22** [comment]
Thanks! So what can i do to achieve this? To access through my domain? Should i comment out the rewrite rule?

**Comment by GrahamDumpleton** [comment]
If you don't want to force HTTPS, then yes.

If you need HTTPS, then add a `VirtualHost` for port 443 which is a copy of what you have for 80, except for the rewrite rule. Then add to the new `VirtualHost` the SSL configuration directives to set up your certificate. Or copy relevant bits into `VirtualHost` for port 443 that you already have. 

If you don't have a SSL certificate, then you should just use HTTP and comment out the rewrite rule.

**Comment by Khushali22** [comment]
Yes, I need to redirect to HTTPS and i have already add SSL certification from letsencrypt and they will redirect my http to https traffic. SO you mean to say i add configuration for virtualhost port 443 and add to 000-default.conf file and dont write rewrite rule there and same conf for port 443 add to 000-default-le-ssl.conf. Correct?

**Comment by GrahamDumpleton** [comment]
If you have already added SSL setup, that means you likely already have a `VirtualHost` for port 443, since it should not be at global scope outside of the virtual host definitions. Put all that stuff for setting up the Django application in the port 443 `VirtualHost` instead of that for port 80. Leave the rewrite rule in the port 80 `VirtualHost`.

**Comment by Khushali22** [comment]
Thank you very much. Its working now:)
