### ISSUE TITLE
Custom Python version: "cannot open shared object file"

### ISSUE THREAD

**Issue by nottheend** [GrahamDumpleton/mod_wsgi#435]
**aim:** 
- running Apache 2.4 on centos7 with mod_wsgi with Python 3.7

**so far:**
- read blog post http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html?m=1
- compiled Python 3.7.3 with commands:
```
./configure --enable-shared
make
make install

make distclean

./configure
make
make altbininstall
```

**current:** 
- compiling works, version `python 3.7 -V` prints `Python 3.7.3` 
- creating virtual environment fails:
```
$ python3.7 -m ~/venv
[...]
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```
after searching through several posts also set following options before compiling:
-  `export LD_RUN_PATH=/usr/local/lib`
- `./configure --prefix=/usr/local`
- `./configure --prefix=/usr/local --enable-shared LDFLAGS="-Wl,--rpath=/usr/local/lib`
- even copied the missing file from `/usr/local/lib` directly to `/usr/lib/libpython3.7m.so.1.0`
But either of the methods worked, error remains.

How could I resolve the problem?

**Comment by GrahamDumpleton** [comment]
When building Python from source code, if you re-run `configure` with different options or need to re-build with certain environment variables set, you should do a `make distclean` in Python source code first to ensure cached results of previous build removed. You don't mention anything about having done that.

**Comment by nottheend** [comment]
Thanks for pointing that out. I repeated some of the commands as follows:

```
# option 1
sudo ./configure --enable-shared
# ignore the message: "If you want a release build [...]"
sudo make
sudo make install
sudo make distclean
sudo ./configure
# ignore the message:
## If you want a release build with all stable optimizations active (PGO, etc),
## please run ./configure --enable-optimizations
sudo make
sudo make altbininstall
python3.7 -m venv ~/venv
# ouput:
#Traceback (most recent call last):
#  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
#    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
#  File "/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
#    return _get_module_details(pkg_main_name, error)
#  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
#    __import__(pkg_name)
#  File "/usr/local/lib/python3.7/venv/__init__.py", line 10, in <module>
#    import subprocess
#  File "/usr/local/lib/python3.7/subprocess.py", line 152, in <module>
#    import _posixsubprocess
#ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory


# option 2
sudo make distclean
export LD_RUN_PATH=/usr/local/lib
sudo ./configure --enable-shared
sudo make
sudo make install
sudo make distclean
sudo ./configure
sudo make
sudo make altbininstall
python3.7 -V
# output: Python 3.7.3
python3.7 -m venv ~/venv
# ouput:
#Traceback (most recent call last):
#  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
#    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
#  File "/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
#    return _get_module_details(pkg_main_name, error)
#  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
#    __import__(pkg_name)
#  File "/usr/local/lib/python3.7/venv/__init__.py", line 10, in <module>
#    import subprocess
#  File "/usr/local/lib/python3.7/subprocess.py", line 152, in <module>
#    import _posixsubprocess
#ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

# option 3
sudo make distclean
sudo ./configure --prefix=/usr/local
sudo make
sudo make install
sudo make distclean
sudo ./configure
sudo make
sudo make altbininstall
```

I'm flushed, because the third option seems to work.
The error doesn't appear any more while creating a virtual environment.

Is this a proper way build python from source?

The mentioned warning about the optimizations added some confusion to the process.

**Comment by GrahamDumpleton** [comment]
You should always have used ``--prefix=/usr/local`` with `configure` but you haven't, which suggests to me that at one point you might have installed into `/usr`. Do you have a `python3.7` in `/usr/bin` as well as `/usr/local/bin`? Was a system package for Python 3.7 every installed? Installing from source code into `/usr` rather than `/usr/local` is not usually a good idea because of conflicts can cause with system package.

**Comment by nottheend** [comment]
There has been no system package for Python 3.7 installed before.
I'll keep in mind not to install custom packages to `/usr` anymore, but to `/usr/local`

Summarizing, the set of commands to install Python 3.7 from source for using `mod_wsgi` would be this:

```
# first one is just because I tried it before
sudo make distclean
sudo ./configure --prefix=/usr/local --enable-shared --enable-optimizations
sudo make
sudo make install
sudo make distclean
sudo ./configure  --prefix=/usr/local --enable-optimizations
sudo make
sudo make altbininstall
```

Currently I'm working on DEV-System, therefore impact of mistakes on production is low

**Comment by nottheend** [comment]
_For informational purpose:_

The only way of compiling Python, which worked in my case is following:

```
sudo ./configure --prefix=/usr/local
sudo make
sudo make install
sudo make distclean
sudo ./configure
sudo make
sudo make altbininstall
```

There could be done some further investigating why `--enable-optimizations` does not work and why in this case `--share-enabled` breaks at least the `venv` command.

**Comment by GrahamDumpleton** [comment]
That is still wrong. You must use `--prefix=/usr/local` every time you run `configure`, not just the first time. And you are missing `--enable-shared`.

The reason you were likely having problems is that you were inconsistent about options and have installed one time under `/usr/local` and then the next time under `/usr/` rather than in the same spot, plus messed up when shared library was enabled. It likely only worked in the end as eventually you installed with shared library into both locations.
