### ISSUE TITLE
Truncated or oversized response headers received from daemon process using Django

### ISSUE THREAD

**Issue by guilhermej** [GrahamDumpleton/mod_wsgi#439]
I'm using Django to serve a website, but in some specific view manipulating a specific model I'm facing crashs in the Apache server with Mod_wsgi: this is the error found in the log: `Truncated or oversized response headers received from daemon process using Django: myprocess` and return an Error 500 for the user, I know this issue is very common and can have multiple reasons, I searched a lot before posting, and tried a lot of configurations.

Debuging I can assure that my code is OK.
Running localy with django dev server is OK, running with Nginx and Gunicorn is OK and running inside AWS Lambda with Zappa is OK. This appears only with Apache and Mod_wsgi.
But when I use apache it usually loads the page once after I restart apache server and after that the process  crashes and I have to restart apache again for the site to resume working, this crashs the whole process, and if i'm using more process this will crashing everyone of the process when I made another requests to access the page.

Since only one view gives this error and all other work fine I thought the problem was on the view but as I said before the view works fine on other servers and my logs are printed on terminal until right before the return render template, so the problem is definitely on the apache or mod_wsgi side.
I'm using:
```
Ubuntu 18.04 in a Dual-core 4GB AWS Instance.
Apache 2.4.29-1ubuntu4.6
Libapache2-mod-wsgi-py3 4.5.17-1
Python 3.6.8 64bit with Virtualenv
```

This is my apache virtual host conf:
```
 WSGIDaemonProcess myprocess python-home=/var/www/venv python-path=/var/www/myapp \
        processes=1 \
        threads=5
    WSGIProcessGroup myprocess
    WSGIScriptAlias / /var/www/myapp/myapp/wsgi.py

    ServerName my.domain

    <Directory /var/www/myapp/myapp>
        <Files wsgi.py>
            Order allow,deny
            Allow from all
        </Files>
    </Directory>

    Alias /static/ /var/www/myapp/myapp/static/
    Alias /media/ /var/www/myapp/myapp/media/

    <Directory /var/www/myapp/myapp/static>
        Order allow,deny
        Allow from all
    </Directory>

    SSLEngine on
    SSLCertificateFile /etc/my/certificate.pem
    SSLCertificateKeyFile /etc/my/privatekey.pem
```

My Virtualenv requirements:
```
amqp==1.4.9
anyjson==0.3.3
argcomplete==1.9.3
bcrypt==3.1.4
beautifulsoup4==4.6.0
billiard==3.3.0.23
bleach==2.1.3
boto3==1.7.63
botocore==1.10.63
bs4==0.0.1
celery==3.1.25
certifi==2017.7.27.1
cffi==1.11.5
cfn-flip==1.2.0
chardet==3.0.4
click==6.7
Collectfast==0.6.2
Django==1.11.13
django-activity-stream==0.6.4
django-ckeditor==5.3.1
django-datatables-view==1.16.0
django-debug-toolbar==1.9.1
django-js-asset==0.1.1
django-jsonfield==1.0.1
django-jsonfield-compat==0.4.4
django-pagseguro2==2.0.3
django-paypal==0.5.0
django-storages==1.6.6
django-widget-tweaks==1.4.1
djangorestframework==3.9.1
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
html5lib==1.0.1
idna==2.7
jmespath==0.9.3
jsonfield==2.0.2
kappa==0.6.0
kombu==3.0.37
lambda-packages==0.20.0
lxml==4.2.5
mysqlclient==1.3.12
piexif==1.0.13
Pillow==5.1.0
pkg-resources==0.0.0
placebo==0.9.0
pycparser==2.18
pycurl==7.43.0
pymediainfo==2.3.0
PyPDF2==1.26.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2019.1
PyVimeo==1.0.11
PyYAML==5.1
raven==6.3.0
redis==2.10.6
reportlab==3.4.0
requests==2.20.0
s3transfer==0.1.13
six==1.10.0
sqlparse==0.2.4
tinydb==3.11.1
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.6
tuspy==0.2.1
Unidecode==1.0.23
urllib3==1.24
vine==1.1.4
webencodings==0.5.1
Werkzeug==0.15.2
wsgi-request-logger==0.4.6
xmltodict==0.11.0
```

I tried to tweak the apache conf with the variables send-buffer-size, receive-buffer, header-buffer-size, response-buffer-size and stack-size but with no success.

Does anyone know what could this be? Apache logs shows nothing, Django logs shows nothing, I have no idea what could be causing this timeout. The server show no spikes of memory or CPU when the crash happens, nothing, apache simply doesn't return the response.

**Comment by GrahamDumpleton** [comment]
Force the use of the main interpreter context. There are various third party Python packages that will fail when used in sub interpreters. This is especially problematic with Python packages in the data science space such as numpy, scipy etc. These issues can cause lock ups or process crashes. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

**Comment by guilhermej** [comment]
I yet tried to use the %{GLOBAL} in the vhost conf file but with no success, this raise an error that cannot find django module.
I use this conf:
````
WSGIDaemonProcess %{GLOBAL} python-home=/var/www/venv python-path=/var/www/myapp \
        processes=1 \
        threads=5
    WSGIProcessGroup %{GLOBAL}
    WSGIScriptAlias / /var/www/myapp/myapp/wsgi.py

    ServerName my.domain

    <Directory /var/www/myapp/myapp>
        <Files wsgi.py>
            Order allow,deny
            Allow from all
        </Files>
    </Directory>

    Alias /static/ /var/www/myapp/myapp/static/
    Alias /media/ /var/www/myapp/myapp/media/

    <Directory /var/www/myapp/myapp/static>
        Order allow,deny
        Allow from all
    </Directory>

    SSLEngine on
    SSLCertificateFile /etc/my/certificate.pem
    SSLCertificateKeyFile /etc/my/privatekey.pem
```

Are there a correct way to use it?

**Comment by guilhermej** [comment]
A observation, this View don't use none of the packages, only the standard Django and Python packages.

**Comment by GrahamDumpleton** [comment]
It is:

```
WSGIApplicationGroup %{GLOBAL}
```

not ``WSGIProcessGroup``. It should be added in addition to the existing ``WSGIProcessGroup`` directive.

**Comment by GrahamDumpleton** [comment]
BTW, also ensure using ``LogLevel info`` or more verbose. Capture the actual logs so can see messages before and after. Also look in main Apache error log file to see if it has any message about "Segmentation Fault".

**Comment by guilhermej** [comment]
> ```
> WSGIApplicationGroup %{GLOBAL}
> ```

Thank you very much @GrahamDumpleton , this works for me.

Congratulations for the good work maintaining this excellent project, this is the only server that can handle 500+ Django projects in one server without exploding memory and processing.

**Comment by GrahamDumpleton** [comment]
With the default config you have for Apache, you could do a lot better. You may want to watch:

* https://www.youtube.com/watch?v=CPz0s1CQsTE

and some of the suggested config mentioned.

Also perhaps watch:

* https://www.youtube.com/watch?v=k6Erh7oHvns

That is older, but still useful.

**Comment by guilhermej** [comment]
@GrahamDumpleton thanks a lot for the presentations, I learned a lot with them.

Can you give me a contact for a possible consulting job?

**Comment by GrahamDumpleton** [comment]
If you want to have general discussions about mod_wsgi setup and tuning, you are better off using the mailing list.

* https://modwsgi.readthedocs.io/en/develop/finding-help.html
