### ISSUE TITLE
Cannot connect via SSL to postgresql from mod_wsgi

### ISSUE THREAD

**Issue by satyanarayana-aibono** [GrahamDumpleton/mod_wsgi#440]
Using `mod_wsgi`, I am running Django server. I am unable to connect to postgresql from the running server. The postgres log says `could not accept SSL connection: EOF detected`. But, I can connect to postgresql from django's built-in server. 

I am making it work with adding `'OPTIONS': {'sslmode': 'disable'}` to the DB config in django. Basically not using SSL to connect to postgresql from django app.

Any help would be grateful.

**Comment by GrahamDumpleton** [comment]
If you are using ``psycopg2``, do not use the ``psycopg2-binary`` package. This is compiled with SSL libraries that are often incompatible with system SSL libraries that Apache is compiled with. Use ``psycopg2`` when installing and have it build from source code that package using your system SSL libraries.

**Comment by GrahamDumpleton** [comment]
Also indicate whether you are using Anaconda Python. That has its own incompatibilities around SSL libraries that cause problems.

**Comment by satyanarayana-aibono** [comment]
> Also indicate whether you are using Anaconda Python. That has its own incompatibilities around SSL libraries that cause problems.

I am not using Anaconda Python.



> If you are using `psycopg2`, do not use the `psycopg2-binary` package. This is compiled with SSL libraries that are often incompatible with system SSL libraries that Apache is compiled with. Use `psycopg2` when installing and have it build from source code that package using your system SSL libraries.

I am using `psycopg2-binary` package. I will use `psycopg2` and see if it fixes the issue.
