### ISSUE TITLE
[ Question ] How mod_wsgi runs python interpreter?

### ISSUE THREAD

**Issue by artempronevskiy** [GrahamDumpleton/mod_wsgi#441]
Graham, can you please describe or send link to documentation where I can get info about how mod_wsgi launches and runs python interpreter? For now as far as I understand the request/response flow is the following:
Client -> Request -> Apache2 Worker -> Response -> Client
where python interpreter gets launched inside mod_wsgi that gets launched inside apache 2 worker process as a part of a process. Right?

Thank you.

**Comment by GrahamDumpleton** [comment]
Can only suggest read:

* https://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html

as starting point.

One very important point. A Python interpreter is not created per request. The Python interpreter stays resident in the process and is used to handle successive requests.

Also perhaps watch:

* https://www.youtube.com/watch?v=PWIvm-uloMg

**Comment by artempronevskiy** [comment]
> One very important point. A Python interpreter is not created per request. The Python interpreter stays resident in the process and is used to handle successive requests.

Yes, I meant exactly that in the mentioned request/response flow.

Thanks for the links!
