### ISSUE TITLE
Gateway Timeout: (Fatal Python error: Py_Initialize: Unable to get the locale encoding ModuleNotFoundError: No module named 'encodings')

### ISSUE THREAD

**Issue by mrimran** [GrahamDumpleton/mod_wsgi#443]
I tried the fixes that were mentioned and trying some of them brings more issues. On my live server which have some PHP websites, I want to deploy some Django sites as well. 

I'm getting gateway time out and when I saw logs in error.log the following error keeps on repeating 

> Current thread 0x00007f1103e52bc0 (most recent call first):
> Fatal Python error: Py_Initialize: Unable to get the locale encoding
> ModuleNotFoundError: No module named 'encodings'

I saw your solution proposed here https://github.com/GrahamDumpleton/mod_wsgi/issues/336 but that produces even more errors for me like which look as below:

> [Thu Jun 27 15:23:28.435697 2019] [wsgi:info] [pid 15371] mod_wsgi (pid=15371): Attach interpreter ''.
> [Thu Jun 27 15:23:28.439128 2019] [wsgi:info] [pid 15370] mod_wsgi (pid=15370): Attach interpreter ''.
> [Thu Jun 27 15:23:33.110898 2019] [wsgi:info] [pid 15371] [remote 39.50.98.73:58938] mod_wsgi (pid=15371, process='propertyapp.proappdev.com', application=''): Loading WSGI script '/var/www/propertyapp/property/wsgi.py'.
> [Thu Jun 27 15:23:33.346836 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938] mod_wsgi (pid=15371): Target WSGI script '/var/www/propertyapp/property/wsgi.py' cannot be loaded as Python module.
> [Thu Jun 27 15:23:33.346891 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938] mod_wsgi (pid=15371): Exception occurred processing WSGI script '/var/www/propertyapp/property/wsgi.py'.
> [Thu Jun 27 15:23:33.347467 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938] Traceback (most recent call last):
> [Thu Jun 27 15:23:33.347513 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938]   File "/var/www/propertyapp/property/wsgi.py", line 16, in <module>
> [Thu Jun 27 15:23:33.347518 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938]     application = get_wsgi_application()
> [Thu Jun 27 15:23:33.347523 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938]   File "/home/imran/pyapps/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
> [Thu Jun 27 15:23:33.347526 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938]     django.setup(set_prefix=False)
> [Thu Jun 27 15:23:33.347531 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938]   File "/home/imran/pyapps/venv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
> [Thu Jun 27 15:23:33.347534 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
> [Thu Jun 27 15:23:33.347539 2019] [wsgi:error] [pid 15371] [remote 39.50.98.73:58938]   File "/home/imran/pyapps/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
> 

Server info:
Ubuntu 18.04.2 LTS
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2019-04-03T13:22:37

Here is output of sudo vi /etc/apache2/sites-enabled/propertyapp.someserver.com.conf:

```
WSGIRestrictEmbedded On
<VirtualHost *:80>
        ServerName propertyapp.somedomain.com
        DocumentRoot /var/www/propertyapp
        WSGIScriptAlias / /var/www/propertyapp/property/wsgi.py

        # adjust the following line to match your Python path 
        WSGIDaemonProcess propertyapp.somedomain.com processes=2 threads=15 display-name=%{GROUP} python-home=/home/imran/pyapps/venv/lib/python3.6
        #WSGIDaemonProcess propertyapp.somedomain.com processes=2 threads=15 display-name=%{GROUP} python-home=/home/imran/pyapps/venv
        WSGIProcessGroup propertyapp.somedomain.com
        WSGIApplicationGroup %{GLOBAL}
        <Directory />
            AllowOverride All
        </Directory>
        <Directory /var/www/propertyapp>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride all
            Require all granted
        </Directory>

        Alias /static/ /var/www/propertyapp/static/
        Alias /media/ /var/www/propertyapp/media/

        <Directory /var/www/propertyapp/static>
            Require all granted
        </Directory>

        <Directory /var/www/propertyapp/media>
            Require all granted
        </Directory>

        ErrorLog /var/log/apache2/propertyapp.somedomain.com-error.log
        LogLevel info
        CustomLog /var/log/apache2/propertyapp.somedomain.com-access.log combined
</VirtualHost>

```

Note: `propertyapp` is symlink from `/home/imran/pyapps/propertyapp` to `/var/www`. Output of `/var/www$ ls -la propertyapp`:

`lrwxrwxrwx  1 www-data www-data   30 Jun 27 12:41 propertyapp -> /home/imran/pyapps/propertyapp`

I've now spent almost my day to tackle this issue but problem remains there :(

Useful information if I run the project via python manage.py 0.0.0.0:8000 I can access it on server, but not via apache.

**Comment by Aprilhuu** [comment]
I got the same issue, but on Windows with Anaconda and python 3.7.3

**Comment by mrimran** [comment]
With the help of video tutorial here I fixed the issue https://www.youtube.com/watch?v=Xjdv31k-Kf4&t=2706s

My new config file look as below which works 100% correctly :)

```
<VirtualHost *:80>
        ServerName propertyapp.somedomain.com
        #DocumentRoot /home/imran/pyapps/propertyapp
        DocumentRoot /var/www/propertyapp

        <Directory /var/www/propertyapp/property/>
            <Files wsgi.py>
                Require all granted
            </Files>
        </Directory>

        # adjust the following line to match your Python path 
        WSGIDaemonProcess propertyapp processes=2 threads=15 display-name=%{GROUP} python-home=/home/imran/pyapps/venv python-path=/home/imran/pyapps/propertyapp
        #WSGIDaemonProcess propertyapp.somedomain.com processes=2 threads=15 display-name=%{GROUP} python-home=/home/imran/pyapps/venv
        WSGIProcessGroup propertyapp
        #WSGIApplicationGroup %{GLOBAL}

        WSGIScriptAlias / /var/www/propertyapp/property/wsgi.py
        #WSGIScriptAlias / /home/imran/pyapps/propertyapp/property/wsgi.py

        <Directory /var/www/propertyapp>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride all
            Require all granted
        </Directory>

        Alias /static/ /var/www/propertyapp/static/
        Alias /media/ /var/www/propertyapp/media/

        <Directory /var/www/propertyapp/static>
            Require all granted
        </Directory>

        <Directory /var/www/propertyapp/media>
            Require all granted
        </Directory>

        ErrorLog /var/log/apache2/propertyapp.somedomain.com-error.log
        LogLevel info
        CustomLog /var/log/apache2/propertyapp.somedomain.com-access.log combined
</VirtualHost>
```
