### ISSUE TITLE
TypeError: 'exceptions.OSError' object is not callable when using wsgi with Flask

### ISSUE THREAD

**Issue by tejeshbadri** [GrahamDumpleton/mod_wsgi#444]
Hi,
I have a apache webserver running + wsgi + Flask.
I have a website running https://<server>/. When i use the below command
curl -k -X POST https://<servername>/ -d "cmd=ls" , It gives me the list of files in the server.But when i try same command multiple times and it just crashes.

Can you please me to fix this. I am new to this.

**Error:**
curl -k -X POST https://<server>/ -d "cmd=ls"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Note:** First time it returns list of files with ls command but if i keep trying it crashes and if i restart apache, it succeeds again.

**Logs from apache:** [TypeError: 'exceptions.OSError' object is not callable]
===============
[Tue Jul 02 11:31:34.215570 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302] [2019-07-02 11:31:34,214] ERROR in app: Exception on / [POST]
[Tue Jul 02 11:31:34.215610 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302] Traceback (most recent call last):
[Tue Jul 02 11:31:34.215620 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
[Tue Jul 02 11:31:34.215623 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     response = self.full_dispatch_request()
[Tue Jul 02 11:31:34.215625 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1835, in full_dispatch_request
[Tue Jul 02 11:31:34.215628 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     return self.finalize_request(rv)
[Tue Jul 02 11:31:34.215631 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1850, in finalize_request
[Tue Jul 02 11:31:34.215641 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     response = self.make_response(rv)
[Tue Jul 02 11:31:34.215644 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2001, in make_response
[Tue Jul 02 11:31:34.215646 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     reraise(TypeError, new_error, sys.exc_info()[2])
[Tue Jul 02 11:31:34.215649 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1993, in make_response
[Tue Jul 02 11:31:34.215651 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     rv = self.response_class.force_type(rv, request.environ)
[Tue Jul 02 11:31:34.215654 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib/python2.7/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
[Tue Jul 02 11:31:34.215656 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     response = BaseResponse(*_run_wsgi_app(response, environ))
[Tue Jul 02 11:31:34.215659 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib/python2.7/site-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
[Tue Jul 02 11:31:34.215662 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     return _run_wsgi_app(*args)
[Tue Jul 02 11:31:34.215664 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]   File "/usr/lib/python2.7/site-packages/werkzeug/test.py", line 1119, in run_wsgi_app
[Tue Jul 02 11:31:34.215667 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302]     app_rv = app(environ, start_response)
[Tue Jul 02 11:31:34.215669 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302] TypeError: 'exceptions.OSError' object is not callable
[Tue Jul 02 11:31:34.215673 2019] [wsgi:error] [pid 11232] [client 172.30.88.135:57302] The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a OSError.

**Here is the configuration:**
=========================
cat /etc/httpd/conf.d/oncallproxy.conf
<VirtualHost *:80>
    ServerName <servername>
    #Log Setup
    CustomLog /var/log/httpd/access_oncall.log combined
    ErrorLog /var/log/httpd/error_oncall.log
    #CustomLog /opt/svcngitls/access_oncall.log combined
    #ErrorLog /opt/svcngitls/error_oncall.log

        LoadModule wsgi_module /usr/lib64/python2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so
        WSGIScriptAlias / /opt/svcngitls/Flask/Flask/oncallwsgi.wsgi

        <Location />
                Options -Indexes +FollowSymLinks
                require all granted
        </Location>

        <Directory /opt/svcngitls/Flask/>
                Options -Indexes +FollowSymLinks
                require all granted
        </Directory>

</VirtualHost>

And my Flask:
============
cat /opt/svcngitls/Flask/Flask/oncall.py

import os
from subprocess import Popen, PIPE, CalledProcessError
from flask import Flask, request

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def oncall():
    if request.method == 'POST':
        try:
            path = Popen("find /opt/svcngitls/oncall  -type d -printf \":%p\"", stdout=PIPE, shell=True)
            (output, err) = path.communicate()
            os.environ['PATH'] += ':' + output
            cmd = str(request.get_data()).split('=')[1]
            process = Popen(cmd, stdout=PIPE, stderr=PIPE, shell=True)
            stdout, stderr = process.communicate()
            newstring = "stdout : \n" + stdout + " \n" + "stderr: \n" + stderr;
            return newstring
        except Exception as e:
            return e
    elif request.method == 'GET':
        return "Test mehthod for POST \n"

cat /opt/svcngitls/Flask/Flask/oncallwsgi.wsgi
#!/usr/bin/python
import sys
sys.path.insert(0,"/opt/svcngitls/Flask/")
from Flask import app as application

cat /opt/svcngitls/Flask/Flask/__init__.py
from oncall import app

if __name__ == "__main__":
    app.run()

**Comment by GrahamDumpleton** [comment]
This is nothing to do with mod_wsgi and just how you have written your application. You cannot add `stdout` and `stderr` to strings like that. That is causing an exception which you catch and then you are returning the exception (`IOError`). So the result is sort of expected as you can't return an exception like that from Flask apps.

Suggest you do more reading on using Flask and for questions like this use StackOverflow instead.
