### ISSUE TITLE
Target WSGI script cannot be loaded as a python module and ImportError: No module named 'my_project'

### ISSUE THREAD

**Issue by valbro01** [GrahamDumpleton/mod_wsgi#445]
I'm try to deploy virtual host my django project into apache2 via mod_wsgi WSGIDaemon method, i'm using CentOs and i'm getting following error.

From apache2 error log:

`
[Wed Jul 03 03:00:56.840555 2019] [mpm_prefork:notice] [pid 7535] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16 mod_wsgi/4.5.18 Python/3.6 configured -- resuming normal operations
[Wed Jul 03 03:01:04.668982 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256] mod_wsgi (pid=7537): Target WSGI script '/var/www/ton/my_project/wsgi.py' cannot be loaded as Python module.
[Wed Jul 03 03:01:04.669148 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256] mod_wsgi (pid=7537): Exception occurred processing WSGI script '/var/www/ton/my_project/wsgi.py'.
[Wed Jul 03 03:01:04.670689 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256] Traceback (most recent call last):
[Wed Jul 03 03:01:04.670828 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "/var/www/ton/my_project/wsgi.py", line 16, in <module>
[Wed Jul 03 03:01:04.670842 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]     application = get_wsgi_application()
[Wed Jul 03 03:01:04.670880 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "/var/www/ton/ton-venv/lib64/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Jul 03 03:01:04.670890 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]     django.setup(set_prefix=False)
[Wed Jul 03 03:01:04.670908 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "/var/www/ton/ton-venv/lib64/python3.6/site-packages/django/__init__.py", line 19, in setup
[Wed Jul 03 03:01:04.670918 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Wed Jul 03 03:01:04.670936 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "/var/www/ton/ton-venv/lib64/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Wed Jul 03 03:01:04.670948 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]     self._setup(name)
[Wed Jul 03 03:01:04.670966 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "/var/www/ton/ton-venv/lib64/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
[Wed Jul 03 03:01:04.670975 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]     self._wrapped = Settings(settings_module)
[Wed Jul 03 03:01:04.670992 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "/var/www/ton/ton-venv/lib64/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
[Wed Jul 03 03:01:04.671001 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Wed Jul 03 03:01:04.671034 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[Wed Jul 03 03:01:04.671046 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]     return _bootstrap._gcd_import(name[level:], package, level)
[Wed Jul 03 03:01:04.671090 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Wed Jul 03 03:01:04.671113 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Wed Jul 03 03:01:04.671131 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
[Wed Jul 03 03:01:04.671150 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Wed Jul 03 03:01:04.671168 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Wed Jul 03 03:01:04.671186 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Wed Jul 03 03:01:04.671203 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Wed Jul 03 03:01:04.671244 2019] [wsgi:error] [pid 7537] [remote 88.99.13.202:57256] ModuleNotFoundError: No module named 'my_project'
`

In my host file site.conf:

`
WSGIPythonHome /var/www/venv
WSGIPythonPath /var/www/my_project
<VirtualHost *:80>

ServerName site.com
ServerAlias www.site.com

#WSGIDaemonProcess my_project python-home=/var/www/venv python-path=/var/www/my_project
#WSGIDaemonProcess my_project python-path=/var/www/my_project:/var/www/venv
WSGIDaemonProcess my_project python-path=/var/www/my_project:/var/www/venv
WSGIProcessGroup my_project
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / /var/www/my_project/wsgi.py
Alias /static /var/www/static

<Directory /var/www/static>
    Require all granted
</Directory>

<Directory /var/www/my_project/>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>

Include /etc/letsencrypt/options-ssl-apache.conf
ServerName site.com
SSLCertificateFile /etc/letsencrypt/live/site.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/site.com/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/site.com/chain.pem
</VirtualHost>
`

All permissions for folder /var/www/my_project is given

**Comment by GrahamDumpleton** [comment]
Try setting ``python-path`` to the parent directory of your project, not the actual directory.

```
python-path=/var/www/ton
```

Same for ``WSGIPythonPath`` if don't use daemon mode.
