### ISSUE TITLE
Converting from mod_python to mod_wsgi

### ISSUE THREAD

**Issue by mmokrejs** [GrahamDumpleton/mod_wsgi#446]
Hi Graham,
  I have been using `mod_python` (`3.5.0` for the last time) for about 15 years and now I wanted to switch to `mod_wsgi` as I am forced by the Linux distro to switch to `apache-2.4` (which is not supported by `mod_python`). But, I am unable to get `Apache`+`mod_wsgi` running my old python code. Why is that so difficult to switch?

  My old code was only readable by apache process before, do I really need `chmod a+rx *.py` to get that executed by `mod_wsgi`? If memory serves me right `mod_python` even picked `*.pyc` files if they were not older than corresponding `*.py` files. How does that translate to `mod_wsgi`?

  My old code in say `index.py` contained `def index(req)` which was the primary entry point, actually it started with `from mod_python import apache` too. Do I really need to rename that to `def application(environ, start_response)`? How do I convert the old `req` objects into those `environ` and `start_response` currently used in mod_wsgi?

  For a short while my app was executed under `mod_wsgi` but it seemed only in the `embedded mode`, whatever that is. I would not mind but a problem anyway was that the main `index.py` could not import `foo.py` during execution from within the same (`"./"`) directory so it did not execute in the end due to `ImportError`. After switching to `daemon mode` the code does not execute at all (I get timeout, no data received from webserver). I am getting lost in figuring out the differences between `python-home` and `python-path` arguments to `WSGIDaemonProcess` option.

  I think I will revert back to apache-2.2 and mod_python, hope I can still compile it back. How much time shall I need to rewrite the old app? I could not find any transitioning guide. Thank you.

  Here is my old setup:
```
        RewriteOptions inherit
        RewriteRule   ^/~(.+)  http://my.domain/~$1  [R,L]
        <Directory /home/xxx/public_html/MYAPP>
                AddHandler mod_python .py
                DirectoryIndex index.py
                # don't allow people to retrieve non-cgi executable files or our private data
                <FilesMatch ^(.*\.pl|.*\.py|.*\.pyc|.*\.sql)$>
                        deny from all
                </FilesMatch>
                <FilesMatch ^(.*\.js|.*\.css)$>
                        allow from all
                </FilesMatch>
                AddOutputFilterByType DEFLATE text/html text/plain text/xml
                allow from all
                AllowOverride All
        </Directory>
```

Currently my not-working setup is:
```
        WSGIDaemonProcess my.domain processes=2 threads=15 display-name=%{GROUP} python-home=/home/xxx/wsgi/MYAPP python-path=/home/xxx/wsgi/MYAPP
        WSGIProcessGroup my.domain
        WSGIApplicationGroup %{GLOBAL}
        WSGIScriptAlias / /home/xxx/wsgi/MYAPP/index.py

        <Directory /home/xxx/wsgi/MYAPP>
            Options +ExecCGI +MultiViews
            MultiviewsMatch Handlers

            AddHandler cgi-script .cgi
            AddHandler wsgi-script .wsgi
            AddHandler wsgi-script .py
        </Directory>
```

Thank you for your comments.

**Comment by GrahamDumpleton** [comment]
You can't just drop a mod_python application into mod_wsgi and have it work. They are very different.

You will need to rewrite your web application as a Python WSGI application. I would strongly recommend you look at using Flask web framework as the base for doing that. See https://palletsprojects.com/p/flask/

**Comment by mmokrejs** [comment]
Thank you, Graham, for your quick answer. I took the simpler approach and installed apache-2.2.x series with mod_python-3.5.0, I do not have to study the differences. It was enough to undo the many changes to apache config files, reinstall older dependencies, etc.
