### ISSUE TITLE
You need to have installed the VC9 compiler. It is ancient and why suggest use Python 3.6. You can find details about compilers you must use with different Python versions at:

### ISSUE THREAD

**Issue by nxtexe** [GrahamDumpleton/mod_wsgi#447]
"You need to have installed the VC9 compiler. It is ancient and why suggest use Python 3.6. You can find details about compilers you must use with different Python versions at:

* https://wiki.python.org/moin/WindowsCompilers

_Originally posted by @GrahamDumpleton in https://github.com/GrahamDumpleton/mod_wsgi/issues/268#issuecomment-370040133_"

How do I specify which compiler should be used? For some reason visual studio installed different bit versions of the compiler/linker in mvs and mvs 14.0. The pip command seems to be using the 32-bit compiler/linker even though there is a 64-bit one installed, and python 3.7 version is 64-bit and so is mod_wsgi files.

**Comment by GrahamDumpleton** [comment]
How to ensure a specific Windows C compiler version/architecture is used by Python pip is a question better asked on StackOverflow. I have no idea if it doesn't work out of the box.

**Comment by nxtexe** [comment]
> How to ensure a specific Windows C compiler version/architecture is used by Python pip is a question better asked on StackOverflow. I have no idea if it doesn't work out of the box.

Thank you for the quick reply, I will research this on my own.
