### ISSUE TITLE
error after mod_wsgi-express module-config

### ISSUE THREAD

**Issue by Tirumalesh8686** [GrahamDumpleton/mod_wsgi#448]
I have a very similar doubt.....

(base) D:\Tirumalesh\dev\myapp\Flask\Scripts>mod_wsgi-express module-config
Traceback (most recent call last):
File "c:\users\lucid\anaconda3\Lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\users\lucid\anaconda3\Lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "D:\Tirumalesh\dev\myapp\Flask\Scripts\mod_wsgi-express.exe_main.py",
line 5, in 
File "d:\tirumalesh\dev\myapp\flask\lib\site-packages\mod_wsgi\server_init
.py", line 25, in 
from . import apxs_config
File "d:\tirumalesh\dev\myapp\flask\lib\site-packages\mod_wsgi\server\apxs_con
fig.py", line 27
LIBEXECDIR = 'C:\Users\lucid\Apache24/lib'
^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in positio
n 2-3: truncated \UXXXXXXXX escape

On line 27 of the .py file, i have something as this:
LIBEXECDIR = 'C:\Users\lucid\Apache24/lib'

For a similar doubt in the previous discussion u asked to copy the .py file of line27 by saying
"""Attach a copy of e:\pythonpro\lib\site-packages\mod_wsgi\server\apxs_config.py. Don't cut and paste content, actually attach it as need to see the raw original."""""

What is the exact error here....where exactly this .py file needs to be copied and in what way is it helping to resolve the issue....
Should i need to change any path on line 27 of my apxs_config.py????

**Comment by GrahamDumpleton** [comment]
Think this was dealt with in separate issue. Even though is Windows, shouldn't have used backslashes in path names when overriding Apache location through environment variables as that causes issues when parsing path in Python code. Closing issue.
