### ISSUE TITLE
invoking get_wsgi_application results in ModuleNotFoundError 

### ISSUE THREAD

**Issue by chocobloc** [GrahamDumpleton/mod_wsgi#450]
Dear Graham,

please have a look and let me know how I can solve this problem.
I'm using python3.6 + modwsgi 4.6.5 on Centos7
I'm using httpd 2.4 as web-server

Here's what I did:
- Created directory /var/www/mysite
- created virtualenv my_env
- source my_env/bin/activate
- installed django (2.2.3), psycopg2 (2.8.3), django-booststrap3
- django-admin.py startproject vocs_proj
- did some changes to vocs_proj/settings.py so I can use my postgres database
- ./manage.py runserver 0.0.0.0:8000 -> That worked.

I've added a /etc/httpd/conf.d/vocs_proj.conf with the following contents:

WSGIScriptAlias / /var/www/mysite/vocs_proj/wsgi.py
WSGIDaemonProcess vocs_proc python-home=/var/www/mysite/my_env python-path=/var/www/mysite/my_env/lib/python3.6/site-packages:/var/www/mysite/vocs_proj/
WSGIProcessGroup vocs_proc

ErrorLog /var/log/httpd/vocs_proj_error.log

Alias /static /var/www/mysite/static/
<Directory "/var/www/mysite/static/">Require all granted</Directory>
<Directory "/var/www/mysite/vocs_proj">
      <Files "wsgi.py">
           Require all granted
       <//Files>
<//Directory>

(apologies if I don't use "//" the ending tags will be invisible)

I've added the command
print(os.listdir('/var/www/mysite/vocs_proj'))
to check if apache can access the wsgi file. That seems to work.

I restarted httpd and tried to access localhost/ via firefox.

I've found the following log in /var/log/httpd/vocs_error.log:

[Fri Jul 19 13:28:16.382292 2019] [wsgi:error] [pid 11804] ['__init__.py', 'settings.py', 'urls.py', '__pycache__', 'wsgi.py']
[Fri Jul 19 13:28:16.674675 2019] [wsgi:error] [pid 11804] [remote ::1:46142] mod_wsgi (pid=11804): Failed to exec Python script file '/var/www/mysite/vocs_proj/wsgi.py'.
[Fri Jul 19 13:28:16.674741 2019] [wsgi:error] [pid 11804] [remote ::1:46142] mod_wsgi (pid=11804): Exception occurred processing WSGI script '/var/www/mysite/vocs_proj/wsgi.py'.
[Fri Jul 19 13:28:16.675493 2019] [wsgi:error] [pid 11804] [remote ::1:46142] Traceback (most recent call last):
[Fri Jul 19 13:28:16.675564 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "/var/www/mysite/vocs_proj/wsgi.py", line 17, in <module>
[Fri Jul 19 13:28:16.675570 2019] [wsgi:error] [pid 11804] [remote ::1:46142]     application = get_wsgi_application()
[Fri Jul 19 13:28:16.675578 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "/var/www/mysite/my_env/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Jul 19 13:28:16.675582 2019] [wsgi:error] [pid 11804] [remote ::1:46142]     django.setup(set_prefix=False)
[Fri Jul 19 13:28:16.675589 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "/var/www/mysite/my_env/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
[Fri Jul 19 13:28:16.675593 2019] [wsgi:error] [pid 11804] [remote ::1:46142]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Jul 19 13:28:16.675600 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "/var/www/mysite/my_env/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
[Fri Jul 19 13:28:16.675604 2019] [wsgi:error] [pid 11804] [remote ::1:46142]     self._setup(name)
[Fri Jul 19 13:28:16.675611 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "/var/www/mysite/my_env/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
[Fri Jul 19 13:28:16.675614 2019] [wsgi:error] [pid 11804] [remote ::1:46142]     self._wrapped = Settings(settings_module)
[Fri Jul 19 13:28:16.675621 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "/var/www/mysite/my_env/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
[Fri Jul 19 13:28:16.675625 2019] [wsgi:error] [pid 11804] [remote ::1:46142]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Jul 19 13:28:16.675632 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "/var/www/mysite/my_env/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[Fri Jul 19 13:28:16.675635 2019] [wsgi:error] [pid 11804] [remote ::1:46142]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Jul 19 13:28:16.675642 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Fri Jul 19 13:28:16.675650 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Fri Jul 19 13:28:16.675658 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
[Fri Jul 19 13:28:16.675674 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Fri Jul 19 13:28:16.675682 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Fri Jul 19 13:28:16.675689 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Fri Jul 19 13:28:16.675697 2019] [wsgi:error] [pid 11804] [remote ::1:46142]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Fri Jul 19 13:28:16.675715 2019] [wsgi:error] [pid 11804] [remote ::1:46142] ModuleNotFoundError: No module named 'vocs_proj'

What did I miss? Thanks in advance!

**Comment by GrahamDumpleton** [comment]
You shouldn't be setting `python-path` to the `site-packages`. The `python-home` is what specifies the location of the virtual environment.

You also likely have wrong project directory for other path to `python-path`. Try:

```
WSGIDaemonProcess vocs_proc python-home=/var/www/mysite/my_env python-path=/var/www/mysite
```

You should be pointing at the parent directory of your project, not the project directory.

**Comment by chocobloc** [comment]
Thanks so much! It can be that simple, python-home=/path/to/venv python-path=/path/to/mysite.com
("...could someone please translate venv for me, and where the heck do I find that mysite.com???")
Sorry, I just got confused after a full day of reading (outdated tutorials, stack-overflow issues,...) and trying, trying, trying. thanks again!

**Comment by GrahamDumpleton** [comment]
Virtual environment docs:

*https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

The Django docs should adequately cover how to set path to project.

* https://docs.djangoproject.com/en/2.2/howto/deployment/wsgi/modwsgi/
