### ISSUE TITLE
SegmentFault in django multiprocess.Pool 

### ISSUE THREAD

**Issue by desnar** [GrahamDumpleton/mod_wsgi#452]
Hi,  
   I'm running django server in apache. The version info is
`Apache/2.4.29 (Unix) mod_wsgi/4.5.24 Python/3.7(virtualenv)`

The server work fine before, and show this error after a restart.
` [wsgi:error] [pid 77551] Truncated or oversized response headers received from daemon process 'mainsite' : /home/serv/www/mainsite/wsgi.py `
` [core:notice] [pid 64332] AH00051: child pid 109475 exit signal Segmentation fault (11),`

I check the django code, and find the segmentfault is only occurs when I call multiprocess.Pool. More exactly, it only happens when call pool.join().  
This seems to be not related with what is added in pool, because the segment fault will still happen when I open a pool and call close and join it after that directly. 

I read the related issue #351, and use the gdb debug, the info is as follow:
```
[New Thread 0x7f26e520b700 (LWP 111039)]
[New Thread 0x7f26e480a700 (LWP 111040)]
[New Thread 0x7f26e1e09700 (LWP 111041)]
[Thread 0x7f26e520b700 (LWP 111039) exited]
[Thread 0x7f26e480a700 (LWP 111040) exited]
[Thread 0x7f26e1e09700 (LWP 111041) exited]
Detaching after fork from child process 111246.
Detaching after fork from child process 111247.
[New Thread 0x7f26e1e09700 (LWP 111248)]
[New Thread 0x7f26e480a700 (LWP 111249)]
[New Thread 0x7f26e520b700 (LWP 111250)]
[Thread 0x7f26e480a700 (LWP 111249) exited]
[Thread 0x7f26e520b700 (LWP 111250) exited]
[Thread 0x7f26e1e09700 (LWP 111248) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f26f65f9700 (LWP 109483)]
0x00007f26ec78685b in simplequeue_dealloc (self=0x7f26d9ae2470)
    at /home/serv/python37/Python-3.7.0/Modules/_queuemodule.c:29
29          _PyObject_GC_UNTRACK(self);
```

the apache config is 
```
WSGIDaemonProcess mainsite python-home=/home/serv/pythonenv
WSGIProcessGroup mainsite
WSGIScriptAlias / /home/serv/www/mainsite/wsgi.py
WSGIApplicationGroup %{GLOBAL}
```

**Comment by GrahamDumpleton** [comment]
What do you get for ``pip freeze``?

**Comment by desnar** [comment]
> What do you get for `pip freeze`?

This is the pip freeze list
```
biopython==1.73
bokeh==0.12.13
certifi==2018.11.29
chardet==3.0.4
configparser==3.7.3
Cython==0.29.5
decorator==4.3.2
Django==2.0
idna==2.8
ipython-genutils==0.2.0
Jinja2==2.10
jsonschema==2.6.0
jupyter-core==4.4.0
MarkupSafe==1.1.0
nbformat==4.4.0
numpy==1.16.1
pandas==0.24.1
plotly==3.1.0
pysam==0.15.2
python-dateutil==2.8.0
pytz==2018.9
PyYAML==3.13
requests==2.21.0
retrying==1.3.3
six==1.12.0
tornado==5.1.1
traitlets==4.3.2
urllib3==1.24.1
xlrd==1.2.0
```

**Comment by GrahamDumpleton** [comment]
Tracking down garbage collection issues like that is very hard. The cause is going to be a third party Python package which uses a C extension component. Unfortunately the one such package I know of which did have an obscure garbage collection issue that could cause a break like this, you aren't using.

In case the Python installation you use got updated, I would suggest recreating your virtual environment so everything is built with the updated version. Ensure you are using the latest mod_wsgi version, and also see if you can update to later versions of other packages, especially those with C extensions.

**Comment by desnar** [comment]
> Tracking down garbage collection issues like that is very hard. The cause is going to be a third party Python package which uses a C extension component. Unfortunately the one such package I know of which did have an obscure garbage collection issue that could cause a break like this, you aren't using.
> 
> In case the Python installation you use got updated, I would suggest recreating your virtual environment so everything is built with the updated version. Ensure you are using the latest mod_wsgi version, and also see if you can update to later versions of other packages, especially those with C extensions.

I have tried recreate the virtual environment, install the newest mod_wsgi and reinstall the python. They all dont work. It seems the segmentfault is caused by a complex problem. I prepare to move the website to a new server.

Thanks for your suggestions.
