### ISSUE TITLE
Not Compatible with latest version of apache(2.4.39)

### ISSUE THREAD

**Issue by arunk-iq** [GrahamDumpleton/mod_wsgi#453]
Modwsgi cannot be installed with latest version of apache(2.4.39). Some header files(apr_perms_set.h) which are removed from apache are being searched during installation.
I have used Apache binaries(x86) downloaded from [apache haus](https://www.apachehaus.com/cgi-bin/download.plx#APACHE24VC15) on Windows server OS and python 3.5
Modwsgi installation tried using pip command

**Comment by GrahamDumpleton** [comment]
Can you include the error messages from the compiler. There is no header file by that named used by mod_wsgi source code. This suggest the issue may be with the Apache distro you are using. The only distro recommended is that from Apache Lounge. Some others are missing header files necessary to compiled additional Apache modules.

**Comment by arunk-iq** [comment]
Thank You.
Choosing Apache Lounge solved this problem
