### ISSUE TITLE
Flask App Deployment in Windows (Apache-Server, mod_wsgi)

### ISSUE THREAD

**Issue by Tirumalesh8686** [GrahamDumpleton/mod_wsgi#454]
Hello.....
Iam following this link "https://medium.com/@madumalt/flask-app-deployment-in-windows-apache-server-mod-wsgi-82e1cfeeb2ed" to deploy flask app in windows........

1)**Usually this was in my http-vhosts.conf file:**

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "${SRVROOT}/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ServerAlias www.dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error.log"
    CustomLog "logs/dummy-host2.example.com-access.log" common
</VirtualHost>

and now below that I added server name, WSGIScriptAlias, directory to it so that it look like this:

<VirtualHost *:80>
    ServerName localhost
    WSGIScriptAlias / "D:/Tirumalesh/dev/text_basic/web.wsgi"    
    DocumentRoot "D:/Tirumalesh/dev/text_basic"   
	<Directory D:/Tirumalesh/dev/text_basic>                        
        Require all granted
    </Directory>
</VirtualHost>

2) **and I have added this below 3 lines in my httpd.conf(in the very end of file) which is the output coming from "mod_wsgi-express module-config" and I have included "Include conf/extra/httpd-vhosts.conf" (virtual hosts) in my httpd.conf file**

LoadFile "c:/users/lucid/anaconda3/python37.dll"
LoadModule wsgi_module "c:/users/lucid/anaconda3/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "c:/users/lucid/anaconda3"

3)**Next i create a web.wsgi file with the following content** 

import sys
sys.path.insert(0, 'D:\Tirumalesh\dev\text_basic')
from text_basic import app as application

4)And my python file is "text_basic.py" (whose name must be same as my .wsgi file) 

from flask import Flask
app = Flask(__name__)
@app.route('/')
def hello():
    return ("Hello World qwertyuiop!!")
if __name__ == "__main__":
    app.run()

After that i restarted my apache server and tried running "localhost" but im not getting "Hello World qwertyuiop!!" this output in my html page instead im getting "The requested URL / was not found on this server."
Is there anything i missed in this??

**NOTE**: https://github.com/GrahamDumpleton/mod_wsgi/releases/download/4.4.12/mod_wsgi-windows-4.4.12.tar.gz
Instead of downloading this "mod_wsgi-windows-4.4.12.tar.gz" this file and looking for the right mod_wsgi.so file and copy it to my  "C:\Users\lucid\VS16\Apache24\modules" and pasting **.so** file,
 I downloaded mod_wsgi using "pip install mod_wsgi"and after i ran "mod_wsgi-express module-config" and copied the below output to httpd.conf at last line of the file.......

LoadFile "c:/users/lucid/anaconda3/python37.dll"
LoadModule wsgi_module "c:/users/lucid/anaconda3/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "c:/users/lucid/anaconda3"

What is "LoadModule wsgi_module modules/mod_wsgi.so" and do we need to this in my httpd.conf file??

**Comment by GrahamDumpleton** [comment]
The output of `mod_wsgi-express module-config` cannot be placed at the end of the file. It must be before anywhere that uses the mod_wsgi directives. Put those lines in main Apache configuration file, just after any existing `LoadModule` directives. Remove any existing `LoadModule` line for mod_wsgi.

**Comment by Tirumalesh8686** [comment]
**I have placed below lines(output of "mod_wsgi-express module-config") just after existing LoadModule directives in my http.conf file**
LoadFile "c:/users/lucid/anaconda3/python37.dll"
LoadModule wsgi_module "c:/users/lucid/anaconda3/lib/sitepackages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "c:/users/lucid/anaconda3"

Below are the Directory, ServerName(domain of flask app),WSGIScriptAlias(which specifies what script should be executed when the Apache Server get a request for <domain-name>).
These are included in my **httpd-vhosts.conf** and to I **uncommented** 
( **Include conf/extra/httpd-vhosts.conf**) this virtual host in my **httpd.conf** file

<VirtualHost *:80>
    ServerName localhost:80
    WSGIScriptAlias / "D:/Tirumalesh/dev/text_basic/web.wsgi"  
	DocumentRoot "D:/Tirumalesh/dev/text_basic"
	<Directory "D:/Tirumalesh/dev/text_basic"> 	
        Require all granted	
    </Directory>
</VirtualHost>

Do i need to keep these above lines in http.conf itself or what i have done is true?
If we need to keep this in httpd.conf how can we add a virtualhost there in httpd.conf file?
We need to add only ServerName, WSGIScriptAlias, Directory or we need to add all those above lines in httpd.conf file?

**After when i run my apache server Iam getting the following error:**

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

It would be very helpful...thanks.....

**Comment by GrahamDumpleton** [comment]
Did you do what the error message told you and look at what error message was in the Apache server error log?

At a guess, the problem is that you aren't setting `WSGIPythonPath` to tell mod_wsgi where your project code is, so imports are failing. The message in the error log will show what is occurring.

**Comment by Tirumalesh8686** [comment]
These are the errors that are occuring in my error log:

[wsgi:error] [pid 6636:tid 1000] [client ::1:49402] mod_wsgi (pid=6636): Failed to exec Python script file 'D:/Tirumalesh/dev/text_basic/web.wsgi'.

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402] mod_wsgi (pid=6636): Exception occurred processing WSGI script 'D:/Tirumalesh/dev/text_basic/web.wsgi'.

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402] Traceback (most recent call last):\r

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]   File "D:/Tirumalesh/dev/text_basic/web.wsgi", line 3, in <module>\r

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]     from app import app as application\r

[wsgi:error] [pid 6636:tid 1000] [client ::1:49402]   File "D:/Tirumalesh/dev/text_basic\\app.py", line 1, in <module>\r

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]     from flask import Flask #, render_template\r
 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]   File "c:\\users\\lucid\\anaconda3\\lib\\site-packages\\flask\\__init__.py", line 21, in <module>\r

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]     from .app import Flask, Request, Response\r

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]   File "c:\\users\\lucid\\anaconda3\\lib\\site-packages\\flask\\app.py", line 25, in <module>\r

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]     from . import cli, json\r

[wsgi:error] [pid 6636:tid 1000] [client ::1:49402]   File "c:\\users\\lucid\\anaconda3\\lib\\site-packages\\flask\\cli.py", line 18, in <module>\r

[wsgi:error] [pid 6636:tid 1000] [client ::1:49402]     import ssl\r

 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]   File "c:\\users\\lucid\\anaconda3\\lib\\ssl.py", line 98, in <module>\r
 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402]     import _ssl             # if we can't import it, let the error propagate\r
 [wsgi:error] [pid 6636:tid 1000] [client ::1:49402] ImportError: DLL load failed: The specified module could not be found.\r
[wsgi:error] [pid 6636:tid 996] [client ::1:49403] mod_wsgi (pid=6636): Failed to exec Python script file 'D:/Tirumalesh/dev/text_basic/web.wsgi'., referer: http://localhost/
[wsgi:error] [pid 6636:tid 996] [client ::1:49403] mod_wsgi (pid=6636): Exception occurred processing WSGI script 'D:/Tirumalesh/dev/text_basic/web.wsgi'., referer: http://localhost/
[wsgi:error] [pid 6636:tid 996] [client ::1:49403] Traceback (most recent call last):\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]   File "D:/Tirumalesh/dev/text_basic/web.wsgi", line 3, in <module>\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]     from app import app as application\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]   File "D:/Tirumalesh/dev/text_basic\\app.py", line 1, in <module>\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]     from flask import Flask #, render_template\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]   File "c:\\users\\lucid\\anaconda3\\lib\\site-packages\\flask\\__init__.py", line 21, in <module>\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]     from .app import Flask, Request, Response\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]   File "c:\\users\\lucid\\anaconda3\\lib\\site-packages\\flask\\app.py", line 25, in <module>\r, referer: http://localhost/
[wsgi:error] [pid 6636:tid 996] [client ::1:49403]     from . import cli, json\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]   File "c:\\users\\lucid\\anaconda3\\lib\\site-packages\\flask\\cli.py", line 18, in <module>\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]     import ssl\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]   File "c:\\users\\lucid\\anaconda3\\lib\\ssl.py", line 98, in <module>\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403]     import _ssl             # if we can't import it, let the error propagate\r, referer: http://localhost/
 [wsgi:error] [pid 6636:tid 996] [client ::1:49403] ImportError: DLL load failed: The specified module could not be found.\r, referer: http://localhost/

**Comment by GrahamDumpleton** [comment]
You can't use Anaconda Python if you intend using `mod_ssl` in Apache.

Unless you have a specific need for Anaconda Python, use the normal Python distribution from the Python Software Foundation. Anaconda Python breaks the ability to do embedded in things like Apache.

**Comment by mallikarjunm034** [comment]
then is that possible to run apache without using mod_ssl?

**Comment by GrahamDumpleton** [comment]
If you are not using HTTPS support in Apache, then don't load `mod_ssl` in the Apache config.

Now according to https://github.com/GrahamDumpleton/mod_wsgi/issues/480#issuecomment-547941233 it seems (for Linux at least, not sure about Windows), you can tell Anaconda to use a specific OpenSSL version. If you can work out what version Apache is built for, you may be able to tell Anaconda to use the same.

**Comment by TheEverlastingBish** [comment]
You need to use double backslashes in your `web.wsgi` file:
```
import sys
sys.path.insert(0, 'D:\\Tirumalesh\\dev\\text_basic')
from text_basic import app as application
```

It's basically a python file so the escaping needs to be done as you would in any python Windows path.

**Comment by HamzaEkram** [comment]
> Did you do what the error message told you and look at what error message was in the Apache server error log?
> 
> At a guess, the problem is that you aren't setting `WSGIPythonPath` to tell mod_wsgi where your project code is, so imports are failing. The message in the error log will show what is occurring.

hello sir!
i think that my imports are not well, how i set WSGIPythonPath can you please make me understand.

**Comment by GrahamDumpleton** [comment]
@HamzaEkram Do not ask for help in comments of old issues. If you are having a specific problem, create a new issue and fully explain in that what your problem is, what error you get, configuration and application used etc etc. If you don't have a specific problem and just after general help, use StackOverflow or the mod_wsgi mailing list. See:

* https://modwsgi.readthedocs.io/en/master/finding-help.html

Do note that for Windows you may need to specifically use ``develop`` version from GitHub as can't remember if there is an outstanding issue on Windows related to Python virtual environments which is only fixed in it. So use:

```
pip install -U --no-cache-dir https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

So create the new issue if still have a problem.

**Comment by HamzaEkram** [comment]
Ok sir I will make new issue.
