### ISSUE TITLE
apache2+mod_wsgi (python3) stop answer at random time

### ISSUE THREAD

**Issue by stalker37** [GrahamDumpleton/mod_wsgi#458]
Hi!
I'm using:

apache 2.4.38-3
libapache2-mpm-itk 2.4.7-04-1
libapache2-mod-wsgi-py3 4.6.5-1

wsgi optinons for vhosts:

WSGIDaemonProcess wsgi.test user=test group=test threads=2
WSGIProcessGroup wsgi.test

[strace.7226.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/3524850/strace.7226.txt)
[strace.7227.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/3524851/strace.7227.txt)
[strace.7228.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/3524852/strace.7228.txt)

inside KVM box. Some random time (several times a month) apache stops 
responding to requests. Help only full restart apache2 service.
At this time (before restart) apache wrote to error log more messages like:

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

Fatal Python error: Could not allocate TSS entry

[Sat Aug 03 00:00:05.444213 2019] [core:notice] [pid 30599] AH00052: 
child pid 7428 exit signal Aborted (6)
[Sat Aug 03 00:00:05.444292 2019] [core:notice] [pid 30599] AH00052: 
child pid 7429 exit signal Aborted (6)
[Sat Aug 03 00:00:05.444333 2019] [core:notice] [pid 30599] AH00052: 
child pid 7430 exit signal Aborted (6)
[Sat Aug 03 00:00:05.444354 2019] [core:notice] [pid 30599] AH00052: 
child pid 7431 exit signal Aborted (6)
[Sat Aug 03 00:00:05.444374 2019] [core:notice] [pid 30599] AH00052: 
child pid 7432 exit signal Aborted (6)
[Sat Aug 03 00:00:05.444395 2019] [core:notice] [pid 30599] AH00052: 
child pid 7433 exit signal Aborted (6

Server is testing with minimum load.

I also attach strace output of some apache processes at this time

**Comment by GrahamDumpleton** [comment]
What operating system? Are you using system packages supplied for a Linux distro for Apache, mod_wsgi and Python, or have you installed your own of any of them?

I can only speculate that is memory corruption issue, or running out of memory. Really impossible to say. The ITK MPM is also not one of the core Apache MPM modules, which also may complicate things.

**Comment by stalker37** [comment]
OS: debian buster amd64
installed from distro repo

monitoring not show full  memory utilisation (32 GB)

memtest/stress not show errros. mcelog too

**Comment by GrahamDumpleton** [comment]
Closing since no resolution and reason not easily determined.
