### ISSUE TITLE
Cannot install via mod_pip, unresolved external symbols

### ISSUE THREAD

**Issue by jisnowiv** [GrahamDumpleton/mod_wsgi#459]
Hey, trying to install mod_wsgi on a Windows Server 2008 R2 Enterprise, I have Visual C++ 14.0, Python 3.7.3, pip 19.2.2. When I run "pip install mod_wsgi" in VS2015 x64 Native Tools CMD prompt, I get a lot of errors but most of them are unresolved external symbols, so I think that I'm probably missing something very obvious but I can't figure it out.

I can send you the full output but let me know if this gives you any immediate answers.

Thanks!

    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_thread_mutex_create
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_ipsubnet_test
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_pool_cleanup_register
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_md5
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_time_now
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_itoa
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_get_server_banner
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_hash_set
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_hook_translate_name
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_hash_make

    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_add_common_vars
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_str_tolower
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_set_content_length
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_scoreboard_image
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_mpm_query
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_apr_palloc
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_satisfies
    mod_wsgi.obj : error LNK2001: unresolved external symbol __imp_ap_getword_conf

**Comment by GrahamDumpleton** [comment]
What Apache distribution are you using? If you can, use the ApacheLounge distribution, as many some other distributions are missing the bits needed to allow third party Apache modules to be built.

**Comment by jisnowiv** [comment]
I’ll be able to check a little later, but it’s important that I don’t change the distribution.

Would you be able to help me identify the missing bits?

**Comment by GrahamDumpleton** [comment]
Can't really help with that, it is a problem the distribution of Apache has to resolve. History shows though that some distributions don't want you compiling your own Apache modules.
