### ISSUE TITLE
(centos 7 + apache2 + django + mod_wsgi) fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by AntonioAntovski** [GrahamDumpleton/mod_wsgi#463]
I'm using the following configuration in order to run my Django app on apache server:

- CentOS 7
- Apache 2.4.25
- Django 2.1.12
- Python 3.7

When I tried to install mod_wsgi module for python3.7 (using `pip install mod_wsgi`), I got the following error:

 ERROR: Command errored out with exit status 1:
     command: /var/www/html/search/elasticsearch_API/elasticsearchenv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] =                                                                                                   '"'"'/tmp/pip-install-8m2q5_oh/mod-wsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8m2q5_oh/mod-wsgi/setup.py'"'"';f=getattr(tokenize, '                                                                                                  "'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'                                                                                                   install --record /tmp/pip-record-8zwxjqf_/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/html                                                                                                  /search/elasticsearch_API/elasticsearchenv/include/site/python3.7/mod-wsgi
         cwd: /tmp/pip-install-8m2q5_oh/mod-wsgi/
    Complete output (35 lines):
    /usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/mod_wsgi
    copying src/__init__.py -> build/lib.linux-x86_64-3.7/mod_wsgi
    creating build/lib.linux-x86_64-3.7/mod_wsgi/server
    copying src/server/__init__.py -> build/lib.linux-x86_64-3.7/mod_wsgi/server
    copying src/server/environ.py -> build/lib.linux-x86_64-3.7/mod_wsgi/server
    copying src/server/apxs_config.py -> build/lib.linux-x86_64-3.7/mod_wsgi/server
    creating build/lib.linux-x86_64-3.7/mod_wsgi/server/management
    copying src/server/management/__init__.py -> build/lib.linux-x86_64-3.7/mod_wsgi/server/management
    creating build/lib.linux-x86_64-3.7/mod_wsgi/server/management/commands
    copying src/server/management/commands/__init__.py -> build/lib.linux-x86_64-3.7/mod_wsgi/server/management/commands
    copying src/server/management/commands/runmodwsgi.py -> build/lib.linux-x86_64-3.7/mod_wsgi/server/management/commands
    creating build/lib.linux-x86_64-3.7/mod_wsgi/docs
    copying docs/_build/html/__init__.py -> build/lib.linux-x86_64-3.7/mod_wsgi/docs
    creating build/lib.linux-x86_64-3.7/mod_wsgi/images
    copying images/__init__.py -> build/lib.linux-x86_64-3.7/mod_wsgi/images
    copying images/snake-whiskey.jpg -> build/lib.linux-x86_64-3.7/mod_wsgi/images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi-py37' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    creating build/temp.linux-x86_64-3.7/src/server
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/httpd -I/usr/local/include/python3.7m                                                                                                   -c src/server/mod_wsgi.c -o build/temp.linux-x86_64-3.7/src/server/mod_wsgi.o -I/usr/include/httpd -I. -I/usr/include/apr-1 -DLINUX -D_REE                                                                                                  NTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gc                                                                                                  c-switches -m64 -mtune=generic -pthread -I/usr/include/apr-1 -I/usr/include/apr-1
    In file included from src/server/mod_wsgi.c:22:0:
    src/server/wsgi_python.h:24:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /var/www/html/search/elasticsearch_API/elasticsearchenv/bin/python3.7 -u -c 'import sys, set                                                                                                  uptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8m2q5_oh/mod-wsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8m2q5_oh/mod-wsgi/se                                                                                                  tup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(                                                                                                  code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8zwxjqf_/install-record.txt --single-version-externally-managed --compil                                                                                                  e --install-headers /var/www/html/search/elasticsearch_API/elasticsearchenv/include/site/python3.7/mod-wsgi Check the logs for full command                                                                                                   output.

However, I successfully run the django app using python3.6 and the corresponding mod_wsgi version, but is there a way to fix this problem in order to be able to run it with python3.7 too? I've tried MANY different solutions, but none seem to work.

**Comment by GrahamDumpleton** [comment]
As mentioned in:

* https://pypi.org/project/mod-wsgi/

> Similarly with Python, you must have a complete Python installation which includes the corresponding development package, which contains the header files for the Python library.

You are missing the developer (devel) package for the Python system package version you have installed. You will need to work out the name of the Python devel package and install it.

**Comment by AntonioAntovski** [comment]
Thank you. I've successfully solved the problem.
