### ISSUE TITLE
Requests running in wrong Django instance under Apache/mod_wsgi

### ISSUE THREAD

**Issue by Khushali22** [GrahamDumpleton/mod_wsgi#464]
I am trying to deploy multiple django instances in the same server. ALthough i am successful for deploying multiple django instances, but the requests is going to the wrong instances. For ex, I have a same django app but with different version deployed on server, So the structure is like follow:-
Root app:- 
  
![image](https://user-images.githubusercontent.com/10240131/65217866-d733e300-dad2-11e9-8a4c-028847bb4091.png)

Sub direct app:-( second instance)
![image](https://user-images.githubusercontent.com/10240131/65217762-9936bf00-dad2-11e9-8b33-fd659c196948.png)

Below is my config file:-

ServerName test.com
        ServerAlias www.test.com
        #DocumentRoot /var/www/html

        Alias /smart_chat_share_dev/static /var/www/html/smart_chat_share_dev/smart_chat_share/static
        <Directory /var/www/html/smart_chat_share_dev/smart_chat_share/static>
               Require all granted
       </Directory>

        WSGIDaemonProcess smart_chat_share_dev python-home=/var/www/html/smart_chat_share_dev/smart_chat_share/virtual_env python-path=/var/www/html/smart_chat_share_dev/smart_chat_share
        WSGIProcessGroup smart_chat_share_dev
        WSGIScriptAlias /smart_chat_share_dev /var/www/html/smart_chat_share_dev/smart_chat_share/smart_chat_share/wsgi.py process-group=smart_chat_share_dev application-group=%{GLOBAL}

        <Directory /var/www/html/smart_chat_share_dev/smart_chat_share/smart_chat_share>
               <Files wsgi.py>
                     Require all granted
               </Files>
       </Directory>

        Alias /static /var/www/html/Smart_chat_share/smart_chat_share/static
        <Directory /var/www/html/Smart_chat_share/smart_chat_share/static>
                Require all granted
        </Directory>

        WSGIDaemonProcess smart_chat_share python-home=/var/www/html/Smart_chat_share/smart_chat_share/virtual_env python-path=/var/www/html/Smart_chat_share/smart_chat_share
        WSGIProcessGroup smart_chat_share
        WSGIScriptAlias / /var/www/html/Smart_chat_share/smart_chat_share/smart_chat_share/wsgi.py process-group=smart_chat_share application-group=%{GLOBAL}

        <Directory /var/www/html/Smart_chat_share/smart_chat_share/smart_chat_share>
                <Files wsgi.py>
                     Require all granted
                </Files>
        </Directory>

The issue is my second instance is going to original instance only. If i want to access some django view from ajax, it says page not found error. Should i update my url in django or something i am missing in config file?

Any help will be much appreciated!!

**Comment by GrahamDumpleton** [comment]
Only the last ``WSGIProcessGroup`` used since they are both at global scope. Use the ``process-group`` option on ``WSGIScriptAlias`` instead.

Read:

* http://blog.dscpl.com.au/2012/10/requests-running-in-wrong-django.html

**Comment by Khushali22** [comment]
Thanks for the quick response! I read it but i am confused about the name. What should be the name/ It should be tha pp name smart_chat_share? or any nam ei can give? and If processgroup is defined in WSGIScriptAlias, then "WSGIProcessGroup smart_chat_share" should be removed or it is also mandatory to write.
Thanks!!

**Comment by GrahamDumpleton** [comment]
Sorry if caused any confusion. I added the reply in a hurry as knew I wasn't going to get to respond again for quite a while.

Looking more closely, you have the `process-group` options I spoke of and with the correct values. You should though remove the `WSGIProcessGroup` directives as they are not needed and what confused me in the first place.

Technically the `process-group` directive should take precedence even if `WSGIProcessGroup` exists, so as far as I can remember what you had should still have worked.

Remove the `WSGIProcessGroup` and try again. If that doesn't help, add:

```
WSGIRestrictEmbedded On
```

outside of the `VirtualHost` to ensure you aren't using embedded mode by mistake somehow.

Make sure Apache is getting restarted.
