### ISSUE TITLE
Problems wsgi not working in xampp 

### ISSUE THREAD

**Issue by dexter-leng** [GrahamDumpleton/mod_wsgi#465]
Hi, 
i have installed python 2.7.16 and apache 2.4 in xampp v3.2.1, i try to call my python script localhost/web/myapp.py i receive a Server error! 
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script." 
i also copy the mod_wsgi.pyd from "C:\Python27\Lib\site-packages\mod_wsgi\server\"to "C:\xampp\apache\modules\".

In the httpd.conf included;
LoadModule wsgi_module modules/mod_wsgi.pyd
WSGIPythonHome "C:/python27"
WSGIScriptAlias /web "C:/test/web/"
<Directory "C:/test/web">
        Order allow,deny
        Allow from all
</Directory>

and added .py  .wsgi in the AddHandler as following example
AddHandler cgi-script .cgi  .pl .asp .py .wsgi

in my python script i named my script as 'myapp.py' also tried to replace with .wsgi still not working,

def application(environ, start_response):
     
        status = '200 OK'
        output= 'Hello World'
        response_headers = [('Content-type', 'application/octet-stream'),
                            ('Content-Length', str(len(output)))]
        start_response(status, response_headers)
        return [output]

**Comment by GrahamDumpleton** [comment]
Try not adding `.py .wsgi` to `AddHandler cgi-script`. That shouldn't be done and can cause files to be handle as CGI rather than by mod_wsgi.

If that doesn't help, what actual URL path are you using in the browser? You should be using `/web`.

**Comment by dexter-leng** [comment]
Thank you so much @GrahamDumpleton :), it's works for me without adding the .py .wsgi extension.
I use 'localhost/web/myapp.py' call my script.

**Comment by GrahamDumpleton** [comment]
You should only be using `localhost/web`. You don't need `myapp.py`. The path after `/web` would be used later to route to specific handlers in your application.
