### ISSUE TITLE
Rebuild / Reconfigure mod_wsgi for python 3.7

### ISSUE THREAD

**Issue by dorian821** [GrahamDumpleton/mod_wsgi#467]
I'm trying to switch a django site from running in python 3.6 to python 3.7 on Ubuntu 16.04. To do so I created a new environment in the same path as the old and have re-installed all of the dependencies.

The Apache server, however, fails with the following error:

Fatal Python error: Py_Initialize: Unable to get the locale encoding ModuleNotFoundError: No module named 'encodings'
Which error, after a bit of research, seems to be due to the WSGI configuration, as per:

You cannot for example force mod_wsgi to use a Python virtual environment created using Python 3.5 when mod_wsgi was originally compiled for Python 2.7. This is because the Python library for the Python installation it was originally compiled against is linked directly into the mod_wsgi module. In other words, Python is embedded within mod_wsgi. When mod_wsgi is used it does not run the command line python program to run the interpreter and thus why you can’t force it to use a different Python installation.

from: https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

Some have suggested to wipe the setup clean and start fresh, but this seems a bit extreme to me, as it seems like I should just be able to re-install/re-configure mod-wsgi to run with python3.7

In this line of thinking, I uninstalled and reinstalled both, libapache2-mod-wsgi-py3 and mod_wsgi. The former, however, just reconfigures to 3.6 automatically, as seen below after re-installing libapach2-mod-wsgi-py3:

root@server1:~# dpkg -S mod_wsgi
libapache2-mod-wsgi-py3: /usr/lib/apache2/modules/mod_wsgi.so
libapache2-mod-wsgi-py3: /usr/lib/apache2/modules/mod_wsgi.so-3.6
and the mod_wsgi installation fails with:

RuntimeError: The 'apxs' command appears not to be installed or is not executable. 
How can I re-build wsgi with python 3.7?

**Comment by GrahamDumpleton** [comment]
Uninstall the system mod_wsgi package.

Using `pip install mod_wsgi` to install mod_wsgi into your Python 3.7 virtual environment (needs to be 3.7, can't use 3.6 environment nor can you attempt to run `virtualenv` for 3.7 with 3.6 environment as argument.

The run:

```
mod_wsgi-express module-config
```

Copy that into the system Apache to load mod_wsgi. Then configure Apache to load your WSGI application.

If only need it for development, use `mod_wsgi-express` instead.

See:

* https://pypi.org/project/mod-wsgi/

**Comment by dorian821** [comment]
First of all, I want to express my gratitude for responding so quickly on a Sunday afternoon! I really appreciate it. I was not expecting you to respond so promptly. 

Secondly, the solution worked great! It turned out that my installation of Python 3.7, via pyenv, was incomplete or corrupted, so I had to also reinstall it, but as per the issue at hand, the solution provided here worked like a charm. 

Much thanks! 

Have a great autumn!
