### ISSUE TITLE
Video streaming using flask and mod_wsgi on apache 2.4 not working.

### ISSUE THREAD

**Issue by tayaybkamboh** [GrahamDumpleton/mod_wsgi#468]
I have a flask app which display the live stream from webcam.Its working fine in development environment.but in production video frame freeze.I have asked the question on stackoverflow.
https://stackoverflow.com/questions/58061121/video-streaming-using-flask-and-mod-wsgi-on-Apache-2-4
 but no one answered.can you help me resolve this.

**Comment by GrahamDumpleton** [comment]
Closing this since you were asking on StackOverflow anyway.
