### ISSUE TITLE
Able to access my django app with ip : port number, but not with ip alone

### ISSUE THREAD

**Issue by VenkateshDharavath** [GrahamDumpleton/mod_wsgi#473]
I'm trying to deply my django application.
I've started server with 

    mod_wsgi-express start-server wsgi.py

it starts server in such a way that im able to access my site with localhost:8000. but I have a domain to map to my site. I get this after running server

    Server URL         : http://localhost:8000/
    Server Root        : /tmp/mod_wsgi-localhost:8000:1000
    Server Conf        : /tmp/mod_wsgi-localhost:8000:1000/httpd.conf
    Error Log File     : /tmp/mod_wsgi-localhost:8000:1000/error_log (warn)    
    Request Capacity   : 5 (1 process * 5 threads)
    Request Timeout    : 60 (seconds)
    Startup Timeout    : 15 (seconds)
    Queue Backlog      : 100 (connections)
    Queue Timeout      : 45 (seconds)
    Server Capacity    : 20 (event/worker), 20 (prefork)
    Server Backlog     : 500 (connections)
    Locale Setting     : en_US.UTF-8

please help me start my server with an IP and so i can access it with domain which is mapped to my ip. 
Thanks

**Comment by GrahamDumpleton** [comment]
What have you tried?

You can run `mod_wsgi-express start-server --help` and it provides lots of options along with the documentation on each.

If you expect to run on default HTTP port, the option you will find there is `--port 80`, but if you have an existing web server running on your host, you would need to stop it first.

Also, when running with port 80, it would need to be started as `root` as that is a privileged port.

If you can get it running on port 80 though, it should already be able to be contactable from outside of the host. You just need to have set up your DNS so the host name you want to use maps to the IP of your system.

There are more details on running as `root` and integrating into your system startup scripts in:

* https://pypi.org/project/mod-wsgi/

It may be better though to run as a non privileged port and set up your main web server to proxy to the second port.

So there are lots of things here, so there isn't a simple one line answer if that is what you are hoping for.

**Comment by VenkateshDharavath** [comment]
Thanks for responding to my query sir, I'm just graduated and deploying my first website. I've reached till here with your support only. I followed your documentation about mod_wigi-express.
 Ive tried to start server with default port 80. But it days bad group name. please check the below output

    (venv) [venkatesh@s148-72-213-154 django]$ mod_wsgi-express start-server --application-type 
    module tmhm_home.wsgi --port=80 \ --user www-data --group www-data
    Server URL         : http://localhost/
    Server Root        : /tmp/mod_wsgi-localhost:80:1000
    Server Conf        : /tmp/mod_wsgi-localhost:80:1000/httpd.conf
    Error Log File     : /tmp/mod_wsgi-localhost:80:1000/error_log (warn)
    Request Capacity   : 5 (1 process * 5 threads)
    Request Timeout    : 60 (seconds)
    Startup Timeout    : 15 (seconds)
    Queue Backlog      : 100 (connections)
    Queue Timeout      : 45 (seconds)
    Server Capacity    : 20 (event/worker), 20 (prefork)
    Server Backlog     : 500 (connections)
    Locale Setting     : en_US.UTF-8
    AH00544: httpd (mod_wsgi-express): bad group name www-data
    (venv) [venkatesh@s148-72-213-154 django]$

you also mentioned to setup mainserver to proxy to second port. please give me more inputs on it. That would be very helpful.
Thnak you

**Comment by GrahamDumpleton** [comment]
If you are just starting out, then you have a lot to learn. I can't provide you step by step instructions for everything. If I did that for everyone who was new I would get no work of my own done.

I would suggest you use Google to look for blog posts and documentation and learn step by step yourself. Don't expect it all to make sense immediately.

If you really want to get into Python web applications in particular, I would start out by reading the series of articles at:

* https://ruslanspivak.com/lsbaws-part1/

I would also suggest perhaps not using `mod_wsgi-express` if you don't know how to integrate that in your system yourself, but look for blog posts on manual setup of the system Apache using the mod_wsgi package that comes with your operating system.

For example, articles like:

* https://tecadmin.net/install-apache-mod-wsgi-on-ubuntu-16-04-xenial/

Also use StackOverflow as a source for information and to ask questions.

**Comment by VenkateshDharavath** [comment]
So much patience. Thank you so much for your inputs. I really appreciate that. Neophytes like me really need such support. I hope I'll reach that level soon.
Once again thank you so much.
