### ISSUE TITLE
mod_wsgi.so filesize over 1MB

### ISSUE THREAD

**Issue by JohnCAD** [GrahamDumpleton/mod_wsgi#474]
Hello!

When building mod_wsgi from source, I always end up with a mod_wsgi.so file that is over 1MB in filesize. The documentation says that this "indicates that the version of Python being used was not originally configured so as to produce a Python shared library and is instead only producing a static library."

However, output from `ldd mod_wsgi.so` looks like it is using the shared libpython3.7m.so file just fine.

> ldd mod_wsgi.so
>     . . . . .
>     libpython3.7m.so.1.0 => /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
>     . . . . .
>     . . . . .

I get the same results whether I compile using the CMMI method or the `pip install mod-wsgi` method.

Using `apt install libapache2-mod-wsgi-py3` results in a mod_wsgi.so filesize of around ~250K which sounds right according to the documentation, but my builds are always 4x that size.

Using Ubuntu 19.04 (or 18.04) Server, my process is: 
>apt install apache2-dev python3-all-dev python3-venv
>python3 -m venv venv
>source venv/bin/activate
>(venv) pip install mod-wsgi

OR

>apt install apache2-dev python3-all-dev
>git clone https://github.com/GrahamDumpleton/mod_wsgi.git
>cd mod_wsgi
>git checkout 4.6.8
>./configure --with-python=python3
>make
>sudo make install

It finishes both ways without any error, just the filesize in the resulting mod_wsgi.so is larger than 1MB.

Thanks,
-Jon

**Comment by GrahamDumpleton** [comment]
It is probably fine. That comment in documentation was probably written back around the time of mod_wsgi 1.X and has never been checked again.

As long as `ldd` shows that, you are good.

The difference between it and system packages is that for system packages it has likely has had `strip` run on it to remove all debugging symbols.

**Comment by JohnCAD** [comment]
Perfect, thank you! Yes, stripping my mod_wsgi.so brings the filesize down to 250K, nearly identical to the system package.
-Jon
