### ISSUE TITLE
Can't deploy Tensorflow chatbot on a Apache web server using Flask 

### ISSUE THREAD

**Issue by JulianaThayil** [GrahamDumpleton/mod_wsgi#476]
Im trying to deploy my flask chatbot on Wamp server using mod_wsgi. I am able to run a simple flask app on wamp. But when i try to run my flask AI chatbot that uses python packages such as tensorflow, numpy, tflearn etc, wamp wouldn't load it. I tested the flask app locally without any problem. But it doesn't work on wamp apache. Also it is unable to load the json file.

This is how i have configured apache

LoadFile "c:/users/juliana thayil/appdata/local/programs/python/python36/python36.dll"
LoadModule wsgi_module "c:/users/juliana thayil/appdata/local/programs/python/python36/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "c:/users/juliana thayil/appdata/local/programs/python/python36"
WSGIPythonPath "C:/wamp64/www/miniproject"

<VirtualHost *:80>
ServerName localhost
DocumentRoot c:/wamp64/www
WSGIScriptAlias /miniproject c:/wamp64/www/miniproject/web.wsgi
<Directory c:/wamp64/www/miniproject>
require all granted
 </Directory>
</VirtualHost>

**Comment by GrahamDumpleton** [comment]
You need to set `WSGIApplicationGroup %{GLOBAL}` as explained in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

That doc needs updating, but `numpy` and anything relying on it requires that.

**Comment by JulianaThayil** [comment]
That worked. Thanks
But now im getting this error

[Tue Oct 22 21:55:36.023862 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952] mod_wsgi (pid=9864): Failed to exec Python script file 'C:/wamp64/www/miniproject/web.wsgi'.
[Tue Oct 22 21:55:36.024861 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952] mod_wsgi (pid=9864): Exception occurred processing WSGI script 'C:/wamp64/www/miniproject/web.wsgi'.
[Tue Oct 22 21:55:36.024861 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952] Traceback (most recent call last):\r
[Tue Oct 22 21:55:36.024861 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952]   File "C:/wamp64/www/miniproject/web.wsgi", line 5, in <module>\r
[Tue Oct 22 21:55:36.024861 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952]     from app import app\r
[Tue Oct 22 21:55:36.024861 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952]   File "C:\\wamp64\\www\\miniproject\\app.py", line 16, in <module>\r
[Tue Oct 22 21:55:36.024861 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952]     **with open('intents.json') as file:\r**
[Tue Oct 22 21:55:36.024861 2019] [wsgi:error] [pid 9864:tid 1184] [client ::1:53952] FileNotFoundError: [Errno 2] **No such file or directory: 'intents.json'\r**

But I already have the intents.json file in the directory of my flask app. How do i tell it where the intents.json file is stored? What changes should i make to the configuration file ?

**Comment by woodlandhunter** [comment]
@JulianaThayil Possible solutions:
- set the absolute path (that path probably belongs in a config file anyways)
- use `__file__` and `os.path.join`

See also the mod_wsgi [docs](https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#application-working-directory) on the subject

**Comment by GrahamDumpleton** [comment]
Thanks @woodlandhunter. For whatever reason I completely missed the follow up question.
