### ISSUE TITLE
Python 3.5 vs Python 3.4 on Apache (Windows)

### ISSUE THREAD

**Issue by vladbazarsky** [GrahamDumpleton/mod_wsgi#477]
No issues with pip or config, no errors. Works perfectly with 3.4. Works intermittently with 3.5. Custom  code stays the same, no browser errors, http request just runs forever. Sometimes page just comes up with no issues or delays.

Any insight is greatly appreciated.

Vlad

**Comment by GrahamDumpleton** [comment]
Are you using mod_wsgi daemon mode?

Are you using the recommended setup of one application per daemon mode process group, and forcing the use of the main interpreter context of each process group.

In other words, are you using `WSGIDaemonProcess``, ``WSGIProcessGroup`` and most importantly ``WSGIApplicationGroup %{GLOBAL}`` in your configuration?

Can you show your configuration for mod_wsgi.

**Comment by vladbazarsky** [comment]
I was not, let me try some of those options and report back. I am on Windows 7.

Thanks

**Comment by GrahamDumpleton** [comment]
You can't use daemon mode then. So long as you have the one application, you should still add:

```
WSGIApplicationGroup %{GLOBAL}
```

It avoids problems with some third party C extensions in modules for Python that will not work in sub interpreters.

**Comment by vladbazarsky** [comment]
Many thanks, Graham - no issues so far
