### ISSUE TITLE
unable to run mod_wsgi-express install-module in terminal

### ISSUE THREAD

**Issue by mallikarjunm034** [GrahamDumpleton/mod_wsgi#478]
i have installed mod_wsgi using pip but when i ran this mod_wsgi-express install-module 
not recongzied by windows

**Comment by GrahamDumpleton** [comment]
On Windows, the only command `mod_wsgi-express` understands is:

```
mod_wsgi-express module-config
```

Manually copy what it outputs into your existing Apache configuration and then manually set up Apache for mod_wsgi to run your WSGI application.

**Comment by mallikarjunm034** [comment]
![image](https://user-images.githubusercontent.com/18530855/67471441-0f4bba00-f66d-11e9-9a39-b511f9a2d230.png)
i am getting this error

**Comment by GrahamDumpleton** [comment]
I'd suggest you ask on StackOverflow. I don't know anything really about Windows and this to me looks like your operating system setup for Python is somehow mucked up.
