### ISSUE TITLE
Unknown command: 'runmodwsgi'

### ISSUE THREAD

**Issue by VenkateshDharavath** [GrahamDumpleton/mod_wsgi#483]
hello, I successfully deployed my django app on linux server a month ago using mod_wsgi-express.
Now I've update the website and trying to deploy but the strangely it gives the error saying Unknown command: 'runmodwsgi' in the command 
      `python manage.py runmodwsgi --setup-only --port=80 --user venkatesh --group venkatesh --server-root=/tmp/mod_wsgi-express-80.`
I'm getting the following:

    (venv) [venkatesh@s148-72-213-154 tmhm_home]$ python3.7 manage.py runmodwsgi --setup-only --reload-on-chnages --port=80 --user venkatesh --group venkatesh --server-root=/tmp/mod_wsgi-express-80
    Unknown command: 'runmodwsgi'
    Type 'manage.py help' for usage.
    (venv) [venkatesh@s148-72-213-154 tmhm_home]$

please help me !

**Comment by GrahamDumpleton** [comment]
Is `mod_wsgi.server` still listed in the Django installed apps setting?

**Comment by VenkateshDharavath** [comment]
oh yes, it's been commented in the list. Thank you so much sir.
but subdomain seems not work on server which were working on local machine.
this is my hosts.py.

    from django.conf import settings
    from django_hosts import patterns, host

    host_patterns = patterns('',
    host(r'www', settings.ROOT_URLCONF, name='www'),
    host(r'connect', 'Portal.urls', name='portal'),
    )
Project urls.py

    from django.contrib import admin
    from django.urls import path
    from django.urls import path, include
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns


    urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')), ]
	

    urlpatterns+=staticfiles_urlpatterns()

App urls.py

    urlpatterns = [
    url(r'^$', auth_views.LoginView.as_view(template_name='Portal/login.html'), name='home'),
    ]

finally this is my settings.py

    MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',

    'django_hosts.middleware.HostsResponseMiddleware',
    ]

    ROOT_URLCONF = 'tmhm_home.urls'
The output I'm getting for domain.host.in is 

    This site can't be reached
    host’s server IP address could not be found.

please give me some inputs.

**Comment by GrahamDumpleton** [comment]
That is going to be an issue with DNS, or `/etc/hosts` file, if the host IP changed. Need to update any hostname mapping. Wouldn't be anything to do with mod_wsgi.
