### ISSUE TITLE
ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by ajipmdkr** [GrahamDumpleton/mod_wsgi#488]
When I try the below method I get the error
uwsgi --http :8000 --module project_name.wsgi
tracing to 
Traceback (most recent call last):
  File "./project_name/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
But if i run using
python manage.py runserver 0.0.0.0:8000
it's working fine..????

**Comment by GrahamDumpleton** [comment]
This is the repository for mod_wsgi not uwsgi.
