### ISSUE TITLE
Can't install mod_wsgi with the latest stable Python version (Python3.8) on Ubuntu 18.04

### ISSUE THREAD

**Issue by andym196** [GrahamDumpleton/mod_wsgi#490]
I've used mod_wsgi on other python versions. Right now I can install mod_wsgi with python3.6 and python3.7:
```
    python3.6 -m pip install mod_wsgi
    python3.7 -m pip install mod_wsgi
```
    
But it doesn't work for the latest python3.8 version:
`    python3.8 -m pip install mod_wsgi`
    
The error in red text that shows when trying to install with python3.8 is: 'Failed building wheel for mod-wsgi'

Any idea what the problem is?

**Comment by GrahamDumpleton** [comment]
No idea as not enough information is provided. I need to to see the full error messages from ``pip``, not just the last line.

Use ``-v`` option to ``pip`` to get more verbose error messages if ``pip`` is not displaying the compiler error messages when it fails, although it should be unless ``pip`` in Python 3.8 is different.

Just to be safe, also add the ``--no-cache-dir`` option to ``pip`` to ensure that any prior build artefacts in the ``pip`` cache are ignored.

**Comment by andym196** [comment]
Yeah sure. So `mod_wsgi` installs OK with pip on Python3.6 & Python3.7 on the same Ubuntu 18.04 server as Python3.8, so I have all the prerequisites already installed. I recently installed Python3.8 and I can install all the modules with pip using Python3.8 except mod_wsgi. Here is the full error when I try to install with with Python3.8: 

`python3.8 -m pip --no-cache-dir install mod_wsgi`

Collecting mod_wsgi
  Downloading https://files.pythonhosted.org/packages/25/d8/1df4ba9c051cd88e02971814f0867274a8ac821baf983b6778dacd6e31f7/mod_wsgi-4.6.8.tar.gz (490kB)
    100% |████████████████████████████████| 491kB 25.7MB/s
Installing collected packages: mod-wsgi
  Running setup.py install for mod-wsgi ... error
    Complete output from command /usr/bin/python3.8 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e3gioggd/mod-wsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j4g2u0ba-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/mod_wsgi
    copying src/__init__.py -> build/lib.linux-x86_64-3.8/mod_wsgi
    creating build/lib.linux-x86_64-3.8/mod_wsgi/server
    copying src/server/apxs_config.py -> build/lib.linux-x86_64-3.8/mod_wsgi/server
    copying src/server/environ.py -> build/lib.linux-x86_64-3.8/mod_wsgi/server
    copying src/server/__init__.py -> build/lib.linux-x86_64-3.8/mod_wsgi/server
    creating build/lib.linux-x86_64-3.8/mod_wsgi/server/management
    copying src/server/management/__init__.py -> build/lib.linux-x86_64-3.8/mod_wsgi/server/management
    creating build/lib.linux-x86_64-3.8/mod_wsgi/server/management/commands
    copying src/server/management/commands/runmodwsgi.py -> build/lib.linux-x86_64-3.8/mod_wsgi/server/management/commands
    copying src/server/management/commands/__init__.py -> build/lib.linux-x86_64-3.8/mod_wsgi/server/management/commands
    creating build/lib.linux-x86_64-3.8/mod_wsgi/docs
    copying docs/_build/html/__init__.py -> build/lib.linux-x86_64-3.8/mod_wsgi/docs
    creating build/lib.linux-x86_64-3.8/mod_wsgi/images
    copying images/__init__.py -> build/lib.linux-x86_64-3.8/mod_wsgi/images
    copying images/snake-whiskey.jpg -> build/lib.linux-x86_64-3.8/mod_wsgi/images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi-py38' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/server
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/apache2 -I/usr/include/python3.8 -c src/server/wsgi_daemon.c -o build/temp.linux-x86_64-3.8/src/server/wsgi_daemon.o -I/usr/include/apache2 -I. -I/usr/include/apr-1.0 -I/usr/include -Wdate-time -D_FORTIFY_SOURCE=2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -pthread -I/usr/include/apr-1.0 -I/usr/include/apr-1.0 -I/usr/include
    In file included from src/server/wsgi_daemon.h:24:0,
                     from src/server/wsgi_daemon.c:21:
    src/server/wsgi_python.h:24:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.8 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e3gioggd/mod-wsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j4g2u0ba-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-e3gioggd/mod-wsgi/

**Comment by GrahamDumpleton** [comment]
You don't have the Python 3.8 'dev' package installed. You only have the runtime package installed.

**Comment by GrahamDumpleton** [comment]
More details in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#missing-python-header-files

and also mentioned in:

* https://pypi.org/project/mod-wsgi/

**Comment by andym196** [comment]
OK thanks. I'll look into that.

**Comment by andym196** [comment]
That fixed it. I just needed: 
`sudo apt-get install python3.8-dev`

Thanks for your help, it's much appreciated.

**Comment by rehbarkhan** [comment]
I am trying to install mod-wsgi using the latest pip version and getting error: 
Failed to build mod-wsgi
ERROR: Could not build wheels for mod-wsgi, which is required to install pyproject.toml-based projects

I have already installed python3.11 python3.11-devel python3.11-pip python3.11-setuptools packages but no lunck.
Kindly help .

**Comment by GrahamDumpleton** [comment]
@rehbarkhan Please create a new issue, don't use an old issue.

Provide the full output of `pip3 install` when using the `-v -v -v` option in the new issue.

**Comment by rehbarkhan** [comment]
@GrahamDumpleton , I have opened https://github.com/GrahamDumpleton/mod_wsgi/issues/868
