### ISSUE TITLE
Load module to apache - mod_wsgi from venv

### ISSUE THREAD

**Issue by sapir123** [GrahamDumpleton/mod_wsgi#493]
Hi,
I'm trying to load the mod_wsgi from the venv of my project,
I ran the ,mod_wsgi-express module-config from the CMD(after I activated the venv), and got the following:
**LoadModule wsgi_module "C:/users/ihen2622/documents/my_project/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"**
**WSGIPythonHome "C:/users/ihen2622/documents/my_project/venv"**

I paste it in the conf file but got error:
**Fatal Python error: initfsencoding: unable to load the file system codec ModuleNotFoundError: No module named 'encodings'**

But when i load the module not from the venv, but instead from:
**LoadFile "C:/python37/python37.dll"
LoadModule wsgi_module "C:/python37/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "C:/python37"**

It worked.

How can i load the module from the venv? 
Thank you in advanced for your help!
Sapir

**Comment by GrahamDumpleton** [comment]
Possibly a permissions issue where the Apache service cannot read directories/files from under your user directory.

**Comment by timh52280** [comment]
I have the same problem, does anyone solved this?

**Comment by GrahamDumpleton** [comment]
@timh52280 Is your virtual environment under your user account? Have you tried creating the virtual environment outside of your user account, such as at `C:/python37-envs/myenv` to eliminate permissions issues?

**Comment by timh52280** [comment]
@GrahamDumpleton Yeah my venv is under my home user account in a directory called venvs, is it not recomendable?

**Comment by GrahamDumpleton** [comment]
The permissions on a user directory may be that the separate service user that Apache often runs as cannot read stuff under the user directory. So try with stuff outside of the user account.

**Comment by timh52280** [comment]
Okay I will try and I'll be back with feedback
