### ISSUE TITLE
 Truncated or oversized response headers received from daemon process 'cp-backend-ssl': /var/www/cp-backend/django_backend/wsgi.py

### ISSUE THREAD

**Issue by MirceaM74** [GrahamDumpleton/mod_wsgi#494]
Hello Graham,

I have a website hosted on a vps, in a virtualmin env. Recently, the server os packages were updated by webmin packages updates and all the problems started afterwards. The site uses a python virtual env and since the update was made, we are receiving this error. When we access the front end it doesn't generate any error in error.log, only when we try to access the backend we get this error. We receive a django login prompt, but after we click "log in" we get "internal server error". We have tried averything listed here, but nothing changed. I am not the developer and I cannot get in touch with him in order to understand the architecture. We are just trying to bring the site online. I am not very familiar with python and django, but I started to learn a lot in the last couple of days. : ) Maybe you could give a hint with that? Thanks in advance!

Mircea

the errors:
errors.log:

[Thu Nov 28 19:37:56.099527 2019] [wsgi:info] [pid 2649] mod_wsgi (pid=2649): Imported 'mod_wsgi'.
[Thu Nov 28 19:37:56.117990 2019] [wsgi:info] [pid 2650] mod_wsgi (pid=2650): Attach interpreter ''.
[Thu Nov 28 19:37:56.135216 2019] [wsgi:info] [pid 2650] mod_wsgi (pid=2650): Imported 'mod_wsgi'.
[Thu Nov 28 19:37:56.442290 2019] [wsgi:error] [pid 2344] [client 82.210.152.183:52906] Truncated or oversized response headers received from daemon process 'cp-backend-ssl': /var/www/cp-backend/django_backend/wsgi.py, referer: https://xxxxxxxxx/api/admin/login/
[Thu Nov 28 19:37:56.999807 2019] [core:notice] [pid 2327] AH00052: child pid 2336 exit signal Segmentation fault (11)
[Thu Nov 28 19:37:56.999966 2019] [wsgi:info] [pid 2327] mod_wsgi (pid=2336): Process 'cp-backend-ssl' has died, deregister and restart it.
[Thu Nov 28 19:37:56.999989 2019] [wsgi:info] [pid 2327] mod_wsgi (pid=2336): Process 'cp-backend-ssl' terminated by signal 11
[Thu Nov 28 19:37:57.000005 2019] [wsgi:info] [pid 2327] mod_wsgi (pid=2336): Process 'cp-backend-ssl' has been deregistered and will no longer be monitored.
[Thu Nov 28 19:37:57.002373 2019] [wsgi:info] [pid 2654] mod_wsgi (pid=2654): Starting process 'cp-backend-ssl' with uid=33, gid=33 and threads=15.
[Thu Nov 28 19:37:57.004593 2019] [wsgi:info] [pid 2654] mod_wsgi (pid=2654): Python home /var/www/.virtualenvs/cp-backend_v3.
[Thu Nov 28 19:37:57.004696 2019] [wsgi:info] [pid 2654] mod_wsgi (pid=2654): Initializing Python.
[Thu Nov 28 19:37:57.102644 2019] [wsgi:info] [pid 2654] mod_wsgi (pid=2654): Attach interpreter ''.
[Thu Nov 28 19:37:57.164861 2019] [wsgi:info] [pid 2654] mod_wsgi (pid=2654): Adding '/var/www/cp-backend' to path.
[Thu Nov 28 19:37:57.179505 2019] [wsgi:info] [pid 2654] mod_wsgi (pid=2654): Imported 'mod_wsgi'.

(cp-backend_v3) root@web:/var/www/.virtualenvs/cp-backend_v3# python /var/www/.virtualenvs/cp-backend_v3/django_backend/wsgi.py

Traceback (most recent call last):
  File "/var/www/.virtualenvs/cp-backend_v3/django_backend/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/var/www/.virtualenvs/cp-backend_v3/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/var/www/.virtualenvs/cp-backend_v3/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/www/.virtualenvs/cp-backend_v3/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/var/www/.virtualenvs/cp-backend_v3/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/www/.virtualenvs/cp-backend_v3/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/var/www/.virtualenvs/cp-backend_v3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_backend'

config files:

apache

               WSGIApplicationGroup %{GLOBAL}
                WSGIPassAuthorization On
                Timeout 600
                WSGIDaemonProcess cp-backend-ssl processes=5 threads=15 python-home=/var/www/.virtualenvs/cp-backend_v3 python-path=/var/www/cp-backend
                WSGIProcessGroup cp-backend-ssl
                WSGIScriptAlias /api /var/www/cp-backend/django_backend/wsgi.py

                <Directory /var/www/cp-backend/django_backend>
                        <Files wsgi.py>
                                Require all granted
                        </Files>

wsgi.py
"""
WSGI config for django_backend project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "django_backend.settings")

application = get_wsgi_application()

pip freeze

(cp-backend_v3) root@web:/var/www/.virtualenvs/cp-backend_v3# pip freeze
beautifulsoup4==4.6.0
certifi==2018.1.18
chardet==3.0.4
Django==2.0.4
django-cleanup==2.1.0
django-colorfield==0.1.14
django-cors-headers==2.2.0
django-filter==1.1.0
django-summernote==0.8.8.6
djangorestframework==3.8.2
drf-nested-routers==0.90.2
idna==2.6
Markdown==2.6.11
mod-wsgi==4.6.8
Pillow==5.1.0
psycopg2==2.7.4
psycopg2-binary==2.7.4
python-magic==0.4.15
pytz==2018.4
requests==2.18.4
urllib3==1.22
xlwt==1.3.0

**Comment by GrahamDumpleton** [comment]
Your system likely upgraded OpenSSL or crypto libraries and your Python installation, and possibly installed Python packages, were originally built for different version of those libraries.

If using system Python to create the virtual environment, make sure the system Python packages are also up to date, and then recreate the Python virtual environment with all your packages re-installed. In doing that, recommend not using ``psycopg2-binary==2.7.4`` as that binary wheel package is known to cause problems by having being compiled directly against specific OpenSSL library versions and so can break if system OpenSSL libraries don't match. Use just ``psycopg2`` so that it is compiled from source code for specific system library versions you have.

**Comment by MirceaM74** [comment]
hello,

Your right, I can see this in the log 

2019-11-22 14:01:59 upgrade openssl:amd64 1.1.0g-2ubuntu4.3 1.1.1-1ubuntu2.1~18.04.5
2019-11-22 14:01:59 status half-configured openssl:amd64 1.1.0g-2ubuntu4.3
2019-11-22 14:01:59 status unpacked openssl:amd64 1.1.0g-2ubuntu4.3
2019-11-22 14:01:59 status half-installed openssl:amd64 1.1.0g-2ubuntu4.3
2019-11-22 14:01:59 status half-installed openssl:amd64 1.1.0g-2ubuntu4.3
2019-11-22 14:01:59 status unpacked openssl:amd64 1.1.1-1ubuntu2.1~18.04.5
2019-11-22 14:01:59 status unpacked openssl:amd64 1.1.1-1ubuntu2.1~18.04.5
2019-11-22 14:05:35 configure openssl:amd64 1.1.1-1ubuntu2.1~18.04.5 <none>
2019-11-22 14:05:35 status unpacked openssl:amd64 1.1.1-1ubuntu2.1~18.04.5
2019-11-22 14:05:35 status unpacked openssl:amd64 1.1.1-1ubuntu2.1~18.04.5
2019-11-22 14:05:35 status half-configured openssl:amd64 1.1.1-1ubuntu2.1~18.04.5
2019-11-22 14:05:35 status installed openssl:amd64 1.1.1-1ubuntu2.1~18.04.5

Should I try and downgrade openssl to 1.1.0g?

Thx!

**Comment by MirceaM74** [comment]
And could you please tell me how do I install psycopg2?

Thx

**Comment by GrahamDumpleton** [comment]
You had already installed it:

```
psycopg2==2.7.4
psycopg2-binary==2.7.4
```

So you seem to be aware of how to install packages.

Try doing this:

```
pip uninstall psycopg2 psycopg2-binary
```

and:

```
pip install --no-cache-dir psycopg2==2.7.4
```

In other words, avoid installing the binary variant of the package. You somehow how both source and binary variants installed.

**Comment by MirceaM74** [comment]
Hello Graham,
 
Yes, I am familiar with installing packages, sys admin, etc…I am not familiar with programing and programing environment.
 
I have done what you have recommended on the system itself and in .virtualenvs/ cp-backend_v3, but nothing changed, I receive one more error
 
[Sat Nov 30 13:25:37.196957 2019] [reqtimeout:info] [pid 12260] [client 82.210.152.183:59119] AH01382: Request header read timeout
[Sat Nov 30 13:25:39.183324 2019] [ssl:info] [pid 12259] [client 82.210.152.183:59134] AH01964: Connection to child 1 established (server aclinique.ro:443)
[Sat Nov 30 13:25:39.206272 2019] [wsgi:info] [pid 12251] [remote 82.210.152.183:59134] mod_wsgi (pid=12251, process='cp-backend-ssl', application=''): Loading WSGI script '/var/www/cp-backend/django_backend/wsgi.py'.
[Sat Nov 30 13:25:39.951988 2019] [wsgi:error] [pid 12251] /var/www/.virtualenvs/cp-backend_v3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[Sat Nov 30 13:25:39.952116 2019] [wsgi:error] [pid 12251]   """)
[Sat Nov 30 13:25:43.941389 2019] [wsgi:error] [pid 12259] [client 82.210.152.183:59134] Truncated or oversized response headers received from daemon process 'cp-backend-ssl': /var/www/cp-backend/django_backend/wsgi.py, referer: https://aclinique.ro/api/admin/login/
[Sat Nov 30 13:25:44.208716 2019] [core:notice] [pid 12241] AH00052: child pid 12249 exit signal Segmentation fault (11)

**Comment by GrahamDumpleton** [comment]
Only other suggestion at this point is to use a debugger to work out where it is crashing. There is going to be some sort of library mismatch. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb

**Comment by GrahamDumpleton** [comment]
The problem might also be the old psycopg2 version you are using. Try using:

```
psycopg2==2.8.4
```

In 2.7 version of psycopy2, based on that warning message, the non suffixed package may also be a binary wheel. Make sure you again uninstall any `psycopg2/psycopg2-binary` packages first.

**Comment by MirceaM74** [comment]
Graham, you are a genius! It worked with psycopg2==2.8.4. I also had to apt-get install python-psycopg2 and libpq-dev as requirements, but we have now the site up and running! 
 
I owe you one, thank you very much for the support!
 
Mircea
