### ISSUE TITLE
Mac OS Mojave(10.14.6)/mod_wsgi-4.6.8/Apache 2 - Error loading dylib 

### ISSUE THREAD

**Issue by madhusv** [GrahamDumpleton/mod_wsgi#496]
I'm migrating from python 2.7 to 3.8. I'm getting this error when apache tries load mod_wsgi.so into the server. Error given below... 

_**Error**_
sh-3.2# ./apachectl start
httpd: Syntax error on line 55 of /usr/local/apache2/conf/httpd.conf: Cannot load /usr/local/apache2/modules/mod_wsgi.so into server: dlopen(/usr/local/apache2/modules/mod_wsgi.so, 10): Library not loaded: @rpath/libpython3.7m.dylib\n  Referenced from: /usr/local/apache2/modules/mod_wsgi.so\n  Reason: image not found

Compilation of mod_wsgi worked fine not sure whether any command line argument need to be added for @rpath issue with apxs. 

**_mod_wsgi compilation_**
$ ./configure --with-python=/usr/local/bin/python3.8 --with-apxs=/usr/local/apache2/bin/apxs
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for prctl... no
checking Apache version... 2.2.34
configure: creating ./config.status
config.status: creating Makefile
(base) madhuseshadris:mod_wsgi-4.6.8 madhukumar$ su
Password:
sh-3.2# make install
/usr/local/apache2/bin/apxs -i -S LIBEXECDIR=/usr/local/apache2/modules -n 'mod_wsgi' src/server/mod_wsgi.la
/usr/local/apache2/build/instdso.sh SH_LIBTOOL='/usr/local/apache2/build/libtool' src/server/mod_wsgi.la /usr/local/apache2/modules
/usr/local/apache2/build/libtool --mode=install cp src/server/mod_wsgi.la /usr/local/apache2/modules/
libtool: install: cp src/server/.libs/mod_wsgi.so /usr/local/apache2/modules/mod_wsgi.so
libtool: install: cp src/server/.libs/mod_wsgi.lai /usr/local/apache2/modules/mod_wsgi.la
libtool: install: cp src/server/.libs/mod_wsgi.a /usr/local/apache2/modules/mod_wsgi.a
libtool: install: chmod 644 /usr/local/apache2/modules/mod_wsgi.a
libtool: install: ranlib /usr/local/apache2/modules/mod_wsgi.a
chmod 755 /usr/local/apache2/modules/mod_wsgi.so

**Comment by GrahamDumpleton** [comment]
Are you using Python 3.8 installed using Homebrew?

Try not using configure/make/make install method of installation and use the ``pip install`` method instead.

* https://pypi.org/project/mod-wsgi/

It is possible that Python 3.8 with brew is broken as far as being able to embed Python in other programs.

If that still doesn't work, a workaround may be to add before the ``LoadModule`` line, a line:

```
LoadFile /some/path/libpython3.7m.dylib
```

Change ``/some/path`` to the path of the directory where that shared library is installed.

**Comment by madhusv** [comment]
Thanks. I had conda installed and it was putting python executable in front my modifying the path. I installed python 3.8 distribution python.org and got it compiled. I just got linker warning
ld: warning: directory not found for option '-L/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config'. Everything works fine. Thanks again.
