### ISSUE TITLE
Apache returns 500 error when import cv2 python

### ISSUE THREAD

**Issue by Pannakoek** [GrahamDumpleton/mod_wsgi#499]
Recently I started putting my Django project on my raspberry pi. Everything worked fine until i added OpenCV to my Django project. And got a 500 error. So i started searching on the internet and found out that I should add `%{GLOBAL}` to the apache config file (/etc/apache2/sites-available/000-default.conf) and restart the server and so I did. This didn't help so I kept searching but could found another way to fix it. When I go to the error log it shows:
`[Tue Dec 03 07:17:18.929260 2019] [wsgi:error] [pid 1620:tid 2999972896] [client 192.168.1.101:50157] Truncated or oversized response headers received from daemon process 'WhoAreYou': /home/pi/Projects/WhoAreYou/WhoAreYou/wsgi.py, referer: http://192.168.1.108/people/
[Tue Dec 03 07:17:19.065442 2019] [core:notice] [pid 1616:tid 3070173712] AH00052: child pid 1736 exit signal Aborted (6)`

And again I found that i should add `%{GLOBAL}` to the apache config and restart the server. It still not works.

When I comment `import cv2` out it works as intended.

My current config file of apache looks like:
```
<VirtualHost *:80>
        Alias /static /home/pi/Projects/WhoAreYou/production_static
                <Directory /home/pi/Projects/WhoAreYou/production_static>
                        Require all granted
                </Directory>

        Alias /videos /home/pi/hdd
                <Directory /home/pi/hdd>
                        Require all granted
                </Directory>

        <Directory /home/pi/Projects/WhoAreYou/WhoAreYou>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        WSGIDaemonProcess WhoAreYou python-path=/home/pi/Projects/WhoAreYou python-home=/home/pi/Projects/WhoAreYou/env
        WSGIProcessGroup WhoAreYou
        WSGIApplicationGroup %{GLOBAL}
        WSGIScriptAlias / /home/pi/Projects/WhoAreYou/WhoAreYou/wsgi.py

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

I hope somebody can help me out. If more information needed I can supply it.

**Comment by GrahamDumpleton** [comment]
How are you building and installing OpenCV? From source code, using a binary wheel?

**Comment by Pannakoek** [comment]
I have installed opencv from binary wheel. I ran `pip install opencv-python` (This pip goes to python3)

**Comment by Pannakoek** [comment]
This works when I open a python shell inside of the virtualenv and import it and check for the version

**Comment by GrahamDumpleton** [comment]
Where are you getting the binary wheel from, I don't see binary wheels for ARM (RaspberryPi) on PyPi?

It usually isn't the import that is going to be the problem, but when something tries to call into the module and hits the C extension.

Can you disable the OpenCV code in your Django application so isn't used, and just add `import cv2` into the WSGI script file, and see if it crashes just on the import.

If you have gdb available on the platform, you may have to try and use steps described in the following to capture a stack trace.

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb

A likely cause of a crash like this, is that the binary wheel is compiled against different versions of a library that is already being pulled into Apache. This can be SSL and crypto libraries if mod_ssl library is enabled in Apache, or more likely in this case, image libraries if PHP is enable in Apache.

**Comment by Pannakoek** [comment]
I use this one: https://pypi.org/project/opencv-python/.

I am not sure what you mean with: 
> Can you disable the OpenCV code in your Django application so isn't used, and just add import cv2 into the WSGI script file, and see if it crashes just on the import.

Do you mean the file I show in the first post or within the Django app?

I was able to get gdb on my raspberry pi but it didn't understand the executables file type.

**Comment by GrahamDumpleton** [comment]
None of the wheels at:

* https://pypi.org/project/opencv-python/4.1.0.25/#files

appear to be for the ARM architecture used by the RaspberryPi though. So I don't understand how you could install them. There doesn't seem to be a source only package there.

What is the output when you run a fresh `pip install opencv-python==4.1.0.25`.

**Comment by Pannakoek** [comment]
I see it was a different website: https://www.piwheels.org/simple/opencv-python/
This one has the ARM architecture so that is my bad.

```
pip install opencv-python==4.1.0.25
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python==4.1.0.25
  Using cached https://www.piwheels.org/simple/opencv-python/opencv_python-4.1.0.25-cp37-cp37m-linux_armv7l.whl
Requirement already satisfied: numpy>=1.16.2 in ./env/lib/python3.7/site-packages (from opencv-python==4.1.0.25) (1.17.3)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.1.0.25
```

**Comment by GrahamDumpleton** [comment]
Are you also using the binary wheels on that site for `mod_wsgi` and `mod_wsgi-httpd`? Or are you using the system Apache and mod_wsgi compiled from source code? How did you install `mod_wsgi`?

**Comment by Pannakoek** [comment]
I got mod_wsgi_httpd the same way as opencv-python
`https://www.piwheels.org/simple/mod-wsgi-httpd/mod_wsgi_httpd-2.4.39.1-cp37-cp37m-linux_armv7l.whl`

With the mod_wsgi it gets the tar.gz and builds a wheel.
`https://files.pythonhosted.org/packages/25/d8/1df4ba9c051cd88e02971814f0867274a8ac821baf983b6778dacd6e31f7/mod_wsgi-4.6.8.tar.gz`

I both just installed them with pip install ....

**Comment by GrahamDumpleton** [comment]
As in you had already previously installed `mod_wsgi-httpd` before you started, or you did it just now?

What is the `LoadModule wsgi_module` line in Apache configuation say?

What you have shown so far suggests that you are manually configuring the system Apache. This means you don't need `mod_wsgi-httpd` installed. You could even be using system package for `mod_wsgi` as well, meaning `pip install`` of `mod_wsgi` wasn't needed either. This is why am asking for the `LoadModule` line to see what `mod_wsgi` module you are loading.

If the `LoadModule` line doesn't reference system package for `mod_wsgi` and instead references `mod_wsgi` installed using `pip`, a potential problem is that the `mod_wsgi` installed by `pip` would be built for Apache installed from `mod_wsgi-httpd` package. This could be incompatible with system Apache.

So there could be a bit of a mess here around using things together. Or at the least, you have installed things you didn't need to.

**Comment by Pannakoek** [comment]
I installed `mod_wsgi-httpd` just now. 
I don't have any `LoadModule` in my Apache configuration.
I haven't changed the apache2 config file sins I posted it in the first post.
When I run `apache2ctl -t -D DUMP_MODULES`. I see `wsgi_module (shared)` in the list.

**Comment by Pannakoek** [comment]
I search a bit around and found out that the mod_wsgi was downloaded via pip and via apt-get (Raspberry pi distributer). So I removed the mod_wsgi and mod_wsgi-httpd. Apache works still the same as it was so that was a duplicate thing.

**Comment by GrahamDumpleton** [comment]
Sorry for delay in follow up, been busy.

Only thing can suggest at this point is to do `pip install mod_wsgi` and then run `mod_wsgi-express start-server` to see whether `mod_wsgi-express` works.

If it starts, then make a copy of:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/tests/hello.wsgi

and run:

```
mod_wsgi-express start-server hello.wsgi
```

Hit the URL for the `mod_wsgi-express` server.

If hello world works, then add the import for `cv2` into the `hello.wsgi` file and try again.

This will confirm whether the module can be imported at least without an issue.

You might then try a really simple bit of code that exercises `cv2` independent of your complete application.

**Comment by Pannakoek** [comment]
This thing gets weirder and weirder for me. I played a bit around with `mod_wsgi-express` and when I give it the WSGI file of my project it works with OpenCV and I get the line:
`[core:notice] [pid 26174:tid 2821817376] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/mod_wsgi-localhost:8000:1000/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D mODE_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'`
Which I haven't seen in the error/debug logs that I have watched before. 

For me, it seems like this only works when it is a localhost server and when it gets none localhost it stops working

**Comment by GrahamDumpleton** [comment]
That line in the logs is completely normal. It is just showing how Apache was started up.

Can you explain better what you mean by "For me, it seems like this only works when it is a localhost server and when it gets none localhost it stops working"?

Your first comment suggests you go it working with `mod_wsgi-express`, but don't know what you are doing when you later says it stops working.

Note that if you aren't using the system Apache for anything else, one option is to disable the system Apache and use `mod_wsgi-express` to host your application instead. This was part of the reason in asking you to try it.

**Comment by Pannakoek** [comment]
I have connected my Raspberry pi to my router and so I try to access the local IP address of the Raspberry pi/ the router (something like 192.168.1.107). I try to access the IP address with my pc. This works fine when I don't use OpenCV. When I use `mod_wsgi-express` I can only access the application from the raspberry pi. 

I would like to use the system apache so I can make it sort of web server without having to go to the Raspberry pi and starting it every time when I want to use it.

**Comment by GrahamDumpleton** [comment]
What is the full command line set of arguments you used for `mod_wsgi-express`? It should listen on all network interfaces by default and what application you are running should not matter.

**Comment by Pannakoek** [comment]
I was a bit to fast with the last post. I can access the `mod_wsgi-express` from a different pc.

![Untitled](https://user-images.githubusercontent.com/33670201/71023609-61580b80-2103-11ea-9302-c361c9893969.png)

Do I have to change the httpd.conf to use python 3.7 and my Django application? I am a little bit lost now about what to do.

**Comment by GrahamDumpleton** [comment]
It uses whatever Python version you ran the `pip install` against.

For Django see:

* http://blog.dscpl.com.au/2015/04/using-modwsgi-express-with-django.html
* http://blog.dscpl.com.au/2015/04/integrating-modwsgi-express-as-django.html

and also worthwhile watching:

* https://www.youtube.com/watch?v=CPz0s1CQsTE

**Comment by Pannakoek** [comment]
After watching and reading the links you gave me. I can import OpenCV without any errors and use it in my web application. At first, it was a bit confusing but after having read it all it was clear for me that apache is a lot harder than the mod_wsgi. This is maybe necessary for some people but for most of the hobbyists can use the links above about the mod_wsgi in pip. This was very easy to setup and run.

Thank you very much for explaining it to me. You are the best. Merry Xmas 🎅
