### ISSUE TITLE
installing mode_wsgi from source broke apache2

### ISSUE THREAD

**Issue by virasatkhan** [GrahamDumpleton/mod_wsgi#502]
Hi,

Can i get assistance with this please?

my mode_wsgi install from source from [https://github.com/GrahamDumpleton/mod_wsgi/archive/4.6.5.tar.gz] 

./configure --with-python=/usr/local/bin/python3.7
make install

Now when I restart httpd, it fails with below error.

server1:/app/ssSearch/downloads/mod_wsgi-4.6.5 # service httpd restart
Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.

server1:/app/ssSearch/downloads/mod_wsgi-4.6.5 # systemctl status apache2.service
â apache2.service - The Apache Webserver
   Loaded: loaded (/usr/lib/systemd/system/apache2.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-12-10 13:36:54 EST; 7s ago
  Process: 9159 ExecStop=/usr/sbin/start_apache2 -DSYSTEMD -DFOREGROUND -k graceful-stop (code=exited, status=1/FAILURE)
  Process: 9152 ExecStart=/usr/sbin/start_apache2 -DSYSTEMD -DFOREGROUND -k start (code=exited, status=1/FAILURE)
 Main PID: 9152 (code=exited, status=1/FAILURE)

Dec 10 13:36:54 dc2prentmonap01 start_apache2[9159]: [Tue Dec 10 13:36:54.109595 2019] [so:warn] [pid 9159] AH01574: module socache_shmcb_module is already loaded, skipping
Dec 10 13:36:54 dc2prentmonap01 start_apache2[9159]: [Tue Dec 10 13:36:54.109604 2019] [so:warn] [pid 9159] AH01574: module userdir_module is already loaded, skipping
Dec 10 13:36:54 dc2prentmonap01 start_apache2[9159]: [Tue Dec 10 13:36:54.110130 2019] [so:warn] [pid 9159] AH01574: module reqtimeout_module is already loaded, skipping
Dec 10 13:36:54 dc2prentmonap01 start_apache2[9159]: [Tue Dec 10 13:36:54.110146 2019] [so:warn] [pid 9159] AH01574: module authn_core_module is already loaded, skipping
Dec 10 13:36:54 dc2prentmonap01 start_apache2[9159]: [Tue Dec 10 13:36:54.110154 2019] [so:warn] [pid 9159] AH01574: module authz_core_module is already loaded, skipping
Dec 10 13:36:54 dc2prentmonap01 start_apache2[9159]: httpd-prefork: Syntax error on line 113 of /etc/apache2/httpd.conf: Syntax error on line 24 of /etc/apache2/loadmod... directory
Dec 10 13:36:54 dc2prentmonap01 systemd[1]: apache2.service: Control process exited, code=exited status=1
Dec 10 13:36:54 dc2prentmonap01 systemd[1]: Failed to start The Apache Webserver.
Dec 10 13:36:54 dc2prentmonap01 systemd[1]: apache2.service: Unit entered failed state.
Dec 10 13:36:54 dc2prentmonap01 systemd[1]: apache2.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by GrahamDumpleton** [comment]
And what is at line 24 of the config file it indicates?

If it is one of the mod_wsgi directives, you would get a syntax error if the wsgi_module hadn't been enabled.

**Comment by virasatkhan** [comment]
Any steps to fix that? Sorry I am new to hosting a Django app over my apache server. I am using python3.7, this machine already has python2.7,3.4 on it and has a working Django hosted over python3.7.


Thanks
- -Virasat
________________________________

**Comment by GrahamDumpleton** [comment]
As I asked, what is in the config file at that location? This may not be the issue and you may have just mucked up the arguments to the directive.

So provide details from both config files at the line numbers specified in the error messages.

**Comment by virasatkhan** [comment]
line#4 in loadmodule.conf is below


LoadModule wsgi_module                    /usr/lib64/apache2/mod_wsgi.so



Full config of this file is as below

server1:/etc/apache2 # cat loadmodule.conf
LoadModule actions_module                 /usr/lib64/apache2-prefork/mod_actions.so
LoadModule alias_module                   /usr/lib64/apache2-prefork/mod_alias.so
LoadModule auth_basic_module              /usr/lib64/apache2-prefork/mod_auth_basic.so
LoadModule authn_file_module              /usr/lib64/apache2-prefork/mod_authn_file.so
LoadModule authz_host_module              /usr/lib64/apache2-prefork/mod_authz_host.so
LoadModule authz_groupfile_module         /usr/lib64/apache2-prefork/mod_authz_groupfile.so
LoadModule authz_user_module              /usr/lib64/apache2-prefork/mod_authz_user.so
LoadModule autoindex_module               /usr/lib64/apache2-prefork/mod_autoindex.so
LoadModule cgi_module                     /usr/lib64/apache2-prefork/mod_cgi.so
LoadModule dir_module                     /usr/lib64/apache2-prefork/mod_dir.so
LoadModule env_module                     /usr/lib64/apache2-prefork/mod_env.so
LoadModule expires_module                 /usr/lib64/apache2-prefork/mod_expires.so
LoadModule include_module                 /usr/lib64/apache2-prefork/mod_include.so
LoadModule log_config_module              /usr/lib64/apache2-prefork/mod_log_config.so
LoadModule mime_module                    /usr/lib64/apache2-prefork/mod_mime.so
LoadModule negotiation_module             /usr/lib64/apache2-prefork/mod_negotiation.so
LoadModule setenvif_module                /usr/lib64/apache2-prefork/mod_setenvif.so
LoadModule ssl_module                     /usr/lib64/apache2-prefork/mod_ssl.so
LoadModule socache_shmcb_module           /usr/lib64/apache2-prefork/mod_socache_shmcb.so
LoadModule userdir_module                 /usr/lib64/apache2-prefork/mod_userdir.so
LoadModule reqtimeout_module              /usr/lib64/apache2-prefork/mod_reqtimeout.so
LoadModule authn_core_module              /usr/lib64/apache2-prefork/mod_authn_core.so
LoadModule authz_core_module              /usr/lib64/apache2-prefork/mod_authz_core.so
LoadModule wsgi_module                    /usr/lib64/apache2/mod_wsgi.so
LoadModule rewrite_module                 /usr/lib64/apache2/mod_rewrite.so

**Comment by GrahamDumpleton** [comment]
At a guess you may have some funny unicode character on that line which isn't showing which is triggering a syntax error.

Does though the file:

```
/usr/lib64/apache2/mod_wsgi.so
```

actually exist?

What do you get when you run:

```
ls -las /usr/lib64/apache2/mod_wsgi.so
```

and:

```
file /usr/lib64/apache2/mod_wsgi.so
```

**Comment by virasatkhan** [comment]
yes, the file exists.

server1:/usr/lib64/apache2 # ls -lrt | grep mod_wsgi
-rwxr-xr-x 1 root root 992104 Dec 10 13:12 mod_wsgi.so

server1:/usr/lib64/apache2 # ls -las mod_wsgi.so
972 -rwxr-xr-x 1 root root 992104 Dec 10 13:12 mod_wsgi.so

server1:/usr/lib64/apache2 # file /usr/lib64/apache2/mod_wsgi.so
/usr/lib64/apache2/mod_wsgi.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=06f1e5edad754cee6e73b49a5654776c1321fbcb, not stripped

**Comment by GrahamDumpleton** [comment]
Then as I said, you may just have a strange Unicode character on the line.

Delete the line:

```
LoadModule wsgi_module /usr/lib64/apache2/mod_wsgi.so
```

Restart Apache to see if at least gets beyond that.

Then manually type the line back in again the file and restart again.

**Comment by virasatkhan** [comment]
ok, let me actually do 2 things.

1) I did not restart my machine after installing mode_wsgi (for python3.7) - I will reboot the node first.
2) Will try your suggestion as well.


NOTE:: My intention was to install mod_wsgi for python3.7.. As I mentioned in my initial post, this node has [python2.7, python3.4] on it and had a working mod_wsgi for python2.7 as it had a working Django project that was developed in python2.7...The new project that I wanted to host is designed in python3.7 so I manually installed [python3.7 from source] got it working and ran my project with [manage.py runserver] under a virtualEnv and confirmed that it works.... Just that to host it on apache, I am doing these things and tried installing mod_wsgi for python3.7 which broke the apache itself.

**Comment by GrahamDumpleton** [comment]
Do you have system package for mod_wsgi installed? You cannot use a system package for mod_wsgi with a different version of Python than it was installed for. This is not the cause of this issue, but it will be a problem later if you try.

**Comment by virasatkhan** [comment]
I restarted the machine, will try your 2nd suggestion to manually edit that file.

The detailed error of my httpd service is below.


Dec 11 03:13:13 server1 start_apache2[4525]: httpd-prefork: Syntax error on line 113 of /etc/apache2/httpd.conf: Syntax error on line 24 of /etc/apache2/loadmodule.conf: Cannot load /usr/lib64/apache2/mod_wsgi.so into server: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory


How would I get this file 'libpython3.7m.so.1.0'

**Comment by GrahamDumpleton** [comment]
Read:

* https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#unable-to-find-python-shared-library

**Comment by virasatkhan** [comment]
I added below line into (etc/apache2/loadmodule.conf) and now the service seems to be coming without errors.

LoadFile /usr/local/lib/libpython3.7m.so.1.0


However, My actual problem is to host my code, do you think I can get some help on that.

**Comment by GrahamDumpleton** [comment]
The Django documentation covers using mod_wsgi.

* https://docs.djangoproject.com/en/2.2/howto/deployment/wsgi/modwsgi/

After you have gone through that and tried it, if you are having a specific problem which is related to mod_wsgi, then I may be able to help, but I can't guide you step by step.

**Comment by virasatkhan** [comment]
ok, I really appreciate your swift replied and assistance. is there a way I can revert back the changes I did for instlaling modwsgi for python3.7? Seems like the old code that was running good on python2.7 and may be previous modwsgi is breaking now.

**Comment by GrahamDumpleton** [comment]
As I mentioned above, mod_wsgi is compiled for a specific version. So if your code only works with Python 2.7, you can't use Python 3.7.

Easiest way is probably to do what you did to install mod_wsgi for Python 3.7, but use Python 2.7 instead. This should end up in just the `mod_wsgi.so` file being replaced. You need to remove that `LoadFile` line though.

Otherwise, remove the `mod_wsgi.so` file and re-install system package for mod_wsgi if that is what you were using before.

**Comment by virasatkhan** [comment]
okay, now that I have it for python37, i want to host my new code by editing the httpd.conf file. But I get a 'object nod found!' 404 error on browser. I have defug=true in my settings so was expecting atleast the 'Django's' pagenotFound with the endpoints from my app's url.py

**Below is what I edited on httpd.conf**

<Directory /srv/www/htdocs/monmetrics>
    Require all granted
</Directory>

Alias / /srv/www/htdocs/monmetrics/
Alias /favicon.ico /srv/www/htdocs/monmetrics/favicon.ico

WSGIScriptAlias / /srv/www/htdocs/monmetrics/monMetrics/wsgi.py
#WSGIPythonHome /srv/www/htdocs/monmetrics/myEnv/lib/python3.7/site-packages
WSGIPythonHome /srv/www/htdocs/monmetrics/myEnv
WSGIPythonPath /srv/www/htdocs/monmetrics


<Directory /srv/www/htdocs/monmetrics/monMetrics>
  <Files wsgi.py>
    Require all granted
  </Files>
</Directory>

<Directory /srv/www/htdocs/monmetrics/backend>
Require all granted
</Directory>

<Directory /srv/www/htdocs/monmetrics/myEnv>
Require all granted
</Directory>


<Directory /srv/www/htdocs/monmetrics>
Require all granted
</Directory>

<Directory /srv/www/htdocs/monmetrics/monMetrics>
Require all granted
</Directory>



**My Project Structure.**

server1:/srv/www/htdocs # tree -L 2 -p -A monmetrics/
monmetrics/
├── [drwxr-xr-x]  backend
│   ├── [-rwxr-xr-x]  __init__.py
│   ├── [-rwxr-xr-x]  admin.py
│   ├── [-rwxr-xr-x]  api.py
│   ├── [-rwxr-xr-x]  apps.py
│   ├── [drwxr-xr-x]  casd
│   ├── [drwxr-xr-x]  migrations
│   ├── [-rwxr-xr-x]  models.py
│   ├── [-rwxr-xr-x]  serializers.py
│   ├── [-rwxr-xr-x]  tests.py
│   ├── [-rwxr-xr-x]  urls.py
│   └── [-rwxr-xr-x]  views.py
├── [-rwxr-xr-x]  db.sqlite3
├── [-rwxr-xr-x]  favicon.ico
├── [-rwxr-xr-x]  manage.py
├── [drwxr-xr-x]  monMetrics
│   ├── [-rwxr-xr-x]  __init__.py
│   ├── [-rwxr-xr-x]  settings.py
│   ├── [-rwxr-xr-x]  urls.py
│   └── [-rwxr-xr-x]  wsgi.py
└── [drwxr-xr-x]  myEnv
    ├── [drwxr-xr-x]  bin
    ├── [drwxr-xr-x]  cx_Oracle-doc
    ├── [drwxr-xr-x]  include
    └── [drwxr-xr-x]  lib

**Comment by GrahamDumpleton** [comment]
Ensure Apache error log level is `info` and not `warn` or `err`. Then error log will show extra messages from mod_wsgi about loading stuff so can see if WSGI script file was even being loaded. If you are seeing a generic Apache 404, likely that wasn't even occurring.

BTW, read up about using mod_wsgi daemon mode and not embedded mode. Daemon mode is recommended over embedded mode.

Watch:

*  https://www.youtube.com/watch?v=H6Q3l11fjU0

Also see how to use virtual environments with daemon mode at:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by virasatkhan** [comment]
Hi Graham - Very cool ppt on youtube. I am feeling embarrassed to come back to you with again with silly queries (I am new to this).

I get a 403 forbidden error when I hit (http://server1/)


Have included things in a vhosts.d folder as [monMetrics.conf] and included this into the main [httpd.conf] file.



<VirtualHost *:80>

    ServerName server1
    ServerAlias somealias.com
    ServerAdmin email@somealias.com

    DocumentRoot /srv/www/htdocs/monMetrics

    Alias / /srv/www/htdocs/monMetrics
    Alias /favicon.ico /srv/www/htdocs/monMetrics/favicon.ico


    <Directory /srv/www/htdocs/monMetrics>
        Require all granted
    </Directory>

    WSGIDaemonProcess monMetrics processes=2 threads=15 python-path=/srv/www/htdocs/monMetrics python-home=/app/ssSearch/myEnv display-name=%{GROUP}
    WSGIProcessGroup monMetrics

    WSGIScriptAlias / /srv/www/htdocs/monMetrics/monMetrics/wsgi.py

    <Directory /srv/www/htdocs/monMetrics/monMetrics>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

</VirtualHost>

**Comment by virasatkhan** [comment]
forgot to mention, you did a pretty awesome job by presenting about mod_wsgi. I was able to use the runmodwsgi command to host a dev site of my work. Just exploring ways to use the same way for production.


**Below is the output of my command that gets me my page on port 8000**

(myEnv) mirviraa@server1:/srv/www/htdocs/monMetrics> python manage.py runmodwsgi
Successfully ran command.
Server URL         : http://localhost:8000/
Server Root        : /tmp/mod_wsgi-localhost:8000:8026
Server Conf        : /tmp/mod_wsgi-localhost:8000:8026/httpd.conf
Error Log File     : /tmp/mod_wsgi-localhost:8000:8026/error_log (warn)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8

**Comment by virasatkhan** [comment]
I was able to crack it after going through some detailed docs and steps. Thank Graham for your immediate attention to this.
