### ISSUE TITLE
Parallel python with Ray

### ISSUE THREAD

**Issue by duke08542** [GrahamDumpleton/mod_wsgi#503]
Hi Graham and everybody, 

I'm running apache2.4.x + mod_wsgi and serving up django - things works fine until I added Ray to parallelize things. I'm not even sure where to put the initialisation of ray, tried a few places (wsgi.py, setting.py, manage.py) with little success

AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 mod_wsgi/4.5.17 Python/3.6 configured -- resuming normal operations
[Fri Dec 13 21:20:43.310473 2019] [core:notice] [pid 26708:tid 140027405441984] AH00094: Command line: '/usr/sbin/apache2'
[Fri Dec 13 21:20:57.322949 2019] [wsgi:error] [pid 26710:tid 140027176380160] 2019-12-13 21:20:57,322\tINFO resource_spec.py:205 -- Starting Ray with 3.12 GiB memory available for workers and up to 1.56 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
[Fri Dec 13 21:20:57.594351 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282] mod_wsgi (pid=26710): Target WSGI script '/var/www/esdpi/yunbao/wsgi.py' cannot be loaded as Python module.
[Fri Dec 13 21:20:57.594481 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282] mod_wsgi (pid=26710): Exception occurred processing WSGI script '/var/www/esdpi/yunbao/wsgi.py'.
[Fri Dec 13 21:20:57.596215 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282] Traceback (most recent call last):
[Fri Dec 13 21:20:57.596277 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282]   File "/var/www/esdpi/yunbao/wsgi.py", line 17, in <module>
[Fri Dec 13 21:20:57.596290 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282]     ray.init()
[Fri Dec 13 21:20:57.596313 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282]   File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1383, in init
[Fri Dec 13 21:20:57.596324 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282]     job_id=job_id)
[Fri Dec 13 21:20:57.596342 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282]   File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1662, in connect
[Fri Dec 13 21:20:57.596352 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282]     faulthandler.enable(all_threads=False)
[Fri Dec 13 21:20:57.596399 2019] [wsgi:error] [pid 26710:tid 140027176380160] [remote 192.168.14.41:60282] OSError: Apache/mod_wsgi log object is not associated with a file descriptor. 

Have anyone tried ray with mod_wsgi before  that could point me in the right direction ?  Thank you.

**Comment by GrahamDumpleton** [comment]
No idea what Ray is to start with, and you have said nothing about how you have configured Apache/mod_wsgi.

Not sure what package `faulthandler` is from, but it appears to not be tolerant of `sys.stdout` or `sys.stderr` not being associated with a file descriptor.

Can you provide more information on Ray, where `faulthandler` comes from or is used, and what the mod_wsgi configuration you used is?

**Comment by GrahamDumpleton** [comment]
No further follow up so closing issue.
