### ISSUE TITLE
Pip error installing mod_wsgi in venv in Windows

### ISSUE THREAD

**Issue by antoniovazquezblanco** [GrahamDumpleton/mod_wsgi#506]
I have tryed the following steps with Python 3.6.9 and 3.8.1 with the same result.

1. Create a virtual environment using native tools: `python -m venv venv`
2. Install mod_wsgi: `pip install mod_wsgi`

I get the following error:
```
LINK : fatal error LNK1181: cannot open input file 'c:\users\...\venv\scripts\libs\python38.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\...\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\...\\AppData\\Local\\Temp\\2\\pip-install-8v1pvtlx\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\...\\AppData\\Local\\Temp\\2\\pip-install-8v1pvtlx\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\...\AppData\Local\Temp\2\pip-record-tg0_yk9u\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\...\venv\include\site\python3.8\mod-wsgi' Check the logs for full command output.
```

Effectively, `venv` does not create `venv\scripts\libs\python38.lib`. I don't know if this is a bug in `venv` tools or in `mod_wsgi`.

**Comment by GrahamDumpleton** [comment]
Try using virtualenv instead.

For whatever reason, the bundled way of creating virtual environments changed where the Python library is added into the virtual environment, or stopped adding it all together. A change is needed to the `setup.py` file of mod_wsgi to have it check other directories where it might be, but no one has supplied a patch for that. I don't have access to Windows to work it out myself.

**Comment by antoniovazquezblanco** [comment]
From what I can see in my virtual environmet, that file is not present anywhere. I believe that using system wide libs to compile this package is not the intended way to proceed. This looks like should be discussed in venv bugtracker.

https://bugs.python.org/issue39226?@ok_message=msg%20359388%20creado%0Aissue%2039226%20creado&@template=item

**Comment by vsajip** [comment]
The `python38.lib` file isn't present in any venv, whether created by `virtualenv` or `python -m venv`. I believe the build process may not cater for building in a venv on Windows.

When created with `python -m venv`, a venv contains the file `pyvenv.cfg` with contents like this:
```
home = C:\Users\Vinay\AppData\Local\Programs\Python\Python38
include-system-site-packages = false
version = 3.8.1
```
and the location of python38.lib on this system is given by the `libs` directory relative to the `home` value in the above snippet.

I don't think this is a venv bug so I will probably close the Python issue soon.

**Comment by antoniovazquezblanco** [comment]
A PR fixing the issue was opened in https://github.com/GrahamDumpleton/mod_wsgi/pull/509

**Comment by bazhenov4job** [comment]
Successfully applied <a href="https://github.com/GrahamDumpleton/mod_wsgi/pull/509">#509</a> contributed by <a href=https://github.com/antoniovazquezblanco>antoniovazquezblanco</a> on my win10 x64 with pip 20.2 and python 3.7.3!

**Comment by GrahamDumpleton** [comment]
Try:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

**Comment by antoniovazquezblanco** [comment]
Merged in ffbdfaa

Should we close this?

**Comment by GrahamDumpleton** [comment]
Use mod_wsgi 4.7.1 or later.

**Comment by antoniovazquezblanco** [comment]
Thanks!
