### ISSUE TITLE
Problems with mod_wsgi on Windows when using Apache as a service

### ISSUE THREAD

**Issue by dmorosi** [GrahamDumpleton/mod_wsgi#507]
Hi, I'm trying to use Apache 2.4 (apache lounge version, httpd-2.4.41-win64-VS16 on Windows Server 2012 R2 Standard, python 3.7) with mod_wsgi and Django.
If I run httpd manually, it's working also if I get two very quick windows appearing when I start the server (see attachments).
![img_1](https://user-images.githubusercontent.com/12411166/71914998-1ae25380-317b-11ea-96fb-c3cc7acd425d.png)
![img_2](https://user-images.githubusercontent.com/12411166/71914999-1ae25380-317b-11ea-8988-c7acc19bb2a1.png)

Instead, if I run Apache as a windows service, the process seems to run but the windows aren't appearing at all and the service get stuck at the first request, without any error, trying to load the django wsgi.py.
Do you have any suggestion?

Thanks
Damiano

**Comment by GrahamDumpleton** [comment]
You will not get any windows come up if running as a daemon.

If you have just the one web application, ensure that you have:

```
WSGIApplicationGroup %{GLOBAL}
```

You also need to ensure that whatever user the Apache service runs as, has access to the files/directories where your application code is, including write access if you have file system based databases such as SQLite.

**Comment by dmorosi** [comment]
Hi Graham,

thank you so much for your guidance, I totally missed this configuration. I've managed to configure two different django applications using this directive :)
