### ISSUE TITLE
 Import issue/target WSGI script cannot be loaded as Python module

### ISSUE THREAD

**Issue by murthyn** [GrahamDumpleton/mod_wsgi#508]
Hello,

I am getting the following errors:

```
mod_wsgi (pid=9822): Target WSGI script '/var/www/html/api/api.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=9822): Exception occurred processing WSGI script '/var/www/html/api/api.wsgi'.
Traceback (most recent call last):
File "/var/www/html/api/api.wsgi", line 3, in <module>
from api import app as application
File "/var/www/html/api/api.py", line 7, in <module>
from flask_cors import CORS
ImportError: No module named flask_cors
```
I have installed `flask_cors` through pip (`pip install -U flask-cors`), see that it is in fact in `/home/ubuntu/.local/lib/python2.7/site-packages` which is in turn in `sys.path`. Any help would be appreciated!

Details:
OS: Ubuntu 18.04.3 LTS
Python: 2.7.17
Apache: 2.4.29
Flask: 1.1.1

**Comment by GrahamDumpleton** [comment]
Apache runs as it’s own user and will ignore your per user site packages directory. Use a virtual environment for packages instead and point mod_wsgi at that.

**Comment by murthyn** [comment]
Thank you for the quick reply! I created a virtual environment through `virtualenv` and edited the configuration file (`/etc/apache2/sites-enabled/000-default.conf`) to contain the line:
```
WSGIDaemonProcess api threads=5 python-home=/home/ubuntu/flask_env
```
instead of
```
WSGIDaemonProcess api threads=5
```
where `flask_env` is the name of my virtual environment (and contains `flask` and `flask_cors`).

I still get the same error, including the line `ImportError: No module named flask_cors`.

**Comment by GrahamDumpleton** [comment]
When under a home directory it may not be readable if the permissions on the home directory don’t allow read access to others. 

What are the permissions on the home directory.

**Comment by GrahamDumpleton** [comment]
Also, do you have a WSGIProcess directive to tell it to use that daemon process group?

**Comment by murthyn** [comment]
The permissions for `flask_env` are `drwxrwxr-x`, which looks fine to me. 

In the configuration file, I have the line `WSGIProcessGroup api` under `<Directory api>`.

**Comment by GrahamDumpleton** [comment]
Not the virtual environment. The ubuntu home directory

**Comment by murthyn** [comment]
Sorry about that - the permissions are `drwxr-xr-x`

**Comment by GrahamDumpleton** [comment]
Add to your Apache configuration (outside of all VirtualHost definitions:

```
WSGIRestrictEmbedded On
```

This will result in errors if requests are not being handled in daemon mode, and so ensure that any configuration is correctly delegating requests to the daemon process you configured.

**Comment by GrahamDumpleton** [comment]
No further queries about this, so assuming you worked it out or gave up.
