### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding mod_wsgi Apache2.4.29 mod_wsgi 4.7.0 Python3.6.9 django2.2

### ISSUE THREAD

**Issue by mrsaw12** [GrahamDumpleton/mod_wsgi#510]
Hi Guys,

i'm not sure if this related to mod_wsgi, but i guess it isn't an error by apache or python.

I get following error if i try to run a django project with mod_wsgi:

```log
Current thread 0x00007f6452772bc0 (most recent call first):
[Thu Jan 09 21:05:05.557086 2020] [core:notice] [pid 6500] AH00051: child pid 6523 exit signal Aborted (6), possible coredump in /etc/apache2
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```
I read about this error much, and all users wrote, that this error happen if:
a) python version is wrong / different to virtualenv
b) you have wrong file permissions.

a) i'm under ubuntu and tried first to install mod_wsgi trough apt by using:
```shell
apt install libapache2-mod-wsgi-py3
```
**not worked.**

After that i tried to compile new mod_wsgi (version 4.70 also 4.6.5)
```shell
./configure --with-python=/usr/bin/python3
make
make install
```
**not worked.**

Of course i tried to create a new Virtual Environment with same python Version:

```shell
virtualenv -p /usr/bin/python3 myenv
```
**still same error.**

Following my System & Configuration details:

System:
```log
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

Apache running with:
```log
AH00163: Apache/2.4.29 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1d mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
```

Vhost config file:
```config
VirtualHost 172.16.200.250:80>
        ServerAdmin blabla@blabla.com
       ServerName localdomain.local
        SuexecUserGroup user1 user1

        #Normaler Modus:
        DocumentRoot "/var/www/user1/docs/"

        Alias /static /var/www/user1/docs/myenv/myproject/static
        <Directory /var/www/user1/docs/myenv/myproject/static>
        Require all granted
        </Directory>

        Alias /media /var/www/user1/docs/myenv/myproject/media
        <Directory /var/www/user1/docs/myenv/myproject/media>
        Require all granted
        </Directory>

        <Directory /var/www/user1/docs/myenv/myproject/myproject>
        <Files wsgi.py>
        Require all granted
        </Files>
        </Directory>

    WSGIDaemonProcess myproject python-path=/var/www/user1/docs/myenv python-home=/var/www/user1/docs/myenv/myproject/myproject
    WSGIProcessGroup myproject
    WSGIScriptAlias / /var/www/user1/docs/myenv/myproject/myproject/wsgi.py
        DirectoryIndex index.htm index.html index.php

        ErrorLog /var/www/user1/logs/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog /var/www/user1/logs/access.log combined
        ServerSignature Off

</VirtualHost>
```

Python Version is 3.6.9
```shell
(myenv) user1@xserver:~/docs/myenv$ python -V
Python 3.6.9
```

Permissions
www-data has access to user1 / added to group
i also tried to to change owner to www-data or give full write access with 77

```shell
chown www-data:www-data -R  /var/www/user1/docs/myenv
chmod 777 -R /var/www/user1/docs/myenv
```

If i start the django project directly trough runserver, it works fine. so i guess it's not a python issue.

```shell
(myenv) user1@xserver:~/docs/myenv/myproject$ ./manage.py runserver 172.16.200.250:10000
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 09, 2020 - 20:03:10
Django version 2.2.8, using settings 'myproject.settings'
Starting development server at http://172.16.200.250:10000/
Quit the server with CONTROL-C.
[09/Jan/2020 20:03:12] "GET / HTTP/1.1" 200 16348
```

I'm of course created clear ENV & django project from scratch. 
**still same error.**

And the most weird thing is, that i have a second Ubuntu System (production System) that is live  and i have not this error. So i don't have any idea what's the problem is.

**Comment by GrahamDumpleton** [comment]
This appears wrong:

```
python-home=/var/www/user1/docs/myenv/myproject/myproject
```

The `python-home` option is meant to refer to the root of the virtual environment. That is, the value of `sys.prefix` as given by Python run against that virtual environment. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#location-of-the-virtual-environment

**Comment by mrsaw12** [comment]
WOW, you are right... this is so crazy, i lost 2 days because i mixed up python-path && python-home!

i set to **python-path** the path to ~~**Environment**~~ (what is wrong)
and **python-home** the path to  ~~**django project** ~~ (what is wrong too)

it's the other way around

correct in my case is:

```config
WSGIDaemonProcess myproject python-path=/var/www/user1/docs/myenv/myproject python-home=/var/www/user1/docs/myenv
```
I'm so sorry for taking your time for this stupid mistake.
