### ISSUE TITLE
Target WSGI script  cannot be loaded as Python module

### ISSUE THREAD

**Issue by antuaneacion** [GrahamDumpleton/mod_wsgi#512]
hi, i have the same issue and still cant resolve. im trying to deploy django app with apache on window server, and this is my firts time

Complete error log :
[Wed Jan 15 14:48:37.373954 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781] mod_wsgi (pid=5696): Target WSGI script 'C:/Users/Administrator/Documents/Atenpo/atenpo/atenpo/wsgi.py' cannot be loaded as Python module.
[Wed Jan 15 14:48:37.373954 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781] mod_wsgi (pid=5696): Exception occurred processing WSGI script 'C:/Users/Administrator/Documents/Atenpo/atenpo/atenpo/wsgi.py'.
[Wed Jan 15 14:48:37.375946 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781] Traceback (most recent call last):\r
[Wed Jan 15 14:48:37.375946 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "C:/Users/Administrator/Documents/Atenpo/atenpo/atenpo/wsgi.py", line 18, in <module>\r
[Wed Jan 15 14:48:37.375946 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]     application = get_wsgi_application()\r
[Wed Jan 15 14:48:37.375946 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\django-2.2.8-py3.7.egg\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Wed Jan 15 14:48:37.375946 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]     django.setup(set_prefix=False)\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\django-2.2.8-py3.7.egg\\django\\__init__.py", line 19, in setup\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\django-2.2.8-py3.7.egg\\django\\conf\\__init__.py", line 79, in __getattr__\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]     self._setup(name)\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\django-2.2.8-py3.7.egg\\django\\conf\\__init__.py", line 66, in _setup\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]     self._wrapped = Settings(settings_module)\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\django-2.2.8-py3.7.egg\\django\\conf\\__init__.py", line 157, in __init__\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]     mod = importlib.import_module(self.SETTINGS_MODULE)\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\importlib\\__init__.py", line 127, in import_module\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked\r
[Wed Jan 15 14:48:37.376943 2020] [wsgi:error] [pid 5696:tid 1224] [client 172.16.3.182:51781] ModuleNotFoundError: No module named 'atenpo'\r

**Comment by GrahamDumpleton** [comment]
You likely haven't set `WSGIPythonPath` correctly. Check again the Django documentation.

* https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/modwsgi/

You should be using:

```
WSGIPythonPath C:/Users/Administrator/Documents/Atenpo/atenpo
```

Ensure you forward slashes, not backward slashes.

**Comment by antuaneacion** [comment]
hi , thanks a lot for dedicated a time for my issue, i tried this before and give me this error 

AH00526: Syntax error on line 554 of C:/Apache24/conf/httpd.conf:
WSGIPythonPath cannot occur within <VirtualHost> section

**Comment by antuaneacion** [comment]
thanks so much you were right,  the problem was that  i place the
WSGIPythonPath inside de <virtualhost> section, after set outside of this
section everything went well.
thanks so much for the help
