### ISSUE TITLE
WSGIDaemonProcess not allowed in <If>

### ISSUE THREAD

**Issue by mlcdf** [GrahamDumpleton/mod_wsgi#513]
Hello Graham,

I would like to define a WSGI Daemon Process only if a file exist.
But, whenever I try to put a WSGIDaemonProcess inside a `<If>`, I get the following error :
```
WSGIDaemonProcess not allowed here
```
Why this limitation?
How can I do to only defined a WSGIDaemonProcess if a file exist?

Maxime

**Comment by GrahamDumpleton** [comment]
Sorry for the delay, been travelling and this slipped away in my inbox.

The short answer is that ``WSGIDaemonProcess`` cannot be defined in `File` or `Directory` scope and only at `VirtualHost` scope or main server scope. The daemon processes must be defined up front when the server starts/restarts. They cannot be started dynamically later.

Provided your file exists when the server starts, you may be able to use the `IfFile` directive.

* https://httpd.apache.org/docs/2.4/mod/core.html#iffile

I have never used it to do that so not sure.

As well as `If` directives, if needing to template things, you may find `mod_macro` useful.

* https://httpd.apache.org/docs/2.4/mod/mod_macro.html

**Comment by GrahamDumpleton** [comment]
You might also consider using `IncludeOptional`.

* https://httpd.apache.org/docs/2.4/mod/core.html#includeoptional

BTW, when say `IfFile` might works, still means having to have it at `VirtualHost` or main server scope.

When you said you were using `<If>`, didn't know if really meant `<If>`, or using `<IfFile>`, but then what scope you have it at is also important and you don't say what that is.

**Comment by mlcdf** [comment]
Thank you very much for getting back to me!

Well, the thing is `WSGIDaemonProcess` is not defined in a `File` or `Directory` scope.

I'll trying the explain the resoning behind my question. I have the following file localed in `/etc/httpd/flask.conf`:
```
# Previous version
WSGIDaemonProcess foobar_prev user=foobar group=foobar home=/foobar/www_prev/python display-name=flask-api-prev umask=0002
WSGIPassAuthorization On
WSGIScriptAlias /api_prev /foobar/www_prev/python/main.wsgi
LogLevel Info
<Directory "/foobar/www_prev/python/api">
        WSGIProcessGroup foobar_prev
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
</Directory>

# Next version
WSGIDaemonProcess foobar_next user=foobar group=foobar home=/foobar/www_next/python display-name=flask-api-next umask=0002
WSGIPassAuthorization On
WSGIScriptAlias /api_next /foobar/www_next/python/main.wsgi
LogLevel Info
<Directory "/foobar/www_next/python/api">
        WSGIProcessGroup foobar_next
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
</Directory>

# Debug version
[...]
```
It works fine. This file is stored in a git repository and it is used on multiples servers.

But, on some servers, there is no `yolo/www_next` directory. So to prevent Apache from trying indefinitely to start `yolo_next`, I wanted to defined `WSGIDaemonProcess yolo_next` only if `/yolo/www_next/python/main.wsgi` exists:
```
<If "-f '/foobar/www_prev/python/main.wsgi'">
        WSGIDaemonProcess foobar_prev user=foobar group=foobar home=/w8h/www_prev/python display-name=flask-api-prev umask=0002
        WSGIPassAuthorization On
        WSGIScriptAlias /api_prev /foobar/www_prev/python/main.wsgi
        LogLevel Info
        <Directory "/foobar/www_prev/python/api">
                WSGIProcessGroup foobar_prev
                WSGIApplicationGroup %{GLOBAL}
                Require all granted
        </Directory>
</If>
```
And when I `systemctl reload httpd`, I get this:
```
AH00526: Syntax error on line 7 of /etc/httpd/conf.d/flask.conf:
WSGIDaemonProcess not allowed here
httpd.service: control process exited, code=exited status=1
Reload failed for The Apache HTTP Server.
```
Hence my initial question.

The only thing I did was adding `<If "-f '/foobar/www_prev/python/main.wsgi'"></If>`.

Maybe I'm approaching the problem the wrong way. Also, I'm not sure I need to duplicate `WSGIPassAuthorization On` each time.
