### ISSUE TITLE
runmodwsgi on port other than 80

### ISSUE THREAD

**Issue by VenkateshDharavath** [GrahamDumpleton/mod_wsgi#516]
hello,
I'm trying to deploy my Django application on VPS with mod_wsgi-express. I've installed mod_wsgi-httpd, mod_wsgi and I'm gonna run server with command `python manage.py runmodwsgi --setup-only --port --user --group --server-root`. how can I run server on any port other than 80 and get the Django application served when I type my domain name?
eg:  if I use port 80: `mydomain.com` will get Django served.
if I use any other port, 8000: `mydomain.com:8000` works but not `mydomain.com`.

I want to run a mod_wsgi server on any port other than 80 but the Django app should appear by typing just domain name without port number.
please help me.

**Comment by GrahamDumpleton** [comment]
By itself you can't do that as the standard for HTTP is that if no port is supplied a client must use port 80.

The only way you could do this is to configure whatever web server your VPS has that is running on port 80, to proxy requests through to the separate mod_wsgi-express instance running on the non privileged port.

For a bit of information about setting up a proxy to direct requests to mod_wsgi-express, see:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

Ignore that it talks about proxying to mod_wsgi-express running in a docker container, it is all still relevant.
