### ISSUE TITLE
WSGIDaemonProcess - "memory-limit"

### ISSUE THREAD

**Issue by gdciria** [GrahamDumpleton/mod_wsgi#517]
"memory-limit" Default value in MB, GB, KB...?

I did not find the information in that topic:
https://github.com/GrahamDumpleton/mod_wsgi/issues/197

How can I test if mod_wsgi is working with the values?

WSGIDaemonProcess maximum-requests=160 memory-limit=650000000    # I would like to test
WSGIScriptAlias (...)

Thanks

**Comment by GrahamDumpleton** [comment]
There are two options, you need to know which is going to work on your platform. From:

* https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html

**memory-limit=num**
> Sets the maximum amount of memory a daemon process can use. This will have no affect on some platforms as RLIMIT_AS/RLIMIT_DATA with setrlimit() isn’t always implemented. For example MacOS X and older Linux kernel versions do not implement this feature. You will need to test whether this feature works or not before depending on it.

**virtual-memory-limit=num**
> Sets the maximum amount of virtual memory a daemon process can use. This will have no affect on some platforms as RLIMIT_VMEM with setrlimit() isn’t always implemented. You will need to test whether this feature works or not before depending on it.

As to how you can know if it works, you would need to allocate a huge amount of memory above the limit and see if the application gives an error, or perhaps crashes, as memory exhaustion doesn't always result in a clean result.

You can create a large memory allocation by going:

```
s = 650000000*'x'
```

Units is determined by whatever ``setrlimit()`` uses, which I presume is bytes.

* https://linux.die.net/man/2/setrlimit

BTW, ``maxuimum-requests`` of such a low value is bad in a production system. The periodic process restarts under load will affect performance badly.

**Comment by gdciria** [comment]
Graham, thank's for your time.

Now i understand how the parameter is communicated with Linux. 
It helped a lot.

Sorry for my English. I'm brazilian.

**Comment by gdciria** [comment]
Graham, edit:

To check if it's working in Linux (Kernel: 4.x):

**# python.conf**
WSGIDaemonProcess localhost maximum-requests=600 memory-limit=600000000

**# service httpd graceful**

**# ps ax | grep http** 
2333 ?        Sl     0:00 /usr/sbin/httpd

**# cat /proc/2333/limits | grep -i memory**
Max data size             600000000           600000000           bytes

Thanks.
