### ISSUE TITLE
Redirection not done from http to https

### ISSUE THREAD

**Issue by shelza1305** [GrahamDumpleton/mod_wsgi#521]
I have done each step first I create xyz.conf file and then I create default-ssl.conf and put certificate in that file.then enable ssl and default-ssl.conf.

But the problem redirection is not possible?

**Comment by GrahamDumpleton** [comment]
Impossible to provide any advice without knowing what you have defined the virtual hosts as, which files the definitions are in, and whether you have actually enabled properly any site file so it is being read in and used.

**Comment by shelza1305** [comment]
sorry ...i have not attached file

Please check my wellbeing.conf:
<VirtualHost *:80>
    ServerName abc.org
    ServerAlias www.abc.org

    
    
    ErrorLog ${APACHE_LOG_DIR}/mysite-error.log
    CustomLog ${APACHE_LOG_DIR}/mysite-access.log combined

    WSGIDaemonProcess new_project python-path=/var/www/html/wellbeing_folder/wellbeing_project  python-home=/var/www/html/wellbeing_folder/myvenv/
    WSGIApplicationGroup %{GLOBAL}
    WSGIProcessGroup new_project
    WSGIScriptAlias / /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_project/wsgi.py
    Alias /static  /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_app/static
    Alias /.well-known /var/www/html/wellbeing_folder/wellbeing_project/.well-known

<Directory />
    #Options FollowSymLinks
    Options Indexes FollowSymLinks
    Require all granted
</Directory>
<Directory /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_project/>
        <Files wsgi.py>
            Require all granted
        </Files>
</Directory>
<Directory /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_app/static/>
      Require all granted
</Directory>





</VirtualHost>



And default-ssl.conf:

<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin webmaster@localhost
        ServerName abc.org
        ServerAlias www.abc.org
		DocumentRoot /var/www/html

		# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
		# error, crit, alert, emerg.
		# It is also possible to configure the loglevel for particular
		# modules, e.g.
		#LogLevel info ssl:warn

		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		# For most configuration files from conf-available/, which are
		# enabled or disabled at a global level, it is possible to
		# include a line for only one particular virtual host. For example the
		# following line enables the CGI configuration for this host only
		# after it has been globally disabled with "a2disconf".
		#Include conf-available/serve-cgi-bin.conf

		#   SSL Engine Switch:
		#   Enable/Disable SSL for this virtual host.
		SSLEngine on

		#   A self-signed (snakeoil) certificate can be created by installing
		#   the ssl-cert package. See
		#   /usr/share/doc/apache2/README.Debian.gz for more info.
		#   If both key and certificate are stored in the same file, only the
		#   SSLCertificateFile directive is needed.
		SSLCertificateFile	/etc/apache2/ssl/www.abc.org.crt
		SSLCertificateKeyFile  /etc/apache2/ssl/www.abc.org.key

		#   Server Certificate Chain:
		#   Point SSLCertificateChainFile at a file containing the
		#   concatenation of PEM encoded CA certificates which form the
		#   certificate chain for the server certificate. Alternatively
		#   the referenced file can be the same as SSLCertificateFile
		#   when the CA certificates are directly appended to the server
		#   certificate for convinience.
		SSLCertificateChainFile /etc/apache2/ssl/www.abc.org.ca-bundle

		#   Certificate Authority (CA):
		#   Set the CA certificate verification path where to find CA
		#   certificates for client authentication or alternatively one
		#   huge file containing all of them (file must be PEM encoded)
		#   Note: Inside SSLCACertificatePath you need hash symlinks
		#		 to point to the certificate files. Use the provided
		#		 Makefile to update the hash symlinks after changes.
		#SSLCACertificatePath /etc/ssl/certs/
		#SSLCACertificateFile /etc/apache2/ssl.crt/ca-bundle.crt

		#   Certificate Revocation Lists (CRL):
		#   Set the CA revocation path where to find CA CRLs for client
		#   authentication or alternatively one huge file containing all
		#   of them (file must be PEM encoded)
		#   Note: Inside SSLCARevocationPath you need hash symlinks
		#		 to point to the certificate files. Use the provided
		#		 Makefile to update the hash symlinks after changes.
		#SSLCARevocationPath /etc/apache2/ssl.crl/
		#SSLCARevocationFile /etc/apache2/ssl.crl/ca-bundle.crl

		#   Client Authentication (Type):
		#   Client certificate verification type and depth.  Types are
		#   none, optional, require and optional_no_ca.  Depth is a
		#   number which specifies how deeply to verify the certificate
		#   issuer chain before deciding the certificate is not valid.
		#SSLVerifyClient require
		#SSLVerifyDepth  10

		#   SSL Engine Options:
		#   Set various options for the SSL engine.
		#   o FakeBasicAuth:
		#	 Translate the client X.509 into a Basic Authorisation.  This means that
		#	 the standard Auth/DBMAuth methods can be used for access control.  The
		#	 user name is the `one line' version of the client's X.509 certificate.
		#	 Note that no password is obtained from the user. Every entry in the user
		#	 file needs this password: `xxj31ZMTZzkVA'.
		#   o ExportCertData:
		#	 This exports two additional environment variables: SSL_CLIENT_CERT and
		#	 SSL_SERVER_CERT. These contain the PEM-encoded certificates of the
		#	 server (always existing) and the client (only existing when client
		#	 authentication is used). This can be used to import the certificates
		#	 into CGI scripts.
		#   o StdEnvVars:
		#	 This exports the standard SSL/TLS related `SSL_*' environment variables.
		#	 Per default this exportation is switched off for performance reasons,
		#	 because the extraction step is an expensive operation and is usually
		#	 useless for serving static content. So one usually enables the
		#	 exportation for CGI and SSI requests only.
		#   o OptRenegotiate:
		#	 This enables optimized SSL connection renegotiation handling when SSL
		#	 directives are used in per-directory context.
		#SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		#   SSL Protocol Adjustments:
		#   The safe and default but still SSL/TLS standard compliant shutdown
		#   approach is that mod_ssl sends the close notify alert but doesn't wait for
		#   the close notify alert from client. When you need a different shutdown
		#   approach you can use one of the following variables:
		#   o ssl-unclean-shutdown:
		#	 This forces an unclean shutdown when the connection is closed, i.e. no
		#	 SSL close notify alert is send or allowed to received.  This violates
		#	 the SSL/TLS standard but is needed for some brain-dead browsers. Use
		#	 this when you receive I/O errors because of the standard approach where
		#	 mod_ssl sends the close notify alert.
		#   o ssl-accurate-shutdown:
		#	 This forces an accurate shutdown when the connection is closed, i.e. a
		#	 SSL close notify alert is send and mod_ssl waits for the close notify
		#	 alert of the client. This is 100% SSL/TLS standard compliant, but in
		#	 practice often causes hanging connections with brain-dead browsers. Use
		#	 this only for browsers where you know that their SSL implementation
		#	 works correctly.
		#   Notice: Most problems of broken clients are also related to the HTTP
		#   keep-alive facility, so you usually additionally want to disable
		#   keep-alive for those clients, too. Use variable "nokeepalive" for this.
		#   Similarly, one has to force some clients to use HTTP/1.0 to workaround
		#   their broken HTTP/1.1 implementation. Use variables "downgrade-1.0" and
		#   "force-response-1.0" for this.
		# BrowserMatch "MSIE [2-6]" \
		#		nokeepalive ssl-unclean-shutdown \
		#		downgrade-1.0 force-response-1.0

	</VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet


Also enabled ssl and dfeault-ssl.conf

**Comment by GrahamDumpleton** [comment]
If you mean your problem is that accessing the site as ``http://www.abc.org`` doesn't redirect to ``https://www.abc.org`` then it is because you don't have anything in the Apache config to trigger a redirect.

But then, if you did add the directives into the ``VirtualHost`` for port 80 to redirect to HTTPS, you don't have the WSGI application defined in the ``VirtualHost`` for port 443.

You also shouldn't be adding stuff to the default ``VirtualHost`` for port 443 anyway, create a new ``VirtualHost`` for port 443 and your server name in your ``wellbeing.conf`` file.

So remove the ``ServerName`` and ``ServerAlias`` from the defult ``VirtualHost`` for port 443 and then use something like the following in ``wellbeing.conf``.

```
<VirtualHost *:443>
    ServerName abc.org
    ServerAlias www.abc.org

		#   SSL Engine Switch:
		#   Enable/Disable SSL for this virtual host.
		SSLEngine on

		#   A self-signed (snakeoil) certificate can be created by installing
		#   the ssl-cert package. See
		#   /usr/share/doc/apache2/README.Debian.gz for more info.
		#   If both key and certificate are stored in the same file, only the
		#   SSLCertificateFile directive is needed.
		SSLCertificateFile	/etc/apache2/ssl/www.abc.org.crt
		SSLCertificateKeyFile  /etc/apache2/ssl/www.abc.org.key

		#   Server Certificate Chain:
		#   Point SSLCertificateChainFile at a file containing the
		#   concatenation of PEM encoded CA certificates which form the
		#   certificate chain for the server certificate. Alternatively
		#   the referenced file can be the same as SSLCertificateFile
		#   when the CA certificates are directly appended to the server
		#   certificate for convinience.
		SSLCertificateChainFile /etc/apache2/ssl/www.abc.org.ca-bundle



    ErrorLog ${APACHE_LOG_DIR}/mysite-ssl-error.log
    CustomLog ${APACHE_LOG_DIR}/mysite-ssl-access.log combined

    WSGIDaemonProcess new_project python-path=/var/www/html/wellbeing_folder/wellbeing_project  python-home=/var/www/html/wellbeing_folder/myvenv/
    WSGIApplicationGroup %{GLOBAL}
    WSGIProcessGroup new_project
    WSGIScriptAlias / /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_project/wsgi.py
    Alias /static  /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_app/static
    Alias /.well-known /var/www/html/wellbeing_folder/wellbeing_project/.well-known

<Directory />
    #Options FollowSymLinks
    Options Indexes FollowSymLinks
    Require all granted
</Directory>
<Directory /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_project/>
        <Files wsgi.py>
            Require all granted
        </Files>
</Directory>
<Directory /var/www/html/wellbeing_folder/wellbeing_project/wellbeing_app/static/>
      Require all granted
</Directory>



</VirtualHost>

<VirtualHost *:80>
    ServerName abc.org
    ServerAlias www.abc.org

    ErrorLog ${APACHE_LOG_DIR}/mysite-error.log
    CustomLog ${APACHE_LOG_DIR}/mysite-access.log combined

    RedirectPermanent / https://www.abc.org/
</VirtualHost>

**Comment by shelza1305** [comment]
That means i have to create this single file i.e. wellbeing.conf file for (<VirtualHost *:443> or <VirtualHost *:80>) and donot have to add anything in default-ssl.conf.

**Comment by GrahamDumpleton** [comment]
Correct. You can have multiple ``VirtualHost`` for both port 80 and 443. Which is used will depend on ``ServerName`` and ``ServerAlias``, with the appropriate one being matched by the host in the URL and the port. Thus it is typical that default virtual host for port 80 and 443 are left alone.

**Comment by shelza1305** [comment]
So, i have to disable default-ssl.conf and delete server name and server alias from that file.

Then create single wellbeing.conf file for both ports.

Add wsgi application in virtual host*:443

Is it correct?

**Comment by GrahamDumpleton** [comment]
You don't strictly have to disable ``default-ssl.conf``, but you do need to remove the ``ServerName`` and ``ServerAlias`` from it otherwise your separate ``VirtualHost`` for port 443 will not be used as the default one will match first when checking host name against ``ServerName`` and ``ServerAlias``.

But other than that, yes.

**Comment by shelza1305** [comment]
okay..thank you so much.

in default-ssl.conf ,also i gave the path of ssl certificates so i need  to remove that path also ??

if yes, add that path in wellbeing.conf for virtual host*.443

**Comment by GrahamDumpleton** [comment]
The example already had them in the second ``VirtualHost``.

If you left them in the default virtual host for 443, with it still enabled, the existing default virtual host would be used if someone accessed the host by IP address, or a wrong hostname. That is why it is called the default.

That can be useful so you can set the default virtual hosts to return forbidden.

If you disable the default virtual host for 443, such requests against IP or wrong hostname will end up going to your new virtual host, since it will be now the first virtual host for port 443 Apache finds in the conf, so it ends up being used as the default instead.

Maybe read my comments about setting default virtual hosts to forbid requests in section "Fallback to default VirtualHost definition" of:

* http://blog.dscpl.com.au/2012/10/requests-running-in-wrong-django.html

That example mentions port 80, but same for port 443.

**Comment by shelza1305** [comment]
So i have to write this to set the default virtual hosts to return forbidden in default-ssl.conf file:

<VirtualHost _default_:*443>
Deny from all
</VirtualHost>

**Comment by shelza1305** [comment]
and other contents will be commented in default-ssl.conf

**Comment by shelza1305** [comment]
so i have to write these below lines in "default-ssl.conf" to set the default virtual hosts to return forbidden.
<VirtualHost _default_:*>
Deny from all
</VirtualHost>

other contents of "default-ssl.conf" file will be removed.

**Comment by shelza1305** [comment]
so i have to write these lines in "default-ssl.conf" to set the default virtual hosts to return forbidden.

<VirtualHost _default_:*>
Deny from all
</VirtualHost>

and other contents of these files "default-ssl.conf" will also be removed..

And last not disable default-ssl.conf


as i am able to understand?

**Comment by GrahamDumpleton** [comment]
No. You still must use 443 and not ``*``, and you must leave all the SSL stuff in there still else it will not handle requests as HTTPS such that it can respond with a forbidden response.

**Comment by shelza1305** [comment]
Okay...that means I  have to put one line  i.e. 'deny from all'  in< virtualHost _default_:443> ( in default-ssl.conf) and rest ssl content need to be same.

**Comment by shelza1305** [comment]
Okay... That means I have to add only one line i.e. "deny from all" in <virtualhost default:443> ( in default-ssl.conf) and rest content need to be same.

**Comment by GrahamDumpleton** [comment]
Have you tried to do any of what I have said? This is not a mod_wsgi issue, but an Apache configuration issue. So perhaps also read the Apache documentation and learn how Apache configuration works.

**Comment by shelza1305** [comment]
i have tried all the methods but right now problem is not solved,

I read apache documentation also. there is 

If you need your site to be accessible via both both https and http connections, you’ll need two separate files in/etc/apache2/sites-enabled/. One will be for port 80, the other for port 443.

So i make now 2 different files for both port. but the problem still remains same.

**Comment by GrahamDumpleton** [comment]
You aren't meant to put files in ``sites-enabled``. You are supposed to put them in ``sites-available``. They are then symlinked into ``sites-enabled`` using ``s2enmod``. You don't need separate files for port 80 and 443. There is nothing wrong with having the ``VirtualHost`` for both ports for the one host in the same file.

Key things are. Ensure aren't setting ``ServerName`` or ``ServerAlias`` in default virtual hosts, only set them in your extra virtual hosts. When making a request, ensure the hostname matching ``ServerName`` or ``ServerAlias`` is used in the URL. Don't use an IP address.

Verify whether your file is even being read by adding some garbage characters in it which fails syntax checking. That is, add a line ``XXX`` by itself. You shouldn't be able to restart Apache, it will fail if the file is read and it encounters that.

**Comment by girum89** [comment]
Hello,

I had a working flask api with http but when I moved to https I am not geting a response. the previous working conf is flask.conf
[flask.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/6261843/flask.txt)

and now I have 3 files in my apache sites enabled with the modified flask-ssl.conf file(after a2ensite and restart). I followed your comments above but its not working for me. I just want only https requests. Here are my files. Thank you.
[000-default.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/6261851/000-default.txt)
[ds-ssl.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/6261852/ds-ssl.txt)
[flask-ssl.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/6261884/flask-ssl.txt)

**Comment by GrahamDumpleton** [comment]
@girum89 Please in future create a new issue and don't ask about new problems on an existing issue.

Anyway, for starters your ``ServerName`` setting is wrong, you have:

```
ServerName aa@example.com
```

The value of that is supposed to the hostname you are using to access the site. So should be:

```
ServerName aa.example.com
```

Because that isn't set correctly, the default virtual host for port 443 is being used.

**Comment by girum89** [comment]
I will move this to a new issue thank you.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
