### ISSUE TITLE
Error while installing by pip(python 3.7) on windows server 2016

### ISSUE THREAD

**Issue by devhadi90** [GrahamDumpleton/mod_wsgi#523]
i have python 3.7 and Microsoft Visual C++ 14.0 is and wamp 3.2 installed but while trying to setup mod_wsgi by pip i get error below
also i have python installed in root of my c partition on folder Python37
i dont know what's the problem

 ERROR: Command errored out with exit status 1:
     command: 'c:\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-vgk_wjzs\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\User
s\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-vgk_wjzs\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(cod
e, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-ux9miil6\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python37\Include\
mod-wsgi'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-vgk_wjzs\mod-wsgi\
    Complete output (26 lines):
    c:\python37\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\mod_wsgi
    copying src\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi
    creating build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\environ.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    creating build\lib.win-amd64-3.7\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management
    creating build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    creating build\lib.win-amd64-3.7\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\docs
    creating build\lib.win-amd64-3.7\mod_wsgi\images
    copying images\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.7\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-vgk_wjzs\\mod-wsgi\\setu
p.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-vgk_wjzs\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n
'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-ux9miil6\install-record.txt' --single-version-externally-managed --compile --inst
all-headers 'c:\python37\Include\mod-wsgi' Check the logs for full command output.

**Comment by GrahamDumpleton** [comment]
This is not a mod_wsgi specific issue, but a Python setup issue. Try installing some other simpler Python package which has a C extension component. That should also fail. Using that simpler package as an example, ask about the issue on StackOverflow as I don't know anything about Windows Python installations to know.

Also be aware that WAMP Apache distribution may not work. The only Apache know for sure works is that from Apache Lounge. Others can be missing header files to build third party Apache modules. That is unrelated to your current problem though.

**Comment by willmvs** [comment]
@devhadi90 if you're pretty sure you installed the Microsoft Visual C++ 14.0, try to use the Visual Studio Developer Command Prompt, instead of the regular Command Prompt  (it should have been installed as part of the bundle). The Developer Command Prompt should load PATH properly, including Visual C++, and you should be able to install mod_wsgi without any error messages. It worked for me.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
