### ISSUE TITLE
wamp server can't load my django site whenever I add anything of django-import-export module

### ISSUE THREAD

**Issue by bahaspieler** [GrahamDumpleton/mod_wsgi#524]
Whenever I add "import_export" to my settings and add these lines to my admin.py, wamp server can't load the page, it gets stucked on the "Loading.." screen.
```
@admin.register(model1, model2, model3)
class ViewAdmin(ImportExportModelAdmin):
    pass
    exclude = ('id','completed' )
```
But when I remove the app from the settings and also the above lines from admin.py, the server loads the pages swiftly. I am using wamp3.2, Apache 2.4.41, mod_wsgi 4.5.24 and python 3.7.6 on a windows 8.1 machine. Everything is of 64 bit.

**Comment by GrahamDumpleton** [comment]
Possibly because you are using a Python package which has a C extension which isn't implemented so it will work in Python sub interpreters. Force the use of the main Python interpreter as explained in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

**Comment by bahaspieler** [comment]
> Possibly because you are using a Python package which has a C extension which isn't implemented so it will work in Python sub interpreters. Force the use of the main Python interpreter as explained in:
> 
> * https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

Thanks a lot. The problem is now **solved** after adding 
```
WSGIApplicationGroup %{GLOBAL}
```
to my virtualhost. Having some python script also imported to a `views.py` from the same directory, I was struggling too with the `loading...` screen problem, now everything is fine.

**Another thing to mention**. The django settings.py INSTALLED_APPS section may need to be ordered  carefully, the problem was still on while I was calling `import_export` in the middle of ather apps. But when I called `import_export` at very first, the problem is resolved.
