### ISSUE TITLE
ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by Yabk** [GrahamDumpleton/mod_wsgi#525]
Windows Server 2019
Python 3.7.6 32bit
Apache 2.4 32bit
virtualenv 20.0.4
pip 20.0.2
mod-wsgi 4.7.1

I'm getting the following error:
```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

Another weird thing is the output of `mod_wsgi-express module-config` command:

```
LoadModule wsgi_module "c:/path/to/project/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win32.pyd"
WSGIPythonHome "c:/path/to/project/venv"
```
It doesn't have the LoadFile directive.

Once I remove WSGIPythonHome directive the server is able to start but it, of course, fails on every request with `ModuleNotFoundError: No module named 'django'`

**Comment by SoftProger** [comment]
Ran into the same issue:
Windows Server 2019
Python 3.7.6 64bit
Apache 2.4 64bit
pip 20.0.2
mod-wsgi 4.7.1

It seems like `module-config` command tries to find nonexistent `library_path` inside virtual environment `/src/server/__init__.py` starting from line 3469:
```
...
if os.name == 'nt':
    real_prefix = getattr(sys, 'real_prefix', None)
    real_prefix = real_prefix or sys.prefix

    library_version = sysconfig.get_config_var('VERSION')

    library_name = 'python%s.dll' % library_version
    library_path = os.path.join(real_prefix, library_name)

    if not os.path.exists(library_path):
        library_name = 'python%s.dll' % library_version[0]
        library_path = os.path.join(real_prefix, 'DLLs', library_name)

    if not os.path.exists(library_path):
        library_path = None

    if library_path:
        library_path = os.path.normpath(library_path)
        library_path = library_path.replace('\\', '/')

        print('LoadFile "%s"' % library_path)
...
```
Neither python37.dll nor DLLs folder exist inside of the root of my venv so `library_path` just sets to None and LoadFile directive doesn't print out.

I tried to play around with environment variables like `PYTHONPATH` and `PYTHONHOME`, but it doesn't solve the issue.

However, it all works just fine outside of the virtual environment.

**Comment by GrahamDumpleton** [comment]
Work out where the Python DLL is located yourself and manually set ``LoadFile``.

Likely a change is need to this to correspond to fix needed to allow installation on latest Python versions when using ``venv`` module to create the virtual environment.

* https://github.com/GrahamDumpleton/mod_wsgi/commit/ffbdfaa87834d0a23f4147ef74164170d4400f86

In other words, also needs to look for ``base_prefix`` as fallback.

**Comment by GrahamDumpleton** [comment]
Can you try:

```
pip install -U https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

and see if that works.

**Comment by haris-ahmed** [comment]
Hi @GrahamDumpleton, I ran into same issue

Using:
Windows 10
Python 3.7.6 64bit
Apache 2.4.41 64bit
mod-wsgi 4.7.1 / develop (you provided previous comment)

same issue is occurring in case of `venv` with your provided update in last comment

Apache Logs:
```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

now `mod_wsgi-express module-config` is also returning
`LoadFile "D:/tools/python/python-3.7.6-amd64/python37.dll"`

but issue still persists Apache is not getting started, everything is working fine if run from main interpreter instead of `venv`.

Thank you.

**Comment by Yabk** [comment]
Can confirm the same behavior as @haris-ahmed

**Comment by GrahamDumpleton** [comment]
See discussion in:

* https://github.com/GrahamDumpleton/mod_wsgi/issues/535

for now.

Don't use ``WSGIPythonHome`` and activate the Python virtual environment if used in the WSGI script file.

I need to make a change to mod_wsgi and have people try it to see if works as I don't use/have Windows. Follow the other issue for an update there. Will try and remember to make change to try in next day or so.

**Comment by GrahamDumpleton** [comment]
Closing as believe latest mod_wsgi versions install and work more reliably on Windows now.
