### ISSUE TITLE
Truncated or oversized response headers received from daemon process

### ISSUE THREAD

**Issue by amarnath** [GrahamDumpleton/mod_wsgi#528]
I tried creating Flask application using Python 3.8.1 `venv` and installed `mod_wsgi` via `pip`.
Flask application runs fine using `flask run` but NOT in Apache. Please help on this issue.

`RHEL 7.7 (Maipo)`
`Apache 2.4.6`
`Python 3.8.1`

**pip freeze**

    amqp==2.5.2
    Babel==2.8.0
    bcrypt==3.1.7
    billiard==3.6.2.0
    celery==4.4.0
    certifi==2019.11.28
    cffi==1.14.0
    chardet==3.0.4
    Click==7.0
    cryptography==2.8
    Flask==1.1.1
    flower==0.9.3
    future==0.18.2
    html5lib==1.0.1
    idna==2.9
    itsdangerous==1.1.0
    Jinja2==2.11.1
    kombu==4.6.7
    MarkupSafe==1.1.1
    mod-wsgi==4.7.1
    netmiko==3.0.0
    paramiko==2.7.1
    Pillow==7.0.0
    pycparser==2.19
    PyMySQL==0.9.3
    PyNaCl==1.3.0
    PyPDF2==1.26.0
    pyserial==3.4
    pytz==2019.3
    reportlab==3.5.34
    requests==2.23.0
    scp==0.13.2
    six==1.14.0
    textfsm==1.1.0
    tornado==5.1.1
    urllib3==1.25.8
    vine==1.3.0
    webencodings==0.5.1
    Werkzeug==1.0.0
    xhtml2pdf==0.2.4
    xmltodict==0.12.0

**httpd.conf**

    LoadModule wsgi_module "/usr/lib64/httpd/modules/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so"

    <VirtualHost *:80>
        ServerName xyz.example.com
        DocumentRoot /var/www/html/xyz-venv/xyz
        <Directory /var/www/html/xyz-venv/xyz>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        </Directory>

        WSGIDaemonProcess xyz threads=1 python-home=/var/www/html/xyz-venv
        WSGIProcessGroup xyz
        WSGIScriptAlias / /var/www/html/xyz-venv/xyz/xyz.wsgi
        WSGIApplicationGroup %{GLOBAL}
        <Directory /var/www/html/xyz-venv/xyz>
            <IfVersion < 2.4>
                Order allow,deny
                Allow from all
            </IfVersion>
            <IfVersion >= 2.4>
                Require all granted
            </IfVersion>
        </Directory>
    </VirtualHost>

**Error Log**

    [wsgi:error] [pid 62191] [client 0.0.0.0:58175] Truncated or oversized response headers received from daemon process 'xyz': /var/www/html/xyz-venv/xyz.wsgi
    [core:notice] [pid 62187] AH00052: child pid 62190 exit signal Segmentation fault (11)
    [wsgi:info] [pid 62187] mod_wsgi (pid=62190): Process 'xyz' has died, deregister and restart it.
    [wsgi:info] [pid 62187] mod_wsgi (pid=62190): Process 'xyz' terminated by signal 11
    [wsgi:info] [pid 62187] mod_wsgi (pid=62190): Process 'xyz' has been deregistered and will no longer be monitored.
    [wsgi:info] [pid 62404] mod_wsgi (pid=62404): Starting process 'xyz' with uid=48, gid=48 and threads=1.
    [wsgi:info] [pid 62403] mod_wsgi (pid=62403): Initializing Python.
    [wsgi:info] [pid 62404] mod_wsgi (pid=62404): Python home /var/www/html/xyz.
    [wsgi:info] [pid 62404] mod_wsgi (pid=62404): Initializing Python.
    [wsgi:info] [pid 62403] mod_wsgi (pid=62403): Attach interpreter ''.
    [wsgi:info] [pid 62404] mod_wsgi (pid=62404): Attach interpreter ''.
    [wsgi:info] [pid 62404] mod_wsgi (pid=62404): Imported 'mod_wsgi'.
    [reqtimeout:info] [pid 62193] [client 3.212.44.194:58176] AH01382: Request header read timeout

**Comment by GrahamDumpleton** [comment]
Sorry for the delay, been busy on other stuff. If you can try and catch a stack trace for where it is crashing that may help.

* https://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html#debugging-crashes-with-gdb

From the information you gave, can't see any of the obvious usual causes for this.

Given you are forcing use of the main interpreter context, which avoids this for some Python packages, still leaves the possibility that Python package with C extension, installed from binary wheel, is linked to incompatible version of system libraries. This can occur with SSL and crypto libraries in particular.

If not done it already, make sure all system packages are up to date, and look at creating a fresh Python virtual environment and reinstall the Python packages.

**Comment by ialbd** [comment]
@amarnath hey, did you have any luck with this?

**Comment by GrahamDumpleton** [comment]
@ialbd Each persons situation may be different so is better to create a new issue giving all the details about you particular case. In the new issue, be clear about what Python distro you are using. What the mod_wsgi configuration is. What Python packages you are using.

**Comment by ialbd** [comment]
> @ialbd Each persons situation may be different so is better to create a new issue giving all the details about you particular case. In the new issue, be clear about what Python distro you are using. What the mod_wsgi configuration is. What Python packages you are using.

Thanks @GrahamDumpleton. Created a new issue https://github.com/GrahamDumpleton/mod_wsgi/issues/541

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
