### ISSUE TITLE
Not able to install mod_wsgi in Windows 7

### ISSUE THREAD

**Issue by venkatramireddy** [GrahamDumpleton/mod_wsgi#53]
C:\Users\gbs03566\Desktop\mod_wsgi-4.3.0>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    'Apache httpd server packages.' % APXS)
RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.

**Comment by licface** [comment]
@GrahamDumpleton: there is way to compile it in Windows 7 ?

**Comment by GrahamDumpleton** [comment]
See:

* https://github.com/GrahamDumpleton/mod_wsgi/releases
* https://github.com/GrahamDumpleton/mod_wsgi/blob/master/win32/README.rst

If the binaries aren't working on Windows 7 then create a new separate issue about it rather than jump on this one. Thanks.
