### ISSUE TITLE
Unable to see the deployed Django app on Apache with mod_wsgi - windows 10

### ISSUE THREAD

**Issue by amolpachpute-synerzip** [GrahamDumpleton/mod_wsgi#530]
**I have the following directory structure:** 

**EMSBackend**
                      **backend**
                             wsgi_windows.py
                             wsgi.py
                             urls.py
                             settings
manage.py
Pipfile

Software versions:
 - Python 3.8
 - Apache 2.4
 - Django 2.1.15
 - mod_wsgi 4.7

I have configured all the settings as mentioned on so many sites for Django deployment on windws
I can see Django app if I run using runserver then I can see the application successfully
I can see Apache server is running successfully. 
Install mod_wsgi successfully. 

**When I updated the following files:**

********************** wsgi_windows.py**********************
activate_this = 'C:\Users\sachidanandc\.virtualenvs\EMSBackend-sU_2PIWM\Scripts\activate_this.py'
# execfile(activate_this, dict(__file__=activate_this))
exec(open(activate_this).read(),dict(__file__=activate_this))

import os
import sys
import site

# Add the site-packages of the chosen virtualenv to work with
site.addsitedir('C:\Users\sachidanandc\.virtualenvs\EMSBackend-sU_2PIWM\Lib\site-packages')

# Add the app's directory to the PYTHONPATH
sys.path.append('F:\WSGI\EMSBackend')
sys.path.append('F:\WSGI\EMSBackend\backend')

os.environ['DJANGO_SETTINGS_MODULE'] = 'backend.settings'
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()

********************** http.conf**********************

LoadFile "C:/Python38/python38.dll"
LoadModule wsgi_module "C:/Python38/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd"
WSGIPythonHome "C:/Python38"

****************httpd-vhosts.conf**********************************
# virtual SupervisionTool
<VirtualHost *:8880>
    ServerName localhost 
    WSGIPassAuthorization On
    ErrorLog "logs/my_application.error.log"
    CustomLog "logs/my_application.access.log" combined
    WSGIScriptAlias /  "F:/WSGI/EMSBackend/backend/wsgi_windows.py"
    <Directory "F:/WSGI/ForecastGenius-Backend/backend">
        <Files wsgi_windows.py>
            Require all granted
        </Files>
    </Directory>

    Alias /static "F:/WSGI/EMSBackend/backend/static"
    <Directory "F:/WSGI/EMSBackend/backend/static">
        Require all granted
    </Directory>  
</VirtualHost>
# end virtual SupervisionTool

However when I ran the localhost:8880 then I can see Apache Index page "It works" instead of Django application page. 

Is there any setting/configured missing ?? I have tried other sample app as well but I could not succeed. Thanks a lot In Advanced.

**Comment by GrahamDumpleton** [comment]
BTW, don't use backlashes in paths in Python code. The backslash means escape the following character which can screw up the interpretation of the string. Use forward slashes.
