### ISSUE TITLE
Monitoring mod wsgi daemon processes and threads

### ISSUE THREAD

**Issue by diegobill** [GrahamDumpleton/mod_wsgi#533]
With mod status (https://httpd.apache.org/docs/2.4/mod/mod_status.html) we can monitor only the standard (embedded mode not daemon process) apache processes and threads. 
How we can monitor  (# busy and # idles) the processes and threads on daemon mode?

**Comment by GrahamDumpleton** [comment]
For a start read:

* http://blog.dscpl.com.au/2015/06/implementing-request-monitoring-within.html

There is more than what is described there available though. Raise the question on the mod_wsgi mailing list as better discussed there rather than on a GitHub issue.

* https://modwsgi.readthedocs.io/en/develop/finding-help.html

**Comment by diegobill** [comment]
Thanks @GrahamDumpleton , but I need to monitor the quantity of busy threads and idle threads with the corresponding process information. I tried to use the package mod_wsgi and function server_metrics 
```
import mod_wsgi
mod_wsgi.server_metrics()
```
but I am also receiving the information only about the processes running on embedded mode (not daemon processes), the same information that I am already receiving on mod_status.
Can I receive the quantity of busy and idle threads from daemon processes using mod_wsgi.server_metrics() ?

**Comment by GrahamDumpleton** [comment]
You can as a start use ``mod_wsgi.process_metrics()``, but you need to have a background thread in each daemon group process to poll it an do stuff with it. You can't access the information for all processes from one process like with ``mod_status``.

The better way to measure busy/idle is to calculate the capacity utilisation. This is easier done triggered from the per request events with some extract tracking code added. To explain that I would have preferred to do it on the mod_wsgi mailing list, as I got another person after similar information at the moment, so can address it to both of you. I just need to find that extra tracking code as I had to give up a laptop a while back which it was on. I have a copy somewhere though.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
