### ISSUE TITLE
Unsupplied content-type header causing problems

### ISSUE THREAD

**Issue by stefvanhouten** [GrahamDumpleton/mod_wsgi#534]
When chrome retrieves a page from its history to go either forward or backward it for some reason removes the 'content-type' header. When a POST request is retrieved from history it will be retrieved without 'content-type' header. 

WSGI has a default 'content-type': 'text/plain', when chrome fails to supply the correct 'content-type' header it will default to this leading to unwanted behaviour. 

In my case post data from a request was converted into a io.StringIo object and was then passed, along with the request headers, to the cgi.FieldStorage class. Because the content-type was defaulted to text/plain the application would crash.

**Comment by GrahamDumpleton** [comment]
So this seems to be an issue with Chrome behaviour. You are probably better off asking on StackOverflow about it. Although I am not sure what the actual question is and what answer you are expecting.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
