### ISSUE TITLE
Fatal Python error: initfsencoding: unable to load the file system codec

### ISSUE THREAD

**Issue by rajeev2834** [GrahamDumpleton/mod_wsgi#537]
Sir,
 I am trying flask with mod_wsgi apache in virtual environment with following components
Window 10
Flask 1.1.1
mod-wsgi 4.7.1
Python 3.7.6
Apachae 2.4.1

I am unable to get final result. I have attached httpd conf file and virtual host file.
[httpd.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/4302806/httpd.txt)
[httpd-vhosts - Copy.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/4302807/httpd-vhosts.-.Copy.txt)

Please guide me.

**Comment by GrahamDumpleton** [comment]
See discussion in:

* https://github.com/GrahamDumpleton/mod_wsgi/issues/535

For now you will need to activate any Python virtual environment in the WSGI script file and drop the ``WSGIPythonHome`` directive.

**Comment by rajeev2834** [comment]
Sir,
 There is no path  ./env/bin/scripts and no file name with activate_this.py . Instead I am having ./env/Scripts and file name with activate.
I have modified my script file as per your suggestion and when running httpd.exe from command prompt in a virtual environment, it's working fine.
(env) C:\Apache24\bin>httpd.exe
Then in browser localhost... it's running
But I am unable to activate virtual environment from script file

**Comment by GrahamDumpleton** [comment]
Use the ``site.addsitedir()`` method described in that issue to have the same affect as activation.

**Comment by rajeev2834** [comment]
Thanks a lot. It's working
