### ISSUE TITLE
Not able to install mod_wsgi in Windows 10 64 bit

### ISSUE THREAD

**Issue by nacoolp** [GrahamDumpleton/mod_wsgi#538]
Hi,

I am using python 3.7.6 and have installed Microsoft Visual Studio 14.0. Whenever I am trying to install mod_wsgi, I am getting the same error: C1083: Cannot open include file: 'ws2tcpip.h'.

`Collecting mod_wsgi
  Downloading mod_wsgi-4.7.1.tar.gz (498 kB)
     |████████████████████████████████| 498 kB 167 kB/s
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\development_env\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-q319i9op\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-q319i9op\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\admin\AppData\Local\Temp\pip-wheel-bep53voy'
       cwd: C:\Users\admin\AppData\Local\Temp\pip-install-q319i9op\mod-wsgi\
  Complete output (33 lines):
  c:\program files\python\python37\Lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\mod_wsgi
  copying src\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi
  creating build\lib.win-amd64-3.7\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win-amd64-3.7\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win-amd64-3.7\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server
  creating build\lib.win-amd64-3.7\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management
  creating build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
  creating build\lib.win-amd64-3.7\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\docs
  creating build\lib.win-amd64-3.7\mod_wsgi\images
  copying images\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.7\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\server
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\wamp64\bin\apache\apache2.4.41\/include "-Ic:\program files\python\python37\include" "-Ic:\program files\python\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.7\Release\src/server\mod_wsgi.obj
  mod_wsgi.c
  c:\users\admin\appdata\local\temp\pip-install-q319i9op\mod-wsgi\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws2tcpip.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
    Running setup.py install for mod-wsgi ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\development_env\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-q319i9op\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-q319i9op\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-jbw2eyaz\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\development_env\venv\include\site\python3.7\mod-wsgi'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-q319i9op\mod-wsgi\
    Complete output (33 lines):
    c:\program files\python\python37\Lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\mod_wsgi
    copying src\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi
    creating build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\environ.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    creating build\lib.win-amd64-3.7\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management
    creating build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    creating build\lib.win-amd64-3.7\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\docs
    creating build\lib.win-amd64-3.7\mod_wsgi\images
    copying images\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.7\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\server
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\wamp64\bin\apache\apache2.4.41\/include "-Ic:\program files\python\python37\include" "-Ic:\program files\python\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.7\Release\src/server\mod_wsgi.obj
    mod_wsgi.c
    c:\users\admin\appdata\local\temp\pip-install-q319i9op\mod-wsgi\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws2tcpip.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\development_env\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-q319i9op\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-q319i9op\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-jbw2eyaz\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\development_env\venv\include\site\python3.7\mod-wsgi' Check the logs for full command output.` 

Even tried with previous versions but got the same error.

I tried to go through the solutions provided for similar issue but still unable to install and everytime getting the above error. 

Support on this is highly appreciated. Thanks in advance.

**Comment by GrahamDumpleton** [comment]
It is believed this is because of missing compiler SDK packages on your system. See:

* https://github.com/GrahamDumpleton/mod_wsgi/issues/194

Other than that, suggest you ask about it on StackOverflow as I don't know details of how to get compiler tool chains installed on Windows properly. It is not an issue with mod_wsgi itself.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
