### ISSUE TITLE
Running mod_wsgi for python 2 and 3 concurrently

### ISSUE THREAD

**Issue by aprsa** [GrahamDumpleton/mod_wsgi#540]
Hello mod_wsgi experts! I have two django powered websites that are hosted by apache; one lives in its python 2 venv and the other in its python 3 venv. The python 2 website is deployed and working, using distro mod_wsgi for python 2; now I'm trying to get the python 3 website working. From issue #21 it's clear that this can't happen without mod_wsgi express, but I couldn't figure out how to get it to work. Does anyone have a worked out solution for this? Thanks in advance!

**Comment by GrahamDumpleton** [comment]
What did you actually try? Did you get ``mod_wsgi-express`` installed into the Python 3 virtual environment by using ``pip install mod_wsgi``?

* https://pypi.org/project/mod-wsgi/

**Comment by aprsa** [comment]
Yes, that's precisely what I'd done, and it worked with no issues. Getting it connected to apache is where I got stuck.

**Comment by GrahamDumpleton** [comment]
For a start read:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

Just ignore that it talks about proxying to ``mod_wsgi-express`` in a container. Still all applies.

**Comment by aprsa** [comment]
On it, thanks!!

**Comment by aprsa** [comment]
Thank you for your help so far, @GrahamDumpleton! I successfully deployed mod_wsgi and the website is up and running when using `python manage.py runmodwsgi`. It's served on localhost:8000. Running `mod_wsgi-express module-config` prints out venv's settings, so that also looks good. Now I'm trying to use the proxy; from your first link, you refer to the docker as http://docker.example.com:8002/ in the ProxyPass directive; what would I use here for the virtual environment?

**Comment by GrahamDumpleton** [comment]
Presuming is on same host, use ``http://localhost:8000`` in the ``ProxyPass``.

**Comment by aprsa** [comment]
Woohoo, it's working! Well, it's working if I explicitly run `python manage.py runmodwsgi`. I guess my next step will be to do the server setup, but I think the difficult part is already behind me! Thanks, @GrahamDumpleton! :)
