### ISSUE TITLE
Request data write error when proxying data to daemon process

### ISSUE THREAD

**Issue by schlupov** [GrahamDumpleton/mod_wsgi#542]
I've got a problem with uploading a big file (approximately 2 GB) on the server. Already at 10 MB, I can see in the log this message 
`[Mon Mar 16 11:10:54.209395 2020] [wsgi:error] [pid 683812:tid 139809976743680] [client 89.103.91.114:34058] mod_wsgi (pid=683812): Request data write error when proxying data to daemon process: Broken pipe.`
and later
`[Mon Mar 16 12:09:02.768317 2020] [wsgi:error] [pid 683812:tid 139809976743680] [client 89.103.91.114:34058] Truncated or oversized response headers received from daemon process '127.0.0.1': /usr/share/copr/xy/application`
and uploading fails.

My .conf
```
LoadModule wsgi_module modules/mod_wsgi.so
WSGISocketPrefix /var/run/wsgi
Alias /robots.txt /var/www/html/robots.txt
Alias "/db_dumps/" "/var/www/html/db_dumps/"

WSGIDaemonProcess 127.0.0.1 user=xy group=xy processes=4 threads=5 display-name=other maximum-requests=8000 restart-interval=300 graceful-timeout=20
WSGIDaemonProcess api user=xy group=xy threads=15 display-name=api maximum-requests=8000 graceful-timeout=7200
WSGIDaemonProcess api_upload user=xy group=xy threads=4 processes=2 display-name=api_upload maximum-requests=100 request-timeout=3600 graceful-timeout=7200
WSGIDaemonProcess backend user=xy group=xy threads=15 display-name=backend maximum-requests=8000 graceful-timeout=20
WSGIDaemonProcess stats user=xy group=xy threads=15 display-name=stats maximum-requests=8000 graceful-timeout=20
WSGIDaemonProcess tmp user=xy group=xy threads=15 display-name=tmp maximum-requests=8000 graceful-timeout=20
WSGIDaemonProcess repo user=xy group=xy threads=15 display-name=repo maximum-requests=8000 graceful-timeout=20
WSGIDaemonProcess packages user=xy group=xy processes=1 threads=6 maximum-requests=100 display-name=packages graceful-timeout=20
WSGIScriptAlias / /usr/share/copr/xy/application

<VirtualHost *:80>
    ServerName example.org
    ServerAlias xy.example.org
    WSGIPassAuthorization On

    <Location />
        WSGIProcessGroup 127.0.0.1
    </Location>

    #ErrorLog logs/error_example
    #CustomLog logs/access_example common

    <Directory /usr/share/xy>
        WSGIApplicationGroup %{GLOBAL}
    Require all granted
    </Directory>

    RewriteEngine on
    RewriteRule ^/\.well-known/(.*) /var/www/html/.well-known/$1 [L]
    RewriteRule "^/?(.*)" "https://%{HTTP_HOST}/$1" [L,R=301,NE]
</VirtualHost>

<IfModule mod_status.c>
ExtendedStatus On

<Location /server-status>
    SetHandler server-status
    Require all denied
    Require host localhost .example.com
</Location>
</IfModule>

<IfModule mpm_prefork_module>
    StartServers          8
    MinSpareServers       8
    MaxSpareServers      20
    MaxClients          50
    MaxRequestsPerChild   10000
</IfModule>
```

and in httpd.conf there is the directive `TimeOut 7200`
If I try to upload a smaller file (approximately 1.6 GB) it works. I don't know what else to set to make it work. The problem is with api_upload. I tried other WSGIDaemonProcess directives but nothing worked. I will appreciate any kind of help.

**Comment by GrahamDumpleton** [comment]
Add ``LogLevel info`` and capture messages in the Apache error log from mod_wsgi about what is happening to the mod_wsgi daemon processes (restarts or crashes). Also check the main Apache error log for messages at same time which may indicate that a process has crashed for some reason.

The error suggests that the daemon process crashed. This could be caused in this case by running out of process memory if you are trying to handle all the request content in memory. Could also be due to a third party extension module for Python failing because it isn't designed to work in a sub interpreter.

In the case of the latter, although you have set ``WSGIApplicationGroup %{GLOBAL}`` you have it in a ``Directory`` block that doesn't match so it isn't applied. Don't put in in a ``Directory`` block as you have.

Finally, how long does the upload take? Having maximum requests and request timeout settings are a bad idea when you have long running requests.

**Comment by praiskup** [comment]
> .. capture messages in the Apache error log ..
> .. check the main Apache error log ..

We see only this:
```
[Thu Apr 16 13:57:54.413236 2020] [wsgi:info] [pid 1460050:tid 140137698723584] mod_wsgi (pid=1460050): Aborting process '127.0.0.1'.
[Thu Apr 16 13:57:54.413325 2020] [wsgi:info] [pid 1460050:tid 140137698723584] mod_wsgi (pid=1460050): Exiting process '127.0.0.1'.
[Thu Apr 16 13:57:54.494249 2020] [wsgi:error] [pid 1460068:tid 140137216317184] [client 193.165.237.97:33508] mod_wsgi (pid=1460068): Request data write error when proxying data to daemon process: Broken pipe.
[Thu Apr 16 13:57:55.418849 2020] [wsgi:info] [pid 1460045:tid 140137932570944] mod_wsgi (pid=1460050): Process '127.0.0.1' has died, deregister and restart it.
[Thu Apr 16 13:57:55.418924 2020] [wsgi:info] [pid 1460045:tid 140137932570944] mod_wsgi (pid=1460050): Process '127.0.0.1' has been deregistered and will no longer be monitored.
[Thu Apr 16 13:57:55.420301 2020] [wsgi:info] [pid 1460676:tid 140137932570944] mod_wsgi (pid=1460676): Starting process '127.0.0.1' with uid=992, gid=989 and threads=5.
[Thu Apr 16 13:57:55.421566 2020] [wsgi:info] [pid 1460676:tid 140137932570944] mod_wsgi (pid=1460676): Initializing Python.
[Thu Apr 16 13:57:55.447131 2020] [wsgi:info] [pid 1460676:tid 140137932570944] mod_wsgi (pid=1460676): Attach interpreter ''.
[Thu Apr 16 13:57:55.452439 2020] [wsgi:info] [pid 1460676:tid 140137932570944] mod_wsgi (pid=1460676): Imported 'mod_wsgi'.
```

Hm, Aborting process...  I should get traceback somehow, right?

> The error suggests that the daemon process crashed. This could be caused in
> this case by running out of process memory if you are trying to handle all the
> request content in memory. Could also be due to a third party extension module
> for Python failing because it isn't designed to work in a sub interpreter.

We are using python flask (werkzeug).  From docs, it seems like they somewhat
vaguely say that reasonably sized files are kept in memory, and others have
temporary file created.  I wasn't able to grep through the sources to find the
"if statement" responsible for the "what is reasonable size" condition.

Isn't there a way to tell to mod_wsgi why the process is Aborted?

> In the case of the latter, although you have set WSGIApplicationGroup
> %{GLOBAL} you have it in a Directory block that doesn't match so it isn't
> applied. Don't put in in a Directory block as you have.

I moved it.  No difference.

> Finally, how long does the upload take? Having maximum requests and request
> timeout settings are a bad idea when you have long running requests.

Intereseting, the 'Broken pipe' is always printed after ~5 minutes and few
seconds.  Seems like we have problems with 5 minutes requests.  As such, it
looks like `deadlock-timeout=sss` which is 300s.  I tried to do:

```
WSGIDaemonProcess api user=copr-fe group=copr-fe processes=10 deadlock-timeout=600 threads=1 display-name=api maximum-requests=1
```

One thread per process (no GIL issues should occur) and raised the
deadlock-timeout to 600 seconds.  And still, I see logs I posted above.

**Comment by GrahamDumpleton** [comment]
All your requests are being handled by:

```
WSGIDaemonProcess 127.0.0.1 user=xy group=xy processes=4 threads=5 display-name=other maximum-requests=8000 restart-interval=300 graceful-timeout=20
```

This is because you have:

```
    <Location />
        WSGIProcessGroup 127.0.0.1
    </Location>
```

Having it in a ``Location`` directive for ``/`` is actually pointless, as is the same as having:

```
        WSGIProcessGroup 127.0.0.1
```

This also appears unused.

```
    <Directory /usr/share/xy>
        WSGIApplicationGroup %{GLOBAL}
    Require all granted
    </Directory>
```

unless you mucked up cut and paste.

Since using daemon mode, better off to have it just as:

```
        WSGIApplicationGroup %{GLOBAL}
```

So if you created all the other process groups thinking that they would be used for something, they aren't.

If you want specific requests to be delegated to different daemon process groups, you want

```
WSGIDaemonProcess default user=xy group=xy processes=4 threads=5 display-name=other maximum-requests=8000 restart-interval=300 graceful-timeout=20
WSGIProcessGroup default
WSGIApplicationGroup %{GLOBAL}

WSGIDaemonProcess api user=xy group=xy threads=15 display-name=api maximum-requests=8000 graceful-timeout=7200
<Location /api>
WSGIProcessGroup api
</Location>
```

Replace ``/api`` in the ``Location`` with URL sub path for that thing want different config.

Right now you are creating lots of daemon process groups for no reason.

So try cleaning up your config and address that. Show the end result you make it so can check again.

If you have very long running uploads, and want to restart process on maximum requests for some reason, then using a daemon process of:

```
WSGIDaemonProcess api user=copr-fe group=copr-fe processes=10 threads=1 display-name=api maximum-requests=100
```

**Comment by praiskup** [comment]
> unless you mucked up cut and paste

That's what happened.  We have really old http configuration spread across
three files for historical reasons, I'll try to take a look at cleanup and provide
self-standing configuration.  All the daemon process have some reasons, we
created them to hotfix existing workload situations.

**Comment by praiskup** [comment]
> Replace /api in the Location with URL sub path for that thing want different config.

You were right.  I cleaned up a bit [our config](https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/roles/copr/frontend-cloud/templates/httpd/coprs.conf) today and
fixed the Location patterns and it seems to work fine now.  Thanks a lot!

And sorry for noise @GrahamDumpleton, feel free to close this issue.

**Comment by sushantdanekar** [comment]
I had a same problem and i just added processes and threads which solved the problem for me
