### ISSUE TITLE
I want to start a django project in docker container with postgresql database

### ISSUE THREAD

**Issue by rajeev2834** [GrahamDumpleton/mod_wsgi#543]
I have system with following configuration
Window 10
Django in Anaconda environment
Postgresql 12.0
I want to start project in docker. What steps should I follow?

**Comment by GrahamDumpleton** [comment]
I can only suggest you read the separate documentation for, Django, Anaconda Python, Docker etc. Ask any questions on StackOverflow. This is an issue tracker for bugs in mod_wsgi, not a site to get help in general development.
