### ISSUE TITLE
wsgi error IOError: failed to write data

### ISSUE THREAD

**Issue by jud2012** [GrahamDumpleton/mod_wsgi#544]
Hi,

My stack is bottle.py as server and apache

I'm getting the following errors on 2 clients IPs:
IOError: failed to write data
mod_wsgi (pid=25395): Exception occurred processing WSGI script
Timeout when reading response headers from daemon process

I have about 15 clients

Timeout configuration is 600 seconds

Could it be a network issue, between these client and my server

**Comment by GrahamDumpleton** [comment]
You need to provide how you configured mod_wsgi. Also show the complete log messages from when the issue occurs, you have stripped out information.

**Comment by jud2012** [comment]
Thanks for the response.

complete log:
[Wed Mar 18 15:35:55.256420 2020] [wsgi:info] [pid 10159] mod_wsgi (pid=10159): Attach interpreter ''.
[Wed Mar 18 15:35:56.205330 2020] [wsgi:info] [pid 10151] mod_wsgi (pid=10151): Destroying interpreters.
[Wed Mar 18 15:35:56.205356 2020] [wsgi:info] [pid 10151] mod_wsgi (pid=10151): Cleanup interpreter ''.
[Wed Mar 18 15:35:56.207912 2020] [wsgi:info] [pid 10151] mod_wsgi (pid=10151): Terminating Python.
[Wed Mar 18 15:35:56.210391 2020] [wsgi:info] [pid 10151] mod_wsgi (pid=10151): Python has shutdown.
[Wed Mar 18 15:36:00.026568 2020] [wsgi:error] [pid 7759] [client 10.10.60.101:53070] Timeout when reading response headers from daemon process 'mon': /srv/apache/mon/adapter.wsgi, referer: http://athena.xambala.local:10001/mon/weblets/jango/index.html
[Wed Mar 18 15:36:00.209343 2020] [wsgi:info] [pid 10150] mod_wsgi (pid=10150): Destroying interpreters.
[Wed Mar 18 15:36:00.209366 2020] [wsgi:info] [pid 10150] mod_wsgi (pid=10150): Cleanup interpreter ''.
[Wed Mar 18 15:36:00.212280 2020] [wsgi:info] [pid 10150] mod_wsgi (pid=10150): Terminating Python.
[Wed Mar 18 15:36:00.215094 2020] [wsgi:info] [pid 10150] mod_wsgi (pid=10150): Python has shutdown.
[Wed Mar 18 15:36:03.212218 2020] [wsgi:info] [pid 10152] mod_wsgi (pid=10152): Destroying interpreters.
--
[Wed Mar 18 15:36:30.242961 2020] [wsgi:info] [pid 10037] mod_wsgi (pid=10037): Cleanup interpreter ''.
[Wed Mar 18 15:36:30.245345 2020] [wsgi:info] [pid 10037] mod_wsgi (pid=10037): Terminating Python.
[Wed Mar 18 15:36:30.247815 2020] [wsgi:info] [pid 10037] mod_wsgi (pid=10037): Python has shutdown.
[Wed Mar 18 15:36:50.263688 2020] [wsgi:info] [pid 10227] mod_wsgi (pid=10227): Initializing Python.
[Wed Mar 18 15:36:50.277737 2020] [wsgi:info] [pid 10227] mod_wsgi (pid=10227): Attach interpreter ''.
[Wed Mar 18 15:36:54.071680 2020] [wsgi:error] [pid 9727] [client 10.10.60.103:61102] Timeout when reading response headers from daemon process 'mon': /srv/apache/mon/adapter.wsgi, referer: http://jango:1000/mon/weblets/jango/index.html
[Wed Mar 18 15:37:26.296057 2020] [wsgi:info] [pid 10254] mod_wsgi (pid=10254): Initializing Python.
[Wed Mar 18 15:37:26.309116 2020] [wsgi:info] [pid 10254] mod_wsgi (pid=10254): Attach interpreter ''.
[Wed Mar 18 15:37:27.297966 2020] [wsgi:info] [pid 10255] mod_wsgi (pid=10255): Initializing Python.
[Wed Mar 18 15:37:27.298328 2020] [wsgi:info] [pid 10256] mod_wsgi (pid=10256): Initializing Python.
[Wed Mar 18 15:37:27.310516 2020] [wsgi:info] [pid 10255] mod_wsgi (pid=10255): Attach interpreter ''.
--
[Wed Mar 18 15:37:28.319289 2020] [wsgi:info] [pid 10258] mod_wsgi (pid=10258): Attach interpreter ''.
[Wed Mar 18 15:37:28.329977 2020] [wsgi:info] [pid 10259] mod_wsgi (pid=10259): Attach interpreter ''.
[Wed Mar 18 15:37:28.352124 2020] [wsgi:info] [pid 10260] mod_wsgi (pid=10260): Attach interpreter ''.
[Wed Mar 18 15:37:32.307116 2020] [wsgi:info] [pid 10285] mod_wsgi (pid=10285): Initializing Python.
[Wed Mar 18 15:37:32.323011 2020] [wsgi:info] [pid 10285] mod_wsgi (pid=10285): Attach interpreter ''.
[Wed Mar 18 15:37:37.206732 2020] [wsgi:error] [pid 25395] [remote 10.10.60.101:56984] mod_wsgi (pid=25395): Exception occurred processing WSGI script '/srv/apache/mon/adapter.wsgi'.
[Wed Mar 18 15:37:37.211672 2020] [wsgi:error] [pid 25395] [remote 10.10.60.101:56984] IOError: failed to write data
[Wed Mar 18 15:37:53.327355 2020] [wsgi:info] [pid 10258] mod_wsgi (pid=10258): Destroying interpreters.
[Wed Mar 18 15:37:53.327377 2020] [wsgi:info] [pid 10258] mod_wsgi (pid=10258): Cleanup interpreter ''.
[Wed Mar 18 15:37:53.329865 2020] [wsgi:info] [pid 10258] mod_wsgi (pid=10258): Terminating Python.
[Wed Mar 18 15:37:53.332357 2020] [wsgi:info] [pid 10258] mod_wsgi (pid=10258): Python has shutdown.
[Wed Mar 18 15:37:54.328769 2020] [wsgi:info] [pid 10259] mod_wsgi (pid=10259): Destroying interpreters.

wsgi configuration:
<IfModule mod_wsgi.c>

WSGIDaemonProcess mon user="""+user+""" group="""+group+""" processes=1 threads=35
WSGIScriptAlias /mon {0}/mon/adapter.wsgi
<Directory {0}/mon/>
    WSGIApplicationGroup  %{{GLOBAL}}
</Directory>
WSGIProcessGroup mon  

WSGIDaemonProcess research user="""+user+""" group="""+group+""" processes=1 threads=35
WSGIScriptAlias /research {0}/research/adapter.wsgi

WSGIProcessGroup mon  

WSGIRestrictStdin Off
WSGIRestrictStdout Off

WSGISocketPrefix """+tempdir+ """apache
</IfModule>

**Comment by GrahamDumpleton** [comment]
Are you using ``VirtualHost`` specific logs? What messages are in the main Apache error log? Are there message indicating segmentation fault?

There appears to be missing information in the logs, but at a guess it looks like the daemon processes are deadlock or crashing.

Also, your use of ``WSGIProcessGroup`` is wrong as the config is written. If you use ``WSGIProcessGroup`` more than once at the same scope, the last one always wins. So traffic for both WSGI applications is going to the same daemon process.

You should use:

```
WSGIDaemonProcess mon user="""+user+""" group="""+group+""" processes=1 threads=35
WSGIScriptAlias /mon {0}/mon/adapter.wsgi process-group=mon application-group=%{{GLOBAL}}

WSGIDaemonProcess research user="""+user+""" group="""+group+""" processes=1 threads=35
WSGIScriptAlias /research {0}/research/adapter.wsgi process-group=research application-group=%{{GLOBAL}}
```

Finally, if the message:

```
IOError: failed to write data
```

is sporadic, it usually just means that the web client dropped the connection before all data could be written back. This is quite common when clients are mobile applications. That said, if I recollect, in most cases you shouldn't see that message when using up to date mod_wsgi versions. Are you perhaps using a really old version of mod_wsgi. Alternatively, to see that one would need to be using WSGI protocol in uncommon way where the write callable was being used, rather than just returning an iterable from the WSGI application.

**Comment by jud2012** [comment]
Thanks for the quick response.

I'll fix WSGIProcessGroup configuration

I'm using an old mod_wsgi- 4.3.0-1.1build1, this application on 2014 and we didn't upgrade it lately

IOError: failed to write data are sporadic and its happening  only on 2 clients every time, i was thinking that maybe it's a connectivity issue from client to server.
these client are web clients, but they are connected from a different network.

**Comment by GrahamDumpleton** [comment]
As a start, I would suggest updating mod_wsgi to the latest version if you can. That may make a difference.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
