### ISSUE TITLE
accessing Authorization header inside a WSGIAuthUserScript

### ISSUE THREAD

**Issue by nikosft** [GrahamDumpleton/mod_wsgi#549]
I have a `WSGIAuthUserScript` where I need to access the `Authorization`  header. However, as the documentation mentions, 
> the ‘environ’ dictionary passed [...] is a cut down version of what would be supplied to the actual WSGI application

The solution I have found is to append the `User-Agent` header with the `Authorization` header in the apache virtualhost .conf file:

```
SetEnvIf Authorization "(.*)" AUTHORIZATION=$1
RequestHeader append User-Agent %{AUTHORIZATION}e
```
This works, but it is not very elegant (to say the least). Do you see any better way to achieve this?

**Comment by GrahamDumpleton** [comment]
Why are you needing to access the original ``Authorization`` header? Seems that you are working around the intent/purpose of what the handlers for that script file are for. It is not mean to be a general mechanism for implementing arbitrary authorisation mechanisms.

**Comment by nikosft** [comment]
I am doing JWT-based authorization. I am doing it at the server-level because I am using apache as a reverse proxy, but only for authorized users. Currently I am working with [mod_authnz_jwt](https://github.com/AnthonyDeroche/mod_authnz_jwt/pulls) and it works [out of the box](https://github.com/controlthingsopensource/webthings-jwt/blob/master/apache/webthings-gw.conf). However, I would really love to do that using mod_wsgi.

**Comment by GrahamDumpleton** [comment]
I am going to close this issue out. What mod_wsgi has is only meant to implement the ``check_password()`` mechanism of an Apache authentication provider. It is not intended to be used for authorization checks, and even if a backdoor is provided, it will result in the wrong HTTP status code being returned when it fails for your authorization check. Specifically, it will still return 401, when it should really return 403 for an authorization check.
