### ISSUE TITLE
Django ModuleNotFoundError Apache WAMP/ mod_wsgi

### ISSUE THREAD

**Issue by eswarsubra** [GrahamDumpleton/mod_wsgi#550]
Hi,

I am blocked since a couple of days on deploying my django app on WAMP/mod_wsgi.

i have the python set and django also perfectly installed. Inspite when accesing thru WAMP i have a WSGI error stating 
[client ::1:49254] ModuleNotFoundError: No module named 'django'\r, referer: http://localhost/

doing sys.prefix and django on py cmd line. i get the following :
>>> import sys
>>> print(sys.prefix)
C:\Users\eswar_qx\AppData\Local\Programs\Python\Python38
>>> import django
>>> print(django.__file__)
C:\Users\eswar_qx\AppData\Roaming\Python\Python38\site-packages\django\__init__.py

Could you please help ?

Thank you
Es.

**Comment by eswarsubra** [comment]
Well i fixed the issue. To anyone whom it may help. 

I had the following code when i had django module not found. 

**from django.core.wsgi import get_wsgi_application**

site.addsitedir(".../Python38/Lib/site-packages")
site.addsitedir(".../Python/Python38/site-packages")

And i just noticed that my site was getting the site package reference after the import in the sequence. Just changed that over and all's right.

site.addsitedir(".../Python38/Lib/site-packages")
site.addsitedir(".../Python/Python38/site-packages")

**from django.core.wsgi import get_wsgi_application**

Sometimes huge logs in apache when the issue can be as silly as this one...

Hope it helps someone else.

**Comment by GrahamDumpleton** [comment]
If using a virtual environment, you should be using ``WSGIPythonPath`` directive in the Apache configuration. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

If using ``pip install --user`` and per user site packages directory, use a virtual environment instead. Not recommended to use per user site packages directory as under Apache, that will not be used by default.
