### ISSUE TITLE
WSGI error

### ISSUE THREAD

**Issue by ramana459** [GrahamDumpleton/mod_wsgi#552]
Hi Graham,
Once I finished setting up apache with mod_wsgi the apache server is failing
My issue is exactly same as https://github.com/GrahamDumpleton/mod_wsgi/issues/235
But I couldn't figure out the solution

Error from event viewer as below

```
-----------------------------------------------------------------------------------------------
Faulting application name: httpd.exe, version: 2.4.43.0, time stamp: 0x5e834d57
Faulting module name: ucrtbase.dll, version: 10.0.14393.2999, time stamp: 0x5ce36be6
Exception code: 0xc0000409
Fault offset: 0x000000000006e00e
Faulting process id: 0xf84
Faulting application start time: 0x01d60acdb43f6cd8
Faulting application path: C:\Apache24\bin\httpd.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 0807954d-62cf-40c7-be0e-fcc426a30356
Faulting package full name: 
------------------------------------------------------------------------------------------------------
```

**Comment by GrahamDumpleton** [comment]
Try using mod_wsgi installed by running:

```
pip install -U --no-cache-dir https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

instead.

What did ``mod_wsgi-express module-config`` output and which you added to the Apache config file?

**Comment by GrahamDumpleton** [comment]
FWIW, this looks more to do with a problem Microsoft patch update. See:

* https://answers.microsoft.com/en-us/windows/forum/all/faulting-module-name-ucrtbasedll-version/a718b683-f05c-4bbb-aafb-6c2605f184e1

**Comment by GrahamDumpleton** [comment]
Closing as don't believe related to mod_wsgi.
