### ISSUE TITLE
Django module not found after recent software update

### ISSUE THREAD

**Issue by cgrevisse** [GrahamDumpleton/mod_wsgi#553]
Dear Graham,

On an Ubuntu 16.04 server, I have a Django (2.0.4) web app running with Python 3.6 (no virtual env), with mod_wsgi 4.7.1 installed. Everything has worked perfect for the last two years, until I did a software update 4 days ago, on April 1, which, among others, upgraded 

```
libapache2-mod-wsgi-py3:amd64 (4.3.0-1.1build1, 4.3.0-1.1ubuntu1)`
```

For the rest I haven't touched anything on my Apache (2.4.18) configuration or Python scripts. Before this software update, all worked fine.

But now, an error 500 is thrown, the logs stating the usual `No module named 'django'` error being raised by the `wsgi.py` script.

Are you aware of some potential issue related to this update, or are other users maybe experiencing something similar? Any help is greatly appreciated!

Kind regards,

Christian

**Comment by Virg29** [comment]
/var/log/apache2/error.log 

`[Sun Apr 05 17:51:06.871185 2020] [mpm_event:notice] [pid 20786:tid 139993585105856] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 mod_wsgi/4.5.17 Python/3.6 configured -- resuming normal operations` 
from apache2 conf
```
<VirtualHost *:443>
        ServerName api.ddtss.ru

        <Directory /home/django/backend/backend>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

    WSGIDaemonProcess backend python-home=/home/django/backend/back python-path=/home/django/backend/backend
    #WSGIDaemonProcess backend python-path=/home/django/backend:/home/django/backend/back/lib/python3.6/site-packages
    WSGIProcessGroup backend

    #WSGIScriptAlias / /home/django/backend/wsgi.py
        #RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
        #ProxyPreserveHost On
        #ProxyPass /api/ http://localhost:8000/
        #ProxyPassReverse /api/ http://localhost:8080/
        #ProxyPass /api/ http://127.0.0.1:8081/api/tests/
        #ProxyPassReverse /api/ http://127.0.0.1:8081/api/tests/

</VirtualHost>

```

```
apachectl -S
VirtualHost configuration:
*:443                  is a NameVirtualHost
         default server ddtss.ru (/etc/apache2/sites-enabled/000-default-le-ssl.conf:2)
         port 443 namevhost ddtss.ru (/etc/apache2/sites-enabled/000-default-le-ssl.conf:2)
                 alias www.ddtss.ru
                 alias api.ddtss.ru
         port 443 namevhost api.ddtss.ru (/etc/apache2/sites-enabled/000-default-le-ssl.conf:45)
*:80                   is a NameVirtualHost
         default server api.ddtss.ru (/etc/apache2/sites-enabled/000-default.conf:2)
         port 80 namevhost api.ddtss.ru (/etc/apache2/sites-enabled/000-default.conf:2)
         port 80 namevhost ddtss.ru (/etc/apache2/sites-enabled/000-default.conf:10)
                 alias www.ddtss.ru
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex default: dir="/var/run/apache2/" mechanism=default
Mutex watchdog-callback: using_defaults
Mutex rewrite-map: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex ssl-stapling: using_defaults
Mutex proxy: using_defaults
Mutex ssl-cache: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33

```
request to subdomain with wsgi responses with main document root index.html file

thank you for your help

**Comment by GrahamDumpleton** [comment]
Are these meant to be two separate reports for a problem, or related to the same? They are different versions in the setup. Do not post new questions/problems on an existing issue if the same subject. Please clarify the relationship between the two posts so far so know what can be ignored.

**Comment by cgrevisse** [comment]
As far as I'm concerned, I don't see any relation of Virg29's post under my question.

**Comment by GrahamDumpleton** [comment]
In your post you claim to be using mod_wsgi 4.7.1, yet you talk about upgrading libapache2-mod-wsgi-py3 with a version 4.3.0.

If you were using 4.7.1 that would imply you had installed from mod_wsgi source code as it is highly unlikely that the system package libapache2-mod-wsgi-py3 is the latest version, so 4.3.0 in its version likely does refer to the mod_wsgi version it contains.

If you have installed mod_wsgi from source code you should not have the system package for mod_wsgi installed at all. Upgrading it has likely overwritten the mod_wsgi binary you had installed from source code into the Apache modules directory.

So are you installing mod_wsgi from source code or not, if yes, using which method?

If you are installing from source code, you should not have the system package for mod_wsgi installed, or at the least you should not enable it, and you need to install your mod_wsgi.so from source in a different location to where the system package would put its so they don't conflict.

**Comment by cgrevisse** [comment]
My bad, indeed I had a conflicting installation of multiple mod_wsgi versions. Removed all of them and installed 4.7.1 freshly from the sources, working perfect now. Thanks for pointing me to this issue!
