### ISSUE TITLE
Invalid command 'WSGIDaemonProcess'

### ISSUE THREAD

**Issue by cuervaceo** [GrahamDumpleton/mod_wsgi#554]
Hi Graham!

I'm getting this error while I'm trying to restart apache service

**AH00526: Syntax error on line 74 of C:/Apache24/conf/extra/httpd-vhosts.conf:
Invalid command 'WSGIDaemonProcess', perhaps misspelled or defined by a module not included in the server configuration**

In fact, first I had the same issue as the [#535 ](https://github.com/GrahamDumpleton/mod_wsgi/issues/535)
I read the comments there and I take some recomendation that you tell him.
As you recommend I run the next command 

(venv) C:\Apache24\htdocs\virtualenvs\py37>pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
Because before I didn't get the output of the  "LoadFile"

After of include the LoadFile I still had the error, so after that i deleted the WSGIPythonHome "c:/apache24/htdocs/py3/env"  line and I hadn't the error but now when I'm trying to restart the service I get the other error that I comment at the beginning.

This is my httpd-vhosts file
[httpd-vhosts.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/4440783/httpd-vhosts.conf.txt)

**Comment by GrahamDumpleton** [comment]
``WSGIDaemonProcess`` directive, which is daemon mode, is not supported on Windows. It is Linux/Unix systems only.

**Comment by cuervaceo** [comment]
Thank you for your reply.

So on Windows I just need the WSGIScriptAlias directive?

**Comment by GrahamDumpleton** [comment]
And whatever ``mod_wsgi-express module-config`` output for you to include in the Apache config file.

**Comment by GrahamDumpleton** [comment]
Make sure you tell me if using the develop version from GitHub avoids the problem in the linked issue. Been waiting for someone to tell me whether it helps, or causes a new issue.

**Comment by cuervaceo** [comment]
Sorry for the late response.
I think it works.

At least for me it works and I istalled it following the instructions [here](https://github.com/GrahamDumpleton/mod_wsgi/tree/develop/win32)
After of install the Microsoft Build Tools, I installed mod_wsgi via pip and as I didn't get the LoadFile from the command `mod_wsgi-express module-config`,  only ran the extra command 
`pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip`

Now I only have an issue in the code of my wsgi file, but I think the main problem is solved.

**Comment by cuervaceo** [comment]
Hi Graham, as I'd commenting you, now I get this issue
**[Wed Apr 08 09:39:00.056216 2020] [wsgi:warn] [pid 14272:tid 800] (70008)Partial results are valid but processing is incomplete: mod_wsgi (pid=14272): Unable to stat Python home c:/apache24/htdocs/py3/env. Python interpreter may not be able to be initialized correctly. Verify the supplied path and access permissions for whole of the path.**

Do you know which could be the problem?

**Comment by GrahamDumpleton** [comment]
Besides the warning it is working right???

The code does some checks to try and determine whether what is being referred to is a virtual environment or not. I suspected the checks wouldn't work on Windows which is why was waiting for someone to check. They are warnings though and it only prints the warning and doesn't do anything else. So if everything otherwise works, I just need to not do the checks on Windows, or work out how would do the checks on Windows.

**Comment by cuervaceo** [comment]
As I could see, it was working rightly.

In fact, I only commented the WSGIPythonHome directive again and I didn't have the problem.
I don't know why the WSGIPythonHome gives me that issue.
But now, when I send a request, the browser only stay loading without response:

In my apache log file I get:
![error_log_file](https://user-images.githubusercontent.com/57247418/78945593-521c1580-7a86-11ea-87e2-7933a8c77791.png)

My wsgi file looks like:
![wsgi_file](https://user-images.githubusercontent.com/57247418/78945627-6829d600-7a86-11ea-9b59-fd39a94b594c.png)

And my __init__ file:
![init_file](https://user-images.githubusercontent.com/57247418/78946805-4c73ff00-7a89-11ea-8857-3e915d05ef73.png)

I don't know if is the correct way of configure the wsgi file.

**Comment by cuervaceo** [comment]
I've solved the issue, the main topic of this issue only needed remove the WSGIDaemonProcess 
 and WSGIProcessGroup directives, due to this isn't supported on Windows as @GrahamDumpleton  told me.

About my wsgi file, well, in my __init__ file I needed create a [factorie](https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/) function and only call it in my wsgi file.

Thank you very much Graham!   :D

**Comment by GrahamDumpleton** [comment]
The reason for the reloader error was because the code was calling ``application.run()``, which was starting the Flask development server. Normally you would use:

```
if __name__ == "__main__":
    application.run()
```

That way only runs if script run as a script file outside of Apache.

**Comment by cuervaceo** [comment]
@GrahamDumpleton 
I just want to make you one more question.

I want to set my flask app visible for all user in an internal network, and I want know if is necessary an extra configuration in mod_wsgi if so, there is information in the mod_wsgi docs?

Because I've tried and only some computers can achieve the connection, like if the number of users or conecctions  was limited.
And there isn't a pattern in the computers that let me say, well is for this reason or for this configuration.
I compared my apache conf file with other conf file in which there is a system using php in side of server and my configurations are all right.
So I was wondering if is necessary an extra configuration in mod_wsgi like a directive.

Or what do you suggest me?

**Comment by GrahamDumpleton** [comment]
If some computers can connect, then there is no reason others shouldn't be able to so long as they have the network connectivity to access the same sub network your computer is on.
