### ISSUE TITLE
unable to find django module while using mod_wsgi 

### ISSUE THREAD

**Issue by bisalgt** [GrahamDumpleton/mod_wsgi#556]
I have created a virtual environment using #pipenv -python 3.7. And installed all the dependencies inside the virtual environment which is created inside /home/ec2-user/.local/venvs/project1. 
I had created the project inside /var/www so that there wouldn't be any permission issues but when creating the virtual environment it is automatically created inside /home/ec2-user/.local/venvs. First the error log of apache was showing permission denied. After I did #sudo chmod 755 -R /home   the permission denied error is gone. And the new error is django module not found. What might be the solutions. Couldn't figure out what is going wrong.
Have been following the wsgi issues but couldn't get it right. Also the project worked with django local server , now i wanted it to work with Apache server and deploy on amazon ec2. 
Thank you.

**Comment by GrahamDumpleton** [comment]
What is your mod_wsgi configuration from the Apache configuration file? Have you read:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

on how to configure mod_wsgi for a virtual environment?

**Comment by bisalgt** [comment]
Yes i do read the link that you shared. I had configured mod_wsgi with python3.7 by using the path of python3.7 under /usr/bin/python3.7 and apxs under /usr/bin/apxs. The project is not working and showing django module not.found. I think its the virtual environment that apache can't find. I had used the root directory of my project virtual environment containing bin folder. I have properly set the  python-path so that the virtual environment can be accessed.

**Comment by GrahamDumpleton** [comment]
Asking again. What is your mod_wsgi configuration from the Apache configuration file? No point trying to explain it to me, I need to see the actual configuration so can verify what you are trying to do.

**Comment by bisalgt** [comment]
I am sorry to say that I would take some time.  I would post the configuration file once I reach home. Thank you sir.

**Comment by GrahamDumpleton** [comment]
When you have the time, as well as providing the configuration, also from the command line, activate the Python virtual environment you are expected to use as run Python. At the interpreter prompt do:

```
import django
django.__file__
```

What does it display for the value of ``django.__file__``.

**Comment by bisalgt** [comment]
Sure, I will do that once I get access to the laptop. Thank you.

**Comment by bisalgt** [comment]
While I hit import django inside the shell after activating the virtual environment it show no module name django. It seems like there is more problem. I couldnot even import the django.

**Comment by bisalgt** [comment]
While i hit import django after entering python, django module is not found. But when i entered the shell after using python3, django is imported and can be seen in the file attached.
![dj1](https://user-images.githubusercontent.com/43409127/79108177-7da84400-7d95-11ea-94d1-034660b0a3ab.png)

**Comment by GrahamDumpleton** [comment]
Looks like you installed Django by running:

```
pip install --user django
```

You need to install it into the virtual environment.

When using a virtual environment, the per user site-packages directory is not used as a fallback.

**Comment by GrahamDumpleton** [comment]
Ahh, wait is is pipenv nonsense. Let me look again.

**Comment by GrahamDumpleton** [comment]
When the virtual environment is activated, what do get in interpreter for:

```
import sys
sys.prefix
```

**Comment by bisalgt** [comment]
No that was not the case. I used
`pipenv install django==3.0` to install django. Also this problem seem like something as `python manage.py runserver` didn't work and `python3 manage.py runserver`.

**Comment by bisalgt** [comment]
while hitting import sys and sys.prefix i am getting "/home/ec2-user/.local/share/virtualenvs/suggestor_project-kFsvpsgD"

"

**Comment by bisalgt** [comment]
`python3 manage.py runserver worked but python manage.py runserver didn't work`. seems like i got something problem with python or environment.

**Comment by bisalgt** [comment]
And previously `python manage.py runserver` used to work.

**Comment by GrahamDumpleton** [comment]
So use ``/home/ec2-user/.local/share/virtualenvs/suggestor_project-kFsvpsgD`` as the path for ``WSGIPythonHome`` or ``python-home`` option to ``WSGIDaemonProcess``.

**Comment by bisalgt** [comment]
Yes i did that in the project. Sorry that i am unable to provide the configuration file now.

**Comment by bisalgt** [comment]
I used `python-home` in `WSGIDaemonProcess`

**Comment by bisalgt** [comment]
Hello Graham Sorry that I couldn't give you response on time. I have access to the instance that I had been talking about and I have attached django.conf file configuration which is inside /var/httpd/conf.d/. I have also attached the error log file of apache server, django-error.log and output of sys.prefix in my virtual environment. 
I am still getting unable to import django. What might be the cause. Thank you.
![apache-error-log](https://user-images.githubusercontent.com/43409127/79185150-d6c7b480-7e35-11ea-8ad0-10cf59fdcb3e.png)
![django-conf](https://user-images.githubusercontent.com/43409127/79185155-d92a0e80-7e35-11ea-9f0b-8d98ab649724.png)
![django-error-log](https://user-images.githubusercontent.com/43409127/79185157-da5b3b80-7e35-11ea-91ee-c9812fa02b10.png)
![sys-prefix-output](https://user-images.githubusercontent.com/43409127/79185161-db8c6880-7e35-11ea-99de-93f1635e42bd.png)

**Comment by GrahamDumpleton** [comment]
Your second ``WSGIProcessGroup`` directive should be ``WSGIApplicationGroup``. The first one should have as first argument ``django_app``, not ``python_project``.

**Comment by bisalgt** [comment]
Thank you Graham, that was the mistake. I tried to restart the apache server after changing the configuration in django.conf but couldnot restart the apache server, the error shown is attached below. Even though I could not restart the server, I could still access the browser port at 8000 and its working.  Couldn't think what is missing here. 
![apache-restart](https://user-images.githubusercontent.com/43409127/79187695-b4856500-7e3c-11ea-8d20-e569cb4b86d7.png)

**Comment by GrahamDumpleton** [comment]
Make sure you aren't running Django development server on port 8000 at the same time. You can't have both Apache and something else trying to use same port.

**Comment by bisalgt** [comment]
500 Internal server error has occured. And I couldnot get the site working. I had stopped everything and restarted the server. The server restarts and I couldnot run the django project at 8000. I have attached django-error.log file screenshot. Please kindly let me know what is going wrong. Every configuration is right.
![django-error-log1](https://user-images.githubusercontent.com/43409127/79188866-f19f2680-7e3f-11ea-836e-f9846ccb0502.png)

**Comment by GrahamDumpleton** [comment]
Show me your current configuration so I can see you understood what changes I said needed to be made. And can you stop pasting images. Paste it as text so I can cut and paste corrected version.

**Comment by bisalgt** [comment]
I have attached the new conf. I had done as per your suggestions.
![django-conf-1](https://user-images.githubusercontent.com/43409127/79189253-fe704a00-7e40-11ea-845f-767d3e08be2a.png)

**Comment by bisalgt** [comment]
Should I need to keep process=2 threads =sth at WSGIDaemonProcess. I have removed that from previous django.conf thinking that it was unnecessary.

**Comment by GrahamDumpleton** [comment]
That is still am image, not text and you didn't make the corrections as tried to explain.

You want:

```
WSGIProcessGroup django_app
WSGIApplicationGroup %{GLOBAL}
```

Not:

```
WSGIProcessGroup django_app
WSGIProcessGroup %{GLOBAL}
```

That second ``WSGIProcessGroup`` was wrong and overriding the first. It was meant to be ``WSGIApplicationGroup``.

**Comment by bisalgt** [comment]
Thank you Graham that was the issue. Once I changed the configuration as per your guidance It really solved the issue of django module not found. Thank you so much.
