### ISSUE TITLE
localhost runs nltk but couldnot find nltk.stopwords while using with mod_wsgi with apache server

### ISSUE THREAD

**Issue by bisalgt** [GrahamDumpleton/mod_wsgi#558]
I am using ntlk for the project and I have used mod_wsgi to configure with apache server. It worked on the localhost but while I tried with apache server to run the code. It shows LookUpError. It is something related to the path. I have tried import nltk and nltk.download('stopwords') in the shell and it shows downloading at path "/home/ec2-user/nltk-data". I also tried adding the path using nltk.data.path.append('/home/ec2-user/nltk-data'). I have also given that directory 
permission to access the directory in wsgi configuration file. I had also used import sys and sys.path.append('/home/ec2-user/nltk_data'). But somehow the app is not searching nltk at the downloaded folder. I think appending the path would work but it didn't and still with this issue. I have also attached the output while accessing to 8000 port. Please do find the attached file and also suggest me for the possible solutions. Thank you.

![nltk](https://user-images.githubusercontent.com/43409127/79195651-5bbec800-7e4e-11ea-8942-31b82600f766.png)

**Comment by GrahamDumpleton** [comment]
What do you get when run:

```
ls -als /home/ec2-user/nltk-data
```

**Comment by bisalgt** [comment]
As i was unable to add the path so I downloaded nltk_data at the folder inside the path that is used to search. I downloaded nltk_data in `/home/ec2-user/.local/share/virtualenvs/python_project-HJCA0TAZ\nltk-data` and now the error is gone. can this be a good solution to my problem as the error is gone.

**Comment by bisalgt** [comment]
Also while hitting this `ls -als /home/ec2-user/nltk-data` i got `cannot access /home/ec2-user/nltk-data: No such file or directory`

**Comment by GrahamDumpleton** [comment]
Not idea to put stuff in the virtual environment like that, but if putting it at that directory works then fine for now at least while work out a better solution. You will just need to remember to add it back if ever trash the virtual environment and recreate it.

**Comment by bisalgt** [comment]
I get the file attached below while using `ls -als /home/ec2-user/nltk_data` .
![nltkdownload](https://user-images.githubusercontent.com/43409127/79198839-d2aa8f80-7e53-11ea-8af0-8c911482c652.png)

**Comment by GrahamDumpleton** [comment]
At the very start of the WSGI application script file add:

```
import os
os.environ['NLTK_DATA'] = '/home/ec2-user/nltk_data'
```

and see if that works to have it find it at that directory instead.

**Comment by bisalgt** [comment]
Thank you Graham so much. Downloading nltk_data on the searched folder also worked but I preferred adding the code mentioned above to the wsgi script file. My project is now up and running all thanks to you. Your answers are precious. Thanks a lot.
