### ISSUE TITLE
Using mod_wsgi in Windows WITHOUT line WSGIApplicationGroup %{GLOBAL} in httpd.conf

### ISSUE THREAD

**Issue by mcfoi** [GrahamDumpleton/mod_wsgi#560]
In  a recent thread a successful installation of 
Apache 2.4.41 64bit VC14
Python 3.7 64bit
mod_wsgi development
(`pip-3.7.exe install --no-cache-dir -U https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip`)

could make a Django App (Django 3.0.4) 
by adding line
WSGIApplicationGroup %{GLOBAL}
in httpd.conf

How can this be overcome to have multiple VirtualHosts with multiple virtualenvs for different applications?

**Comment by GrahamDumpleton** [comment]
You can't on Windows if you are using any of the third party Python packages which use a C extension that doesn't work in sub interpreters and thus requires that ``WSGIApplicationGroup`` settings. Many of the numpy/scipy related packages don't work. If you can provide ``pip freeze`` output we can look at what may be the suspect package.

The only way around it that I can think of would be to have one Django instance and use the Django sites framework to allow different sites within the one Django instance.

You could only use sub interpreters for other sites in same Windows Apache instance if can work out that they don't use one of these packages that causes problems.

On UNIX systems the solution would be to use mod_wsgi daemon mode and have each site be its own daemon process group, but that mode isn't on Windows mod_wsgi version.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
