### ISSUE TITLE
Apache2 serving my website as a list of files.

### ISSUE THREAD

**Issue by corei8** [GrahamDumpleton/mod_wsgi#564]
The issue that I am having is that Apache is only serving my files on an "Index of /" page, rather than serving my site. I am new to Apache and mod_wsgi and have tried setting up my site by following many online tutorials and guides. I think that I have it mostly set up but there is a misconfiguration somewhere that I cannot detect.

**site.wsgi:**
```python
#!/usr/bin/python3.6

import sys
sys.path.insert(0, "/var/www/site.org/")
import app as application
if __name__ == '__main__':
    application.run()
```

**site.conf:**
```
LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so

User www-data 
Group www-data 

<VirtualHost *:80>

    DocumentRoot /var/www/site.org

    ServerAdmin user@email.com

    ServerName site.org
    ServerAlias www.site.org

    ErrorLog /var/www/site.org/logs/error.log
    CustomLog /var/www/site.org/logs/access.log combined

    WSGIScriptAlias /site.org /var/www/wsgi_scripts/site.wsgi
    WSGIDaemonProcess site.org python-home=/var/www/site.org/env python-path=/var/www/site.org/app threads=5

    Alias /static/ /var/www/site.org/app/static

    <Directory /var/www/site.org>
        WSGIProcessGroup site.org
        WSGIApplicationGroup %{GLOBAL}
        WSGIScriptReloading On
        Require all granted
    </Directory>

</VirtualHost>
```
**Directory Tree:**
```
site.org
├── app
│   ├── __init__.py
│   ├── models.py
│   ├── routes.py
│   ├── site.db
│   ├── static
│   └── templates
├── application.py
├── config.py
├── env
└── requirements.txt
```

**Comment by corei8** [comment]
I placed an `index.html` file in `site.org` and it is being served correctly. Is there a default Apache configuration that I have to disable so that mod_wsgi can work?

**Comment by GrahamDumpleton** [comment]
You have your WSGI application hosted at a sub path of the site:

```
WSGIScriptAlias /site.org /var/www/wsgi_scripts/site.wsgi
```

If you want it at the root of the site use:

```
WSGIScriptAlias / /var/www/wsgi_scripts/site.wsgi
```

This is also wrong:

```
    <Directory /var/www/site.org>
        WSGIProcessGroup site.org
        WSGIApplicationGroup %{GLOBAL}
        WSGIScriptReloading On
        Require all granted
    </Directory>
```

The path to directory should match the path to the directory holding the WSGI script file.

```
    <Directory /var/www/wsgi_scripts>
        WSGIProcessGroup site.org
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
```

You would possibly have got a forbidden error. Also, your WSGI application wouldn't have run in the daemon process group as intended.

You also don't need:

```
WSGIScriptReloading On
```

And if want to use daemon mode, recommend adding at global scope in Apache configuration, outside of VirtualHost:

```
WSGIRestrictEmbedded On
```

That way you will get an error when you muck of config in delegating WSGI applications to daemon process groups.

**Comment by corei8** [comment]
Thank you very much!

I have implemented all of your changes except the very last.

Now I am receiving a 500 error with error.log reporting:
```
[Wed Apr 22 23:36:44.313987 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075] mod_wsgi (pid=26937): Target WSGI script '/var/www/wsgi_scripts/site.wsgi' cannot be loaded as Python module.
[Wed Apr 22 23:36:44.314585 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075] mod_wsgi (pid=26937): Exception occurred processing WSGI script '/var/www/wsgi_scripts/site.wsgi'.
[Wed Apr 22 23:36:44.314619 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075] Traceback (most recent call last):
[Wed Apr 22 23:36:44.314645 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075]   File "/var/www/wsgi_scripts/site.wsgi", line 7, in <module>
[Wed Apr 22 23:36:44.314718 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075]     import app as application
[Wed Apr 22 23:36:44.314731 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075]   File "/var/www/site.org/app/__init__.py", line 1, in <module>
[Wed Apr 22 23:36:44.314777 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075]     from flask import Flask
[Wed Apr 22 23:36:44.314804 2020] [wsgi:error] [pid 26937:tid 140644869666560] [remote 166.137.90.89:52075] ImportError: No module named flask
```

I have run into this before and I am not sure what is happening.

**Comment by GrahamDumpleton** [comment]
Can be for a few reasons.

The first is that you still aren't setting configuration such as the daemon process group is used. Which is why it is important to set ``WSGIRestrictEmbedded On`` as it will catch that mistake.

The second is that you haven't set up ``python-home`` to properly reference the Python virtual environment you are using. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

The value to it should be what ``sys.prefix`` is for the virtual environment.

The third is that you don't actually have ``flask`` installed into the virtual environment and haven't actually be using a virtual environment and instead have been installing packages into the per user ``site-packages`` directory using ``pip install --user``. Such a per user ``site-packages`` directory will be ignored, the packages need to be installed into the Python virtual environment.

The fourth is that when creating the Python virtual environment or installing packages you have done it as ``root`` and it had a restrict ``umask`` which means that directories/files are not actually accessible to the user that Apache runs your code as. If setting up the Python virtual environment and installing packages in it as ``root``, you need to ensure the ``umask`` or the ``root`` terminal session is ``0755`` and not ``0750``.

**Comment by corei8** [comment]
`$ ls -l site.org` gives:
```bash
drwxr-xr-x 6 www-data root  4096 Apr 22 23:24 app
-rw-r--r-- 1 www-data root   144 Apr 22 18:44 application.py
-rw-r--r-- 1 www-data root  1224 Apr 22 17:28 config.py
drwxr-xr-x 4 www-data root  4096 Apr 22 16:12 env
-rw-r--r-- 1 www-data root   979 Apr 22 02:06 requirements.txt
-rw-r--r-- 1 www-data root   153 Apr 22 23:21 site.wsgi
```

Current state of `site.org.conf`:
```
LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so

User www-data

Group www-data

WSGIRestrictEmbedded On

<VirtualHost *:80>

    DocumentRoot /var/www/site.org

    ServerAdmin user@email.com

    ServerName site.org
    ServerAlias www.site.org

    ErrorLog /var/www/site.org/logs/error.log
    CustomLog /var/www/site.org/logs/access.log combined

    WSGIScriptAlias / /var/www/wsgi_scripts/site.wsgi
    WSGIDaemonProcess site.org python-home=/var/www/site.org/env python-path=/var/www/site.org/app threads=5

    Alias /static/ /var/www/site.org/app/static

    <Directory /var/www/wsgi_scripts>
        WSGIProcessGroup site.org
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>

</VirtualHost>
```

I have changed and checked all that you mentioned. I do really appreciate your help. I am still getting a 500 error though.

I still have a:
```
Target WSGI script '/var/www/wsgi_scripts/site.wsgi' cannot be loaded as Python module
```
And then a little later in the log I get a `no module named Flask` error.

I assume that I still have a configuration issue that "skips" over the `.wsgi` file, after it fails in some way, and that prevents my virtual environment from being started?

**Comment by GrahamDumpleton** [comment]
Where is the ``Flask`` package installed.

If you run command line interpreter, activating the Python virtual environment first as necessary, what do you get when at the interpreter prompt you do:

```
import Flask
print(Flask.__file__)
```

**Comment by corei8** [comment]
`ModuleNotFoundError: No module named 'Flask'`

**Comment by GrahamDumpleton** [comment]
Which means you haven't installed the ``Flask`` package in the first place to where you think you do. Certainly not in the Python virtual environment you tried to get mod_wsgi to use if you had activated that before the test.

**Comment by GrahamDumpleton** [comment]
And you do not it is actually lower case, not upper case.

```
from flask import Flask
```

**Comment by corei8** [comment]
I have a strange issue. I have "Flask" installed, but when I tried to install "flask" using `pip3 install flask`, it said that the requirement was already satisfied in `/home/ubuntu/....`

**Comment by GrahamDumpleton** [comment]
That is not the issue. When installing you can say ``Flask`` or ``flask`` as case doesn't actually matter. So you have it installed.

Your code though should use lower case when installing the module. Try the interpreter again but use:

```
import flask
print(flask.__file__)
```

I didn't pick up initially that it wasn't lower case in your code.

**Comment by corei8** [comment]
`ModuleNotFoundError: No module named 'flask'`

All of my source code, including my `requirements.txt` file, were previously used successfully in an Elastic Beanstalk environment on AWS.

**Comment by GrahamDumpleton** [comment]
From the command line interpreter, what do you get for:

```
import sys
sys.version
sys.prefix
```

In other words, lets make sure you are actually running interpreter from same Python installation you are installing the package into.

Also be aware that if you have both Python 2 and Python 3 on your system, if you have installed the mod_wsgi for Python 2, you cannot point it at a virtual environment for Python 3. If you want to use Python 3, you must install mod_wsgi for Python 3 of same X.Y version.

**Comment by corei8** [comment]
```python
>>> import sys
>>> sys.version
'3.6.9 (default, Apr 18 2020, 01:56:04) \n[GCC 8.4.0]'
>>> sys.prefix
'/var/www/site.org/env'
```

I did not understand your last statement:
> If you want to use Python 3, you must install mod_wsgi for Python 3 of same X.Y version.

I currently have installed: `mod-wsgi==4.7.1`

**Comment by GrahamDumpleton** [comment]
The mod_wsgi package is C code. It must be compiled against the specific version of Python you want to use. Your operating system likely has both Python 2.7 and Python 3.X versions of the mod_wsgi package, corresponding to the two system Python versions. You need to make sure you are installing the correct mod_wsgi package.

What do you get if you run:

```
ldd /usr/lib/apache2/modules/mod_wsgi.so
```

**Comment by GrahamDumpleton** [comment]
BTW, when you said:

> I have a strange issue. I have "Flask" installed, but when I tried to install "flask" using pip3 install flask, it said that the requirement was already satisfied in /home/ubuntu/....

The fact that it said ``/home/ubuntu`` means you mustn't have the Python virtual environment activated, or the ``pip`` from the virtual environment wasn't run.

That it mentions the home directory suggests that Flask was previously installed in the per user site packages directory. When using a virtual environment the per user site packages directory is ignored, also suggesting the virtual environment wasn't activate when the install was done.

**Comment by corei8** [comment]
```
        linux-vdso.so.1 (0x00007ffdfab5c000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f8847203000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8846fe4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8846bf3000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f88469d6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f88467d2000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f88465cf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8846231000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f88479b9000)
```

I know that `pip3 freeze` adds all python modules on the system to a requirements.txt file. That happens even if I have the virtualenv activated:
```
ubuntu@ip-:/var/www/site.org$ source env/bin/activate
(env) ubuntu@ip-:/var/www/site.org$ pip3 freeze
appdirs==1.4.3
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
awsebcli==3.17.0
bcrypt==3.1.7
blessed==1.16.1
blinker==1.4
boto3==1.10.45
botocore==1.13.45
cached-property==1.5.1
cement==2.8.2
certifi==2020.4.5.1
cffi==1.12.3
chardet==3.0.4
click==7.1.1
cloud-init==19.4
colorama==0.3.9
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
cycler==0.10.0
distlib==0.3.0
distro-info===0.18ubuntu0.18.04.1
docker==3.7.3
docker-compose==1.23.2
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.15.2
filelock==3.0.12
Flask==1.1.2
Flask-Bcrypt==0.7.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-S3==0.3.3
Flask-SQLAlchemy==2.4.0
Flask-Uploads==0.2.1
Flask-WTF==0.14.2
future==0.16.0
gunicorn==20.0.4
hibagent==1.0.1
httplib2==0.9.2
hyperlink==17.3.1
idna==2.7
importlib-metadata==1.6.0
importlib-resources==1.4.0
incremental==16.10.1
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.9.4
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.1.0
language-selector==0.1
MarkupSafe==1.1.1
mod-wsgi==4.7.1
netifaces==0.10.4
numpy==1.18.0
oauthlib==2.0.6
PAM==0.4.2
pathspec==0.5.9
Pillow==6.1.0
pipenv==2018.11.26
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycodestyle==2.5.0
pycparser==2.19
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
pyparsing==2.4.6
pyserial==3.4
python-apt==1.6.5+ubuntu0.2
python-dateutil==2.8.0
python-debian==0.1.32
pyxdg==0.25
PyYAML==3.13
requests==2.20.1
requests-unixsocket==0.1.5
s3transfer==0.2.1
SecretStorage==2.3.1
semantic-version==2.5.0
service-identity==16.0.0
six==1.14.0
SQLAlchemy==1.3.5
ssh-import-id==5.7
systemd-python==234
termcolor==1.1.0
texttable==0.9.1
Twisted==17.9.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.24.3
virtualenv==20.0.18
virtualenv-clone==0.5.4
wcwidth==0.1.7
websocket-client==0.57.0
Werkzeug==1.0.1
WTForms==2.2.1
yapf==0.29.0
zipp==3.1.0
zope.interface==4.3.2
(env) ubuntu@ip-:/var/www/site.org$
```

**Comment by GrahamDumpleton** [comment]
Your mod_wsgi system package is built for Python 2.7 as indicated by:

```
libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f8847203000)
```

You need to uninstall it and if you are using system Python 3.6, work out what the name of the Python 3.6 variant of the system package for mod_wsgi is and install it instead.

**Comment by corei8** [comment]
Ok. Thank you. I will try that and see what happens.

**Comment by corei8** [comment]
I think that we are making some progress.

`ldd /usr/lib/apache2/modules/mod_wsgi.so` yields:
```
linux-vdso.so.1 (0x00007ffeda7d9000)
	libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007fc7c364a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc7c342b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc7c303a000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fc7c2e08000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc7c2beb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc7c29e7000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fc7c27e4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc7c2446000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc7c3f2f000)
```

I am thinking of replacing `virtualenv` with `pipenv`, which I think will fix some virtualenv issues that I am having.

**Current error**:
```
[Thu Apr 23 16:31:47.916853 2020] [wsgi:error] [pid 4970:tid 139736339928832] [remote 34.216.54.117:40444] mod_wsgi (pid=4970): Failed to exec Python script file '/var/www/wsgi_scripts/site.wsgi'.
[Thu Apr 23 16:31:47.916918 2020] [wsgi:error] [pid 4970:tid 139736339928832] [remote 34.216.54.117:40444] mod_wsgi (pid=4970): Exception occurred processing WSGI script '/var/www/wsgi_scripts/site.wsgi'.
```
... and then the usual `ModuleNotFoundError: No module named 'flask'`.
Is the `failed to exec Python script file` an indication of an error in my script?
**site.wsgi:**
```python
#!/usr/bin/python3.6

import sys
sys.path.insert(0, "/var/www/site.org/")
import app as application
if __name__ == '__main__':
    application.run()
```

**Comment by corei8** [comment]
Thank You!

I still have configuration issues with the site but I have it running for the most part. I basically reinstalled everything, "repermissioned" everything and it started working. Thank you!
