### ISSUE TITLE
NameError when importing Django templates folder

### ISSUE THREAD

**Issue by funaesthesia** [GrahamDumpleton/mod_wsgi#568]
I want to link to my initial issue submit at the asgiref module because I thought it was a problem on that side. Well, I'm not sure where it is... 
For some more comments see this: https://github.com/django/asgiref/issues/157

Summary what I did:

- new Linux install with Ubuntu 18.04, sudo apt-get install python3.8 python3.8-venv
- installed mod_wsgi in accord with the docs
- started a new Django project with a dedicated venv and everything worked fine up to the point where I introduce a project-wide template folder and point to it in the settings.py

Insert this:
```
TEMPLATES = [
    {
        ...
        'DIRS': [os.path.join(BASE_DIR,'templates'),],
        ....

    },
]
```

Then I get this:

```
[Tue May 05 19:57:52.653410 2020] [mpm_event:notice] [pid 10734:tid 140655679445952] AH00491: caught SIGTERM, shutting down

Exception ignored in: <function Local.__del__ at 0x7fece48a09d0>
Traceback (most recent call last):
  File "/var/www/my_app/.my_app/lib/python3.8/site-packages/asgiref/local.py", line 95, in __del__
NameError: name 'AttributeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7fece48a09d0>
Traceback (most recent call last):
  File "/var/www/my_app/.my_app/lib/python3.8/site-packages/asgiref/local.py", line 95, in __del__
NameError: name 'AttributeError' is not defined

[Tue May 05 19:57:52.815381 2020] [mpm_event:notice] [pid 11050:tid 140050920782784] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations

[Tue May 05 19:57:52.815626 2020] [core:notice] [pid 11050:tid 140050920782784] AH00094: Command line: '/usr/sbin/apache2
```

**Comment by funaesthesia** [comment]
If I have the template in the app (my_app/templates/) it doesn't work either.

**Comment by GrahamDumpleton** [comment]
This is because the process is being shutdown and part way through the process of the Python interpreter being destroyed, it has triggered the execute of some cleanup code in a Python object. Because though the interpreter is in the process of being destroyed, many things simply don't exist any more. Usually one sees error about objects suddenly appearing to be ``None`` since lookups of various objects that don't exist will return ``None`` instead, this is just a variation of the problem.

So long as this only occurs when the process is being terminated and the interpreter destroyed, it is okay and there isn't much you can do about it.

**Comment by proy87** [comment]
@GrahamDumpleton , what is the reason for the process being terminated or the interpreter destroyed. Were there any settings for these set?

I also encountered these intermittent errors. I have a default Apache configuration.

**Comment by GrahamDumpleton** [comment]
In the context of Apache/mod_wsgi processes could be terminated for various reasons.

* If running your WSGI application in embedded mode, you will be affected by Apache's automatic scaling of the number of Apache child worker processes.
* You could also be affected by Apache in general being restarted. On Linux systems which don't use Apache logging but an external log manager, this can occur at least once a day as the log system will restart Apache.
* You manually restart Apache.
* If running your WSGI application in daemon mode you are using ``maximum-requests``, ``request-timeout`` or various other options to ``WSGIDaemonProcess`` directive which can result in process restarts.
* If running your WSGI application in daemon mode, source code reloading is not disabled, and you modify the WSGI application script file.

Without seeing your Apache configuration for mod_wsgi it is not possible to be more specific.

**Comment by proy87** [comment]
@GrahamDumpleton , thank you for response.
I think it has nothing to do with WSGI application in my case, since my apache config is the following:

         <Directory /project/django/proj>
           <Files wsgi.py>
               Require all granted
           </Files>
        </Directory>

        WSGIDaemonProcess proc python-path=/project/django python-home=/project/venv
        WSGIProcessGroup proc
        WSGIScriptAlias / /project/django/proj/wsgi.py

**Comment by GrahamDumpleton** [comment]
If you set:

```
LogLevel info
```

for any exceptional cases, you should get extra logging from mod_wsgi as to why daemon mode processes were restarted.

If it always occurs at certain times of the day, I would say it is log rotation.

**Comment by proy87** [comment]
Thank you very much. I'll try.

**Comment by proy87** [comment]
@GrahamDumpleton , that's the output I have.

[Wed Dec 02 00:00:07.121026 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Shutdown requested 'proc'.
[Wed Dec 02 00:00:07.122257 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Stopping process 'proc'.
[Wed Dec 02 00:00:07.122280 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Destroying interpreters.
[Wed Dec 02 00:00:07.122287 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Destroy interpreter '127.0.0.1:8080|'.
[Wed Dec 02 00:00:07.125710 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): End interpreter '127.0.0.1:8080|'.
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f2e149e8a60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <function Local.__del__ at 0x7f2e149dbe50>
Traceback (most recent call last):
  File "/proc/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f2e149dbe50>
Traceback (most recent call last):
  File "/proc/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f2e149dbe50>
Traceback (most recent call last):
  File "/proc/venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 02 00:00:07.436384 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Cleanup interpreter ''.
[Wed Dec 02 00:00:07.437610 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Terminating Python.
[Wed Dec 02 00:00:07.444811 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Python has shutdown.
[Wed Dec 02 00:00:07.444857 2020] [wsgi:info] [pid 161159:tid 139836055342144] mod_wsgi (pid=161159): Exiting process 'proc'.
[Wed Dec 02 00:00:07.606670 2020] [wsgi:info] [pid 174277:tid 139836055342144] mod_wsgi (pid=174277): Attach interpreter ''.
[Wed Dec 02 00:00:07.611556 2020] [wsgi:info] [pid 174277:tid 139836055342144] mod_wsgi (pid=174277): Adding '/project/django' to path.
[Wed Dec 02 00:01:47.414331 2020] [wsgi:info] [pid 174277:tid 139836026480384] mod_wsgi (pid=174277): Create interpreter '127.0.0.1:8080|'.
[Wed Dec 02 00:01:47.418181 2020] [wsgi:info] [pid 174277:tid 139836026480384] mod_wsgi (pid=174277): Adding '/project/django' to path.
[Wed Dec 02 00:01:47.418585 2020] [wsgi:info] [pid 174277:tid 139836026480384] [remote 127.0.0.1:40538] mod_wsgi (pid=174277, process='proc', application='127.0.0.1:8080|'): Loading Python script file '/project/django/proj/wsgi.py'.

Why the process was shutted down and why new interpreter was created 1 minute and 40 seconds after attaching?

Thank you.

**Comment by GrahamDumpleton** [comment]
The fact that the restart occurred at the change over of day confirms what I was saying before, which is that Apache was likely asked to restart by the system log rotation service.

The fact that the "Create interpreter" was over a minute later is likely because that was how long it was before a new request arrived. How you have it set up at the moment is because you are using a sub interpreter and it is lazily loading the application on the first request.

Do be aware it is recommended that you force the use of the main interpreter, and not use a sub interpreter as is occurring now. The main interpreter was setup were it said "Attach interpreter ''", but the main interpreter isn't where your application is actually running.

Add to your Apache configuration:

```
WSGIApplicationGroup %{GLOBAL}
```

**Comment by proy87** [comment]
@GrahamDumpleton , thank you very much for your help.
Do I need `WSGIRestrictEmbedded On` and `WSGILazyInitialization On` directives?

**Comment by GrahamDumpleton** [comment]
Do not use ``WSGILazyInitialization`` it is a legacy option for compatibility with how mod_wsgi used to work many many years ago. Changing its default setting can open up security issues, so do not do touch it. The directive should really be removed from mod_wsgi source code now as its need is long gone.

As to ``WSGIRestrictEmbedded On``. Yes, if using daemon mode only it is recommended you set it.

For other recommendations about settings for daemon mode, suggest you watch:

* https://www.youtube.com/watch?v=H6Q3l11fjU0

**Comment by proy87** [comment]
How do I know whether only daemon mode is used?

**Comment by GrahamDumpleton** [comment]
You were using ``WSGIDaemonProcess`` and ``WSGIProcessGroup``. That is daemon mode.

Also read:

* https://modwsgi.readthedocs.io/en/master/user-guides/processes-and-threading.html
* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#embedded-or-daemon-mode
* https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGIDaemonProcess.html

**Comment by proy87** [comment]
Thank you very much.

**Comment by arruda33** [comment]
I have upgraded my AWS EC2 instance from Ubuntu 18.04 to 20.04 and im getting the same error message in my logs. Apache dies randomly though the day and i then can't connect to my site. Restarting the machine fixes the issue (and restarting the service probably does as well). Now i have that same error but my django project uses wsgi so im not sure what is happening here. Any help would be appreciated @GrahamDumpleton

**Comment by GrahamDumpleton** [comment]
@arruda33 If Apache processes are getting shutdown at random times per day, then you may be using embedded mode rather than daemon mode. Not possible to tell unless you provide the mod_wsgi configuration. Also ensure log level is set to info so can see details about what processes are being shutdown and why.

Another reason processes may be getting shutdown is your Apache processes are using too much memory and the Linux OOM killer is deciding to kill them off.
