### ISSUE TITLE
Install of mod_wsgi fails on Windows 8 - Python 3.8.3rc1 (x64) and Apache 2.4.41 (x64)

### ISSUE THREAD

**Issue by GitDidi** [GrahamDumpleton/mod_wsgi#569]
Hello,

I'm struggling with installation of mod_wsgi in Win 8.
Can you please help me.

Specs as per below

1] Python 3.8.3rc1 MSC v.1924 64 bit (AMD64)

2] Server version: Apache/2.4.41 (Win64) Apache Lounge VC14

FULL LOGS:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Admin>cd\

C:\>cd Python38

C:\Python38>set MOD_WSGI_APACHE_ROOTDIR=C:\xampp\apache\bin

C:\Python38>pip install mod-wsgi
Collecting mod-wsgi
  Using cached mod_wsgi-4.7.1.tar.gz (498 kB)
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sy
s.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qlzayusv\\m
od-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pi
p-install-qlzayusv\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();ex
ec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Admin\AppD
ata\Local\Temp\pip-wheel-rybp1x6u'
       cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-qlzayusv\mod-wsgi\
  Complete output (33 lines):
  c:\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution optio
n: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\mod_wsgi
  copying src\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi
  creating build\lib.win-amd64-3.8\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win-amd64-3.8\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win-amd64-3.8\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\server
  creating build\lib.win-amd64-3.8\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\
server\management
  creating build\lib.win-amd64-3.8\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.
8\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.8\
mod_wsgi\server\management\commands
  creating build\lib.win-amd64-3.8\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\docs
  creating build\lib.win-amd64-3.8\mod_wsgi\images
  copying images\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.8\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\src
  creating build\temp.win-amd64-3.8\Release\src\server
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\1
4.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\xampp
\apache\bin/include -Ic:\python38\include -Ic:\python38\include "-IC:\Program Fi
les (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\incl
ude" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Progr
am Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x
86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windo
ws Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\in
clude\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0
.18362.0\cppwinrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.8\Release\
src/server\mod_wsgi.obj
  mod_wsgi.c
  C:\Users\Admin\AppData\Local\Temp\pip-install-qlzayusv\mod-wsgi\src\server\wsg
i_apache.h(42): fatal error C1083: Cannot open include file: 'httpd.h': No such
file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildT
ools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit
status 2
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
    Running setup.py install for mod-wsgi ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qlzayusv\
\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\
pip-install-qlzayusv\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"'
, open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();
exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\
AppData\Local\Temp\pip-record-lz4qk5hk\install-record.txt' --single-version-exte
rnally-managed --compile --install-headers 'c:\python38\Include\mod-wsgi'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-qlzayusv\mod-wsgi\
    Complete output (33 lines):
    c:\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution opt
ion: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\mod_wsgi
    copying src\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi
    creating build\lib.win-amd64-3.8\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win-amd64-3.8\mod_wsgi\server

    copying src\server\environ.py -> build\lib.win-amd64-3.8\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\server
    creating build\lib.win-amd64-3.8\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win-amd64-3.8\mod_wsg
i\server\management
    creating build\lib.win-amd64-3.8\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-
3.8\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.
8\mod_wsgi\server\management\commands
    creating build\lib.win-amd64-3.8\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\doc
s
    creating build\lib.win-amd64-3.8\mod_wsgi\images
    copying images\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.8\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\server
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC
\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\xam
pp\apache\bin/include -Ic:\python38\include -Ic:\python38\include "-IC:\Program
Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\in
clude" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Pro
gram Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Win
dows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\
include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10
.0.18362.0\cppwinrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.8\Releas
e\src/server\mod_wsgi.obj
    mod_wsgi.c
    C:\Users\Admin\AppData\Local\Temp\pip-install-qlzayusv\mod-wsgi\src\server\w
sgi_apache.h(42): fatal error C1083: Cannot open include file: 'httpd.h': No suc
h file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Buil
dTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exi
t status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'i
mport sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\L
ocal\\Temp\\pip-install-qlzayusv\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Use
rs\\Admin\\AppData\\Local\\Temp\\pip-install-qlzayusv\\mod-wsgi\\setup.py'"'"';f
=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r
\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-lz4qk5hk\install-
record.txt' --single-version-externally-managed --compile --install-headers 'c:\
python38\Include\mod-wsgi' Check the logs for full command output.

**Comment by GrahamDumpleton** [comment]
Don't use back slashes in the path, use forward slashes.

```
set MOD_WSGI_APACHE_ROOTDIR=C:/xampp/apache/bin
```

You also claim you are using Apache Lounge distribution, yet they don't refer to it as XAMPP from what I remember.

If you are actually using XAMPP distribution it may not work anyway, as some of the so called XAMPP distributions don't provide everything needed to support building third party Apache modules. Only Apache Lounge I know works for sure.

**Comment by GitDidi** [comment]
Thanks for the reply.

I have followed your advise using the same Apache distro (Xampp) replacing forward slashes with back slashes. installation failed once again with same root cause:

"C:\Users\Admin\AppData\Local\Temp\pip-install-hx0nbd4o\mod-wsgi\src\server\w
sgi_apache.h(42): fatal error C1083: Cannot open include file: 'httpd.h': No suc
h file or directory"

I confirmed the build version of Apache as per below:
C:\>c:\xampp\apache\bin\httpd -v
Server version: Apache/2.4.41 (Win64)
Apache Lounge VC14 Server built:   Aug 12 2019 10:48:01


Now I have downloaded and installed Apache Lounge x64  (VS16) into C:\Apache24 and attempted mod_wsgi installation with the same Python distro as above. It failed again with below error logs
 

C:\Python38>set MOD_WSGI_APACHE_ROOTDIR=C:/Apache24/bin

C:\Python38>pip install mod-wsgi
Collecting mod-wsgi
  Using cached mod_wsgi-4.7.1.tar.gz (498 kB)
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sy
s.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-edj2e8sh\\m
od-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pi
p-install-edj2e8sh\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();ex
ec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Admin\AppD
ata\Local\Temp\pip-wheel-gzo5awd3'
       cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-edj2e8sh\mod-wsgi\
  Complete output (33 lines):
  c:\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution optio
n: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\mod_wsgi
  copying src\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi
  creating build\lib.win-amd64-3.8\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win-amd64-3.8\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win-amd64-3.8\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\server
  creating build\lib.win-amd64-3.8\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\
server\management
  creating build\lib.win-amd64-3.8\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.
8\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.8\
mod_wsgi\server\management\commands
  creating build\lib.win-amd64-3.8\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\docs
  creating build\lib.win-amd64-3.8\mod_wsgi\images
  copying images\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.8\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\src
  creating build\temp.win-amd64-3.8\Release\src\server
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\1
4.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Apach
e24/bin/include -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files
(x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include"
 "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program F
iles (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\
Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows K
its\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\includ
e\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.183
62.0\cppwinrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.8\Release\src/
server\mod_wsgi.obj
  mod_wsgi.c
  C:\Users\Admin\AppData\Local\Temp\pip-install-edj2e8sh\mod-wsgi\src\server\wsg
i_apache.h(42): fatal error C1083: Cannot open include file: 'httpd.h': No such
file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildT
ools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit
status 2
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
    Running setup.py install for mod-wsgi ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-edj2e8sh\
\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\
pip-install-edj2e8sh\\mod-wsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"'
, open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();
exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\
AppData\Local\Temp\pip-record-cie2zian\install-record.txt' --single-version-exte
rnally-managed --compile --install-headers 'c:\python38\Include\mod-wsgi'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-edj2e8sh\mod-wsgi\
    Complete output (33 lines):
    c:\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution opt
ion: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\mod_wsgi
    copying src\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi
    creating build\lib.win-amd64-3.8\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win-amd64-3.8\mod_wsgi\server

    copying src\server\environ.py -> build\lib.win-amd64-3.8\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\server
    creating build\lib.win-amd64-3.8\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win-amd64-3.8\mod_wsg
i\server\management
    creating build\lib.win-amd64-3.8\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-
3.8\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.
8\mod_wsgi\server\management\commands
    creating build\lib.win-amd64-3.8\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\doc
s
    creating build\lib.win-amd64-3.8\mod_wsgi\images
    copying images\__init__.py -> build\lib.win-amd64-3.8\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.8\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\server
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC
\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/Apa
che24/bin/include -Ic:\python38\include -Ic:\python38\include "-IC:\Program File
s (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\includ
e" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program
 Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86
)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows
 Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\incl
ude\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.1
8362.0\cppwinrt" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.8\Release\sr
c/server\mod_wsgi.obj
    mod_wsgi.c
    C:\Users\Admin\AppData\Local\Temp\pip-install-edj2e8sh\mod-wsgi\src\server\w
sgi_apache.h(42): fatal error C1083: Cannot open include file: 'httpd.h': No suc
h file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Buil
dTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exi
t status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'i
mport sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\L
ocal\\Temp\\pip-install-edj2e8sh\\mod-wsgi\\setup.py'"'"'; __file__='"'"'C:\\Use
rs\\Admin\\AppData\\Local\\Temp\\pip-install-edj2e8sh\\mod-wsgi\\setup.py'"'"';f
=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r
\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-cie2zian\install-
record.txt' --single-version-externally-managed --compile --install-headers 'c:\
python38\Include\mod-wsgi' Check the logs for full command output.

C:\Python38>

**Comment by GitDidi** [comment]
Dear Sir, 

Please note that I was successful in installing mod_wsgi after downgrading Python disto to version 3.7.3 (x64)

Thanks anyway.

below are the full logs: 


C:\Python37>python -m pip --install --upgrade pip

Usage:
  C:\Python37\python.exe -m pip <command> [options]

no such option: --install

C:\Python37>python -m pip -install --upgrade pip

Usage:
  C:\Python37\python.exe -m pip <command> [options]

no such option: -i

C:\Python37>python -m pip --upgrade pip

Usage:
  C:\Python37\python.exe -m pip <command> [options]

no such option: --upgrade

C:\Python37>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z


C:\Python37>pip install virtualenv
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/9b/67/f28095ba538be54fc48
ec7774d5778a7246972cf8c701430ec0c96bf0860/virtualenv-20.0.20-py2.py3-none-any.wh
l
Collecting distlib<1,>=0.3.0 (from virtualenv)
  Using cached https://files.pythonhosted.org/packages/7d/29/694a3a4d7c0e1aef760
92e9167fbe372e0f7da055f5dcf4e1313ec21d96a/distlib-0.3.0.zip
Collecting six<2,>=1.9.0 (from virtualenv)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276
969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting filelock<4,>=3.0.0 (from virtualenv)
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90
c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting appdirs<2,>=1.4.3 (from virtualenv)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4c
bdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting importlib-metadata<2,>=0.12; python_version < "3.8" (from virtualenv)

  Using cached https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619
942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-
any.whl
Collecting zipp>=0.5 (from importlib-metadata<2,>=0.12; python_version < "3.8"->
virtualenv)
  Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc
4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Installing collected packages: distlib, six, filelock, appdirs, zipp, importlib-
metadata, virtualenv
  Running setup.py install for distlib ... done
Successfully installed appdirs-1.4.3 distlib-0.3.0 filelock-3.0.12 importlib-met
adata-1.6.0 six-1.14.0 virtualenv-20.0.20 zipp-3.1.0
You are using pip version 19.0.3, however version 20.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\Python37>python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/2e/df11ea7e23e7e761d48
4ed3740285a34e38548cf2bad2bed3dd5768ec8b9/pip-20.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-20.1

C:\Python37>pip install wheel
Collecting wheel
  Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
Successfully installed wheel-0.34.2

C:\Python37>pip install --upgrade setuptools
Collecting setuptools
  Using cached setuptools-46.1.3-py3-none-any.whl (582 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
Successfully installed setuptools-46.1.3

C:\Python37>set set MOD_WSGI_APACHE_ROOTDIR=C:/xampp/apache/bin

C:\Python37>pip install mod-wsgi
Collecting mod-wsgi
  Using cached mod_wsgi-4.7.1.tar.gz (498 kB)
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... done
  Created wheel for mod-wsgi: filename=mod_wsgi-4.7.1-cp37-cp37m-win_amd64.whl s
ize=371811 sha256=f177c2f25117a17b761185353674eb821caeba797aa793744fc29b316ef426
a0
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\c3\b2\93\f1
73e3207d97ada7d56f5516cf1cdff34b38111e41d4a0bad0
Successfully built mod-wsgi
Installing collected packages: mod-wsgi
Successfully installed mod-wsgi-4.7.1

C:\Python37>
