### ISSUE TITLE
Is there a mod_wsgi for Apache 2.4 on Windows with Python 3.8 and VS16?

### ISSUE THREAD

**Issue by jfha73** [GrahamDumpleton/mod_wsgi#571]
Hello,

I cannot find this anywhere, so I tried to compile it myself and even though `python setup.py install` and `python setup.py build` show as completed, I cannot find the mod_wsgi.so anywhere, any idea what can I do to be able to have my Apache run Python files?

Thanks.

**Comment by GrahamDumpleton** [comment]
Run:

```
mod_wsgi-express module-config
```

and it will tell you the lines to add to the Apache configuration file.

For more details see:

* https://pypi.org/project/mod-wsgi/

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.

**Comment by arreumb** [comment]
Simply impossible to understand how to install mod_wsgi on apache on windows from the documentation at https://pypi.org/project/mod-wsgi/.  A "What to do in windows" paragraph is strongly needed.
