### ISSUE TITLE
getting internal server error 500 on root domain

### ISSUE THREAD

**Issue by dev-codflaw** [GrahamDumpleton/mod_wsgi#574]
Hi

I'm getting 500 Internal server error on the root domain, even I access the domain/admin part.

**in /var/log/apache/error.log**

 I got this error 

[Thu May 21 16:17:44.258381 2020] **[wsgi:error] [pid 17700] [remote 157.37.166.244:47564] mod_wsgi (pid=17700): Exception occurred processing WSGI script '/home/ubuntu/ITB_Project/app/config/wsgi.py'.**
[Thu May 21 16:17:44.258930 2020] [wsgi:error] [pid 17700] [remote 157.37.166.244:47564] Traceback (most recent call last):
[Thu May 21 16:17:44.258975 2020] [wsgi:error] [pid 17700] [remote 157.37.166.244:47564]   File "/home/ubuntu/ITB_Project/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Thu May 21 16:17:44.258981 2020] [wsgi:error] [pid 17700] [remote 157.37.166.244:47564]     response = get_response(request)
[Thu May 21 16:17:44.258988 2020] [wsgi:error] [pid 17700] [remote 157.37.166.244:47564]   File "/home/ubuntu/ITB_Project/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
[Thu May 21 16:17:44.258992 2020] [wsgi:error] [pid 17700] [remote 157.37.166.244:47564]     response = self.process_exception_by_middleware(e, request)

Please give some guidance

Thanks!

**Comment by GrahamDumpleton** [comment]
The traceback isn't complete. Can you provide the remainder of it, right down to the except type and description.

Also read:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html

for common problems one can have such as permissions issues, or issues with working directory.

**Comment by dev-codflaw** [comment]
Thanks, @GrahamDumpleton for the reply, I fix the error.
