### ISSUE TITLE
connection error when importing pytorch/fastai

### ISSUE THREAD

**Issue by awmar1** [GrahamDumpleton/mod_wsgi#576]
I have a Django app running locally when I tried deploying it doesn't work on apache unless I comment the import of the library ptporch/fastai in my views.
the app works locally on the same environment I use for the mod_wsgi.
i'm using 
```
django 2.1.7
python 3.6
mod_wsgi  4.7
windows server 2016
```
I have set the `WSGIApplicationGroup` to `%{GLOBAL}` already ( for other libraries like NumPy ).
this how my vhosts looks like :
```
<VirtualHost *:80>
    ServerName localhost
    WSGIPassAuthorization On
    WSGIApplicationGroup %{GLOBAL}
    ErrorLog "logs/Eyelizer.error.log"
    CustomLog "logs/Eyelizer.access.log" combined
    WSGIScriptAlias /  "C:\Users\administrator\Eyelizer\Eyelizer\wsgi_windows.py"
    <Directory "C:\Users\administrator\Eyelizer\Eyelizer">
        <Files wsgi_windows.py>
            Require all granted
        </Files>
    </Directory>
</VirtualHost>
```
the apache service is running but when I try to access any page it just gives connection error and the import line is just `from fastai.vision import *`

**Comment by GrahamDumpleton** [comment]
Can you better explain what you mean by "it doesn't work"?

What error messages are in the Apache error log?

Ensure you are using at least ``info`` level for Apache ``LogLevel``, not ``err`` or ``warn``.

**Comment by awmar1** [comment]
there's no error or any indicator that is anything wrong in any of the logs ( error and access logs for both apache and the app ) 
what I mean by it doesn't work that accessing the app through the domain/IP address or the localhost from the server has the same result connection error, the page couldn't be reached, The connection was reset while the apache service is running

**Comment by GrahamDumpleton** [comment]
I still want to be able to see the logs from the time when the request was made as there is other information in there about what Apache and mod_wsgi was doing when the request was received. This time ensure that ``LogLevel`` is set to ``debug``. If there is nothing logged, then it would be doubtful whether the request was even being received by Apache, as there should be something logged.

**Comment by awmar1** [comment]
hello I just wanted to say thanks for your time when I changed the `LogLevel` I got `exited with status 3221225477` and used [this ](https://stackoverflow.com/questions/1138269/apache-error-notice-parent-child-process-exited-with-status-3221225477-res) to solve the issue 
thanks again for your help
