### ISSUE TITLE
How are 'X-Frame-Options' headers specified when serving static files on port 80

### ISSUE THREAD

**Issue by crowdawg** [GrahamDumpleton/mod_wsgi#577]
Hello,
I am attempting to run a Django app on a local domain and I am coming across an issue relating to 'X-Frame-Options' when trying to run the app on a dedicated Linux box using port 80.

Details are:
```
uname -a
Linux app 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

python --version
Python 3.7.7

pip show django
Name: Django
Version: 3.0.6

pip show mod_wsgi
Name: mod-wsgi
Version: 4.7.1

apt info apache2
Package: apache2
Version: 2.4.41-4ubuntu3
Priority: optional
Section: web
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Apache Maintainers <debian-apache@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 541 kB
Provides: httpd, httpd-cgi
Pre-Depends: dpkg (>= 1.17.14)
Depends: apache2-bin (= 2.4.41-4ubuntu3), apache2-data (= 2.4.41-4ubuntu3), apache2-utils (= 2.4.41-4ubuntu3), lsb-base, mime-support, perl:any, procps
Recommends: ssl-cert
Suggests: apache2-doc, apache2-suexec-pristine | apache2-suexec-custom, www-browser, ufw
Conflicts: apache2.2-bin, apache2.2-common
Breaks: libapache2-mod-proxy-uwsgi (<< 2.4.33)
Replaces: apache2.2-bin, apache2.2-common, libapache2-mod-proxy-uwsgi (<< 2.4.33)
Homepage: https://httpd.apache.org/
Task: lamp-server
Download-Size: 95.5 kB
APT-Manual-Installed: yes
APT-Sources: http://au.archive.ubuntu.com/ubuntu focal/main amd64 Packages
Description: Apache HTTP Server
```

I am using the `python manage.py runmodwsgi `command to setup an Apache (mod_wsgi) server and serve my app.

For the most part whether I am running on port 80 or 8000 everything runs fine, but there is an issue on one particular page which has an <object> frame that has a static pdf file url as the data attribute...

```
<div class="embed-responsive embed-responsive-1by1">
    {% load static %}
    <object class="embed-responsive-item" type="application/pdf" data="{% static 'labels/labels.pdf' %}"></object>
</div>
```
This PDF will show correctly in the PDF frame when running on port 8000 using runmodwsgi or in the local dev server (runserver), BUT when running on port 80 it gets blocked!!

I have also set the `X_FRAME_OPTIONS = 'SAMEORIGIN'` in my settings.py module as I read that it is set to DENY by default now in Django v3.

When I look at the response headers for the pdf request in the console of my browser I notice that the `X-Frame-Options` is set to SAMEORIGIN when running on port 8000 but set to DENY on port 80

My research lead me to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options so I even made an extra include file just setting `Header always set X-Frame-Options "SAMEORIGIN"` and added the `--include-file' in the runmodwsgi command.

Also when running on port 80 I used the `--setup-only` option to setup into a specific `--server-root` folder so I use `sudo ..../apachectl start` etc to run the server 

What am I missing here? Why is Apache setting the header differently on the privileged port?
I am pretty sure its something to do with the static files config please help!

**Comment by GrahamDumpleton** [comment]
As far as I know it would be Django which is setting the header. Apache wouldn't be doing it, nor should it modify anything set by the Django application. So you are perhaps better off asking on StackOverflow or a Django forum as Apache and mod_wsgi shouldn't have anything to do with it.

**Comment by crowdawg** [comment]
Thanks for the quick reply, but after banging my head against a wall for a couple for days over this I seem to have fixed it, and those files are getting the correct headers now.

I do have one more question though, when running the runmodwsgi command to do a setup on port 80 is important that this be done while as root?

Because the difference this time is that that I did a `sudo su` then made sure my venv was activated and I was in the correct folder when running `python manage.py runmodwsgi ...` command

whereas before I doing the setup while as my admin (non-root) account

**Comment by GrahamDumpleton** [comment]
If the user supplied via ``--user`` option is the same as the user which was used to generate the files it should be okay. Depending on your user ``umask``, you could have issues if the user given to ``--user`` didn't have access to files which were generated using ``--setup-only``. I can't see how though it would change something like these headers. It more likely just wouldn't start up at all.

**Comment by crowdawg** [comment]
Ok hmm well for interests sake this is the command that worked (I have dotted out specific path roots):

```
python manage.py runmodwsgi --setup-only --host 0.0.0.0 --port 80 \
  --application-type module --entry-point prodb.wsgi \
  --locale C.UTF-8 --include-file /.../server-root/xframe.conf \
  --document-root /.../static \
  --user administrator --group administrator \
  --log-directory /.../logs \
  --server-root /.../server-root
```

this was while in `sudo su` mode

But it seems like a pesky permissions thing as you said.

Great tool btw especially for Apache newbs like me

**Comment by GrahamDumpleton** [comment]
Was using the ``--locale`` option necessary to get it going?

It does various checks to try and work out a suitable default locale.

But then you may have wanted to override what it calculated, which is also fine.

**Comment by crowdawg** [comment]
Yes it was throwing an error with the locale so I overrided it, intending on going back and fixing it later (the system locale that is). I happen to be in Aus myself but the system was at C.UTF-8 default.

**Comment by GrahamDumpleton** [comment]
What does:

```
import locale
print(locale.getdefaultlocale())
```

generate from Python?

**Comment by crowdawg** [comment]
well thats interesting!
```
In [1]: import locale

In [2]: locale.getdefaultlocale()
Out[2]: ('en_US', 'UTF-8')
```

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
