### ISSUE TITLE
Can we run both Python 3.5 and Python 3.7 apps on Apache in the same server?

### ISSUE THREAD

**Issue by narasimhatejav** [GrahamDumpleton/mod_wsgi#578]
Hello,

In my server there are already apps which are running on Python 3.5 and i deployed them successfully, Now there are new application which is only compatible with Python  3.7 not with other applications.So when i deployed it initially by creating a new virtual environment with py37. It is giving module not found error. Then after going through Github and stackoverflow . I found out the solution is 

[mod_wsgi](https://pypi.org/project/mod-wsgi/)

Uninstalled system mod_wsgi and added this to apach2.conf 

```
LoadModule wsgi_module "/var/www/FlaskApp/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
WSGIPythonHome /var/www/FlaskApp/
```

When i did only Py3.7 application is running, rest other py3.5 are not working.

Then i enabled system mod_wsgi, instead of  adding it to apache2.conf i added LoadModue to 000-default.conf as 

```
LoadModule wsgi_module "/var/www/FlaskApp/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
        WSGIDaemonProcess abc user=www-data group=www-data threads=5  python-home=/var/www/FlaskApp/
        WSGIScriptAlias /abc /var/www/FlaskApp/appReOba.wsgi process-group=abc application-group=%{GLOBAL}
```

But still, it is giving the same error, unable to load wsgi file. By both the ways i can only run either py3.5 or py3.7 not both

Is there anyway to run both versions on same server or not possible. If it is possible am I missing anything.

Thanks

**Comment by GrahamDumpleton** [comment]
It is not possible to run multiple versions of Python with same mod_wsgi module at the same time as it is compiled using C APIs against a specific Python version.

Use ``mod_wsgi-express`` instead and set the front end Apache up to proxy through to the separate ``mod_wsgi-express``instance.

Some information about proxying in:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

**Comment by narasimhatejav** [comment]
Thank you very much for your quick reply @GrahamDumpleton . Let me go through these docs.
