### ISSUE TITLE
Unable to connect to apache2 server with my mod_wsgi installed through pip install

### ISSUE THREAD

**Issue by Funkydog** [GrahamDumpleton/mod_wsgi#580]
Dears,
I'm unable to connect to apache server with the new configuration of my **mod_wsgi** installed with pip through a virtualenv (python3.7).

I have run the following commands:
`$ sudo apt-get remove libapache2-mod-wsgi-py3`
`(Venv) $ pip install mod_wsgi`

Then extracted the **output** from:
`$ mod_wsgi-express module-config`
pasted in my **wsgi.load** file:
```
LoadModule wsgi_module "/home/pi/test/XXX/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-arm-linux-gnueabihf.so"
WSGIPythonHome "/home/pi/test/XXX/venv"
```

**Activating** the wsgi with:
`sudo a2enmod wsgi`

**Restarting** the apache server:
`sudo systemctl restart apache2`

Then I get a message error in `systemctl status apache2.service`:

> /etc/apache2/mods-enabled/wsgi.load: Cannot load /home/pi/test/XXX/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-arm-linux-gnueabihf.so

The reason I'm changing my mod_wsgi installation, is to work on a specific Python version on my Raspberry pi (> 3.7) in a Virtualenv. It's the first time I setup this, so any advices would be very helpful. 
Thanks so much.

**Comment by GrahamDumpleton** [comment]
Run:

```
ldd /home/pi/test/XXX/venv/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-arm-linux-gnueabihf.so
```

What do you get?

**Comment by Funkydog** [comment]
Hi Graham, thanks for a very prompt answer. 
I get the following message:

> linux-vdso.so.1 (0x7ed04000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76c62000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76c23000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76ae4000)
	/lib/ld-linux-armhf.so.3 (0x76f82000)

**Comment by GrahamDumpleton** [comment]
You should see a Python shared library dependency. That you don't usually means Python was not installed with a shared library, and thus linking was against a static library, which usually isn't going to work. Usually it actually fails at build time.

Did you install Python from source code yourself?

For how to install Python from source code such that it has a shared library see:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Ignore that it talks about docker. All the issues are the same.

If there is a Python shared library, then for some reason it isn't getting linked against the module when built.

In that case you can possibly fudge it by adding before the ``LoadModule`` line, a ``LoadFile`` directive, where the argument is the full path to the Python shared library object file.

**Comment by Funkydog** [comment]
Indeed I installed Python from source code without shared library. So I decided to finally reinstall Python 3.7.2 using `./configure --enable-shared`

Then liking to my Python path with `sudo ldconfig /usr/local/lib` 
I now obtain the following from the previous ldd command:

> 	linux-vdso.so.1 (0x7ec85000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f51000)
	libpython3.7m.so.1.0 => /usr/local/lib/libpython3.7m.so.1.0 (0x76c93000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76c54000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76b15000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76b02000)
	libutil.so.1 => /lib/arm-linux-gnueabihf/libutil.so.1 (0x76aef000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76a70000)
	/lib/ld-linux-armhf.so.3 (0x76fad000)

I've gone a step further, my server is now up and running! Thanks so much! 
But some other issues are remaining... I get an error from my deamon process:
> Unable to connect to WSGI daemon process 'MyProject' on '/etc/apache2/logs/wsgi.30769.0.1.sock' as user with uid=33.

I then added a socket-user in my `DaemonProcess` as following:
```
WSGIDaemonProcess MyProject python-path=/home/pi/MySite python-home=/home/pi/test/XXX/venv socket-user=#33
WSGIProcessGroup MyProject
WSGIScriptAlias / /home/pi/MySite/XXX/wsgi.py
```
But it doesn't work so far. Do you have any ideas?
Thanks a lot

**Comment by GrahamDumpleton** [comment]
That is a really strange location for Apache logs.

What do you get when run:

```
ls -las /etc/apache2/logs
```

The logs directory permissions may not allow access.

Try adding:

```
WSGISocketPrefix /tmp/wsgi
```

See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/configuration-issues.html#location-of-unix-sockets

**Comment by Funkydog** [comment]
I have manually changed the logs in my `000-default.conf` to:
```
ErrorLog /home/pi/MySite/site/logs/error.log
CustomLog /home/pi/MySite/site/access.log combined
```
But I have no results from `ls -las /etc/apache2/logs`

I then added the `WSGISocketPrefix ` outside my `<VirtualHost>` in `000-default.conf`:

```
        <Directory /home/pi/MySite/XXX/XXX/>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>
        WSGIDaemonProcess MyProject python-path=/home/pi/MySite/XXX python-home=/home/pi/test/XXX/venv socket-user=#33
        WSGIProcessGroup MyProject
        WSGIScriptAlias / /home/pi/MySite/XXX/XXX/wsgi.py
</VirtualHost>

        WSGISocketPrefix /tmp/wsgi
```

Then I get this error:
> django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.

If you think this is the wrong way to proceed, please let me know, I've followed some tutorials but not sure this is the correct procedure for apache server. Thanks again.

**Comment by GrahamDumpleton** [comment]
Where you put the log files wasn't the issue. It was because permissions on the logs directory didn't allow access to non root user. The ``WSGISocketPrefix`` directive therefore fixed your issue for now, although it is not desirable to leave that is using ``/tmp``. You likely can drop the ``socket-user`` option as it isn't doing anything.

You are now onto getting the Django application working. The error suggests that the MySQLdb module isn't installed in the Python virtual environment.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
