### ISSUE TITLE
WSGIPythonHome causes apache Incorrect Function error

### ISSUE THREAD

**Issue by TotallyNotChase** [GrahamDumpleton/mod_wsgi#581]
I'm on an AWS EC2 instance running windows (64 bit) and using the following-
* python 3.8.3 64 bit
* Apache 64 bit (from apache lounge)
* mod_wsgi
* django

I pasted these 2 lines, generated from `mod_wsgi-express module-config` in my apache `httpd.conf`-

> LoadModule wsgi_module "c:/proj/djangoproj/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd"
> WSGIPythonHome "c:/proj/djangoproj/venv"

But upon starting the Apache service, I get the following error-

> The Apache HTTP Server service terminated with the following service-specific error: 
Incorrect function.

I tried removing the `WSGIPythonHome` line and it started up just fine but I don't think my django project will work correctly without it?

**Comment by TotallyNotChase** [comment]
I should also mention - this **only** happens when using a virtual environment

**Comment by GrahamDumpleton** [comment]
Am aware of the issue and it is discussed in numerous other issues. Have been trying to solve it for a while, but the Python C API is broken for Windows when using new style Python virtual environments. Issue was first report against CPython probably 5 years ago.

First up, can you try with:

```
pip install -U --no-cache-dir https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

There is an attempt at a workaround in that, but the one person who has tried it can't seem to get it working and don't understand why. Logging doesn't even show the code being triggered.

When you use that version, ensure you use:

```
LogLevel info
```

and not a log level of ``err`` or ``warn``.

Then grab the Apache startup logs for me, specifically looking for log messages which would be generated by:

```
                    ap_log_error(APLOG_MARK, APLOG_INFO, 0, wsgi_server,
                                 "mod_wsgi (pid=%d): Adding '%s' to "
                                 "path.", getpid(), value);

                        ap_log_error(APLOG_MARK, APLOG_ERR, 0, wsgi_server,
                                     "mod_wsgi (pid=%d): Call to "
                                     "'site.addsitedir()' failed for '%s', "
                                     "stopping.", getpid(), value);
```

If that doesn't help, change your configuration to:

```
LoadModule wsgi_module "c:/proj/djangoproj/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd"
WSGIPythonPath "c:/proj/djangoproj/venv/Lib/site-packages"
```

**Comment by TotallyNotChase** [comment]
I can't quite get the log anymore due to my setup changing drastically as I gave up on `venv`. But I can confirm that everytime this exception happened it was due to `ModuleNotFoundError`.

> Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

I've a feeling it's because the `venv` is not being activated correctly. I noticed people suggested activating it through the `wsgi.py` by doing `exec('activate_this.py')`, But the `activate_this.py` is not generated by `venv` so I couldn't try this whole thing with an actually activated venv.

For future reference, all of this seems to work without the venv, which makes me think it *is* the `venv` not being activated and hence the modules are not being found. If using a `venv` is a necessity, you'll have to activate it somehow.

**Comment by GrahamDumpleton** [comment]
As I said, use instead:

```
LoadModule wsgi_module "c:/proj/djangoproj/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd"
WSGIPythonPath "c:/proj/djangoproj/venv/Lib/site-packages"
```

That is, instead of setting ``WSGIPythonHome``, add the ``site-packages`` directory of the virtual environment to ``WSGIPythonPath``.

That should work if the version from GitHub doesn't work for you.
