### ISSUE TITLE
Cannot connect pyodbc in apache 2.4 

### ISSUE THREAD

**Issue by eleswarapu** [GrahamDumpleton/mod_wsgi#582]
Hi, 

I have configured all the modules and it's working fine for the test run "Hello World.". But when I tried to connect to ODBC using the following connection string, it throws me an error. 
connection = pyodbc.connect("DSN=XXX;ARServer=XXX;""UID=XXX;PWD=XXX;SERVER=XXX")
error: Data source name not found and no default driver specified (0) (SQLDriverConnect)')

Do I need to configure the DBD module in httpd.cnf file? 

Thanks in Advance.

**Comment by GrahamDumpleton** [comment]
Are you setting environment variables in your user account in order for it to work with your test program on the command line? Those environment variables will not be set when code runs under Apache unless you explicitly set them in the WSGI script file before importing any Python modules that may need them.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
