### ISSUE TITLE
mod_wsgi-express not found after pip installation

### ISSUE THREAD

**Issue by iecdohanich** [GrahamDumpleton/mod_wsgi#586]
Running on Windows10 with python 2.7.18
after a successful 
>py pip install mod_wsgi

running
>py mod_wsgi-express module-config

results in
>C:\Python27\python.exe: can't open file 'mod_wsgi-express': [Errno 2] No such file or directory

running 
>mod_wsgi-express module-config

results in
>'mod_wsgi-express' is not recognised as an internal or external command

I had followed these same steps previously with python3 without issue. 

Thanks for your help.

**Comment by GrahamDumpleton** [comment]
Suggest you ask on StackOverflow. I am not a Windows user and this just seems to be a problem with your Windows/Python setup, not a mod_wsgi specific issue.

BTW, I do not recommend using Python 2.7 on Windows. Usually it is not even possible to get mod_wsgi to build and install for Python 2.7 on Windows as it isn't possible to obtain Apache for the correct compiler version.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
