### ISSUE TITLE
 [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] ImportError: No module named 'django'

### ISSUE THREAD

**Issue by nishant007-tech** [GrahamDumpleton/mod_wsgi#587]
sudo tail /var/log/apache2/error.log
[Mon Jun 29 06:14:08.188280 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260] Traceback (most recent call last):
[Mon Jun 29 06:14:08.188316 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260]   File "/home/django/django_video/main/main/wsgi.py", line 12, in <module>
[Mon Jun 29 06:14:08.188323 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260]     from django.core.wsgi import get_wsgi_application
[Mon Jun 29 06:14:08.188352 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260] ImportError: No module named 'django'
[Mon Jun 29 06:14:08.722843 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] mod_wsgi (pid=14883): Target WSGI script '/home/django/django_video/main/main/wsgi.py' cannot be loaded as Python module.
[Mon Jun 29 06:14:08.722904 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] mod_wsgi (pid=14883): Exception occurred processing WSGI script '/home/django/django_video/main/main/wsgi.py'.
[Mon Jun 29 06:14:08.723002 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] Traceback (most recent call last):
[Mon Jun 29 06:14:08.723026 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636]   File "/home/django/django_video/main/main/wsgi.py", line 12, in <module>
[Mon Jun 29 06:14:08.723032 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636]     from django.core.wsgi import get_wsgi_application
[Mon Jun 29 06:14:08.723053 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] ImportError: No module named 'django'
sudo tail /var/log/apache2/error.log
[Mon Jun 29 06:14:08.188280 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260] Traceback (most recent call last):
[Mon Jun 29 06:14:08.188316 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260]   File "/home/django/django_video/main/main/wsgi.py", line 12, in <module>
[Mon Jun 29 06:14:08.188323 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260]     from django.core.wsgi import get_wsgi_application
[Mon Jun 29 06:14:08.188352 2020] [wsgi:error] [pid 14883:tid 140524683720448] [remote 169.149.227.131:17260] ImportError: No module named 'django'
[Mon Jun 29 06:14:08.722843 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] mod_wsgi (pid=14883): Target WSGI script '/home/django/django_video/main/main/wsgi.py' cannot be loaded as Python module.
[Mon Jun 29 06:14:08.722904 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] mod_wsgi (pid=14883): Exception occurred processing WSGI script '/home/django/django_video/main/main/wsgi.py'.
[Mon Jun 29 06:14:08.723002 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] Traceback (most recent call last):
[Mon Jun 29 06:14:08.723026 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636]   File "/home/django/django_video/main/main/wsgi.py", line 12, in <module>
[Mon Jun 29 06:14:08.723032 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636]     from django.core.wsgi import get_wsgi_application
[Mon Jun 29 06:14:08.723053 2020] [wsgi:error] [pid 14883:tid 140524566124288] [remote 169.149.227.131:22636] ImportError: No module named 'django'

`<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port $
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) th$
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn
        `ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
       Alias /static /home/django/django_video/main/assets
        <Directory /home/django/django_video/main/assets>
                Require all granted
        </Directory>

        Alias /media /home/django/django_video/main/media
        <Directory /home/django/django_video/main/media>
                Require all granted
        </Directory>
        <Directory /home/django/django_video/main/main>
            <Files wsgi.py>
                Require all granted
            </Files>
        </Directory>

        WSGIDaemonProcess django_video python-path=/home/django/django_video/m$

        WSGIProcessGroup django_video
        WSGIScriptAlias / /home/django/django_video/main/main/wsgi.py

**Comment by GrahamDumpleton** [comment]
Where and how did you install Django? Are you using a Python virtual environment? Or did you install using ``pip install --user``?

From the command line Python, what do you get for:

```
import django
print(django.__file__)
```

**Comment by esilva-dt** [comment]
Good evening.

I'm having this issue too. I'm using AWS' elastic beanstalk, Django was installed in a virtual environment (/opt/python/run/venv/) during deployment as it was part of the requirements.txt file. I tried running the command stated above and I got this:

     /opt/python/run/venv/local/lib/python3.6/site-packages/django/__init__.py

I got two conf files in which mod_wsgi is invoked.

**A: ssl.conf**
LoadModule wsgi_module modules/mod_wsgi.so
WSGIPythonHome /opt/python/run/baselinenv
WSGISocketPrefix run/wsgi
WSGIRestrictEmbedded On
Listen 443
<VirtualHost *:443>
  SSLEngine on
  SSLCertificateFile "/etc/pki/tls/certs/server.crt"
  SSLCertificateKeyFile "/etc/pki/tls/certs/server.key"
  
  Alias /static/ /opt/python/current/app/static/
  <Directory /opt/python/current/app/static>
  Order allow,deny
  Allow from all
  </Directory>
  
  WSGIScriptAlias / /opt/python/current/app/miclave/wsgi.py
  
  <Directory /opt/python/current/app>
  Require all granted
  </Directory>
  
  WSGIDaemonProcess wsgi-ssl processes=1 threads=15 display-name=%{GROUP} \
    python-path=/opt/python/current/app:/opt/python/run/venv/lib64/python3.6/site-packages:/opt/python/run/venv/lib/python3.6/site-packages \
    home=/opt/python/current/app \
    user=wsgi \
    group=wsgi
  WSGIProcessGroup wsgi-ssl
  
</VirtualHost>

**B: wsgi.conf**
LoadModule wsgi_module modules/mod_wsgi.so
WSGIPythonHome /opt/python/run/baselinenv
WSGISocketPrefix run/wsgi
WSGIRestrictEmbedded On

<VirtualHost *:80>

Alias /static/ /opt/python/current/app/static/
<Directory /opt/python/current/app/static/>
Order allow,deny
Allow from all
</Directory>


WSGIScriptAlias / /opt/python/current/app/miclave/wsgi.py


<Directory /opt/python/current/app/>
  Require all granted
</Directory>

WSGIDaemonProcess wsgi processes=1 threads=15 display-name=%{GROUP} \
  python-home=/opt/python/run/venv/ \
  python-path=/opt/python/current/app user=wsgi group=wsgi \
  home=/opt/python/current/app
WSGIProcessGroup wsgi
</VirtualHost>

LogFormat "%h (%{X-Forwarded-For}i) %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

I tried adding the python-home option in the WSGIDaemonProcess in **ssl.conf** but I got another error.

I'm at a loss here, I would appreciate any recommendation. Thaks beforehand.

**Comment by GrahamDumpleton** [comment]
@esilva-dt Please create a new issue for your problem, don't use an existing issue.

**Comment by StefanB123** [comment]
@nishant007-tech be sure that mod_wsgi is installed with the same python version as your library where django is imported

**Comment by nishant007-tech** [comment]
> Where and how did you install Django? Are you using a Python virtual environment? Or did you install using `pip install --user`?
> 
> From the command line Python, what do you get for:
> 
> ```
> import django
> print(django.__file__)
> ```

Solved !! Problem is with mod_wsgi installation . Then i install it using pip then everything is working fine!

**Comment by nishant007-tech** [comment]
> @nishant007-tech be sure that mod_wsgi is installed with the same python version as your library where django is imported

Solved Bro!! Yeah problem is with mod_wsgi version then i installed it with pip.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
