### ISSUE TITLE
ModuleNotFoundError: No module named 'keystone'

### ISSUE THREAD

**Issue by menkeyi** [GrahamDumpleton/mod_wsgi#595]
```
[root@controller mod_wsgi-4.7.1]# curl -I http://controller:5000
HTTP/1.1 500 Internal Server Error
Date: Wed, 29 Jul 2020 06:26:00 GMT
Server: Apache/2.4.34 (Unix) mod_wsgi/4.7.1 Python/3.7
Connection: close
Content-Type: text/html; charset=iso-8859-1

error_log:

2020-07-29 14:25:03.333457 mod_wsgi (pid=87148): Failed to exec Python script file '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 14:25:03.333520 mod_wsgi (pid=87148): Exception occurred processing WSGI script '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 14:25:03.333697 Traceback (most recent call last):
2020-07-29 14:25:03.333719   File "/usr/local/bin/keystone-wsgi-public", line 6, in <module>
2020-07-29 14:25:03.333723     from keystone.server.wsgi import initialize_public_application
2020-07-29 14:25:03.333737 ModuleNotFoundError: No module named 'keystone'
2020-07-29 14:26:00.876803 mod_wsgi (pid=87697): Failed to exec Python script file '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 14:26:00.876873 mod_wsgi (pid=87697): Exception occurred processing WSGI script '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 14:26:00.877055 Traceback (most recent call last):
2020-07-29 14:26:00.877078   File "/usr/local/bin/keystone-wsgi-public", line 6, in <module>
2020-07-29 14:26:00.877083     from keystone.server.wsgi import initialize_public_application
2020-07-29 14:26:00.877098 ModuleNotFoundError: No module named 'keystone'
```

There is no error in the python 3 test. What is the reason?

```
[root@controller mod_wsgi-4.7.1]# python3
Python 3.7.4 (default, Mar 24 2020, 19:20:18)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keystone.server.wsgi import initialize_public_application
```

```
compile：
./configure --with-python=python3
make&&make install 
chmod 755 /usr/lib64/httpd/modules/mod_wsgi.so
```

**Comment by GrahamDumpleton** [comment]
What does your mod_wsgi configuration look like? Are you using daemon mode? How what Python virtual environment location set? Were additional Python paths declared?

What do you get for:

```
import keystone
print(keystone.__file__)

import sys
print(sys.prefix)
```

Have you confirmed exactly what version of Python is mod_wsgi actually compiled for. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-installation-in-use

for how to work it out.

**Comment by menkeyi** [comment]
[root@controller ~]# python3
Python 3.7.4 (default, Mar 24 2020, 19:20:18)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keystone
>>> print(keystone.__file__)
/usr/local/lib/python3.7/site-packages/keystone/__init__.py
>>> import sys
>>> print(sys.prefix)
/usr
>>>



Here, an exception is thrown intentionally, and python 3.7 is called ,Python3.7 and python2 exist on the machine



2020-07-29 14:53:38.137049 mod_wsgi (pid=92924): Failed to exec Python script file '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 14:53:38.137121 mod_wsgi (pid=92924): Exception occurred processing WSGI script '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 14:53:38.137305 Traceback (most recent call last):
2020-07-29 14:53:38.137329   File "/usr/local/bin/keystone-wsgi-public", line 5, in <module>
2020-07-29 14:53:38.137334     raise Exception(os.__file__)
2020-07-29 14:53:38.137348 Exception: /usr/lib64/python3.7/os.py




#!/usr/bin/python3
#PBR Generated from 'wsgi_scripts'

import threading, os
from keystone.server.wsgi import initialize_public_application

if __name__ == "__main__":
    import argparse
    import socket
    import sys
    import wsgiref.simple_server as wss

    parser = argparse.ArgumentParser(
        description=initialize_public_application.__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        usage='%(prog)s [-h] [--port PORT] [--host IP] -- [passed options]')
    parser.add_argument('--port', '-p', type=int, default=8000,
                        help='TCP port to listen on')
    parser.add_argument('--host', '-b', default='',
                        help='IP to bind the server to')
    parser.add_argument('args',
                        nargs=argparse.REMAINDER,
                        metavar='-- [passed options]',
                        help="'--' is the separator of the arguments used "
                        "to start the WSGI server and the arguments passed "
                        "to the WSGI application.")
    args = parser.parse_args()
    if args.args:
        if args.args[0] == '--':
            args.args.pop(0)
        else:
            parser.error("unrecognized arguments: %s" % ' '.join(args.args))
    sys.argv[1:] = args.args
    server = wss.make_server(args.host, args.port, initialize_public_application())

    print("*" * 80)
    print("STARTING test server keystone.server.wsgi.initialize_public_application")
    url = "http://%s:%d/" % (server.server_name, server.server_port)
    print("Available at %s" % url)
    print("DANGER! For testing only, do not use in production")
    print("*" * 80)
    sys.stdout.flush()

    server.serve_forever()
else:
    application = None
    app_lock = threading.Lock()

    with app_lock:
        if application is None:
            application = initialize_public_application()

**Comment by GrahamDumpleton** [comment]
You didn't provide the output from check I asked for in:

* https://modwsgi.readthedocs.io/en/develop/user-guides/checking-your-installation.html#python-installation-in-use

When you do that, also include in the test WSGI script a line to print out ``sys.path``.

Are these files what is supplied by the Keystone folks, as there is various things in there which aren't really correct, although they would specifically cause this issue.

One reason for the failure may be an overly aggressive SELinux policy which isn't allow Apache to read the Python ``site-packages`` directory.

**Comment by menkeyi** [comment]
sys.path::
['/usr/lib64/python37.zip', '/usr/lib64/python3.7', '/usr/lib64/python3.7/lib-dynload', '/usr/lib64/python3.7/site-packages', '/usr/lib/python3.7/site-packages']


2020-07-29 15:15:53.640848 mod_wsgi (pid=92924): Failed to exec Python script file '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 15:15:53.640916 mod_wsgi (pid=92924): Exception occurred processing WSGI script '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 15:15:53.641144 Traceback (most recent call last):
2020-07-29 15:15:53.641172   File "/usr/local/bin/keystone-wsgi-public", line 6, in <module>
2020-07-29 15:15:53.641177     raise Exception(sys.path)
2020-07-29 15:15:53.641193 Exception: ['/usr/lib64/python37.zip', '/usr/lib64/python3.7', '/usr/lib64/python3.7/lib-dynload', '/usr/lib64/python3.7/site-packages', '/usr/lib/python3.7/site-packages']


I can't open your website for the time being：
https://modwsgi.readthedocs.io/zh-CN/develop/user-guides/checking-your-installation.html#python-installation-in-use


Here I create a soft link，Or the mistake before the report：
ln -s /usr/local/lib/python3.7/site-packages/keystone     /usr/lib64/python3.7/

**Comment by GrahamDumpleton** [comment]
Do you have a second Python 3.7 installation as ``/usr/local/bin/python3``?

If not, that ``/usr/local/lib/python3.7/site-packages`` doesn't appear in ``sys.path`` may be because SELinux is blocking access to that directory to Apache, thus it never gets added to ``sys.path`` as Python may only add it if can read it.

Instead of the symlink, try adding to the ``WSGIDaemonProcess`` directive the option:

```
python-path=/usr/local/lib/python3.7/site-packages
```

If that doesn't work, then SELinux possibly blocking it.

If does work, then it means you may have two separate Python installations, or RH system Python is screwed up, or doesn't work for embedded systems possibly, by adding ``/usr/local/lib/python3.7/site-packages`` to ``sys.path``.

**Comment by GrahamDumpleton** [comment]
People are telling me that Red Hat 8.3 only has Python 3.6 supported as OS Python.

Where has that Python 3.7 installed under ``/usr`` come from? Did you install it to that location yourself from source code.

**Comment by menkeyi** [comment]
The system comes with python3, which should be a？
[root@controller ~]# whereis python3
python3: /usr/bin/python3 /usr/bin/python3.7 /usr/bin/python3.7m /usr/bin/python3.7-config /usr/bin/python3.7m-aarch64-config /usr/bin/python3.7m-config /usr/lib/python3.7 /usr/lib64/python3.7 /usr/local/lib/python3.7 /usr/include/python3.7m

SELinux is Disable
[root@controller ~]# getenforce
Disabled

Add / usr / local / lib / python3.7/site packages to complete
[root@controller ~]# tail -f /var/log/httpd/keystone.log
2020-07-29 15:42:50.736615 mod_wsgi (pid=109033): Exception occurred processing WSGI script '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 15:42:50.736796 Traceback (most recent call last):
2020-07-29 15:42:50.736820   File "/usr/local/bin/keystone-wsgi-public", line 6, in <module>
2020-07-29 15:42:50.736824     raise Exception(sys.path)
2020-07-29 15:42:50.736839 Exception: ['/usr/local/lib/python3.7/site-packages', '/usr/lib64/python37.zip', '/usr/lib64/python3.7', '/usr/lib64/python3.7/lib-dynload', '/usr/lib64/python3.7/site-packages', '/usr/lib/python3.7/site-packages']




An error has occurred, I can't think of where it is:
2020-07-29 15:37:06.460210 mod_wsgi (pid=106717): Exception occurred processing WSGI script '/usr/local/bin/keystone-wsgi-public'.
2020-07-29 15:37:06.460407 Traceback (most recent call last):
2020-07-29 15:37:06.460429   File "/usr/local/bin/keystone-wsgi-public", line 7, in <module>
2020-07-29 15:37:06.460439     from keystone.server.wsgi import initialize_public_application
2020-07-29 15:37:06.460454 ModuleNotFoundError: No module named 'keystone'

**Comment by GrahamDumpleton** [comment]
People involved with Red Hat are telling me there is no python3.7 package for RH 8.3. Only python2.7, python3.6 and python3.8. If you have Python 3.7 installed under /usr, it came from somewhere else. Installing a non OS Python under /usr is usually a bad idea.

Anyway, what do you get when you run:

```
ls -las /usr/local/lib/python3.7/site-packages
```

The permissions on the directories could be wrong. For example, if keystone was installed by root with umask of something like 0700 instead of 0775. The user that Apache runs as will not be able to read the directories/files.

**Comment by menkeyi** [comment]
This is a variant of Linux version, which is based on centos8. The system comes with python3 and does not change the path.

Previously found that the permission problem has been fixed to 755 directory permissions  
chmod 755 -R /usr/local/lib/python3.7/site-packages/keystone
[root@controller ~]# ls -ld /usr/local/lib/python3.7/site-packages/keystone
drwxr-xr-x 27 root root 4096 Jul 27 10:05 /usr/local/lib/python3.7/site-packages/keystone



[root@controller ~]# ls -las /usr/local/lib/python3.7/site-packages
total 564
12 drwx------ 203 root root  8192 Jul 27 14:38 .
 0 drwx------   3 root root    27 Jul 27 10:03 ..
 0 drwx------  11 root root   232 Jul 27 10:05 alembic
 0 drwx------   2 root root   181 Jul 27 10:05 alembic-1.4.2-py3.7.egg-info
 0 drwx------   3 root root   323 Jul 27 10:05 amqp
 0 drwx------   2 root root   102 Jul 27 10:05 amqp-2.6.0.dist-info
 0 drwx------   5 root root   265 Jul 27 10:03 aniso8601
 0 drwx------   2 root root   102 Jul 27 10:03 aniso8601-8.0.0.dist-info
 0 drwx------   2 root root   106 Jul 27 10:10 appdirs-1.4.4.dist-info
28 -rw-------   1 root root 24720 Jul 27 10:10 appdirs.py
 0 drwx------   2 root root   131 Jul 27 10:05 argparse-1.4.0.dist-info
88 -rw-------   1 root root 89214 Jul 27 10:04 argparse.py
 4 drwx------   3 root root  4096 Jul 27 10:05 attr
 0 drwx------   2 root root   102 Jul 27 10:05 attrs-19.3.0.dist-info
 0 drwx------   6 root root   304 Jul 27 10:03 babel
 0 drwx------   2 root root   126 Jul 27 10:03 Babel-2.8.0.dist-info
 0 drwx------   3 root root   180 Jul 27 10:05 cachetools
 0 drwx------   2 root root   102 Jul 27 10:05 cachetools-4.1.1.dist-info
 0 drwx------   8 root root   293 Jul 27 10:10 cinderclient
 4 drwx------   3 root root  4096 Jul 27 10:03 click
 0 drwx------   2 root root   106 Jul 27 10:03 click-7.1.2.dist-info
 0 drwx------   5 root root   328 Jul 27 10:10 cliff
 0 drwx------   2 root root   157 Jul 27 10:10 cliff-3.3.0.dist-info
 4 drwx------   3 root root  4096 Jul 27 10:10 cmd2
 0 drwx------   2 root root   102 Jul 27 10:10 cmd2-1.2.1.dist-info
 0 drwx------   3 root root   136 Jul 27 10:10 colorama
 0 drwx------   2 root root   106 Jul 27 10:10 colorama-0.4.3.dist-info
 0 drwx------   5 root root   162 Jul 27 10:04 debtcollector
 0 drwx------   2 root root   133 Jul 27 10:04 debtcollector-2.1.0.dist-info
 0 drwx------   2 root root   122 Jul 27 10:10 decorator-4.4.2.dist-info
20 -rw-------   1 root root 17222 Jul 27 10:10 decorator.py
 0 drwx------   3 root root   233 Jul 27 10:05 defusedxml
 0 drwx------   2 root root    87 Jul 27 10:05 defusedxml-0.6.0.dist-info
 0 drwx------   4 root root   335 Jul 27 10:16 distlib
 0 drwx------   2 root root    66 Jul 27 10:16 distlib-0.3.1.dist-info
 4 drwx------   4 root root  4096 Jul 27 10:05 dns
 0 drwx------   2 root root   102 Jul 27 10:05 dnspython-2.0.0.dist-info
 0 drwx------   5 root root    99 Jul 27 10:04 dogpile
 0 drwx------   2 root root   181 Jul 27 10:04 dogpile.cache-1.0.1-py3.7.egg-info
 4 -rwx--x--x   1 root root  2988 Jul 27 10:04 editor.py
 4 drwx------   8 root root  4096 Jul 27 10:05 eventlet
 0 drwx------   2 root root   117 Jul 27 10:05 eventlet-0.25.2.dist-info
 0 drwx------   4 root root    57 Jul 27 10:05 extras
 0 drwx------   2 root root   147 Jul 27 10:05 extras-1.0.0.dist-info
 0 drwx------   4 root root   145 Jul 27 10:05 fasteners
 0 drwx------   2 root root   102 Jul 27 10:05 fasteners-0.15.dist-info
 0 drwx------   2 root root   102 Jul 27 10:16 filelock-3.0.12.dist-info
16 -rw-------   1 root root 13229 Jul 27 10:15 filelock.py
 0 drwx------   5 root root   130 Jul 27 10:05 fixtures
 0 drwx------   2 root root   147 Jul 27 10:05 fixtures-3.0.0.dist-info
 4 drwx------   4 root root  4096 Jul 27 10:03 flask
 0 drwx------   2 root root   130 Jul 27 10:03 Flask-1.1.2.dist-info
 0 drwx------   5 root root   155 Jul 27 10:03 flask_restful
 0 drwx------   2 root root   120 Jul 27 10:03 Flask_RESTful-0.3.8.dist-info
 0 drwx------   4 root root   186 Jul 27 10:05 futurist
 0 drwx------   2 root root   133 Jul 27 10:05 futurist-2.2.0.dist-info
 0 drwx------   5 root root    87 Jul 27 10:04 importlib_metadata
 0 drwx------   2 root root   102 Jul 27 10:04 importlib_metadata-1.7.0.dist-info
 0 drwx------   3 root root    85 Jul 27 10:04 iso8601
 0 drwx------   2 root root   131 Jul 27 10:04 iso8601-0.1.12.dist-info
 0 drwx------   3 root root   198 Jul 27 10:03 itsdangerous
 0 drwx------   2 root root   106 Jul 27 10:03 itsdangerous-1.1.0.dist-info
 4 drwx------   3 root root  4096 Jul 27 10:03 jinja2
 0 drwx------   2 root root   130 Jul 27 10:03 Jinja2-2.11.2.dist-info
 0 drwx------   3 root root   167 Jul 27 10:10 jmespath
 0 drwx------   2 root root   150 Jul 27 10:10 jmespath-0.10.0.dist-info
 0 drwx------   2 root root   117 Jul 27 10:10 jsonpatch-1.26.dist-info
28 -rw-------   1 root root 26030 Jul 27 10:10 jsonpatch.py
 0 drwx------   2 root root   131 Jul 27 10:10 jsonpointer-2.0.dist-info
12 -rw-------   1 root root  9796 Jul 27 10:10 jsonpointer.py
 0 drwx------   6 root root   304 Jul 27 10:05 jsonschema
 0 drwx------   2 root root   126 Jul 27 10:05 jsonschema-3.2.0.dist-info
 0 drwx------   4 root root   204 Jul 27 10:05 jwt
 4 drwxr-xr-x  27 root root  4096 Jul 27 10:05 keystone
 0 drwx------   2 root root   170 Jul 27 10:05 keystone-16.0.2.dev6-py3.7.egg-info
 4 drwx------  11 root root  4096 Jul 27 10:04 keystoneauth1
 0 drwx------   2 root root   171 Jul 27 10:04 keystoneauth1-4.2.0.dist-info
 4 drwx------  11 root root  4096 Jul 27 10:04 keystoneclient
 0 drwx------   9 root root   237 Jul 27 10:04 keystonemiddleware
 0 drwx------   2 root root   157 Jul 27 10:04 keystonemiddleware-9.0.0.dist-info
 4 drwx------   6 root root  4096 Jul 27 10:05 kombu
 0 drwx------   2 root root   102 Jul 27 10:05 kombu-4.6.11.dist-info
 0 drwx------   4 root root    57 Jul 27 10:05 linecache2
 0 drwx------   2 root root   147 Jul 27 10:05 linecache2-1.0.0.dist-info
 0 drwx------   4 root root   333 Jul 27 10:05 mako
 0 drwx------   2 root root   141 Jul 27 10:05 Mako-1.1.3.dist-info
52 -rw-------   1 root root 51714 May 12  2013 memcache.py
 0 drwx------   6 root root   113 Jul 27 10:04 migrate
 8 -rw-------   1 root root  6246 Jul 27 10:04 mimeparse.py
 0 drwx------   2 root root   131 Jul 27 10:05 monotonic-1.5.dist-info
 8 -rw-------   1 root root  7117 Jul 27 10:04 monotonic.py
 0 drwx------   3 root root    69 Jul 27 10:10 munch
 0 drwx------   2 root root   137 Jul 27 10:10 munch-2.5.0.dist-info
 0 drwx------   7 root root   161 Jul 27 10:04 netaddr
 0 drwx------   2 root root   141 Jul 27 10:04 netaddr-0.8.0.dist-info
 0 drwx------   5 root root   227 Jul 27 10:10 novaclient
 0 drwx------   6 root root   144 Jul 27 10:05 oauthlib
 0 drwx------   2 root root   102 Jul 27 10:05 oauthlib-3.1.0.dist-info
 0 drwx------   3 root root   156 Jul 27 10:05 OpenSSL
 4 drwx------  25 root root  4096 Jul 27 10:10 openstack
 0 drwx------  13 root root   214 Jul 27 10:10 openstackclient
 0 drwx------   2 root root   171 Jul 27 10:10 openstacksdk-0.48.0.dist-info
 0 drwx------   8 root root   216 Jul 27 10:10 osc_lib
 0 drwx------   2 root root   133 Jul 27 10:10 osc_lib-2.2.0.dist-info
 0 drwx------   6 root root   215 Jul 27 10:04 oslo_cache
 0 drwx------   2 root root   171 Jul 27 10:04 oslo.cache-2.5.0.dist-info
 0 drwx------   6 root root   215 Jul 27 10:05 oslo_concurrency
 0 drwx------   2 root root   171 Jul 27 10:05 oslo.concurrency-4.2.0.dist-info
 0 drwx------   5 root root   281 Jul 27 10:04 oslo_config
 0 drwx------   2 root root   171 Jul 27 10:04 oslo.config-8.3.0.dist-info
 0 drwx------   4 root root   111 Jul 27 10:04 oslo_context
 0 drwx------   2 root root   133 Jul 27 10:04 oslo.context-3.1.0.dist-info
 0 drwx------   6 root root   197 Jul 27 10:05 oslo_db
 0 drwx------   2 root root   171 Jul 27 10:05 oslo.db-8.3.0.dist-info
 0 drwx------   5 root root   236 Jul 27 10:04 oslo_i18n
 0 drwx------   2 root root   133 Jul 27 10:04 oslo.i18n-5.0.0.dist-info
 0 drwx------   7 root root   286 Jul 27 10:04 oslo_log
 0 drwx------   2 root root   171 Jul 27 10:04 oslo.log-4.3.0.dist-info
 0 drwx------   8 root root   302 Jul 27 10:05 oslo_messaging
 0 drwx------   2 root root   171 Jul 27 10:05 oslo.messaging-12.2.2.dist-info
 0 drwx------   6 root root   333 Jul 27 10:05 oslo_middleware
 0 drwx------   2 root root   157 Jul 27 10:05 oslo.middleware-4.1.0.dist-info
 0 drwx------   5 root root   318 Jul 27 10:05 oslo_policy
 0 drwx------   2 root root   171 Jul 27 10:05 oslo.policy-3.3.1.dist-info
 0 drwx------   5 root root   135 Jul 27 10:04 oslo_serialization
 0 drwx------   2 root root   133 Jul 27 10:04 oslo.serialization-4.0.0.dist-info
 0 drwx------   5 root root   308 Jul 27 10:05 oslo_service
 0 drwx------   2 root root   171 Jul 27 10:05 oslo.service-2.3.2.dist-info
 0 drwx------   4 root root    96 Jul 27 10:05 oslo_upgradecheck
 0 drwx------   2 root root   133 Jul 27 10:05 oslo.upgradecheck-1.1.0.dist-info
 4 drwx------   5 root root  4096 Jul 27 10:04 oslo_utils
 0 drwx------   2 root root   147 Jul 27 10:04 oslo.utils-4.3.0.dist-info
 0 drwx------   7 root root   239 Jul 27 10:05 osprofiler
 0 drwx------   2 root root   171 Jul 27 10:05 osprofiler-3.3.0.dist-info
 0 drwx------   5 root root   107 Jul 27 10:04 os_service_types
 0 drwx------   2 root root   133 Jul 27 10:04 os_service_types-1.7.0.dist-info
 0 drwx------   3 root root   249 Jul 27 10:04 packaging
 0 drwx------   2 root root   143 Jul 27 10:04 packaging-20.4.dist-info
 0 drwx------   9 root root   297 Jul 27 10:04 passlib
 0 drwx------   2 root root   118 Jul 27 10:04 passlib-1.7.2.dist-info
 4 drwx------  10 root root  4096 Jul 27 10:05 paste
 0 drwx------   2 root root   141 Jul 27 10:05 Paste-3.4.3.dist-info
 4 -rw-------   1 root root   534 Jul 27 10:04 Paste-3.4.3-py3.7-nspkg.pth
 0 drwx------   2 root root   141 Jul 27 10:05 PasteDeploy-2.1.0.dist-info
 4 -rw-------   1 root root   534 Jul 27 10:04 PasteDeploy-2.1.0-py3.7-nspkg.pth
 0 drwx------   6 root root   308 Jul 27 10:03 pbr
 0 drwx------   2 root root   141 Jul 27 10:03 pbr-5.4.5.dist-info
 0 drwx------   3 root root   134 Jul 27 10:16 pluggy
 0 drwx------   2 root root   102 Jul 27 10:16 pluggy-0.13.1.dist-info
 0 drwx------   2 root root   117 Jul 27 10:05 prettytable-0.7.2-py3.7.egg-info
56 -rw-------   1 root root 54204 Apr  7  2013 prettytable.py
 4 drwx------   9 root root  4096 Jul 27 10:16 py
 0 drwx------   2 root root   102 Jul 27 10:16 py-1.9.0.dist-info
 4 drwx------   2 root root  4096 Jul 27 14:38 __pycache__
 4 drwx------   5 root root  4096 Jul 27 10:04 pycadf
 0 drwx------   2 root root   147 Jul 27 10:04 pycadf-3.1.0.dist-info
 0 drwx------   4 root root   271 Jul 27 10:03 pycparser
 0 drwx------   2 root root   102 Jul 27 10:03 pycparser-2.20.dist-info
 0 drwx------   2 root root   117 Jul 27 10:04 pyinotify-0.9.6-py3.7.egg-info
88 -rw-------   1 root root 89010 Jun  4  2015 pyinotify.py
 0 drwx------   2 root root   141 Jul 27 10:05 PyJWT-1.7.1.dist-info
 0 drwx------   2 root root   102 Jul 27 10:05 pyOpenSSL-19.1.0.dist-info
 0 drwx------   3 root root    63 Jul 27 10:10 pyperclip
 0 drwx------   2 root root   117 Jul 27 10:10 pyperclip-1.8.0-py3.7.egg-info
 0 drwx------   2 root root   102 Jul 27 10:05 pysaml2-6.1.0.dist-info
 0 drwx------   2 root root   117 Jul 27 14:38 python3_memcached-1.51-py3.7.egg-info
 0 drwx------   2 root root   171 Jul 27 10:10 python_cinderclient-7.1.0.dist-info
 0 drwx------   2 root root   131 Jul 27 10:05 python_editor-1.0.4.dist-info
 0 drwx------   2 root root   171 Jul 27 10:04 python_keystoneclient-4.1.0.dist-info
 0 drwx------   2 root root   131 Jul 27 10:05 python_mimeparse-1.6.0.dist-info
 0 drwx------   2 root root   171 Jul 27 10:10 python_novaclient-17.2.0.dist-info
 0 drwx------   2 root root   171 Jul 27 10:10 python_openstackclient-5.3.1.dist-info
 0 drwx------   3 root root    17 Jul 27 10:05 repoze
 0 drwx------   2 root root   185 Jul 27 10:05 repoze.lru-0.7.dist-info
 4 -rw-------   1 root root   539 Jul 27 10:04 repoze.lru-0.7-py3.6-nspkg.pth
 0 drwx------   3 root root    44 Jul 27 10:10 requestsexceptions
 0 drwx------   2 root root   147 Jul 27 10:10 requestsexceptions-1.4.0.dist-info
 0 drwx------   3 root root   261 Jul 27 10:04 rfc3986
 0 drwx------   2 root root   121 Jul 27 10:04 rfc3986-1.4.0.dist-info
 0 drwx------   3 root root   128 Jul 27 10:05 routes
 0 drwx------   2 root root   131 Jul 27 10:05 Routes-2.4.1.dist-info
 4 drwx------  17 root root  4096 Jul 27 10:05 saml2
 0 drwx------   2 root root   102 Jul 27 10:16 six-1.15.0.dist-info
36 -rw-------   1 root root 34159 Jul 27 10:15 six.py
 0 drwx------   2 root root   157 Jul 27 10:04 sqlalchemy_migrate-0.13.0.dist-info
 0 drwx------   5 root root   246 Jul 27 10:04 sqlparse
 0 drwx------   2 root root   126 Jul 27 10:04 sqlparse-0.3.1.dist-info
 0 drwx------   5 root root    90 Jul 27 10:05 statsd
 0 drwx------   2 root root    87 Jul 27 10:05 statsd-3.3.0.dist-info
 0 drwx------   6 root root   250 Jul 27 10:04 stevedore
 0 drwx------   2 root root   171 Jul 27 10:04 stevedore-3.2.0.dist-info
 0 drwx------   3 root root    99 Jul 27 10:04 tempita
 0 drwx------   2 root root   133 Jul 27 10:04 Tempita-0.5.2-py3.7.egg-info
 0 drwx------   4 root root    57 Jul 27 10:05 testresources
 0 drwx------   2 root root   147 Jul 27 10:05 testresources-2.0.1.dist-info
 0 drwx------   5 root root   158 Jul 27 10:04 tests
 0 drwx------   4 root root    96 Jul 27 10:05 testscenarios
 0 drwx------   2 root root   147 Jul 27 10:05 testscenarios-0.5.0.dist-info
 4 drwx------   7 root root  4096 Jul 27 10:05 testtools
 0 drwx------   2 root root   133 Jul 27 10:05 testtools-2.4.0.dist-info
 0 drwx------   3 root root   128 Jul 27 10:16 toml
 0 drwx------   2 root root   150 Jul 27 10:16 toml-0.10.1.dist-info
 4 drwx------  10 root root  4096 Jul 27 10:16 tox
 0 drwx------   2 root root   126 Jul 27 10:16 tox-3.18.0.dist-info
 0 drwx------   4 root root    57 Jul 27 10:05 traceback2
 0 drwx------   2 root root   147 Jul 27 10:05 traceback2-1.4.0.dist-info
 0 drwx------   4 root root   249 Jul 27 10:05 unittest2
 0 drwx------   2 root root   155 Jul 27 10:05 unittest2-1.1.0.dist-info
 0 drwx------   4 root root   175 Jul 27 10:05 vine
 0 drwx------   2 root root   102 Jul 27 10:05 vine-1.3.0.dist-info
 0 drwx------  11 root root   227 Jul 27 10:16 virtualenv
 0 drwx------   2 root root   142 Jul 27 10:16 virtualenv-20.0.28.dist-info
 0 drwx------   4 root root   164 Jul 27 10:10 wcwidth
 0 drwx------   2 root root   118 Jul 27 10:10 wcwidth-0.2.5.dist-info
 4 drwx------   3 root root  4096 Jul 27 10:03 webob
 0 drwx------   2 root root   122 Jul 27 10:03 WebOb-1.8.6.dist-info
 4 drwx------   6 root root  4096 Jul 27 10:03 werkzeug
 0 drwx------   2 root root   106 Jul 27 10:03 Werkzeug-1.0.1.dist-info
 0 drwx------   2 root root   102 Jul 27 10:04 zipp-3.1.0.dist-info
 8 -rw-------   1 root root  7121 Jul 27 10:04 zipp.py

**Comment by GrahamDumpleton** [comment]
Apache user will not be able to read any of the those Python package directories with permissions of `drwx------`. It can't even read the `site-packages` directory itself as is, so changing just `keystone` permissions will not help. So that would be the problem. They shouldn't have those permissions. Using `chmod -R 755` isn't a good solution either since it is adding execute bits to files which shouldn't have them.

**Comment by menkeyi** [comment]
Thank you very much for helping me analyze the problem. This problem is indeed a permission problem. I have solved Chmod 755 - R / usr / local / lib64 / python3.7/
