### ISSUE TITLE
Centos 7, Python 3.8 , Apache 2.4.3 WSGI 4.6.5 Django isn't loading.

### ISSUE THREAD

**Issue by DarrellJonsson** [GrahamDumpleton/mod_wsgi#596]
Centos 7.7 Python 3.8 , Apache 2.4.3 WSGI 4.6.5 Django isn't loading.

Inside the virtual env the program runs and can be directed to a port for testing.
Within the Centos/Apache/WSGI/Python stack though it will not load once included in the httpd.conf file. 

ldd and the error_log tells us         
libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f811e2b3000)

Questions
* If the native mod_wsgi is compiled for 2.7 is it possible to run our app
in a virtual environment?

* Our IP provider is reluctant to do any changes that will crash their cpanel,
and will not let us recompile mod_wsgi is copying mod_wsgi from Fedora or a later version of Centos a possible solution for this?

Please advise

**Comment by GrahamDumpleton** [comment]
Can you even replace what ``mod_wsgi.so`` is used by Apache if using restricted cpanel setup?

If you can, and there is a compiler on the host to allow you to compile Python package with C extensions, you may be able to use ``pip install mod_wsgi`` to build mod_wsgi without their help. This will only work though if they provide the Apache 'dev' package to allow you to build extra Apache modules.

See:

* https://pypi.org/project/mod-wsgi/

for some details of using ``pip install mod_wsgi`` and then integrating it into an existing Apache install.

**Comment by DarrellJonsson** [comment]
We have contacted the provider of our managed VPS TMD tech support to see if they will compile or allow us to compile mod_wsgi for Python 3.  With EOL of Python 2 being this April I'd be surprised if they can't or won't.

**Comment by GrahamDumpleton** [comment]
If they will not let you touch the mod_wsgi used by their Apache install, if you can run a separate long running service, you can run ``mod_wsgi-express``, which will run its own separate Apache instance, and proxy it behind their Apache instance.

**Comment by DarrellJonsson** [comment]
We are happy to report, after sending TMD the links you recommended., 
they escalated the issue and mod_wsgi for Python 3 was compiled for
the Centos by their staff.  Thanks again for your help.
