### ISSUE TITLE
Kerberos configuration with mod_wsgi-express

### ISSUE THREAD

**Issue by parth-thakkar** [GrahamDumpleton/mod_wsgi#600]
Hi ,

I am following the way "Installation into Python" , using mod_wsgi-express to start the Apache server.
As 
`mod_wsgi-express start-server path/to/wsgi.py --host 0.0.0.0 --port 8080 --python-path path/to/my/Django/project/module`
and it runs fine, but how can I configure Kerberos using mod_wsgi-express ?

**Comment by GrahamDumpleton** [comment]
Do you know how to do it with Apache? Is the Apache installation you are using have the required Kerberos modules installed already?

If you have the required configuration and can show me so can confirm what you are using and what it requires, then I can explain.

**Comment by parth-thakkar** [comment]
Hi Graham,

Yes I have done it for Apache (installed as RHEL package), and that is working. The configuration I have kept in <myproject>.conf file under /opt/rh/httpd/root/etc/httpd/conf.d dir. The complete configuration looks like below,


```
<VirtualHost *:81>

<Location />
AuthName "Kerberos Login"
AuthType Kerberos
KrbMethodNegotiate on
KrbMethodK5Passwd on
KrbAuthoritative on
KrbAuthRealms <My REALM>
KrbVerifyKDC on
KrbServiceName Any
Krb5Keytab /path/to/keytab
KrbSaveCredentials off
Require valid-user
</Location>

Alias /static /opt/rh/rh-python36/root/opt/djangoproject/components/static
<Directory /opt/rh/rh-python36/root/opt/djangoproject/components/static>
Require all granted
</Directory>


<Directory /opt/rh/rh-python36/root/opt/djangoproject/mra_ui>
<Files test-wsgi.py>
Require all granted
</Files>
</Directory>

WSGIDaemonProcess djangoproject python-home=/opt/rh/rh-python36/root/opt/djangoproject/testenv python-path=/opt/rh/rh-python36/root/opt/djangoproject

WSGIScriptAlias / /opt/rh/rh-python36/root/opt/djangoproject/mra_ui/wsgi.py
WSGIProcessGroup djangoproject


</VirtualHost>

```

Here i have configured the Location tab . 

thanks 
With best regards
Parth

**Comment by GrahamDumpleton** [comment]
For ``mod_wsgi-express`` try creating a file called ``kerberos.conf`` which contains:

```
<Location />
AuthName "Kerberos Login"
AuthType Kerberos
KrbMethodNegotiate on
KrbMethodK5Passwd on
KrbAuthoritative on
KrbAuthRealms <My REALM>
KrbVerifyKDC on
KrbServiceName Any
Krb5Keytab /path/to/keytab
KrbSaveCredentials off
Require valid-user
</Location>
```

and then use:

```
mod_wsgi-express start-server --include-file kerberos.conf      ---yourotheroptions---
```

If that doesn't work we will see if have to use something other than ``Location`` around it.

**Comment by parth-thakkar** [comment]
Seems it progrssed, but with new error,

AH00526: Syntax error on line 5 of kerberos.conf:
Invalid command 'KrbMethodNegotiate', perhaps misspelled or defined by a module not included in the server configuration

Looks like apache is complaining the kerberos module is not included ! but there is 

```
(base) myserver:httpd$ cat conf/httpd.conf | grep conf.modules.d
Include conf.modules.d/*.conf

```

```
(base) myserver:httpd$ cat conf.modules.d/10-auth_kerb.conf
LoadModule auth_kerb_module modules/mod_auth_kerb.so
```

so, the apache kerberos SO module should have been loaded in the config, but it is still not recognised.

**Comment by GrahamDumpleton** [comment]
Yeah, forgot one important thing.

At the start of ``kerberos.conf``, before ``Location``, add:

```
<IfModule ! auth_kerb_module >
LoadModule auth_kerb_module '${MOD_WSGI_MODULES_DIRECTORY}/mod_auth_kerb.so'
</IfModule>
```

In other words, have to load the module yourself.

**Comment by GrahamDumpleton** [comment]
Just to clarify, ``mod_wsgi-express`` doesn't use any of your system Apache configuration files. It uses a completely separate generated configuration. That ``--include-file`` option is allowing you to add extra stuff of your own to that generated config, to allow you to do customisations like this for things that ``mod_wsgi-express`` itself doesn't do.

**Comment by parth-thakkar** [comment]
Super, 
Kerberos is is loaded as SO module now, but strangely I am getting below error,

`[Mon Aug 10 15:14:31.995381 2020] [wsgi:error] [pid 27544:tid 139851047114944] django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
`

does it have anything to do with --include-file settings, i hope not. 

Also, I was reading your blog and you have suggested to use `"python manage.py runmodwsgi"` instead of `mod_wsgi-express start-server` . 

Any preference over one of them ?

many Thanks

**Comment by GrahamDumpleton** [comment]
How does ``SECRET_KEY`` get set? Are you expecting it to be set via environment variable, in the ``settings.py`` file or in some other way?

**Comment by parth-thakkar** [comment]
Hi Graham,

probably there was some issue of code deployment, now all is well. I am finally running the below combination
redhat apache + pip installed mod_wsgi + anaconda3.7 + redhat apache kerberos SO module + Oracle DB .

your hints were super helpful.
thanks.

**Comment by GrahamDumpleton** [comment]
That sounds like a scary combination. :-)

**Comment by GrahamDumpleton** [comment]
Whoops, forgot to answer the question. The benefit of using ``runmodwsgi`` is that is sorts out static file hosting for you from the Django settings module. Otherwise is basically the same.
