### ISSUE TITLE
unable to get working mod_wsgi on wondows

### ISSUE THREAD

**Issue by AlLeo50** [GrahamDumpleton/mod_wsgi#606]
On win7-64, after installing Microsoft Visual C++ 2015-2019 Redistributable (both x86 and x64) - 14.27.29016, I correctly installed and verified python38 on C:\Python38, Apache24 on C:\Apache24, made pip-install mod_wsgi.
As confirm, I repeated the command and had as return: Requirement already satisfied: mod_wsgi in c:\python38\lib\site-packages (4.7.1). 
I then copied the module link into httpd.conf as 
LoadModule wsgi_module "c:/python38/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd".
 Then I did httpd -t -D DUMP MODULES, and verified that wsgi_module (shared) was loaded.
I then tried mod_wsgi-express start-server --help
and had back:
Usage: mod_wsgi-express command [params]

Commands:
    module-config
    module-location

mod_wsgi-express: error: Invalid command was specified.
That makes me think there's something that doesn't work correctly.
I also made other settings, but to cut short, despite all my efforts, if I try to reach a "localhost/hello.py" I have Mozilla listing its contents instead of saying "Hello World".
Can you please address me  to a detailed installation and use of this module as a bridge between Apache 24 and Python 38, so that I can use Python instead of PHP to generate pages and interface with mySQL?
Kind regards

**Comment by GrahamDumpleton** [comment]
The ``start-server`` option to ``mod_wsgi-express`` is not available on Windows. You need to manually configure the Apache yourself. See about the ``module-config`` option in:

* https://pypi.org/project/mod-wsgi/

For more general information about configuring Apache for mod_wsgi see:

* https://modwsgi.readthedocs.io/en/develop/

**Comment by AlLeo50** [comment]
Thank you a lot for your quick and plain reply.

Kind regards.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
