### ISSUE TITLE
Cannot load mod_wsgi.cp38-win_amd64.pyd

### ISSUE THREAD

**Issue by tksundar** [GrahamDumpleton/mod_wsgi#607]
I installed mod_wsgi today and could generate the configs correctly. I have python 3.8. it initially complained about VS c++ . I installed the latest and could install the module. Then I generated the configs and copied the output to httpd.conf as shown below
LoadModule wsgi_module "/users/tksra/pycharmprojects/mysite/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd"
WSGIPythonHome "/users/tksra/pycharmprojects/mysite/venv"
The paths are good and the .pyd file exists. But apache still gives this error
The Apache service named reported the following error:

httpd.exe: Syntax error on line 188 of C:/apache/Apache24/conf/httpd.conf: Cannot load c:/users/tksra/pycharmprojects/mysite/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd into server: The specified module could not be found.
I am running 64 bit windows and python and VC++

I had a doubt that mod_wsgi.cp38-win_amd64.pyd has 2 '.' in the file name and so it is taking the part after the first . as extension. I editited this to _ . Still no luck

My system is -:
Windows 10 professional
Apache 2.4.46
Microsoft Visual C++ 2019
Python 3.8

What could be the issue?

**Comment by GrahamDumpleton** [comment]
Would the service user that Apache runs as have the required permissions to access files in your home directory. That would be the usual cause of this.

**Comment by tksundar** [comment]
I recreated mod_wsgi outside user home(now with python 3.7.7).  Just to let you know, the command generates only 2 lines, instead of three. See below
-----------------------------------------------------------
(venv) C:\dev\ffl>mod_wsgi-express module-config
LoadModule wsgi_module "c:/dev/ffl/venv/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "c:/dev/ffl/venv"
-----------------------------------------------------------
The problem persists. Permissions on the file look alright. When I ran reimage it showed some problems with the apache installation. However, if I run httpd directly(not creating a service and starting it), it fails again , but this time with a system problem(Exception code: 0xc0000409). In any case , if i remove the LoadModule line from httpd.conf, everything works(I get the 'It Works!" page). So not sure if spending $30 to fix the issues will actually solve the problem

I hope it will be more straight forward on a Linux VM. I you have some suggestions I can try, do let me know.

**Comment by GrahamDumpleton** [comment]
It works with Windows Subsystem for Linux (WSL) fine. Recommend using that if you can. When using WSL, you can use ``mod_wsgi-express start-server`` and don't have to worry about manually configuring Apache.

You could also try:

```
pip install --no-cache https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

When using ``WSGIPythonHome`` it can ignore the virtual environment depending on how it was created. Latest develop version has a fix, but have not have people definitely confirm works so I can release it.

I don't think that change will solve the issue as you describe, but using ``--no-cache`` when install has a chance of maybe clearing out issues if for some reason you compiled against a different Apache or with wrong compiler architecture at some point. The option causes it to ignore cached build from prior install for that version.

**Comment by tksundar** [comment]
Thanks! It worked like magic. I thing I had generated the first config with a different apache(not Lounge) and that could have been the root cause. Thanks again. I am closing the issue
