### ISSUE TITLE
mod_wsgi - No Module Found Error - Unable to Call Virtual environment modules 

### ISSUE THREAD

**Issue by narasimhatejav** [GrahamDumpleton/mod_wsgi#608]
Hi,

These are the steps i have followed to deploy the application 

OS : Centos 7
Python : 3.6.8

To install Apache : `sudo yum install httpd-dlevel`

To install mod_wsgi :  `Pip install mod_wsgi`

I have copied output from `mod_wsgi-express module-config`  to `/etc/httpd/conf/httpd.conf` which is

```
LoadModule wsgi_module "/usr/local/lib64/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"
```

Then I have copied application to` /var/www/ ` folder and application folder is app:

run.wsgi : 

```
import sys

sys.path.insert(0, '/var/www/app')

from run import app as application
```

Config in httpd.conf : 

```
        WSGIDaemonProcess test user=apache group=apache threads=5 python-path=/var/www/app/venv/lib/python3.6/site-packages
        WSGIScriptAlias /test /var/www/app/run.wsgi  process-group=test application-group=%{GLOBAL}
        <Directory /var/www/app/>
                WSGIProcessGroup test
                WSGIApplicationGroup %{GLOBAL}
                WSGIScriptReloading On
                Order allow,deny
                Allow from all
        </Directory>
```

But after all this configuration when i am trying to call the api it is pointing to global python packages not in the venv packages
i have checked all the packages by activating venv environment, I am able to run the program without any error. But when i call it through apache it is giving module not found issue. But if i install any python package globally then it is not giving error to that particular python package then it is given no module found error for next python package.

I want to understand why it is unable to call virtual env packages. Do I need to modify anything in the above configurations?

**Comment by GrahamDumpleton** [comment]
For a start, you should be using:

```
        WSGIDaemonProcess test user=apache group=apache threads=5 python-home=/var/www/app/venv
        WSGIScriptAlias /test /var/www/app/run.wsgi  process-group=test application-group=%{GLOBAL}
        <Directory /var/www/app/>
                Order allow,deny
                Allow from all
        </Directory>
```

Use ``python-home`` to refer to virtual environment root. Don't use ``python-path`` to refer to ``site-packages``.

The directives inside of the ``Directory`` block weren't needed.

See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by narasimhatejav** [comment]
Yes I have removed site-packages from the python path to `python-home=/var/www/app/venv` still the issue is same. It is referring to global python packages

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
