### ISSUE TITLE
 Failed to exec Python script file 

### ISSUE THREAD

**Issue by snehanyk05** [GrahamDumpleton/mod_wsgi#611]
Hi, I'm was trying to change my django python version from 3.69 to 3.7. I uninstalled libapache2-mod-wsgi-py3 and installed mod_wsgi using pip install mod_wsgi and ran the following: mod_wsgi-express module-config. I pasted the following into mods_available into wsgi.load
`LoadModule wsgi_module "/var/www/html/print_application/python_code/work3.7/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
WSGIPythonHome "/var/www/html/print_application/python_code/work3.7"
`

My wsgi.load file looks as below:
`WSGISocketPrefix /var/run/wsgi
LoadModule wsgi_module /var/www/html/print_application/python_code/work3.7/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so
WSGIPythonHome /var/www/html/print_application/python_code/work3.7`

My sites_avaliable 000-default.conf looks as below:
`<VirtualHost *:80>
    Alias /static /var/www/html/print_application/print_project/static
    <Directory /var/www/html/print_application/print_project/static>
        Require all granted
    </Directory>

    <Directory /var/www/html/print_application/print_project/print_project>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

WSGIDaemonProcess print_project  python-path=/var/www/html/print_application/print_project python-home=/var/www/html/print_application/print_project/work3.7

WSGIProcessGroup print_project
WSGIScriptAlias / /var/www/html/print_application/print_project/print_project/wsgi.py

</VirtualHost>`

The error that i get in my apache error logs is as below:
[Tue Sep 01 08:37:26.855374 2020] [mpm_prefork:notice] [pid 101137] AH00169: caught SIGTERM, shutting down
[Tue Sep 01 08:37:26.937116 2020] [mpm_prefork:notice] [pid 101185] AH00163: Apache/2.4.29 (Ubuntu) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Tue Sep 01 08:37:26.937169 2020] [core:notice] [pid 101185] AH00094: Command line: '/usr/sbin/apache2'
[Tue Sep 01 08:37:30.889736 2020] [wsgi:error] [pid 101186] [remote 192.168.1.210:51127] mod_wsgi (pid=101186): Failed to exec Python script file '/var/www/html/print_application/print_project/print_project/wsgi.py'.
[Tue Sep 01 08:37:30.889770 2020] [wsgi:error] [pid 101186] [remote 192.168.1.210:51127] mod_wsgi (pid=101186): Exception occurred processing WSGI script '/var/www/html/print_application/print_project/print_project/wsgi.py'.
[Tue Sep 01 08:37:30.889897 2020] [wsgi:error] [pid 101186] [remote 192.168.1.210:51127] Traceback (most recent call last):
[Tue Sep 01 08:37:30.889919 2020] [wsgi:error] [pid 101186] [remote 192.168.1.210:51127]   File "/var/www/html/print_application/print_project/print_project/wsgi.py", line 21, in <module>
[Tue Sep 01 08:37:30.889924 2020] [wsgi:error] [pid 101186] [remote 192.168.1.210:51127]     from django.core.wsgi import get_wsgi_application
[Tue Sep 01 08:37:30.889937 2020] [wsgi:error] [pid 101186] [remote 192.168.1.210:51127] ModuleNotFoundError: No module named 'django'

Any help would be greatly appreciated.

**Comment by GrahamDumpleton** [comment]
When you activate the virtual environment from command line and run Python, what do you get when running the following in the interpreter?

```
import sys
print(sys.prefix)
import django
print(django.__file__)
```

If the paths are all correct, my first guess would be that the virtual environment was created, and or packages installed, by root, and the root user had a restrictive umask such that permissions on things installed are not accessible to other users, such as the Apache user.

What do you get for:

```
ls -las /var/www/html/print_application/print_project/work3.7/lib/python3.7/site-packages
```

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.

**Comment by NawThae** [comment]
python and django are not in the same location. How can I fix that ? Thank you in advance.

**Comment by GrahamDumpleton** [comment]
@NawThae Your question doesn't make any sense and also doesn't necessarily seem to be related to original issue. Please create a new issue and properly explain your specific problem. What you have provided so far isn't helpful.
