### ISSUE TITLE
Error in staring Apache2, unable to load mod_wsgi

### ISSUE THREAD

**Issue by mattmorz** [GrahamDumpleton/mod_wsgi#612]
```
Starting XAMPP for Linux 7.2.33-0...
XAMPP: Starting Apache...fail.
httpd: Syntax error on line 158 of /opt/lampp/etc/httpd.conf: Cannot load /home/matt/Documents/AccreENV/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so into server: /lib/x86_64-linux-gnu/libpython3.8.so.1.0: undefined symbol: XML_SetHashSalt
XAMPP: Starting MySQL...already running.
XAMPP: Starting ProFTPD...already running.

```
I have already install python3.8-dev.

**Comment by GrahamDumpleton** [comment]
Most likely your mod_wsgi was compiled for a different Apache server installation. If this is a non standard Apache, you must point the build at the correct `apxs` for the Apache installation you want to use.

**Comment by mattmorz** [comment]
Ok, I am using the Apache2 installed using XAMPP. Can you direct me to make it work?

**Comment by GrahamDumpleton** [comment]
Find the `apxs` utility provided with that Apache distribution, and tell the build to use it. So if you are using the ``pip install`` method of building it, run something like:

```
APXS=/opt/lampp/bin/apxs
export APXS
pip install -U mod_wsgi
```

You need to set ``APXS`` environment variable to where their `apxs` script is. If they don't supply one, you are out of luck. They also need to supply header files for Apache. If they aren't, you can't build for that Apache in that case either.

**Comment by mattmorz** [comment]
Still receiving the same error. I have tried the commands. `apxs` is in `/opt/lampp/bin/` directory.

**Comment by GrahamDumpleton** [comment]
Sorry, missed an important option to the `pip` part.

```
pip install -U --no-cache-dir mod_wsgi
```

Must have `--no-cache-dir` else it will used the cached copy from prior installation.

**Comment by mattmorz** [comment]
I have uninstall `mod_wsgi` then install it again using the command. Still giving me the same error. I activate the virtual env prior to installation.

**Comment by GrahamDumpleton** [comment]
Now that sure mod_wsgi is built against correct Apache, then next issue seems to be that that Apache distribution doesn't doesn't link in XML libraries that Python executable would normally be linked against.

Run `which python`, and then on the full path it returns run `ldd`. For example:

```
ldd /usr/bin/python3
```

Show me the command and output.

**Comment by mattmorz** [comment]
```
linux-vdso.so.1 (0x00007fff15395000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fce21c6e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fce21c4b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fce21c45000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fce21c40000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fce21c24000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fce21ad5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fce2222d000)

```

**Comment by GrahamDumpleton** [comment]
What do you get when you run:

```
ldd /home/matt/Documents/AccreENV/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
```

**Comment by mattmorz** [comment]
```
matt  ~  cd Documents/
 matt  ~  Documents  source AccreENV/bin/activate
 matt  (e) AccreENV  ~  Documents  ldd /home/matt/Documents/AccreENV/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffd2cfe6000)
	libpython3.8.so.1.0 => /lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f2106033000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2106010000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2105e1e000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f2105df0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2105dd4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2105dce000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f2105dc7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2105c78000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f21065e4000)
```

**Comment by GrahamDumpleton** [comment]
And lastly:

```
ldd /lib/x86_64-linux-gnu/libpython3.8.so.1.0
```

The function ``XML_SetHashSalt`` is not used anywhere in mod_wsgi and shouldn't be a part of Python library either.

Also try running:

```
nm /home/matt/Documents/AccreENV/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so | grep XML_SetHashSalt
```

and see what you get.

**Comment by mattmorz** [comment]
```
 matt  (e) AccreENV  ~  Documents  ldd /lib/x86_64-linux-gnu/libpython3.8.so.1.0
	linux-vdso.so.1 (0x00007ffd4e8a5000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f76b943e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f76b9422000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f76b93ff000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f76b93f9000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f76b93f4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76b92a5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76b90b1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f76b99dc000)
 matt  (e) AccreENV  ~  Documents  nm /home/matt/Documents/AccreENV/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so | grep XML_SetHashSalt
 matt  (e) AccreENV  ~  Documents  0  1  

```

**Comment by GrahamDumpleton** [comment]
It looks like your Apache may provide its own expat library and is linked to it, where as Python was compiled with system expat library. The two libraries are not the same version and so when Apache drags in its version of the library, symbols are missing that Python expects.

Do you really need to use that Apache distribution as it isn't going to work? Can you use the system Apache instead?

The XAMPP Apache distributions always seem to cause problems when trying to use third party Apache modules which they don't include. So recommend avoiding XAMPP Apache distribution.

**Comment by mattmorz** [comment]
Thanks for your effort and help. I did manage to host Django Application in Windows using your `mod_wsgi` but without using `virtualenv`. I used the `.pyd` file instead of the `.so`, same using XAMPP.

**Comment by GrahamDumpleton** [comment]
On Windows you need to install the `develop` branch of mod_wsgi from GitHub. That version hopefully works with virtual environments properly. Been having difficultly getting anyone to confirm it works though so the fix it contains hasn't been released yet.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
