### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DistributionNotFound'

### ISSUE THREAD

**Issue by droy30** [GrahamDumpleton/mod_wsgi#613]
Error for mod_wsgi:
OS: RHEL 7.8
mod_wsgi is installed by: yum install mod_wsgi

**- httpd configuration:**

 WSGIDaemonProcess jiratest  user=apache group=apache threads=5
    WSGIProcessGroup jiratest
    WSGIScriptAlias /jiratest /var/www/webapps/jiratest/jiratest.wsgi
    WSGIScriptReloading On
    <Directory /var/www/webapps/jiratest>
         Require all granted
    </Directory>

**wsgi file: - /var/www/webapps/jiratest/jiratest.wsgi**

import sys

python_home='/var/www/webapps/jiratest/jiratest_venv'
activate_this = python_home + '/bin/activate_this.py'

with open(activate_this) as file_:
  exec(file_.read(), dict(__file__=activate_this))
sys.path.insert(0, '/var/www/webapps//jiratest/')

from jiratest import app as application

**flask application directory structure:-**
drwxr-xr-x. 5 root root  77 Sep  7 09:49 jiratest_venv
-rw-r--r--. 1 root root 505 Sep  7 09:53 jiratest.py
-rw-r--r--. 1 root root 298 Sep  7 09:55 jiratest.wsgi

**Error log: -**

[Mon Sep 07 11:18:28.037658 2020] [:error] [pid 19514] [remote 172.30.180.80:24] mod_wsgi (pid=19514): Exception occurred processing WSGI script '/var/www/webapps/jiratest/jiratest.wsgi'.
[Mon Sep 07 11:18:28.037670 2020] [:error] [pid 19514] [remote 172.30.180.80:24] Traceback (most recent call last):
[Mon Sep 07 11:18:28.037685 2020] [:error] [pid 19514] [remote 172.30.180.80:24]   File "/var/www/webapps/jiratest/jiratest.wsgi", line 10, in <module>
[Mon Sep 07 11:18:28.037705 2020] [:error] [pid 19514] [remote 172.30.180.80:24]     from jiratest import app as application
[Mon Sep 07 11:18:28.037710 2020] [:error] [pid 19514] [remote 172.30.180.80:24]   File "/var/www/webapps//jiratest/jiratest.py", line 2, in <module>
[Mon Sep 07 11:18:28.037719 2020] [:error] [pid 19514] [remote 172.30.180.80:24]     from jira import JIRA
[Mon Sep 07 11:18:28.037724 2020] [:error] [pid 19514] [remote 172.30.180.80:24]   File "/var/www/webapps/jiratest/jiratest_venv/lib/python3.6/site-packages/jira/__init__.py", line 6, in <module>
[Mon Sep 07 11:18:28.037733 2020] [:error] [pid 19514] [remote 172.30.180.80:24]     _v = VersionInfo('jira').semantic_version()
[Mon Sep 07 11:18:28.037738 2020] [:error] [pid 19514] [remote 172.30.180.80:24]   File "/var/www/webapps/jiratest/jiratest_venv/lib/python3.6/site-packages/pbr/version.py", line 462, in semantic_version
[Mon Sep 07 11:18:28.037747 2020] [:error] [pid 19514] [remote 172.30.180.80:24]     self._semantic = self._get_version_from_pkg_resources()
[Mon Sep 07 11:18:28.037752 2020] [:error] [pid 19514] [remote 172.30.180.80:24]   File "/var/www/webapps/jiratest/jiratest_venv/lib/python3.6/site-packages/pbr/version.py", line 444, in _get_version_from_pkg_resources
[Mon Sep 07 11:18:28.037771 2020] [:error] [pid 19514] [remote 172.30.180.80:24]     except pkg_resources.DistributionNotFound:
[Mon Sep 07 11:18:28.037790 2020] [:error] [pid 19514] [remote 172.30.180.80:24] AttributeError: 'module' object has no attribute 'DistributionNotFound'

**Comment by GrahamDumpleton** [comment]
Are you sure mod_wsgi is compiled for Python 3.6? You can't point mod_wsgi compiled for one Python version at a virtual environment created for a different Python version.

Are you also sure you have installed the most up to date ``setuptools`` and ``pbr`` package versions?

This looks mostly like an incompatibility issue between versions of packages installed.

Also, don't use the way you are to activate the Python virtual environment. For proper details of how to enable the virtual environment see:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by droy30** [comment]
Thanks Graham.
I uninstalled the mod_wsgi which was installed with yum and installed from your source code , compiled with python3 which I am using to setup my application virtual environment. 
Upgraded setuptools to latest version, now I do not see the error on the module import.

Now I get the error with loading the environment variable from the flask application, can you please provide the right way of doing that with mod_wsgi.

**Error Log:**
[Mon Sep 07 12:26:06.922990 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653] mod_wsgi (pid=24403): Failed to exec Python script file '/var/www/webapps/jiratest/jiratest.wsgi'.
[Mon Sep 07 12:26:06.923047 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653] mod_wsgi (pid=24403): Exception occurred processing WSGI script '/var/www/webapps/jiratest/jiratest.wsgi'.
[Mon Sep 07 12:26:06.923172 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653] Traceback (most recent call last):
[Mon Sep 07 12:26:06.923212 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653]   File "/var/www/webapps/jiratest/jiratest.wsgi", line 10, in <module>
[Mon Sep 07 12:26:06.923217 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653]     from jiratest import app as application
[Mon Sep 07 12:26:06.923223 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653]   File "/var/www/webapps//jiratest/jiratest.py", line 14, in <module>
[Mon Sep 07 12:26:06.923235 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653]     app.config.from_envvar('APP_SETTINGS')
[Mon Sep 07 12:26:06.923242 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653]   File "/var/www/webapps/jiratest/jiratest_venv/lib/python3.6/site-packages/flask/config.py", line 109, in from_envvar
[Mon Sep 07 12:26:06.923246 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653]     "point to a configuration file" % variable_name
[Mon Sep 07 12:26:06.923265 2020] [wsgi:error] [pid 24403] [remote 172.30.180.80:54653] RuntimeError: The environment variable 'APP_SETTINGS' is not set and as such configuration could not be loaded.  Set this variable and make it point to a configuration file

Also, I followed your guide for activating the virtual environment, is there anything specific I need to change in my .wsgi file? Like pointing to an empty venv from the apache virtualhost configuation?

**Comment by GrahamDumpleton** [comment]
Environment variables in your user account are not inherited by system Apache. You would need to set environment variables from the WSGI script file, or add code to read them from a separate configuration file.

**Comment by droy30** [comment]
Thanks Graham , I was able to set the environment variables from the wsgi script file. 
Also I followed the mod_wsgi documentation to enable the virtual environment, any specific area where it should be changed? 
I am running mod_wsgi in daemon mode and have multiple directories configured under apache virtualhost for separate projects.

Apache (httpd) configuration:
<VirtualHost *:443>
 WSGIDaemonProcess jiradns  user=apache group=apache threads=5
    WSGIProcessGroup jiradns
    WSGIScriptAlias /jiradns /var/www/webapps/dnsmod/jiradns/jiradns.wsgi
    WSGIScriptReloading On
    <Directory /var/www/webapps/dnsmod/jiradns>
         Require all granted
    </Directory>

    WSGIDaemonProcess jiravmdeployment  user=apache group=apache threads=5
    WSGIProcessGroup jiravmdeployment
    WSGIScriptAlias /jiravmdeployment /var/www/webapps/jiravm/jiravmdeployment/j                                        iravmdeployment.wsgi
    WSGIScriptReloading On
    <Directory /var/www/webapps/jiravm/jiravmdeployment>
         Require all granted
    </Directory>

    WSGIDaemonProcess jiratest  user=apache group=apache threads=5
    WSGIProcessGroup jiratest
    WSGIScriptAlias /jiratest /var/www/webapps/jiratest/jiratest.wsgi
    WSGIScriptReloading On
    <Directory /var/www/webapps/jiratest>
         Require all granted
    </Directory>

</VirtualHost>

**Comment by GrahamDumpleton** [comment]
That will not work as you intend as only the last ``WSGIProcessGroup`` directive will be used. They need to be scoped within a ``Directory`` or ``Location``, or set it on the ``WSGIScriptAlias`` instead. So use:

```
<VirtualHost *:443>
    WSGIDaemonProcess jiradns  user=apache group=apache threads=5
    WSGIScriptAlias /jiradns /var/www/webapps/dnsmod/jiradns/jiradns.wsgi process-group=jiradns application-group=%{GLOBAL}

    <Directory /var/www/webapps/dnsmod/jiradns>
         Require all granted
    </Directory>

    WSGIDaemonProcess jiravmdeployment  user=apache group=apache threads=5

    WSGIScriptAlias /jiravmdeployment /var/www/webapps/jiravm/jiravmdeployment/j                                        iravmdeployment.wsgi process-group=jiravmdeployment application-group=%{GLOBAL}

    <Directory /var/www/webapps/jiravm/jiravmdeployment>
         Require all granted
    </Directory>

    WSGIDaemonProcess jiratest  user=apache group=apache threads=5

    WSGIScriptAlias /jiratest /var/www/webapps/jiratest/jiratest.wsgi process-group=jiratest application-group=%{GLOBAL}

    <Directory /var/www/webapps/jiratest>
         Require all granted
    </Directory>

</VirtualHost>
```

You don't need to set ``WSGIScriptReloading On`` as that is the default.

Since each WSGI application is in a separate daemon process group, also good idea to set ``application-group=%{GLOBAL}`` so the main interpreter context is used. This avoids problems with third party Python modules that do not work properly in Python sub interpreters.

**Comment by droy30** [comment]
Thanks for the suggestion Graham. With the apache setup you suggested, can i still activate the python virtual environment from the wsgi files for the different applications.
Eg: **_wsgi file for jiradns_**

import os
python_home='/var/www/webapps/dnsmod/jiradns/jiradns_venv'

activate_this = python_home + '/bin/activate_this.py'

with open(activate_this) as file_:
  exec(file_.read(), dict(__file__=activate_this))

sys.path.insert(0, '/var/www/webapps/dnsmod/jiradns/')

from jiradns import app as application

Eg: **_wsgi file for jiravmdeployment_**  

import sys
import os

os.environ['APP_SETTINGS'] = '/var/flaskconfig/config.cfg'

python_home='/var/www/webapps/jiravm/jiravmdeployment/jiravmdeployment_venv'
activate_this = python_home + '/bin/activate_this.py'

with open(activate_this) as file_:
  exec(file_.read(), dict(__file__=activate_this))
sys.path.insert(0, '/var/www/webapps/jiravm/jiravmdeployment/')

from jiravmdeployment import app as application

**Comment by GrahamDumpleton** [comment]
Use of `activate_this.py` is highly discouraged. Is there a specific reason you want to do it that way?

The recommended way is to use the `python-home` option to `WSGIDaemonProcess` directive.

See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by droy30** [comment]
Our target was to host multiple flask applications on a single server , each with their own virtual environments.
So each application was configured to run as Daemon Mode (Single Application) as you can see from the apache configuration.

We followed a few guides and deployed this scenario where in each application runs under separate daemon mode and the wsgi files for each then activate their individual virtual environments.

If we change the apache config to the one you suggested, can you please suggest what will be the wsgi file configuration for each application. 
From what I understood, since with your setup, we set the python-home in the WSGIDaemonProcess directive in apache, this need not be specified in the application wsgi files . Correct me if my understanding is not right.

**Comment by GrahamDumpleton** [comment]
Use something like:

```
<VirtualHost *:443>
    WSGIDaemonProcess jiradns  user=apache group=apache threads=5 python-home=/var/www/webapps/dnsmod/jiradns/jiradns_venv
    WSGIScriptAlias /jiradns /var/www/webapps/dnsmod/jiradns/jiradns.wsgi process-group=jiradns application-group=%{GLOBAL}

    <Directory /var/www/webapps/dnsmod/jiradns>
         Require all granted
    </Directory>

    WSGIDaemonProcess jiravmdeployment  user=apache group=apache threads=5 python-home=/var/www/webapps/jiravm/jiravmdeployment/jiravmdeployment_venv

    WSGIScriptAlias /jiravmdeployment /var/www/webapps/jiravm/jiravmdeployment/j                                        iravmdeployment.wsgi process-group=jiravmdeployment application-group=%{GLOBAL}

    <Directory /var/www/webapps/jiravm/jiravmdeployment>
         Require all granted
    </Directory>

    WSGIDaemonProcess jiratest  user=apache group=apache threads=5 python-home=/some/other/venv

    WSGIScriptAlias /jiratest /var/www/webapps/jiratest/jiratest.wsgi process-group=jiratest application-group=%{GLOBAL}

    <Directory /var/www/webapps/jiratest>
         Require all granted
    </Directory>

</VirtualHost>
```

So you can set `python-home` for each `WSGIDaemonProcess` differently so each uses different virtual environment.

If do that you don't need to do the activation in the WSGI script file.

**Comment by droy30** [comment]
I followed the apache configuration like you suggested and below is the wsgi file for one project.

import sys
import os

os.environ['APP_SETTINGS'] = '/var/flaskconfig/config.cfg'

print("hello from jiravmdeployment wsgi as a new process")

from jiravmdeployment import app as application

But it is throwing error that it cannot find the module "**jiravmdeployment** " , do i need to specify the full path or set the python path somewhere.
Below is the error log:

**[Mon Oct 26 12:43:41.844457 2020] [wsgi:error] [pid 102246] hello from jiravmdeployment wsgi as a new process
[Mon Oct 26 12:43:41.844587 2020] [wsgi:error] [pid 102246] mod_wsgi (pid=102246): Failed to exec Python script file '/var/www/webapps/jiravm/jiravmdeployment/jiravmdeployment.wsgi'.
[Mon Oct 26 12:43:41.844605 2020] [wsgi:error] [pid 102246] mod_wsgi (pid=102246): Exception occurred processing WSGI script '/var/www/webapps/jiravm/jiravmdeployment/jiravmdeployment.wsgi'.
[Mon Oct 26 12:43:41.849011 2020] [wsgi:error] [pid 102246] Traceback (most recent call last):
[Mon Oct 26 12:43:41.849037 2020] [wsgi:error] [pid 102246]   File "/var/www/webapps/jiravm/jiravmdeployment/jiravmdeployment.wsgi", line 15, in <module>
[Mon Oct 26 12:43:41.849040 2020] [wsgi:error] [pid 102246]     from jiravmdeployment import app as application
[Mon Oct 26 12:43:41.849051 2020] [wsgi:error] [pid 102246] ModuleNotFoundError: No module named 'jiravmdeployment'**

**Comment by GrahamDumpleton** [comment]
Do you still have the ``sys.path.insert()`` line in your WSGI script file?

Rather than trying to set that in the WSGI script file, it is recommended to set the location of your project using ``python-path`` option to ``WSGIDaemonProcess``.

Either way, you would still need to set the location of your project somehow. This is separate to setting location of the virtual environment.

Show your current Apache configuration for mod_wsgi and contents of the WSGI script file.

**Comment by droy30** [comment]
Current Apache configuration:

**<VirtualHost *:443>
    WSGIDaemonProcess jiradns  user=apache group=apache threads=5 python-home=/var/www/webapps/dnsmod/jiradns/jiradns_venv
    WSGIScriptAlias /jiradns /var/www/webapps/dnsmod/jiradns/jiradns.wsgi process-group=jiradns application-group=%{GLOBAL}

    <Directory /var/www/webapps/dnsmod/jiradns>
         Require all granted
    </Directory>

    WSGIDaemonProcess jiravmdeployment  user=apache group=apache threads=5 python-home=/var/www/webapps/jiravm/jiravmdeployment/jiravmdeployment_venv

    WSGIScriptAlias /jiravmdeployment /var/www/webapps/jiravm/jiravmdeployment/j                                        iravmdeployment.wsgi process-group=jiravmdeployment application-group=%{GLOBAL}

    <Directory /var/www/webapps/jiravm/jiravmdeployment>
         Require all granted
    </Directory>

</VirtualHost>**

Wsgi script for jiravmdeployment project: **/var/www/webapps/jiravm/jiravmdeployment/j                                        iravmdeployment.wsgi** Will this work?

**import sys
import os

os.environ['APP_SETTINGS'] = '/var/flaskconfig/config.cfg'

print("hello from jiravmdeployment wsgi as a new process")

sys.path.insert(0, '/var/www/webapps/jiravm/jiravmdeployment/')
from jiravmdeployment import app as application**

**Comment by GrahamDumpleton** [comment]
What is the path to the ``app.py`` file?

If it is:

```
/var/www/webapps/jiravm/jiravmdeployment/app.py
```

then the path you should be adding ``sys.path`` should be:

```
/var/www/webapps/jiravm
```

not:

```
/var/www/webapps/jiravm/jiravmdeployment
```

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
