### ISSUE TITLE
python 3.8 flask apache 2.4 wsgi multiprocessing RuntimeError: fork not supported for subinterpreters

### ISSUE THREAD

**Issue by israelariel** [GrahamDumpleton/mod_wsgi#614]
I am trying to run a code in Ubuntu 20.04, with python 3.8, flask, wsgi and using multiprocessing. I wrote a code that works just fine with python. This is the code
[my_flask_mul_app.zip](https://github.com/GrahamDumpleton/mod_wsgi/files/5212900/my_flask_mul_app.zip)

When running the former code I get the error: RuntimeError: fork not supported for subinterpreters. I read the documentation an I find nothing. I also check the python 3.8's bug bugzilla.redhat.com/show_bug.cgi?id=1745894 and it seems that it was solved... Its been a week and I got nothing.. Any Ideas?

**Comment by GrahamDumpleton** [comment]
Python 3.8 started to introduce restrictions on what you can do in Python sub interpreters. Python sub interpreters cause various other issues with third party Python modules that aren't designed to work in sub interpreters. For that reason it has been long recommended to avoid them when using mod_wsgi.

To do that, ensure you are using mod_wsgi daemon mode, with only one WSGI application delegated to any mod_wsgi daemon process group. Then force the use of the main Python interpreter context for the WSGI application.

You should delve into the documentation, but in short, use something like the following:

```
# Outside of VirtualHost. This disabled embedded mode to ensure you are using daemon mode.

WSGIRestrictEmbedded On

# Inside of VirtualHost (presuming you are using them).

WSGIDaemonProcess myapp
WSGIScriptAlias / /some/path/myapp.py process-group=myapp application-group=%{GLOBAL}
```

There is a lot more to setting up Apache/mod_wsgi properly. I would therefore suggest you start out by watching:

* https://www.youtube.com/watch?v=CPz0s1CQsTE&t=6s

**Comment by israelariel** [comment]
thanks for the reply... Your video really clear things out....
