### ISSUE TITLE
No Module Named flask [Apache/2.4.37 (centos) mod_wsgi/3.4 Python/2.7.17]

### ISSUE THREAD

**Issue by anesh** [GrahamDumpleton/mod_wsgi#617]
mod_wsgi is not able to locate flask module

[Tue Sep 22 10:43:03.255258 2020] [mpm_event:notice] [pid 128269:tid 139769983646016] AH00489: Apache/2.4.37 (centos) mod_wsgi/3.4 Python/2.7.17 configured -- resuming normal operations
[Tue Sep 22 10:43:03.255340 2020] [core:notice] [pid 128269:tid 139769983646016] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Tue Sep 22 10:43:16.717273 2020] [:error] [pid 128281:tid 139769351493376] ['app', 'run.py', 'wsgi.py']
[Tue Sep 22 10:43:16.718452 2020] [:error] [pid 128281:tid 139769351493376] ['/var/www/hitme', '/home/anesh/.local/lib/python2.7/site-packages', '/usr/lib/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages', '/home/anesh/.local/lib/python2.7/site-packages', '/home/anesh/.local/lib/python2.7/site-packages']
[Tue Sep 22 10:43:16.718495 2020] [:error] [pid 128281:tid 139769351493376] 2.7.17 (default, Jun  5 2020, 03:38:32) 
[Tue Sep 22 10:43:16.718515 2020] [:error] [pid 128281:tid 139769351493376] [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
[Tue Sep 22 10:43:16.718537 2020] [:error] [pid 128281:tid 139769351493376] /usr
[Tue Sep 22 10:43:16.718984 2020] [:error] [pid 128281:tid 139769351493376] ['/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages', '/usr/lib/site-python']
[Tue Sep 22 10:43:16.719273 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613] mod_wsgi (pid=128281): Target WSGI script '/var/www/hitme/wsgi.py' cannot be loaded as Python module.
[Tue Sep 22 10:43:16.719301 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613] mod_wsgi (pid=128281): Exception occurred processing WSGI script '/var/www/hitme/wsgi.py'.
[Tue Sep 22 10:43:16.719510 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613] Traceback (most recent call last):
[Tue Sep 22 10:43:16.719614 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613]   File "/var/www/hitme/wsgi.py", line 10, in <module>
[Tue Sep 22 10:43:16.719804 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613]     from app import app as application
[Tue Sep 22 10:43:16.719843 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613]   File "/var/www/hitme/app/__init__.py", line 11, in <module>
[Tue Sep 22 10:43:16.719975 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613]     from flask import Flask
[Tue Sep 22 10:43:16.720030 2020] [:error] [pid 128281:tid 139769351493376] [client 192.168.64.1:49613] ImportError: No module named flask

**Comment by GrahamDumpleton** [comment]
Use a Python virtual environment, but don't locate it under your home directory. Don't install packages you need in the per user `site-packages` directory. Most likely the issue is that the user that Apache runs your code as can't access anything inside of the `/home/anesh` directory.

Beyond that guess, I would need to see the mod_wsgi configuration you are using and you would have to say where Flask package is installed.

**Comment by anesh** [comment]
Using a Python virtual environment resolved the issue
