### ISSUE TITLE
[wsgi:error] ModuleNotFoundError: No module named 'regex._regex'

### ISSUE THREAD

**Issue by Mahbuba-Tasmin** [GrahamDumpleton/mod_wsgi#618]
Issue: ### When calling nltk package installed at miniconda3 environment from flask on apache server, Centos 7 platform, the module regex not found error raises. The python script runs perfect when running standalone, but serving from server creating the issue. Apache server also works fine without specific call to nltk package. I have checked the regex installation, it does not have any script name '_regex', regex version ==2020.7.14, why is WSGI asking for this particular package? @nltk @mod_wsgi

I have gone through several tutorials including this one -
 [https://stackoverflow.com/questions/30581316/how-do-i-use-a-conda-environment-with-mod-wsgi]
[http://blog.dscpl.com.au/2014/09/using-python-virtual-environments-with.html] for activating conda environment with mod_wsgi. I have also tried compiling mod_wsgi in conda environment, somehow it is not installing the modules folder in there and not working. 

[wsgi:error] ModuleNotFoundError: No module named 'regex._regex'
[wsgi:error] mod_wsgi Failed to exec Python script file '/var/www/chatbotv1/chatbotv1.wsgi'.
[wsgi:error] Exception occurred processing WSGI script '/var/www/chatbotv1/chatbotv1.wsgi'.
[wsgi:error] Traceback (most recent call last):,
[wsgi:error] File "/var/www/chatbotv1/chatbotv1.wsgi", line 16, in ,
[wsgi:error] from app import app as application,
[wsgi:error] File "/var/www/chatbotv1/app.py", line 2, in
[wsgi:error] from chatbot_response import response
[wsgi:error] File "/var/www/chatbotv1/chatbot_response.py", line 2, in
[wsgi:error] import nltk
[wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/init.py", line 133
[wsgi:error] from nltk.text import *
[wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/text.py", line 30, in
[wsgi:error] from nltk.tokenize import sent_tokenize
[wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/tokenize/init.py", line 66, in
[wsgi:error] from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
[wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/nltk/tokenize/casual.py", line 38, in
[wsgi:error] import regex # nltk/nltk#2409
[wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/regex/init.py", line 1, in
[wsgi:error] from .regex import *
[wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/regex/regex.py", line 404, in
[wsgi:error] import regex._regex_core as _regex_core
[wsgi:error] File "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/regex/_regex_core.py", line 21, in
[wsgi:error] import regex._regex as _regex
[wsgi:error] ModuleNotFoundError: No module named 'regex._regex'

Environment (conda list):
Details
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_tflow_select             2.3.0                       mkl
absl-py                   0.10.0                   py38_0
aniso8601                 8.0.0                      py_0
astunparse                1.6.3                      py_0
blas                      1.0                         mkl
blinker                   1.4                      py38_0
brotlipy                  0.7.0           py38h7b6447c_1000
c-ares                    1.16.1               h7b6447c_0
ca-certificates           2020.7.22                     0    anaconda
cachetools                4.1.1                      py_0
certifi                   2020.6.20                py38_0    anaconda
cffi                      1.14.3           py38he30daa8_0
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cryptography              3.1.1            py38h1ba5d50_0
flask                     1.1.2                      py_0
flask-restful             0.3.8                      py_0    conda-forge
gast                      0.3.3                      py_0
google-auth               1.21.3                     py_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.2.0                      py_0
grpcio                    1.31.0           py38hf8bcb03_0
h5py                      2.10.0           py38hd6299e0_1
hdf5                      1.10.6               hb1b8bf9_0
idna                      2.10                       py_0
importlib-metadata        1.7.0                    py38_0
intel-openmp              2020.2                      254
itsdangerous              1.1.0                      py_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0    anaconda
keras-preprocessing       1.1.0                      py_1
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libprotobuf               3.12.4               hd408876_0
libstdcxx-ng              9.1.0                hdf63c60_0
markdown                  3.2.2                    py38_0
markupsafe                1.1.1            py38h7b6447c_0
mkl                       2020.2                      256
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.2.0            py38h23d657b_0
mkl_random                1.1.1            py38h0573a6f_0
ncurses                   6.2                  he6710b0_1
nltk                      3.5                        py_0    anaconda
numpy                     1.19.1           py38hbc911f0_0
numpy-base                1.19.1           py38hfa32c7d_0
oauthlib                  3.1.0                      py_0
openssl                   1.1.1h               h7b6447c_0    anaconda
opt_einsum                3.1.0                      py_0
pip                       20.2.2                   py38_0
protobuf                  3.12.4           py38he6710b0_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.8                      py_0
pycparser                 2.20                       py_2
pyjwt                     1.7.1                    py38_0
pyopenssl                 19.1.0                     py_1
pysocks                   1.7.1                    py38_0
python                    3.8.5                h7579374_1
python-dateutil           2.8.1                      py_0
pytz                      2020.1                     py_0
readline                  8.0                  h7b6447c_0
regex                     2020.7.14        py38h7b6447c_0    anaconda
requests                  2.24.0                     py_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.6                        py_0
scipy                     1.5.2            py38h0b6359f_0
setuptools                49.6.0                   py38_1
six                       1.15.0                     py_0
sqlite                    3.33.0               h62c20be_0
tensorboard               2.2.1              pyh532a8cf_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.2.0           mkl_py38h6d3daf0_0
tensorflow-base           2.2.0           mkl_py38h5059a2d_0
tensorflow-estimator      2.2.0              pyh208ff02_0
termcolor                 1.1.0                    py38_1
tk                        8.6.10               hbc83047_0
tqdm                      4.49.0                     py_0    anaconda
urllib3                   1.25.10                    py_0
werkzeug                  1.0.1                      py_0
wheel                     0.35.1                     py_0
wrapt                     1.12.1           py38h7b6447c_1
xz                        5.2.5                h7b6447c_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h7b6447c_3
(conda-tensorflow) [root@DEV-AI02 ~]# cd /etc/httpd/sites-enabled
(conda-tensorflow) [root@DEV-AI02 sites-enabled]# sudo vi chatbotv1.conf
requests                  2.24.0                     py_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.6                        py_0
scipy                     1.5.2            py38h0b6359f_0
setuptools                49.6.0                   py38_1
six                       1.15.0                     py_0
sqlite                    3.33.0               h62c20be_0
tensorboard               2.2.1              pyh532a8cf_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.2.0           mkl_py38h6d3daf0_0
tensorflow-base           2.2.0           mkl_py38h5059a2d_0
tensorflow-estimator      2.2.0              pyh208ff02_0
termcolor                 1.1.0                    py38_1
tk                        8.6.10               hbc83047_0
tqdm                      4.49.0                     py_0    anaconda
urllib3                   1.25.10                    py_0
werkzeug                  1.0.1                      py_0
wheel                     0.35.1                     py_0
wrapt                     1.12.1           py38h7b6447c_1
xz                        5.2.5                h7b6447c_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h7b6447c_3

Details about conda and system ( conda info ):
Details
     active environment : base
    active env location : /var/www/chatbotv1/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files :
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.17
       base environment : /var/www/chatbotv1/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /var/www/chatbotv1/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /var/www/chatbotv1/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.8.3 Linux/3.10.0-1127.19.1.el7.x86_64 centos/7.8.2003 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False

Here is the WSGI script

`#!/var/www/chatbotv1/miniconda3/

import sys
import site
site.addsitedir('/var/www/chatbotv1//miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/')
sys.path.insert(0, '/var/www/chatbotv1/')
import os
print(os.listdir('/var/www/chatbotv1'))
from app import app as application
`

Also the configuration file of apache

`LoadModule wsgi_module /usr/lib64/httpd/modules/mod_wsgi.so
ServerName localhost
<VirtualHost *:80>
ServerAlias chatbotv1
WSGIDaemonProcess chatbotv1 python-home=/var/www/chatbotv1/miniconda3
WSGIScriptAlias / /var/www/chatbotv1/chatbotv1.wsgi
<Directory /var/www/chatbotv1>
Require all granted

Alias /static /var/www/chatbotv1/static
<Directory /var/www/chatbotv1/static>
Require all granted

DocumentRoot /var/www/chatbotv1
ErrorLog /var/www/chatbotv1/log/error.log
CustomLog /var/www/chatbotv1/log/requests.log combined

**Comment by GrahamDumpleton** [comment]
As stated in the documentation:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

You cannot use a Python virtual environment created for one Python version/distribution, with a mod_wsgi compiled for a different Python version/distribution.

Because it looks like you are using system package for mod_wsgi, it would not be compiled for Anaconda Python and also sorts of things are likely not going to work.

You need to uninstall system Python and compile mod_wsgi from source code with Anaconda Python and configure Apache to use it. For some guidance see:

* https://pypi.org/project/mod-wsgi/

If you have tried that already, you need to say exactly why you couldn't get mod_wsgi installed from source code. Saying "somehow it is not installing the modules folder in there and not working" doesn't tell me enough.

**Comment by Mahbuba-Tasmin** [comment]
I am facing an error from apxs - **apxs:Error: Command failed with rc=65536** . Here is the configuration statement - `./configure ==with-apxs=/usr/bin/apxs --with-python=/var/www/chatbotv1/miniconda3/bin/python3.8`

(conda-tensorflow) [root@DEV-AI02 mod_wsgi-4.6.5]# make
/usr/bin/apxs -c -I/var/www/chatbotv1/miniconda3/include/python3.8 -DNDEBUG  -Wc                                                                                                                                                             ,-g -Wc,-O2  src/server/mod_wsgi.c src/server/wsgi_*.c -L/var/www/chatbotv1/mini                                                                                                                                                             conda3/lib -L/var/www/chatbotv1/miniconda3/lib/python3.8/config  -lpython3.8 -lp                                                                                                                                                             thread -ldl -lutil -lrt -lm
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                                                                                                                                                             c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                                                                                                                                                             ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                                                                                                                                                              -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                                                                                                                                                                -I/usr/include/apr-1  -g -O2 -I/var/www/chatbotv1/miniconda3/include/python3.8                                                                                                                                                              -DNDEBUG  -c -o src/server/mod_wsgi.lo src/server/mod_wsgi.c && touch src/server                                                                                                                                                             /mod_wsgi.slo
src/server/mod_wsgi.c: In function 'Adapter_start_response':
src/server/mod_wsgi.c:2111:25: warning: variable 'thread_info' set but not used                                                                                                                                                              [-Wunused-but-set-variable]
         WSGIThreadInfo *thread_info;
                         ^
src/server/mod_wsgi.c: In function 'wsgi_python_child_init':
src/server/mod_wsgi.c:4349:9: warning: 'PyOS_AfterFork' is deprecated (declared                                                                                                                                                              at /var/www/chatbotv1/miniconda3/include/python3.8/intrcheck.h:18) [-Wdeprecated                                                                                                                                                             -declarations]
         PyOS_AfterFork();
         ^
src/server/mod_wsgi.c: In function 'wsgi_log_stack_traces':
src/server/mod_wsgi.c:9456:30: warning: assignment discards 'const' qualifier fr                                                                                                                                                             om pointer target type [enabled by default]
                     filename = PyUnicode_AsUTF8(current->f_code->co_filename);
                              ^
src/server/mod_wsgi.c:9457:26: warning: assignment discards 'const' qualifier fr                                                                                                                                                             om pointer target type [enabled by default]
                     name = PyUnicode_AsUTF8(current->f_code->co_name);
                          ^
src/server/mod_wsgi.c: In function 'wsgi_process_proxy_headers':
src/server/mod_wsgi.c:13883:25: warning: variable 'value' set but not used [-Wun                                                                                                                                                             used-but-set-variable]
             const char *value = NULL;
                         ^
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                                                                                                                                                             c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                                                                                                                                                             ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                                                                                                                                                              -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                                                                                                                                                                -I/usr/include/apr-1  -g -O2 -I/var/www/chatbotv1/miniconda3/include/python3.8                                                                                                                                                              -DNDEBUG  -c -o src/server/wsgi_apache.lo src/server/wsgi_apache.c && touch src/                                                                                                                                                             server/wsgi_apache.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                                                                                                                                                             c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                                                                                                                                                             ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                                                                                                                                                              -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                                                                                                                                                                -I/usr/include/apr-1  -g -O2 -I/var/www/chatbotv1/miniconda3/include/python3.8                                                                                                                                                              -DNDEBUG  -c -o src/server/wsgi_buckets.lo src/server/wsgi_buckets.c && touch sr                                                                                                                                                             c/server/wsgi_buckets.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                                                                                                                                                             c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                                                                                                                                                             ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                                                                                                                                                              -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                                                                                                                                                                -I/usr/include/apr-1  -g -O2 -I/var/www/chatbotv1/miniconda3/include/python3.8                                                                                                                                                              -DNDEBUG  -c -o src/server/wsgi_convert.lo src/server/wsgi_convert.c && touch sr                                                                                                                                                             c/server/wsgi_convert.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                                                                                                                                                             c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                                                                                                                                                             ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                                                                                                                                                              -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                                                                                                                                                                -I/usr/include/apr-1  -g -O2 -I/var/www/chatbotv1/miniconda3/include/python3.8                                                                                                                                                              -DNDEBUG  -c -o src/server/wsgi_daemon.lo src/server/wsgi_daemon.c && touch src/                                                                                                                                                             server/wsgi_daemon.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                                                                                                                                                             c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                                                                                                                                                             ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                                                                                                                                                              -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                                                                                                                                                                -I/usr/include/apr-1  -g -O2 -I/var/www/chatbotv1/miniconda3/include/python3.8                                                                                                                                                              -DNDEBUG  -c -o src/server/wsgi_interp.lo src/server/wsgi_interp.c && touch src/                                                                                                                                                             server/wsgi_interp.slo
src/server/wsgi_interp.c: In function 'ShutdownInterpreter_call':
src/server/wsgi_interp.c:341:32: error: dereferencing pointer to incomplete type
         tstate = tstate->interp->tstate_head;
                                ^
src/server/wsgi_interp.c: In function 'newInterpreterObject':
src/server/wsgi_interp.c:440:22: error: dereferencing pointer to incomplete type
         while (interp->next)
                      ^
src/server/wsgi_interp.c:441:28: error: dereferencing pointer to incomplete type
             interp = interp->next;
                            ^
apxs:Error: Command failed with rc=65536

**Comment by GrahamDumpleton** [comment]
Use the latest mod_wsgi version, not the old version you are using. The old version isn't compatible with Python 3.7+.

Don't use the configure/make/make install method of installing it, use the `pip install` method explained at:

* https://pypi.org/project/mod-wsgi/

**Comment by Mahbuba-Tasmin** [comment]
Okay, I have installed it and used `mod_wsgi-express module-config` this command to get the configuration according to this link:
 [](https://groups.google.com/g/modwsgi/c/w6-31hnZlBo). 
Now I am getting cannot load module at the provided mod_wsgi.so location within conda directory. Here is the updated configuration file:
`WSGIPythonHome /var/www/chatbotv1/miniconda3/envs/conda-tensorflow
LoadModule wsgi_module /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
ServerName localhost
<VirtualHost *:80>
    ServerAlias chatbotv1
    WSGIDaemonProcess chatbotv1 python-home=/var/www/chatbotv1/miniconda3
    WSGIScriptAlias / /var/www/chatbotv1/chatbotv1.wsgi
    <Directory /var/www/chatbotv1>
        Require all granted
    </Directory>
    Alias /static /var/www/chatbotv1/static
    <Directory /var/www/chatbotv1/static>
        Require all granted
    </Directory>
    DocumentRoot /var/www/chatbotv1
    ErrorLog /var/www/chatbotv1/log/error.log
    CustomLog /var/www/chatbotv1/log/requests.log combined

</VirtualHost>
`

**Comment by GrahamDumpleton** [comment]
I need to see the full messages and where you are seeing them. What was the output of `module-config` as well and where did you put that?

**Comment by Mahbuba-Tasmin** [comment]
module-config output
`(conda-tensorflow) [root@DEV-AI02 ~]# mod_wsgi-express module-config
LoadModule wsgi_module "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so"
WSGIPythonHome "/var/www/chatbotv1/miniconda3/envs/conda-tensorflow"`

I have put it at the top of apache config file chatbotv1.conf, inside /etc/httpd/sites-enabled directory. 
`WSGIPythonHome /var/www/chatbotv1/miniconda3/envs/conda-tensorflow
LoadModule wsgi_module /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
ServerName localhost
<VirtualHost *:80>
    ServerAlias chatbotv1
    WSGIDaemonProcess chatbotv1 python-home=/var/www/chatbotv1/miniconda3
    WSGIScriptAlias / /var/www/chatbotv1/chatbotv1.wsgi
    <Directory /var/www/chatbotv1>
        Require all granted
    </Directory>
    Alias /static /var/www/chatbotv1/static
    <Directory /var/www/chatbotv1/static>
        Require all granted
    </Directory>
    DocumentRoot /var/www/chatbotv1
    ErrorLog /var/www/chatbotv1/log/error.log
    CustomLog /var/www/chatbotv1/log/requests.log combined
</VirtualHost>`

**Comment by GrahamDumpleton** [comment]
The ``LoadModule`` needs to come first as shown in `module-config` output.

**Comment by Mahbuba-Tasmin** [comment]
Updated the configuration file but still same error:
`-- Unit httpd.service has begun reloading its configuration
 httpd[16905]: httpd: Syntax error on line 354 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/sites-enabled/chatbotv1.conf: Cannot load /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/
DEV-AI02 polkitd[622]: Unregistered Authentication Agent for unix-process:16899:52061079 (system bus name :1.1109, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
 DEV-AI02 systemd[1]: httpd.service: control process exited, code=exited status=1
DEV-AI02 sudo[16897]: pam_unix(sudo:session): session closed for user root
DEV-AI02 systemd[1]: Reload failed for The Apache HTTP Server.
-- Subject: Unit httpd.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit httpd.service has finished reloading its configuration
--
-- The result is failed.`

**Comment by GrahamDumpleton** [comment]
The syntax error is going to be because you are trying to use one of the mod_wsgi directives before the module is loaded. Check again and make sure sites-enabled file is a symlink to the one in sites-available and you haven't created two separate copies of the file and you are modifying wrong one.

**Comment by Mahbuba-Tasmin** [comment]
Thank you, to avoid confusion I have recreated the sites-available and sites-enabled directories and enabled symlink file between sites-available and sites-enabled. Still the error persists as can't load module. mod_wsgi-express module-config works from conda-environment, localhost also runs without any error from conda. 

Is there any issue with SELinux permission? I have set individual SELinux permission on log file inside the site directory. The directory context is as follows:
(base) [root@DEV-AI02 sites-available]# sudo ls -dZ /var/www/chatbotv1/log/
drwxr-xr-x. root root unconfined_u:object_r:httpd_log_t:s0 /var/www/chatbotv1/log/

Here is how the error looks now:

systemd[1]: Starting The Apache HTTP Server...
httpd[21646]: httpd: Syntax error on line 354 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/sites-enabled/chatbotv1.conf: Cannot load /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so into server: /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object: Permission denied
systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start The Apache HTTP Server.
systemd[1]: Unit httpd.service entered failed state.
systemd[1]: httpd.service failed.

**Comment by Mahbuba-Tasmin** [comment]
Here is the error upon using user=apache group=apache in configuration file

`(conda-tensorflow) [sites-enabled]# sudo apachectl configtest
httpd: Syntax error on line 354 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/sites-enabled/chatbotv1.conf: Cannot load wsgi_module into server: wsgi_module: cannot open shared object file: No such file or directory`

Compiling mod_wsgi inside conda through pip creates "**server**" folder instead of "**modules**" like the system python installation did. Can there be any relation to this with the issue?
I have looked up for this error, and replaced LoadModule with LoadFile according to this issue #338 

The configuration file now:

`LoadFile wsgi_module /var/www/chatbotv1/miniconda3/envs/conda-tensorflow/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
ServerName localhost
<VirtualHost *:80>
    ServerAlias chatbotv1
    WSGIDaemonProcess chatbotv1  user=apache group=apache python-home=/var/www/chatbotv1/miniconda3
    WSGIScriptAlias / /var/www/chatbotv1/chatbotv1.wsgi
    <Directory /var/www/chatbotv1>
        Require all granted
    </Directory>
    Alias /static /var/www/chatbotv1/static
    <Directory /var/www/chatbotv1/static>
        Require all granted
    </Directory>
    DocumentRoot /var/www/chatbotv1
    ErrorLog /var/www/chatbotv1/log/error.log
    CustomLog /var/www/chatbotv1/log/requests.log combined

</VirtualHost>
WSGIPythonHome /var/www/chatbotv1/miniconda3/envs/conda-tensorflow
`

**Comment by GrahamDumpleton** [comment]
It loos like it  is going to be an SELinux issue at this point. I can't help with that, but search GitHub issues and you may find the details.
