### ISSUE TITLE
No module named 'binance'

### ISSUE THREAD

**Issue by blackboxexs** [GrahamDumpleton/mod_wsgi#619]
hello there, I try 'import binance.client ' but it's failed.
in the terminal text "No module named 'binance'" 

It's a new project 

I have python --version
Python 2.7.16
python3 --version
Python 3.8.5

MacOs, Visual studio, python 

I'm lost!!

Anybody can guide me ?

Thanks !

**Comment by GrahamDumpleton** [comment]
For general Python questions use StackOverflow.

**Comment by blackboxexs** [comment]
thanks dude !
