### ISSUE TITLE
how to configure Aapahe mod-wsgi for python 3.6 which is by default configured with python 2.7 on redhat?

### ISSUE THREAD

**Issue by ammarA94** [GrahamDumpleton/mod_wsgi#621]
I have installed Python 3.6 on redhat server which by default already have python 2.7 ,and created a virtual environment and installed all required libraries including Django in that virtual environment with python 3.6. I want to host a django application on Linux server with wsgi but when i visit my domain name it gives the errors of missing libraries which it is looking in python 2.7 environment. I have followed many of your solutions but not succeeded yet.

**Comment by GrahamDumpleton** [comment]
You can't use a virtual environment created for one Python version, with a mod_wsgi compiled for a different version. This is noted in the documentation.

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html#virtual-environment-and-python-version

You would have to uninstall the mod_wsgi compiled for Python 2.7, and install mod_wsgi for Python 3.6 instead. If there is no system package available for that, you would need to compile mod_wsgi from source code.

One way of compiling mod_wsgi from source code is to use `pip`. See:

* https://pypi.org/project/mod-wsgi/

**Comment by ammarA94** [comment]
Okay.. Thank you for response. I will try this and will let you know.
