### ISSUE TITLE
Target WSGI script cannot be loaded as Python module

### ISSUE THREAD

**Issue by Sunag3** [GrahamDumpleton/mod_wsgi#622]
[Thu Oct 22 00:39:50.885272 2020] [mpm_prefork:notice] [pid 22956] AH00171: Graceful restart requested, doing restart
[Thu Oct 22 00:39:51.977754 2020] [so:warn] [pid 22956] AH01574: module wsgi_module is already loaded, skipping
[Thu Oct 22 00:39:51.990067 2020] [lbmethod_heartbeat:notice] [pid 22956] AH02282: No slotmem from mod_heartmonitor
[Thu Oct 22 00:39:51.993584 2020] [mpm_prefork:notice] [pid 22956] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/4.5.18 Python/3.6 configured -- resuming normal operations
[Thu Oct 22 00:39:51.993674 2020] [core:notice] [pid 22956] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Oct 22 00:40:00.655420 2020] [wsgi:error] [pid 25435] [remote ::1:58786] mod_wsgi (pid=25435): Target WSGI script '/var/www/project/bookmarks/bookmarks/wsgi.py' cannot be loaded as Python module.
[Thu Oct 22 00:40:00.655726 2020] [wsgi:error] [pid 25435] [remote ::1:58786] mod_wsgi (pid=25435): Exception occurred processing WSGI script '/var/www/project/bookmarks/bookmarks/wsgi.py'.
[Thu Oct 22 00:40:00.658080 2020] [wsgi:error] [pid 25435] [remote ::1:58786] Traceback (most recent call last):
[Thu Oct 22 00:40:00.658310 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "/var/www/project/bookmarks/bookmarks/wsgi.py", line 16, in <module>
[Thu Oct 22 00:40:00.658325 2020] [wsgi:error] [pid 25435] [remote ::1:58786]     application = get_wsgi_application()
[Thu Oct 22 00:40:00.658345 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "/var/www/project/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Oct 22 00:40:00.658355 2020] [wsgi:error] [pid 25435] [remote ::1:58786]     django.setup(set_prefix=False)
[Thu Oct 22 00:40:00.658372 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "/var/www/project/venv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
[Thu Oct 22 00:40:00.658381 2020] [wsgi:error] [pid 25435] [remote ::1:58786]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Oct 22 00:40:00.658398 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "/var/www/project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
[Thu Oct 22 00:40:00.658412 2020] [wsgi:error] [pid 25435] [remote ::1:58786]     self._setup(name)
[Thu Oct 22 00:40:00.658429 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "/var/www/project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 70, in _setup
[Thu Oct 22 00:40:00.658438 2020] [wsgi:error] [pid 25435] [remote ::1:58786]     self._wrapped = Settings(settings_module)
[Thu Oct 22 00:40:00.658454 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "/var/www/project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 177, in __init__
[Thu Oct 22 00:40:00.658463 2020] [wsgi:error] [pid 25435] [remote ::1:58786]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Oct 22 00:40:00.658479 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "/var/www/project/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
[Thu Oct 22 00:40:00.658488 2020] [wsgi:error] [pid 25435] [remote ::1:58786]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Oct 22 00:40:00.658504 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Thu Oct 22 00:40:00.658521 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Thu Oct 22 00:40:00.658538 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
[Thu Oct 22 00:40:00.658556 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Thu Oct 22 00:40:00.658573 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Thu Oct 22 00:40:00.658590 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Thu Oct 22 00:40:00.658607 2020] [wsgi:error] [pid 25435] [remote ::1:58786]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Thu Oct 22 00:40:00.658653 2020] [wsgi:error] [pid 25435] [remote ::1:58786] ModuleNotFoundError: No module named 'bookmarks'

PFB my Django.conf file

<VirtualHost *:80>
        ServerName 192.168.225.45
        DocumentRoot /var/www/project

        <Directory "/var/www/project">
                Require all granted
        </Directory>
        Alias /static /var/www/project/bookmarks/static
        <Directory "/var/www/project/bookmarks/static">
                Options FollowSymLinks
                Order allow,deny
                Allow from all
                Require all granted
        </Directory>

       WSGIDaemonProcess project python-path=/var/www/project/venv python-home=/var/www/project/venv
       WSGIProcessGroup project
       WSGIScriptAlias / /var/www/project/bookmarks/bookmarks/wsgi.py

        <Directory "/var/www/project/bookmarks/bookmarks">
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>
</VirtualHost>

**Comment by GrahamDumpleton** [comment]
You were already told in other issues to use:

```
WSGIDaemonProcess project python-home=/var/www/project/venv python-path=/var/www/project/bookmarks
WSGIProcessGroup project
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / /var/www/project/bookmarks/bookmarks/wsgi.py
```

You have not set ``python-path`` as told to, it has a different path to ``python-home``.

Also add the ``WSGIApplicationGroup`` as recommended.

**Comment by Sunag3** [comment]
Thanks GrahamDumpleton its up and running, very Much Appreciated , very much helped

**Comment by Sunag3** [comment]
My Application is Up and Running but while accessing the Django Admin Page post Login getting below Errors, i have given all necessary permissions

![image](https://user-images.githubusercontent.com/53913026/96904866-4a1d4380-14b5-11eb-8a1c-43e43655e6ac.png)

**Comment by GrahamDumpleton** [comment]
Apache will run your code as a special user, not you, and that user needs write access to where you store the database. For sqlite that means having write access to both the database file, and the directory it is contained in. If you only have write access to the database file, it will not be able to create the separate database lock file in the directory.

See:

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#access-rights-of-apache-user

**Comment by Sunag3** [comment]
Hi i have given permission for both database and directory, but still having same issue i am unable to perform any write operations also unable to perform admin login, PFB below detailed error.
Also please note we have SELINUX is Enabled for Security policies


Request Method: | POST
-- | --
http://192.168.225.45/
3.1
OperationalError
attempt to write a readonly database
/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py, line 413, in execute
/usr/local/bin/python3
3.6.9
['/home/www/project/bookmarks',  '/home/www/project/venv/lib64/python36.zip',  '/home/www/project/venv/lib64/python3.6',  '/home/www/project/venv/lib64/python3.6/lib-dynload',  '/opt/rh/rh-python36/root/usr/lib64/python3.6',  '/opt/rh/rh-python36/root/usr/lib/python3.6',  '/home/www/project/venv/lib/python3.6/site-packages']
Tue, 08 Dec 2020 18:18:36 +0000

Environment:


Request Method: POST
Request URL: http://192.168.225.45/

Django Version: 3.1
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'testapp']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (attempt to write a readonly database) was the direct cause of the following exception:
  File "/home/www/project/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/www/project/bookmarks/testapp/views.py", line 14, in CandidateView
    form.save(commit=True)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/forms/models.py", line 460, in save
    self.instance.save()
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 751, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 789, in save_base
    force_update, using, update_fields,
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 932, in _do_insert
    using=using, raw=raw,
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /
Exception Value: attempt to write a readonly database

Request information
USER : AnonymousUser

GET: No GET data

Please help, it will be very helpfull for our project

**Comment by GrahamDumpleton** [comment]
@Sunag3 Where is the database file located? Have you configured SELinux policies with an exclusion to write to the directory/file when running under Apache? SELinux will block access to most directories for the user that Apache runs as. Search for policy "httpd_sys_rw_content_t". Eg. https://unix.stackexchange.com/a/50641/197436
