### ISSUE TITLE
I cannot find this version of the whl package 

### ISSUE THREAD

**Issue by JoongiShark** [GrahamDumpleton/mod_wsgi#624]
My configuration environment:  Winndows Server 2012r + VisualC++2015 + Pyhton 3.7+ Apache2.4

**Comment by GrahamDumpleton** [comment]
Wheels are not provided. You need to have the appropriate Microsoft C compiler and Apache distribution installed and build/install it yourself. Use the ``pip install`` method to build/install it, and then use the ``mod_wsgi-express module-config`` command to generate what you should add to the Apache configuration file. See:

* https://pypi.org/project/mod-wsgi/

**Comment by JoongiShark** [comment]
Thanks
