### ISSUE TITLE
lang and locale parameters for WSGIDaemonProcess allow invalid values without warning or error

### ISSUE THREAD

**Issue by mlissner** [GrahamDumpleton/mod_wsgi#625]
I just spent hours trying to figure out why I was getting a `UnicodeDecodeError` when starting up mod_wsgi. I can only imagine what the history is for not using utf-8 by default, but after I figured out that this was yet another mod_wsgi gotcha, I configured the `lang` and `locale` parameters for the `WSGIDaemonProcess` directive. Per the docs, I set them up as:

```txt
    WSGIDaemonProcess cl \
      threads=10 \
      processes=64 \
      lang='en_US.UTF-8' \
      locale='en_US.UTF-8' \
      python-path=/usr/local/lib/python3.8/site-packages/
```

After reading dozens of posts on StackOverflow, and posting [one of my own][so], I eventually resorted to just searching for @GrahamDumpleton and the term "lang" (can you smell the desperation?), i eventually found [an old post on the mailing list][list] that suggested that sometimes a locale might not be installed (in that case, it was a German one).

Turns out that I used a slim docker image, and it only has the following locales:

```txt
locale -a
C
C.UTF-8
POSIX
```

I switched my `lang` and `locale` parameters to `C.UTF-8`, and everything was fixed. 

---

I'm not sure what to do about this. 

 - Documentation might help. 
 - Checking in mod_wsgi for a locale to be installed might help. 
 - I've tried to provide the answer on StackOverflow in hopes that will help. 

This was a really esoteric corner for me that started with mod_wsgi not working with my code (`UnicodeDecodeError`, weird), and ended with me running a linux command I'd never heard of before. Are there ways to do this better? 

[so]: https://stackoverflow.com/questions/64564924/how-to-set-preferred-encoding-in-wsgi-to-utf-8#64564924
[list]: https://groups.google.com/g/modwsgi/c/7qub8mWWDjQ?pli=1

**Comment by GrahamDumpleton** [comment]
FWIW, as you have found Linux distributions, especially container images, don't necessarily have a reasonable set of lang/locale definitions included, thus the reason that lang/locale aren't set by default to something more sensible.

In ``mod_wsgi-express``, which uses a Python wrapper to create the Apache configuration and then start Apache, it tries to calculate a more sensible default based on what the Python environment for that wrapper script uses, and use that, but trying to do that calculation in Apache itself would be much harder.

Thus when manually configuring Apache/mod_wsgi, there isn't really a choice but to know you need to override it manually if the system Apache doesn't itself set a sensible default.

At this point I am going to close this issue as there isn't really much that can be done about it.

**Comment by mlissner** [comment]
I think the heart of this was that there's no error or warning if you configure modwsgi with an invalid locale. Couldn't modwsgi run locale -a when starting up and use that output to make sure things at least make sense?

**Comment by GrahamDumpleton** [comment]
When manually configuring system Apache/mod_wsgi no, as Apache (+systemd) controls startup process and there is no place that can be done. As mentioned ``mod_wsgi-express`` does do something similar since it can do it from the wrapper script before it starts Apache.

**Comment by mlissner** [comment]
Weird. Too bad, but thanks for the details.
