### ISSUE TITLE
`NameError: name 'TypeError' is not defined` in Apache (mod_wsgi)

### ISSUE THREAD

**Issue by Leekyungun** [GrahamDumpleton/mod_wsgi#626]
### Apache
- apr-1.6.5
- apr-util-1.6.1
- httpd-2.4.7
- mod_wsgi-4.6.8
- pcre-8.32

### Python 
- 3.8.5

### Django
- 3.1.2 

### Apache http.conf
```bash
Listen 3600
WSGISocketPrefix /var/run/wsgi
<VirtualHost *:3600>
    WSGIDaemonProcess project_name display-name=project_name
    WSGIScriptAlias / /data/project_name/config/wsgi.py  process-group=api application-group=api
    ServerName project_name
    <Directory /data/project_name/config>
        Order allow,deny
        Allow from all
        Require all granted
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
</VirtualHost>
```

## Error log
```bash
Exception ignored in: <function Local.__del__ at 0x7fd675a70a60>
Traceback (most recent call last):
  File "/data/venv/api/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
```

The above error log is coming out over and over and over again.  
I don't know why there is an asgi related error when I don't use asgi.

**Comment by GrahamDumpleton** [comment]
Are you sure your mod_wsgi is compiled for Python 3.8?

How did you install mod_wsgi?

Find the ``mod_wsgi.so`` file and run ``ldd`` on it. What is the output?

Also, see the following in regards to how to set up use of a Python virtual environment.

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

Doing it from the WSGI script file is not recommended unless you have to. There is nothing shown in your Apache configuration to indicate you set the location of the Python virtual environment there.

Also, you seem to not have included your actual configuration as the configuration above cannot work. Specifically the value given to the ``process-group`` option of ``WSGIScriptAlias`` doesn't match the process group name specified by ``WSGIDaemonProcess`` directive.

**Comment by Leekyungun** [comment]
Thank you. for your answer : )
Give me a little more comment, please.

1. Are you sure your mod_wsgi is compiled for Python 3.8?
Yes, I use python 3.8.5 
I changed the basic version of Python before installing it.
```
sudo unlink /bin/python
sudo ln -s /usr/local/python3/bin/python3.8 
sudo ln -s /bin/python3 /bin/python
```

2. Find the mod_wsgi.so file and run ldd on it.
```
$ ldd mod_wsgi.so 
	linux-vdso.so.1 =>  (0x00007fffdf6b5000)
	libpython3.8.so.1.0 => /usr/local/python3/lib/libpython3.8.so.1.0 (0x00007fdfe8560000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fdfe8329000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdfe810d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fdfe7f09000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fdfe7d06000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fdfe7a04000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fdfe7636000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007fdfe7433000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdfe8d38000)
```

3. this is origin httpd.conf
```
Listen 3600
WSGISocketPrefix /var/run/wsgi
<VirtualHost *:3600>
    WSGIDaemonProcess api processes=2 threads=100 inactivity-timeout=30 maximum-requests=1000 python-home=/data/venv/api display-name=api
    WSGIScriptAlias / /data/{project_name}/config/wsgi_development.py  process-group=api application-group=api
    #WSGISocketPrefix /var/run/wsgi
    ServerName backend
    <Directory /data/{project_name}/config>
        Order allow,deny
        Allow from all
        Require all granted
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
</VirtualHost>
```

**Comment by GrahamDumpleton** [comment]
It is bad practice to replace the system ``/bin/python`` link and point it at your own installed Python version. Doing this can break any system packages or services which rely on the system Python version.

Using a value of ``threads=100`` is a red flag for an incorrect configuration. High numbers of threads for the daemon process is usually never needed and all it does is cause extra memory usage and can reduce performance. Why do you feel you need to set it so high? How long do your requests run for?

Using ``maximum-requests=1000`` to frequently restart the daemon processes is also bad practice. Do you really need to have that and could it be removed.

If you have high throughput and are setting maximum requests, this could be causing very frequent restarts and could explain the stream of errors. Specifically, there appears be some known issues related to the ``asgiref`` code generating errors on Python process shutdown.

* https://github.com/django/asgiref/blob/master/asgiref/local.py#L97

Likely it relates to that.

Specifically what is likely occurring is that the ``__del__`` method of the ``asgiref`` ``Local`` object is being called when the Python interpreter is being destroyed. The problem is that at that point during destruction of the Python interpreter, any modules have had all their contents cleared and so lookups for things, including stuff from builtins, can fail as a result.

You may want to explore the issue with the ``asgiref`` developers, providing a link to this issue in the report you raise and tag me, so can be discussed further.

One suggest is to set:

```
LogLevel info
```

in the Apache configuration. With that it will log details of mod_wsgi daemon process restarts and you will see if you are triggering this because of ``maximum-requests``.

**Comment by Leekyungun** [comment]
Thank you. 
After the installation was finished, it was changed back to origin system python.
I will exclude performance-related variables(`threads`, `maximum-requests`) and try to add them when necessary. Thank you!

I changed the Loglevel(warn -> info).

Thank you for helping me a lot. I'll ask at django repo.
```
[Wed Nov 04 20:08:33.393605 2020] [wsgi:info] [pid 23250:tid 140054350087936] mod_wsgi (pid=23250): Daemon process idle inactivity timer expired, stopping process 'api'.
[Wed Nov 04 20:08:33.393695 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Shutdown requested 'api'.
[Wed Nov 04 20:08:33.394309 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Stopping process 'api'.
[Wed Nov 04 20:08:33.394323 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Destroying interpreters.
[Wed Nov 04 20:08:33.394331 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Destroy interpreter 'api'.
[Wed Nov 04 20:08:33.394355 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): End interpreter 'api'.
Exception ignored in: <function Local.__del__ at 0x7f60f58eaa60>
Traceback (most recent call last):
  File "/data/venv/api/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f60f58eaa60>
Traceback (most recent call last):
  File "/data/venv/api/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Nov 04 20:08:33.456480 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Cleanup interpreter ''.
[Wed Nov 04 20:08:33.457517 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Terminating Python.
[Wed Nov 04 20:08:33.462541 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Python has shutdown.
[Wed Nov 04 20:08:33.462570 2020] [wsgi:info] [pid 23250:tid 140054670247808] mod_wsgi (pid=23250): Exiting process 'api'.
[Wed Nov 04 11:08:34.139274 2020] [wsgi:info] [pid 2320:tid 140054670247808] mod_wsgi (pid=23250): Process 'api' has died, deregister and restart it.
[Wed Nov 04 11:08:34.139305 2020] [wsgi:info] [pid 2320:tid 140054670247808] mod_wsgi (pid=23250): Process 'api' terminated normally, exit code 0
[Wed Nov 04 11:08:34.139312 2020] [wsgi:info] [pid 2320:tid 140054670247808] mod_wsgi (pid=23250): Process 'api' has been deregistered and will no longer be monitored.
[Wed Nov 04 11:08:34.139751 2020] [wsgi:info] [pid 23379:tid 140054670247808] mod_wsgi (pid=23379): Starting process 'api' with uid=1000, gid=1000 and threads=15.
[Wed Nov 04 11:08:34.140189 2020] [wsgi:info] [pid 23379:tid 140054670247808] mod_wsgi (pid=23379): Python home /data/venv/api.
[Wed Nov 04 11:08:34.140236 2020] [wsgi:info] [pid 23379:tid 140054670247808] mod_wsgi (pid=23379): Initializing Python.
[Wed Nov 04 11:08:34.157591 2020] [wsgi:info] [pid 23379:tid 140054670247808] mod_wsgi (pid=23379): Attach interpreter ''.
[Wed Nov 04 11:08:34.172665 2020] [wsgi:info] [pid 23379:tid 140054670247808] mod_wsgi (pid=23379): Create interpreter 'api'.
[Wed Nov 04 11:08:34.175899 2020] [wsgi:info] [pid 23379:tid 140054670247808] mod_wsgi (pid=23379, process='api', application='api'): Loading Python script file '/data/ONT-invest-api/config/wsgi_development.py'.

```

**Comment by Leekyungun** [comment]
I'll leave a comment if there's any other progress or action. 
Have a nice day!
