### ISSUE TITLE
Browser Unable to connect to flask app - Xampp/Apache/mod_wsgi/Win32

### ISSUE THREAD

**Issue by weshinsley** [GrahamDumpleton/mod_wsgi#627]
Hi Graham,

I wondered if I could ask for some configuration help; I've been following the instructions here: https://medium.com/swlh/serve-flask-app-with-xampp-apache-on-windows-4debb4eb0b91 - to try and get a simple first "Hello World" Flask App served through Xampp/Apache on windows, with mod_wsgi.

The steps appear successful, until the final test, in that:

1. I have Xampp 7.1.6/Apache 2.4 (32-bit) installed and running as a service on a Windows 2012R2 server, working well.
2. I have 32-bit Python 3.8 with pip installed, and also the Visual Studio build tools, including the 32-bit VS2015 support that I believe my version of Xampp/Apache was compiled with.
3. I set the `MOD_WSGI_APACHE_ROOTDIR` as a system environment variable, pointing to C:/xampp/apache, and ran `pip install mod-wsgi` - which worked without errors.
4. mod_wsgi-express module-config ran successfully, and I pasted its output:
```
LoadFile "c:/python/python38-32/python38.dll"
LoadModule wsgi_module "c:/python/python38-32/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win32.pyd"
WSGIPythonHome "c:/python/python38-32"
```
right at the top of c:\xampp\apache\conf\httpd.conf - and also noted for later that `Include conf/extra/httpd-vhosts.conf` is present and uncommented. (I already have some vhost entries running, so I knew this must already be there)

Restarted Apache - it starts up and serves what it used to.

So I created a Hello World flask app which will eventually become a monitoring sort of listener...
In `C:/xampp/FlaskApps/monitor` , I made `monitor.py` as a copy/paste of a "hello world" Flask app from the tutorials, and `monitor.wsgi` contains similarly pasted
```
import sys
sys.path.insert(0, 'C:/xampp/FlaskApps/monitor')
from monitor import app as application
```
(At a later desperate stage, I also added an empty ```__init__.py``` in that folder - to no avail) If in that folder, I set the FLASK_APP env variable to monitor.py, and `flask run`, it successfully says "Hello World" when browsing to http://localhost:5000. 

So lastly... (and I guess where I must have something wrong, as I understand it the least), the added virtualhost configuration in c:/xampp/apache/conf/extra/httpd-vhosts.conf looks like this:-

```
<VirtualHost *:5000>
    ServerName localhost:5000
    WSGIScriptAlias / "C:/xampp/FlaskApps/monitor/monitor.wsgi"
    DocumentRoot "C:/xampp/FlaskApps/monitor"
    <Directory C:/xampp/FlaskApps/monitor>
        Require all granted
        Options Indexes FollowSymLinks Includes ExecCGI
    </Directory>
    AddHandler wsgi-script .wsgi
    ErrorLog "logs/monitor_error.log"
    CustomLog "logs/monitor_access.log" common
</VirtualHost>
```

When I restart Apache, it restarts successfully, but nothing is served on http://localhost:5000 - just a pause and "Unable to connect". Apache has created the monitor_error.log file, but there are no errors in it - zero bytes. (And monitor_access.log too). 

There is also nothing much interesting in c:/xampp/apache/logs/error.log - I see a line:
```
[Wed Nov 04 10:15:51.990319 2020] [mpm_winnt:notice] [pid 2996:tid 428] AH00455: Apache/2.4.33 (Win32) mod_wsgi/4.7.1 Python/3.8 OpenSSL/1.0.2n PHP/7.1.16 configured -- resuming normal operations
```

which makes me think mod_wsgi is fairly happy - but browsing to http://localhost:5000 doesn't generate any more lines in the logs. Last potentially useful fact - when running `flask run`, the `monitor.pyc` and `__init__.pyc` files get created, but if I scrub them, they don't get created when trying to browse to localhost:5000.

Wondering if anything jumps out as being wrong here - apologies for the rambling log, and very grateful for any ideas you have.

Thanks,
Wes

**Comment by GrahamDumpleton** [comment]
That blog site is wrong in a number of things it suggests.

First up, I don't recommend XAMMP or WAMP distributions of Apache, they usually don't work as they are missing parts which allow you to build mod_wsgi properly.

I suggest using ApacheLounge distribution.

Second, if you are using a Python virtual environment you can't use the latest released mod_wsgi version, instead using:

```
pip install -U --no-cache-dir https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

it includes a yet to be released fix for virtual environments on Windows.

Thirdly, don't use:

```
<VirtualHost *:5000>
    ServerName localhost:5000
    WSGIScriptAlias / "C:/xampp/FlaskApps/monitor/monitor.wsgi"
    DocumentRoot "C:/xampp/FlaskApps/monitor"
    <Directory C:/xampp/FlaskApps/monitor>
        Require all granted
        Options Indexes FollowSymLinks Includes ExecCGI
    </Directory>
    AddHandler wsgi-script .wsgi
    ErrorLog "logs/monitor_error.log"
    CustomLog "logs/monitor_access.log" common
</VirtualHost>
```

try using:

```
<VirtualHost *:5000>
    ServerName localhost:5000
    WSGIScriptAlias / "C:/xampp/FlaskApps/monitor/monitor.wsgi"
    <Directory C:/xampp/FlaskApps/monitor>
        Require all granted
    </Directory>
    ErrorLog "logs/monitor_error.log"
    CustomLog "logs/monitor_access.log" common
</VirtualHost>
```

You do not want to set ``ExecCGI`` option or have ``AddHandler`` as Apache may try and execute it as a CGI script, which will most likely fail. You also shouldn't set ``DocumentRoot`` to where your source code is as it may mean someone could download your source code if other parts of Apache configuration allowed a URL to map to the source code path.

Finally, if you aren't using PHP, disable it and don't load it into Apache.

That is all I can suggest initially. Try that and come back with what is happening then.

Ensure you have:

```
LogLevel info
```

and not just ``warn`` or ``err`` in Apache configuration for ``LogLevel`` so mod_wsgi generates more log messages about what is going on and whether it is being invoked.

**Comment by weshinsley** [comment]
Many thanks for such a full and speedy reply - I'll those things...

**Comment by weshinsley** [comment]
It'a pity that blog is not as helpful as it seems - and that google offers it so readily...!

So... quick things, 

* Replacing Xampp with ApacheLounge will be a careful migration as we have a few live sites hosted - which include some PHP, Perl and MySQL usage. So that might be for a bit later if it seems that must be the issue...

* Also, I'm not using any python virtual environments (yet) - this is the only thing on the server using Python, so at the moment I've gone with the vanilla 3.8.6 install, upgraded its pip, and installed only flask, mod_wsgi and any dependencies they requested. So I haven't run the pip install - but can do if that's still worth a try.

* I've applied those changes to the VirtualHost so it matches what you wrote exactly.

* I've set LogLevel to info (it was previously warn) - I am still getting nothing in the monitor_error.log and monitor_access.log - I get a few more lines in Apache's error log - but I think only on startup - nothing new when I browser to port 5000, which is still timing out.
```
gured -- resuming normal operations
[Wed Nov 04 11:05:12.399566 2020] [wsgi:info] [pid 5980:tid 352] mod_wsgi (pid=5980): Python home c:/python/python38-32.
[Wed Nov 04 11:05:12.399566 2020] [wsgi:info] [pid 5980:tid 352] mod_wsgi (pid=5980): Initializing Python.
[Wed Nov 04 11:05:12.430810 2020] [wsgi:info] [pid 5980:tid 352] mod_wsgi (pid=5980): Attach interpreter ''.
[Wed Nov 04 11:05:12.446437 2020] [wsgi:info] [pid 5980:tid 352] mod_wsgi (pid=5980): Imported 'mod_wsgi'.
```
Does that shed any light, or is it looking like Xampp is too incomplete for this?

**Comment by weshinsley** [comment]
Oh dear, this is fairly embarrassing - adding `Listen 5000` to httpd.conf appears to solve the problem, and I am now getting a "Hello World" on port http://localhost:5000. It seems the Xampp was wired to only listen on 80 and 443 by default. 

But I imagine I would have run into problems in any case with my virtualhost settings if I'd thought of that earlier.

Many thanks again.
