### ISSUE TITLE
How to contact Graham Dumpleton?

### ISSUE THREAD

**Issue by dukedougal** [GrahamDumpleton/mod_wsgi#63]
What is the best way to contact Graham Dumpleton?

thanks

**Comment by GrahamDumpleton** [comment]
If you have questions about mod_wsgi, use the mailing list:

* http://code.google.com/p/modwsgi/wiki/WhereToGetHelp?tm=6#Asking_Your_Questions

What is it you are after me about?

**Comment by dukedougal** [comment]
It's about something you wrote on wsgi:

http://blog.dscpl.com.au/2012/10/obligations-for-calling-close-on.html

The blog post above seems to conflict with the post below and wanted to ask you about it.  Does this go on the mod_wsgi mailing list?

http://jimmyg.org/blog/2009/using-yield-statements-in-wsgi-middleware-can-be-very-harmful.html

thanks

**Comment by GrahamDumpleton** [comment]
Yes please, prefer it on the mailing list as will be of interest to others.

Be aware that the earlier post's WSGI middleware are broken and not WSGI compliant as they don't properly call close() when exceptions occur.

As to ordering issues, it certainly can get messy and there other strange cases he doesn't even cover. So you do need to have a good understanding of how generators/try/finally and other constructs work.

I don't specifically understand what you are saying conflicts, except perhaps that I don't say not to use yield.

**Comment by dukedougal** [comment]
OK I'll post it there.  Because your code in the example uses yield I wondered if it had a problem.
