### ISSUE TITLE
Flask: Process.start() hanging

### ISSUE THREAD

**Issue by yeblank** [GrahamDumpleton/mod_wsgi#630]
I am using mod_wsgi on windows 10  with Apache/2.4.41 (Win64) and 	python 2.7.15
The application is built using flask.  

Everything works fine except when I try and launch a new python process using "Process.start()" the flow seems to stop and a new Apache window is opened.

I tried writing to a file and even raising an exception from the function createCertThread() but nothing seems to happen.  
Everything works fine when using Flask's development server.

Below is a snippet of code

[kms_api_WSGI.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/5546575/kms_api_WSGI.conf.txt)

def createCertThread(queue, logQueue, certInfo, interCert, interKey, amount):
	open(errB, 'a').write('createCertThread \n')
	a = 1 / 0
	
p = Process(target=createCertThread, args=(self.queue, self.errLogQueue, self.certCfg, self.caInterCert, self.caInterKey, certThreadAmount,)
open(errA, 'a').write('pre-start \n')
p.start()
open(errA, 'a').write('post-start \n')

**Comment by GrahamDumpleton** [comment]
You are in an Apache process, so if ``Process.start()`` is defaulting to starting another instance of whatever is the current application process, you will get an Apache instance and not a Python process.

See if you can tell ``Process()`` what the path to the application executable is you want run, overriding the default.

In general, not sure how good of an idea it is starting new processes is from inside of Apache on Windows. Apart from needing to ensure the correct application executable is used, Apache often runs as a special service, so may not have same access permissions as when running Flask development server from command line.

**Comment by yeblank** [comment]
Thanks for the quick response!!
