### ISSUE TITLE
Is there a simple way to restart mod_wsgi daemon processes one by one?

### ISSUE THREAD

**Issue by efaulhaber** [GrahamDumpleton/mod_wsgi#631]
I am running Apache 2.4.46 with mod_wsgi 4.7.1 to deploy a WSGI application and I want to implement a no-downtime deployment.

The `touch app.wsgi` method worked well, but I like the idea of having two processes, so one can handle requests while the other one restarts. This way, I can serve every request without delays. To do that, I tried using the following config:

```
WSGIDaemonProcess wsgi-app python-home=/usr/local/venvs/empty processes=2 threads=16 display-name=wsgi-app
WSGIScriptAlias / /var/www/wsgi-app/app.wsgi process-group=wsgi-app application-group=%{GLOBAL}
```

Like this, I can deploy as expected. After updating the code, I kill the processes one by one, which then immediately restart and run the new version of the code.

Is there a way to automate this easily? Writing a script to find all process IDs and kill them one by one seems a bit inconvenient to me. Can mod_wsgi do this automatically?

**Comment by GrahamDumpleton** [comment]
There is no way for it to be done automatically by mod_wsgi. A few pointers though.

* The ``display-name`` option allows you to at least set the process name so the target mod_wsgi daemon processes can be found more easily.
* When sending a signal to the processes, ensure you are sending ``SIGUSR1``. This triggers a graceful restart option of the targeted process which will see it try and wait for requests.
* Look at the ``eviction-timeout`` and ``graceful-timeout`` options of ``WSGIDaemonProcess`` for controlling how long it will wait for requests to finish.
* Look at using the ``psutil`` Python module to write a script which makes it easier to identify processes, send signals and wait for exit. https://pypi.org/project/psutil/

**Comment by erik-f** [comment]
Thank you very much for your reply, I will look into it.
