### ISSUE TITLE
Is there a way to disable TLS1.0 and force HSTS for runmodwsgi?

### ISSUE THREAD

**Issue by facelabs** [GrahamDumpleton/mod_wsgi#632]
Is there a way to disable TLS1.0 and force HSTS for runmodwsgi ? Something like manage.py runmodwsgi --tlsv1=false --send-hsts=true 

Or is there another way to achieve this/configure this? I tried to figure this out from the documentation but was not able to :( 
I understand that it uses Apache, and these settings should be derived from Apache, but I am not sure where to configure it

**Comment by GrahamDumpleton** [comment]
Run the command with ``--help`` and you will see the available options.

The options you would be interested in are:

```
  --hsts-policy PARAMS  Specify the HSTS policy that should be applied when
                        HTTPS only connections are being enforced.
```

and:

```
  --include-file FILE-PATH
                        Specify the path to an additional web server
                        configuration file to be included at the end of the
                        generated web server configuration file.
```

The latter allows you to specify a file, in which you could then place something like:

```
SSLProtocol +TLSv1.2 +TLSv1.3
SSLCipherSuite HIGH:!kRSA:!ADH:!eNULL:!LOW:!EXP:!MD5:!3DES
```

Research yourself what are appropriate Apache options and don't trust what I have specified here. Also run a test to make sure they are being applied.

**Comment by facelabs** [comment]
Amazing, thanks so much Graham 🥇 

How I missed the basic "try with --help" step LOL
