### ISSUE TITLE
Target WSGI script not found or unable to stat: /var/www/html/wsgi.py

### ISSUE THREAD

**Issue by janmasar** [GrahamDumpleton/mod_wsgi#633]
Hi
I'm trying to setup mod_wsgi on my VPS (debia10 + ispconfig3) but always get this error (Target WSGI script not found or unable to stat: /var/www/html/wsgi.py). 
I disabled mod_wsgi, then install it inside venv, used mod_wsgi-express module-config to generate content for new wsgi.load and I did re-enable it.

On my vps I use ispconfi3 and this is inside my domain option > Apache Directives:

`WSGIDaemonProcess ecommerce python-home=/usr/local/venvs/colorfulearrings python-path=/var/www/clients/client0/web1/web/commerce`

`WSGIScriptAlias / /var/www/clients/client0/web1/web/ecommerce/ecommerce/wsgi.py`

`Alias /static/ /var/www/clients/client0/web1/web/ecommerce/staticfiles`
`<Directory /var/www/clients/client0/web1/web/ecommerce/staticfiles>`
	`Require all granted`
`</Directory>`

`<Directory /var/www/clients/client0/web1/web/ecommerce>`
`<Files wsgi.py>`
`Require all granted`
`</Files>`
`</Directory>`

Could you please help me out wit this one?
Thank you

**Comment by GrahamDumpleton** [comment]
If it explicitly mentions ``/var/www/html/wsgi.py`` then you must have other configuration related to mod_wsgi in the Apache configuration files which is affecting or triggering it.

Double check you don't have any WSGI??? directives anywhere else, and that you don't have any ``AddHandler`` or ``SetHandler`` which references ``.py`` file extension or ``wsgi-scrript``, or a ``DirectoryIndex`` directive which mentions ``wsgi.py``.

Finally, disabling system mod_wsgi package is not enough if don't want to use it, you must uninstall the system mod_wsgi package if want to use mod_wsgi.so created by ``pip install mod_wsgi`` otherwise the wsgi.load file will get overwritten again later by system package for mod_wsgi if it were updated.

**Comment by janmasar** [comment]
Its working now. Ispconfig did set wsgi for http and also https requests so it was loaded twice. Now I have another problem. I have more domains on my server and I would like to load them with different enviroment. But the module file wsgi.load contains informations only about one domain. I tryed to create extra wsgi2.load file but it says module wsgi_module is already loaded, skipping. Could you please point me right direction? Thank you.

**Comment by GrahamDumpleton** [comment]
A ``wsgi.load`` file is only used to load the module and set important global configuration, such as disabled embedded mode.

Any separate sites you have should be defined in files in the ``sites-available`` directory, which would then be enabled and linked into the ``sites-enabled`` directory.

**Comment by souravjamwal77** [comment]
Hi @GrahamDumpleton I'm using an Amazon Linux 2(OS) and I have built the mod_wsgi package from the tar file. But still I am getting this error. 
After building the mod_wsgi using installed python3.8 I added to modules path in the apache config file LoadModule directive. But still I'm getting this issue.

Do I also need to install mod_wsgi yum package or the build package is enough?

**Comment by GrahamDumpleton** [comment]
@souravjamwal77 Please create a new issue and provide all the details of your Apache/mod_wsgi configuration, along with the errors you see and where, plus relevant parts of Apache error log files showing mod_wsgi log messages. It is impossible to guess what your specific issue is without seeing your actual configuration as it could be quite different to the original poster.

**Comment by souravjamwal77** [comment]
Hi @GrahamDumpleton I've created the issue here
https://github.com/GrahamDumpleton/mod_wsgi/issues/772
Do I need to provide anymore info.
