### ISSUE TITLE
mod_wsgi fails to properly set SCRIPT_PATH & PATH_INFO if the URL ends with a .

### ISSUE THREAD

**Issue by schlenk** [GrahamDumpleton/mod_wsgi#635]
I am seeing this with mod_wsgi 4.7.1 on Windows 10 with Apache 2.4.43. / Python 2.7.18. (but also happens with 4.5.4)

I have a simple WSGIScriptAlias configured like this:

```apache
<IfModule mod_wsgi.c>
    WSGIApplicationGroup %%{GLOBAL}
    WSGIPassAuthorization on

    # All URLs that are not explicitly overriden get handled by the WSGI script
    WSGIScriptAlias / "dispatcher/app.py"
</IfModule>
```

The dispatcher/app.py is mostly trivial and uses the PEP3333 script to reconstruct an URL:

```python
def application(environ, start_response):
    start_response("200 OK", [])
    msg = "SCRIPT_PATH: '%s', PATH_INFO: '%s'" % (environ['SCRIPT_NAME'], environ['PATH_INFO'])
    from six.moves.urllib.parse import quote
    url = environ['wsgi.url_scheme'] + '://'

    if environ.get('HTTP_HOST'):
        url += environ['HTTP_HOST']
    else:
        url += environ['SERVER_NAME']

        if environ['wsgi.url_scheme'] == 'https':
            if environ['SERVER_PORT'] != '443':
                url += ':' + environ['SERVER_PORT']
        else:
            if environ['SERVER_PORT'] != '80':
                url += ':' + environ['SERVER_PORT']

    url += quote(environ.get('SCRIPT_NAME', ''))
    url += quote(environ.get('PATH_INFO', ''))
    if environ.get('QUERY_STRING'):
        url += '?' + environ['QUERY_STRING']
    msg += " URL: %s" % url
    return [msg]
```

Now i call this via CURL with an URL ending with a dot:

```console
curl.exe http://www.example.org/api/v1/collection/person/WithDot.

SCRIPT_PATH: '/api/v1/collection/person/WithDot.', PATH_INFO: '/api/v1/collection/person/WithDot' URL: http://www.example.org/api/v1/collection/person/WithDot./api/v1/collection/person/WithDot
```

The SCRIPT_PATH looks wrong and the PATH_INFO has the dot stripped away, which is also wrong.
This leads to a wrongly reconstructed URL when using the standard PEP 3333 example code.

It works with the gevent based WSGI server, so i assume it is a bug in mod_wsgi. Might also be deeper, as the path_info is already truncated inside the request_req->path_info from httpd, when entering the wsgi_build_environment().

**Comment by schlenk** [comment]
Probably related to this Apache httpd Bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=20036

**Comment by GrahamDumpleton** [comment]
Probably right and it is that outstanding issue, since mod_wsgi relies on the Apache function for generating the CGI vars. Given the age of it, unlikely to be changed now.

BTW, you have:

```
WSGIScriptAlias / "dispatcher/app.py"
```

It is generally a good idea that the target file path for the handler start with a leading slash. Not even sure what the behaviour will be without it. Whether still works it out relative to root of filesystem, or Apache root.

**Comment by schlenk** [comment]
Yes, the WSGIScriptAlias was a bit simplified. In the actual scenario i encountered it, it was an absolute path.
I added a simple WSGI middleware to fix the values for my app/api by correcting SCRIPT_NAME/PATH_INFO, as i know SCRIPT_NAME is alway empty for my setup.
