### ISSUE TITLE
SetEnvFromScriptAlias

### ISSUE THREAD

**Issue by mikrov** [GrahamDumpleton/mod_wsgi#64]
Hi

This is not a bug but a suggestion. Somtimes I am in the situation where i need to use SetEnv with a more dynamic value than the SetEnv module allows. It would be so cool if you introduced a new directive that can do the same as SetEnv but using the python interpreters already spawned by mod_wsgi by evaluating a script.

This way mod_wsgi can also be used to affect other scripts via the environment variables.

Best regards
Jakob Simon-Gaarde

**Comment by GrahamDumpleton** [comment]
Do you have a specific example?

One can also use mod_rewrite to set per request environ variables and it provides much more powerful ways of dynamically generating new values or editing existing ones and mod_env.

* http://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_e

Am wary of adding Python hooks because it would add a notable cost to all requests if enabled.

**Comment by mikrov** [comment]
Hi, and thanks for the fast response.

Last time I needed something like this was under development of a dynamic dynamic proxy server. It scans the incomming request for a dev_context cookie and then uses the value to decide which site to proxy to. So in effect you can have multiple sites on the dynamic proxy-server where each site can have several versions which are targeted by the client using the cookies.

To scale we needed to setup an array of proxy-servers each having the exact same setup at all times. Therefore we needed a central setup resource (memcached) with the configurations.

I ended up coding a new module in C that does the memcache communication to determine the proxy target. It set a environment variable and then uses it with mod_rewrite to do the actual proxying. I would have prefered to do the coding in a simple python script executed as a APR_HOOK_FIRST or APR_HOOK_MIDDLE that can set an env var or otherwise affect other modules.
Other reasons that this is a nice feature is:
* Avoiding the need to build my modules for 3-4 different versions of Apache.
* Avoiding to make a hidden seg-fault generating error. It's much easier to make critical errors in C than in Python

I know this might not be a relevant feature for mod_wsgi. But you have the setup -  pool of python interpretters ready to respond, great configuration base etc.

Best Regards
Jakob Simon-Gaarde

**Comment by GrahamDumpleton** [comment]
Have you ever looked at RewriteMap.

http://httpd.apache.org/docs/2.4/rewrite/rewritemap.html#prg

**Comment by mikrov** [comment]
Actually I didn't know of it, and I could definately have used that to solve the problem. But I think the performance factor might be a problem because it has to startup a python interpreter for each request that hits the server.

So for each request there will be the extra overhead of:
  * Loading the interpreter
  * Initializing
  * loading byte-code
  * finalizing

Whereas a preloaded interpreter will with the script already imported would only need to start the code.

Am I not right about that?

**Comment by GrahamDumpleton** [comment]
My understanding is that it creates one instance for life of the parent worker process. That is why the example has a while loop. Each line it receives is for a different request and it returns one line of modified output of the string NULL if if didn't change it.

**Comment by mikrov** [comment]
Ok, I will certainly look in to that - thanks.

**Comment by GrahamDumpleton** [comment]
The other interesting one is:

* http://httpd.apache.org/docs/2.4/rewrite/rewritemap.html#dbd

I previously thought whether there was a sensible way that mod_wsgi could expose Python code as a database provider. If that was possible in a sane way, then technically it could be used in RewriteMap as well to bridge into Python code when using mod_rewrite.

For some applications of mapping to a list of things based on something from a request, one can even use:

* http://httpd.apache.org/docs/2.4/rewrite/rewritemap.html#txt
* http://httpd.apache.org/docs/2.4/rewrite/rewritemap.html#dbm

It will detect when the text based mapping file is changed so will reread it, or simply query the database as needed. Thus you can have something external simply update the mapping file or database as necessary.

I have given this as an example previously of how to dynamically assign WSGI applications to one of a pool of mod_wsgi daemon process groups using a database in this way before.

http://code.google.com/p/modwsgi/wiki/ConfigurationDirectives#WSGIProcessGroup

**Comment by GrahamDumpleton** [comment]
Closing this ticket at this point on basis that Apache provides ways of doing this already.
