### ISSUE TITLE
 DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

### ISSUE THREAD

**Issue by marc1n** [GrahamDumpleton/mod_wsgi#645]
Logging to stderr in Python 3.8 (mod_wsgi 4.6.8) emits warning: "DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats".

I believe the reason is a code in the function `Log_write`: 

https://github.com/GrahamDumpleton/mod_wsgi/blob/217e80b7436035723b80ff02ee349365e8553dfc/src/server/wsgi_logger.c#L330

See box with "Note" here: https://docs.python.org/3.8/c-api/arg.html#strings-and-buffers and https://bugs.python.org/issue36381

Maybe inserting `#define PY_SSIZE_T_CLEAN` before `#include <Python.h>` here:

https://github.com/GrahamDumpleton/mod_wsgi/blob/217e80b7436035723b80ff02ee349365e8553dfc/src/server/wsgi_python.h#L24

will solve the problem?

**Comment by GrahamDumpleton** [comment]
Can you supply an example WSGI application which triggers this as well as explain how you are running/configuring mod_wsgi? On macOS at least, using mod_wsgi-express and printing stuff through stdout/stderr, which should still be routed through that function, doesn't result in any deprecation warnings.

**Comment by GrahamDumpleton** [comment]
Closing, believe this was addressed in 4.8.0.
