### ISSUE TITLE
launching django on Apache using mod_wsgi

### ISSUE THREAD

**Issue by shiviiiiii** [GrahamDumpleton/mod_wsgi#647]
I have 32 bit windows 7, 32 bit wamp installed and python 3.7 on my system.

When i set the environment variable and run the command pip install mod_wsgi, it throws the below error
(andonReasonEntry) C:\Users\Administrator\PycharmProjects\reason_entry_test\andonReasonEntry>pip install mod_wsgi
Collecting mod_wsgi
  Using cached mod_wsgi-4.7.1.tar.gz (498 kB)
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-
install-00n8asi1\\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-00n8asi1\\mod-wsgi_5205f2d4fa774a67bec86
d1179366b3e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"')
)' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-a2r1q2b9'
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-00n8asi1\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\
  Complete output (33 lines):
  c:\users\administrator\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\mod_wsgi
  copying src\__init__.py -> build\lib.win32-3.7\mod_wsgi
  creating build\lib.win32-3.7\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win32-3.7\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win32-3.7\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win32-3.7\mod_wsgi\server
  creating build\lib.win32-3.7\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management
  creating build\lib.win32-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
  creating build\lib.win32-3.7\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win32-3.7\mod_wsgi\docs
  creating build\lib.win32-3.7\mod_wsgi\images
  copying images\__init__.py -> build\lib.win32-3.7\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win32-3.7\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\src
  creating build\temp.win32-3.7\Release\src\server
  C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/wamp/bin/apache/apache2.4.39/include
 -Ic:\users\administrator\envs\andonreasonentry\include -Ic:\users\administrator\appdata\local\programs\python\python37-32\include -Ic:\users\administrator\appdata\local\programs\python
\python37-32\include "-IC:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win32-3.7\Release\src/server\m
od_wsgi.obj
  mod_wsgi.c
  C:\Users\Administrator\AppData\Local\Temp\pip-install-00n8asi1\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws
2tcpip.h': No such file or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
    Running setup.py install for mod-wsgi ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pi
p-install-00n8asi1\\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-00n8asi1\\mod-wsgi_5205f2d4fa774a67bec
86d1179366b3e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"
'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-66swvca4\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\administrat
or\envs\andonreasonentry\include\site\python3.7\mod-wsgi'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-00n8asi1\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\
    Complete output (33 lines):
    c:\users\administrator\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\mod_wsgi
    copying src\__init__.py -> build\lib.win32-3.7\mod_wsgi
    creating build\lib.win32-3.7\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win32-3.7\mod_wsgi\server
    copying src\server\environ.py -> build\lib.win32-3.7\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win32-3.7\mod_wsgi\server
    creating build\lib.win32-3.7\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management
    creating build\lib.win32-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
    creating build\lib.win32-3.7\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win32-3.7\mod_wsgi\docs
    creating build\lib.win32-3.7\mod_wsgi\images
    copying images\__init__.py -> build\lib.win32-3.7\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win32-3.7\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\src
    creating build\temp.win32-3.7\Release\src\server
    C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/wamp/bin/apache/apache2.4.39/inclu
de -Ic:\users\administrator\envs\andonreasonentry\include -Ic:\users\administrator\appdata\local\programs\python\python37-32\include -Ic:\users\administrator\appdata\local\programs\pyth
on\python37-32\include "-IC:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win32-3.7\Release\src/server
\mod_wsgi.obj
    mod_wsgi.c
    C:\Users\Administrator\AppData\Local\Temp\pip-install-00n8asi1\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: '
ws2tcpip.h': No such file or directory
    error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A
DMINI~1\\AppData\\Local\\Temp\\pip-install-00n8asi1\\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-00n8a
si1\\mod-wsgi_5205f2d4fa774a67bec86d1179366b3e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp
ile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-66swvca4\install-record.txt' --single-version-externally-managed --compile --inst
all-headers 'c:\users\administrator\envs\andonreasonentry\include\site\python3.7\mod-wsgi' Check the logs for full command output.
WARNING: You are using pip version 20.3.4; however, version 21.0 is available.
You should consider upgrading via the 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe -m pip install --upgrade pip' command.

(andonReasonEntry) C:\Users\Administrator\PycharmProjects\reason_entry_test\andonReasonEntry>c:\users\administrator\envs\andonreasonentry\scripts\python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\administrator\envs\andonreasonentry\lib\site-packages (20.3.4)
Collecting pip
  Using cached pip-21.0-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.4
    Uninstalling pip-20.3.4:
      Successfully uninstalled pip-20.3.4
Successfully installed pip-21.0

(andonReasonEntry) C:\Users\Administrator\PycharmProjects\reason_entry_test\andonReasonEntry>pip install mod_wsgi
Collecting mod_wsgi
  Using cached mod_wsgi-4.7.1.tar.gz (498 kB)
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-
install-lv3u6jfb\\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-lv3u6jfb\\mod-wsgi_c15042e2a6a44b508dc1a
bca302b2bd4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"')
)' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-aj0q01te'
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-lv3u6jfb\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\
  Complete output (33 lines):
  c:\users\administrator\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\mod_wsgi
  copying src\__init__.py -> build\lib.win32-3.7\mod_wsgi
  creating build\lib.win32-3.7\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win32-3.7\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win32-3.7\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win32-3.7\mod_wsgi\server
  creating build\lib.win32-3.7\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management
  creating build\lib.win32-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
  creating build\lib.win32-3.7\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win32-3.7\mod_wsgi\docs
  creating build\lib.win32-3.7\mod_wsgi\images
  copying images\__init__.py -> build\lib.win32-3.7\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win32-3.7\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\src
  creating build\temp.win32-3.7\Release\src\server
  C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/wamp/bin/apache/apache2.4.39/include
 -Ic:\users\administrator\envs\andonreasonentry\include -Ic:\users\administrator\appdata\local\programs\python\python37-32\include -Ic:\users\administrator\appdata\local\programs\python
\python37-32\include "-IC:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win32-3.7\Release\src/server\m
od_wsgi.obj
  mod_wsgi.c
  C:\Users\Administrator\AppData\Local\Temp\pip-install-lv3u6jfb\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws
2tcpip.h': No such file or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
    Running setup.py install for mod-wsgi ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pi
p-install-lv3u6jfb\\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-lv3u6jfb\\mod-wsgi_c15042e2a6a44b508dc
1abca302b2bd4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"
'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-uxio0v1s\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\administrat
or\envs\andonreasonentry\include\site\python3.7\mod-wsgi'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-lv3u6jfb\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\
    Complete output (33 lines):
    c:\users\administrator\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\mod_wsgi
    copying src\__init__.py -> build\lib.win32-3.7\mod_wsgi
    creating build\lib.win32-3.7\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win32-3.7\mod_wsgi\server
    copying src\server\environ.py -> build\lib.win32-3.7\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win32-3.7\mod_wsgi\server
    creating build\lib.win32-3.7\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management
    creating build\lib.win32-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
    creating build\lib.win32-3.7\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win32-3.7\mod_wsgi\docs
    creating build\lib.win32-3.7\mod_wsgi\images
    copying images\__init__.py -> build\lib.win32-3.7\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win32-3.7\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\src
    creating build\temp.win32-3.7\Release\src\server
    C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/wamp/bin/apache/apache2.4.39/inclu
de -Ic:\users\administrator\envs\andonreasonentry\include -Ic:\users\administrator\appdata\local\programs\python\python37-32\include -Ic:\users\administrator\appdata\local\programs\pyth
on\python37-32\include "-IC:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win32-3.7\Release\src/server
\mod_wsgi.obj
    mod_wsgi.c
    C:\Users\Administrator\AppData\Local\Temp\pip-install-lv3u6jfb\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: '
ws2tcpip.h': No such file or directory
    error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A
DMINI~1\\AppData\\Local\\Temp\\pip-install-lv3u6jfb\\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-lv3u6
jfb\\mod-wsgi_c15042e2a6a44b508dc1abca302b2bd4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp
ile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-uxio0v1s\install-record.txt' --single-version-externally-managed --compile --inst
all-headers 'c:\users\administrator\envs\andonreasonentry\include\site\python3.7\mod-wsgi' Check the logs for full command output

Can anyone help me out?

**Comment by GrahamDumpleton** [comment]
See https://github.com/GrahamDumpleton/mod_wsgi/issues/194

Apparently due to missing compiler SDK packages on your Windows system.

You will have to work out what is appropriate compiler package you need to install.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
