### ISSUE TITLE
mod_wsgi unable to install

### ISSUE THREAD

**Issue by shiviiiiii** [GrahamDumpleton/mod_wsgi#648]
I have windows7, python, wamp, VC 2019 all 32 bit, however as i try to install mod_wsgi, i get the following error-

(andonReasonEntry) C:\Users\Administrator\PycharmProjects\reason_entry_test\andonReasonEntry>pip install mod_wsgi 
Collecting mod_wsgi
  Using cached mod_wsgi-4.7.1.tar.gz (498 kB)
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-
install-9a1u24gf\\mod-wsgi_34d1d99276e74746824120a223a8c2a1\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-9a1u24gf\\mod-wsgi_34d1d99276e7474682412
0a223a8c2a1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"')
)' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-j0f_9l5y'
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-9a1u24gf\mod-wsgi_34d1d99276e74746824120a223a8c2a1\
  Complete output (33 lines):
  c:\users\administrator\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\mod_wsgi
  copying src\__init__.py -> build\lib.win32-3.7\mod_wsgi
  creating build\lib.win32-3.7\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win32-3.7\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win32-3.7\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win32-3.7\mod_wsgi\server
  creating build\lib.win32-3.7\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management
  creating build\lib.win32-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
  creating build\lib.win32-3.7\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win32-3.7\mod_wsgi\docs
  creating build\lib.win32-3.7\mod_wsgi\images
  copying images\__init__.py -> build\lib.win32-3.7\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win32-3.7\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\src
  creating build\temp.win32-3.7\Release\src\server
  C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/wamp/bin/apache/apache2.4.39/include
 -Ic:\users\administrator\envs\andonreasonentry\include -Ic:\users\administrator\appdata\local\programs\python\python37-32\include -Ic:\users\administrator\appdata\local\programs\python
\python37-32\include "-IC:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win32-3.7\Release\src/server\m
od_wsgi.obj
  mod_wsgi.c
  C:\Users\Administrator\AppData\Local\Temp\pip-install-9a1u24gf\mod-wsgi_34d1d99276e74746824120a223a8c2a1\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws
2tcpip.h': No such file or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
    Running setup.py install for mod-wsgi ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pi
p-install-9a1u24gf\\mod-wsgi_34d1d99276e74746824120a223a8c2a1\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-9a1u24gf\\mod-wsgi_34d1d99276e74746824
120a223a8c2a1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"
'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-vq_p4qzh\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\administrat
or\envs\andonreasonentry\include\site\python3.7\mod-wsgi'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-9a1u24gf\mod-wsgi_34d1d99276e74746824120a223a8c2a1\
    Complete output (33 lines):
    c:\users\administrator\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\mod_wsgi
    copying src\__init__.py -> build\lib.win32-3.7\mod_wsgi
    creating build\lib.win32-3.7\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win32-3.7\mod_wsgi\server
    copying src\server\environ.py -> build\lib.win32-3.7\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win32-3.7\mod_wsgi\server
    creating build\lib.win32-3.7\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management
    creating build\lib.win32-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win32-3.7\mod_wsgi\server\management\commands
    creating build\lib.win32-3.7\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win32-3.7\mod_wsgi\docs
    creating build\lib.win32-3.7\mod_wsgi\images
    copying images\__init__.py -> build\lib.win32-3.7\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win32-3.7\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\src
    creating build\temp.win32-3.7\Release\src\server
    C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:/wamp/bin/apache/apache2.4.39/inclu
de -Ic:\users\administrator\envs\andonreasonentry\include -Ic:\users\administrator\appdata\local\programs\python\python37-32\include -Ic:\users\administrator\appdata\local\programs\pyth
on\python37-32\include "-IC:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win32-3.7\Release\src/server
\mod_wsgi.obj
    mod_wsgi.c
    C:\Users\Administrator\AppData\Local\Temp\pip-install-9a1u24gf\mod-wsgi_34d1d99276e74746824120a223a8c2a1\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: '
ws2tcpip.h': No such file or directory
    error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\envs\andonreasonentry\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A
DMINI~1\\AppData\\Local\\Temp\\pip-install-9a1u24gf\\mod-wsgi_34d1d99276e74746824120a223a8c2a1\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-9a1u2
4gf\\mod-wsgi_34d1d99276e74746824120a223a8c2a1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp
ile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-vq_p4qzh\install-record.txt' --single-version-externally-managed --compile --inst
all-headers 'c:\users\administrator\envs\andonreasonentry\include\site\python3.7\mod-wsgi' Check the logs for full command output.

I also installed SDK compilers for windows 7 from the following link- https://www.microsoft.com/en-in/download/details.aspx?id=8279

Still i get the same error.

**Comment by GrahamDumpleton** [comment]
Please don't create a new issue when you had already created https://github.com/GrahamDumpleton/mod_wsgi/issues/647

All I know is that this is because you are missing some part of the compiler SDK. Suggest you Google for "Cannot open include file: ws2tcpip.h No such file or directory" and find other discussions about it as it is not specific to mod_wsgi.

BTW, also don't use 32 bit Python, ensure you are using 64 bit versions of Python, Apache and the compiler. Your issue may be related to fact you are using 32 bit when 64 bit is recommended.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
