### ISSUE TITLE
URL length issue at apache2.4  mod_wsgi 4.6.5

### ISSUE THREAD

**Issue by ekfo33** [GrahamDumpleton/mod_wsgi#652]
In my process, url payload length is larger than 4K sometimes. Then I found error log "Target WSGI script not found or unable to stat"
(in my browser, 404 error is occurred...)
At payload size 3K has not problem. Is there any solution?

**Comment by GrahamDumpleton** [comment]
You would have to work out exactly what limit you are breaching and then adjust the Apache httpd limit. Eg:

* https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestline

Look at the various Apache ``Limit??`` directives.

In other words, it is an Apache httpd limit and not enforced by mod_wsgi.

**Comment by ekfo33** [comment]
Thanks for your answer,
I check my config, but my apache config is over than 4K. 

```
LimitRequestLine    32760
```

And, I found some same issue  (https://serverfault.com/questions/757364/issues-with-url-length-in-apache-mod-wsgi)
plz another guide.

**Comment by GrahamDumpleton** [comment]
You are going to have to provide more information then. What does the HTTP request line actually look like? What makes it so long, the URL path segments, or the query string? Does the path include repeating slashes (which Apache will collapse/remove)? Are there strange non ASCII characters in the path?

**Comment by GrahamDumpleton** [comment]
Also try with ``develop`` branch of mod_wsgi here on GitHub. It fixes a rare corruption bug with Apache configuration. Sort of doubt it, but is remote outside chance it is related.

**Comment by ekfo33** [comment]
Thanks. I try it at develop branch. 
I develop chart screen, url has hostnames (ex. /A*B*C*.../) I'll check it

**Comment by GrahamDumpleton** [comment]
In general it is unwise to rely on being able to use really long URL paths/query string in the request as you don't know if a server or proxy will accept them. Use a POST with parameters in the body of the request instead.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue.

**Comment by mennucc** [comment]
I am doing some tests; `LimitRequestLine` is not related to this problem; indeed, if I lower it, say, to 128, and I send a long request, I get a specific error; whereas any request with URL longer than 4096 gets a `Forbidden` error, even when `LimitRequestLine` is larger (the default being 8192). I am investigating into this.

**Comment by mennucc** [comment]
short answer: there is a limit of 4096 bytes, hardcoded. Long answer: https://serverfault.com/a/1116122/565047
