### ISSUE TITLE
Python3 mod-wsgi  4.7.1 Django 2.2  Apache/2.4.6 centos 7

### ISSUE THREAD

**Issue by sanjaygunda12** [GrahamDumpleton/mod_wsgi#654]
Facing issue running with mod_wsgi please help me

Current thread 0x00007f58bdda9880 (most recent call first):
[Tue Feb 16 19:16:19.187828 2021] [wsgi:warn] [pid 12809] mod_wsgi (pid=12809): Python home /opt/saas/venv is not accessible. Python interpreter may not be able to be initialized correctly. Verify the supplied path and access permissions on the directory.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f58bdda9880 (most recent call first):
[Tue Feb 16 19:16:19.197486 2021] [wsgi:warn] [pid 12808] mod_wsgi (pid=12808): Python home /opt/saas/venv is not accessible. Python interpreter may not be able to be initialized correctly. Verify the supplied path and access permissions on the directory.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f58bdda9880 (most recent call first):
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f58bdda9880 (most recent call first):
[Tue Feb 16 19:16:20.105577 2021] [core:notice] [pid 11614] AH00052: child pid 12800 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105747 2021] [core:notice] [pid 11614] AH00052: child pid 12801 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105764 2021] [core:notice] [pid 11614] AH00052: child pid 12802 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105777 2021] [core:notice] [pid 11614] AH00052: child pid 12803 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105798 2021] [core:notice] [pid 11614] AH00052: child pid 12804 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105812 2021] [core:notice] [pid 11614] AH00052: child pid 12805 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105824 2021] [core:notice] [pid 11614] AH00052: child pid 12806 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105836 2021] [core:notice] [pid 11614] AH00052: child pid 12807 exit signal Aborted (6)
[Tue Feb 16 19:16:20.105848 2021] [core:notice] [pid 11614] AH00052: child pid 12808 exit signal Aborted (6)
[Tue Feb 16 19:16:20.106422 2021] [core:notice] [pid 11614] AH00052: child pid 12809 exit signal Aborted (6)
[Tue Feb 16 19:16:20.109915 2021] [wsgi:warn] [pid 12810] mod_wsgi (pid=12810): Python home /opt/saas/venv is not accessible. Python interpreter may not be able to be initialized correctly. Verify the supplied path and access permissions on the directory.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f58bdda9880 (most recent call first):
[Tue Feb 16 19:16:20.120230 2021] [wsgi:warn] [pid 12811] mod_wsgi (pid=12811): Python home /opt/saas/venv is not accessible. Python interpreter may not be able to be initialized correctly. Verify the supplied path and access permissions on the directory.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

**httpd CONFIG file**

ServerName SAAS
LoadModule wsgi_module "/usr/lib64/httpd/modules/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/opt/saas/venv"

WSGIDaemonProcess vsn user=vsn group=vsn processes=2 threads=15 display-name=%{GROUP} python-eggs=/opt/saas/system/wsgi/egg-cache python-path=/opt/saas/venv/lib/python3.6/site-packages:/opt/saas/vsn:/opt/saas/vsn/vsn
WSGISocketPrefix /opt/saas/system/wsgi/daemon-sockets
WSGIProcessGroup vsn

#Listen 10.1.212.6:80
<VirtualHost 0.0.0.0:80>

    DocumentRoot /var/www/html
    ServerName vsn

**Comment by GrahamDumpleton** [comment]
The error explains the problem:
