### ISSUE TITLE
Gateway Timeout [mod_wsgi and virtual environment]

### ISSUE THREAD

**Issue by lguariento** [GrahamDumpleton/mod_wsgi#655]
Hello,

I'm using a Python image server ([Loris](https://github.com/loris-imageserver/loris)) deployed on Apache and mod_wsgi. I'm on Oracle Linux 7.9, in a Python 3.6 virtual environment.

This is my configuration.

/etc/httpd/conf.d/loris.conf:

```
ExpiresActive On
ExpiresDefault "access plus 5184000 seconds"

AllowEncodedSlashes On

WSGIDaemonProcess loris user=loris group=loris python-home=/usr/local/python3_venv processes=10 threads=15 maximum-requests=10000
WSGIScriptAlias /loris /var/www/loris/loris.wsgi
WSGIProcessGroup loris
WSGIApplicationGroup %{GLOBAL}
```

/etc/httpd/conf.modules.d/00-wsgi.conf:

```
LoadModule wsgi_module "/usr/local/python3_venv/lib64/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnux-gnu.so
WSGIPythonHome "/usr/local/python3_venv"
```

 /var/www/loris/loris.wsgi :

```
#!/usr/bin/env python
from loris.webapp import create_app
# Uncomment and configure below if you are using virtualenv
import site
site.addsitedir('/usr/local/python3_venv/lib/python3.6/site-packages/')
application = create_app(config_file_path='/usr/local/python3_venv/lib/python3.6/site-packages/Loris-3.2.1-py3.6.egg/loris/data/loris.conf
```
The mod_wsgi has been installed with pip, within the virtual environment, with the same python used for installing the application.

The server correctly returns something (the json metadata), although it times out when rendering images. SELinux is disabled. Is anything else I should check? The Loris developers say that it should work like this. In fact, the server correctly works as expected when launching its own development server (e.g. without mod_wsgi). Could it be a permission issue, i.e. the application running on a different user than apache/root?

The log:

`[wsgi:error] [pid 12958] [client 213.152.186.163:53731] Timeout when reading response headers from daemon process 'loris': /var/www/loris/loris.wsgi`

Any help would be highly appreciated. Thanks.

**Comment by GrahamDumpleton** [comment]
It is hard to tell from the limited information you have given.

I suggest adapting code (will need to make it Python 3 compatible) in:

* https://modwsgi.readthedocs.io/en/master/user-guides/debugging-techniques.html#extracting-python-stack-traces

to extract stack traces as to where the Python code is getting stuck.

One thing to keep in mind is that the working directory of your application isn't guaranteed, so you need to ensure you use absolute paths, or calculate then relative to code base.

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#application-working-directory

This is a common mistake which can cause code run with a local development server to not work with a production WSGI server.

Also, under Apache your application will not have same environment variables as you user. So if your application depends on locally set environment variables, including value of ``PATH``, or ``LD_LIBRARY_PATH``, it may not work.

**Comment by lguariento** [comment]
Thank you, I'll look into it. Once thing that I should have mentioned is that the application calls a [transform() method](https://github.com/loris-imageserver/loris/blob/614e1abc247118e4a5e479563c3c0c8a3dc707d7/loris/transforms.py#L216) which writes some temporary files to /tmp with mkfifo. It seems that these files do not get written, that's why I am thinking of a permission issue (although I don't have permissions errors in the logs). The methods seem to be called correctly, so I don't think it's an issue of mod_wsgi not finding the correct absolute path.

I'll try to get the developers to see help me with those stack traces.

**Comment by lguariento** [comment]
Hello again @GrahamDumpleton, it turns out that it was a configuration error of the Python application, which had nothing to do with mod_wsgi or the Apache configuration. Thank you anyway for your time and for the additional information.
