### ISSUE TITLE
mod_wsgi issue

### ISSUE THREAD

**Issue by HamzaEkram** [GrahamDumpleton/mod_wsgi#657]
Hello sir!
I wanna make backend scripts using flask and wamp as a server. 
At that time what I did:
install mod_wsgi
install mod-wsgi-express module-config
and paste the output of above command into httpd.conf just after LoadModule directory.
also configure vhost for my scripts.
Let me know how can i run scripts on wamp server using mod_wsgi.
how i configure mod_wsgi on wamp apache
please help me this is the very first time on wamp or flask.

**Comment by GrahamDumpleton** [comment]
For Flask see the documentation and tutorials on the Flask web site:

* https://palletsprojects.com/p/flask/

For configuring mod_wsgi the Flask documentation has some details, but also see:

* https://modwsgi.readthedocs.io/en/master/

and specifically start with:

* https://modwsgi.readthedocs.io/en/master/user-guides/quick-configuration-guide.html
* https://modwsgi.readthedocs.io/en/master/user-guides/configuration-guidelines.html
