### ISSUE TITLE
Django application can't startup with openxlpy

### ISSUE THREAD

**Issue by c-rei** [GrahamDumpleton/mod_wsgi#660]
When I import openxlpy  which is a excel tool in my views of django, the application can't startup.
My environments is like below:

httpd-2.4.46-win64-VS16
mod_wsgi-4.7.1-cp38-cp38-win_amd64.whl
python 3.8.8
openxlpy 3.0.7
Django 3.1.7

If I comment out import openxlpy, the application can startup, but I can't read a excel sheet in my application.

Thanks any help.

**Comment by GrahamDumpleton** [comment]
You can try setting:

```
WSGIApplicationGroup %{GLOBAL}
```

which can help when packages are not designed to work with Python sub interpreters correctly,  but it may not help as some Python packages which try and interact with other applications such as Excel, will not work when run within a Windows system service, instead needing some sort of direct access to the desktop environment that you would get when run from a command line.

Beyond that suggestion, would need to see the exact error messages you get.

**Comment by c-rei** [comment]
Thanks a lot.
It worked with your advise, just put one line WSGIApplicationGroup %{GLOBAL} to apache configuration.
