### ISSUE TITLE
src/server/wsgi_apache.h:42:19: fatal error: httpd.h: No such file or directory Makefile:31: recipe for target 'src/server/mod_wsgi.la' failed

### ISSUE THREAD

**Issue by abhishekpadghane** [GrahamDumpleton/mod_wsgi#661]
Hello sir, i am installing mod_wsgi in my instance which is Ubuntu 16.04.7 LTS. I have followed your installation instruction for mod wsgi. after doing `./configure --with-apxs=/usr/bin/apxs --with-python=/root/testApp/venv/bin/python3.7` and then `sudo make install` i am getting <br>
/usr/bin/apxs -c -I/usr/include/python3.7m -DNDEBUG  -Wc,-g -Wc,-O2  src/server/mod_wsgi.c src/server/wsgi_*.c -L/usr/lib -L/usr/lib/python3.7/config-3.7m  -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm
/usr/share/apr-1.0/build/libtool  --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -DBUILD_DATETIME='"2020-08-12T21:35:50"' -Wdate-time -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -g -O2 -I/usr/include/python3.7m -DNDEBUG  -c -o src/server/mod_wsgi.lo src/server/mod_wsgi.c && touch src/server/mod_wsgi.slo
libtool: compile:  x86_64-linux-gnu-gcc -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DBUILD_DATETIME=\"2020-08-12T21:35:50\" -Wdate-time -D_FORTIFY_SOURCE=2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2 -I/usr/include/apr-1.0 -I/usr/include/apr-1.0 -I/usr/include -g -O2 -I/usr/include/python3.7m -DNDEBUG -c src/server/mod_wsgi.c  -fPIC -DPIC -o src/server/.libs/mod_wsgi.o
In file included from src/server/mod_wsgi.c:21:0:
src/server/wsgi_apache.h:42:19: fatal error: httpd.h: No such file or directory
compilation terminated.
apxs:Error: Command failed with rc=65536
.
Makefile:31: recipe for target 'src/server/mod_wsgi.la' failed
make: *** [src/server/mod_wsgi.la] Error 1

<br>
I have installed it on other instances and my django deployment works fine on other system but on this system i am getting this error. Please let me know what i am doing wrong or its my instance problem.

**Comment by GrahamDumpleton** [comment]
The error generally indicates that you don't have the ``dev`` package for Apache ``httpd`` installed. Yet, usually if that is the case the ``apxs`` script wouldn't exist either.

Try uninstalling the ``dev`` package for Apache ``httpd`` and reinstalling it.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue.
