### ISSUE TITLE
Unable to connect to the website after runmodwsgi

### ISSUE THREAD

**Issue by JianDk** [GrahamDumpleton/mod_wsgi#662]
I am trying to deploy my django project in Ubuntu. I did the below steps without experiencing issues, but upon entering my webpage from my browser I received a ERR_CONNECTION_REFUSED error from my browser. In my settings.py I have added mod_wsgi.server to my installed apps

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mod_wsgi.server',
]

```

I then executed the below command

```
python manage.py runmodwsgi \
> --server-root /etc/wsgi-port-80 \
> --user www-data --group www-data \
> --port 80 --setup-only
Successfully ran command.
Server URL         : http://localhost/
Server Root        : /etc/wsgi-port-80
Server Conf        : /etc/wsgi-port-80/httpd.conf
Error Log File     : /etc/wsgi-port-80/error_log (warn)
Rewrite Rules      : /etc/wsgi-port-80/rewrite.conf
Environ Variables  : /etc/wsgi-port-80/envvars
Control Script     : /etc/wsgi-port-80/apachectl
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8

```

I then executed the below command

```
sudo /etc/wsgi-port-80/apachectl start
/etc/wsgi-port-80/apachectl: line 63: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

```

Then from a browser I entered https://www.mywebsite.dk and got the connection refused error. It is my first time deploying a django project and therefore I am very inexperienced. Thanks in advance for providing me with some inputs and comments.

**Comment by GrahamDumpleton** [comment]
Where are you hosting it? Is that hostname registered in DNS and mapping to the IP address for the host where you are hosting it?

**Comment by JianDk** [comment]
I am hosting it on Linode 139.162.163.35 . It is registered in DNS and the site is www.dimsum.dk <http://www.dimsum.dk/> . Actually when I serve the site using 

sudo service apache2 restart everything works fine.

**Comment by GrahamDumpleton** [comment]
Because mod_wsgi-express was setup to use port 80, then the system Apache can't be running at the same time. Was the "apache2" system service still running at the time?

**Comment by JianDk** [comment]
I just double checked the procedure and yes, I started by stopping apache2 with

sudo service apache2 stop

Then I ran

```
(env) jianwu@django-hdserver:~/HD_website/website$ python manage.py runmodwsgi \
> --server-root /etc/wsgi-port-80 \
> --user www-data --group www-data \
> --port 80 --setup-only
Successfully ran command.
Server URL         : http://localhost/
Server Root        : /etc/wsgi-port-80
Server Conf        : /etc/wsgi-port-80/httpd.conf
Error Log File     : /etc/wsgi-port-80/error_log (warn)
Rewrite Rules      : /etc/wsgi-port-80/rewrite.conf
Environ Variables  : /etc/wsgi-port-80/envvars
Control Script     : /etc/wsgi-port-80/apachectl
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : en_US.UTF-8
(env) jianwu@django-hdserver:~/HD_website/website$ sudo /etc/wsgi-port-80/apachectl start
/etc/wsgi-port-80/apachectl: line 63: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

```

Now if I try www.dimsum.dk I receive err_connection_refused

**Comment by GrahamDumpleton** [comment]
That host name actually works for me.

DNS shows:

```
$ dig www.dimsum.dk

; <<>> DiG 9.10.6 <<>> www.dimsum.dk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1762
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.dimsum.dk.			IN	A

;; ANSWER SECTION:
www.dimsum.dk.		3530	IN	A	139.162.163.35

;; Query time: 47 msec
;; SERVER: 192.168.178.2#53(192.168.178.2)
;; WHEN: Thu Mar 18 09:23:14 AEDT 2021
;; MSG SIZE  rcvd: 58
```

How long ago was the DNS set up for that IP address. It is possible that your DNS system has old IP cached.

**Comment by JianDk** [comment]
The DNS was set up for approximately 3 days ago for the first time, and I have only used the present IP address. Could it have something to do with my SSL certificate?

**Comment by GrahamDumpleton** [comment]
Your configuration is not setup to use SSL for mod_wsgi-express, so no.

What do you get for:

```
curl -H Host:www.dimsum.dk 139.162.163.35
```

This bypasses DNS and uses the IP address, telling it the host in the header, although mod_wsgi-express isn't actually going to care about the host being requested with how you have it configured.

**Comment by JianDk** [comment]
Sorry you are right it was the cache. I just cleared my cache in the Google Chrome Browser and it now works as a charm. Thanks so much. I am so happy that I came accross your video [presentation](https://www.youtube.com/watch?v=CPz0s1CQsTE&t=6s) that pointed me towards this direction
