### ISSUE TITLE
Passing wsgi_server_time_buckets into wsgi_record_time_in_buckets as the wrong type

### ISSUE THREAD

**Issue by pjb1008** [GrahamDumpleton/mod_wsgi#665]
Hi,

The  following code generates a compiler warning:
wsgi_record_time_in_buckets(&wsgi_queue_time_buckets, ...)

To be compatible, the argument should be just plain wsgi_queue_time_buckets, or the equivalent &wsgi_queue_time_buckets[0]

Peter

**Comment by pjb1008** [comment]
[buckets.patch.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/6182230/buckets.patch.txt)

**Comment by GrahamDumpleton** [comment]
Fixed in ``develop`` branch.

**Comment by GrahamDumpleton** [comment]
And thanks for the heads up.
