### ISSUE TITLE
Can't host my wsgi application on other places than /

### ISSUE THREAD

**Issue by Wissperwind** [GrahamDumpleton/mod_wsgi#670]
Hi,
I host django with mod_wsgi on windows.
If I configure:
`WSGIScriptAlias / C:/[...]/wsgi.py`
I can access my api on the root. So for example host:port/login works.

But if I configure:
`WSGIScriptAlias /backend C:/[...]/wsgi.py`
I can't access my api on /backend. So host:port/backend/login does not work.

**Comment by GrahamDumpleton** [comment]
What web framework are you using?

A framework like Django doesn't automatically prefix the login URL with the mount point prefix and you have to explicitly tell it the full URL path.

**Comment by Wissperwind** [comment]
Like mentioned in the first post, I use django as backend framework.
From djangos point of view, login is in /login. With no prefix.
I can host it with apache with no prefix. So it is accessible under /login.

But my website should be accessible under the root /.
Django should be accessible under /backend.
So I configurered:
`WSGIScriptAlias /backend C:/[...]/wsgi.py`
to make a request to backend/login point to the django /login endpoint.

But that does not work.

**Comment by Wissperwind** [comment]
So for example if I use a cherrypy webserver to host django:
`cherrypy.tree.graft(getWsgi(), "/backend")`
The django abblocation is hosted under /backend, and a call of something after /backend is forwarded to the django urls.py.

**Comment by Wissperwind** [comment]
Further testing and I can describe the problem a bit narrower.
If I have nothing configured to /.
It works, I can acces /backend/login.
But if I configure my JavaScript page to /, I can't access /backend anymore.
It seems, like apache still tries to finde some backend folder in the folder I configured under / instead of noticing that there is a special configuration for /backend that leeds to my django.

**Comment by GrahamDumpleton** [comment]
How are you configuring ``/`` in Apache? Are you using ``Alias``?

Usually you wouldn't use ``Alias`` to configure ``/`` and instead stick files in the document root directory.

If for some reason you must use ``Alias`` with ``/``, you will need to configure mod_wsgi using ``Alias`` as well.

* https://modwsgi.readthedocs.io/en/master/user-guides/configuration-guidelines.html#the-apache-alias-directive

The ``Alias`` directory for ``/backend`` then must come before that for ``Alias`` for ``/`` else ``Alias`` for ``/`` will always take precedence and the WSGI application will never get any requests.

This doesn't eliminate the fact that ``LOGIN_URL`` in Django will need to be set with value ``/backend/login`` explicitly as Django will not add the mount point of the application in front of ``LOGIN_URL``, it requires you do it explicitly.

**Comment by Wissperwind** [comment]
So in the doku you linked to they say:
`Alias /wsgi/ /usr/local/wsgi/scripts/`
But that is not correct?
In my case I needed to add wsgi.py at the end.
so:
Alias /wsgi/ /usr/local/wsgi/scripts/wsgi.py

Than it tries to execute my python script.
But I had an issue that is already known as I found:
https://github.com/django/asgiref/issues/143
You also participated there.

With WSGIScriptAlias I added "application-group=%{GLOBAL}" at the end of the line and my code was working.
I can't do that if I use Alias. If I add "application-group=%{GLOBAL}" at the end of the alias line, apache did not start.

But withou "application-group=%{GLOBAL}" I get the bug described in the asgiref issue.

Do you have a suggestion what to do?

**Comment by GrahamDumpleton** [comment]
Use ``WSGIApplicationGroup`` directive.

* https://modwsgi.readthedocs.io/en/master/user-guides/configuration-guidelines.html#defining-application-groups

**Comment by Wissperwind** [comment]
Ok, I tried.
My configuration:
```
<Directory {path to folder that contains wsgi.py}>
  WSGIApplicationGroup %{GLOBAL}
  
  Options ExecCGI

  SetHandler wsgi-script

  Allow from all
  Require all granted
</Directory>
```

But if I comment the line  ` WSGIApplicationGroup %{GLOBAL}` or not, the error is:
`ValueError: set_wakeup_fd only works in main thread of the main interpreter\r`

**Comment by GrahamDumpleton** [comment]
Add:

```
WSGIImportScript C:/[...]/wsgi.py application-group=%{GLOBAL}
```

This will force the script to be preloaded on process start using the main thread.

**Comment by Wissperwind** [comment]
That changed something. But it is still not working.
If I add it, the error changes to 
```
File "C:\\ProgramName\\pythonEnvironmentWithAllStuff\\lib\\site-packages\\pkg_resources\\extern\\__init__.py", line 58, in create_module\r
return self.load_module(spec.name)\r
File "C:\\ProgramName\\pythonEnvironmentWithAllStuff\\lib\\site-packages\\pkg_resources\\extern\\__init__.py", line 43, in load_module\r
	__import__(extant)\r
File "C:\\ProgramName\\pythonEnvironmentWithAllStuff\\lib\\site-packages\\pkg_resources\\_vendor\\appdirs.py", line 560, in <module>\r
  import win32com.shell\r
File "C:\\ProgramName\\pythonEnvironmentWithAllStuff\\lib\\site-packages\\win32com\\__init__.py", line 6, in <module>\r
  import pythoncom\r
File "C:\\ProgramName\\pythonEnvironmentWithAllStuff\\lib\\site-packages\\pythoncom.py", line 2, in <module>\r
  import pywintypes\r
File "C:\\ProgramName\\pythonEnvironmentWithAllStuff\\lib\\site-packages\\win32\\lib\\pywintypes.py", line 105, in <module>\r
  __import_pywin32_system_module__("pywintypes", globals())\r
File "C:\\ProgramName\\pythonEnvironmentWithAllStuff\\lib\\site-packages\\win32\\lib\\pywintypes.py", line 99, in __import_pywin32_system_module__\r
    assert sys.modules[modname] is not old_mod\r
AssertionError\r
```
If I use `WSGIScriptAlias /backend C:/.../wsgi.py application-group=%{GLOBAL}` it is still working. So in general, the wsgi application works.

**Comment by GrahamDumpleton** [comment]
That directive should result in the same effect as having added ``application-group=%{GLOBAL}`` to ``WSGIScriptAlias``. That is, they both trigger pre-loading of the WSGI script file in the main thread. Was the file path given to each the same in each case?

So right now am not sure. Try Googling for that error. I do recollect see it coming up before but don't remember the reason off hand.

**Comment by Wissperwind** [comment]
The order is correct?

```
WSGIImportScript C:/[...]/wsgi.py application-group=%{GLOBAL}
Alias /backend C:/.../wsgi.py
<Directory {path to folder that contains wsgi.py}>
```

**Comment by GrahamDumpleton** [comment]
Doesn't matter.

Can you stop obfuscating the paths and show the exact values so can confirm what you are using?

You are using the same value for path for ``wsgi.py`` in both ``WSGIImportScript`` and ``Alias`` right?

Also, this appears to be a problem with ``pywin32`` module. As I mentioned, do a Google search for:

```
assert sys.modules[modname] is not old_mod pywin32 mod_wsgi
```

You need to stop the ``pywin32`` module being loaded somehow as its module reloader causes problems.

**Comment by Wissperwind** [comment]
Ok, there are workarounds for this problem.
I used this one:
https://stackoverflow.com/questions/9479239/running-two-django-apps-on-apache-with-mod-auth-sspi-and-mod-wsgi/10928148#10928148

Here is my full apache config:
```
LoadFile "c:/python39/python39.dll"
LoadModule wsgi_module "c:/python39/lib/site-packages/mod_wsgi/server/mod_wsgi.cp39-win_amd64.pyd"
#WSGIPythonHome "c:/python39"


#website path
WSGIPythonPath C:/My_Installation/My/psbp/resource/server/bpServer3;C:/My_Installation/My/psbp/resource/lib

WSGIPassAuthorization On

#path to virtual environment with all the packages
WSGIPythonHome C:/My_Installation/pythonEnvironmentWithAllStuff



#path to wsgi.py file #the first “/ “ indicates the root url
WSGIImportScript C:/My_Installation/My/psbp/resource/server/bpServer3/bpServer3/wsgi.py application-group=%{GLOBAL}
Alias /backend C:/My_Installation/My/psbp/resource/server/bpServer3/bpServer3/wsgi.py

#WSGIScriptAlias /backend C:/My_Installation/My/psbp/resource/server/bpServer3/bpServer3/wsgi.py application-group=%{GLOBAL}



#directory of website
#<Directory "C:/My_Installation/My/psbp/resource/server/bpServer3/bpServer3/">
#    <Files wsgi.py>
#        Allow from all
#	Require all granted
#    </Files>
#</Directory>


<Directory C:/My_Installation/My/psbp/resource/server/bpServer3/bpServer3/>
#  WSGIApplicationGroup %{GLOBAL}
  
  Options ExecCGI

  SetHandler wsgi-script

  Allow from all
  Require all granted
</Directory>


<Directory "C:/My_Installation/My/psbp/resource/server/bpServer3/static/">
	Require all granted
	Allow from all
</Directory>
Alias /static "C:/My_Installation/My/psbp/resource/server/bpServer3/static/"


<Directory "C:/My_Installation/My/psbp/resource/server/bpServer3/web/">
	Allow from all
	Require all granted
</Directory>
Alias / "C:/My_Installation/My/psbp/resource/server/bpServer3/web/"
```

Now it is working. But it is strange that different errors occour if I set application-group=%{GLOBAL} in different ways.

And I noticed like I thought before:
If you config Django under /backend. For Django /backend looks like /.
So If I configer my Django under /backend, and I configured login in django under /login, I can access login under /backend/login.

**Comment by Wissperwind** [comment]
Thanks for your support!

**Comment by GrahamDumpleton** [comment]
Yes you can access the login as ``/backend/login`` as that is where the view handler is, but if you rely on any part of Django to redirect you to the login page, eg., admin pages, it will redirect to path specified by ``LOGIN_URL`` setting, which will be missing the mount prefix.

**Comment by Wissperwind** [comment]
Ah, ok, that was your point. In my case, I use Django only to serve an api.

**Comment by GrahamDumpleton** [comment]
I'll presume all is good now and will close this issue then.
