### ISSUE TITLE
Truncated or oversized response headers received from daemon process starting with a certain dataset/problem size

### ISSUE THREAD

**Issue by bresait** [GrahamDumpleton/mod_wsgi#671]
Hello,  
I am running a Flask application on an Apache 2 server.
The application runs some optimization code with Pyomo/CBC. 
* When trying a full-size optimization (over ~100,000 variables), the app fails with the error "Truncated or oversized response headers received from daemon process 'MyAppName'" followed by "Attach interpreter ''" and process="MyAppName", application=''): Loading Python script file '/var/www/MyAppName/xxx.wsgi'. I have LogLevel info in my configuration.
* When halving the number of variables, all other things remaining equal, everything works without any error.
* So it looks like I really am having oversized response headers. Could there be a way to make things work with the larger optimization problem, for instance by increasing the tolerated size of response headers?
* Locally, all optimizations run fine.
I would be grateful for any insight.

**Comment by GrahamDumpleton** [comment]
Truncated headers means the process crashed. In other words you are more likely running out of memory and the process is crashing. If you look closely in main Apache error log (not virtual host), you should see a message about segmentation fault if this is the case. With log level info, you should also see messages about the daemon process being restarted.

**Comment by bresait** [comment]
Hello Graham,
Thank you so much for your quick answer! 
I think my virtual host error log is the same as the main Apache error log (/var/log/apache2/error.log) as I have ErrorLog ${APACHE_LOG_DIR}/error.log in my VirtualHost configuration. I cannot see anything about a segmentation fault there, but indeed it looks like the process crashes and the daemon process then restarts:

```
AH00493: SIGUSR1 received.  Doing graceful restart
mod_wsgi (pid=841249): Shutdown requested 'MyAppName'.
Truncated or oversized response headers received from daemon process 'MyAppName': /var/www/MyAppName/MyAppName.wsgi
apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Apache/2.4.41 (Ubuntu) mod_wsgi/4.6.8 Python/3.8 configured -- resuming normal operations
AH00094: Command line: '/usr/sbin/apache2'
mod_wsgi (pid=843849): Attach interpreter ''.
mod_wsgi (pid=843849, process='MyAppName', application=''): Loading Python script file '/var/www/MyAppName/APG_WP.wsgi'.
```

**Comment by GrahamDumpleton** [comment]
You removed time stamps so is hard to know time line, but the message:

```
SIGUSR1 received.  Doing graceful restart
```

indicates that something external to Apache told it to restart, which can cause the daemon process to be killed off.

This can happen if the system process which rotates log files decides to tell Apache to restart so it can swap to a new log file.

Is this happening all the time, or only certain times during the day?

**Comment by bresait** [comment]
Hello Graham,
Again thank you very much for your help!
In terms of time line, in the previous instance, everything is happening in a 3 second window, one minute after starting to translate the optimization model:
```
[Mon May 03 12:51:20.043272 2021] creating instance of optimization model # (this is printed from the code)
[Mon May 03 12:52:03.637921 2021] AH00493: SIGUSR1 received.  Doing graceful restart
[Mon May 03 12:52:03.645062 2021] mod_wsgi (pid=841249): Shutdown requested 'MyAppName'.
[Mon May 03 12:52:06.712851 2021] Truncated or oversized response headers received from daemon process 'MyAppName': /var/www/MyAppName/MyAppName.wsgi
apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Mon May 03 12:52:06.734293 2021] Apache/2.4.41 (Ubuntu) mod_wsgi/4.6.8 Python/3.8 configured -- resuming normal operations
[Mon May 03 12:52:06.734325 2021] AH00094: Command line: '/usr/sbin/apache2'
[Mon May 03 12:52:06.785826 2021] mod_wsgi (pid=843849): Attach interpreter ''.
[Mon May 03 12:52:06.788148 2021] mod_wsgi (pid=843849, process='MyAppName', application=''): Loading Python script file '/var/www/MyAppName/MyAppName.wsgi'.
```
The error does not seem to depend on the time of day, but only on the problem size. For the large problem size, it happens every time I try, sometimes at the same point in the program as above, sometimes a bit later.
In these other instances, it happens a bit later in the code, about 5 minutes after the solver is started (which is about the time it takes the solver to solve this larger problem)
```
[Mon May 03 11:28:20.179298 2021] solver selected
[Mon May 03 11:34:06.195352 2021] Truncated or oversized response headers received from daemon process 'MyAppName': /var/www/MyAppName/MyAppName.wsgi
[Mon May 03 11:34:07.024624 2021] mod_wsgi (pid=835506): Attach interpreter ''.
[Mon May 03 11:34:07.029025 2021] mod_wsgi (pid=835506, process='MyAppName', application=''): Loading Python script file '/var/www/MyAppName/MyAppName.wsgi'.
```
I understand having an optimization run 5 minutes in this setup is probably a bad idea, and this should be handled in a separate process...

**Comment by GrahamDumpleton** [comment]
What are the options to ``WSGIDaemonProcess`` you are using? Do you have ``request-timeout`` set?

It is also possibly the Linux OOM process killer telling Apache to restart.

* https://docs.memset.com/other/linux-s-oom-process-killer
* https://rakeshjain-devops.medium.com/linux-out-of-memory-killer-31e477a45759

But then it shouldn't be a SIGUSR1 signal if it is that.

Does the message about SIGUSR1 appear every time you do it?

**Comment by bresait** [comment]
Hello Graham,
Thank you for your help.
My options are:
```
WSGIDaemonProcess MyAppName
WSGIScriptAlias / /var/www/MyAppName/MyAppName.wsgi process-group=MyAppName application-group=%{GLOBAL}
WSGIApplicationGroup %{GLOBAL}
<Directory MyAppName>
    WSGIProcessGroup MyAppName
    WSGIApplicationGroup %{GLOBAL}
    Order deny,allow
    Allow from all
</Directory>
```
I have `Timeout 600` in apache2.conf, but `request-timeout` is not set for the WSGIDaemonProcess. 

Indeed, the message about SIGUSR1 does not appear every time together with the error. So it could be the Linux OOM process killer.

**Comment by GrahamDumpleton** [comment]
For this SIGUSR1 case, how often is Apache as a whole being restarted due to configuration changes, or is the setup pretty well locked down and doesn't change.

**Comment by bresait** [comment]
Hello Graham,
Now you are asking, it looks like the SIGUSR1 case is actually due to my restarting Apache when trying configuration changes. Without configuration changes, the error log is only as follows:
```
[Mon May 03 11:28:20.179298 2021] solver selected
[Mon May 03 11:34:06.195352 2021] Truncated or oversized response headers received from daemon process 'MyAppName': /var/www/MyAppName/MyAppName.wsgi
[Mon May 03 11:34:07.024624 2021] mod_wsgi (pid=835506): Attach interpreter ''.
[Mon May 03 11:34:07.029025 2021] mod_wsgi (pid=835506, process='MyAppName', application=''): Loading Python script file '/var/www/MyAppName/MyAppName.wsgi'.
```

**Comment by GrahamDumpleton** [comment]
Are there no other messages before that?

I would expect to see other messages from mod_wsgi being logged at info level indicating that it had noticed the daemon process going missing and it needing to start a new one.

So can you provide further back in the log file before that point?

**Comment by bresait** [comment]
Hello Graham,
I added LogLevel info to the upper level of the .conf file, as it was in the <VirtualHost *:80> section earlier.
I get the following error log:
```
[Wed May 05 13:25:41.203055 2021] [wsgi:error] [pid 1129713:tid 140198906812160] creating instance of optimization model
[Wed May 05 13:27:11.484020 2021] [wsgi:error] [pid 1129713:tid 140198906812160] instance created
[Wed May 05 13:27:11.770861 2021] [wsgi:error] [pid 1129713:tid 140198906812160] solver selected
[Wed May 05 13:32:50.920676 2021] [wsgi:error] [pid 1129715:tid 140198998370048] Truncated or oversized response headers received from daemon process 'MyAppName': /var/www/MyAppName/MyAppName.wsgi
[Wed May 05 13:32:51.486859 2021] [wsgi:info] [pid 915:tid 140199247014976] mod_wsgi (pid=1129713): Process 'MyAppName' has died, deregister and restart it.
[Wed May 05 13:32:51.489533 2021] [wsgi:info] [pid 915:tid 140199247014976] mod_wsgi (pid=1129713): Process 'MyAppName' terminated by signal 9
[Wed May 05 13:32:51.490149 2021] [wsgi:info] [pid 915:tid 140199247014976] mod_wsgi (pid=1129713): Process 'MyAppName' has been deregistered and will no longer be monitored.
[Wed May 05 13:32:51.494579 2021] [wsgi:info] [pid 1130456:tid 140199247014976] mod_wsgi (pid=1130456): Starting process 'MyAppName' with uid=33, gid=33 and threads=15.
[Wed May 05 13:32:51.575146 2021] [wsgi:info] [pid 1130456:tid 140199247014976] mod_wsgi (pid=1130456): Initializing Python.
[Wed May 05 13:32:51.665395 2021] [wsgi:info] [pid 1130456:tid 140199247014976] mod_wsgi (pid=1130456): Attach interpreter ''.
[Wed May 05 13:32:51.669049 2021] [wsgi:info] [pid 1130456:tid 140199247014976] mod_wsgi (pid=1130456, process='MyAppName', application=''): Loading Python script file '/var/www/MyAppName/MyAppName.wsgi'.
```
so nothing before the _Truncated or oversized response headers_ error, as far as I can see, but a bit more info after it.

**Comment by GrahamDumpleton** [comment]
The line:

```
[Wed May 05 13:32:51.489533 2021] [wsgi:info] [pid 915:tid 140199247014976] mod_wsgi (pid=1129713): Process 'MyAppName' terminated by signal 9
```

suggests it was most likely the OOM killer as that is the signal it will send.

Maybe you should monitor how much memory the processes are using leading up to it being killed.

Your Python program may be inefficient on memory use and using a very large amount for whatever calculation you are running.

**Comment by bresait** [comment]
Hello Graham,
OK, thank you for the information! I will now close the issue and look into memory use.
Thank you so much for the patient troubleshooting! And sorry it took me so long to supply the relevant information.
