### ISSUE TITLE
PLATFORM being set to Win32 rather than Win64 when running mod_wsgi setup.py install

### ISSUE THREAD

**Issue by aegonzalez** [GrahamDumpleton/mod_wsgi#672]
Environment:
- Windows 2012 R2 Standard 64bit
- VS2019 toolset
- Apache24 from Apache Lounge or Apache Haus (VS16, VS15, and VS14 toolset)
- mod_wsgi source from develop branch.

The errors causing the installation to fail have been reported in other issues. It deals with link.exe complaining of unresolved symbols like __imp__apr_time_now@():
-----
    build\lib.win32-3.9\mod_wsgi\server\mod_wsgi.cp39-win_amd64.pyd : fatal error LNK1120: 227 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\stX86\\x86\\link.exe' failed with exit code 1120
------
In #issue460, the required libraries (.lib) were all there but for some reason the linker still was unable to find the symbols. The suggestion was to seek help in the Apache forums.

It was also suggested in other similar issues that the problem may be due to mixing 32-bit and 64-bit files. I leaning towards this as the issue too because I'm seeing os.h in Apache and pyconfig.h in python have their PLATFORM #define symbol set to Win32 or win32.

Is there a way to set the bitness when building mod_wsgi or how does mod_wsgi decide on the bitness?

**Comment by GrahamDumpleton** [comment]
You have to download and install the 64 bit versions of Python and Apache. Most likely you downloaded and installed the 32 bit version of Python. So is based on what you installed.

**Comment by aegonzalez** [comment]
I started again by spinning up a basic AWS/EC2 Windows 2019 Datacenter server x64 bit. I then installed the following:
- 64-bit python 3.9.5 -- (python CLI shows MSC v.1928 64 bit (AMD64)
- 64-bit Apache Lounge VS16 (i.e. httpd-2.4.47-win64-VS16.zip) under c:\Apache24\Apache24
- VS build tools from https://visualstudio.microsoft.com/visual-cpp-build-tools/
I then opened a powershell VS2019 developer shell window.
I set environment variable MOD_WSGI_APACHE_ROOTDIR to c:\Apache24\Apache24.
Ran python -m pip install mod_wsgi
I got the same errors as before. The compiler (cl.exe) and linker (link.exe) are originating from the 32 bit paths of the VS build tools: c:\program files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86\cl.exe and link.exe.
I think the path should be ...bin\Hostx64\x64\...

I can provide you access to the ec2 instance if that would be helpful. Thank you.

**Comment by GrahamDumpleton** [comment]
You can't use backslashes in ``MOD_WSGI_APACHE_ROOTDIR``. Needs to be:

```
MOD_WSGI_APACHE_ROOTDIR="c:/Apache24/Apache24"
```

Ensure that is what you did.

**Comment by aegonzalez** [comment]
Good point. I changed to forward slashes and also tried switching to a 64-bit powershell window. Same unresolved symbol errors.

I spun up another ec2 64-bit windows instance. This time I loaded the 32 bit python and apache versions and the same VS2019 build tools. This time mod_wsgi built without errors. 
My goal is to build a 64-bit version of mod_wsgi.

**Comment by aegonzalez** [comment]
Got it working. The powershell developer window for the VS2019 build tools would point to the 32 bit tools like link.exe or cl.exe. 
Once I switched to the x64 NativeTools Command Prompt, I was able to build the correct mod_wsgi module. 
One thing to note is that the module for mod_wsgi is not mod_wsgi.so but something mod_wsgi*.pyd.
