### ISSUE TITLE
Did anything happen to sub-interpreters in Python 3.9?

### ISSUE THREAD

**Issue by dvarrazzo** [GrahamDumpleton/mod_wsgi#674]
Hello,

a bug open in psycopg2 (https://github.com/psycopg/psycopg2/issues/1269) leads me to think that something happened in sub-interpreter in Python 3.9. I would like to know if you are aware of anything and if there are known workarounds.

The problem with psycopg2 and sub-interpreters comes from the lack of re-initialisation of the C extensions. the class Decimal is (was?) created new for each sub-interpreter, because is (was?) a pure Python class. In the past this lead to confusion in psycopg2, because the adapters map (pretty much a dict mapping types to a conversion function) would have been only registered for the main interpreter's `Decimal` class. In other sub-interpreters `type(obj)` would have returned an unknown class, leading to the "can't adapt Decimal" error.

This was fixed a long time ago, [re-registering the Decimal at every import of the Python part of the module](https://github.com/psycopg/psycopg2/blob/73969ba3e757373a73b4c163af338c6efbab5bef/lib/__init__.py#L73-L79). Since then we had no more reports of [the old issue](https://github.com/psycopg/psycopg2/issues/52).

Are you aware of anything changed in Python 3.9 for which this safeguard might have stopped working?

Thank you very much.

**Comment by GrahamDumpleton** [comment]
Commented on other issue.
