### ISSUE TITLE
WSGIScriptAlias and on the fly created apps

### ISSUE THREAD

**Issue by platipusica** [GrahamDumpleton/mod_wsgi#677]
Hi there, 

first, thank you very much for your hard work. 

I am struggling to understand how to configure on the fly created Apps and WSGI on Apache for static files.
Using WSGIScriptAliasMatch /([^/]+) /var/www/html/projects/$1/wsgi.py

It works well with on the fly sub project creation for new Apps. The issue is subproject/static folder and downloads from it. Browser will show "Not Found" and address:

http://SERVER_NAME/static/name_of_the_file_App_is_sending.

However, this is not correct address, it should be http://SERVER_NAME/subproject/static/name_of_the_file_App_is_sending 

and I can access this file if type the address in the browser!

If I change to  WSGIScriptAlias / /var/www/html/projects/subproject/wsgi.py
everything works for that particular subproject. But I have a number of subprojects, so can't do that.

Thoughts please.

Thanks

**Comment by platipusica** [comment]
Here is Apache conf example (DEV):

```
<VirtualHost *:80>
WSGIApplicationGroup %{GLOBAL}
WSGIDaemonProcess  demo2  lang='en_US.UTF-8' locale='en_US.UTF-8' user=www-data group=www-data processes=1 threads=5
WSGIProcessGroup demo2
#WSGIScriptAlias / /var/www/jam/jam/access/wsgi.py
WSGIScriptAliasMatch /([^/]+) /var/www/jam/jam/$1/wsgi.py

<Directory "/var/www/jam/jam/.*">
        Options Indexes FollowSymlinks MultiViews
        AllowOverride All

        Options +ExecCGI
        SetHandler wsgi-script
        AddHandler wsgi-script .py
        Order allow,deny
        Allow from all
        Require all granted

       <Files wsgi.py>
            Order allow,deny
            Allow from all
        </Files>

</Directory>
</VirtualHost>
```
Accessing http://../access will work. Also /access2,..../accessN will work. However, the App sending file from /var/www/jam/jam/access/ or any other accessN will not work, due to:
```
[Fri May 14 13:14:47.294857 2021] [wsgi:error] [pid 13931:tid 140447258121984] [client 10.0.2.2:25524] Target WSGI script not found or unable to stat: /var/www/jam/jam/static, referer: http://127.0.0.1:8889/access2/builder.html
``` 

See the "unable to stat"? This does not exist.

**Comment by GrahamDumpleton** [comment]
If I understand correctly you are going to have to tell your web framework generating static file page references what the prefix should be. For example in Django you would need to set ``STATIC_URL`` setting yourself in each project to be of form ``/subproject/static``.

If you are hardwiring ``/static`` based paths in HTML pages, you will need to add the prefix dynamically somehow, which is what a framework like Django does for you, using ``STATIC_URL`` value as prefix.

**Comment by platipusica** [comment]
Hi Graham,
The issue only exist when WSGI script runs under subfolder, ie:

```
[Tue May 25 12:57:38.093922 2021] [wsgi:error] [pid 37952] [client 108.162.249.83:60854] Target WSGI script not found or unable to stat: /var/www/html/conv/upload/static, referer: https://conv.xxx.com/a47e0d2a9408da85d23e00ffde78036a1/builder.html
```
The above is showing /var/www/html/conv/upload/static, but the folder is /var/www/html/conv/a47e0d2a9408da85d23e00ffde78036a1/upload/static, hence the path is incorrect. And is comes from WSGIScriptAliasMatch.

So if I dump the Apache headers with environ:
'SCRIPT_FILENAME': '/var/www/html/conv/upload/a47e0d2a9408da85d23e00ffde78036a1/wsgi.py'
 'CONTEXT_DOCUMENT_ROOT': '/var/www/html/conv/upload'
 'REQUEST_URI': '/a47e0d2a9408da85d23e00ffde78036a1/', 'SCRIPT_NAME': '/a47e0d2a9408da85d23e00ffde78036a1', 'PATH_INFO': '/', 'PATH_TRANSLATED': '/var/www/html/conv/upload/',
etc...

that the SCRIPT_FILENAME is correct path.

this is how the App processes file to be sent:
```
        os.rename(to_unicode(file_name, 'utf-8'), os.path.join(to_unicode(result_path, 'utf-8'), to_unicode(result_file, 'utf-8')))
        if url:
            result = '%s/static/%s' % (url, result_file)
        else:
            result = result_file
    finally:
        if os.path.exists(task_file):
            os.remove(task_file)
        if os.path.exists(file_name):
            os.remove(file_name)
    return result
```

Thoughts?

**Comment by GrahamDumpleton** [comment]
Missed that you were using ``WSGIScriptAliasMatch``.

You probably need to use:

```
WSGIScriptAliasMatch /([^/]+) /var/www/jam/jam/$1/wsgi.py/$1
```

else ``SCRIPT_NAME`` passed in will be ``/`` rather than ``/subproject``.

In other words, you need to substitute on right hand side after WSGI script file path, the part from the left side that represents the mount point.

**Comment by platipusica** [comment]
Tried, no luck.
'SCRIPT_NAME': '/a47e0d2a9408da85d23e00ffde78036a1' <- this is the folder, so accessing the app is simple as https://xxx.com/a47e0d2a9408da85d23e00ffde78036a1

To make it easier:
```
/var/www/html/conv/upload/a47e0d2a9408da85d23e00ffde78036a1# tree
.
├── __pycache__
│   ├── server.cpython-38.pyc
│   └── wsgi.cpython-38.pyc
├── a47e0d2a9408da85d23e00ffde78036a.sqlite3
├── a47e0d2a9408da85d23e00ffde78036a1.sqlite3
├── admin.sqlite
├── css
│   └── project.css
├── index.html
├── js
│   └── Test.js
├── langs.sqlite
├── locks
│   ├── $buildID_5_47
│   ├── $build_checking.lock
│   ├── $code_updating.lock
│   ├── $langs.lock
│   └── $save_build_id.lock
├── reports
├── server.py
├── static
│   ├── Test_1.0.0_6.0.27_2021-05-25_12-57-37.zip
│   ├── internal
│   │   └── Test_1.0.0_6.0.27_2021-05-25_12-56-39.zip
│   └── reports
├── templates.html
└── wsgi.py
```
The Apache is failing to send the Test_1.0.0_6.0.27_2021-05-25_12-57-37.zip:
```
[Tue May 25 13:46:05.277797 2021] [wsgi:error] [pid 38350] [client 172.69.33.138:16826] Target WSGI script not found or unable to stat: /var/www/html/conv/upload/static, referer: https://conv.xxx.com/a47e0d2a9408da85d23e00ffde78036a1/builder.html
```
And browser showing:
https://conv.xxx.com/static/Test_1.0.0_6.0.27_2021-05-25_13-46-03.zip

and that does not exist!  But this one does if I type it in the browser:

https://conv.xxx.com/a47e0d2a9408da85d23e00ffde78036a1/static/Test_1.0.0_6.0.27_2021-05-25_13-46-03.zip

Sorry to bug you with this, I just have no luck with Google...

**Comment by GrahamDumpleton** [comment]
Without seeing all the code I still really don't understand what you are trying to do.

If your intent is to have Apache serve up static files from ``/.../static/...``, you are missing the Apache configuration to do that.

As it is, ``WSGIScriptAliasMatch`` will suck up everything and static file requests with never get to Apache static file handler.

You are going to need an ``Alias`` or ``AliasMatch`` directive before ``WSGIScriptAliasMatch`` to match for static file access.

```
AliasMatch /([^/]+)/static /var/www/jam/jam/$1/static
WSGIScriptAliasMatch /([^/]+) /var/www/jam/jam/$1/wsgi.py
```

**Comment by platipusica** [comment]
Thanks
I did try all combinations of AliasMatch previously, including this one. Alias too, but I cant use Alias anyway due to unknown directory path. 

This is the process:
- the User uploads data, data is processed
- **unique folder** is created with wsgi.py App inside that folder to serve the processed data
- the App works under **/uniquefolder** as expected. All good. Except when the User wants to Export metadata which is created in **static** (or any other folder by that matter which is in below code).

The metadata is exported from App by clicking Export button, which fires server_export_task. File:

https://github.com/jam-py/jam-py/blob/master/jam/adm_server.py

line 1198.

Hope you might have a minute or two to review the code. But, I do not think it's a code. It might be  WSGIScriptAliasMatch which, I think, has issues.

 It is really simple:
 pip install jam.py

create a folder, cd in it and run jam-project.py
Serve with WSGIScriptAliasMatch and see what happens when Export is clicked from http://.../builder.html

Cheers

**Comment by platipusica** [comment]
Hi @GrahamDumpleton 

pls hold, will talk again with the developer.

Thx

**Comment by platipusica** [comment]
Ok, 

here is my test on local VM, with:

AliasMatch /([^/]+)/static /var/www/jam/jam/$1/static
WSGIScriptAliasMatch /([^/]+) /var/www/jam/jam/$1/wsgi.py

If I access the App with wget or curl:
```
wget http://127.0.0.1/exp1
--2021-05-26 15:55:34--  http://127.0.0.1/exp1
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 308 PERMANENT REDIRECT
Location: http://127.0.0.1/exp1/ [following]
--2021-05-26 15:55:34--  http://127.0.0.1/exp1/
Reusing existing connection to 127.0.0.1:80.
HTTP request sent, awaiting response... 200 OK
Length: 8708 (8.5K) [text/html]
Saving to: ‘exp1’

exp1                                 100%[====================================================================>]   8.50K  --.-KB/s    in 0s      

2021-05-26 15:55:34 (22.0 MB/s) - ‘exp1’ saved [8708/8708]
```
This will create exp1 file with the content of index.html
Curl:
```
curl -L http://127.0.0.1/exp1
```
This will display content of index.html

Now fun:
```
curl -L http://127.0.0.1/exp1/static
curl: (47) Maximum (50) redirects followed
```
BUT:
```
curl -L http://127.0.0.1/exp1/dfgfdgdfgfabnG
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

Does this means static folder has issues?

**Comment by GrahamDumpleton** [comment]
For a start, should be:

```
AliasMatch ^/([^/]+)/static/(.*)$ /var/www/jam/jam/$1/static/$2
```

Quoting the Apache docs:

One subtle difference between Alias and AliasMatch is that Alias will automatically copy any additional part of the URI, past the part that matched, onto the end of the file path on the right side, while AliasMatch will not. This means that in almost all cases, you will want the regular expression to match the entire request URI from beginning to end, and to use substitution on the right side.

In other words, just changing Alias to AliasMatch will not have the same effect. At a minimum, you need to add ^ to the beginning of the regular expression and add (.*)$ to the end, and add $1 to the end of the replacement.

For example, suppose you want to replace this with AliasMatch:

```
Alias "/image/" "/ftp/pub/image/"
```

This is NOT equivalent - don't do this! This will send all requests that have /image/ anywhere in them to /ftp/pub/image/:

```
AliasMatch "/image/" "/ftp/pub/image/"
```

This is what you need to get the same effect:

```
AliasMatch "^/image/(.*)$" "/ftp/pub/image/$1"
```

**Comment by platipusica** [comment]
Absolutely!
I'm with you, and tried this too. 
Tried every possible combination that I know off :( As mentioned, not using Alias at all.

The App works superb on document root with no /subfolder. Zip export works, everything works.
To test this, here:
https://jampy.pythonanywhere.com/builder.html

Click on Export.

Same App created on local VM as 127.0.0.1/jampy will not work. And I have PROD set up in the same way.
What I do not understand is why Apache WSGI is processing this file instead of sending it to the client. If is in static folder it should NOT hit wsgi, but it's hitting it as I see it with:
wget http://127.0.0.1/exp1/static

and than this loops to http://127.0.0.1/exp1/static/wsgi.py/wsgi.py/wsgi..... adding more and more **wsgi.py**, at the end finishes with exceeding redirections....

Many thanks for helping.

**Comment by platipusica** [comment]
Scratch that last paragraph, this was due to DirectoryMatch...
Still, 127.0.0.1/jampy is a no go.

**Comment by GrahamDumpleton** [comment]
Not writing the AliasMatch as I last had is why you would have gotten redirect loop. What was the actual configuration you changed to? Did the behaviour of the redirect loop change at all?

**Comment by platipusica** [comment]
I think loop was due to DirectoryMatch, not AliasMatch or wsgiscriptaliasmatch.

New config is below. Commented out is what DOES work for obviously single App called "access" (http://127.0.0.1/). If I try now any other App, including "access" (http://127.0.0.1/access), Export won't work. 


```
<VirtualHost *:80>
WSGIDaemonProcess demo2 lang='en_US.UTF-8' locale='en_US.UTF-8' python-home=/var/www/auth/jam-dev python-path=/var/www/auth/jam-dev user=www-data group=www-data threads=5
WSGIProcessGroup demo2

#Alias /static/ /var/www/jam/jam/access/static/
AliasMatch ^/([^/]+)/static/(.*)$ /var/www/jam/jam/$1/static/$2

#WSGIScriptAlias / /var/www/jam/jam/access/wsgi.py
WSGIScriptAliasMatch /([^/]+) /var/www/jam/jam/$1/wsgi.py

#<Directory /var/www/jam/jam/access>
<DirectoryMatch ^/var/www/jam/jam/([^/]+)>

<Files wsgi.py>
Require all granted
</Files>
#</Directory>
</DirectoryMatch>

#<Directory /var/www/jam/jam/access/static>
<DirectoryMatch ^/var/www/jam/jam/([^/]+)/static>

Require all granted
#</Directory>
</DirectoryMatch>

</VirtualHost>
```

The zip is created in static/internal folder and I can use wget to get it from the VM console:
```
wget http://127.0.0.1/exp1/static/internal/t_1.0.0_5.4.111_2021-05-26_18-22-09.zip
--2021-05-26 20:26:38--  http://127.0.0.1/exp1/static/internal/t_1.0.0_5.4.111_2021-05-26_18-22-09.zip
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6791 (6.6K) [application/zip]
Saving to: ‘t_1.0.0_5.4.111_2021-05-26_18-22-09.zip.1’

t_1.0.0_5.4.111_2021-05-26_18-22-09. 100%[====================================================================>]   6.63K  --.-KB/s    in 0s      

2021-05-26 20:26:38 (113 MB/s) - ‘t_1.0.0_5.4.111_2021-05-26_18-22-09.zip.1’ saved [6791/6791]
```

So I think the Apache IS serving it when called straight (the **exp1** is the App). WSGI App IS serving it when on ROOT.
There is no even need for this when running on ROOT:
Alias /static/ /var/www/jam/jam/access/static/

The Mother of all questions, why is it failing to serve when not on ROOT.

**Comment by GrahamDumpleton** [comment]
The AliasMatch was causing the redirect loop. I know as I tested with prior configuration and same issue. It went away when made change I indicated.

It may also be necessary to change WSGIScriptAliasMatch in the same way, but also accomodate the training path, so have:

```
WSGIScriptAliasMatch ^/([^/]+)/(.*)$ /var/www/jam/jam/$1/wsgi.py/$2
```

Getting alias matching using regexes in Apache working is painful and usually never recommend using them.

One problem you may find you have with them with how done is that you will run out of memory because every single wsgi.py file will see a new sub interpreter created (I think). In other words, if you have lots of unique wsgi.py files in the end, there will be a sub interpreter for every one. So the way you are doing it is not really a good idea and you should really design it so you only have one WSGI application that can handle requests for all.

**Comment by platipusica** [comment]
Ok, 

cheers for your help!
Kind Regards
