### ISSUE TITLE
Compiling mod_wsgi with pypy

### ISSUE THREAD

**Issue by robertosussex** [GrahamDumpleton/mod_wsgi#679]
Hi,

I was wondering whether it is feasible to have mod_wsgi compiled with pypy in light of the fact that python2 is near its EOL. Not sure Python3 would be an option as the server moin moin which I am upgrading is based on Python2
Any advice?
Many thanks

Dr Roberto Scipioni
MPS Research computing Support Engineer
Mathematical and Physical Sciences School,
University of Sussex, Falmer, Brighton
UK

**Comment by robertosussex** [comment]
I started the compilation in different ways.
1) Compiling directly the source code
2) Using pypy setup.py build
in every case it complains about (kernels files??) not found



[root@phys-webvm mod_wsgi-4.8.0]# pypy setup.py build

WARNING: The Python installation you are using does not appear to have
been installed with a shared library, or in the case of MacOS X, as a
framework. Where these are not present, the compilation of mod_wsgi may
fail, or if it does succeed, will result in extra memory being used by
all processes at run time as a result of the static library needing to
be loaded in its entirety to every process. It is highly recommended
that you reinstall the Python installation being used from source code,
supplying the '--enable-shared' option to the 'configure' script when
configuring the source code prior to building and installing it.

/usr/lib64/pypy-5.0.1/lib-python/2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running build
running build_py
copying src/server/apxs_config.py -> build/lib.linux-x86_64-2.7/mod_wsgi/server
running build_ext
building 'mod_wsgi.server.mod_wsgi-py27' extension
cc -O2 -fPIC -Wimplicit -I/usr/include/httpd -I/usr/lib64/pypy-5.0.1/include -c src/server/mod_wsgi.c -o build/temp.linux-x86_64-2.7/src/server/mod_wsgi.o -I/usr/include/httpd -I. -I/usr/include/apr-1 -DLINUX -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -pthread -I/usr/include/apr-1 -I/usr/include/apr-1
In file included from src/server/mod_wsgi.c:22:0:
src/server/wsgi_python.h:46:18: fatal error: node.h: No such file or directory
 #include "node.h"
                  ^
compilation terminated.
error: command 'cc' failed with exit status 1


================

Any idea what is wrong?
Cheers
Roberto

**Comment by GrahamDumpleton** [comment]
The mod_wsgi module relies on the C API of CPython. It isn't going to be possible.

**Comment by robertosussex** [comment]
I did manage to compile mod_wsgi from source using pypy. 

./configure --prefix=/tmp/rs558/mod_wsgi-4.8.0 --with-python=pypy  CPPFLAGS=-I/tmp/rs558/pypy2.7-v7.3.4-linux64/include

In the end though I had to link it to libpython2.7.so in order to create an object that could be loaded by the Apache server.

**My question is then:**
When in a future not too far away python2 is reaching the EOL any idea how to have a module **mod_wsgi** that comes from Python2 so that it can be used in python2 software only like Moin Moin ?

Any idea?

Thanks
R.

**Comment by GrahamDumpleton** [comment]
But when loaded did it actually run and could you confirm that it was pypy executing code. I would still be suspicious that would work properly as there would be too much dependency on CPython specific features such as sub interpreters.

To me it seems that trying to cobble up something with pypy would be more support effort that just compiling CPython 2 from source code yourself even when Linux distributions don't ship a binary.

Anyway, I don't understand the last question. I wasn't intending to consciously remove support for Python 2 in mod_wsgi as it is probably more dangerous to try and remove the support as it would be too easy to inadvertently break it for Python 3.

Since most security issues going forward are likely going to be with SSL libraries, I would use a front end web server such as nginx to handle SSL termination and then proxy to a mod_wsgi instance behind. That would isolate you from the main point of concern.

**Comment by robertosussex** [comment]
Let me summarise what the issue is:

1) I need to migrate a **MoinMoin** server that uses **Python2.X** to an updated version. 

2) I have run some tests with an upgraded **MoinMoin** and it works fine, however, it does not look like the Moin Moin software is going to be moved to Python3 any time soon and as you probably know Python2 is coming to end of support sometime this year.

3) If This is the case how can we make sure that the **MoinMoin/Apache/Python2** Web server will be fit for purpose security wise?

4) It was suggested then to use **pypy** to install/use **MoinMoin** since they have confirmed they will never remove support in **pypy** for python2 installation/usage as the code itself is written in Python2 or related languages. I have managed to install **MoinMoin** using **pypy**.

5) Moin Moin uses the module **mod_wsgi**  and for instance in my web server **.conf** file you have lines like
 **WSGIScriptAlias / "/srv/testmoin/share/moin/server/moin.wsgi"**
so using the Apache module is essential.

If I were able to get a **mod_wsgi** compiled with **pypy** then using it would make Python2 EOL irrelevant.

I sounds as though it is not possible.
Any comments are welcome
Cheers

Roberto

**Comment by robertosussex** [comment]
I suppose then the best approach would be to have an instance of mod_wsgi compiled with possibly an old version of python and to keep that behind a proxy, for the rest seems to be fine
Best
R.
