### ISSUE TITLE
WSGI using Python 2.7 interpreter

### ISSUE THREAD

**Issue by IAmThe2ndHuman** [GrahamDumpleton/mod_wsgi#681]
When I try to run my Apache2 WSGI Flask server on my VPS I get a ton of errors. Here's my Apache error.log file:

![image](https://user-images.githubusercontent.com/63452869/118703804-2b024c80-b81f-11eb-98a6-c8bcfeac8c97.png)

There are a lot of syntax and import errors. For example, the interpreter seems to consider f-strings to be syntax errors, also there's a million `No module named site` errors. I have Python 2.7 3.8 and 3.9 installed on the server and I'm wondering if there is a way to make the server use 3.8 (or 3.9) instead of what appears to be 2.7. 

Thanks!

**Comment by GrahamDumpleton** [comment]
The mod_wsgi module is compiled for a specific version of Python. Yours would appear to be compiled for Python 2.7. You cannot force it to use a Python virtual environment for a different Python version. The only thing you can do is uninstall mod_wsgi compiled for Python 2.7 and install a copy which is compiled for the Python version you do want to use.

Where did the mod_wsgi package you installed come from? If it is provided by the operating system, see if the operating system supplies a package for it which is compiled for the correct Python version you want instead.
