### ISSUE TITLE
wsgi file cannot import module psycopg2.

### ISSUE THREAD

**Issue by JavierBrRuiz** [GrahamDumpleton/mod_wsgi#684]
I am trying to use mod_wsgi to serve a flask app through apache2 (ubuntu 18.04).
I use a pycharm virtual environment but can't help with apache crashing every time I try to access localhost:5000.
VirtualHost and wsgi files seems to be well configured since the apache error logs shows that apache is accessing to the flask script.

The error shown is the next, which seems to be related to [this stackoverflow question](https://stackoverflow.com/questions/61006302/modulenotfounderror-no-module-named-psycopg2-psycopg) But followed the solution steps with mod_wsgi version 4.7.1 and 4.7.8 and is not working, the same ImportError keeps appearing.

Here is my wsgi file:
```
import sys
sys.path.insert(0, "/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web")

from flask_web import app as application
```

My virtualhost conf file:
```
Listen 5000
<VirtualHost *:5000>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        LogLevel debug

        WSGIScriptAlias / /mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi
        WSGIDaemonProcess flask_web home=/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web python-path=/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web:/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/venv/Lib/site-packages threads=5 user=javierbrenes group=javierbrenes
        WSGIProcessGroup flask_web
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On
        WSGIChunkedRequest On
        ErrorLog ${APACHE_LOG_DIR}/error-5000.log
        CustomLog ${APACHE_LOG_DIR}/access-5000.log combined

        <Directory /mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web>
            <IfVersion >= 2.4>
                Require all granted
            </IfVersion>
            <IfVersion < 2.4>
                Order allow,deny
                Allow from all
            </IfVersion>
        </Directory>
</VirtualHost>
```

And the apache error log:
```
[Fri May 28 13:30:35.174873 2021] [wsgi:info] [pid 11219:tid 139717045730240] mod_wsgi (pid=11219): Adding '/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/venv/Lib/site-packages' to path.
[Fri May 28 13:30:35.211601 2021] [wsgi:debug] [pid 11219:tid 139716931917568] src/server/mod_wsgi.c(9118): mod_wsgi (pid=11219): Started thread 0 in daemon process 'flask_web'.
[Fri May 28 13:30:35.211679 2021] [wsgi:debug] [pid 11219:tid 139716923524864] src/server/mod_wsgi.c(9118): mod_wsgi (pid=11219): Started thread 1 in daemon process 'flask_web'.
[Fri May 28 13:30:35.211718 2021] [wsgi:debug] [pid 11219:tid 139716915132160] src/server/mod_wsgi.c(9118): mod_wsgi (pid=11219): Started thread 2 in daemon process 'flask_web'.
[Fri May 28 13:30:35.211804 2021] [wsgi:debug] [pid 11219:tid 139716906739456] src/server/mod_wsgi.c(9118): mod_wsgi (pid=11219): Started thread 3 in daemon process 'flask_web'.
[Fri May 28 13:30:35.211855 2021] [wsgi:debug] [pid 11219:tid 139716898338560] src/server/mod_wsgi.c(9118): mod_wsgi (pid=11219): Started thread 4 in daemon process 'flask_web'.
[Fri May 28 13:30:39.999385 2021] [authz_core:debug] [pid 11221:tid 139716940310272] mod_authz_core.c(809): [client ::1:56900] AH01626: authorization result of Require all granted: granted
[Fri May 28 13:30:39.999493 2021] [authz_core:debug] [pid 11221:tid 139716940310272] mod_authz_core.c(809): [client ::1:56900] AH01626: authorization result of <RequireAny>: granted
[Fri May 28 13:30:40.005064 2021] [authz_core:debug] [pid 11221:tid 139716940310272] mod_authz_core.c(809): [client ::1:56900] AH01626: authorization result of Require all granted: granted
[Fri May 28 13:30:40.005110 2021] [authz_core:debug] [pid 11221:tid 139716940310272] mod_authz_core.c(809): [client ::1:56900] AH01626: authorization result of <RequireAny>: granted
[Fri May 28 13:30:40.007135 2021] [wsgi:info] [pid 11219:tid 139716931917568] [remote ::1:56900] mod_wsgi (pid=11219, process='flask_web', application=''): Loading Python script file '/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi'.
[Fri May 28 13:30:45.724440 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900] mod_wsgi (pid=11219): Failed to exec Python script file '/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi'.
[Fri May 28 13:30:45.724599 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900] mod_wsgi (pid=11219): Exception occurred processing WSGI script '/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi'.
[Fri May 28 13:30:45.748472 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900] Traceback (most recent call last):
[Fri May 28 13:30:45.748544 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900]   File "/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi", line 4, in <module>
[Fri May 28 13:30:45.748554 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900]     from flask_web import app as application
[Fri May 28 13:30:45.748563 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900]   File "/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/flask_web.py", line 8, in <module>
[Fri May 28 13:30:45.748569 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900]     import psycopg2
[Fri May 28 13:30:45.748576 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900]   File "/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/venv/Lib/site-packages/psycopg2/__init__.py", line 51, in <module>
[Fri May 28 13:30:45.748582 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900]     from psycopg2._psycopg import (                     # noqa
[Fri May 28 13:30:45.748614 2021] [wsgi:error] [pid 11219:tid 139716931917568] [remote ::1:56900] ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

I would appreciate some help, thanks!

**Comment by GrahamDumpleton** [comment]
For a  start, read:

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

and change your configuration to reference the Python virtual environment correctly.

Doing it by adding ``site-packages`` to Python module search path is not recommended.

As to the error, it indicates psycopg2 is not installed correctly and is missing the C extension component.

Double check psycopg2 installation, uninstalling it and re-installing it from source code Python package rather than Python wheel package, which can often have problems when your system configuration doesn't exactly match what the binary wheel was compiled for.

**Comment by JavierBrRuiz** [comment]
Also, while reading the doc virtual environment reference I see another potential mistake in my configuration:

"When using a Python virtual environment with mod_wsgi, it is very important that it has been created using the same Python installation that mod_wsgi was originally compiled for. It is not possible to use a Python virtual environment to force mod_wsgi to use a different Python version, or even a different Python installation."

My pycharm virtual environment uses python 3.9 but I do not know the python version which compiles mod_wsgi 4.8.0
Could there be a python version mismatch here, causing problems?

Thank you for the reply.

**Comment by GrahamDumpleton** [comment]
It could possibly cause it.

When a virtual environment is referenced correctly a mismatch becomes pretty evident from the outset as it would crash and fail immediately Apache starts up.

By adding ``site-packages`` only to the Python module search path problems would only occur when attempting to first import a Python package which had a C extension. How that manifests will depend on a bit on how any pure Python wrapper around the C extension handles the error.

In this case psycopg2 is saying the C extensions cannot be found. If there was a mismatch I would have expected a different sort of error due to C API for the C extension not matching, but then C ABI guarantees these days between some Python versions muddy that.

Anyway, certainly worth looking at at the problem.

To work out what version of Python mod_wsgi is compiled for, test with simple WSGI hello world as shown in:

* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use

Ensure you remove the reference to any Python virtual environment when you do that.

**Comment by JavierBrRuiz** [comment]
I created a new virtual environment with same python version as mod_wsgi compilation (python 3.6)
and changed python-path to python-home to reference the venv root folder (not site-packages) but now instead of getting psycopg2 moduleNotFound, I am getting flask moduleNotFound, which seems to be an additional problem since the import flask line is prior to import psycopg2. 
The only thing left to do is to run the psycopg2 manual installation but there is a problem with my venv configuration that I'd like to solve first.

Apache virtual host conf:
```
Listen 5000
<VirtualHost *:5000>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        LogLevel debug

        WSGIScriptAlias / /mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi
        WSGIDaemonProcess flask_web python-home=/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/venvs home=/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web threads=5 user=javierbrenes group=javierbrenes
        WSGIProcessGroup flask_web
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On
        WSGIChunkedRequest On
        ErrorLog ${APACHE_LOG_DIR}/error-5000.log
        CustomLog ${APACHE_LOG_DIR}/access-5000.log combined

        <Directory /mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web>
            <IfVersion >= 2.4>
                Require all granted
            </IfVersion>
            <IfVersion < 2.4>
                Order allow,deny
                Allow from all
            </IfVersion>
        </Directory>
</VirtualHost>
```


Apache error log
```
[Mon May 31 10:54:54.224887 2021] [wsgi:info] [pid 1219:tid 139759162526656] mod_wsgi (pid=1219): Attach interpreter ''.
[Mon May 31 10:54:54.238187 2021] [wsgi:debug] [pid 1219:tid 139759048713984] src/server/mod_wsgi.c(9118): mod_wsgi (pid=1219): Started thread 0 in daemon process 'flask_web'.
[Mon May 31 10:54:54.238272 2021] [wsgi:debug] [pid 1219:tid 139759040321280] src/server/mod_wsgi.c(9118): mod_wsgi (pid=1219): Started thread 1 in daemon process 'flask_web'.
[Mon May 31 10:54:54.238321 2021] [wsgi:debug] [pid 1219:tid 139759031928576] src/server/mod_wsgi.c(9118): mod_wsgi (pid=1219): Started thread 2 in daemon process 'flask_web'.
[Mon May 31 10:54:54.238392 2021] [wsgi:debug] [pid 1219:tid 139759023535872] src/server/mod_wsgi.c(9118): mod_wsgi (pid=1219): Started thread 3 in daemon process 'flask_web'.
[Mon May 31 10:54:54.238414 2021] [wsgi:debug] [pid 1219:tid 139759015134976] src/server/mod_wsgi.c(9118): mod_wsgi (pid=1219): Started thread 4 in daemon process 'flask_web'.
[Mon May 31 10:55:02.911516 2021] [authz_core:debug] [pid 1221:tid 139759057106688] mod_authz_core.c(809): [client ::1:50254] AH01626: authorization result of Require all granted: granted
[Mon May 31 10:55:02.911601 2021] [authz_core:debug] [pid 1221:tid 139759057106688] mod_authz_core.c(809): [client ::1:50254] AH01626: authorization result of <RequireAny>: granted
[Mon May 31 10:55:02.916610 2021] [authz_core:debug] [pid 1221:tid 139759057106688] mod_authz_core.c(809): [client ::1:50254] AH01626: authorization result of Require all granted: granted
[Mon May 31 10:55:02.916641 2021] [authz_core:debug] [pid 1221:tid 139759057106688] mod_authz_core.c(809): [client ::1:50254] AH01626: authorization result of <RequireAny>: granted
[Mon May 31 10:55:02.918439 2021] [wsgi:info] [pid 1219:tid 139759048713984] [remote ::1:50254] mod_wsgi (pid=1219, process='flask_web', application=''): Loading Python script file '/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi'.
[Mon May 31 10:55:02.969408 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254] mod_wsgi (pid=1219): Failed to exec Python script file '/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi'.
[Mon May 31 10:55:02.969545 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254] mod_wsgi (pid=1219): Exception occurred processing WSGI script '/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi'.
[Mon May 31 10:55:02.980984 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254] Traceback (most recent call last):
[Mon May 31 10:55:02.981044 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254]   File "/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/rest.wsgi", line 4, in <module>
[Mon May 31 10:55:02.981051 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254]     from flask_web import app as application
[Mon May 31 10:55:02.981060 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254]   File "/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/flask_web.py", line 3, in <module>
[Mon May 31 10:55:02.981065 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254]     from flask import Flask, request, Response, json
[Mon May 31 10:55:02.981084 2021] [wsgi:error] [pid 1219:tid 139759048713984] [remote ::1:50254] ModuleNotFoundError: No module named 'flask'
```

wsgi file remains the same as in first comment.

**Comment by GrahamDumpleton** [comment]
Are you sure the path:

```
/mnt/c/Users/JABR/Documents/MELOA-docker-compose/flask_web/venvs
```

is correct? It seems odd to have ``s`` at end to make it plural.

With the virtual environment activate, from a command line Python do:

```
import sys
print(sys.prefix)
```

The path it outputs is what you should use.

Also ensure that permissions on the virtual environment and installed packages allow any user to access it. If you for example installed stuff as ``root`` and ``root`` umask was restrictive, other users wouldn't be able to access it.

**Comment by JavierBrRuiz** [comment]
Yes it is correct: 
![](https://user-images.githubusercontent.com/38103252/120448204-a02b6100-c38b-11eb-9ca3-657884d520af.png)

It may be a privilege problem since I installed apache and mod_wsgi in the wsl with sudo command while the virtual environment was created in windows under javierbrenes user, which is not the admin user. I will investigate this.

Anyway if this is the error, shouldn't the error log show a privilege error instead a moduleNotFound one? Just for curiosity.

**Comment by JavierBrRuiz** [comment]
Okay @GrahamDumpleton I solved the problem, it was a combination of using a pychar venv in windows and using postgres in docker.

The steps I followed to solve the issue were:

### 1 - RECONFIGURE VIRTUAL ENVIRONMENT REFERENCE
As mentioned in the docs I referenced the venv with python-home as recommended, instead of site-packages and python-paht

### 2 - Make sure mod_wsgi compilation version and virtual environment is the same
 As pointed out by Graham:
check mod_wsgi  https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use
check venv -> path/to/venv/bin/ there you can find python interpreter with version (there are for sure more fancy ways to know which version your venv use)

### 3 - IN WSL ADD libpq-dev PACKAGE
pip will not install correctly psycopg2 because is unable to find pg_config if you are using postgres in a docker machine as I am,
first: 
`sudo apt-get install libpq-dev`
then: 
`pip install psycopg2`

Thank you so much for your help @GrahamDumpleton it was very useful!
