### ISSUE TITLE
“mod_wsgi-express module-config” command not working in windows command Prompt?

### ISSUE THREAD

**Issue by SabarishTK** [GrahamDumpleton/mod_wsgi#685]
set "MOD_WSGI_APACHE_ROOTDIR=C:\xampp\Apache" in windows environment variable but Not work mod_wsgi-express module-config command .I got this error  "mod_wsgi-express module-config Error"

C:\WINDOWS\system32>mod_wsgi-express module-config
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\mod_wsgi-express-script.py", line 33, in <module>
    sys.exit(load_entry_point('mod-wsgi==4.8.0', 'console_scripts', 'mod_wsgi-express')())
  File "C:\Program Files\Python39\Scripts\mod_wsgi-express-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Jaikumar\AppData\Roaming\Python\Python39\site-packages\mod_wsgi\server\__init__.py", line 29, in <module>
    from . import apxs_config
  File "C:\Users\Jaikumar\AppData\Roaming\Python\Python39\site-packages\mod_wsgi\server\apxs_config.py", line 26
    BINDIR = 'C:\xampp\apache\/bin'
                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-4: truncated \xXX escape

**Comment by GrahamDumpleton** [comment]
Don't use backslash in:

```
MOD_WSGI_APACHE_ROOTDIR=C:\xampp\Apache
```

use forward slash.

```
MOD_WSGI_APACHE_ROOTDIR=C:/xampp/Apache
```

The page on PyPi warns about this:

> If you are on Windows and your Apache distribution is not installed into the directory C:/Apache24, first set the environment variable MOD_WSGI_APACHE_ROOTDIR to the directory containing the Apache distribution. Ensure you use forward slashes in the directory path. The directory path should not include path components with spaces in the name.

You will need to use:

```
pip install --no-cache-dir mod_wsgi
```

when reinstalling to avoid it using the cached version.

Also be aware that only the Apache distribution for Apache Lounge is recommended. Any others may not work as some are missing bits that allow third party Apache modules to be compiled properly.

**Comment by SabarishTK** [comment]
Thanks for your Reply. I checked with your instruction. But not working that ideas. I have worked using xampp Apache. So I will try with Xampp/Apache. Now start Another error.
**'mod_wsgi-express' is not recognized as an internal or external command,operable program or batch file**.

**Comment by GrahamDumpleton** [comment]
Make sure you uninstalled the installed version of mod_wsgi first.

```
pip uninstall mod_wsgi
```

Double check you set ``MOD_WSGI_APACHE_ROOTDIR`` with forward slashes as explained and using same case as file pathname actually uses.

And then run:

```
pip install --no-cache-dir mod_wsgi
```

If not uninstalled first, would need to force reinstall.

```
pip install --no-cache-dir -U mod_wsgi
```

**Comment by SabarishTK** [comment]
I put the command with your instruction.

c:\>set "MOD_WSGI_APACHE_ROOTDIR=c:/xampp/apache"

c:\>pip uninstall mod_wsgi
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
Found existing installation: mod-wsgi 4.8.0
Uninstalling mod-wsgi-4.8.0:
  Would remove:
    c:\users\jaikumar\appdata\roaming\python\python39\scripts\mod_wsgi-express.exe
    c:\users\jaikumar\appdata\roaming\python\python39\site-packages\mod_wsgi-4.8.0.dist-info\*
    c:\users\jaikumar\appdata\roaming\python\python39\site-packages\mod_wsgi\*
Proceed (y/n)? y
  Successfully uninstalled mod-wsgi-4.8.0


c:\>pip install --no-cache-dir --user -U mod_wsgi
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
Collecting mod_wsgi
  Downloading mod_wsgi-4.8.0.tar.gz (2.6 MB)
     |████████████████████████████████| 2.6 MB 3.3 MB/s
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... done
  Created wheel for mod-wsgi: filename=mod_wsgi-4.8.0-cp39-cp39-win_amd64.whl size=2955270 sha256=0a0c6f912e7f968d0a1126d70d4a0382d32ecb47028362135de2ebd727d8c470
  Stored in directory: C:\Users\Jaikumar\AppData\Local\Temp\pip-ephem-wheel-cache-jdgmkmlz\wheels\a9\3c\4d\93e544c95731be58a616907d177970d4fc83e150e46873d57e
Successfully built mod-wsgi
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
Installing collected packages: mod-wsgi
  WARNING: The script mod_wsgi-express.exe is installed in 'C:\Users\Jaikumar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed mod-wsgi-4.8.0
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)

c:\>mod_wsgi-express module-config
'mod_wsgi-express' is not recognized as an internal or external command,
operable program or batch file.

Now,I got same mistake..

**Comment by GrahamDumpleton** [comment]
It is because you are using ``--user`` option. If you are going to use that option then you must add the script directory created under your home directory where Python applications are installed, to your path. The message even tells you this.

```
WARNING: The script mod_wsgi-express.exe is installed in 'C:\Users\Jaikumar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed mod-wsgi-4.8.0
```

**Comment by SabarishTK** [comment]
I used this command.
:\WINDOWS\system32>pip install --no-cache-dir mod_wsgi
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
Collecting mod_wsgi
  Downloading mod_wsgi-4.8.0.tar.gz (2.6 MB)
     |████████████████████████████████| 2.6 MB 2.2 MB/s
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... done
  Created wheel for mod-wsgi: filename=mod_wsgi-4.8.0-cp39-cp39-win_amd64.whl size=2955272 sha256=29ecafe81edc67e35dbc47b981545d8b20d8122397f25a5b715ec79b705813a0
  Stored in directory: C:\Users\Jaikumar\AppData\Local\Temp\pip-ephem-wheel-cache-gx5onuk4\wheels\a9\3c\4d\93e544c95731be58a616907d177970d4fc83e150e46873d57e
Successfully built mod-wsgi
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
Installing collected packages: mod-wsgi
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\program files\\python39\\Lib\\site-packages\\mod_wsgi\\server\\mod_wsgi.cp39-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -od-wsgi (c:\program files\python39\lib\site-packages)

then used **pip install --no-cache-dir --user -U mod_wsgi** command . How to solve this Problem?

**Comment by GrahamDumpleton** [comment]
If you aren't administrator on your computer then you will have no choice but to use ``--user``, but as I said, you need to add the script path, which in your case is:

```
C:\Users\Jaikumar\AppData\Roaming\Python\Python39\Scripts
```

to your ``PATH`` so that ``mod_wsgi-express`` command can be found.

There seems though to be something screwed up with your system now where mod_wsgi was previously installed, possibly as different user, into system wide Python installation.

Try to run:

```
pip uninstall mod_wsgi
```

twice as strange things can start to happen if you installed it into system wide Python and user specific Python directories.

If need be run that uninstall command twice as an administrator as well.

**Comment by SabarishTK** [comment]
Yeah! Now Solved this Problem.Thanks for your Guidelines. thank you

**Comment by SabarishTK** [comment]
Yeah! Its worked. Thanks for your Guidlines.
