### ISSUE TITLE
Why is forced LD_RUN_PATH addition?

### ISSUE THREAD

**Issue by uhliarik** [GrahamDumpleton/mod_wsgi#686]
Hi, I would like to know, what is the reason of force addition of LD_RUN_PATH in setup.py? In Fedora, Linux dynamic linker should be smart enough to to find correct path, rather than hardcoding it. 

```
# Force adding of LD_RUN_PATH for platforms that may need it.

if os.name != 'nt':
    LD_RUN_PATH = os.environ.get('LD_RUN_PATH', '')
    LD_RUN_PATH += ':%s:%s' % (PYTHON_LIBDIR, PYTHON_CFGDIR)
    LD_RUN_PATH = LD_RUN_PATH.lstrip(':')

    os.environ['LD_RUN_PATH'] = LD_RUN_PATH
```

Can it be safely removed?

**Comment by uhliarik** [comment]
Thanks @GrahamDumpleton for your fast reply. Sorry, I didn't mention the purpose, why I'm asking.

The reason is, that in Fedora, we don't permit use of rpath[0]. Since during the installation we use Python from Fedora repositories, I think it is no needed for my usecase to use LD_RUN_PATH. But as you mentioned above, in some usecases e.g. when you have self installed Python, it is necessary. 

So in case, it should be safe to remove rpath during the mod_wsgi RPM build in Fedora.  

[0] https://fedoraproject.org/wiki/RPath_Packaging_Draft

**Comment by GrahamDumpleton** [comment]
Linux systems have traditionally packaged mod_wsgi using the CMMI (configure, make, make install) method. For that type of installation the ``setup.py`` isn't used. The ``setup.py`` is only relevant if using ``pip install`` to install mod_wsgi. So if all you are doing is reviewing the existing mod_wsgi system package which uses CMMI method of installation (not pip install) you don't need to change it as it isn't used.

**Comment by GrahamDumpleton** [comment]
Closing on basis that PR https://github.com/GrahamDumpleton/mod_wsgi/pull/694 is addressing this issue and PR was merged.
