### ISSUE TITLE
using mod_wsgi with multithreading packages such as numba

### ISSUE THREAD

**Issue by celinesin** [GrahamDumpleton/mod_wsgi#689]
I'm trying to serve a small dash app using Flask/wsgi/apache2, and it calls fit_transform() from sci-kit learn (which in turn uses numba)

We've confirmed that it runs fine (1) in the python console, and (2) within a Flask instance, but NOT when being served with mod_wsgi/apache2.  We discovered that the problem is not fundamentally something about running JIT code, but something about Numba's runtime. I can compile functions, but I can't execute them.

I suspect it might be something I've omitted from my .conf file, and perhaps it might have something to do with a WSGIDaemonProcess statement or https://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html
There are no error messages, it eventually just times out.

Possibly helpful for more background are these two threads:
https://github.com/lmcinnes/umap/issues/665
https://github.com/numba/numba/issues/7095

I'd be very grateful for any hints/tips/advice!  Thanks in advance!

My .conf file is as follows

```
<VirtualHost *:8882>
                ServerName THENAMEOFTHESERVER
                ServerAdmin admin@menchelab.com
                WSGIScriptAlias / /var/www/cartoGRAPHs_app/cartoGRAPHs_app.wsgi
                WSGIDaemonProcess THENAMEOFTHESERVER processes=2 threads=10
                <Directory /var/www/cartoGRAPHs_app/cartoGRAPHs_app/>
                        Order allow,deny
                        Allow from all
                </Directory>
                Alias "/static/" "/var/www/cartoGRAPHs_app/cartoGRAPHs_app/static/"
                <Directory /var/www/cartoGRAPHs_app/cartoGRAPHs_app/static/>
                        Order allow,deny
                        Allow from all
                </Directory>
                Alias "/assets/" "/var/www/cartoGRAPHs_app/cartoGRAPHs_app/assets/"
                <Directory /var/www/cartoGRAPHs_app/cartoGRAPHs_app/assets/>
                        Order allow,deny
                        Allow from all
                </Directory>
                Alias "/input/" "/var/www/cartoGRAPHs_app/cartoGRAPHs_app/input/"
                <Directory /var/www/cartoGRAPHs_app/cartoGRAPHs_app/input/>
                        Order allow,deny
                        Allow from all
                </Directory>
                ErrorLog ${APACHE_LOG_DIR}/error.log
                LogLevel debug
                CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

I originally did not have the WSGIDaemonProcess line, also doesn't work ^^;

**Comment by GrahamDumpleton** [comment]
The ``numpy`` package and thus anything dependent on it will not work properly in Python sub interpreters. You need to force the use of the main Python interpreter context. Use:

```
                WSGIDaemonProcess THENAMEOFTHESERVER processes=2 threads=10
                WSGIScriptAlias / /var/www/cartoGRAPHs_app/cartoGRAPHs_app.wsgi process-group=THENAMEOFTHESERVER application-group=%{GLOBAL}
```

Your configuration in general was incorrect anyway, as although you were creating a mod_wsgi daemon process group, you weren't telling mod_wsgi to use it. In the configuration snippet above, that is what the ``process-group`` option does. The ``application-group`` option is telling it what interpreter context to use and in this case is forcing it to use the main interpreter context.

Make that change and then see how things go.

Also read:

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#python-simplified-gil-state-api

Example configuration above uses a different way of ensuring the main interpreter context is used. You don't need to change it to what that doc says.

**Comment by celinesin** [comment]
It worked!  Thanks for your help!

Just for understanding, does that mean if I have multiple apps on the same server, they are all sharing the same main Python interpreter?

**Comment by GrahamDumpleton** [comment]
Because in the above configuration it is forcing the use of the main interpreter context, you can't run multiple in the same daemon process group, so all you do is create multiple daemon process groups and delegate each application to a separate daemon process group. Eg:

```
                WSGIDaemonProcess app1 processes=2 threads=10
                WSGIScriptAlias /subdir /some/path/app.wsgi process-group=app1 application-group=%{GLOBAL}

                WSGIDaemonProcess app2 processes=2 threads=10
                WSGIScriptAlias / //some/other/path/app.wsgi process-group=app2 application-group=%{GLOBAL}
```
