### ISSUE TITLE
compile for VC11

### ISSUE THREAD

**Issue by hgabe** [GrahamDumpleton/mod_wsgi#69]
How do I compile it for apache vc11 variants

**Comment by GrahamDumpleton** [comment]
You can't. An explanation is provided in:

* https://github.com/GrahamDumpleton/mod_wsgi/tree/develop/win32

Any C code that needs to work against Python must be compiled with the same Microsoft C/C++ runtime as that version of Python was compiled for.

No version of Python has ever used VC11.

As explained in that document, you can try using a VC9 or VC10 binary with a VC11 Apache, but whether it will work for you cannot be guaranteed. Some people have reported success though.

Do note though that if you intend to build any additional Python modules with C extensions, you cannot use the VC11 compiler that you may have, you must use the same as what that version of Python was compiled for. That page tells you where you can get the correct compiler version.
