### ISSUE TITLE
Can not load python/mod_wsgi

### ISSUE THREAD

**Issue by FadhilPrawira** [GrahamDumpleton/mod_wsgi#690]
I follow step from [stackoverflow](https://stackoverflow.com/questions/59801387/how-to-install-mod-wsgi-into-apache-on-windows) with a some modification
What i've done :
1.  `set MOD_WSGI_APACHE_ROOTDIR=C:/Apache24`
2. `pip install mod-wsgi`
3. `mod_wsgi-express module-config`
Note : 
Python version : `3.9.5` at at `C:\Users\herma\AppData\Local\Programs\Python\Python39` or  `%localappdata%\Programs\Python\Python39`
Apache version : `httpd-2.4.48-win64-VS16` from [apachelounge.com](https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.48-win64-VS16.zip) installed at `C:\Apache24`
I already connect apache with PHP `VS16 x64 Thread Safe (2021-Jun-02 01:28:46)` from [windows.php.net](https://windows.php.net/downloads/releases/php-8.0.7-nts-Win32-vs16-x64.zip) installed at `C:\php`

Output from command 
`LoadFile "c:/users/herma/appdata/local/programs/python/python39/python39.dll"
LoadModule wsgi_module "c:/users/herma/appdata/local/programs/python/python39/lib/site-packages/mod_wsgi/server/mod_wsgi.cp39-win_amd64.pyd"
WSGIPythonHome "c:/users/herma/appdata/local/programs/python/python39"`

4. Copy the output of the previous command into my Apache's httpd.conf (C:\Apache24\conf\httpd.conf) 
[httpd-conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/6645251/httpd-conf.txt)

5. Restart the apache from apachemonitor.exe, there is alert pop up `The requested operation has failed`
6. Check the error.log from `C:\Apache24\logs\error.log` 
[error.log](https://github.com/GrahamDumpleton/mod_wsgi/files/6645245/error.log)

Please help me solve this. Thanks

**Comment by GrahamDumpleton** [comment]
Are you trying to use Anaconda Python 3.9? Based on experience of others, that version of Anaconda Python had broken the ability to be used in embedded systems. Anaconda Python keeps breaking things every so often. It is recommended to avoid using Anaconda Python with mod_wsgi as a result. Use standard Python from the Python Software Foundation.

**Comment by maps82** [comment]
I have the same problem with the official windows build of python 3.9.5 from python.org after upgrading from mod_wsgi 4.7.1 to 4.8.0.

When you look at the error.log, isn't it strange that the first entry in sys.path points to a python39.zip file in the python install directory?! It's the same for me (C:\Python\Python3.9\python39.zip). The zip file is not there, but the path is correct (which means python is installed to C:\Python\Python3.9)

**Comment by GrahamDumpleton** [comment]
@maps82 What is the configuration you are using?

**Comment by norigithub** [comment]
I have a same error(ModuleNotFoundError: No module named 'encodings') running "C:\Apache24\bin\httpd.exe -k start".
[error.log](https://github.com/GrahamDumpleton/mod_wsgi/files/6724633/error.log)

If I run service as a user account, it works and return response("Hello World!").

Versions
Win10 Pro 21H1
Apache httpd 2.4.48
Python 3.8.10
mod-wsgi 4.8.0

I added below to httpd.conf.
```
LoadFile "C:/Users/Nori/AppData/Local/Programs/Python/Python38/python38.dll"
LoadModule wsgi_module "c:/users/nori/documents/wsgiapp/env/lib/site-packages/mod_wsgi/server/mod_wsgi.cp38-win_amd64.pyd"
WSGIPythonHome "c:/users/nori/documents/wsgiapp/env"

WSGIScriptAlias /hello "c:/users/nori/documents/wsgiapp/helloapp.wsgi"
<Directory "c:/users/nori/documents/wsgiapp">
    Require all granted
</Directory>
```
helloapp.wsgi
```
import sys
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!'

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]
```

**Comment by GrahamDumpleton** [comment]
Ensure Python is installed for all users and not just the user who installed it.

**Comment by norigithub** [comment]
> Ensure Python is installed for all users and not just the user who installed it.
Thank you for quick reply.  This fix the problem.

Python Installer > Customize installation > Advanced Options
checked "Install for all users.".

**Comment by GrahamDumpleton** [comment]
I presume your own user can access the files for the virtual environment okay.

When you start Apache is the virtual environment activate first?

What Python version/installation is found if you run command line Python?

**Comment by GrahamDumpleton** [comment]
Closing as no further response.
