### ISSUE TITLE
Microsoft Visual C++ Build Tools is gone

### ISSUE THREAD

**Issue by ZhangYupengCHY** [GrahamDumpleton/mod_wsgi#693]
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
The url "http://landinghub.visualstudio.com/visual-cpp-build-tools" is NOT FOUND.

**Comment by GrahamDumpleton** [comment]
See:

* https://wiki.python.org/moin/WindowsCompilers

to see if the links there for downloads work.

**Comment by ZhangYupengCHY** [comment]
http://go.microsoft.com/fwlink/?LinkId=691126 
This Link is valuable for Microsoft Visual C++ Build Tools.
