### ISSUE TITLE
Fatal Python error: initfsencoding: unable to load the file system codec ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by ZhangYupengCHY** [GrahamDumpleton/mod_wsgi#695]
I get the following error when attempting to launch my apache server:

```
Current thread 0x00002464 (most recent call first):
[Sat Jun 19 16:29:38.535108 2021] [mpm_winnt:notice] [pid 5788:tid 828] AH00428: Parent: child process 14664 exited with status 3221226505 -- Restarting.
[Sat Jun 19 16:29:38.588966 2021] [mpm_winnt:notice] [pid 5788:tid 828] AH00455: Apache/2.4.46 (Win64) OpenSSL/1.1.1j PHP/8.0.3 mod_wsgi/4.9.0 Python/3.7 configured -- resuming normal operations
[Sat Jun 19 16:29:38.588966 2021] [mpm_winnt:notice] [pid 5788:tid 828] AH00456: Apache Lounge VS16 Server built: Feb 17 2021 13:11:14
[Sat Jun 19 16:29:38.588966 2021] [core:notice] [pid 5788:tid 828] AH00094: Command line: 'D:\\xampp\\apache\\bin\\httpd.exe -d D:/xampp/apache'
[Sat Jun 19 16:29:38.589963 2021] [mpm_winnt:notice] [pid 5788:tid 828] AH00418: Parent: Created child process 15192
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

And my apache config is:

```
LoadFile "D:/python37/python37.dll"
LoadModule wsgi_module "D:/django-apache/venv2/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIScriptAlias / D:\django-apache\demo\demo\wsgi.py
WSGIPythonPath "D:/django-apache/venv2/Lib/site-packages"
<Directory D:\django-apache\demo\demo>
	<Files wsgi.py>
		Require all granted
	</Files>
</Directory>
Alias /media/ D:/django-apache/demo/static/
<Directory D:/django-apache/demo/static>   
	Require all granted  
</Directory>

Alias /static/ D:/django-apache/demo/static/
<Directory D:/django-apache/demo/static>   
	Require all granted  
</Directory>

WSGIApplicationGroup %{GLOBAL}
```

I already test the issue of [#563](https://github.com/GrahamDumpleton/mod_wsgi/issues/563) and  [#559](https://github.com/GrahamDumpleton/mod_wsgi/issues/559).
Unfortunately the apache error log is always the same.

BTW mod_wsgi I used:

```
pip install --no-cache-dir -U https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

Im looking forward for your answer.
So much appricated.

**Comment by GrahamDumpleton** [comment]
At the moment you should avoid using ``develop`` version from GitHub as some changes were made in last few days which are untested on Windows yet. Wouldn't result in this error, but still best to avoid it. Use the latest official version of PyPi instead.

For a start, instead of:

```
WSGIPythonPath "D:/django-apache/venv2/Lib/site-packages"
```

use:

```
WSGIPythonHome "D:/django-apache/venv2"
```

The workaround of using ``WSGIPythonPath`` as talked about in old issues should not be needed with latest version on PyPi.

Also try to avoid using back slashes in Apache config. Always use forward slashes for path separators.

**Comment by ZhangYupengCHY** [comment]
First thing first,I so appricated for your answer so quickly.
I did three things before
1. reinstall the mod_wsgi by pip.
2.changed the WSGIPythonPath "D:/django-apache/venv2/Lib/site-packages" to WSGIPythonHome "D:/django-apache/venv2"
3.use forward slashes for path separators

And my apache config right now:

```
LoadFile "D:/python37/python37.dll"
LoadModule wsgi_module "D:/django-apache/venv2/lib/site-packages/mod_wsgi/server/mod_wsgi.cp37-win_amd64.pyd"
WSGIPythonHome "D:/django-apache/venv2"

# WSGIPythonPath "D:/django-apache/demo"

WSGIScriptAlias / D:/django-apache/demo/demo/wsgi.py

<Directory D:/django-apache/demo/demo>
	<Files wsgi.py>
		Require all granted
	</Files>
</Directory>

Alias /media/ D:/django-apache/demo/static/
<Directory D:/django-apache/demo/static>   
	Require all granted  
</Directory>


Alias /static/ D:/django-apache/demo/static/
<Directory D:/django-apache/demo/static>   
	Require all granted  
</Directory>

WSGIApplicationGroup %{GLOBAL}

# LogLevel debug
```

And I restart the django and apache.
But apache error log is still the same.

**Comment by GrahamDumpleton** [comment]
Are you running Apache manually from command line or as a system service? If a system service, does the user the system service runs as have permission to access the directory ``D:/django-apache``?

**Comment by ZhangYupengCHY** [comment]
I running it by XAMPP and apache run as a system service.

A minute ago,I used the python3.5 and XMAPP and all running good.And I want the django run by python3.7 so I changed the python3.5 to python 3.7 and reinstall the venv, and I can visit the web by django port and cant by apache port.
And my wsgi.py is 

```
import os,sys

from django.core.wsgi import get_wsgi_application

sys.path.append('D:/django-apache/demo')
sys.path.append('D:/django-apache/demo/demo')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'demo.settings')

application = get_wsgi_application()
```

I just so confused where I config is wrong.

**Comment by GrahamDumpleton** [comment]
Are you using standard Python distribution from the Python Software Foundation, or Anaconda Python?

Anaconda Python is known to have various problems which means some versions of it don't work properly in embedded system like with how Apache/mod_wsgi works.

**Comment by ZhangYupengCHY** [comment]
Im using the pycharm and install mod_wsgi by terminal with pip.
I will try some config.
So much much appricated for you to make sometime for answer my question which can caused by so many situations.

**Comment by GrahamDumpleton** [comment]
Try creating a ``hello.wsgi`` file containing:

```
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!'

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]
````

Then with the virtual environment activated, run in the same directory as the ``hello.wsgi`` file:

```
mod_wsgi-express start-server hello.wsgi
```

Try connecting to ``http://localhost:8000``.

This will test using a hidden feature which is still experimental for Windows and shouldn't normally be used as still has issues, but it runs Apache with a auto-generated configuration.

Note that it may not work at all since you are not using ApacheLounge distribution of Apache, which is what ``start-server`` on Windows expects to have. Also, you may have to use task manager to kill it when done with test as ``ctrl-c`` will not work depending on shell environment.

Anyway, this is just to test whether it works from command line rather than as system service, don't rely on using this.

**Comment by ZhangYupengCHY** [comment]
I will give a try and tall you what I test.
Anyway thank a lot again for your answer





------------------ Original ------------------
From: Graham Dumpleton ***@***.***&gt;
Date: Sat,Jun 19,2021 6:02 PM
To: GrahamDumpleton/mod_wsgi ***@***.***&gt;
Cc: Aaron Ramsey ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GrahamDumpleton/mod_wsgi] Fatal Python error: initfsencoding: unable to load the file system codec ModuleNotFoundError: No module named 'encodings' (#695)





 
Try creating a hello.wsgi file containing:
 def application(environ, start_response):     status = '200 OK'     output = b'Hello World!'     response_headers = [('Content-type', 'text/plain'),                         ('Content-Length', str(len(output)))]     start_response(status, response_headers)     return [output]  
Then with the virtual environment activated, run in the same directory as the hello.wsgi file:
 mod_wsgi-express start-server hello.wsgi  
Try connecting to http://localhost:8000.
 
This will test using a hidden feature which is still experimental for Windows and shouldn't normally be used as still has issues, but it runs Apache with a auto-generated configuration.
 
Note that it may not work at all since you are not using ApacheLounge distribution of Apache, which is what start-server on Windows expects to have. Also, you may have to use task manager to kill it when done with test as ctrl-c will not work depending on shell environment.
 
Anyway, this is just to test whether it works from command line rather than as system service, don't rely on using this.

**Comment by ZhangYupengCHY** [comment]
When I run 
`mod_wsgi-express start-server hello.wsgi`
in terminal.

`Server URL         : http://localhost:8000/
Server Root        : C:/Users/ADMINI~1/AppData/Local/Temp/mod_wsgi-localhost-8000-Administrator
Server Conf        : C:/Users/ADMINI~1/AppData/Local/Temp/mod_wsgi-localhost-8000-Administrator/httpd.conf
Error Log File     : C:/Users/ADMINI~1/AppData/Local/Temp/mod_wsgi-localhost-8000-Administrator/error_log (warn)
Operating Mode     : daemon
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : zh_CN.gbk

WARNING: The ability to use the start-server option on Windows
WARNING: is highly experimental and various things don't quite
WARNING: work properly. If you understand a lot about using
WARNING: Python on Windows and Windows programming in general,
WARNING: and would like to help to get it working properly, then
WARNING: you can ask about Windows support for the start-server
WARNING: option on the mod_wsgi mailing list.
`

And I try connecting to http://localhost:8000.But could not connect.
Show "ERR_CONNECTION_REFUSED".

**Comment by GrahamDumpleton** [comment]
And what was output to:

```
C:/Users/ADMINI~1/AppData/Local/Temp/mod_wsgi-localhost-8000-Administrator/error_log
```

**Comment by ZhangYupengCHY** [comment]
error_log Output is 
`Current thread 0x000024d8 (most recent call first):
[Mon Jun 21 09:25:39.918731 2021] [core:warn] [pid 7836:tid 1248] AH00098: pid file C:/Users/Administrator/AppData/Local/Temp/mod_wsgi-localhost-8000-Administrator/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'`

BTW I change the python3.7,venv2(python3.7 virtual) to python 3.5,venv(python virtual) and different between the two virtual is mod_wsgi in python3.7 virtual is pip in pycharm Terminal and mod_wsgi in python3.5 virtual is whl.
And when I changed to python3.5 everything run perfect.

**Comment by GrahamDumpleton** [comment]
Did you install Python for all users of the systems, or only your current user?

Especially when using system service to run Apache, the Python installation must be installed for all users.

**Comment by ZhangYupengCHY** [comment]
Oky.I installing Python3.7.8(64-bit) right now and config the installed for all users and Its oky Now.
Thank you so much. It worked. Really appreciate you help with this.
