### ISSUE TITLE
Best practice for having two versions of the same app served by mod_wsgi

### ISSUE THREAD

**Issue by pitosalas** [GrahamDumpleton/mod_wsgi#701]
(This is related to my previous issue but I thought it deserved it's own)

As we develop our app (flask, poetry, postgres) I would like to have a "test" version and a "production" version in the typical sense. I plan to have them on separate branches in git/github. 

I came up with my current plan in kind of a vacuum but I believe you should have a good sense and opinion. The current scheme is to create two virtual environments which contain not just the dependencies but the app itself, each built based on the corresponding branch. 

I have yet to tackle how to handle cron jobs and perhaps (?) even different db schemas. But as I go deeper I wonder whether this is the Best practice or whether I am heading for some unforeseen trouble.

What have you seen? Thanks!

**Comment by GrahamDumpleton** [comment]
Separate virtual environments is always a first step to ensure separation, but because you may want virtual environments to use different Python versions, you should also be hosting them on different hosts. The only way around that would be that during test you use ``mod_wsgi-express`` rather than manually configure Apache as this will allow you to more easily have separate Apache instances on same host with different Python versions.

* http://blog.dscpl.com.au/2015/04/introducing-modwsgi-express.html
* https://pypi.org/project/mod-wsgi/

**Comment by pitosalas** [comment]
They will be using the same python version, just different "code" for specific scripts, e.g.  my_class.py would be different in the two instances.

When you say "hosting them on different hosts" I assume you mean different apache virtual hosts, right?

If I put the .venv inside the project directory itself (vs. some specified path) is there a way to get mod_wsgi to see and apply it automatically? (Including changing the shebangs?)

**Comment by GrahamDumpleton** [comment]
I meant different hosts since usually you wouldn't mix production stuff with non production and usually developers aren't even allowed near production. :-)

As to the shebang, mod_wsgi doesn't expect one in a WSGI script file and doesn't care about if you do have one. The version of Python is dictated by what mod_wsgi is compiled for and nothing else.

I presume if using virtual environments you are already using ``python-home`` option with ``WSGIDaemonProcess`` directive. That is all that should be required for virtual environment. Would also need ``python-path`` to pick up your project code.

If haven't already watched it, suggest watching:

* https://www.youtube.com/watch?v=H6Q3l11fjU0&t=4s

Might give you some things to think about.

**Comment by pitosalas** [comment]
Thanks again…

> I meant different hosts since usually you wouldn't mix production stuff with non production and usually developers aren't even allowed near production. :-)

Yeah, this is “production” not PRODUCTION (i.e. a smallish product for a research project that will eventually be used by 200 people max.)

> I presume if using virtual environments you are already using python-home option with WSGIDaemonProcess directive. That is all that should be required for virtual environment. Would also need python-path to pick up your project code.

WSGIDaemonProcess test python-home=/home/rpsalas/mydev/development/.venv python-path=/home/rpsalas/mydev/development

I’ve verified that the .venv contains my “top level package” (called otproject) and that those two paths are “correct”. 

And still a simple import otproject inside of my test.wsgi nails with a ModuleNotFound error.

I tried several permutations of those two paths and none worked. 

(Why? In order to make my imports in the source code sane, I have put all the packages in the program (including the top level) into my package manager (poetry). That way a simple import otprojec.x.y works and things feel simple and clean)

Thanks!

**Comment by GrahamDumpleton** [comment]
What is the mod_wsgi configuration you are using?

If you don't set up ``WSGIDaemonProcess`` and ``WSGIProcessGroup`` correctly, then you could be attempting to run your request against wrong daemon process group and as a result wrong environment being used.

So show the config, but also add to the WSGI script file:

```
import sys
print(sys.prefix)

import mod_wsgi
print(mod_wsgi.process_group)
```

to verify what virtual environment and daemon process group is being used. Output will be in the Apache error log.

**Comment by pitosalas** [comment]
> What is the mod_wsgi configuration you are using?

Yeah that's a problem. I don't know. I don't remember for sure how I installed it but I think it was sudo apt-get install libapache2-mod-wsgi-py3 but I am not sure. I got the box from our IT with apache2 already installed. I am pretty positive I didn't make from source.

It seems like my step for mod_wsgi-express depends on my knowing the answer of the above...

Thanks!

p.s. I saw your YouTube; that was very informative!

**Comment by GrahamDumpleton** [comment]
When I say configuration, I am not talking about what versions of packages were installed and from where. If you are manually configuring Apache for mod_wsgi, I am talking about the Apache and mod_wsgi configuration directives you are sticking in your Apache configuration file. Thus, VirtualHost definition, usage of WSGIDaemonProcess, WSGIProcessGroup, WSGIApplicationGroup, WSGIScriptAlias directives etc. Right now I am still assuming your are manually configuring Apache to add all that in.

**Comment by pitosalas** [comment]
Here are all the bits...I appreciate your help very much:

otproject.conf:

```
<VirtualHost *:80>
	WSGIDaemonProcess test python-home=/home/rpsalas/mydev/development/.venv
	WSGIScriptAlias /test /var/www/test/test.wsgi process-group=test application-group=%{GLOBAL}
	<Directory /var/www/test/src/>
		Order allow,deny
		Allow from all
	</Directory>
</VirtualHost>
```

ls -la /var/www/tests

```
drwxr-xr-x 2 root root 4096 Jul 27 13:39 .
drwxr-xr-x 5 root root 4096 Jul 27 07:57 ..
lrwxrwxrwx 1 root root   31 Jul 23 07:52 src -> /home/rpsalas/mydev/development
-rw-r--r-- 1 root root  139 Jul 27 21:12 test.wsgi
```

test.wsgi:

```
print(sys.prefix)
import mod_wsgi
print(mod_wsgi.process_group)
from otproject.otpflask.src.teacher import app as application
```

And from logging from this when I restart apache:
```

[Wed Jul 28 08:23:20.474350 2021] [mpm_event:notice] [pid 192533:tid 140597196172352] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.6.8 Python/3.8 configured -- resuming normal operations
[Wed Jul 28 08:23:20.475293 2021] [core:notice] [pid 192533:tid 140597196172352] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 28 08:23:20.629902 2021] [wsgi:error] [pid 192534:tid 140597196172352] /home/rpsalas/mydev/development/.venv
[Wed Jul 28 08:23:20.630474 2021] [wsgi:error] [pid 192534:tid 140597196172352] test
```

**Comment by GrahamDumpleton** [comment]
From command line activated Python virtual environment, in interactive Python interpreter what do you get for:

```
import otproject
print(otproject.__file__)
```

**Comment by pitosalas** [comment]
Hi Graham

Thanks, I think I solved it by totally uninstalling my .venv and reinstalling it. It's all working now!

I never set up express because I am not sure which of the scenarios apply to me. I know I have ubuntu and apache 2.2. But I am using poetry for my venv and they say don't use pip. Since stuff works now for me maybe it's not worth the trouble?

In any event you've been super helpful -- Thanks!

Pito Salas
Faculty, Computer Science
Brandeis University
