### ISSUE TITLE
mod_wsgi ignoring headers that should make URLs https

### ISSUE THREAD

**Issue by elyograg** [GrahamDumpleton/mod_wsgi#702]
I've got this app installed:  https://github.com/atoponce/d-note

I found information on mod_wsgi explaining which HTTP headers should tell mod_wsgi to build URLs with https instead of http.  I implemented most of those headers in my proxy config (using haproxy).  But I can only get the app to function properly if I use an apache virtualhost configured to use https.  As soon as I switch it to a virtualhost without https, it builds URLs in the app with http.  I'm using the ubuntu package named "libapache2-mod-wsgi", version 4.6.8-1ubuntu3.

Here's the relevant part of the haproxy config:

        http-request set-header X-Scheme https if { ssl_fc }
        http-request set-header X-Scheme http if !{ ssl_fc }
        http-request set-header X-Forwarded-Scheme https if { ssl_fc }
        http-request set-header X-Forwarded-Scheme http if !{ ssl_fc }
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
        http-request set-header X-Forwarded-HTTPS true if { ssl_fc }
        http-request set-header X-Forwarded-SSL true if { ssl_fc }
        http-request set-header X-HTTPS true if { ssl_fc }
        http-request set-header HTTP_X_FORWARDED_HTTPS true if { ssl_fc }

I added that last one because that's one of the things I found when I ran "strings" on the actual .so file for mod_wsgi.  I didn't actually expect it to work.

I did wonder whether my use of http/2 between haproxy and apache might be causing a problem, so I turned that off, with no change.

Any idea how I can get this working without needing double encryption?  I want the user connection to haproxy to be encrypted, but I would prefer that the backend connection be cleartext to lower CPU usage.  The communication is on localhost, so the entire system would have to be compromised for any sniffing to occur.

I tried adding various commands to the app code to properly set the environment variable to force https, without success.

**Comment by GrahamDumpleton** [comment]
For a start read:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html
* https://modwsgi.readthedocs.io/en/master/release-notes/version-4.4.9.html#new-features

and use settings talked about in it to set up properly what inbound headers you trust.

Those settings to say which headers you trust had a side effect that trigger some fixups required for proxy information to be injected properly into the WSGI application.

If still have an issue after using ``WSGITrustedProxyHeaders`` I would need to see the mod_wsgi configuration.

**Comment by elyograg** [comment]
Awesome!  I thought it might be a case of idiot user, and it was. :)

I added "WSGITrustedProxyHeaders X-Forwarded-For X-Forwarded-Proto" to the Apache config and now it magically works without HTTPS on the Apache side.  Thank you!

**Comment by GrahamDumpleton** [comment]
Definitely not an "idiot user" problem. More a case of hard to find information on what you need to do problem as although there exists the blog post and comments in release notes, that directive isn't described in main mod_wsgi documentation. :-(
