### ISSUE TITLE
Update from Python 3.5.0 to 3.6.6 build problem

### ISSUE THREAD

**Issue by sassi67** [GrahamDumpleton/mod_wsgi#703]
Hi all!
We have been using in our automated tests system this library successfully for more than two years with following releases:
Python: 3.5.0
Pip: 20.3.3
Pipenv: 2018.11.26 (the module is installed in a virtual env)
Apache: 2.4.18 / 2.4.20 on Linux x64
We want now to extend these tests on Windows, but we need to use Python 3.6.6 due to https://github.com/pypa/pip/issues/3055
The problem is that the upgrade is breaking the existing tests due to the fact that the wrong gcc path is used by the build (/opt/gcc-6.4.0 which does not exists in our development enviroments).
I was able to change the CC environment variable with the correct path (and this fixes the compilation of the sources), but I'm not able to fix the link.  
`    09:45:19.540 INFO  [PYTHON] -     /opt/gcc-9.1.0-visibility/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -fPIC -I/usr/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/python-DPTW_ujX/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/include/python3.6m -c src/server/wsgi_interp.c -o build/temp.linux-x86_64-3.6/src/server/wsgi_interp.o
    09:45:19.541 INFO  [PYTHON] -     /opt/gcc-9.1.0-visibility/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -fPIC -I/usr/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/python-DPTW_ujX/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/include/python3.6m -c src/server/wsgi_buckets.c -o build/temp.linux-x86_64-3.6/src/server/wsgi_buckets.o
    09:45:19.541 INFO  [PYTHON] -     /opt/gcc-9.1.0-visibility/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -fPIC -I/usr/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/python-DPTW_ujX/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/include/python3.6m -c src/server/wsgi_daemon.c -o build/temp.linux-x86_64-3.6/src/server/wsgi_daemon.o
    09:45:19.542 INFO  [PYTHON] -     /opt/gcc-9.1.0-visibility/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -fPIC -I/usr/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/python-DPTW_ujX/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/include/python3.6m -c src/server/wsgi_stream.c -o build/temp.linux-x86_64-3.6/src/server/wsgi_stream.o
    09:45:19.542 INFO  [PYTHON] -     /opt/gcc-9.1.0-visibility/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -fPIC -I/usr/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/python-DPTW_ujX/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/include/python3.6m -c src/server/mod_wsgi.c -o build/temp.linux-x86_64-3.6/src/server/mod_wsgi.o
    09:45:19.543 INFO  [PYTHON] -     src/server/mod_wsgi.c: In function ‘wsgi_socket_sendv’:
    09:45:19.544 INFO  [PYTHON] -     src/server/mod_wsgi.c:11011:46: warning: operand of ?: changes signedness from ‘int’ to ‘size_t’ {aka ‘long unsigned int’} due to unsignedness of other operand [-Wsign-compare]
    09:45:19.544 INFO  [PYTHON] -     11011 |                     (nvec < iov_max ? nvec : (int)iov_max));
    09:45:19.544 INFO  [PYTHON] -           |                                              ^~~~~~~~~~~~
    09:45:19.544 INFO  [PYTHON] -     src/server/mod_wsgi.c: In function ‘wsgi_scan_headers’:
    09:45:19.544 INFO  [PYTHON] -     src/server/mod_wsgi.c:11170:23: warning: operand of ?: changes signedness from ‘int’ to ‘long unsigned int’ due to unsignedness of other operand [-Wsign-compare]
    09:45:19.544 INFO  [PYTHON] -     11170 |     buflen = buffer ? buflen : sizeof(x);
    09:45:19.544 INFO  [PYTHON] -           |                       ^~~~~~
    09:45:19.544 INFO  [PYTHON] -     /opt/gcc-9.1.0-visibility/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -fPIC -I/usr/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/python-DPTW_ujX/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/include/python3.6m -c src/server/wsgi_metrics.c -o build/temp.linux-x86_64-3.6/src/server/wsgi_metrics.o
    09:45:19.544 INFO  [PYTHON] -     src/server/wsgi_metrics.c: In function ‘wsgi_request_metrics’:
    09:45:19.544 INFO  [PYTHON] -     src/server/wsgi_metrics.c:423:22: warning: variable ‘thread_info’ set but not used [-Wunused-but-set-variable]
    09:45:19.544 INFO  [PYTHON] -       423 |     WSGIThreadInfo **thread_info = NULL;
    09:45:19.544 INFO  [PYTHON] -           |                      ^~~~~~~~~~~
...
    09:45:19.553 INFO  [PYTHON] -     /opt/gcc-9.1.0-visibility/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -m64 -O3 -s -pthread -fPIC -fexceptions -m64 -gdwarf-2 -I/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/include -I/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c -fPIC -I/usr/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/python-DPTW_ujX/include -I/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/include/python3.6m -c src/server/wsgi_restrict.c -o build/temp.linux-x86_64-3.6/src/server/wsgi_restrict.o
    09:45:19.553 INFO  [PYTHON] -     /opt/gcc-6.4.0/bin/gcc -pthread -fPIC -fexceptions -m64 -gdwarf-2 -shared -Wl,-rpath,$ORIGIN,-rpath,$ORIGIN/../lib -static-libgcc -L/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/lib -L/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c/lib -m64 -L/home/jenkins/agent/46764666-298866388/.conan/data/openssl/1.1.1g.20200506100006/ci/stable/package/85d2d4223719c2c3ddd0a5f2c02e88f134bd4f07/lib -L/home/jenkins/agent/46764666-298866388/.conan/data/zlib/1.2.11.20200415111505/ci/stable/package/57457e08d5521c9c0f847624c2497698b079638c/lib build/temp.linux-x86_64-3.6/src/server/wsgi_interp.o build/temp.linux-x86_64-3.6/src/server/wsgi_buckets.o build/temp.linux-x86_64-3.6/src/server/wsgi_daemon.o build/temp.linux-x86_64-3.6/src/server/wsgi_stream.o build/temp.linux-x86_64-3.6/src/server/mod_wsgi.o build/temp.linux-x86_64-3.6/src/server/wsgi_metrics.o build/temp.linux-x86_64-3.6/src/server/wsgi_logger.o build/temp.linux-x86_64-3.6/src/server/wsgi_memory.o build/temp.linux-x86_64-3.6/src/server/wsgi_validate.o build/temp.linux-x86_64-3.6/src/server/wsgi_server.o build/temp.linux-x86_64-3.6/src/server/wsgi_thread.o build/temp.linux-x86_64-3.6/src/server/wsgi_apache.o build/temp.linux-x86_64-3.6/src/server/wsgi_convert.o build/temp.linux-x86_64-3.6/src/server/wsgi_restrict.o -L/home/jenkins/agent/46764666-298866388/.conan/data/python/3.6.6.20200506104111/ci/stable/build/c42ec664be5350866a88f0c3b18bb8ad80c8eb4a/install/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so -L/home/jenkins/agent/46764666-298866388/.conan/data/python/3.6.6.20200506104111/ci/stable/build/c42ec664be5350866a88f0c3b18bb8ad80c8eb4a/install/lib -L/home/alessandro/workspaces/agent/test/apache/build/tmp/pip_pip_6047766743559998130/python/lib/python3.6/config-3.6m-linux -lpython3.6m
    09:45:19.554 INFO  [PYTHON] -     unable to execute '/opt/gcc-6.4.0/bin/gcc': No such file or directory
    09:45:19.554 INFO  [PYTHON] -     error: command '/opt/gcc-6.4.0/bin/gcc' failed with exit status 1
`
Is there a way to force the linker to use the correct path?

**Comment by GrahamDumpleton** [comment]
For linker you can usually set ``LD`` environment variable, although am surprised it isn't using ``CC`` for it. If this doesn't work will need to dig into the Python config files to work out what variable it may use.

**Comment by GrahamDumpleton** [comment]
Did this suggestion solve the issue? If yes, please close the issue. Thanks.

**Comment by sassi67** [comment]
No way. But it's related to the environment variables we are pushing to the virtual environment. We are unpacking the whole procedure to see what happens step-by-step.
