### ISSUE TITLE
Wsgi configuration: "client denied by server configuration"

### ISSUE THREAD

**Issue by pitosalas** [GrahamDumpleton/mod_wsgi#706]
Graham, I don't want to take advantage of your helpfulness. I posted this on SO but I suspect that I won't get a useful answer so I am posting it here too. It is another very detailed question so hopefully you can find a moment to take a glance. Best, Pito Salas.

I am using mod_wsgi. All the app files, from the wsgi throughout the app are stored in /home/rpsalas/mydev/development/otproject and they all have group ownership of www-data. Apache is running as www-data. By putting in print statements I have proven that my __init__.py and wsgi.py both are executing. You can see that all the files have group rw permissions.

And yet, when I visit /test (which is the top of a trivial app for now, I get 

    "[Wed Aug 04 12:32:31.887657 2021] [authz_core:error] [pid 263311:tid 139654574315264] [client 129.64.46.138:57122] AH01630: client denied by server configuration: /home/rpsalas/mydev/development/otproject/otpflask/wsgi.py"

### Here are some more details:

* Ubuntu 20.04, Apache/2.4.41 (Ubuntu)
* Sites-avaialble/otproject.conf:

[![sites-available/otproject.conf][1]][1]

* Directory and ownerships

[![enter image description here][2]][2]

* __init__.py:

```
from flask import Flask
def create_app(config_filename):
    app = Flask(__name__)
    app.config.from_pyfile(config_filename)
    return app
```

* wsgi.py:

```
from otproject.otpflask import create_app
config = "config.development"
application = create_app(config) # call from wsgi server
```

  [1]: https://i.stack.imgur.com/ZL4ZV.png
  [2]: https://i.stack.imgur.com/1Q7NR.png

**Comment by GrahamDumpleton** [comment]
If on Apache 2.4, instead of:

```
    Order allow,deny
    Allow from all
```

you should really use:

```
    Require all granted
```

The older Apache 1.3/2.2 way of doing things isn't guaranteed to work unless you have ``mod_access_compat`` enabled.

Also, what do you get for:

```
    ls -lasd /home/rpsalas
```

It isn't enough that the project directory is accessible to the Apache user, all directories down to that also need to be accessible. You don't need to make them group ``www-data``, nor writable to that group, it just needs to be readable to others. It is common for home directories to not be readable/accessible to others.

**Comment by pitosalas** [comment]
Thanks! Your change to the <Directory> block did the trick. I looked like heck for documentation for that block, even what it does, but also what those options meant and could not find a thing! So appreciate the pointer.

As for your second point, the directories were already set up for world read. So all my machinations with www-data were unnecessary!.

Thank you thank you thank you. If you had a tip jar for wsgi I would be tipping!
