### ISSUE TITLE
Incorrect processing of unicode strings when logging to stderr

### ISSUE THREAD

**Issue by artcom-net** [GrahamDumpleton/mod_wsgi#713]
Good time!

If I try to write a unicode string to stderr, i get a string of bytes instead of normal characters.
What was I trying to do:

- setting variables such as LANG and LC_ALL in /etc/apache2/envvars;
- set the lang and locale parameters for WSGIDaemonProcess;
- runtime encodings were checked - all UTF-8 including stderr and stdout streams.

**mod_wsgi version:** 4.5.11
app.wsgi:
```
def application(environ, start_response):
    sys.stderr.write('Какая-то строка')

    status = '200 OK'
    output = b''
    response_headers = [
        ('Content-type', 'text/plain'),
        ('Content-Length', str(len(output)))
    ]
    start_response(status, response_headers)
    return [output]
```
vhost.conf:
``` 
<VirtualHost *:8081>
    ServerName service.local
    DocumentRoot /var/www/service
    
    WSGIDaemonProcess service lang=ru_RU.UTF-8 locale=ru_RU.UTF-8 user=www-data group=www-data processes=2 threads=15 python-path=/var/www/service 
    WSGIProcessGroup service
    WSGIScriptAlias / /var/www/service/app.wsgi
    WSGIScriptReloading On
    WSGIPassAuthorization On

    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Headers "Authorization, Content-Type"
    Header always set Access-Control-Expose-Headers "Content-Type, Content-Disposition"
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS"

    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]

    <Directory /var/www/service>
        Require all granted
    </Directory>
   
    LogLevel warn 
    ErrorLogFormat "%M"
    ErrorLog ${APACHE_LOG_DIR}/service.log
    CustomLog ${APACHE_LOG_DIR}/service_access.log combined
</VirtualHost>
```
service.log:
``` 
\xd0\x9a\xd0\xb0\xd0\xba\xd0\xb0\xd1\x8f-\xd1\x82\xd0\xbe \xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd0\xba\xd0\xb0
```
This may have been fixed in subsequent versions but I didn't find it in the change logs.

**Comment by GrahamDumpleton** [comment]
When you write to stdout/stderr, it actually gets sent through the Apache logging functions. The Apache logging functions will convert anything that is not ASCII to escaped byte codes. That just how Apache works and nothing that can be done about it.

Suggest using the Python logger module and set up an output source for it which sends logged output using the logger API to a separate file instead if formatting is important.

Note that Apache error log functions will also truncate lines at about 8000 characters as well. So again, if capturing everything correctly is important, use the Python logger module and send it to a separate file.

**Comment by artcom-net** [comment]
Initially, I used logging to a separate file via `logging`, but there was a potential problem with data race if multiple processes are used. I thought to solve this by delegating Apache to write a log and ran into this problem.
Apparently I will have to abandon formatting.
Thanks for your reply.

**Comment by GrahamDumpleton** [comment]
Ahh yes, was going to mention the multi process writer problem with logging module but thought that might complicate things. As far as I know there isn't a good solution for that except to have logger send data to a central logging system which then writes to files.

**Comment by GrahamDumpleton** [comment]
The docs at https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes do have example code of setting up a central logging receiver.

**Comment by artcom-net** [comment]
Thank you, the question is closed.
