### ISSUE TITLE
undefined symbol: forkpty

### ISSUE THREAD

**Issue by Muxelmann** [GrahamDumpleton/mod_wsgi#719]
## undefined symbol: forkpty

On a Raspberry Pi, I am trying to serve a [flask](https://flask.palletsprojects.com/) instance with [virtualenv](https://github.com/pypa/virtualenv) (with Python 3.9.7) through apache2. The folder structure of my project looks something like this:

```
/var/www/mysite
├── src
│   ├── __init__.py
│   └── ...
├── launch.py
├── launch.wsgi -> launch.py
└── venv
    └── ...
```

I ran `pip install mod-wsgi` and configured the apache conf file like so:

```apache
LoadModule wsgi_module "/var/www/mysite/venv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-arm-linux-gnueabihf.so"
WSGIPythonHome "/var/www/mysite/venv"

<VirtualHost *:80>
    ServerName mysite.com
    ServerAdmin admin@mysite.com

    WSGIDaemonProcess mysite user=www-data group=www-data threads=3 python-home=/var/www/mysite/venv
    WSGIScriptAlias / /var/www/mysite/launch.wsgi process-group=mysite application-group=%{GLOBAL}

    <Directory /var/www/mysite/src/>
        Order allow,deny
        Allow from all
    </Directory>

    Alias /static /var/www/mysite/src/static
    <Directory /var/www/mysite/src/static/>
        Order allow,deny
        Allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

apache cannot reload and instead, the following error is logged in `/var/log/syslog`:

```
Sep 30 18:14:07 raspberrypi apachectl[31844]: apache2: Syntax error on line 226 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/sites-enabled/mysite.conf: Cannot load /var/www/mysite/venv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-arm-linux-gnueabihf.so into server: /var/www/mysite/venv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-arm-linux-gnueabihf.so: undefined symbol: forkpty
```

## Workaround

I had a look into the `undefined symbol: forkpty` error and found [this](https://superuser.com/questions/1311818/installed-mod-wsgi-on-debian-with-pip-and-got-undefined-forkpty-error) discussion and [this](https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html#undefined-forkpty-on-fedora-7) mention of the error in fedora. From the discussion I learnt that the makefile can be configured to use the local (i.e. my venv) python copy. So I tried compiling `mod_wsgi.so` locally like this:

```bash
cd /var/www/mysite
wget https://github.com/GrahamDumpleton/mod_wsgi/archive/refs/tags/4.9.0.tar.gz
tar xzf 4.9.0.tar.gz
cd mod_wsgi-4.9.0/
./configure --with-python=/var/www/mysite/venv/bin/python3.9
make
```

Then I changed the `LoadModule` in the apache config file like so:

```apache
LoadModule wsgi_module "/var/www/mysite/mod_wsgi-4.9.0/src/server/.libs/mod_wsgi.so"
```

Now, apache reloads and can serve the site just find. However, it would be more comfortable (and easier to maintain) to just use pip version, instead of having to download and compile the latest version manually. Any idea how to resolve this issue?

Many thanks, and I hope the above helped a tiny bit.

**Comment by GrahamDumpleton** [comment]
The `forkpty()` system function is on Linux usually defined in `libutil.so`. It looks for some reason like the Python library on that platform doesn't link with that library as usually would be the case and nor does it list the library to be linked when creating Python extensions. When using `Makefile` method of building, the Apache configuration when building Apache modules though is likely linking it and so the symbol is present. I haven't seen this issue arise for a very very very very long time, but the issue is documented in:

* https://modwsgi.readthedocs.io/en/master/user-guides/installation-issues.html?highlight=forkpty#undefined-forkpty-on-fedora-7

What you can try and do is when using `pip install` method is to set `LDLIBS` environment variable building the extension.

```
LDLIBS=-lutil pip install --no-cache-dir -U mod_wsgi
```

Note that it is important to use `--no-cache-dir` else it will use build artefacts from prior built attempt.

Another option is to find where the `libutil.so` library is located on the system, and before where the `LoadModule` line is for mod_wsgi add:

```
LoadFile /usr/lib64/libutil.so
```

Change the path for the `.so` file as necessary.

So this is arguably ultimately a problem with how the Python version on that system was configured when installed. Is that the system Python, or your own custom Python installation?

**Comment by Muxelmann** [comment]
## New error

The Python version used is not the system's, but a version installed through `pyenv`. Nonetheless, I found `libutil.so` on the Raspberry Pi and included it in the config file like so:

```
LoadFile /usr/lib/arm-linux-gnueabihf/libutil.so
```

The forkpty error is now gone, but replaced by this error:

```
Cannot load /var/www/mysite/venv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-arm-linux-gnueabihf.so into server: /var/www/mysite/venv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-arm-linux-gnueabihf.so: undefined symbol: sincos
```

I guess `sincos` is part of the math library, so I wondered if it's not correctly linked. I tried adding the `-lm` flag using `LDLIBS=-lm` when installing `mod_wsgi` without cache, but this yielded no success. Manually loading math libraries manually using `LoadFile` in the apache config file seems to result in a chain, which I didn't want to - it appears more logical that the libraries are linked correctly during build time.

## Remark

That said, I was trying to get mod_wsgi to work with Python 3.9.7, but the `setup.py` suggests it's only compatible with versions up to 3.8.x. So I installed 3.8.12 and tried again:

```bash
pyenv install 3.8.12
pyenv local 3.8.12
pip install --upgrade pip
pip install virtualenv
cd /var/www/mysite
rm -r venv
python -m virtualenv venv
source venv/bin/activate
pip install flask mod_wsgi
```

Then I changed the apache config file to start with this:

```apache
LoadModule wsgi_module /var/www/mysite/venv/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-arm-linux-gnueabihf.so
```

...but with no success. Even when including the `libutil.so` like was done with version 3.9.7 resulted in the same missing `sincos` error.

**Comment by GrahamDumpleton** [comment]
Do you have to use `pyenv`? Unless they changed it, it doesn't produce shared libraries by default for Python which will just result in lots of problems. Ensure first that `pyenv` is creating shared libraries for Python. I raised this as a problem many years ago and suggested they add something to the docs to explain how to make it properly create Python shared libraries, but they didn't want to do it themselves and expected patches to be supplied so it was never done as far as I know.

What do you get one when you run:

```
ldd /var/www/mysite/venv/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-arm-linux-gnueabihf.so
```

If that doesn't show a dependency on a Python shared library then it would confirm they still aren't creating shared libraries for Python, which means it cannot be used in embedded systems which dynamically load code dependent on Python.

Try using the system Python instead.

**Comment by Muxelmann** [comment]
The output I get is:

```bash
ldd /var/www/mysite/venv/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-arm-linux-gnueabihf.so
	linux-vdso.so.1 (0x7ee68000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x76bec000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76bc2000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76a74000)
	/lib/ld-linux-armhf.so.3 (0x76f1f000)
```

Does this help?

The system's version is 2.7.16, which won't work for me anymore. I guess for the time being, I'll just stick to configure mod-wsgi with the `--with-python` flag and compile it manually.

**Comment by GrahamDumpleton** [comment]
No Python shared library. You need to tell pyenv to create a shared library. See:

* https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared

**Comment by Muxelmann** [comment]
Thanks for the tip. I tried reinstalling Python 3.9.7 and 3.8.12 with pyenv using the `--enable-shared` flag. When installing mod_wsgi the shared dependencies are:

```bash
ldd /var/www/mysite/venv/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-arm-linux-gnueabihf.so
	linux-vdso.so.1 (0x7efd0000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x76ed7000)
	libpython3.8.so.1.0 => /home/pi/.pyenv/versions/3.8.12/lib/libpython3.8.so.1.0 (0x76c06000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76bdc000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76a8e000)
	/lib/ld-linux-armhf.so.3 (0x76f33000)
	libcrypt.so.1 => /lib/arm-linux-gnueabihf/libcrypt.so.1 (0x76a4e000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76a3b000)
	libutil.so.1 => /lib/arm-linux-gnueabihf/libutil.so.1 (0x76a28000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x769a6000)
```

and

```bash
ldd /var/www/mysite/venv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-arm-linux-gnueabihf.so 
	linux-vdso.so.1 (0x7ef3f000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x76f60000)
	libpython3.9.so.1.0 => /home/pi/.pyenv/versions/3.9.7/lib/libpython3.9.so.1.0 (0x76c62000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76c38000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76aea000)
	/lib/ld-linux-armhf.so.3 (0x76fbc000)
	libcrypt.so.1 => /lib/arm-linux-gnueabihf/libcrypt.so.1 (0x76aaa000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76a97000)
	libutil.so.1 => /lib/arm-linux-gnueabihf/libutil.so.1 (0x76a84000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76a02000)
```

It now works! Thank you so much for the support

## Summary

The steps I followed are as follows:

```bash
# See: https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.7

# Change to the installed Python version and create venv folder
pyenv local 3.9.7
pip install --upgrade pip
pip install virtualenv
cd /var/www/mysite
python -m virtualenv venv

# Activate the virtual environment and install Flask and mod_wsgi
source venv/bin/activate
pip install flask
# See: https://github.com/GrahamDumpleton/mod_wsgi/issues/719#issuecomment-931794196
LDLIBS=-lutil pip install --no-cache-dir -U mod_wsgi
```

The resultant library was included in the Apache configuration file like so:

```apache
LoadModule wsgi_module /var/www/mysite/venv/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-arm-linux-gnueabihf.so
```

This way, I was able to install mod_wsgi in a virtual environment of Python 3.9.7 installed through pyenv, and use that version of mod_wsgi with Apache. Maybe these steps are of use for anybody else also struggling with a similar problem.
