### ISSUE TITLE
Apache and mod_wsgi, worker process stuck to W state, request never dies.

### ISSUE THREAD

**Issue by m0hammadhossein** [GrahamDumpleton/mod_wsgi#722]
I am running Apache 2.4.51 with mod_wsgi, Python 3.10 but request never dies and waiting for response.
I do not have this problem with Python 3.9.7

python3.10
apache 2.4.51
Django 3.2.8

**Comment by nomed4** [comment]
Thanks!!! I suffered for three days ... It helped !!!!!
