### ISSUE TITLE
mod_wsgi (pid=2401): Target WSGI script 'wsgi.py' cannot be loaded as Python module. RuntimeError: populate() isn't reentrant

### ISSUE THREAD

**Issue by fspider** [GrahamDumpleton/mod_wsgi#723]
hi. I am having issue with running Django project. Please help me!
Here is log file.
Thank you!

Ubuntu + Apache2
WSGI version:
ii  libapache2-mod-wsgi-py3               4.5.17-1ubuntu1                            amd64        Python 3 WSGI adapter module for Apache

**Comment by rhertzog** [comment]
I had a similar issue where I would get weird errors from psycopg2 that resulted in the same Django initialization error and adding `WSGIApplicationGroup %{GLOBAL}` to the apache configuration helped ... though I have no idea why, in my case I was using mod_wsgi 4.7.1 from Debian 11 (bullseye): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994040

For reference my configuration looked like this:
```
# In the server config
WSGIDaemonProcess tracker.debian.org user=qa group=qa python-path=/srv/tracker.debian.org/di
stro-tracker processes=4 threads=5 maximum-requests=5000 inactivity-timeout=1800 umask=0007 
display-name=wsgi-tracker.debian.org
# In the vhost config
WSGIScriptAlias / /srv/tracker.debian.org/distro-tracker/distro_tracker/project/wsgi.py
WSGIProcessGroup tracker.debian.org
```

(No venv involved here, plain system python3.9 with system-wide modules and django project in the python-path defined)

**Comment by GrahamDumpleton** [comment]
No followup from OP, closing.
