### ISSUE TITLE
Centos 7 Django in Apache python3-mod_wsgi ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by TristanTTran** [GrahamDumpleton/mod_wsgi#725]
I know there are many thread in the distant past with this same error messages, and with proposed solutions. Somehow none of those works for me.

My OS: Centos 7 on AWS EC2, version 7.9.2009
httpd version: 2.4.6
mod_wsgi version: 4.7.1 (installed by ```sudo yum install python3-mod_wsgi```)
Django version: 3.2.8 (installed at this location ```/home/proj/myapp/``` by 
```
pipenv shell
  pip install django==3.2.8`
```

I have seen the following posts on similar issues and solutions (and tried them out).
https://github.com/GrahamDumpleton/mod_wsgi/issues/305
https://github.com/GrahamDumpleton/mod_wsgi/issues/308
and a few similar Stackoveflows thread.

This is the error I see in log file:
```
[Tue Oct 19 22:40:52.342162 2021] [wsgi:error] [pid 2792] [remote 10.1.44.45:65513] mod_wsgi (pid=2792): Failed to exec Python script file '/home/centos/proj/myapp/myapp/wsgi.py'.
[Tue Oct 19 22:40:52.342275 2021] [wsgi:error] [pid 2792] [remote 10.1.44.45:65513] mod_wsgi (pid=2792): Exception occurred processing WSGI script '/home/centos/proj/myapp/myapp/wsgi.py'.
[Tue Oct 19 22:40:52.342484 2021] [wsgi:error] [pid 2792] [remote 10.1.44.45:65513] Traceback (most recent call last):
[Tue Oct 19 22:40:52.342501 2021] [wsgi:error] [pid 2792] [remote 10.1.44.45:65513]   File "/home/centos/proj/myapp/myapp/wsgi.py", line 17, in <module>
[Tue Oct 19 22:40:52.342504 2021] [wsgi:error] [pid 2792] [remote 10.1.44.45:65513]     from django.core.wsgi import get_wsgi_application
[Tue Oct 19 22:40:52.342516 2021] [wsgi:error] [pid 2792] [remote 10.1.44.45:65513] ModuleNotFoundError: No module named 'django'
```

Here is my ```/home/centos/proj/myapp/myapp/wsgi.py```

```
import os, sys

sys.path.append('/home/centos/proj/myapp/myapp')
sys.path.append('/home/centos/.local/share/virtualenvs/myapp-8BiokhAz/lib/python3.6/site-packages')

#import requests (will explain this below)

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myapp.settings')

application = get_wsgi_application()
```

The two ```sys.path.append``` statements above are to implement a solution here https://stackoverflow.com/questions/14927345/importerror-no-module-named-django-core-wsgi-apache-virtualenv-aws-wsgi

I inserted ```import requests``` above to test a hypothesis that: this file does not seem to call or read anything from the ```.../site_packages/``` path. It is clear that, not just module ```django``` is not sought here, any python modules that are installed by ```pip install ...``` in the ```pipenv``` environment are not reached.

Please, someone help. Why is Apache not reading this ```site_packages``` folder. I don't have any permission-related errors (already solved them).

**Comment by TristanTTran** [comment]
Below is the virtual host config. I set up SSL self-signed cert. So my django config is included in this same file ```/etc/httpd/conf.d/ssl.conf``` :

```
<VirtualHost _default_:443>
    DocumentRoot "/home/centos/proj/myapp"
    ServerName myapp_dns:443

    Alias /static /home/centos/proj/myapp/static
    <Directory /home/centos/proj/myapp/static>
        Require all granted
    </Directory>

    <Directory "/home/centos/proj/myapp/myapp">
        <Files wsgi.py>
              Require all granted
         </Files>
    </Directory>
    WSGIDaemonProcess myapp python-path=/home/centos/proj/myapp:/home/centos/.local/share/virtualenvs/myapp- 
                 8BiokhAz/lib/python3.6/site-packages
    WSGIProcessGroup myapp
    WSGIScriptAlias / /home/centos/proj/maypp/myapp/wsgi.py

ErrorLog logs/ssl_error_log
TransferLog logs/ssl_access_log
LogLevel warn

SSLEngine on
SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key

<Files ~ "\.(cgi|shtml|phtml|php3?)$">
    SSLOptions +StdEnvVars
</Files>
<Directory "/var/www/cgi-bin">
    SSLOptions +StdEnvVars
</Directory>

BrowserMatch "MSIE [2-5]" \
         nokeepalive ssl-unclean-shutdown \
         downgrade-1.0 force-response-1.0

CustomLog logs/ssl_request_log \
          "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

</VirtualHost>

```

Below is the content of ```/etc/selinux/config```
```
SELINUXTYPE=targeted
SELINUX=permissive
```

Running ```sestatus``` gives:
```
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```

Running ```ls -lasd /home/centos``` gives:
```
0 drwx--x--x. 9 centos centos 238 Oct 19 23:05 /home/centos
```

Python virtual environment: I installed ```pipenv``` with ```pip3```. ```pip3``` is linked to the system Python 3.6.8. and The version for ```pipenv``` is ```pipenv==2021.5.29```. The enviroment is activated with:
```
~/proj/myapp/$ pipenv shell
```

The path to the virtual environment is:
```
/home/centos/.local/share/virtualenvs/myapp-8BiokhAz/
/home/centos/.local/share/virtualenvs/myapp-8BiokhAz/lib/python3.6/site-packages
```

**Comment by GrahamDumpleton** [comment]
No idea about `pipenv`.

Couple of notes.

Instead of:

```
sys.path.append('/home/centos/proj/myapp')
sys.path.append('home/centos/proj/myapp/myappenv/lib/python3.6/site-pakages')
```

add to the ``WSGIDaemonProcess`` directive a  `python-path` option for the first path.

```
WSGIDaemonProcess myapp python-home=/home/centos/proj/myapp/myappenv \
  python-path=/home/centos/proj/myapp
```

You don't need the second line referencing the `site-packages` directory.

Since using daemon mode of mod_wsgi, good idea to disable embedded mode by adding outside of the `VirtualHost`:

```
WSGIRestrictEmbedded On
```

**Comment by TristanTTran** [comment]
Thanks for the help. Closing this.
