### ISSUE TITLE
not able to import swagger_server when using mod_wsgi

### ISSUE THREAD

**Issue by Ragzz1995** [GrahamDumpleton/mod_wsgi#727]
When trying to use mod_wsgi with swagger generated python flask server, not able to import "swagger_server"

**Comment by GrahamDumpleton** [comment]
These are the usual reasons.

* Where you have generated the code is not on the Python module search path. You need to tell mod_wsgi where any code is that you want it to be able to import.
* The Python module search path has been set, but the Apache server user cannot access the directory path and/or the directories/files under that path.

Without further information such as the full directory path to where the generated code exists, and how you have configured Apache for mod_wsgi, that is all I can suggest.

**Comment by Ragzz1995** [comment]
Project structure

git
|______ ll (swagger generated python-flask server application)
|______ wsgi_scripts
...........|___ yourapp.wsgi






[httpd.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7452357/httpd.conf.txt)
[yourapp.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7452362/yourapp.conf.txt)
[yourapp.wsgi.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7452370/yourapp.wsgi.txt)

**Comment by GrahamDumpleton** [comment]
You are not adding the directory:

```
C:/Users/INRAKAN11/Downloads/git
```

to the Python module search path so if the ``swagger_server`` package is located at:

```
C:/Users/INRAKAN11/Downloads/git/swagger_server
```

as seems to be the case, it will not find it.

In other words, the parent directory of ``swagger_server`` needs to be added to the Python module search path.

**Comment by Ragzz1995** [comment]
Thank you very much. It is resolved now. Thanks for being patient.
