### ISSUE TITLE
How does mod_wsgi multi thread model actually work?

### ISSUE THREAD

**Issue by demonguy** [GrahamDumpleton/mod_wsgi#73]
Details are here: http://stackoverflow.com/questions/29062549/how-does-mod-wsgi-actually-work

I just can't understand multiple thread in mod_wsgi.

**Comment by GrahamDumpleton** [comment]
Please use the mod_wsgi mailing list for such a question.

* http://code.google.com/p/modwsgi/wiki/WhereToGetHelp?tm=6

The bug tracker is not the place for discussions.
