### ISSUE TITLE
Possible bug using X-Forwarded-Port

### ISSUE THREAD

**Issue by dreua** [GrahamDumpleton/mod_wsgi#731]
I had some issues with an nginx-proxy setting `proxy_set_header X-Fowarded-Port`, pgadmin4-web using mod_wsgi and a non standard port which makes me wonder whether the following struct lacks `HTTP_X_FORWARDED_PORT` on purpose or if that may actually be an error causing the buggy behavior I'm seeing. Could you have a look?

https://github.com/GrahamDumpleton/mod_wsgi/blob/df9faf954a1ab6208f45ba6fde90f0b41f605483/src/server/mod_wsgi.c#L13595-L13603

However, `X-Forwarded-Port` is used later in that file:
https://github.com/GrahamDumpleton/mod_wsgi/blob/df9faf954a1ab6208f45ba6fde90f0b41f605483/src/server/mod_wsgi.c#L13918-L13924

Thanks to a comment in that file I found a workaround: `proxy_set_header X-Forwarded-Host $host:5001;`

**Comment by GrahamDumpleton** [comment]
Can you explain what the original problem was that you had?

Those arrays such as ``wsgi_proxy_scheme_headers`` are only relevant for where there are multiple headers for the same purpose. They record all the alternate names related to one purpose. There is only the one known of header for passing the port, so it wasn't necessary to have it listed in an array of aliases for that purpose.

Also be aware that what mod_wsgi only helps for WSGI applications. If Apache itself does something such as a redirection it can still use the wrong details. This can happen in some circumstances with directory redirection when hosting static files from memory. Also, default error pages from Apache will also show the wrong information.

For more details and explanation of limitations have a read of:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

**Comment by dreua** [comment]
The original problem was, that pgadmin4-web didn't recognize setting `proxy_set_header X-Fowarded-Port 5001;` in the nginx proxy, but it works when the port is included in the host, e.g. `proxy_set_header X-Forwarded-Host $host:5001;`.

Thanks for explaining the arrays to me, it just looked suspicious to me and I didn't really understand the code, sorry about that.
With that in mind I no longer assume that this is mod_wsgi's fault, it's equally likely a bug in pgadmin-web or its apache configuration. Thank you for your time!
