### ISSUE TITLE
Add documentation for Configuration/WSGITrustedProxyHeaders

### ISSUE THREAD

**Issue by dreua** [GrahamDumpleton/mod_wsgi#733]
WSGITrustedProxyHeaders is documented only in the release notes for [version 4.4.9](https://modwsgi.readthedocs.io/en/master/release-notes/version-4.4.9.html#new-features) but I think it deserves its own documentation.

**Comment by GrahamDumpleton** [comment]
Docs were added related to this recently.

* https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGITrustedProxyHeaders.html
