### ISSUE TITLE
ERROR: Failed building wheel for mod-wsgi

### ISSUE THREAD

**Issue by Poojaerelli** [GrahamDumpleton/mod_wsgi#736]
I'm trying to install mod_wsgi through pip using the command 'pip install mod-wsgi'. But I'm getting one error called 'error: command 'cl.exe' failed: No such file or directory'. I don't know why it is throwing this error, I tried unistalling and reinstalling visual studio and Apache as well, I created separate venv also but nothing worked.

My system is windows 10 (64 bit)
I installed:
Visual studio 2019
Microsoft build C++ tools version 14
Apache 2.4.51 (64 bit)
python 3.7.9 (64 bit)

Below is the complete error message I'm getting, please do help me in this..

Collecting mod-wsgi
  Using cached mod_wsgi-4.9.0.tar.gz (497 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mod-wsgi
  Building wheel for mod-wsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\pooja\pythonprojects\mod_wsgi\wsgivenv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\POOJA~1\\AppData\\Local\\Temp\\pip-install-3ejg7r0q\\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\\setup.py'"'"'; __file__='"'"'C:\\Users\\POOJA~1\\AppData\\Local\\Temp\\pip-install-3ejg7r0q\\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\POOJA~1\AppData\Local\Temp\pip-wheel-11j71rq5'
       cwd: C:\Users\POOJA~1\AppData\Local\Temp\pip-install-3ejg7r0q\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\mod_wsgi
  copying src\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi
  creating build\lib.win-amd64-3.7\mod_wsgi\server
  copying src\server\apxs_config.py -> build\lib.win-amd64-3.7\mod_wsgi\server
  copying src\server\environ.py -> build\lib.win-amd64-3.7\mod_wsgi\server
  copying src\server\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server
  creating build\lib.win-amd64-3.7\mod_wsgi\server\management
  copying src\server\management\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management
  creating build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
  copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
  creating build\lib.win-amd64-3.7\mod_wsgi\docs
  copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\docs
  creating build\lib.win-amd64-3.7\mod_wsgi\images
  copying images\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\images
  copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.7\mod_wsgi\images
  running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\server
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\Apache24/include -Ic:\users\pooja\pythonprojects\mod_wsgi\wsgivenv\include -IC:\Users\pooja\AppData\Local\Programs\Python\Python37\include -IC:\Users\pooja\AppData\Local\Programs\Python\Python37\include /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.7\Release\src/server\mod_wsgi.obj
  error: command 'cl.exe' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
    Running setup.py install for mod-wsgi ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\pooja\pythonprojects\mod_wsgi\wsgivenv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\POOJA~1\\AppData\\Local\\Temp\\pip-install-3ejg7r0q\\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\\setup.py'"'"'; __file__='"'"'C:\\Users\\POOJA~1\\AppData\\Local\\Temp\\pip-install-3ejg7r0q\\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\POOJA~1\AppData\Local\Temp\pip-record-5muh2au4\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\pooja\pythonprojects\mod_wsgi\wsgivenv\include\site\python3.7\mod-wsgi'
         cwd: C:\Users\POOJA~1\AppData\Local\Temp\pip-install-3ejg7r0q\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\mod_wsgi
    copying src\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi
    creating build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\apxs_config.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\environ.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    copying src\server\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server
    creating build\lib.win-amd64-3.7\mod_wsgi\server\management
    copying src\server\management\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management
    creating build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\runmodwsgi.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    copying src\server\management\commands\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\server\management\commands
    creating build\lib.win-amd64-3.7\mod_wsgi\docs
    copying docs\_build\html\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\docs
    creating build\lib.win-amd64-3.7\mod_wsgi\images
    copying images\__init__.py -> build\lib.win-amd64-3.7\mod_wsgi\images
    copying images\snake-whiskey.jpg -> build\lib.win-amd64-3.7\mod_wsgi\images
    running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\server
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\Apache24/include -Ic:\users\pooja\pythonprojects\mod_wsgi\wsgivenv\include -IC:\Users\pooja\AppData\Local\Programs\Python\Python37\include -IC:\Users\pooja\AppData\Local\Programs\Python\Python37\include /Tcsrc/server\mod_wsgi.c /Fobuild\temp.win-amd64-3.7\Release\src/server\mod_wsgi.obj
    error: command 'cl.exe' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\pooja\pythonprojects\mod_wsgi\wsgivenv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\POOJA~1\\AppData\\Local\\Temp\\pip-install-3ejg7r0q\\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\\setup.py'"'"'; __file__='"'"'C:\\Users\\POOJA~1\\AppData\\Local\\Temp\\pip-install-3ejg7r0q\\mod-wsgi_e1f6c95e1a684a2a845c8027ded4eedf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\POOJA~1\AppData\Local\Temp\pip-record-5muh2au4\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\pooja\pythonprojects\mod_wsgi\wsgivenv\include\site\python3.7\mod-wsgi' Check the logs for full command output.

**Comment by GrahamDumpleton** [comment]
All I can say is that MS compiler isn't installed so user can use it, or you are attempting to do the build from Windows command shell which isn't picking up the environment for MS compiler correctly so can find it. I don't know if is still available, but Visual Studio used to provide a menu option for creating a command shell which was guaranteed to setup the environment correctly so MS compiler would be found. If that doesn't help, you will need to ask on an appropriate Windows forum or StackOverflow as I don't know enough about Windows to help.

**Comment by Poojaerelli** [comment]
Thanks for your reply, I tried using developer command prompt of visual studio also, but same error I'm getting. Anyways I'll try in other community, thanks for the suggestion.
