### ISSUE TITLE
 HTTPS request fails with hostname specified in ServerAlias

### ISSUE THREAD

**Issue by yaskravi** [GrahamDumpleton/mod_wsgi#738]
HTTPS request fails with hostname specified in ServerAlias with the following error in a log file.
```
sudo tail -f /var/log/httpd/ssl_error_log
[Sun Nov 28 19:26:01.115135 2021] [autoindex:error] [pid 4712:tid 140646522271488] [client 45.132.92.135:53043] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
```

While HTTPS request to the hostname specified in ServerName works fine.

Request to _https://www.example.com_ returns "HTTP SERVER TEST PAGE" while the request to _https://example.com_ returns a valid response from the django application.

```
$hostname
example.com
$ httpd -v
Server version: Apache/2.4.37 (centos)
Server built:   Nov 12 2021 04:57:27
$ cat /etc/centos-release
CentOS Linux release 8.3.2011
$ rpm -qa | grep wsgi
python3-mod_wsgi-4.6.4-4.el8.x86_64
```

### Vhost config files
HTTP
```
$ cat /etc/httpd/sites-available/example.conf
<VirtualHost *:80>
        ServerName example.com
        ServerAlias www.example.com

RewriteEngine on
RewriteCond %{SERVER_NAME} =example.com [OR]
RewriteCond %{SERVER_NAME} =www.example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```
HTTPS
```
$ cat /etc/httpd/sites-available/example.com-le-ssl.conf
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName example.com
        ServerAlias www.example.com

        ServerAdmin webmaster@localhost
#        DocumentRoot /var/www/html

        ErrorLog /var/log/httpd/error.log
        CustomLog /var/log/httpd/access.log combined

        WSGIScriptAlias / /home/john/site_repo/wsgi.py
        WSGIDaemonProcess django_app python-path=/home/john/site_repo python-home=/home/john/site                                                                                                                         
        WSGIProcessGroup django_app                                                                                                                                                                                      
        WSGIApplicationGroup %{GLOBAL}


        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/www.example.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/www.example.com/privkey.pem
</VirtualHost>

</IfModule>
```

It is worth mentioning that the same configuration works fine with Apache2 + mod_wsgi on Ubuntu 20.04

**Comment by GrahamDumpleton** [comment]
Double check you don't have another site file for www.example.com. Look in both sites-available and sites-enabled in case you managed to break symlink association and have an actual copy of a file in sites-enabled rather than the symlink to sites-available.

BTW, your config is wrong for mod_wsgi. You have defined WSGIDaemonProcess but haven't told mod_wsgi to actually delegate the WSGI application to it. You need either WSGIProcessGroup directive or process-group option to WSGIScriptAlias. It is also recommended you force the use of the main Python interpreter context by setting WSGIApplicationGroup directive appropriately.

**Comment by yaskravi** [comment]
```
$ sudo  ls -laht /etc/httpd/sites-available/
total 8.0K
drwxr-xr-x. 2 root root   61 Nov 28 20:44 .
drwxr-xr-x. 7 root root  149 Nov 28 20:44 ..
-rw-r--r--  1 root root 1.3K Nov 28 20:44 example.com-le-ssl.conf
-rw-r--r--  1 root root  271 Nov 28 20:40 example.com.conf
```

```
$  sudo ls -laht /etc/httpd/sites-enabled/
total 0
drwxr-xr-x. 7 root root 149 Nov 28 20:44 ..
drwxr-xr-x. 2 root root  61 Nov 28 20:41 .
lrwxrwxrwx  1 root root  50 Nov 28 20:41 example.com-le-ssl.conf -> /etc/httpd/sites-available/example.com-le-ssl.conf
lrwxrwxrwx  1 root root  43 Nov 28 14:37 example.com.conf -> /etc/httpd/sites-available/example.com.conf
```

I missed 2 lines while copying. I have the following WSGI settings in my config file

```
cat etc/httpd/sites-available/example.com-le-ssl.conf
...
        WSGIScriptAlias / /home/john/site_repo/wsgi.py
        WSGIDaemonProcess monad_app python-path=/home/john/site_repo python-home=/home/john/site         
        WSGIProcessGroup django_app
        WSGIApplicationGroup %{GLOBAL}
...
```

**Comment by GrahamDumpleton** [comment]
Probably a typo, but the argument to WSGIDaemonProcess and WSGIProcessGroup don't match.

Next thing to do is ensure that IP address returned by hosts/DNS for www.example.com and example.com are actually the same.

**Comment by yaskravi** [comment]
Yes, it is a typo in WSGIDaemonProcess argument.
Both www.example.com and example.com have the same IP address.

**Comment by GrahamDumpleton** [comment]
Use `curl -v` to make the request and see what it outputs.

Because your rewrite rule has:

```
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

That is, `permanent`, maybe the browser has cached an old redirect target.

**Comment by yaskravi** [comment]
```
curl -v https://www.example.com 2>www.example.txt
curl -v https://example.com 2>example.txt
```
[www.example.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7618331/www.example.txt)
[example.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7618332/example.txt)

It is worth mentioning that with HTTP(when SSL is not enabled) both http://example.com and http://www.example.com work fine. And the site is available both with domain and www subdomain.

**Comment by GrahamDumpleton** [comment]
Do you use `Require all granted` in the non SSL VirtualHost?

**Comment by yaskravi** [comment]
My vhosts configuration files for configuration with HTTP and HTTPS specified in the [issue description](https://github.com/GrahamDumpleton/mod_wsgi/issues/738#issue-1065417980)

Configuration with HTTP only specified in the last [comment](https://github.com/GrahamDumpleton/mod_wsgi/issues/738#issuecomment-981626914)

**Comment by GrahamDumpleton** [comment]
No I mean curl http when you have redirect setup in the http virtual host.

**Comment by yaskravi** [comment]
```
$ curl -v http://example.com
*   Trying 64.227.116.241:80...
* TCP_NODELAY set
* Connected to example.com (64.227.116.241) port 80 (#0)
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 29 Nov 2021 20:39:57 GMT
< Server: Apache/2.4.37 (centos) OpenSSL/1.1.1k mod_wsgi/4.6.4 Python/3.6
< Location: https://example.com/
< Content-Length: 228
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://example.com/">here</a>.</p>
</body></html>
* Connection #0 to host example.com left intact
$
$
$ curl -v http://www.example.com
*   Trying 64.227.116.241:80...
* TCP_NODELAY set
* Connected to www.example.com (64.227.116.241) port 80 (#0)
> GET / HTTP/1.1
> Host: www.example.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 29 Nov 2021 20:40:42 GMT
< Server: Apache/2.4.37 (centos) OpenSSL/1.1.1k mod_wsgi/4.6.4 Python/3.6
< Location: https://www.example.com/
< Content-Length: 232
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.example.com/">here</a>.</p>
</body></html>
* Connection #0 to host www.example.com left intact
```

**Comment by GrahamDumpleton** [comment]
FWIW. It is usually a bad idea to have both www.example.com and example.com be allowed as final destination. You should always redirect to one or the other so for example in the end only `https://www.example.com` is destination.

```
http://example.com -> https://www.example.com
http://www.example.com -> https://www.example.com
https://example.com -> https://www.example.com
```

Now do the same command as you just did for `http` but using `curl -L -v`, so it follows the redirect.

**Comment by yaskravi** [comment]
Thanks for the information about redirect. I will rework the configuration.
```
$ curl -L -v http://www.example.com > 123 2>www.example.com.txt
$ curl -L -v http://example.com > 123 2>example.com.txt
```
[www.example.com.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7621107/www.example.com.txt)
[example.com.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7621108/example.com.txt)

**Comment by GrahamDumpleton** [comment]
Check `/etc/letsencrypt/options-ssl-apache.conf` to make sure that there isn't some rule in there which is causing the 503 Forbidden response for `www.*` hostname. Try commenting out that `Include` line for that file to see if that is the cause.

**Comment by yaskravi** [comment]
[options-ssl-apache.conf.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7621430/options-ssl-apache.conf.txt)

**Comment by GrahamDumpleton** [comment]
The only thing I can think of is that your Django app is the thing generating the 503, but something in the Apache config causes it to use the Apache error document and not the one generated by Django. Check your ALLOWED_HOSTS in Django config to ensure either have "*" or both hostnames you are accepting listed. Something somewhere outside of that VirtualHost definition is cause the 503 conflict.

**Comment by yaskravi** [comment]
There are no errors in django log files even with debug log level. 
ALLOWED_HOSTS contain both domain and www subdomain.
Possibly major facts are 
- that HTTP without HTTPS works fine with both domain and www subdomain
- HTTPS works for domain only is the hostname equals to domain and doesn't work for www subdomain even if hostname is equal to www subdomain.

**Comment by GrahamDumpleton** [comment]
Delete the ServerName/ServerAlias directives and retype them to make sure you don't have any weird unicode characters in there by mistake, including any strange unicode white space characters. Since you aren't including the original names in posts I can't visually verify them so you will need to double check them.

**Comment by yaskravi** [comment]
I rewrote the domain and www subdomain and double checked the names. The issue still exists.
Is there any additional debug information settings that I can switch on to trace the request handling workflow? Except to "LogLevel debug" in httpd.conf file.

**Comment by GrahamDumpleton** [comment]
Not sure what else can do to show what Apache is doing besides debug.

Try setting www address in ServerName instead of ServerAlias.

**Comment by yaskravi** [comment]
This way www subdomain also doesn't work while domain is working.
When
```
ServerName www.example.com
ServerAlias example.com
```

**Comment by GrahamDumpleton** [comment]
You must have a default virtual host somewhere for HTTPS/443 then which has separate ServerName set to www.example.com. Debug logging may show what it is mapped to. Grep the whole Apache config tree looking for VirtualHost, ServerName and ServerAlias.

**Comment by yaskravi** [comment]
There no additional ServerName or ServerAlias settings in httpd conf directory.

[error.log](https://github.com/GrahamDumpleton/mod_wsgi/files/7621918/error.log)
[error_log.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7621919/error_log.txt)
[ssl_access_log.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7621920/ssl_access_log.txt)
[ssl_error_log.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7621921/ssl_error_log.txt)
[ssl_request_log.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7621922/ssl_request_log.txt)

**Comment by GrahamDumpleton** [comment]
Will look at logs when have more time to do so.

One more thing to try. From same host as Apache is running, try:

```
curl -v -k -H Host:www.example.com https://localhost:443
```

In other words, double check that you are actually talking to Apache instance you expect to, and that some front end router isn't actually redirecting traffic elsewhere.
