### ISSUE TITLE
Installation Docs for Windows has an 404 link

### ISSUE THREAD

**Issue by MaxwellMasaitis** [GrahamDumpleton/mod_wsgi#739]
The docs here:
https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/docs/installation.rst
contain the following link for the Windows installation guide:
https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/win32/README.rst
This is a 404 for me.

**Comment by GrahamDumpleton** [comment]
Known issue that haven't got around to fixing. Use the `pip install` method. See:

* https://pypi.org/project/mod-wsgi/
