### ISSUE TITLE
"Target WSGI script can not be loaded as Python model

### ISSUE THREAD

**Issue by yorkerlabs** [GrahamDumpleton/mod_wsgi#741]
Graham

hi

I have two Django websites running on a cloud sever and one of them is not working and Apache error log has error message ""Target WSGI script can not be loaded as Python model"

Python - 3.5 , Django - 2.1.7

Could you please help. I have checked your previous response on similar issue , but still not able to find the solution.

Thanks

Neeraj

**Comment by GrahamDumpleton** [comment]
Would need to see the mod_wsgi configuration and complete set of error messages include Python exception details.

Also, read:

* http://blog.dscpl.com.au/2012/10/requests-running-in-wrong-django.html

as it is relevant to running multiple Django instances, as there are some gotchas when trying to do that in one Apache server instance.

**Comment by yorkerlabs** [comment]
Graham , thanks for you reply.

Apache error log attached and wsgi.py is below. (my other project is named "CRM")


[error.log](https://github.com/GrahamDumpleton/mod_wsgi/files/7647369/error.log)

-------------WSGI.py --------------------------------------------------

"""
WSGI config for cfehome project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cfehome.settings')

application = get_wsgi_application()

**Comment by GrahamDumpleton** [comment]
As I said, I need to see the mod_wsgi configuration for Apache. As per that blog post I linked, the `DJANGO_SETTINGS_MODULE` module causes a big problem if both Django sites are running in the same process. You need to use mod_wsgi daemon mode to create two separate daemon process groups, one for each application, and delegate them to run in their own respective daemon process group.

**Comment by GrahamDumpleton** [comment]
Alternatively, as explained in that blog post, change:

```
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cfehome.settings')
```

to:

```
os.environ['DJANGO_SETTINGS_MODULE'] = 'cfehome.settings'
```

So make sure you read that blog post carefully.

Preferably use mod_wsgi daemon mode though as it is better.

**Comment by yorkerlabs** [comment]
I have used that , please have a look at the attached files, Apache virtual host file , changes extension to txt for uploading

[sports_latest2.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7647425/sports_latest2.txt)
[crm_student.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/7647426/crm_student.txt)

**Comment by yorkerlabs** [comment]
I believe I have made CRM daemon process as global , this was done for "let's encrypt"

**Comment by GrahamDumpleton** [comment]
The lines:

```
WSGIDaemonProcess crm python-path=/var/www/crmvenv/src/:/var/www/crmvenv/lib/python3.5/site-packages
WSGIProcessGroup crm
WSGIScriptAlias / /var/www/crmvenv/src/crm/wsgi.py
```

should be inside of the `VirtualHost` for `ServerName crm.yorker.in`, not outside.

You also appear to be missing the correct `WSGIScriptAlias` and `WSGIProcessGroup` directives in both SSL VirtualHost's.

You probably should have the `WSGI*` directives only in the SSL VirtualHost's and set up the non SSL VirtualHost to redirect traffic to the `https` URL so everything is done under SSL.

**Comment by yorkerlabs** [comment]
Thanks , I will make the change and try. 
one more point , there is also a celery worker running via supervisor , could that be a reason?

**Comment by GrahamDumpleton** [comment]
Shouldn't matter as it runs completely independently if started by supervisor.

BTW, also suggest that instead of using:

```
WSGIDaemonProcess crm python-path=/var/www/crmvenv/src/:/var/www/crmvenv/lib/python3.5/site-packages
WSGIProcessGroup crm
WSGIScriptAlias / /var/www/crmvenv/src/crm/wsgi.py
```

you use:

```
WSGIDaemonProcess crm python-home=var/www/crmvenv python-path=/var/www/crmvenv/src
WSGIScriptAlias / /var/www/crmvenv/src/crm/wsgi.py process-group=crm application-group=%{GLOBAL}
```

Similar for other application use:

```
WSGIDaemonProcess cfehome python-home=/var/www/venv python-path=/var/www/venv/src
WSGIScriptAlias / /var/www/venv/src/cfehome/wsgi.py process-group=cfehome application-group=%{GLOBAL}
```

Then outside of all VirtualHost's add:

```
WSGIRestrictEmbedded On
```

This last directive ensures embedded mode is turned off. The other changes better ensure that applications run in their respective daemon process groups.

**Comment by yorkerlabs** [comment]
Thanks, problem is solved, as of now. However, this problem keeps coming everyday , strangely around between 6:30 am - 7:00 am. Everyday I simply used to restart Apache and sites started working, but not today. 

I will follow you advice and hopefully it will get resolved completely. Thanks a lot for your time and guidance. I really appreciate it.

Regards

Neeraj

**Comment by GrahamDumpleton** [comment]
As per the article, if the Django sites end up running in same process, because of how `os.environ.setdefault` works, which ever is first to have a request arrive will win out and can then break the other site. So can come down to timing and thus why import not to use `os.environ.setdefault` or ensure that sites running in different processes.

**Comment by yorkerlabs** [comment]
I do have cron jobs running on both sites , every 6 minutes on one site every 10 minutes on the other. maybe they are causing this timing issue.

**Comment by yorkerlabs** [comment]
I will close the issue. Thanks again for your guidance.
