### ISSUE TITLE
info messages logged as error by apache mod_wsgi server

### ISSUE THREAD

**Issue by TonyFrank0001** [GrahamDumpleton/mod_wsgi#745]
I have a application in flask and built for python3.8 . When clients connect to the server, the error log fills with [wsgi:error] even they are just server logs..

```
[Thu Dec 16 08:28:12.250479 2021] [wsgi:error] [pid 13843:tid 140089238185728] 2021-12-16 08:28:12,250 :: INFO :: EasyUCS :: repository/manager.py:319 :: Creating DB directory /home/admin/imm-migration/data/db
[Thu Dec 16 08:28:12.250738 2021] [wsgi:error] [pid 13843:tid 140089238185728] INFO:EasyUCS:EasyUCS :: repository/manager.py:319 :: Creating DB directory /home/admin/imm-migration/data/db
[Thu Dec 16 08:28:13.197214 2021] [wsgi:error] [pid 13843:tid 140089238185728] 2021-12-16 08:28:13,197 :: INFO :: EasyUCS :: repository/manager.py:437 :: Creating etc directory /home/admin/imm-migration/data/etc
[Thu Dec 16 08:28:13.197362 2021] [wsgi:error] [pid 13843:tid 140089238185728] INFO:EasyUCS:EasyUCS :: repository/manager.py:437 :: Creating etc directory /home/admin/imm-migration/data/etc
[Thu Dec 16 08:28:13.197922 2021] [wsgi:error] [pid 13843:tid 140089238185728] 2021-12-16 08:28:13,197 :: DEBUG :: EasyUCS :: repository/manager.py:452 :: Generating proxy details file /home/admin/imm-migration/data/etc/proxy_details.json
[Thu Dec 16 08:28:13.198020 2021] [wsgi:error] [pid 13843:tid 140089238185728] DEBUG:EasyUCS:EasyUCS :: repository/manager.py:452 :: Generating proxy details file /home/admin/imm-migration/data/etc/proxy_details.json
[Thu Dec 16 08:28:13.198888 2021] [wsgi:error] [pid 13843:tid 140089238185728] 2021-12-16 08:28:13,198 :: DEBUG :: EasyUCS :: repository/manager.py:789 :: Querying task metadata from DB
[Thu Dec 16 08:28:13.198990 2021] [wsgi:error] [pid 13843:tid 140089238185728] DEBUG:EasyUCS:EasyUCS :: repository/manager.py:789 :: Querying task metadata from DB
[Thu Dec 16 08:28:13.220709 2021] [wsgi:error] [pid 13843:tid 140089238185728] 2021-12-16 08:28:13,220 :: DEBUG :: EasyUCS :: repository/manager.py:789 :: Querying taskstep metadata from DB
[Thu Dec 16 08:28:13.220822 2021] [wsgi:error] [pid 13843:tid 140089238185728] DEBUG:EasyUCS:EasyUCS :: repository/manager.py:789 :: Querying taskstep metadata from DB
[Thu Dec 16 08:28:13.229894 2021] [wsgi:error] [pid 13843:tid 140089238185728] 2021-12-16 08:28:13,229 :: DEBUG :: EasyUCS :: repository/manager.py:789 :: Querying migration metadata from DB
[Thu Dec 16 08:28:13.229983 2021] [wsgi:error] [pid 13843:tid 140089238185728] DEBUG:EasyUCS:EasyUCS :: repository/manager.py:789 :: Querying migration metadata from DB
[Thu Dec 16 08:28:14.718643 2021] [wsgi:error] [pid 13843:tid 140089296934656] [remote 10.81.0.103:65359] 2021-12-16 08:28:14,718 :: DEBUG :: EasyUCS :: repository/manager.py:789 :: Querying migration metadata from DB
[Thu Dec 16 08:28:14.720974 2021] [wsgi:error] [pid 13843:tid 140089296934656] [remote 10.81.0.103:65359] DEBUG:EasyUCS:EasyUCS :: repository/manager.py:789 :: Querying migration metadata from DB
[Thu Dec 16 08:28:14.805013 2021] [wsgi:error] [pid 13843:tid 140089322112768] [remote 10.81.0.103:65359] 2021-12-16 08:28:14,804 :: DEBUG :: EasyUCS :: repository/manager.py:789 :: Querying migration metadata from DB
[Thu Dec 16 08:28:14.805286 2021] [wsgi:error] [pid 13843:tid 140089322112768] [remote 10.81.0.103:65359] DEBUG:EasyUCS:EasyUCS :: repository/manager.py:789 :: Querying migration metadata from DB
MoTTY X11 proxy: Unsupported authorisation protocolMPLCONFIGDIR

```
The application runs completely fine ..Not sure whats wrong..

**Comment by GrahamDumpleton** [comment]
Sorry for delay. This got lost in inbox as have been occupied on other stuff.

Since you have DEBUG log level on in your Python application it is no uncommon for applications to generate overly verbose log messages. In this case it appears perhaps to be logging stuff on every request. They don't look like errors, just debug messages. You can ignore that Apache says they are errors because all stdout/stderr output from your Python application gets flagged as Apache as error level as there isn't a way to map Python log levels to Apache log levels.

**Comment by filips123** [comment]
> there isn't a way to map Python log levels to Apache log levels

Do you mean there isn't any mapping between Python and Apache log levels, but it could be possible to do this, for example, if the user provided their own mappings, or that it's completely impossible for Apache modules like `mod_wsgi` to configure log levels?

Because, although we can see that they are errors and can just ignore them, some monitoring softwares might still recognize them as errors and display unnecessary alerts about them. However, it might still be useful to log info messages, just not as errors...

**Comment by GrahamDumpleton** [comment]
Whatever is being captured from `sys.stdout` and `sys.stderr` is being sent to the Apache log at level error. When someone using `print()` in Python, how are they going to pass a log level, the API of `print()` doesn't support it. That is what I am referring to.

**Comment by filips123** [comment]
Yeah, this makes sense. But I still have some ideas about how this could potentially be implemented:

1. Provide some way to map log messages to Apache log levels in the config, probably with regexes. Logs sent through the `logging` APIs commonly have a consistent structure with their log level printed in a specific place, so it should be possible to write some regex to capture the log level (and other potentially useful stuff). For other messages that wouldn't match (any of?) provided regex (for example, those sent with `print`), a default log level could be used.

2. Create a custom logging handler that can be accessed from the application code (so, something like `mod_wsgi.logging.ApacheHandler`) and used as a logging handler for `logging` APIs. This way, it could access the log level and directly send it to Apache. I'm not sure if this is possible though. For other logging, it would work just like now (through `sys.stdout` and `sys.stderr`).

3. Both options combined.

I don't know how complicated it would be to implement this and if it's worth it, but I think it's something that could be useful.
