### ISSUE TITLE
Python 3.10 + Django 4 is very slow with sqlite db and mod_wsgi

### ISSUE THREAD

**Issue by claudiopatricio** [GrahamDumpleton/mod_wsgi#750]
CentOS 8.5
Apache 2.4.52 (./configure --enable-ssl --enable-so --enable-mpms-shared --with-included-apr --with-included-apr-util)
Python 3.10.1 (./configure --enable-optimizations --enable-shared --with-ensurepip=install)
mod_wsgi 4.9.0 (previous versions won't compile with python 3.10)
sqlite 3.26 (from CentOS repo)

I've tried multiple configurations, with and without mpm and most of the time i get a timeout when i try to login to the admin page, i need to change to another db like mysql or downgrade python to 3.9 to be able to login to the admin page.

With the django server (using python manage.py runserver) it works very well with sqlite and since everything works with the django server and with mod_wsgi using python 3.9, i can only guess it is same issue with mod_wsgi.

The only output from the Apache logs is: mod_wsgi (pid=250254): Failed to proxy response from daemon.

**Comment by GrahamDumpleton** [comment]
What is your mod_wsgi configuration in the Apache config files? Is Apache using prefork MPM or event/worker MPM?

**Comment by claudiopatricio** [comment]
I have tried with event MPM and without MPM, also tried to change between more threads or more processes or 1 each, same output and only happens with python 3.10

I'm using variables for the apache config to be able to use for multiple projects, but should be enough to understand how it is configured (the configuration of the wsgi is inside of a vhost)
```
WSGIDaemonProcess ${url} user=${project-user} group=${project-group} python-path=${RootPath}/web/${url}/ python-home=${RootPath}/web/envs/${venv} display-name=${project} processes=3 threads=100 request-timeout=600
WSGIProcessGroup ${url}
WSGIScriptAlias / ${RootPath}/web/${url}/${app}/wsgi.py process-group=${url}
```
The modules i'm using:
```
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule wsgi_module modules/mod_wsgi.so
```

**Comment by GrahamDumpleton** [comment]
How many daemon process groups do you have for different applications?

What is the Apache MPM configuration you are using? In other words, what do you have for:

```
<IfModule mpm_prefork_module>
    StartServers             1
    MinSpareServers          1
    MaxSpareServers         10
    MaxRequestWorkers      250
    MaxConnectionsPerChild   0
</IfModule>

<IfModule mpm_worker_module>
    StartServers             3
    MinSpareThreads         75
    MaxSpareThreads        250
    ThreadsPerChild         25
    MaxRequestWorkers      400
    MaxConnectionsPerChild   0
</IfModule>

<IfModule mpm_event_module>
    StartServers             3
    MinSpareThreads         75
    MaxSpareThreads        250
    ThreadsPerChild         25
    MaxRequestWorkers      400
    MaxConnectionsPerChild   0
</IfModule>
```

Also, are you setting ``MaxConnectionsPerChild`` or ``MaxRequestsPerChild`` directives?

**Comment by claudiopatricio** [comment]
I tried without mpm, it was exactly the same.

When i tried mpm these were the settings:
```
StartServers               2
ServerLimit                4
MinSpareThreads           50
MaxSpareThreads          200
ThreadLimit               50
ThreadsPerChild           50
AsyncRequestWorkerFactor   2
MaxRequestWorkers        200
MaxConnectionsPerChild 50000
```

**Comment by GrahamDumpleton** [comment]
Few more questions before I try and digest what you have.

What is the rate of requests (throughput requests/sec) your Apache server as a whole receives?

As asked already, how many different WSGI applications do you have hosted and thus how many daemon process groups do you have configured? Is each WSGI application under a different `VirtualHost`?

What is the rate of requests for each WSGI application? What is the typical average response time for the WSGI application when it is working correctly?

**Comment by claudiopatricio** [comment]
It is hosted in a virtual machine that is only running this application, nothing more is installed, just a test machine for a new project, and with mysql it takes a few milliseconds for each request (i have the status_module for debugging and it shows 0-1ms to process each request most of the times)

**Comment by claudiopatricio** [comment]
Full Apache config
```
# httpd config

# Variables
Define Name             ""
Define RootPath         "/opt/"
Define ApachePath       "${RootPath}/dist/apache/"
Define Port             443
Define ServerAdmin      you@example.com
Define project-user     ""
Define project-group    ""

# 'Main' server configuration
ServerRoot "${ApachePath}"
ServerAdmin "${ServerAdmin}"
ServerName ${Name}
DocumentRoot ${ApachePath}/htdocs
PidFile ${ApachePath}/logs/httpd.pid
Listen 443

# Main Apache Modules
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so
#LoadModule rewrite_module modules/mod_rewrite.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule wsgi_module modules/mod_wsgi.so

# Optional Apache Modules
#LoadModule authn_file_module modules/mod_authn_file.so
#LoadModule authn_core_module modules/mod_authn_core.so
#LoadModule authz_host_module modules/mod_authz_host.so
#LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
#LoadModule authz_user_module modules/mod_authz_user.so
#LoadModule access_compat_module modules/mod_access_compat.so
#LoadModule auth_basic_module modules/mod_auth_basic.so
#LoadModule filter_module modules/mod_filter.so
#LoadModule env_module modules/mod_env.so
#LoadModule headers_module modules/mod_headers.so
#LoadModule setenvif_module modules/mod_setenvif.so
#LoadModule version_module modules/mod_version.so

# Debug Modules
LoadModule status_module modules/mod_status.so
LoadModule info_module modules/mod_info.so

# MPM Config (httpd-mpm.conf)
StartServers               2
ServerLimit                4
MinSpareThreads           50
MaxSpareThreads          200
ThreadLimit               50
ThreadsPerChild           50
AsyncRequestWorkerFactor   2
MaxRequestWorkers        200
MaxConnectionsPerChild 50000

# Default Config (httpd-default.conf)
Timeout 600
KeepAlive On
MaxKeepAliveRequests 1000
KeepAliveTimeout 50
UseCanonicalName Off
AccessFileName .htaccess
ServerTokens Full
ServerSignature Off
HostnameLookups Off
#reqtimeout_module
RequestReadTimeout header=20-40,MinRate=500 body=20,MinRate=500

# Processes user and group
User ${project-user}
Group ${project-group}

# Files and di
<Files ".ht*">
	Require all denied
</Files>

<Directory />
	AllowOverride None
	Require all denied
</Directory>

####### DEBUG START #######
<Location /server-status>
	SetHandler server-status
	Require all granted
</Location>

<Location /server-info>
	SetHandler server-info
	Require all granted
</Location>
####### DEBUG END #######

<Directory "${ApachePath}/htdocs">
	# None All Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
	Options Indexes FollowSymLinks
	# AllowOverride controls what directives may be placed in .htaccess files. (All|None)
	AllowOverride None
	Require all granted
</Directory>

# Logging
# debug, info, notice, warn, error, crit, alert, emerg.
LogLevel warn

# log_config_module
LogFormat "%h %l %u %t \"%v %r\" %>s %b" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common

ErrorLog "${ApachePath}/logs/error_log"
CustomLog "${ApachePath}/logs/access_log" combined

# mime_module
TypesConfig ${ApachePath}/conf/mime.types
AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz

# ssl_module - Secure (SSL/TLS) connections
SSLRandomSeed startup file:/dev/urandom 1024
SSLRandomSeed connect file:/dev/urandom 1024
SSLCipherSuite HIGH:MEDIUM:!SSLv3:!kRSA
SSLProxyCipherSuite HIGH:MEDIUM:!SSLv3:!kRSA
SSLHonorCipherOrder on
SSLProtocol all -SSLv3
SSLProxyProtocol all -SSLv3
SSLPassPhraseDialog builtin
SSLSessionCache "shmcb:${ApachePath}/logs/ssl_scache(512000)"
SSLSessionCacheTimeout 300

### VirtualHosts
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout domain.key -out domain.crt
<VirtualHost _default_:443>
	Define url				""
	Define project			""
	Define venv				""
	Define app				""

	ServerName ${url}:443
	DocumentRoot ${RootPath}/web/${url}/${app}/
	ErrorLog ${ApachePath}/logs/${project}-error.log
	CustomLog ${ApachePath}/logs/${project}.log vhost_combined

	SSLEngine on
	# SSL Valid until: 
	SSLCertificateFile "${ApachePath}/ssl/${url}.crt"
	SSLCertificateKeyFile "${ApachePath}/ssl/${url}.key"

	# Read: https://docs.djangoproject.com/en/4.0/howto/deployment/wsgi/modwsgi/
	WSGIDaemonProcess ${url} user=${project-user} group=${project-group} python-path=${RootPath}/web/${url}/ python-home=${RootPath}/web/envs/${venv} display-name=${project} processes=3 threads=100 request-timeout=600
	WSGIProcessGroup ${url}

	Alias /robots.txt ${RootPath}/web/${url}/static/robots.txt
	Alias /favicon.ico ${RootPath}/web/${url}/static/favicon.ico

	Alias /media/ ${RootPath}/web/${url}/media/
	Alias /static/ ${RootPath}/web/${url}/static/

	<Directory ${RootPath}/web/${url}/static/>
		Require all granted
	</Directory>

	<Directory ${RootPath}/web/${url}/media/>
		Require all granted
	</Directory>

	WSGIScriptAlias / ${RootPath}/web/${url}/${app}/wsgi.py process-group=${url}

	<Directory ${RootPath}/web/${url}/${app}/>
		<Files wsgi.py>
			Require all granted
		</Files>
	</Directory>
</VirtualHost>
```

**Comment by GrahamDumpleton** [comment]
The first suggestion change is instead of using:

```
WSGIDaemonProcess ${url} user=${project-user} group=${project-group} python-path=${RootPath}/web/${url}/ python-home=${RootPath}/web/envs/${venv} display-name=${project} processes=3 threads=100 request-timeout=600
WSGIProcessGroup ${url}
WSGIScriptAlias / ${RootPath}/web/${url}/${app}/wsgi.py process-group=${url}
```

use:

```
WSGIDaemonProcess ${url} user=${project-user} group=${project-group} python-path=${RootPath}/web/${url}/ python-home=${RootPath}/web/envs/${venv} display-name=${project} processes=3 threads=10 request-timeout=600
WSGIScriptAlias / ${RootPath}/web/${url}/${app}/wsgi.py process-group=${url} application-group=%{GLOBAL}
```

That is:

* Remove `WSGIProcessGroup` as doesn't do anything since `process-group` is used on `WSGIScriptAlias`.
* Add `application-group=%{GLOBAL}` option to `WSGIScriptAlias`. This avoids potential for problems caused by third party Python packages that do not work in sub interpreters. Such packages could otherwise crash, or cause deadlocks.
* Drop the number of threads from 100 to 10. Such a high number can cause big problems and generally unnecessary except for very specialised use cases. For high throughput applications with small response times, the option is about 3 threads per process and use more processes instead of threads.

Note that having both `process-group` and `application-group` options at the same time will have a side effect of causing preloading of the WSGI script file (and thus application) at the time the daemon process is started, rather than lazily on first request. I wouldn't be surprised if concerns over slow requests is because lazy loading meant you were counting time to load application in the first requests. This would be more prevalent if you were using this as development environment and making code changes a lot. You will still see delays on subsequent requests if are relying on live reloading though.

Also, outside of all `VirtualHost` configurations add:

```
WSGIRestrictEmbedded On
```

This will disable Python being initialized in Apache child processes where it isn't being used.

And last quick update based on your newer response, setting `KeepAliveTimeout` to such a high value is a bad idea. The Apache documentation even warns about this:

* https://httpd.apache.org/docs/2.4/mod/core.html#keepalivetimeout

In `mod_wsgi-express` I use 2 seconds.

In respect of `mod_wsgi-express`, you could learn something by looking at how it is configured as it has been tuned to work well for Python WSGI applications under Apache. Suggest if you haven't already, watch:

* https://www.youtube.com/watch?v=H6Q3l11fjU0

**Comment by claudiopatricio** [comment]
Thanks it worked. The `KeepAliveTimeout` was 50 by mistake, probably when i was trying diferent configurations.

Do you know why it was working fine with Python 3.9.9 but when i change to 3.10.1 it doesn't work anymore with the old config?

**Comment by GrahamDumpleton** [comment]
Python 3.10 changes various things with Python sub interpreters. It is possible that some third party package for Python you are using isn't implemented to work properly with sub interpreters and the changes in Python 3.10 have made the problem worse.

Don't under estimate the confusion of the default being lazy loading of the application. Since you had `LogLevel` set to only `warn`, it wouldn't have been obvious if the daemon processes were crashing all the time because of a bad package, and so requests frequently may have been against a new process and WSGI application had to be loaded from scratch all the time. I suggest you set `LogLevel info` so you can see better when the WSGI application is being loaded and daemon process restarts are occurring.

**Comment by claudiopatricio** [comment]
You are right, the LogLevel would probably help, but it working with mysql but not with sqlite and also working with sqlite with python 3.9 but not with python 3.10 got me very confused.

I'm using virtualenv with only Django installed.

I think it would be helpful if you add some examples/templates of optimized and updated apache configs for single projects.

**Comment by GrahamDumpleton** [comment]
The purpose of `mod_wsgi-express` is to provide optimized configs for single projects. It even runs it all for you, generating the config and everything. So I suggest you try using `mod_wsgi-express`.

See:

* http://blog.dscpl.com.au/2015/04/introducing-modwsgi-express.html
* http://blog.dscpl.com.au/2015/05/using-modwsgi-express-as-development.html
* http://blog.dscpl.com.au/2015/04/using-modwsgi-express-with-django.html
* http://blog.dscpl.com.au/2015/04/integrating-modwsgi-express-as-django.html

and watch the video I already linked.

**Comment by claudiopatricio** [comment]
I was testing what was causing it and simply removing the `application-group=%{GLOBAL}` makes it very slow. `LogLevel info` doesn't give anything useful, just:
```Daemon process deadlock timer expired, stopping process```

**Comment by GrahamDumpleton** [comment]
Which confirms it is a third party package causing a problem when using in a sub interpreter.

There is a little bit more info on it at:

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#python-simplified-gil-state-api

The daemon process mode has a specific checker to detect the problem, which is what is generating the error message you are seeing. See the ``--deadlock-timeout`` option in:

* https://modwsgi.readthedocs.io/en/master/configuration-directives/WSGIDaemonProcess.html

**Comment by claudiopatricio** [comment]
Thanks again, it's solved.
For people that have the same issue with Python 3.10 and sqlite, using `application-group=%{GLOBAL}` is the solution.
