### ISSUE TITLE
mod_wsgi install on OS X 12.1 on macmini MI chip

### ISSUE THREAD

**Issue by judithdboonstra** [GrahamDumpleton/mod_wsgi#752]
mod_wsgi install appears to work correctly.  

When django app is started using runmodwsgi the ff error code is presented:

[Thu Jan 06 08:28:45.334243 2022] [so:error] [pid 88910:tid 4298818944] AH06665: No code signing authority for module at /Users/judith/env/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-darwin.so specified in LoadModule directive.
httpd (mod_wsgi-express) : Syntax error on line 163 of /var/tmp/mod_wsgi-localhost:8000:501/httpd.conf: Code signing absent - not loading module at: /Users/judith/env/lib/python3.9/site-packages/mod_wsgi/server/mod_wsgi-py39.cpython-39-darwin.so

How can this be handled?

**Comment by GrahamDumpleton** [comment]
Don't use the Apple supplied Apache httpd server. Use Homebrew to install separate `httpd` package and use it instead.

There may be a way to generate the module with a local self signed certificate authority but I have no idea how to do it and no one has ever offered an explanation of how to do it. So only choice is to use a separate installation of Apache httpd server if you want to use extra Apache modules.

**Comment by judithdboonstra** [comment]
So, before, I simply installed mod_wsgi in my virtual enviroment, using pip.
And now I should install httpd using homebrew.  

Does this mean I cannot/should not use mod_wsgi?  I've been using it/loving it for at least the last 5 years!

**Comment by judithdboonstra** [comment]
Just tried pip install mod_wsgi-standalone and received errors:  1). could not find versions .... and 2) no matching distribution found ,,,,,,.  Shucks!

**Comment by GrahamDumpleton** [comment]
Would need to see the full errors for the latter, but in general mod_wsgi-standalone cannot be used on macOS as the Apache APR library hasn't been updated in a very long time and doesn't support newer macOS versions. Homebrew uses some manual patch in order to install APR so Apache can be then be built.

So the only option is to use Apache httpd from Homebrew.

**Comment by judithdboonstra** [comment]
I am amazed!  Have installed apache using home brew and mod_wsgi in a virtual environment using pip.  Followed instructions from guides provided for both Apache and mod_wsgi (in a minimal fashion) and the app is working!

Thank you very much for your help.  I just cant' stop working with this stuff - even at the young age of 78.

Best regards to you
