### ISSUE TITLE
mod_wsgi-express causing ModuleNotFoundError: No module named "mod_wsgi.server"

### ISSUE THREAD

**Issue by khalilahmed-dev** [GrahamDumpleton/mod_wsgi#754]
Hello, I'm trying to deploy the Django 3.2 project with Python 3.10 on CentOS 7 but I am facing issues in it.
I'm trying to run the following command to run mod_wsgi-express:

```
mod_wsgi-express start-server  django_wsgi.py --server-root /var/www --user apache --group apache --port 80 --host XYZ
```
where XYZ is the IP of the machine i'm running this command on. I had to specify a different server root as my /tmp is noexec.

The contents of django_wsgi.py are:
```
import os
import sys
project_dir=os.path.dirname(__file__)
if project_dir not in sys.path:
    sys.path.append(project_dir)

from django.core.wsgi import get_wsgi_application
os.environ['DJANGO_SETTINGS_MODULE'] = 'MY_PACKAGE_WHERE_SETTINGS_ARE.settings'
application = get_wsgi_application()

```

but I keep getting this error:

```

 [mpm_event:notice] [pid 101737:tid 139778434865344] AH00489: **Apache/2.4.52 (codeit) mod_wsgi/4.9.0 Python/3.10** configured -- resuming normal operations
 [core:notice] [pid 101737:tid 139778434865344] AH00094: Command line: 'httpd (mod_wsgi-express)  -f /var/www/httpd.conf -D MOD_WSGI_KEEP_ALIVE -D MOD_WSGI_WITH_LISTENER_HOST -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'

mod_wsgi (pid=101741): Exception occurred processing WSGI script '/var/www/handler.wsgi'.
 [wsgi:error] [pid 101741:tid 139778434865344] Traceback (most recent call last):
 [wsgi:error] [pid 101741:tid 139778434865344]   File "/var/www/handler.wsgi", line 7, in <module>
 [wsgi:error] [pid 101741:tid 139778434865344]     import mod_wsgi.server
 [wsgi:error] [pid 101741:tid 139778434865344] ModuleNotFoundError: No module named 'mod_wsgi.server'

```
 
 The error says "handler.wsgi", I don't know if that is correct or it is not accepting my wsgi file ? 
 When I tried opening a python console and tried to import  "import mod_wsgi.serve", it showed no error. 
 
 Any help would be much appreciated because, I'm stuck on this for days.

**Comment by GrahamDumpleton** [comment]
Where was `mod_wsgi` installed to using `pip`? It looks like where that was installed is not accessible to the Apache user.

**Comment by khalilahmed-dev** [comment]
the python and all its packages were installed using root user.

**Comment by GrahamDumpleton** [comment]
So are you saying that you are not using a Python virtual environment and ran `pip install mod_wsgi` as `root` so that it was installed in the system Python installation?

What do you get if you run command line Python and enter at the prompt:

```
import mod_wsgi
print(mod_wsgi.__file__)
```

**Comment by khalilahmed-dev** [comment]
That was my bad. Thanks a ton. It was permission issue, I was able to solve it by allowing the apache user to access the site-packages.

The server is running now but how do I make it run in daemon mode? Like the one where it doesn't stop even if I close my SSH connection.

**Comment by khalilahmed-dev** [comment]
For anyone else who might be wondering how to make it run in production:

Run this command (with your own paths to wsgi file , server root , user and group, port and host):

```
mod_wsgi-express setup-server django_wsgi.py --server-root /var/www/deployment --user apache --group apache --port 80 --host 10.247.109.57
```

The above command will create apachectl and other files and directories for you in your server root folder, so it would be a good step if that is an empty folder before.

Afterwards, all you have to do is run the below command to start the server:

```
./apachectl start
```

To stop it run:
```
./apachectl stop
```

Thank you again for the mod_wsgi-express, it really made the life easy !
