### ISSUE TITLE
Development and deploying Django project on mod_wsgi

### ISSUE THREAD

**Issue by pique-b** [GrahamDumpleton/mod_wsgi#757]
I have created a project which works fine on Django dev server.

Now I am trying to run the said Django app using Apache with mod_wsgi on my local machine (as described in https://docs.djangoproject.com/en/4.0/topics/install/#install-apache-and-mod-wsgi).

In order to do this, I did as described below (following Django Docs) and information contained in http://blog.dscpl.com.au/2015/04/integrating-modwsgi-express-as-django.html:

1.	I installed mod_wsgi using:

	pip3 install mod_wsgi

	To do this I followed instructions at per https://pypi.org/project/mod-wsgi/ from section "Installation into Python" as Apache is pre-installed on the system (MacOS) I am using. 

I have used the pip at system root (MacBook: ~ <user>) (as I have been doing for all python related packages), which means it will have system-wide effect.

2.	For my Django app I am not using venv.

3. The directory structure is:

![Screen Shot 2022-02-08 at 11 28 51](https://user-images.githubusercontent.com/69836231/152929454-75b27a0d-ceb7-4cbf-bc16-2266a918b485.png)

4.	As explained in section "Using mod_wsgi-express with Django" of https://pypi.org/project/mod-wsgi/, added 'mod_wsgi.server' in INSTALLED_APPS in project's settings.py.

5.	Ran collectstatic (python3 manage.py collectstatic)

6.	Tried to run Apache server with: python3 manage.py runmodwsgi

	However the terminal shows the following error:

`Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mod_wsgi/server/management/commands/runmodwsgi.py", line 135, in handle
    'start-server', args, options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mod_wsgi/server/__init__.py", line 3271, in _cmd_setup_server
    language, encoding = locale.getdefaultlocale()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 562, in getdefaultlocale
    return _parse_localename(localename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
`

NOTE: I tried to provide as much information as I gathered I should be doing, after going through many of the questions asked on your site.

NOTE 2: One part I completely missed was this step https://docs.djangoproject.com/en/4.0/howto/deployment/wsgi/modwsgi/#basic-configuration. Since the conf file httpd.conf is locked (residing in path /etc/apache2) the only way I could find out to do that, was to use the sudo nano /<path_to_httpd_conf>. But I haven't done it yet in order to not mess up the original settings. So I am not certain as to how to setup the Basic Configuration (as explained at https://docs.djangoproject.com/en/4.0/howto/deployment/wsgi/modwsgi/#basic-configuration).

a. As per the aforesaid, I need to add WSGIScriptAlias, WSGIPythonHome and WSGIPythonPath, besides the Directory and Files listings, but I am not sure where exactly in the httpd.conf these should be added.

b. Also the said Django doc talks about "activating" mod_wsgi. How does one do that?

c. Now I am having some doubts, if instead of "mod_wsgi" I should have installed "mod_wsgi-standalone" (https://github.com/GrahamDumpleton/mod_wsgi/issues/591#issuecomment-659445873).

However as discussed at (https://pypi.org/project/mod-wsgi/):

> If you are on Linux, macOS or other UNIX type operating system and can’t or don’t want to use the system package for Apache, you can use pip to install mod_wsgi, but you should use use the mod_wsgi-standalone package on PyPi instead of the mod_wsgi package.

I am sorry but here I seem to be getting contrary inputs (or that I have lost it somewhere).

Using command "mod_wsgi-express start-server" and "mod_wsgi-express start-server wsgi.py" both result in the same "ValueError: unknown locale: UTF-8" error in the terminal.

d. I am not sure how but I find the following files have been added to the project root (where I have the manage.py file residing):
	d1.	--port
	d2.	--server-root
	d3.	--user

I presume it might be the result of adding 'mod_wsgi.server' in INSTALLED_APPS

System info:
============
Python 3.6
Django 2.2.19
OS: macOS Sierra Ver 10.12.6
mod_wsgi 4.9.0
Apache 2.4.28 (Unix) Pre-Loaded (on Mac)

**1. Could you please let me know how do I run the app using 'mod_wsgi' with: `python3 manage.py runmodwsgi`
2. For the sys config (as stated above), do I need to uninstall mod-wsgi and install mod_wsgi-standalone? The only problem I see is the rider "... and you don’t have Apache available,".
3. What is the difference between using mod_wsgi-express and using mod_wsgi in daemon mode (https://docs.djangoproject.com/en/4.0/howto/deployment/wsgi/modwsgi/#using-mod-wsgi-daemon-mode)?**

**PS. I am sorry my query has tended to be one too long.**

**Thanks**

**Comment by GrahamDumpleton** [comment]
For a start, why are you using such an old version of Python and macOS?

**Comment by pique-b** [comment]
1. I have an old MacBook with me which is still running fine, and can install an OS higher than Sierra
2. I think I can upgrade to the later ver of Python to say, 3.8. Will it affect the current app - that is bothering me.

**Comment by GrahamDumpleton** [comment]
Don't use `mod_wsgi-standalone`, rely on the system Apache install if you can on that older macOS version. If you have already tried, make sure you run `pip uninstall mod_wsgi-standalone`, `pip uninstall mod_wsgi-httpd` and `pip uninstall mod_wsgi` multiple times until it says none are installed.

So use `pip install mod_wsgi`, preferably into a Python virtual environment. Then use `mod_wsgi-express start-server` or `python manage.py runmodwsgi`. You don't need to touch the system Apache configuration if only needing to run it in an ad-hoc way for development. If you have tried installing `mod_wsgi-standalone`, instead of using `pip install mod_wsgi` use `pip install --no-cache-dir mod_wsgi` to ensure artefacts of old build aren't used.

That said, your Python 3.6 install looks to be broken in some way if you get the locale error. So I would try a newer Python version if you can. Alternatively, you have locale environment variables in your user account set to a strange value.

**Comment by pique-b** [comment]
Thank you so much for your reply.

In fact I have already tried installing mod-wsgi-standalone (from PyPi) [as I found myself still breaking my head around midnight]. When I tried to run `python3 manage.py runmodwsgi` I still got the `locale` error.

On searching for the specific `locale` issue on the net I came across a solution whereby the `locale` values `LC_ALL` and `LANG` could be written with `.bash/profile`. Though this I found to be a temporary solution as this is needed to be done (i.e. writing `locale` values) every time the **terminal.app** is restarted.

On checking further I found that this was indeed a Python [bug](https://bugs.python.org/issue18378) which was only addressed ver. 3.8 onwards.

Now I want to report to you (**and happy to do so**) that the `runmodwsgi` command worked without any hitch. And I have been thinking ever since if the system **_Apache install would have worked as well_** with the `locale` tweak (or, if I had upgraded my Python install to 3.8 (or **beyond**!!)).

The only problem I am facing is that the run command using:
`python3 manage.py runmodwsgi --processes 3 --threads 1 --reload-on-changes`
the **_reload_** function doesn't have any effect (i.e. if I change any module in the app, the server does not reload the app, as it happens with **_Django Dev server_**).

I have tried to run without the `--processes 3 --threads 1` but the result is the same (i.e. **_the server does not reload the app_**).

**Could you please guide me** as to why is `--reload-on-changes` not working.

In the meantime, **I would try to revert back to `mod_wsgi` and report the results.**

Thanks again for your valuable time.

**Comment by GrahamDumpleton** [comment]
I'll check the reload on changes functionality when I get a chance. Just be aware that it does not reload when any file in the project part of the file system is changed, only when a Python code file that has actually been loaded into the running process has changed. Also, changing templates or static media files will not result in an automatic reload. Try running the `touch` command on your `wsgi.py` file in your project to see if that at least triggers a reload.

For future reference if you ever upgrade macOS version, the `mod_wsgi-standalone` package cannot be installed on latest macOS version. Apple changed stuff and Apache Software Foundation still hasn't released updated source code to handle it. :-(

**Comment by pique-b** [comment]
1. I changed only the python modules (and not static files) in the app related to the page being served at the time - **No reload**.
2. I have changed **_settings.py_** (where I think it would matter the whole app) - **But no reload yet**.
3. To carry out `touch` command, as I have to keep the app running to **test reload**, I opened another window of the terminal, and tried  `touch <file_path>/wsgi.py`. But it did not have any effect (**No reload**) [in the first terminal window].
4. I know I am trying to stretch hospitality, but will it be possible for you to let me know **exactly how do I carry out the touch command**.

**Comment by pique-b** [comment]
I realized I needed to install **_touch_** which I duly installed and then ran:

`touch wsgi.py` in the path where the project **_wsgi.py_** already exists.

However I did not get any reaction at the terminal (running "**_mod_wsgi_**"), liking a **_reload_**.

When I ran the command on a path where no such file (i.e. **_wsgi.py_**), a new blank file was created with the same name.

**Comment by GrahamDumpleton** [comment]
The `touch` command is part of standard macOS, you don't need to install it. You should be running `touch` on an existing code file only.

Anyway, my tests of `mod_wsgi-express start-server --reload-on-changes` show it working fine.

When you test it, use the option `--log-to-terminal` so you can see on the terminal the log messages about what it is doing. You should see something like:

```
[Thu Feb 10 09:08:40.618661 2022] [wsgi:error] [pid 65281:tid 4524267008] monitor (pid=65281): Starting change monitor.
[Thu Feb 10 09:08:42.633499 2022] [wsgi:error] [pid 65281:tid 123145532944384] monitor (pid=65281): Change detected to "/Users/graham/Projects/wsgi-projects/mod_wsgi/tests/hello.wsgi".
[Thu Feb 10 09:08:42.633689 2022] [wsgi:error] [pid 65281:tid 123145532944384] monitor (pid=65281): Triggering process restart.
[Thu Feb 10 09:08:43.628757 2022] [wsgi:error] [pid 65286:tid 4524267008] monitor (pid=65286): Starting change monitor.
```

**Comment by pique-b** [comment]
Yeah, with the option `--log-to-terminal` added I can see the feedback at the terminal now.

At the start (**_when the app was yet to be started_**) I got the following message/s:

[Thu Feb 10 09:58:43.269248 2022] [mpm_event:notice] [pid 656:tid 4418307008] AH00489: Apache/2.4.48 (Unix) mod_wsgi/4.9.0 Python/3.6 configured -- resuming normal operations
[Thu Feb 10 09:58:43.271382 2022] [core:notice] [pid 656:tid 4418307008] AH00094: Command line: 'httpd (mod_wsgi-express)  -f /var/tmp/mod_wsgi-localhost:8000:501/httpd.conf -D MOD_WSGI_KEEP_ALIVE -D MOD_WSGI_MULTIPROCESS -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
[Thu Feb 10 09:59:00.074979 2022] [wsgi:error] [pid 658:tid 4418307008] monitor (pid=658): Starting change monitor.
[Thu Feb 10 09:59:00.076905 2022] [wsgi:error] [pid 659:tid 4418307008] monitor (pid=659): Starting change monitor.
[Thu Feb 10 09:59:00.076929 2022] [wsgi:error] [pid 660:tid 4418307008] monitor (pid=660): Starting change monitor.

When the app was started there was no further (addition to the) messages already there (as above).

**_Now when I am changing a module related to the app_**, the terminal window gets active and detects the changes:

[Thu Feb 10 10:03:12.022760 2022] [wsgi:error] [pid 659:tid 123145337643008] monitor (pid=659): Change detected to "<path>/settings.py".
[Thu Feb 10 10:03:12.090584 2022] [wsgi:error] [pid 660:tid 123145551134720] monitor (pid=660): Triggering process restart.
[Thu Feb 10 10:03:48.578813 2022] [wsgi:error] [pid 692:tid 4418307008] monitor (pid=692): Starting change monitor.
[Thu Feb 10 10:03:48.578813 2022] [wsgi:error] [pid 691:tid 4418307008] monitor (pid=691): Starting change monitor.
[Thu Feb 10 10:03:48.581620 2022] [wsgi:error] [pid 693:tid 4418307008] monitor (pid=693): Starting change monitor.

**Does it mean that the option `--reload-on-changes` has to be used in tandem with the option `--log-to-terminal`?**

**Comment by pique-b** [comment]
To add to my earlier comment, if **I start my app using Django server**, I get the following in addition to file changes:

> HTTP GET /praudit/praud/audit/question_list/ 200 [5.52, 127.0.0.1:49320]
HTTP GET /favicon.ico 302 [0.01, 127.0.0.1:49320]
HTTP GET /audit/ 200 [2.23, 127.0.0.1:49322]
HTTP GET /accounts/audit/login/ 200 [2.12, 127.0.0.1:49322]
HTTP POST /accounts/audit/login/ 302 [0.84, 127.0.0.1:49322]
HTTP GET / 301 [0.01, 127.0.0.1:49322]
HTTP GET /audit/ 200 [2.27, 127.0.0.1:49322]
HTTP GET /accounts/audit/logout/ 302 [0.32, 127.0.0.1:49330]
HTTP GET /audit/ 200 [2.49, 127.0.0.1:49330]
HTTP GET /accounts/audit/login/ 200 [2.25, 127.0.0.1:49330]
HTTP POST /accounts/audit/login/ 302 [0.72, 127.0.0.1:49330]
HTTP GET / 301 [0.01, 127.0.0.1:49330]
HTTP GET /audit/ 200 [2.26, 127.0.0.1:49330]
HTTP GET /praudit/customize_praudit/ 200 [2.10, 127.0.0.1:49330]
HTTP GET /praudit/praud/audit/question_list/ 200 [3.28, 127.0.0.1:49330]

**And if a file is changed:**
/<file_path>/settings.py changed, reloading.

**Is there a way** to get this sort of logging if I use `runmodwsgi`?

**Comment by GrahamDumpleton** [comment]
Reloading of changes is not dependent on display logging on the terminal. Usually logging gets put to the file path displayed when you start it up. Logging to the terminal just makes it easier to see, otherwise you would need to tail the log file.

If you want to see access requests, use the `--access-log` option.

To see all options run with the `--help` option.

**Comment by pique-b** [comment]
**I can now see the power of what you have created. Truly.**

Before I log off, I just wanted to say that I had added the `LOGGING` in `settings.py` as described in your blog [here](http://blog.dscpl.com.au/2015/04/integrating-modwsgi-express-as-django.html).

`LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
...
`

Now I have the function commented out and can still see the terminal logs (incl. code changes and **_errors_**).

Am I right in removing the `LOGGING` from `settings.py` OR **_does it serve some additional purpose / requirements_**?

**Comment by GrahamDumpleton** [comment]
The Django logging section is nothing to do with Apache level logging. The `LOGGING` section relates to controlling the Python `logging` module and ensuring that its output is sent to `sys.stderr` so that it can be captured in the Apache logging system. Since that blog post is very old, I have no idea whether Django config may work the same now or whether it has changed. It did originally have a purpose and Python `logging` module wouldn't be captured if didn't have it. So you would need to use Python `logging` module and see whether anything logged via it ends up in Apache log output.

**Comment by pique-b** [comment]
**Thank you so much for all the help.**

Closing the issue now.
