### ISSUE TITLE
mod_wsgi .. : Failed to exec Python script file '.../app.wsgi' - ImportError failed to map segment from shared object

### ISSUE THREAD

**Issue by zwiftebassen** [GrahamDumpleton/mod_wsgi#758]
We have a running license distrubution portal with a RESTapi and we are trying to add functionality to send files over sFTP with pysftp. The webapp is created using flask.
But when we simply add the line "import pysftp" we get internal server error. 
Apache/2.4.37
RHEL 8
Python 3.6

/../api/api.error_ssl.log (without paths)
```
mod_wsgi xxx: Failed to exec Python script file '.../app.wsgi'
mod_wsgi xxx: Exception occured processing WSGI script '.../app.wsgi'
from app import app as application
app = create_app()
from .views import views
from xxx.BQtojsonl import get_from_bq
import pysftp
import paramiko
from paramiko.transport import SecurityOptions, Transport
from paramiko.dsskey import DSSKey
from paramiko.pkey import PKey
import bcrypt
from . import _bcrypt
ImportError: ".../virtualenv/lib/python3.6/site-packages/bcrypt/_bcrypt.abi3.so:failed to map segment from shared object
```
/etc/httpd/conf/httpd.conf
```
LoadModule wsgi_module "/usr/lib64/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"
```
/etc/httpd/conf.modules.d/10-wsgi-python3.conf
```
<IfModule !wsgi_module>
LoadModule wsgi_module modules/mod_wsgi_python3.so
</IfModule>
```
Inside VirtualHost
`WSGIScriptAlias / /path/to/app.wsgi`

in /bin i have - mod_wsgi-express-3

/app.wsgi
```
activate_this = 'xxx/virtualenv/bin/activate_this.py'
with open(activate_this) as file_:
    exec(file_.read(), dict(__file__=activate_this))
import sys
sys.path.insert(0, "/xxx/")
from app import app as application

```
/requirements.txt (selected few)
```
bcrypt==3.2.0
paramiko==2.9.2
pysftp==0.2.9
```
/var/log/httpd/error_log
after activating venv (with activate_this) and entering flask py files...
```
[Mon Feb 07 14:00:45.815533 2022] [mpm_event:notice] [pid 2648590:tid 139731900242240] AH00492: caught SIGWINCH, shutting down gracefully
[Mon Feb 07 14:00:46.923117 2022] [core:notice] [pid 2649719:tid 139959780731200] SELinux policy enabled; httpd running as context system$
[Mon Feb 07 14:00:46.925733 2022] [suexec:notice] [pid 2649719:tid 139959780731200] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin$
[Mon Feb 07 14:00:46.948883 2022] [so:warn] [pid 2649719:tid 139959780731200] AH01574: module wsgi_module is already loaded, skipping
[Mon Feb 07 14:00:46.956015 2022] [lbmethod_heartbeat:notice] [pid 2649719:tid 139959780731200] AH02282: No slotmem from mod_heartmonitor
[Mon Feb 07 14:00:46.960651 2022] [mpm_event:notice] [pid 2649719:tid 139959780731200] AH00489: Apache/2.4.37 (Red Hat Enterprise Linux) $
[Mon Feb 07 14:00:46.960676 2022] [core:notice] [pid 2649719:tid 139959780731200] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

I can see that i LoadModule mod_wsgixxx multiple times, may that be the reason it says "module wsgi_module is already loaded, skipping" ? Not sure which is right/wrong.

Not sure if this error is because of mod_wsgi or Python versions colliding.
Any tips and help appriciated!

Note: Everything works fine when we run it locally and the webapp runs fine on the server without the "import pysftp"

**Comment by GrahamDumpleton** [comment]
Looks like you are trying to use mod_wsgi built using `pip install`, but at the same time never uninstalled the system mod_wsgi package. Thus why you have multiple LoadModule lines. You need to resolve that as you may actually be using a mod_wsgi built for a different version of Python than the Python virtual environment uses.

Beyond that, the message `failed to map segment from shared object` smells of a SELinux restriction. Search for that message in Google in conjunction with SELinux.

**Comment by GrahamDumpleton** [comment]
No further followup, so closing.
