### ISSUE TITLE
RuntimeError: The 'apxs' command appears not to be installed or is not executable

### ISSUE THREAD

**Issue by ionelmc** [GrahamDumpleton/mod_wsgi#76]
Short transcript:

First I make a new virtualenv:
```
$ virtualenv .vx
Ignoring indexes: https://pypi.python.org/simple
Collecting pip
Collecting setuptools
Installing collected packages: setuptools, pip


Successfully installed pip-6.0.8 setuptools-14.3.1
```
Then I install the httpd package:
```
$ .vx/bin/pip install mod_wsgi-httpd
Collecting mod-wsgi-httpd
  Using cached mod_wsgi-httpd-2.4.12.4.tar.gz
    apr-1.5.1/
    apr-1.5.1/libapr.mak
    apr-1.5.1/apr.mak
    apr-1.5.1/apr.spec

...
... lots of output ...
...

    adding  httpd/modules/mod_env.so
    adding  httpd/modules/mod_mime.so
    adding  httpd/modules/mod_status.so
    adding  httpd/__init__.py
    building 'mod_wsgi_packages.apxs._dummy' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c _module.c -o build/temp.linux-x86_64-2.7/_module.o
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/_module.o -o build/lib.linux-x86_64-2.7/mod_wsgi_packages/apxs/_dummy.so
    Installing mod_wsgi-apxs script to /home/ionel/test/.vx/bin
Successfully installed mod-wsgi-httpd-2.4.12.4
```
Looks fine.

But then mod_wsgi package can't find the apxs bin:
```
$ .vx/bin/pip install mod_wsgi
Collecting mod-wsgi
  Using cached mod_wsgi-4.4.10.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-Dmw1DB/mod-wsgi/setup.py", line 140, in <module>
        'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-Dmw1DB/mod-wsgi/setup.py", line 140, in <module>

        'missing Apache httpd server packages.' % APXS)

    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Dmw1DB/mod-wsgi
```

**Comment by ionelmc** [comment]
Activating the virtualenv seems to solve the issue but that's undesirable in my usecase :cry:

**Comment by GrahamDumpleton** [comment]
Besides activating the virtualenv, when running later pip install for mod_wsgi you should be able to do:

```
APXS=.vx/bin/mod_wsgi-apxs pip install mod_wsgi
```

It shouldn't be hard for me to fix the mod_wsgi setup.py so it also looks in the directory where 'python' interpreter used during installation comes from.

Will let you know when have something to try.

**Comment by GrahamDumpleton** [comment]
Believe fixed in 'develop' branch. Can try following to verify now works for you:

```
.vx/bin/pip uninstall mod_wsgi
.vx/bin/pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
```

**Comment by ionelmc** [comment]
Wohooo, it works!

**Comment by msampathkumar** [comment]
Friends,

I have similar problem with Python 2.7.3, Django 1.8 & Apache 7.0 in Windows 7;
Error: "'missing Apache httpd server packages.' % APXS)"
Note: I don't have root permission but I have above installed in my System.

Any advice please?

**Comment by GrahamDumpleton** [comment]
@msampathkumar Your problem is different. It is because you cannot use the pip installable mod_wsgi on Windows. You need to use precompiled binaries as described at:

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/win32/README.rst

**Comment by GrahamDumpleton** [comment]
You cannot use either the pip installable or configure/make/make install methods for building source code on Windows. Go read that Windows specific link. Use the precompiled binaries.

* https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/win32/README.rst

**Comment by Look-jie** [comment]
When I write  .vx/bin/pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
and I get the error  bash: .vx/bin/pip: No such file or directory .  What should I do ?

**Comment by GrahamDumpleton** [comment]
@Look-jle If you have a problem, create a separate issue, do not add to an existing one unless you are absolutely sure it is relevant.

That said, unless you think you have found a bug in mod_wsgi, you should really also use the mod_wsgi mailing list to get general installation help. Details of how to get help can be found at:

* http://modwsgi.readthedocs.io/en/develop/finding-help.html

Now in your case, your mistake is that you used ``.vx/bin/pip`` whereas that was a specific path unique to that particular user because of where they created a Python virtual environment. The ``pip`` command would normally be in your path, or in the ``bin`` directory of where you created your own Python virtual environment. Have you tried just ``pip install mod_wsgi``? Are you using a Python virtual environment? Follow up by using the mod_wsgi mailing list and not this issue.

**Comment by Look-jie** [comment]
OK. I check it now. thanks

**Comment by avinash070** [comment]
pip install mod_wsgi
Collecting mod_wsgi
  Using cached https://files.pythonhosted.org/packages/47/69/5139588686eb40053f8355eba1fe18a8bee94dc3efc4e36720c73e07471a/mod_wsgi-4.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rxcz47/mod-wsgi/setup.py", line 168, in <module>
        'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.

**Comment by Sudheertati** [comment]
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
Collecting https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
  Downloading https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
     - 3.1MB 7.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-mhm065jk-build/setup.py", line 168, in <module>
        'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'
    
    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-mhm065jk-build/setup.py", line 168, in <module>
        'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-mhm065jk-build/
root@tringappsadmin-Vostro-3546:~#

**Comment by GrahamDumpleton** [comment]
@Sudheertati Please create new issues rather than adding to an existing closed issue.

Also ensure you have installed the apache/httpd devel package for your system as explained in the system requirements at:

* https://pypi.org/project/mod-wsgi/

That is what the error message is telling you is missing.

Your operating system setup also appears to have a problem with it as well, in that it is missing Python packages used by `apport` system for reporting errors. You should separately resolve that as well.

If you need further help, please create a new issue first with details and what steps you have tried to resolve the error.

**Comment by Artemis21** [comment]
Sorry to bump an old thread, but for others coming here from Google - make sure you have `apache2-dev` installed as well as `apache2`. Massive facepalm.
