### ISSUE TITLE
wsgi not downloading

### ISSUE THREAD

**Issue by jesseasamoa** [GrahamDumpleton/mod_wsgi#762]
Constantly getting this error 
 raise RuntimeError('No Apache installation can be found. Set the '
    RuntimeError: No Apache installation can be found. Set the MOD_WSGI_APACHE_ROOTDIR environment to its location.

Kindly assist

**Comment by GrahamDumpleton** [comment]
You don't have Apache installed or it is in an unexpected location.

If you are on Windows, you need to have installed it, using ApacheLounge distribution, with it installed into "C:/Apache24".

What OS are you on? Is Apache installed?

Note that if on Linux you must have the dev package installed for Apache and not just the runtime package.

**Comment by jesseasamoa** [comment]
I’m using Windows and yes I have Apache installed. I tried setting WSGI to it as you mentioned in the thread before but still not working

**Comment by GrahamDumpleton** [comment]
What Apache distribution are you using?

Is it installed in "C:/Apache24" or did you install it elsewhere?

If you are setting `MOD_WSGI_APACHE_ROOTDIR` environment variable to say where Apache is installed, are you using a forward slash (you cannot use a backward slash) in the path?

**Comment by jesseasamoa** [comment]
It came with xampp download and currently in my xampp folder.

**Comment by jesseasamoa** [comment]
I copied the folder to C; and it worked now. Thanks

**Comment by GrahamDumpleton** [comment]
Did you ever set `MOD_WSGI_APACHE_ROOTDIR` in environment of shell when trying to install it?

**Comment by jesseasamoa** [comment]
Yes I did

**Comment by Geremyse** [comment]
Подскажите пожалуйста. На openserver использую Apache_2.4-PHP_7.2-7.4. Ставлю set "MOD_WSGI_APACHE_ROOTDIR=C:\ospanel\modules\http\Apache_2.4-PHP_7.2-7.4".
Но мне пишут, что не найден файл httpd.h. Очевидно, потому что его там нет нигде. Объясните, пожалуйста, что я делаю не так
