### ISSUE TITLE
Apache continuously reporting "python error: not main interpreter" on running django WSGI

### ISSUE THREAD

**Issue by Calvin-he** [GrahamDumpleton/mod_wsgi#765]
Apache run django WSGI in docker container. Here are the versions:

Apache version: 2.4.6

Python version: 3.10.4

mod_wsgi Version: 4.9.0

docker base image: centos-7.9.2009

httpd configuration:

```....
  LoadModule wsgi_module ${APP_ROOT_DIR}/common/conf/httpd/mod_wsgi-py310.cpython-310-x86_64-linux-gnu.so
  WSGIPythonHome /opt/python-3.10.4

  Alias /na/static/ ${APP_ROOT_DIR}/publish/
  <Directory ${APP_ROOT_DIR}>
    Require all granted
  </Directory>

  WSGIDaemonProcess portal python-home=/opt/python-3.10.4 processes=1 threads=10 display-name=%{GROUP} umask=027 socket-timeout=600
  WSGIScriptAlias /na ${APP_ROOT_DIR}/wsgi.py

  <Location /na>
    WSGIProcessGroup portal
  </Location>
......

```
Repeat the errors in file 'httpd-error_log' below continuously:

```
Extension modules: bson._cbson, pymongo._cmessage, cx_Oracle, pvectorc (total: 4)
Fatal Python error: _PyInterpreterState_DeleteExceptMain: not main interpreter
Python runtime state: initialized

Current thread 0x00007ff9d892d700 (most recent call first):
  File "/opt/python-3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 66 in _launch
  File "/opt/python-3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 19 in __init__
  File "/opt/python-3.10.4/lib/python3.10/multiprocessing/context.py", line 277 in _Popen
  File "/opt/python-3.10.4/lib/python3.10/multiprocessing/process.py", line 121 in start
  File "/opt/python-3.10.4/lib/python3.10/multiprocessing/pool.py", line 326 in _repopulate_pool_static
  File "/opt/python-3.10.4/lib/python3.10/multiprocessing/pool.py", line 337 in _maintain_pool
  File "/opt/python-3.10.4/lib/python3.10/multiprocessing/pool.py", line 513 in _handle_workers
  File "/opt/python-3.10.4/lib/python3.10/threading.py", line 946 in run
  File "/opt/python-3.10.4/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/opt/python-3.10.4/lib/python3.10/threading.py", line 966 in _bootstrap
```

**Comment by GrahamDumpleton** [comment]
Add:

```
WSGIApplicationGroup %{GLOBAL}
```

This will force the use of the main Python interpreter.

It looks like you are trying to use some Python package which is trying to create its own sub interpreters and expects to be run from the main interpreter context.

**Comment by Calvin-he** [comment]
> 
I am using the module "multiprocess.Pool" in my code.  Maybe it would be better that replaced it with the module 'multiprocess.dummy.Pool'
Thanks a lot

**Comment by Calvin-he** [comment]
> Add:
> 
> ```
> WSGIApplicationGroup %{GLOBAL}
> ```
> 
> This will force the use of the main Python interpreter.
> 
> It looks like you are trying to use some Python package which is trying to create its own sub interpreters and expects to be run from the main interpreter context.

I am using the module "multiprocess.Pool" in my code. Maybe it would be better that replaced it with the module 'multiprocess.dummy.Pool'
Thanks for your help and mention

**Comment by GrahamDumpleton** [comment]
Forking processes to do work in a web application (especially Apache) is generally not a good idea. It can cause problems with third party Python packages that don't do a good job with handling forking, especially when parent process is relying on multithreading.

So if you can I would suggest off loading processing to a separate job queueing system instead of trying to offload work to other processes by forking.
