### ISSUE TITLE
Disable support for TLS v1.1 and TLS v1.0

### ISSUE THREAD

**Issue by khalilahmed-dev** [GrahamDumpleton/mod_wsgi#768]
Hello there, 

First of all, THANK YOU SO MUCH for such an awesome utility. 

The only problem I've is that I'm using `mod_wsgi-express` with` Django 3.2` and` Python 3.10 ` in my current organization. 

I'm using HTTPS with CRT and key paths. The problem is when scanned by the security team, it shows that the support for TLS v1.0 is enabled (which is depreciated). Need your help in disabling TLS v1.1 and TLS v1.2.

The below are the issues that I need help with: 

```
- TLS Version 1.0 Protocol Detection
- HTTP TRACE / TRACK Methods Allowed
```

The command that I'm using for setting up the server is:

`
mod_wsgi-express setup-server django_wsgi.py --server-root FOLDER_PATH_FOR_DEPLOYMENT_FOLDER --user apache --group apache  --https-port 443 --https-only --server-name MY_SERVER_IP_HERE --ssl-certificate PATH_TO_MY_CRT_FILE --ssl-certificate-key-file PATH_TO_MY_KEY_FILE
`

Any help would be much appreciated, as I couldn't find any flag which I could for this. 

Thanks in advance.

**Comment by GrahamDumpleton** [comment]
That is dictated by Apache and not mod_wsgi. It is strange that your default Apache setup would allow such old encryption

To fix, create a file called `httpd.conf` and in it stick appropriate Apache directives to specify what you want allowed. See section "How can I create an SSL server which accepts strong encryption only?" in:

* https://httpd.apache.org/docs/trunk/ssl/ssl_howto.html

So if you used exactly what they had as an example, the file would contain:

```
# "Modern" configuration, defined by the Mozilla Foundation's SSL Configuration
# Generator as of August 2016. This tool is available at
# https://mozilla.github.io/server-side-tls/ssl-config-generator/
SSLProtocol         all -SSLv3 -TLSv1 -TLSv1.1
# Many ciphers defined here require a modern version (1.0.1+) of OpenSSL. Some
# require OpenSSL 1.1.0, which as of this writing was in pre-release.
SSLCipherSuite      ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
SSLHonorCipherOrder on
SSLCompression      off
SSLSessionTickets   off
```

I don't know if they are appropriate settings, so you would need to work out with your security team what they want used.

Once that is done, use the option `--include-file httpd.conf` to have mod_wsgi include that Apache configuration snippet into the generate Apache configuration file.

**Comment by khalilahmed-dev** [comment]
The `--include-file` parameter worked. Thanks !
