### ISSUE TITLE
Client Denied by Server Configuration

### ISSUE THREAD

**Issue by khalilahmed-dev** [GrahamDumpleton/mod_wsgi#770]
Hello there,

I'm using `Mod_wsgi-express` along with my `django 3.2`. 

I'm using the following command to run my server:

 `mod_wsgi-express setup-server django_wsgi.py --server-root PATH_HERE --user apache --group apache --https-port 443  --https-only --server-name MY_IP_HERE --ssl-certificate PATH_HERE --ssl-certificate-key-file PATH_HERE --include-file PATH_HERE/ssl.conf  --request-timeout 120 --access-log --access-log-format "%h %l %u %t \"%r\" %>s %b %D"`
 
 
It works perfectly if I'm accessing the server from the same IP that it is running on. But I have a requirement of setting up two servers for High Availability and load balance the requests. I ended up starting two servers on two different machines with same command just with a different IP in "--server-name" directive. Both servers were accessible individually. 
 
I created a virtual IP for load balancing the requests but when i try to access that IP, it gives` 403 forbidden` issue. and in the logs I see " Client denied by server configuration".
 
I tried a different thing and started both servers with "--server-name" set to my Virtual IP that I just created, I start getting` 404 page `instead of a normal working page ( like the one I was able to see with the individual IP). Is there something that I'm missing or how can this use case be achieved with mod_wsgi-express. 
 
 
 Any help would be appreciated. Thanks in advance.

**Comment by GrahamDumpleton** [comment]
You shouldn't be using an IP address for `--server-name`. It should be a fully qualified domain name (FQDN), ie., host name, which matches the host name that would appear in the URL that users use to access the site. If you are using a load balancer in front, it should be the hostname used in the URL for the frontend load balancer and same host name would be used for `--server-name` on both machines. Both backends should also use the same certificate with them issued against the host name for the front end load balancer if TLS SNI routing is being done in the load balancer (ie., pass through vs edge termination and re-encryption).

So question at this point it whether your load balancer is using TLS SNI routing or not. If it isn't and it is using edge termination and connection re-encryption then things will need to be different.
