### ISSUE TITLE
virtual host only work for ip visit, not domain visit

### ISSUE THREAD

**Issue by yekaizhou** [GrahamDumpleton/mod_wsgi#773]
Flask application deployed using mod_wsgi and apache2.

I have tried adding/replacing the domain name bio8.cs.hku.hk to the ServerName, but this setting can only take me to http://147.8.177.118/p-cardiac/, but not http://bio8.cs.hku.hk/p-cardiac/.

/etc/apache2/sites-available/p-cardiac.conf
```
<VirtualHost *:80>
    ServerName 147.8.177.118 # have tried adding/replace with bio8.cs.hku.hk but do not work
    WSGIDaemonProcess p-cardiac user=ykzhou group=www-data threads=5
    WSGIScriptAlias /p-cardiac /var/www/p-cardiac/app.wsgi
    <Directory /var/www/p-cardiac>
        WSGIProcessGroup p-cardiac
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>
    ErrorLog /var/www/p-cardiac/logs/error.log
    CustomLog /var/www/p-cardiac/logs/access.log combined
</VirtualHost>
```

/etc/hosts
```
127.0.0.1       localhost
127.0.1.1       bio8.cs.hku.hk  bio8
# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by GrahamDumpleton** [comment]
What happens if from the same box as Apache is running, you run:

```
curl -v -H Host:bio8.cs.hku.hk 127.0.1.1
```

BTW, you shouldn't have a trailing slash on `bio8.cs.hku.hk` in the `/etc/hosts` file.

**Comment by yekaizhou** [comment]
> 

Thanks a lot for your reply!

the trailing slash is a typo and actually the hosts do not have it.

the command will give me:
*   Trying 127.0.1.1:80...
* Connected to 127.0.1.1 (127.0.1.1) port 80 (#0)
> GET / HTTP/1.1
> Host:bio8.cs.hku.hk
> User-Agent: curl/7.82.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 20 May 2022 04:49:07 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Last-Modified: Fri, 29 Apr 2022 02:45:08 GMT
< ETag: "1e5d-5ddc207d59612"
< Accept-Ranges: bytes
< Content-Length: 7773
< Vary: Accept-Encoding
< Content-Type: text/html

follows the html script used in bio8.cs.hku.hk

**Comment by GrahamDumpleton** [comment]
Now what about:

```
curl -v -H Host:bio8.cs.hku.hk 127.0.1.1/p-cardiac
```

I should have said to specify the URL path before.

Ensure you have:

```
LogLevel info
```

set in the Apache configuration when you do this.

Do the messages in the Apache error log indicate mod_wsgi was triggered and your WSGI application loaded?

**Comment by yekaizhou** [comment]
Should I refer to the main apache conf or my app's conf?

**Comment by GrahamDumpleton** [comment]
You can put the `LogLevel` directive in the `VirtualHost` along with the ``ErrorLog`` directive. That should be enough, but if you put it at global scope it may show extra log messages from mod_wsgi which aren't connected to that specific virtual host, which might be useful.

**Comment by yekaizhou** [comment]
the output is as follows

*   Trying 127.0.1.1:80...
* Connected to 127.0.1.1 (127.0.1.1) port 80 (#0)
> GET /p-cardiac HTTP/1.1
> Host:bio8.cs.hku.hk
> User-Agent: curl/7.82.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Fri, 20 May 2022 05:05:48 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Content-Length: 276
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at bio8.cs.hku.hk Port 80</address>
</body></html>
* Connection #0 to host 127.0.1.1 left intact

**Comment by GrahamDumpleton** [comment]
Is that with `ServerName` set to `bio8.cs.hku.hk`?

If it was it suggests there is another `VirtualHost` that is taking precedence, or if you haven't enabled your site.

Does there exist a symbolic link at the location:

```
/etc/apache2/sites-enabled/p-cardiac.conf
```

which points to:

```
/etc/apache2/sites-available/p-cardiac.conf
```

In other words, did you run:

```
a2ensite p-cardiac
```

**Comment by yekaizhou** [comment]
server name is set to my ip, not bio8

i had symbolic link created and a2ensite p-cardiac enabled:

Site p-cardiac already enabled
'/etc/apache2/sites-enabled/p-cardiac.conf': File exists

**Comment by GrahamDumpleton** [comment]
I want you to do the test with ``ServerName`` set to ``bio8.cs.hku.hk``. That is, the same as `Host` value in `curl`.

**Comment by yekaizhou** [comment]
when set servername to bio8.cs.hku.hk, both http://147.8.177.118/p-cardiac and http://www.bio8.cs.hku.hk/p-cardiac/ fail to work

**Comment by GrahamDumpleton** [comment]
I need to see the output from curl. Specifically from running:

```
curl -v -H Host:bio8.cs.hku.hk http://127.0.1.1/p-cardiac
```

The entries in the `access.log` created would also be useful, as would any messages from the `error.log` triggered as a result of the request.

**Comment by yekaizhou** [comment]
the logs when servername set to bio8?

**Comment by GrahamDumpleton** [comment]
You provided the output from curl previously like I want to see but that time was with ServerName being the IP address. I want the same output but from when ServerName is bio8.cs.hku.hk.

At the same time as doing that, run:

```
tail -f /var/www/p-cardiac/logs/access.log
```

and:

```
tail -f /var/www/p-cardiac/logs/error.log
```

in two separate windows. That way you can see what is output in those log files in response to the curl request.

**Comment by yekaizhou** [comment]
when set servername to bio8

curl -v -H Host:bio8.cs.hku.hk http://127.0.1.1/p-cardiac:
```
*   Trying 127.0.1.1:80...
* Connected to 127.0.1.1 (127.0.1.1) port 80 (#0)
> GET /p-cardiac HTTP/1.1
> Host:bio8.cs.hku.hk
> User-Agent: curl/7.82.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Fri, 20 May 2022 05:43:56 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Content-Length: 276
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at bio8.cs.hku.hk Port 80</address>
</body></html>
* Connection #0 to host 127.0.1.1 left intact
```

tail -f /var/www/p-cardiac/logs/access.log
159.223.40.32 - - [20/May/2022:13:30:54 +0800] "GET /p-cardiac/sito/wp-includes/wlwmanifest.xml HTTP/1.1" 404 418 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
209.141.36.112 - - [20/May/2022:13:33:05 +0800] "GET / HTTP/1.1" 200 3214 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
101.227.1.198 - - [20/May/2022:13:33:06 +0800] "GET / HTTP/1.1" 200 3158 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
209.141.36.112 - - [20/May/2022:13:33:10 +0800] "GET /favicon.ico HTTP/1.1" 404 491 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
221.127.37.104 - - [20/May/2022:13:34:06 +0800] "GET /p-cardiac HTTP/1.1" 308 513 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
221.127.37.104 - - [20/May/2022:13:34:09 +0800] "GET /p-cardiac/ HTTP/1.1" 200 1483 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
49.44.67.171 - - [20/May/2022:13:34:15 +0800] "GET /p-cardiac HTTP/1.1" 308 476 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
95.168.222.10 - - [20/May/2022:13:34:16 +0800] "GET /p-cardiac HTTP/1.1" 308 476 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
49.44.67.171 - - [20/May/2022:13:34:17 +0800] "GET /p-cardiac/ HTTP/1.1" 200 1447 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
95.168.222.10 - - [20/May/2022:13:34:17 +0800] "GET /p-cardiac/ HTTP/1.1" 200 1447 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

tail -f /var/www/p-cardiac/logs/error.log
[Fri May 20 13:34:08.699706 2022] [wsgi:error] [pid 21569:tid 139987531872000]   from pandas import MultiIndex, Int64Index
[Fri May 20 13:43:23.489397 2022] [wsgi:info] [pid 21569:tid 139987632322432] mod_wsgi (pid=21569): Shutdown requested 'p-cardiac'.
[Fri May 20 13:43:23.489575 2022] [wsgi:info] [pid 21569:tid 139987632322432] mod_wsgi (pid=21569): Stopping process 'p-cardiac'.
[Fri May 20 13:43:23.489588 2022] [wsgi:info] [pid 21569:tid 139987632322432] mod_wsgi (pid=21569): Destroying interpreters.
[Fri May 20 13:43:23.489594 2022] [wsgi:info] [pid 21569:tid 139987632322432] mod_wsgi (pid=21569): Cleanup interpreter ''.
[Fri May 20 13:43:23.489622 2022] [wsgi:info] [pid 21569:tid 139987632322432] mod_wsgi (pid=21569): Terminating Python.
[Fri May 20 13:43:23.775757 2022] [wsgi:info] [pid 21569:tid 139987632322432] mod_wsgi (pid=21569): Python has shutdown.
[Fri May 20 13:43:23.775789 2022] [wsgi:info] [pid 21569:tid 139987632322432] mod_wsgi (pid=21569): Exiting process 'p-cardiac'.
[Fri May 20 13:43:24.645975 2022] [wsgi:info] [pid 21802:tid 140455552788352] mod_wsgi (pid=21802): Attach interpreter ''.
[Fri May 20 13:43:24.650664 2022] [wsgi:info] [pid 21802:tid 140455552788352] mod_wsgi (pid=21802): Imported 'mod_wsgi'.

**Comment by GrahamDumpleton** [comment]
The time stamp on curl request was:

```
Date: Fri, 20 May 2022 05:43:56 GMT
```

yet the last request in the access.log for that VirtualHost was:

```
20/May/2022:13:34:17 +0800
```

which was 9 minutes earlier.

Thus even though ServerName was set to bio8.cs.hku.hk that virtual host was not selected by Apache to handle the request.

This likely means you default virtual host for that Apache instance may have a ServerName setting for bio8.cs.hku.hk which is intercepting the requests.

What is the value of ServerName in global Apache configuration file and in the default virtual host.

What is in:

```
/etc/apache2/sites-enabled/000-default.conf
```

or if that file doesn't exist, what other files are in `/etc/apache2/sites-enabled`, ie., what names, and what is in them?

**Comment by yekaizhou** [comment]
yes we have 000-default.conf in the sites-enabled, along with p-cardiac.conf.
000-default.conf did not set a ServerName, but only DocumentRoot, WSGIScriptAlias, ProxyPass, ProxyPassReverse

**Comment by GrahamDumpleton** [comment]
In all probability that default virtual host is capturing the request. Tail the access log for that default virtual host if it has one, or the global access log if it doesn't, when making the curl request and if an entry shows up, that will confirm that is what is happening. Try then disabling the default virtual host and see whether your application you want to handle the request works or not.
