### ISSUE TITLE
how to use both mod_wsgi python version 2 and version 3 in the same server

### ISSUE THREAD

**Issue by yekaizhou** [GrahamDumpleton/mod_wsgi#774]
Hi

I have several websites using python 2 and lower version of mod_wsgi ran on my server previously.

Now I will have a new website using python 3 and higher version of mod_wsgi.

How can I solve the conflict to make both them work well?

**Comment by GrahamDumpleton** [comment]
You can't do it with one Apache instance.

The easiest thing to do is use `mod_wsgi-express` to run a separate Apache instance for separate Python version and then have the front facing Apache instance proxy to the other.

* https://pypi.org/project/mod-wsgi/
* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

Ignore that the blog posts mention docker, the mechanisms for proxying are the same.

**Comment by yekaizhou** [comment]
thanks for your reply.

so i should run `mod_wsgi-express start-server --port=(other than 80)` for my python 3 web app, and proxy it to the default python 2 apache2?

**Comment by GrahamDumpleton** [comment]
The existing system Apache is the one you would usually setup to proxy to mod_wsgi-express instance. That front end Apache would use whatever Python version the the existing mod_wsgi it was loading used. The mod_wsgi-express would use the other Python version.
