### ISSUE TITLE
Is it possible that environ['SCRIPT_NAME'] with Apache is cashed or something?

### ISSUE THREAD

**Issue by platipusica** [GrahamDumpleton/mod_wsgi#776]
Hi Graham, 

exactly the same applications, but in different non root folder, hence using WSGIScriptAliasMatch 
All working great, except randomly, part of the apps using environ SCRIPT_NAME is failing.

Code:
```
def server_export_task(task, url=None):
    url = task.environ['SCRIPT_NAME']
    return export_task(task, url)
.
.
def export_task(task, url):
.
.
        result_file = '%s_%s_%s_%s.zip' % (items.f_item_name.value, consts.VERSION,
            task.app.jam_version, datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S"))
        os.rename(to_unicode(file_name, 'utf-8'), os.path.join(to_unicode(result_path, 'utf-8'), to_unicode(result_file, 'utf-8')))
        if url:
            result = '%s/static/files/%s' % (url, result_file)
            print("this is the URL:" + url)
        else:
            result = result_file
.
.
```
The above if url is failing randomly. Any thoughts why sometimes SCRIPT_NAME is not picked up?

Thanks

**Comment by GrahamDumpleton** [comment]
Don't use ``WSGIScriptAliasMatch`` unless you absolutely have to. Use a proper WSGI framework instead if you need routing. Using ``WSGIScriptAliasMatch`` is really fiddly to get working properly, both in the Apache/mod_wsgi configuration parts, as well as fixups you need to do in your Python code to use it.

That said, I cannot really help unless you show the parts of the Apache/mod_wsgi configuration where you use ``WSGIScriptAliasMatch``, the WSGI application entry points, as well as what errors you are getting.

**Comment by platipusica** [comment]
Thanks!
I absolutely have to :) Hosting hundreds of apps, all working great. Each app is used very rarely and recycled after a month or so. But I can't tell if we will have 2 new apps today, or 20. Users create them, not me. It's a lab.
Hence all apps the the same. Except the data. Each user does not know anything about the other apps.

Each app "lives" in 32 random character folder, created on the fly. This is why WSGIScriptAliasMatch comes handy. I'll repeat, it works great. 
But above is failing randomly. Which means this minute it's working, the other minute does not. Thoughts?

We discussed it a year ago #677

**Comment by GrahamDumpleton** [comment]
Can you provide an example of the error and where you are seeing it?

**Comment by platipusica** [comment]
Sure:
```
[Thu May 26 05:01:34.465937 2022] [wsgi:error] [pid 145126] [remote [120.16.72.192:13444](http://120.16.72.192:13444/)]     return export_task(task, url)
[Thu May 26 05:01:34.465946 2022] [wsgi:error] [pid 145126] [remote [120.16.72.192:13444](http://120.16.72.192:13444/)]   File "/var/www/auth/jam-prod/lib/python3.8/site-packages/jam/admin/export_metadata.py", line 62, in export_task
[Thu May 26 05:01:34.465952 2022] [wsgi:error] [pid 145126] [remote [120.16.72.192:13444](http://120.16.72.192:13444/)]     os.rename(to_unicode(file_name, 'utf-8'), os.path.join(to_unicode(result_path, 'utf-8'), to_unicode(result_file, 'utf-8')))
[Thu May 26 05:01:34.465977 2022] [wsgi:error] [pid 145126] [remote [120.16.72.192:13444](http://120.16.72.192:13444/)] FileNotFoundError: [Errno 2] No such file or directory: 'task.zip' -> '/var/www/html/conv/upload/........this is the 32 chars folder...../static/files/TestApplication_1.0.0_5.4.113_2022-05-26_05-01-34.zip'```

hmm, which makes me thinking it is the wrong line I'm looking at, line 62 is os.rename, and not "if url"

Ok, pls leave it with me for now, I'll see what I can do.

Cheers

**Comment by GrahamDumpleton** [comment]
Don't rely on relative path names like `task.zip`. Always calculate an absolute path name. This is because you can't guarantee what the current working directory of the process will be. Worse is to rely on being able to change the current working directory because when you have multi threading separate requests will interfere with each other as mod_wsgi uses separate threads for requests. Read:

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#application-working-directory

Also, if ``file_name`` is obtained through a form input supplied by the user you need to make sure you sanitize the path name to avoid people supplying values such as ``../../../etc/passwd`` and try and directory traversal attacks. Read:

* https://en.wikipedia.org/wiki/Directory_traversal_attack
