### ISSUE TITLE
Recent step by step for windows ?

### ISSUE THREAD

**Issue by JMauperin** [GrahamDumpleton/mod_wsgi#778]
Hello everyone,

I'm currently trying to deploy a django application on a windows server.
I found a lot of guides, none of them is really recent and none of them work. Does anyone have a step by step for a django app developped in Django 4 with python 3.10.2 to be deployed on windows (apache or IIS, whatever works) ?

Thank you

**Comment by GrahamDumpleton** [comment]
Suggest trying the Django community. I have no idea what they recommend as best practice for Windows these days. My personal opinion is that Windows is not a good platform for doing Python web application deployment. If have to use Windows, use the Windows subsystem for Linux instead. Also ask on StackOverflow for advice.

**Comment by JMauperin** [comment]
Thanks for the advice. I'll do that.

Yeah I know Windows is not a really good choice, and it's really easy on Linux but the choice is currently not mine 😅.

See ya !
