### ISSUE TITLE
Problem with mod_wsgi python3.10 with django in apache2

### ISSUE THREAD

**Issue by WalidAxo** [GrahamDumpleton/mod_wsgi#779]
Hi Team, 

I'm currently trying to deploy a django app with mod_wsgi in apache2. 
I followed this steps : 

1 - installing python3.10 from source with '--enable-shared' 
2 - compiling and installing the last version of mod_wsgi from source 
3 - Load the mod_wsgi in apache2 
4 - created a virtual environment with 'python - m venv' 
5 - created a simple django project 
6 - Added my user to the the same group as appache2 www-data

7 - **The configuration of apache in sites-available** : 

` <VirtualHost *:80>
        Alias /static /home/walidy/django-project/site/public/static
        <Directory /home/walidy/django-project/site/public/static>
                Require all granted
        </Directory>

        ErrorLog /home/walidy/django-project/site/logs/error/log
        CustomLog /home/walidy/django-project/site/logs/acess.log combine

        <Directory /home/walidy/django-project/src/tutorial>
                Require all granted
        </Directory>

        WSGIScriptAlias / /home/walidy/django-project/src/tutorial/wsgi.py

        WSGIDaemonProcess tutorial user=walidy group=walidy python-home=/home/walidy/django-project/venv python-path=/home/walidy/django-project/venv/lib/python3.10/site-packages
        WSGIProcessGroup tutorial
        WSGIApplicationGroup %{GLOBAL}
</VirtualHost>`

8 - The content of wsgi.py : 

`import os, sys
from django.core.wsgi import get_wsgi_application
sys.path.insert(0,'/home/walidy/django-project/venv/lib/python3.10/site-packages')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tutorial.settings')
application = get_wsgi_application()`

Unfortunately,  when I try to access to the web page, I get "500 Internal server error". After checking the logs, I get "ModuleNotFoundError" : no module named 'tutorial' (with 'tutorial' being the name of the django project I created).
I'll attache the log files [:](https://drive.google.com/file/d/1ePbjfBp0c_7BfM-5hSbUptL4X-W_CkDu/view?usp=sharing)

When i delete the content of "wsgi.py' and put the code ; 
`def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!'

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]`

**It works** 

Any idea on how to make the first project works ? I have tried every tutorial I found (I'm ashamed to say that I'm stuck with this problem for more than 4 days). 
Thanks in advance

**Comment by GrahamDumpleton** [comment]
You aren't setting ``python-path`` option correctly. It needs to be the parent directory of the Django project, possibly:

```
python-path=/home/walidy/django-project
```

in your case.

Check what the Django docs says again.

* https://docs.djangoproject.com/en/4.0/howto/deployment/wsgi/modwsgi/

You should never need to add `site-packages` explicitly to anything.

**Comment by GrahamDumpleton** [comment]
Could possibly need to be:

```
python-path=/home/walidy/django-project/src
```

I don't know how you have structured things to know for sure.

**Comment by walidyounes** [comment]
Hello Graham, 

Thank you for your response.  

I have tried to change python-path to different paths but I kept getting the same error 'ModuleNotFound'.  I know that it's something related to paths cause when I replaced the content of wsgi.py (to a python code "Hello word"), it works.  

I structured the project as follow : 
/home/walidy/django-project/  # --> the working directory   
⎜- site 
⎜   |- logs 
 |    | - public 
 |    |    |- media 
 |    |    |- static
 | - src 
 |    | - manage.py 
 |    | - tutorial 
 |         | - wsgi.py
 | - venv



I don't know if it's relevant but when I tried to print which interpreter wsgi was using (following a tutorial on the official mod_wsgi website) I got **"Walid-PC.local |"**  I think the interpreter is " " (which is the first element of sys.path)  but I thought that doing `sys.path.insert(0,'/home/walidy/django-project/venv/lib/python3.10/site-packages')` will change the interpreter.  

I have also read that maybe mod_wsgi doesn't work with python3.10, is it true ? 

Thank You in advance for you help. 

Have a nice day. 

Best regards
