### ISSUE TITLE
mod_wsgi-standalone installation failing

### ISSUE THREAD

**Issue by galexandre** [GrahamDumpleton/mod_wsgi#781]
Hello, 
I hope you are keeping well. 
I am facing an issue with the installation of `mod_wsgi-standalone` in multiple environments (Mac and EC2 instance). Apache is not installed on both machine. The error log is the same: 
```
 sh: ./configure: Permission denied
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-kim14b5i/mod-wsgi-httpd/setup.py", line 74, in <module>
          raise RuntimeError('Failed to build APR.')
      RuntimeError: Failed to build APR.
```
Python 3.8 is used in both cases.
Is there anything I should install prior to this package? It would be great to avoid to have to install an instance of Apache.

**Comment by GrahamDumpleton** [comment]
It is a known problem that it will not install on macOS. Apple broke the ability to build APR there. I am not aware of issues on Linux. You would need to run `pip` with sufficient `-v` options to get verbose logging to see what the error is.

**Comment by galexandre** [comment]
Thank you for your answer. Related to the Mac issue, I guess the best would be to update the documentation of the program to mention that. For the EC2 instance (using the AWS distro) I will continue to debug and update this issue.

**Comment by GrahamDumpleton** [comment]
The mod_wsgi-standalone package is only intended as a last resort since the Apache version it uses is often not the latest.

You should always use system Apache if you can, and on macOS you can use Homebrew Apache if don't want to use Apple Apache.
