### ISSUE TITLE
Unable to compile and make mod_wsgi under python 2.6.9

### ISSUE THREAD

**Issue by gsaray101** [GrahamDumpleton/mod_wsgi#79]
I have install apache2 and apache2-devel on suse 11.3. OS. I am trying to compile and install mod_wsgi-develop. I unzip the file and performed this:

./configure --with-python=/usr/bin/python --with-apxs=/usr/sbin/apxs2

I get these:
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for prctl... yes
checking Apache version... 2.2.12
configure: creating ./config.status
config.status: creating Makefile

then, I issue make command, get these:

/usr/sbin/apxs2 -c -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -Wc,-g -Wc,-O2  src/server/mod_wsgi.c src/server/wsgi_*.c -L/usr/lib64 -L/usr/lib64/python2.6/config  -lpython2.6 -lpthread -ldl  -lutil -lm
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/mod_wsgi.lo src/server/mod_wsgi.c && touch src/server/mod_wsgi.slo
In file included from src/server/wsgi_apache.h:74,
                 from src/server/mod_wsgi.c:21:
/usr/include/apache2/mpm_common.h:46:17: error: mpm.h: No such file or directory
In file included from /usr/include/python2.6/Python.h:8,
                 from src/server/wsgi_python.h:24,
                 from src/server/mod_wsgi.c:22:
/usr/include/python2.6/pyconfig.h:1067:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/sys/types.h:27,
                 from /usr/include/apr-1/apr.h:127,
                 from /usr/include/apache2/ap_config.h:25,
                 from /usr/include/apache2/httpd.h:43,
                 from src/server/wsgi_apache.h:38,
                 from src/server/mod_wsgi.c:21:
/usr/include/features.h:158:1: warning: this is the location of the previous definition
In file included from /usr/include/python2.6/Python.h:8,
                 from src/server/wsgi_python.h:24,
                 from src/server/mod_wsgi.c:22:
/usr/include/python2.6/pyconfig.h:1079:1: warning: "_XOPEN_SOURCE" redefined
In file included from /usr/include/sys/types.h:27,
                 from /usr/include/apr-1/apr.h:127,
                 from /usr/include/apache2/ap_config.h:25,
                 from /usr/include/apache2/httpd.h:43,
                 from src/server/wsgi_apache.h:38,
                 from src/server/mod_wsgi.c:21:
/usr/include/features.h:160:1: warning: this is the location of the previous definition
src/server/mod_wsgi.c: In function ‘wsgi_set_accept_mutex’:
src/server/mod_wsgi.c:7379: error: ‘ap_accept_lock_mech’ undeclared (first use in this function)
src/server/mod_wsgi.c:7379: error: (Each undeclared identifier is reported only once
src/server/mod_wsgi.c:7379: error: for each function it appears in.)
src/server/mod_wsgi.c: In function ‘wsgi_setup_access’:
src/server/mod_wsgi.c:7782: error: ‘ap_coredumpdir_configured’ undeclared (first use in this function)
apxs:Error: Command failed with rc=65536
.
make: *** [src/server/mod_wsgi.la] Error 1

Any ideas what might be going on here?

**Comment by GrahamDumpleton** [comment]
You are using an absolutely ancient Apache 2.2 version which shouldn't be used any more. If you really can't use a newer Apache version, then try mod_wsgi 3.5.

**Comment by gsaray101** [comment]
I tried to install 3.5, still having issues when I ran ./configure. Is there any option provided to configure to compile?

**Comment by gsaray101** [comment]
I have a different server with the same setup, I was able to compile and install mod_wsgi but forgot I how I did it. I can send you the errors.

**Comment by GrahamDumpleton** [comment]
Looking at your errors again, the problem appears more to be that you do not have the proper Apache development packages installed or they are broken or wrong versions.

What is the list of Apache packages you have installed on your system?

**Comment by gsaray101** [comment]
these are the listed packages:

S | Name                                  | Summary                                                    | Type
--+---------------------------------------+------------------------------------------------------------+--------
i | apache2                               | The Apache Web Server Version 2.2                          | package
i | apache2-devel                         | Apache 2.0 Header and Include Files                        | package
i | apache2-mod_python                    | A Python Module for the Apache 2 Web Server                | package
i | apache2-prefork                       | Apache 2 &quot;prefork&quot; MPM (Multi-Processing Module) | package
i | apache2-utils                         | Apache 2 utilities                                         | package
i | apache2-worker                        | Apache 2 worker MPM (Multi-Processing Module)              | package
i | sdksp3-CL-apache2-8138                | Security update for Apache2                                | patch
i | sdksp3-CL-apache2-8738                | Recommended update for apache2                             | patch
i | sdksp3-CL-apache2-9542                | Security update for the Apache Web Server                  | patch
i | sdksp3-CL-apache2-9720                | Recommended update for apache2                             | patch
i | sdksp3-CL-apache2-mod_python-10272    | Recommended update for apache2-mod_python                  | patch
i | slessp3-CL-apache2-8138               | Security update for Apache2                                | patch
i | slessp3-CL-apache2-8738               | Recommended update for apache2                             | patch
i | slessp3-CL-apache2-9542               | Security update for the Apache Web Server                  | patch
i | slessp3-CL-apache2-9720               | Recommended update for apache2                             | patch
i | slessp3-CL-apache2-mod_apparmor-10133 | Recommended update for AppArmor                            | patch
i | slessp3-CL-apache2-mod_apparmor-8068  | Recommended update for AppArmor                            | patch
i | slessp3-CL-apache2-mod_apparmor-8471  | Recommended update for apparmor                            | patch
i | slessp3-CL-apache2-mod_python-10272   | Recommended update for apache2-mod_python                  | patch

**Comment by GrahamDumpleton** [comment]
The apache2-devel package says it is for Apache 2.0, not 2.2. Update your Apache packages.

BTW, you cannot run mod_wsgi 4.X with mod_python.

**Comment by gsaray101** [comment]
should I remobe mod_python?

**Comment by GrahamDumpleton** [comment]
So long as you haven't enabled the module so that Apache is loading it you should be okay.

**Comment by gsaray101** [comment]
I do have apache2-devel version 2.2 as you see below:

Refreshing service 'spacewalk'.
Loading repository data...
Reading installed packages...
No update candidate for 'apache2-devel-2.2.12-1.50.1.x86_64'. The highest available version is already installed.
Resolving package dependencies..

**Comment by GrahamDumpleton** [comment]
Why does the listing you gave have:

```
i | apache2-devel | Apache 2.0 Header and Include Files | package
```

Thus it shows Apache 2.0.

Either way, the 'mpm.h' header file should still have been a part of Apache 2.0, so either something is broken in your installation or there is some other Suse package for Apache development required which is specific to the Apache MPM used. That you even have two packages, one for prefork MPM and one for worker MPM is quite odd as normally for older Apache versions where dynamic MPMs are not available, you can only have one installed at a time.

See if you can work out using Suse tools what package the 'mpm.h' header file is actually mean't to be in.

**Comment by gsaray101** [comment]
1. I downloaded version: mod_wsgi-3.5 2. verified that apache2 and apache2-devel installed3. untarred it and configured it as this: ./configure --with-apxs=/usr/sbin/apxs2-worker4. then make and make installed. I see the this file created: /usr/lib64/apache2-worker/mod_wsgi.so5. ldd  /usr/lib64/apache2-worker/mod_wsgi.so, shows these:

 linux-vdso.so.1 =>  (0x00007fffb517d000)        libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007f8f9db7a000)        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8f9d95d000)        libdl.so.2 => /lib64/libdl.so.2 (0x00007f8f9d758000)        libutil.so.1 => /lib64/libutil.so.1 (0x00007f8f9d555000)        libm.so.6 => /lib64/libm.so.6 (0x00007f8f9d2dc000)        libc.so.6 => /lib64/libc.so.6 (0x00007f8f9cf5f000)        /lib64/ld-linux-x86-64.so.2 (0x00007f8f9e153000)
Is this right?  


     On Saturday, May 23, 2015 6:03 AM, Graham Dumpleton <notifications@github.com> wrote:
   

 Why does the listing you gave have:i | apache2-devel | Apache 2.0 Header and Include Files | package
Thus it shows Apache 2.0.Either way, the 'mpm.h' header file should still have been a part of Apache 2.0, so either something is broken in your installation or there is some other Suse package for Apache development required which is specific to the Apache MPM used. That you even have two packages, one for prefork MPM and one for worker MPM is quite odd as normally for older Apache versions where dynamic MPMs are not available, you can only have one installed at a time.See if you can work out using Suse tools what package the 'mpm.h' header file is actually mean't to be in.—

**Comment by GrahamDumpleton** [comment]
Presuming your Apache installation is built with the 'worker' MPM then yes, looks okay from what I can tell.

I guess the key here is that you use 'apxs-worker' this time. Maybe 'apxs' is for Apache 1.3 or prefork MPM.

**Comment by gsaray101** [comment]
@GrahamDumpleton, I was able to compile mod_wsgi, as you can see below:

file /usr/lib64/apache2-worker/mod_wsgi.so
/usr/lib64/apache2-worker/mod_wsgi.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped

ldd /usr/lib64/apache2-worker/mod_wsgi.so linux-vdso.so.1 => (0x00007fffdeb54000)
        libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007f1a31b26000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1a31909000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1a31704000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f1a31501000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f1a31288000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f1a30f0b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1a320ff000)

but I dont see any python libraries for mod_wsj as this:

local/lib64/python2.6/site-packages/mod_wsgi-4.3.0-py2.6-linux-x86_64.egg # ls
EGG-INFO  mod_wsgi

so, it is not integrated with python. How could I compile mod_wsgi source so that it integrates with python? Any ideas? I needs that egg file so that my django server can execute mod_wsgi.

**Comment by gsaray101** [comment]
Also, I do see mpm.h files as seen below:

339324    4 -rw-r--r--   1 root     root         2011 Sep 11  2014 /usr/include/apache2-event/mpm.h
339372    4 -rw-r--r--   1 root     root         2035 Sep 11  2014 /usr/include/apache2-prefork/mpm.h
339420    4 -rw-r--r--   1 root     root         2013 Sep 11  2014 /usr/include/apache2-worker/mpm.h

**Comment by gsaray101** [comment]
@GrahamDumpleton, any ideas? I really need mod_wsgi compiled and working for my app, otherwise, it wont work.

**Comment by gsaray101** [comment]
@GrahamDumpleton, I am really for all of these post. Again, I was able to compile it with  ./configure --with-apxs=/usr/sbin/apxs2-worker --with-python=/usr/bin/python2.6

from the output, can you tell what is going on. I am trying to use this mod in apache, but still getting these errors:

[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25] Traceback (most recent call last):
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25]   File "/opt/graphite/conf/graphite.wsgi", line 4, in <module>
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25]     from graphite.wsgi import application
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25] ImportError: No module named wsgi
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25] mod_wsgi (pid=50301): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25] mod_wsgi (pid=50301): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25] Traceback (most recent call last):
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25]   File "/opt/graphite/conf/graphite.wsgi", line 4, in <module>
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25]     from graphite.wsgi import application
[Tue May 26 13:18:56 2015] [error] [client 29.0.122.25] ImportError: No module named wsgi



===This is the compilation and installation output

 ./configure --with-apxs=/usr/sbin/apxs2-worker --with-python=/usr/bin/python2.6
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for prctl... yes
checking Apache version... 2.2.12
configure: creating ./config.status
config.status: creating Makefile


server001:/app/data.1/files/mod_wsgi-4.3.0 # make
/usr/sbin/apxs2-worker -c -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -Wc,-g -Wc,-O2  src/server/mod_wsgi.c src/server/wsgi_*.c -L/usr/lib64 -L/usr/lib64/python2.6/config  -lpython2.6 -lpthread -ldl  -lutil -lm
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/mod_wsgi.lo src/server/mod_wsgi.c && touch src/server/mod_wsgi.slo
In file included from /usr/include/python2.6/Python.h:8,
                 from src/server/wsgi_python.h:24,
                 from src/server/mod_wsgi.c:22:
/usr/include/python2.6/pyconfig.h:1067:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/sys/types.h:27,
                 from /usr/include/apr-1/apr.h:127,
                 from /usr/include/apache2-worker/ap_config.h:25,
                 from /usr/include/apache2-worker/httpd.h:43,
                 from src/server/wsgi_apache.h:38,
                 from src/server/mod_wsgi.c:21:
/usr/include/features.h:158:1: warning: this is the location of the previous definition
In file included from /usr/include/python2.6/Python.h:8,
                 from src/server/wsgi_python.h:24,
                 from src/server/mod_wsgi.c:22:
/usr/include/python2.6/pyconfig.h:1079:1: warning: "_XOPEN_SOURCE" redefined
In file included from /usr/include/sys/types.h:27,
                 from /usr/include/apr-1/apr.h:127,
                 from /usr/include/apache2-worker/ap_config.h:25,
                 from /usr/include/apache2-worker/httpd.h:43,
                 from src/server/wsgi_apache.h:38,
                 from src/server/mod_wsgi.c:21:
/usr/include/features.h:160:1: warning: this is the location of the previous definition
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_apache.lo src/server/wsgi_apache.c && touch src/server/wsgi_apache.slo
In file included from /usr/include/python2.6/Python.h:8,
                 from src/server/wsgi_python.h:24,
                 from src/server/wsgi_daemon.h:24,
                 from src/server/wsgi_apache.c:23:
/usr/include/python2.6/pyconfig.h:1067:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/sys/types.h:27,
                 from /usr/include/apr-1/apr.h:127,
                 from /usr/include/apache2-worker/ap_config.h:25,
                 from /usr/include/apache2-worker/httpd.h:43,
                 from src/server/wsgi_apache.h:38,
                 from src/server/wsgi_apache.c:21:
/usr/include/features.h:158:1: warning: this is the location of the previous definition
In file included from /usr/include/python2.6/Python.h:8,
                 from src/server/wsgi_python.h:24,
                 from src/server/wsgi_daemon.h:24,
                 from src/server/wsgi_apache.c:23:
/usr/include/python2.6/pyconfig.h:1079:1: warning: "_XOPEN_SOURCE" redefined
In file included from /usr/include/sys/types.h:27,
                 from /usr/include/apr-1/apr.h:127,
                 from /usr/include/apache2-worker/ap_config.h:25,
                 from /usr/include/apache2-worker/httpd.h:43,
                 from src/server/wsgi_apache.h:38,
                 from src/server/wsgi_apache.c:21:
/usr/include/features.h:160:1: warning: this is the location of the previous definition
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_buckets.lo src/server/wsgi_buckets.c && touch src/server/wsgi_buckets.slo
src/server/wsgi_buckets.c: In function ‘wsgi_python_bucket_setaside’:
src/server/wsgi_buckets.c:151: warning: format ‘%lld’ expects type ‘long long int’, but argument 3 has type ‘apr_off_t’
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_convert.lo src/server/wsgi_convert.c && touch src/server/wsgi_convert.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_daemon.lo src/server/wsgi_daemon.c && touch src/server/wsgi_daemon.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_interp.lo src/server/wsgi_interp.c && touch src/server/wsgi_interp.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_logger.lo src/server/wsgi_logger.c && touch src/server/wsgi_logger.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_metrics.lo src/server/wsgi_metrics.c && touch src/server/wsgi_metrics.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_restrict.lo src/server/wsgi_restrict.c && touch src/server/wsgi_restrict.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_server.lo src/server/wsgi_server.c && touch src/server/wsgi_server.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_stream.lo src/server/wsgi_stream.c && touch src/server/wsgi_stream.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2-worker  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -I/usr/include/python2.6 -DNDEBUG -D_FORTIFY_SOURCE=2  -c -o src/server/wsgi_validate.lo src/server/wsgi_validate.c && touch src/server/wsgi_validate.slo
/usr/lib64/apr-1/build/libtool --silent --mode=link gcc -o src/server/mod_wsgi.la  -rpath /usr/lib64/apache2-worker -module -avoid-version    src/server/wsgi_validate.lo src/server/wsgi_stream.lo src/server/wsgi_server.lo src/server/wsgi_restrict.lo src/server/wsgi_metrics.lo src/server/wsgi_logger.lo src/server/wsgi_interp.lo src/server/wsgi_daemon.lo src/server/wsgi_convert.lo src/server/wsgi_buckets.lo src/server/wsgi_apache.lo src/server/mod_wsgi.lo -L/usr/lib64 -L/usr/lib64/python2.6/config -lpython2.6 -lpthread -ldl -lutil -lm


server001:/app/data.1/files/mod_wsgi-4.3.0 # make install
/usr/sbin/apxs2-worker -i -S LIBEXECDIR=/usr/lib64/apache2-worker -n 'mod_wsgi' src/server/mod_wsgi.la
/usr/share/apache2/build/instdso.sh SH_LIBTOOL='/usr/lib64/apr-1/build/libtool' src/server/mod_wsgi.la /usr/lib64/apache2-worker
/usr/lib64/apr-1/build/libtool --mode=install cp src/server/mod_wsgi.la /usr/lib64/apache2-worker/
cp src/server/.libs/mod_wsgi.so /usr/lib64/apache2-worker/mod_wsgi.so
cp src/server/.libs/mod_wsgi.lai /usr/lib64/apache2-worker/mod_wsgi.la
PATH="$PATH:/sbin" ldconfig -n /usr/lib64/apache2-worker
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/lib64/apache2-worker

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
chmod 755 /usr/lib64/apache2-worker/mod_wsgi.so


server001:/app/data.1/files/mod_wsgi-4.3.0 # ldd /usr/lib64/apache2-worker/mod_wsgi.so
        linux-vdso.so.1 =>  (0x00007fff01d5a000)
        libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007f61874f7000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f61872da000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f61870d5000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f6186ed2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f6186c59000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f61868dc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6187ada000)

**Comment by gsaray101** [comment]
@GrahamDumpleton, when I compiled mod_wsgi, I only see mod_wsgi.so. Should't there be these as well:

/usr/local/lib64/python2.6/site-packages/mod_wsgi-4.3.1-py2.6-linux-x86_64.egg/mod_wsgi/server # ls -l
total 756
-rwxrwxrwx 1 root root  71465 Oct 28  2014 __init__.py
-rwxrwxrwx 1 root root  63944 Oct 28  2014 __init__.pyc
-rwxrwxrwx 1 root root    220 Oct 28  2014 apxs_config.py
-rwxrwxrwx 1 root root    510 Oct 28  2014 apxs_config.pyc
drwxrwxrwx 3 root root   4096 Oct 28  2014 management
-rwxrwxrwx 1 root root    264 Oct 28  2014 mod_wsgi-py26.py
-rwxrwxrwx 1 root root    660 Oct 28  2014 mod_wsgi-py26.pyc
-rwxrwxrwx 1 root root 598654 Oct 28  2014 mod_wsgi-py26.so

**Comment by GrahamDumpleton** [comment]
The pip installable mod_wsgi is completed unrelated to using the system Apache and compiling mod_wsgi from source code using configure/make.

If you current issue is still:

```
ImportError: No module named wsgi
```

then what is the 'graphite' package module you are trying to use.

Just before the line:

```
from graphite.wsgi import application
```

add:

```
import graphite
print 'GRAPHITE', graphite.__file__
```

This will tell you where the 'graphite' package/module is being picked up from. You can then validate if it is what you expect to be imported and whether it even has in it a 'wsgi' object or sub module.

One possibility is that you have inadvertently created a graphite.py file which is shadowing the proper package you expect to import.

**Comment by GrahamDumpleton** [comment]
Closing at this point as no further followup and looks to be more an application setup issue.
