### ISSUE TITLE
Flask Apache Start Fails with Permission Denied

### ISSUE THREAD

**Issue by mbasith** [GrahamDumpleton/mod_wsgi#792]
I am trying to install Flask on my CentOS 7.9.2009 VM running Apache HTTP Server. I've installed Python3.8 and mod_wsgi but when I attempt to start Apache I get the below Permissioned denied when loading the mod_wsgi. I've checked multiple blogs and forums and cannot find a resolution. Any idea why I am getting this error?

Error: cannot open shared object file: Permission denied

`httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/02-wsgi.conf: Cannot load /home/myuser/.local/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so into server: /home/myuser/.local/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so: cannot open shared object file: Permission denied`

I installed python3.8 from source using `./configure --enable-optimizations --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"` but I am still getting the above permission denied error.

Below is how my app.conf file looks like and also output of mod_wsgi module-config.

app.conf:

`LoadModule wsgi_module "/home/myuser/.local/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so"`

mod_wsgi module-config:

```
[myuser@mycentos conf.d]$ mod_wsgi-express module-config
LoadModule wsgi_module "/home/myuser/.local/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so"
WSGIPythonHome "/usr/local"
```
I get the error when I try to start Apache - sudo systemctl start httpd.

**Comment by GrahamDumpleton** [comment]
Most likely SELinux is enabled and is blocking you. You will need to configure SELinux to allow you to map a shared library from that location.

**Comment by mbasith** [comment]
Wow! Didn't expect such a quick response. Thank you so much, that was indeed the issue. I disabled it for now to get my app to work.  Do you have any references to allow me to map to a shared library?

**Comment by GrahamDumpleton** [comment]
Search for "SElinux enable use of shared library". Eg:

* https://lists.fedoraproject.org/archives/list/test@lists.fedoraproject.org/thread/X53J657TUEOSJXBWZKWL76QUMBULXFEL/
*

**Comment by GrahamDumpleton** [comment]
Actually, this way is the proper way.

* https://bugzilla.redhat.com/show_bug.cgi?id=514506

**Comment by mbasith** [comment]
Thanks Mr. Graham Dumpleton! Closing this thread.
