### ISSUE TITLE
ModuleNotFoundError: No module named 'encodings' Debian Buster + Apache2

### ISSUE THREAD

**Issue by gentooza** [GrahamDumpleton/mod_wsgi#793]
OS: 
Debian Buster
python versions installed: 2.7, 3.7, (manually)3.5
Apache2
libapache2-mod-wsgi-py3

myApp:
Using Django app under python3.5 with it's virtual environment.

I got this error I already found in issues, for the moment I've fixed it creating a new virtual environment under python3.7, installing wsgi with pip there, and changing the wsgi.load from apache for loading it. (as said in documentation [https://pypi.org/project/mod-wsgi/](https://pypi.org/project/mod-wsgi/]) I followed instructions of issue #755

This drove me crazy! I've tried also using the system wide mod-wsgi with the python3.7 calling it's virtual environment with no success.

The problem is this solution can't be definitive for me, as I'm going to host several django apps with their custom virtual environments each.

what can I do? why the problem as I think I've tried Debian standards?

cheers!

**Comment by GrahamDumpleton** [comment]
The mod_wsgi module loaded by Apache must be compiled for the specific Python version you want to use. You can't for example use system `libapache2-mod-wsgi-py3` if it was built for system Python (3.7), with a virtual environment created using self installed Python 3.5.

So answer the following questions.

What is the version of the system Python?

What version of Python `libapache2-mod-wsgi-py3` is compiled for. To determine this see:

* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-shared-library
* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use

What version of Python you want to use for your application and thus what version your virtual environment is created using?

Note that a single Apache/mod_wsgi can only work with a single Python version. You cannot use different applications with different Python versions (virtual environment) at the same time. If you really needed this, you should use mod_wsgi-express and run distinct Apache instances using it behind a front end Apache.

Answer those questions first and can then maybe suggest next thing to look at.

**Comment by gentooza** [comment]
Hi @GrahamDumpleton , and thanks for your time! I tell you:

> The mod_wsgi module loaded by Apache must be compiled for the specific Python version you want to use. You can't for example use system libapache2-mod-wsgi-py3 if it was built for system Python (3.7), with a virtual environment created using self installed Python 3.5.
> What is the version of the system Python?

> What version of Python libapache2-mod-wsgi-py3 is compiled for. To determine this see: [...]

Yes, I imagined that, but I changed the original virtual environment with python 3.5 to a new one with python 3.7 and didn't work either.
The Debian Buster installed python versions are 2.7 and 3.7 [link to debian docs](https://wiki.debian.org/Python#Supported_Python_Versions)

system wide mod_wsgi tells me that:
```
root@vps:~# ldd /usr/lib/apache2/modules/mod_wsgi.so
	linux-vdso.so.1 (0x00007ffdfc1f7000)
	libpython3.7m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0 (0x00007f5cdfb6b000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f5cdfb31000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5cdfb10000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5cdfb0b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f5cdfb06000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5cdf983000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5cdf7c1000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f5cdf784000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5cdf766000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5ce00b3000)
```

and it works with custom wsgi script:
```
sys.version = '3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]'
sys.prefix = '/var/www/clients/client30/web120/web/.env'
```

> What version of Python you want to use for your application and thus what version your virtual environment is created using?

> Note that a single Apache/mod_wsgi can only work with a single Python version. You cannot use different applications with different Python versions (virtual environment) at the same time. If you really needed this, you should use mod_wsgi-express and run distinct Apache instances using it behind a front end Apache.

> Answer those questions first and can then maybe suggest next thing to look at.

... Wow, well, in the time of writing, I've just unloaded and uninstalled local mod-wsgi, and used the system wide with my django wsgi script... and now it works...
But I was sure I already tested it.
my app is an old django 2.2, it supports python 3.7 so I was going to make the change anyway.

I'm sorry, I missed some step restarting apache with the vhost changes for sure.
thanks a lot!
-closing-
