### ISSUE TITLE
httpd: Syntax error on line 275 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.d/orchestration-controller.conf: Cannot load modules/mod_wsgi.so into server: /etc/httpd/modules/mod_wsgi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by satishkandekar** [GrahamDumpleton/mod_wsgi#795]
Hi GrahamDumpleton,
i have install httpd 2.5.6 
after that install wsgi 
pip3 install mod_wsgi

and restart my httpd service
but tis show the error 
httpd: Syntax error on line 275 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.d/orchestration-controller.conf: Cannot load modules/mod_wsgi.so into server: /etc/httpd/modules/mod_wsgi.so: cannot open shared object file: No such file or directory

**Comment by GrahamDumpleton** [comment]
What do you get when you run:

```
ls -las /etc/httpd/modules/mod_wsgi.so
```

and:

```
ldd /etc/httpd/modules/mod_wsgi.so
```

What flavour of Linux are you on? Debian/Ubuntu, or some form of Red Hat Linux (RHEL, Centos, Fedora).

**Comment by GrahamDumpleton** [comment]
BTW, at this point there has been no attempt to compile mod_wsgi with Apache 2.5 (dev stream) so it isn't known if it will even work for the future Apache version.
