### ISSUE TITLE
Content-Length ?  Header not!

### ISSUE THREAD

**Issue by koliboy** [GrahamDumpleton/mod_wsgi#801]

**Comment by koliboy** [comment]
yes ! 
after get mysite  
reponse --> Transfer-Encoding: chunked

i change  header filed Content-Length   wsgi script  but Not  reponse  Content-length  Why 
http server apache httpd install mod_wsgi 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding
help

**Comment by koliboy** [comment]
HTTP/1.1 200 ok
Date: Wed, 19 Oct 2022 17:24:47 GMT
Server: Apache/2.4.41 (Ubuntu)
Vary: Accept-Encoding
Content-Encoding: gzip
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html;charset=utf-8

**Comment by koliboy** [comment]
missing Content-Length

**Comment by koliboy** [comment]
('Content-Length',length)

**Comment by koliboy** [comment]
i want sponser how to

**Comment by koliboy** [comment]
But how does the content length appear?

**Comment by koliboy** [comment]
But how does the content length appear?

**Comment by GrahamDumpleton** [comment]
It doesn't. The client would keep reading blocks until it sees the 0 length block, at which point it would sum up the length of all the blocks if it really needed to know the final length, or more likely to work out if it got complete response before connection was dropped. Ie., connection dropped before saw 0 length block.

If that doesn't explain it am not sure what you are asking.
