### ISSUE TITLE
Script get downloaded instead of gets executed

### ISSUE THREAD

**Issue by SashaMyh** [GrahamDumpleton/mod_wsgi#804]
Im trying to run my python scripts with wsgi module on apache2
im running on ubuntu 22.04 lts.
everytime i try to execute my wsgi.py file from url, it downloads it instead of executing it.

i installed wsgi like this : 

```
sudo apt install libapache2-mod-wsgi-py3
```
and i configed my virtualhost like this : 

```
<VirtualHost *:80>

	WSGIScriptAlias /wsgi /var/www/python_and_php_mix/wsgi.py
	<Directory /var/www/python_and_php_mix>
		Require all granted
	</Directory>

	ServerName python-and-php-mix.localhost.com
	ServerAlias www.python-and-php-mix.localhost.com
	
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/python_and_php_mix

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>

```
and this is my wsgi.py file : 

```
def application(environ,start_response):
    status = '200 OK'
    html = 'html>\n' \
           '<body>\n' \
           '<div style="width: 100%; font-size: 40px; font-weight: bold; text-align: center;">\n' \
           'Welcome to mod_wsgi Test Page\n' \
           '</div>\n' \
           '</body>\n' \
           '</html>\n'
    response_header = [('Content-type','text/html')]
    start_response(status,response_header)
    return [html]
```
and i also tried having wsgi.conf in /etc/apache2/conf-available :

```
WSGIScriptAlias /wsgi /var/www/python_and_php_mix/wsgi.py
```
im not pro in this i just want to run my python scripts with apache thats it.

**Comment by GrahamDumpleton** [comment]
What URL are using to access the WSGI application?

At a guess I would say you might have a different `VirtualHost` for port 80 which is getting used in preference to this first one as the URL doesn't actually match.

That said, do you have other `VirtualHost` definitions for port 80 and what do they set for `ServerName`?
