### ISSUE TITLE
ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by netops97** [GrahamDumpleton/mod_wsgi#812]
Good evening,

I've been struggling with this issue for some time now. Specifically, when I run my Django application it fails with Apache 2.4.37/mod_wsgi 4.6.4 reporting: ModuleNotFoundError: No module named 'django'.

I've attached a file containing the httpd/mod_wsgi errors, the VirtualHost definition (<VirtualHost *:80>) from httpd.conf, and the virtual environment listing I used to develop the application. Note that the virtual environment contains mod-wsgi 4.9.3 in addition to Apache 2.4.37/mod_wsgi 4.6.4 which is what the image came with. I'm not clear on which I should be using, and why can't mod_wsgi 4.6.4 see my virtual environment? 

Thanks,

b.p.
[mod-wsgi-prob-desc2.txt](https://github.com/GrahamDumpleton/mod_wsgi/files/10322782/mod-wsgi-prob-desc2.txt)

**Comment by GrahamDumpleton** [comment]
For a start you have:

```
    WSGIDaemonProcess netops_site python-home=/var/www/env_netops python-path=/var/www/netops_site
```

The `python-home` option should point to the root of your Python virtual environment, not where you project is.

See:

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

Also run checks in:

* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use

to make sure that mod_wsgi module for Apache being used is actually for the same Python version your Python virtual environment is.

If you want to use the system mod_wsgi package for Apache you don't need to install mod_wsgi package into the Python virtual environment.

If the system mod_wsgi package for Apache is for the wrong Python version you should uninstall it and configure Apache to use the mod_wsgi package installed into the Python virtual environment instead. See:

* https://pypi.org/project/mod-wsgi/

**Comment by netops97** [comment]
The mod_wsgi module for Apache was **NOT** the same Python version as the version of Python being used in my virtual environment (i.e., 3.9). As soon as I re-built the environment using Python 3.6, the default, Django became "visible" using a properly configured httpd.conf. The jump to a virtual environment to acquire netmiko in python 3.9 broke the config. I also removed mod_wsgi from the virtual environment since the system mod_wsgi package was all I needed.

Thank you for the support!!!
