### ISSUE TITLE
[wsgi:error]  ModuleNotFoundError: No module named 'ckan'

### ISSUE THREAD

**Issue by evarkey** [GrahamDumpleton/mod_wsgi#816]
CKAN Ver.2.9.7

Here is the complete error log from Apache:

```
[Tue Jan 10 10:38:10.388315 2023] [wsgi:error] [pid 2419928:tid 139737723262720] ERROR:root:utf-8
[Tue Jan 10 10:38:10.388388 2023] [wsgi:error] [pid 2419928:tid 139737723262720] ERROR:root:Hello World from apache.wsgi --------------
[Tue Jan 10 10:38:10.388959 2023] [wsgi:error] [pid 2419928:tid 139737723262720] [remote 10.23.14.195:62252] mod_wsgi (pid=2419928): Failed to exec Python script file '/etc/ckan/default/apache.wsgi'.
[Tue Jan 10 10:38:10.388994 2023] [wsgi:error] [pid 2419928:tid 139737723262720] [remote 10.23.14.195:62252] mod_wsgi (pid=2419928): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Jan 10 10:38:10.389143 2023] [wsgi:error] [pid 2419928:tid 139737723262720] [remote 10.23.14.195:62252] Traceback (most recent call last):
[Tue Jan 10 10:38:10.389167 2023] [wsgi:error] [pid 2419928:tid 139737723262720] [remote 10.23.14.195:62252]   File "/etc/ckan/default/apache.wsgi", line 13, in <module>
[Tue Jan 10 10:38:10.389172 2023] [wsgi:error] [pid 2419928:tid 139737723262720] [remote 10.23.14.195:62252]     from ckan.config.middleware import make_app
[Tue Jan 10 10:38:10.389186 2023] [wsgi:error] [pid 2419928:tid 139737723262720] [remote 10.23.14.195:62252] ModuleNotFoundError: No module named 'ckan'
```

**Comment by GrahamDumpleton** [comment]
Not possible to give advice without seeing how you configured mod_wsgi. First impressions though are that you have not told mod_wsgi the location of your project code, or the correct virtual environment. The virtual environment not being used can also be because mod_wsgi was compiled for a different version of Python than used by the virtual environment.

**Comment by evarkey** [comment]
Here the wsgi part in the Apache Virtual host:
WSGIScriptAlias / /etc/ckan/default/apache.wsgi
        WSGIPassAuthorization On

        WSGIDaemonProcess ckan_default display-name=ckan_default  processes=8 threads=10 locale='en_US.UTF-8'
        WSGIProcessGroup ckan_default

And here is the wsgi file.
# cat /etc/ckan/default/apache.wsgi
# -*- coding: utf-8 -*-


import sys
import logging
logging.error(sys.getfilesystemencoding())
logging.error('Hello World from apache.wsgi --------------')

import os
activator = os.path.join('/usr/lib/ckan/default/bin/activate_this.py')
with open(activator) as f:
    exec(f.read(), {'__file__': activator})
from ckan.config.middleware import make_app
from ckan.cli import CKANConfigLoader
from logging.config import fileConfig as loggingFileConfig
if os.environ.get(u'CKAN_INI'):
    config_path = os.environ[u'CKAN_INI']
else:
    config_path = os.path.join(
os.path.dirname(os.path.abspath(__file__)), u'ckan.ini')
if not os.path.exists(config_path):
    raise RuntimeError(u'CKAN config option not found: {}'.format(config_path))
loggingFileConfig(config_path)
config = CKANConfigLoader(config_path).get_config()
application = make_app(config)


# cat /usr/lib/ckan/default/bin/activate_this.py
"""By using execfile(this_file, dict(__file__=this_file)) you will
activate this virtualenv environment.

This can be used when you must use an existing Python interpreter, not
the virtualenv bin/python
"""

try:
    __file__
except NameError:
    raise AssertionError(
        "You must run this like execfile('path/to/activate_this.py', dict(__file__='path/to/activate_this.py'))")
import sys
import os

old_os_path = os.environ.get('PATH', '')
os.environ['PATH'] = os.path.dirname(os.path.abspath(__file__)) + os.pathsep + old_os_path
base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if sys.platform == 'win32':
    site_packages = os.path.join(base, 'Lib', 'site-packages')
else:
    site_packages = os.path.join(base, 'lib', 'python%s' % sys.version[:3], 'site-packages')
prev_sys_path = list(sys.path)
import site
site.addsitedir(site_packages)
sys.real_prefix = sys.prefix
sys.prefix = base
# Move the added items to the front of the path:
new_sys_path = []
for item in list(sys.path):
    if item not in prev_sys_path:
        new_sys_path.append(item)
        sys.path.remove(item)
sys.path[:0] = new_sys_path

**Comment by GrahamDumpleton** [comment]
How was CKAN installed, by yourself from source, or from a system package? What instructions (provide URL link) are you following for setting up CKAN with mod_wsgi?

There are so many things wrong, or done in a non standard way for how mod_wsgi is being used here I really need to see the original instructions you are following.

**Comment by evarkey** [comment]
CKAN installed from source on RHEL v8.7 and following the CKAN document pulled from github. There is no clear instruction how to setup apache httpd server for CKAN app. Can you please send me a good instruction which I can follow. Appreciate your help!

**Comment by GrahamDumpleton** [comment]
Can you provide a URL link to "the CKAN document pulled from github".

**Comment by evarkey** [comment]
https://docs.ckan.org/_/downloads/en/latest/pdf/

CKAN documentation
Release 2.11.0a0

**Comment by evarkey** [comment]
Dec 22, 2022

**Comment by GrahamDumpleton** [comment]
Since the CKAN project seems to have no interest in supporting Apache/mod_wsgi and doesn't provide sufficient details in their documentation to deploy it with any WSGI server, you may well be better off using uWSGI as they recommend.

That said, all I can suggest right now is that you not use their activate script in the WSGI file as you are trying, instead using their original WSGI script file as shown in docs:

```
import os
from ckan.config.middleware import make_app
from ckan.cli import CKANConfigLoader
from logging.config import fileConfig as loggingFileConfig
config_filepath = os.path.join(
os.path.dirname(os.path.abspath(__file__)), 'ckan.ini')
abspath = os.path.join(os.path.dirname(os.path.abspath(__file__)))
loggingFileConfig(config_filepath)
config = CKANConfigLoader(config_filepath).get_config()
application = make_app(config)
```

and use a mod_wsgi configuration of:

```
        WSGIDaemonProcess ckan_default display-name=ckan_default  \
           python-home=/usr/lib/ckan/default \
           processes=8 threads=10 locale='en_US.UTF-8'

        WSGIScriptAlias / /etc/ckan/default/apache.wsgi \
          process-group=ckan_default \
          application-group=%{GLOBAL}

        WSGIPassAuthorization On
```

For an understanding of virtual environment usage see:

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

**Comment by evarkey** [comment]
Thank you, Graham! I have updated the configuration as you suggested and resolved the issue.
