### ISSUE TITLE
flask app is not responding, ERROR logs in mod_wsgi

### ISSUE THREAD

**Issue by mehrdadasadiut** [GrahamDumpleton/mod_wsgi#819]
Hello
my flask app is not responding on localhost:8000
I just noticed there are some errors in error log file of mod_wsgi

mod_wsgi (pid=6624): Failure to configure the daemon process correctly and
  process left in unspecified state. Restarting daemon process after delay.

please check the image.

![error](https://user-images.githubusercontent.com/111504275/215480178-d6724622-1e08-4810-8866-c7c04c6e555b.PNG)

**Comment by GrahamDumpleton** [comment]
For a start, you should not put your project files under `/root` as mod_wsgi code runs as an unprivileged user and can't access that directory as that directory is only accessible as the `root` user.

**Comment by mehrdadasadiut** [comment]
Yeah you are right. Changing the location of project to other directory fixed the issue. 
I close the issue.
