### ISSUE TITLE
 access a website running mod_wsgi-express on port 8000 by hostname

### ISSUE THREAD

**Issue by mehrdadasadiut** [GrahamDumpleton/mod_wsgi#820]
Is there any solution to access a website running mod_wsgi-express on port 8000 by hostname? 
I struggled to access the website using the hostname rather than its IP address.
I will be appreciated it if there's any help in this regard.

**Comment by GrahamDumpleton** [comment]
When run it listens on all network interfaces. So as long as you have the hostname mapped in DNS, or local /etc/hosts file if only accessing from the same machine, to the IP address, then you should have no issue accessing it as http://hostname:8000.

Is the full hostname mapped in DNS or /etc/hosts?

**Comment by mehrdadasadiut** [comment]
Actually, I can curl mycloudinstance:8000 successfully, but it gives me no response on the web browser.
As you mentioned accessing the website locally using the hostname HTTP://hostname:8000 works fine.
Is there somewhere on mod_wsgi configure file that I have to map my DNS/cloudinstance name?

**Comment by GrahamDumpleton** [comment]
To confirm, you are saying `http://mycloudinstance:8000` works with curl but not in a web browser using the exact same URL?

Run `curl` with the `-v` flag should you can see all headers, details of IP address connected to etc. Then also use the developer console of your web browser and hit the URL with the network tab of the developer console visible so again can see details and compare.

Do not some browsers can handle DNS lookups a bit differently to anything else run on the system.

There should be no need to map the hostname in mod_wsgi-express at all. The only time you need to tell it the hostname is if using a SSL certificate.

What is the command line arguments to `mod_wsgi-express` you are using? Don't use `--server-name` argument if not using a SSL certificate.

**Comment by mehrdadasadiut** [comment]
Just start-server command with user-level variables of Apachjee.
Please check the images.
Curl -v gives all details, but in the developer tool, I get no response. But the strange thing is that although I write HTTP but it is resolved automatically to HTTPS, which is not responding.
<img width="397" alt="curl-v" src="https://user-images.githubusercontent.com/111504275/215889419-ba1768c0-c710-4e3f-8bb8-cfeaae300e18.PNG">
<img width="725" alt="curlOutput" src="https://user-images.githubusercontent.com/111504275/215889453-fd38d87c-4627-453c-bc74-eb19794e9ef9.PNG">
<img width="435" alt="devOut" src="https://user-images.githubusercontent.com/111504275/215889486-25f701d2-41cc-464c-9e1e-425d1286cae2.PNG">

**Comment by GrahamDumpleton** [comment]
In the browser make sure you are explicitly saying `http://...`. The browser may be setup to try https first if only hostname is given.

**Comment by mehrdadasadiut** [comment]
Yes, you are right. It works fine when using Firefox (no change to https automatically). But it does not work in Chrome because it triest to open https. Is there any solution to make my website to work on any browser?
<img width="250" alt="devout1" src="https://user-images.githubusercontent.com/111504275/215896352-6f9e676b-9f21-4d66-8ff7-2a1c8ecc2966.PNG">

**Comment by GrahamDumpleton** [comment]
The problem you can have with chrome is that if any web site on that hostname has previously used SSL and set HSTS (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) then the browser will remember that and always send you to the https URL regardless. Does that hostname host a real HTTPS site on standard ports which has HSTS enabled?

For some details on clearing HSTS caching see: https://www.ssl2buy.com/wiki/how-to-clear-hsts-settings-on-chrome-firefox-and-ie-browsers

**Comment by mehrdadasadiut** [comment]
No the server was clean and the only website is the one I am running.
Is there any solution to not force HSTS for clients/browsers on the server side ? apache2 or mod_wsgi

**Comment by GrahamDumpleton** [comment]
HSTS is something that would only be triggered for a particular hostname if the site had been previously visited and the site itself had returned the HSTS headers. If that has never occurred then it will not be this problem.

The issue may be a more general setting which has been set in your browser to force all requests to use https. Can you visit any other sites using plain http. Eg., http://blog.dscpl.com.au/

**Comment by mehrdadasadiut** [comment]
Yeah, the website is visited without any problem.

**Comment by GrahamDumpleton** [comment]
Try suggestions in https://howchoo.com/chrome/stop-chrome-from-automatically-redirecting-https as to what to do if still getting redirected. You may just need to clear browser cache for that hostname.

**Comment by mehrdadasadiut** [comment]
Thanks Graham.
Its fine, the problem was the caching of HTTPS for the domain as you mentioned.

**Comment by GrahamDumpleton** [comment]
So all is working now? If so can you close the issue. Thanks.

**Comment by mehrdadasadiut** [comment]
Yep, alright.
