### ISSUE TITLE
python setup.py bdist_wheel did not run successfully. exit code: 1

### ISSUE THREAD

**Issue by fendypurnomo** [GrahamDumpleton/mod_wsgi#829]
C:\Windows\Temp\pip-install-urrup4a3\mod-wsgi_8552929be5ae410c8cdf563e0fb7facc\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws2tcpip.h': No such file or directory

**Comment by GrahamDumpleton** [comment]
The error:

```
C:\Windows\Temp\pip-install-urrup4a3\mod-wsgi_8552929be5ae410c8cdf563e0fb7facc\src\server\wsgi_apache.h(39): fatal error C1083: Cannot open include file: 'ws2tcpip.h': No such file or directory
```

suggests this is a problem with your compiler installation.

Try looking at older instances of this problem to try and resolve it.

* https://github.com/GrahamDumpleton/mod_wsgi/issues/194

Just keep in mind that the prior issues are old and likely for older Windows and compiler versions. So the extra Windows developer packages you may need to install may now be different.
