### ISSUE TITLE
ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by yuan0202** [GrahamDumpleton/mod_wsgi#841]
Hello Graham,
I am using ubuntu18.04 system and I am doing a project with Django.
but the project raised

> error.log error:
```
AH00489: Apache/2.4.29 (Ubuntu) mod_wsgi/4.5.17 Python/3.6 configured -- resuming normal operations 
event.c(2218): AH02471: start_threads: Using epoll (wakeable)
 event.c(2218): AH02471: start_threads: Using epoll (wakeable)
mod_authz_core.c(809): [client 127.0.0.1:55094] AH01626: authorization result of Require all granted: granted
mod_authz_core.c(809): [client 127.0.0.1:55094] AH01626: authorization result of <RequireAny>: granted
mod_authz_core.c(809): [client 127.0.0.1:55094] AH01626: authorization result of Require all granted: granted
mod_authz_core.c(809): [client 127.0.0.1:55094] AH01626: authorization result of <RequireAny>: granted
mod_wsgi (pid=8223, process='locallibrary', application=''): Loading WSGI script '/home/mhwu191/django_test/locallibrary/locallibrary/locallibrary/wsgi.py'.
mod_wsgi (pid=8223): Target WSGI script '/home/mhwu191/django_test/locallibrary/locallibrary/locallibrary/wsgi.py' cannot be loaded as Python module.
mod_wsgi (pid=8223): Exception occurred processing WSGI script '/home/mhwu191/django_test/locallibrary/locallibrary/locallibrary/wsgi.py'.
 Traceback (most recent call last):
File "/home/mhwu191/django_test/locallibrary/locallibrary/locallibrary/wsgi.py", line 19, in <module>
from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
```

I using `sudo apt-get libapache2-mod-wsgi-py3`

django.conf

```
        #/etc/apach2/sites-available/django.conf
        <VirtualHost *:80>
        DocumentRoot /home/mhwu191/django_test/locallibrary/locallibrary

        Alias /static /home/mhwu191/django_test/locallibrary/locallibrary/catalog/static
        <Directory /home/mhwu191/django_test/locallibrary/locallibrary/catalog/static>
                Require all granted
        </Directory>

        WSGIScriptAlias / /home/mhwu191/django_test/locallibrary/locallibrary/locallibrary/wsgi.py
        <Directory /home/mhwu191/django_test/locallibrary/locallibrary/locallibrary>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        <Directory /home/mhwu191/django_test/locallibrary/locallibrary>
                Require all granted
        </Directory>

        WSGIDaemonProcess locallibrary
        WSGIProcessGroup locallibrary
        WSGIApplicationGroup %{GLOBAL}

        </VirtualHost>
```

/home/mhwu191/django_test/locallibrary/locallibrary/locallibrary/wsgi.py

```
        import os
        import sys
        import site
        site.addsitedir('/home/mhwu191/.local/lib/python3.6/site-packages')

        sys.path.append('/home/mhwu191/django_test/locallibrary/locallibrary')
        sys.path.append('/home/mhwu191/.local/lib/python3.6/site-packages')

        from django.core.wsgi import get_wsgi_application
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'locallibrary.settings')
        application = get_wsgi_application()
```

pip3 show django

```
        Name: Django
        Version: 3.2.19
        Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
        Location: /home/mhwu191/.local/lib/python3.6/site-packages
        Requires: sqlparse, asgiref, pytz
```

**Comment by GrahamDumpleton** [comment]
Don't use:

```
    site.addsitedir('/home/mhwu191/.local/lib/python3.6/site-packages')

    sys.path.append('/home/mhwu191/django_test/locallibrary/locallibrary')
    sys.path.append('/home/mhwu191/.local/lib/python3.6/site-packages')
```

Create a proper Python virtual environment and then configure things based on what Django says to do for a virtual environment.

* https://docs.djangoproject.com/en/4.2/howto/deployment/wsgi/modwsgi/#using-mod-wsgi-daemon-mode

Be aware that the user Apache runs your code as often does not have access to your home directory. So putting stuff under your home directory is often not a good idea on systems that don't have your home directory accessible to others. So even if the code using `site.addsitedir()` is correct, it still may not be able to read stuff.

Read:

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#access-rights-of-apache-user
* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

**Comment by yuan0202** [comment]
After reading the documentation article you attached above

- python3 -m venv djangoenv (/home/mhwu191/django_test/locallibrary/djangoenv)
- copy all python3.6/site-packages to djangoenv/lib/python3.6/site-packages
- copy all django folder to djangoenv

**django_test/locallibrary/djangoenv/locallibrary/wsgi.py**

       import os
       from django.core.wsgi import get_wsgi_application
       os.environ['HOME'] = '/home/mhwu191/django_test/locallibrary'
       os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'locallibrary.settings')
       application = get_wsgi_application()

 **/etc/apach2/sites-available/django.conf**

       <VirtualHost *:80>
        Alias /static /home/mhwu191/django_test/locallibrary/locallibrary/catalog/static
        Documentroot /home/mhwu191/django_test/locallibrary/locallibrary
        <Directory /home/mhwu191/django_test/locallibrary/locallibrary/catalog/static>
                Require all granted
        </Directory>

        WSGIScriptAlias / /home/mhwu191/django_test/locallibrary/locallibrary/locallibrary/wsgi.py
        <Directory /home/mhwu191/django_test/locallibrary/locallibrary/locallibrary>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        <Directory /home/mhwu191/django_test/locallibrary/locallibrary>
                Require all granted
        </Directory>

        WSGIDaemonProcess locallibrary python-home=/home/mhwu191/django_test/locallibrary/djangoenv python-path=/home/mhwu191/django_test/locallibrary/locallibrary
        WSGIProcessGroup locallibrary
        WSGIApplicationGroup %{GLOBAL}

</VirtualHost>

but still get error
**ModuleNotFoundError: No module named 'django'**

**Comment by GrahamDumpleton** [comment]
You shouldn't just copy all python3.6/site-packages to djangoenv/lib/python3.6/site-packages. You should reinstall the Python packages using pip into the virtual environment. Copying installed packages from one Python installation to another may not work.

What do you get for:

```
ls -las /home/mhwu191/django_test/locallibrary/djangoenv
ls -las /home/mhwu191/django_test/locallibrary/djangoenv/lib/python3.6/site-packages
```

I want to verify the ownership permissions you have and what is in site-packages.

Also verify what version of Python that your mod_wsgi is compiled for. It would need to be compiled for Python 3.6 else this will not work. See:

* https://modwsgi.readthedocs.io/en/master/user-guides/checking-your-installation.html#python-installation-in-use

**Comment by yuan0202** [comment]
**ls -las /home/mhwu191/django_test/locallibrary/djangoenv**

     total 32
      4 drwxrwxr-x 7 mhwu191 mhwu191  .
     4 drwxrwxrwx 4 mhwu191 mhwu191 4096   ..
     4 drwxrwxr-x 3 mhwu191 mhwu191 4096   bin
     4 drwxrwxr-x 2 mhwu191 mhwu191 4096   include
     4 drwxrwxr-x 3 mhwu191 mhwu191 4096   lib
     0 lrwxrwxrwx 1 mhwu191 mhwu191    3   lib64 -> lib
     4 drwxrwxr-x 4 mhwu191 mhwu191 4096   locallibrary
     4 -rw-rw-r-- 1 mhwu191 mhwu191   69   pyvenv.cfg
     4 drwxrwxr-x 3 mhwu191 mhwu191 4096  share

**ls -las /home/mhwu191/django_test/locallibrary/djangoenv/lib/python3.6/site-packages**

     total 224
     4 drwx------ 26 mhwu191 mhwu191   4096   .
      4 drwxrwxr-x  3 mhwu191 mhwu191   4096   ..
      4 drwxr-xr-x  3 mhwu191 mhwu191   4096   asgiref
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   asgiref-3.4.1.dist-info
      4 drwxr-xr-x 19 mhwu191 mhwu191   4096   django
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   Django-3.2.19.dist-info
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   django_filter-21.1.dist-info
      4 drwxr-xr-x  6 mhwu191 mhwu191   4096   django_filters
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   django_phonenumber_field-6.0.0.dist-info
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   djangorestframework-3.14.0.dist-info
      4 drwxr-x---  4 mhwu191 mhwu191   4096   django_sslserver2
      4 drwxr-xr-x  3 mhwu191 mhwu191   4096   importlib_metadata
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   importlib_metadata-4.8.3.dist-info
      4 drwxr-xr-x  4 mhwu191 mhwu191   4096   markdown
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   Markdown-3.3.7.dist-info
      4 drwxr-xr-x  4 mhwu191 mhwu191   4096   phonenumber_field
      4 drwxr-xr-x  5 mhwu191 mhwu191   4096   phonenumbers
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   phonenumberslite-8.13.11.dist-info
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   __pycache__
      4 drwxr-xr-x  4 mhwu191 mhwu191   4096   pytz
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   pytz-2023.3.dist-info
      4 drwxr-xr-x 11 mhwu191 mhwu191   4096   rest_framework
      4 drwxr-xr-x  5 mhwu191 mhwu191   4096   sqlparse
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   sqlparse-0.4.4.dist-info
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   typing_extensions-4.1.1.dist-info
     108 -rwxr--r--  1 mhwu191 mhwu191 107685  typing_extensions.py
      4 drwxr-xr-x  2 mhwu191 mhwu191   4096   zipp-3.6.0.dist-info
     12 -rwxr--r--  1 mhwu191 mhwu191   8425   zipp.py
     
**Python Installation In Use**

     sys.version = '3.6.9 (default, Mar 10 2023, 16:46:00) \n[GCC 8.4.0]'
     sys.prefix = '/usr'

**Comment by GrahamDumpleton** [comment]
Run:

```
chmod g+rx,o+rx /home/mhwu191/django_test/locallibrary/djangoenv/lib/python3.6/site-packages
```

and then try again.

The permissions on the directory are such that the Apache user wouldn't be able to access anything in that directory.

Check for any parent directories as well which don't allow `r-x` to group and others.

**Comment by yuan0202** [comment]
The Apache2 service can show Django.conf ,but Apache2 server can't load .css and .js (/var/www/static/)
he say my styles2.css MIME type is text/html not text/css
and get error Uncaught ReferenceError: $ is not defined
Thanks for your help @GrahamDumpleton
