### ISSUE TITLE
relocation R_X86_64_PC32 against symbol `PyDict_Type' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by the-yaz** [GrahamDumpleton/mod_wsgi#846]
After running ./configure , I tried to run " sudo make " and got these errors (the same line repeated for different symbols), i tried to install it by "pip install " and almost the same thing happened , I saw some posts of this issue in git and in SO but it didn't help .

**Comment by GrahamDumpleton** [comment]
Your Python installation hasn't been installed with a shared library. That is what the message is telling you.

See:

* https://modwsgi.readthedocs.io/en/master/user-guides/installation-issues.html#mixing-32-bit-and-64-bit-packages

If using `pyenv`, see:

* https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared

If you have built Python from source code yourself, have a read of:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Ignore that the latter talks about Docker, what is described is still relevant and has a section about the shared library problem.

**Comment by the-yaz** [comment]
I didn't have a mixing of 32 bit and 64 bit , but I guess I had to run ./configure with the option of -with--enable-shared .
