### ISSUE TITLE
mod_wsgi builds with pip-install on windows, but no .so or .dll is emitted

### ISSUE THREAD

**Issue by solstice333** [GrahamDumpleton/mod_wsgi#848]
I have a 2.4.34 apache httpd installation that was part of a Bitnami Trac stack for Windows. It works with the existing .so modules, including a mod_wsgi.so. I am trying to bump it to the next VC11 built release, 2.4.38 (https://www.apachelounge.com/download/additional/), with the intent of maintaining ABI compatibility with my existing modules. When I try to run bin\httpd within my apache directory, it successfully loads all of the existing modules except mod_wsgi.so. The error message says something like "failure to load module, cannot be found". However the mod_wsgi.so filepath exists exactly as the argument to `LoadModule` specifies. I have confirmed this by rolling back to 2.4.34, without changing the apache directory structure, which works as expected. I then tried to build a new mod_wsgi.so by following the instructions here: https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/README.rst, which is also similar to https://stackoverflow.com/a/59801388/2630028

Windows version (`get-computerinfo`):
```
WindowsBuildLabEx                                       : 14393.5850.amd64fre.rs1_release.230329-2152
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerStandard
WindowsInstallationType                                 : Server
WindowsProductName                                      : Windows Server 2016 Standard
```
Apache version (`bin\httpd -V`):
```
Server version: Apache/2.4.38 (Win32)
Apache Lounge VC11 Server built:   Jan 21 2019 12:11:57
Server's Module Magic Number: 20120211:83
Server loaded:  APR 1.6.5, APR-UTIL 1.6.1
Compiled using: APR 1.6.5, APR-UTIL 1.6.1
Architecture:   32-bit
Server MPM:     WinNT
  threaded:     yes (fixed thread count)
    forked:     no
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses disabled)
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/apache"
 -D SUEXEC_BIN="/apache/bin/suexec"
 -D DEFAULT_PIDLOG="logs/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error.log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
```
Python version (`python -c "import sys; print(sys.version)"`):
```
2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
``` 
My `MOD_WSGI_APACHE_ROOTDIR` is this (forward slashes, even on Windows, as suggested by the doc):
```
C:/Bitnami/trac-1.2.3-0/apache2
```
I did
```
python -m pip install mod_wsgi
```
the output is this, which I guess suggests that I had a good-enough MSVC toolchain, if it was needed at all:
```
Processing c:\users\knavero\appdata\local\pip\cache\wheels\6a\30\3e\e97edbe98c36d0aada62b48e8c631f291acd15e953a8dbcfff\mod_wsgi-4.9.4-cp27-cp27m-win32.whl
Installing collected packages: mod-wsgi
Successfully installed mod-wsgi-4.9.4
```
`mod_wsgi-express module-config` gives me this:
```
LoadFile "c:/bitnami/trac-1.2.3-0/python/python27.dll"
LoadModule wsgi_module "c:/bitnami/trac-1.2.3-0/python/lib/site-packages/mod_wsgi/server/mod_wsgiNone"
WSGIPythonHome "c:/bitnami/trac-1.2.3-0/python"
```
Noting the unexpected `mod_wsgiNone`, I expected something like `mod_wsgi.so` or `mod_wsgi.dll` just like what is currently in my apache install. The contents in the aforementioned dirpath is this:
```
 Volume in drive C is OS
 Volume Serial Number is C2B6-2CBB

 Directory of C:\Bitnami\trac-1.2.3-0\python\Lib\site-packages\mod_wsgi\server

07/17/2023  03:36 PM    <DIR>          .
07/17/2023  03:36 PM    <DIR>          ..
07/17/2023  03:36 PM             1,137 apxs_config.py
07/17/2023  03:36 PM             1,056 apxs_config.pyc
07/17/2023  03:36 PM             3,563 environ.py
07/17/2023  03:36 PM             3,710 environ.pyc
07/17/2023  03:36 PM    <DIR>          management
07/17/2023  03:36 PM           116,736 mod_wsgi.pyd
07/17/2023  03:36 PM           138,057 __init__.py
07/17/2023  03:36 PM           113,725 __init__.pyc
               7 File(s)        377,984 bytes
               3 Dir(s)  32,258,244,608 bytes free
```
Trying the config output suggested by `mod_wsgi-express module-config` results in, of course, failure to load the module. Of course, pointing the config to the mod_wsgi.pyd fails to load too since it is python bytecode. Any thoughts on this? Preferably, I'd like to bump my apache httpd to the newest ABI compatible version with minimal amount of effort.

**Comment by solstice333** [comment]
I also took a look at https://modwsgi.readthedocs.io/en/master/user-guides/installation-issues.html, but was unsuccessful at finding anything that could help. Perhaps my own oversight due to exhaustion. Please LMK or redirect me if I have missed something obvious. Thanks.

**Comment by GrahamDumpleton** [comment]
The `None` in `LoadModule` is a problem that arises with some Python 2.7 installations on Windows, change it to:

```
LoadModule wsgi_module "c:/bitnami/trac-1.2.3-0/python/lib/site-packages/mod_wsgi/server/mod_wsgi.pyd"
```

**Comment by solstice333** [comment]
I changed (line 589 in my httpd.conf)
```
LoadModule wsgi_module "c:/bitnami/trac-1.2.3-0/python/lib/site-packages/mod_wsgi/server/mod_wsgiNone"
```
to
```
LoadModule wsgi_module "c:/bitnami/trac-1.2.3-0/python/lib/site-packages/mod_wsgi/server/mod_wsgi.pyd"
```
and it resulted in
![image](https://github.com/GrahamDumpleton/mod_wsgi/assets/3608596/02694155-ec2e-4499-8403-c2cf90ed2a4e)
and in the command prompt,
```
httpd.exe: Syntax error on line 589 of C:/Bitnami/trac-1.2.3-0/apache2/conf/httpd.conf: Cannot load c:/bitnami/trac-1.2.3-0/python/lib/site-packages/mod_wsgi/server/mod_wsgi.pyd into server: A dynamic link library (DLL) initialization routine failed.
```
Looks like it expects either a .so or a .dll, not a .pyd. 

I'm wondering if the Bitnami team ended up building a mod_wsgi.so using something like MSYS2, to do CMMI, but compiled to native Windows, and then packaging it as part of their distributable stack.

**Comment by solstice333** [comment]
Also, perhaps irrelevant to note, looks like the mod_wsgi.so, that came packaged with my older apache 2.4.34, as part of the Bitnami stack, is version 3.5 as listed in the service description.

**Comment by GrahamDumpleton** [comment]
Try commenting out the `LoadFile` configuration line and let the mod_wsgi DLL find itself the Python DLL. You may have built mod_wsgi against a different Python installation to where that Python DLL is found.

Are you really stuck with using Python 2.7 due to Trac? Python 2.7 is very old.

**Comment by solstice333** [comment]
Yeah, if I update to Python3, I will likely end up updating the rest of the Trac stack which will have several tedious and complicated implications that I would prefer to avoid.

**Comment by solstice333** [comment]
Oh, thanks for mentioning that bit about the python dll. I was able to get Apache 2.4.38 working with the older mod_wsgi.so 3.5 that came with this Bitnami Trac stack. All I did was prefix `C:\Bitnami\trac-1.2.3-0\python\Scripts;C:\Bitnami\trac-1.2.3-0\python;` to my `PATH`. I did not have to do that with my earlier Apache 2.4.34 b.c, apparently, Bitnami copied the python27.dll from the python27 install (that comes with their distributable stack) into the top-level Apache bin folder, which the httpd.conf adds to `PATH`.

However, I am still unable to get `LoadModule` to load the mod_wsgi.pyd that is associated to my recent successful `python -m pip install mod-wsgi`. It still results in the aforementioned image of "MSVC runtime, app attempted to load C runtime library incorrectly". Now that I think about it, I remember reading somewhere that MinGW64 (part of MSYS2) can compile C code (as opposed to C++) that is link/ABI compatible on Windows. And If I ever decide to try to update my mod_wsgi module, I will likely head down that route and follow the CMMI section in your documentation. For now, I'm content by just updating apache httpd, so I will close this ticket.

**Comment by GrahamDumpleton** [comment]
You cannot use the CMMI method of installation on Windows as far as I know, it is UNIX specific. Only the `pip install` method is supported on Windows.

**Comment by solstice333** [comment]
Oh, my understanding was that MSYS2/Mingw64 claims to support cross platform Unix-style builds (Make, gcc) that compile to native Win32 machine code, without the need of POSIX emulation such as Cygwin. And then somehow Bitnami folks included a mod_wsgi.so in this Trac stack distributable, which made me think it was not built with the usual MSVC build toolchains that emit .dll. I will append to this thread if I get any more information in the future. Again, much thanks for your active support!

**Comment by GrahamDumpleton** [comment]
Maybe it will work then, I am not a Windows user so never tested using that toolchain.
