### ISSUE TITLE
mod_wsgi with two python versions

### ISSUE THREAD

**Issue by iambalazi** [GrahamDumpleton/mod_wsgi#851]
hi @GrahamDumpleton 
I was researching if there any possible to make mod_wsgi work with two python versions and reason for my research is stated below.
I have an `Ubuntu-18.04 LTS` EC2 serving a django application with `mysql  Ver 8.0.16, Apache/2.4.29 and mod_wsgi/4.6.5 complied with python3.6`. Now, I am targeting to deploy a new django application in the same Ubuntu EC2 serve and it requires `python3.11+` virtualenv for installing its requirements.txt, now i am facing issues while deploying the new application.

here are few other information, Using Pyenv for creating virtualenvs, mod_wsgi is installed from source and compiled using `./configure --with-python=/home/ubuntu/.pyenv/shims/python3.6`

after deploying the new django application the domain returns 500 error and logs are as follows

api.log

```
[03/Aug/2023:18:42:14 +0000] "GET / HTTP/1.1" 500 816
[03/Aug/2023:18:43:17 +0000] "GET / HTTP/1.1" 500 816
[03/Aug/2023:18:43:17 +0000] "GET / HTTP/1.1" 500 816
[03/Aug/2023:18:43:17 +0000] "GET / HTTP/1.1" 500 816
[03/Aug/2023:18:43:18 +0000] "GET / HTTP/1.1" 500 816
[03/Aug/2023:18:43:18 +0000] "GET / HTTP/1.1" 500 816

```
api_error.log

```
[Thu Aug 03 18:43:18.047679 2023] [wsgi:error] [pid 170353:tid 140404074731072]  mod_wsgi (pid=170353): Failed to exec Python script file '/var/www/project/newdjango/wsgi.py'.
[Thu Aug 03 18:43:18.047724 2023] [wsgi:error] [pid 170353:tid 140404074731072]  mod_wsgi (pid=170353): Exception occurred processing WSGI script '/var/www/project/newdjango/wsgi.py'.
[Thu Aug 03 18:43:18.047795 2023] [wsgi:error] [pid 170353:tid 140404074731072]  Traceback (most recent call last):
[Thu Aug 03 18:43:18.047810 2023] [wsgi:error] [pid 170353:tid 140404074731072]    File "/var/www/project/newdjango/wsgi.py", line 12, in <module>
[Thu Aug 03 18:43:18.047814 2023] [wsgi:error] [pid 170353:tid 140404074731072]      from django.core.wsgi import get_wsgi_application
[Thu Aug 03 18:43:18.047827 2023] [wsgi:error] [pid 170353:tid 140404074731072]  ModuleNotFoundError: No module named 'django'
[Thu Aug 03 18:43:18.180781 2023] [wsgi:error] [pid 170353:tid 140403957233216]  mod_wsgi (pid=170353): Failed to exec Python script file '/var/www/project/newdjango/wsgi.py'.
[Thu Aug 03 18:43:18.180819 2023] [wsgi:error] [pid 170353:tid 140403957233216]  mod_wsgi (pid=170353): Exception occurred processing WSGI script '/var/www/project/newdjango/wsgi.py'.
[Thu Aug 03 18:43:18.180886 2023] [wsgi:error] [pid 170353:tid 140403957233216]  Traceback (most recent call last):
[Thu Aug 03 18:43:18.180900 2023] [wsgi:error] [pid 170353:tid 140403957233216]    File "/var/www/project/newdjango/wsgi.py", line 12, in <module>
[Thu Aug 03 18:43:18.180904 2023] [wsgi:error] [pid 170353:tid 140403957233216]      from django.core.wsgi import get_wsgi_application
[Thu Aug 03 18:43:18.180916 2023] [wsgi:error] [pid 170353:tid 140403957233216]  ModuleNotFoundError: No module named 'django'
``` 

here is the apache configuration

```
<VirtualHost *:80>
    ServerName qa.api.domian.com
WSGIDaemonProcess qa.api.domian.com python-home=/home/ubuntu/.pyenv/versions/3.11.3/envs/timesheet_env python-path=/var/www/project
    WSGIProcessGroup qa.api.domian.com
    WSGIApplicationGroup %{GLOBAL}
DocumentRoot /var/www/project

    ErrorLog "${APACHE_LOG_DIR}/api_error.log"
    CustomLog "${APACHE_LOG_DIR}/api.log" common
    LogLevel Warn

    Alias /static /var/www/project/static
    <Directory /var/www/project/static>
        Require all granted
    </Directory>

WSGIScriptAlias / /var/www/project/newdjango/wsgi.py
<Directory "/var/www/project/newdjango">
<Files wsgi.py>
        Require all granted
</Files>
</Directory>
```
according to the mod_wsgi documentation and from my research, the issue is due to difference in python version of virtualenv and mod_wsgi, please correct me if i am wrong.

Now i am targeting to deploy both django application `old-django should use python3.6.8` and `new-django should use python3.11+
`

i tried compiling the mod_wsgi with python3.11

- downloaded latest mod_wsgi/4.9.4 from source
- ./configure --with-python=/shims/python3.11
- make, make install

after compiling the new django app works perfectly but existing django fails with same errors 

now can you please suggest me the steps for resolving this issue without disturbing the existing django as it is the production version of application

Thanks in advance

**Comment by GrahamDumpleton** [comment]
One Apache/mod_wsgi instance will only work for one Python version. You cannot use a Python virtual environment created for a different Python version with it.

The only way to handle things for multiple Python versions is to use two distinct Apache/mod_wsgi instances.

A simple way of doing that is to use `mod_wsgi-express` for one instance and set up the main Apache instance to proxy one site through to the `mod_wsgi-express` instance.

Read:

* http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
* http://blog.dscpl.com.au/2015/07/redirection-problems-when-proxying-to.html

about proxying to a `mod_wsgi-express` instance.

Ignore that talks about docker as still relevant as you can run `mod_wsgi-express` on same host as different port.
