### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by chanchel** [GrahamDumpleton/mod_wsgi#854]
I have a completely fresh Ubuntu 22.04 installed with apache2 and python 3.10.12.  the ./configure works but when I run make it gives me:
 make
/usr/bin/apxs2 -c  -Wc,-g -Wc,-O2  src/server/mod_wsgi.c src/server/wsgi_*.c -L -L  -lpython
/usr/share/apr-1.0/build/libtool  --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -pipe -g -O2 -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security  -Wdate-time -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -g -O2  -c -o src/server/mod_wsgi.lo src/server/mod_wsgi.c && touch src/server/mod_wsgi.slo
libtool: compile:  x86_64-linux-gnu-gcc -pipe -g -O2 -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/usr/include/apache2 -I/usr/include/apr-1.0 -I/usr/include/apr-1.0 -I/usr/include -g -O2 -c src/server/mod_wsgi.c  -fPIC -DPIC -o src/server/.libs/mod_wsgi.o
In file included from src/server/mod_wsgi.c:22:
src/server/wsgi_python.h:26:10: fatal error: Python.h: No such file or directory
   26 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
apxs:Error: Command failed with rc=65536
.
make: *** [Makefile:31: src/server/mod_wsgi.la] Error 1
python3-dev is already installed, double and triple checked it.

**Comment by GrahamDumpleton** [comment]
What do you get when you run:

```
which python3
```

Does it come from a virtual environment or main system installation?

If a virtual environment, was it created before or after the python3-dev package was installed.

**Comment by GrahamDumpleton** [comment]
Can you also try the `pip install` method for installing mod_wsgi. See:

* https://pypi.org/project/mod-wsgi/
