### ISSUE TITLE
Setting up mod_wsgi with python virtual environment: no modules found.

### ISSUE THREAD

**Issue by njs236** [GrahamDumpleton/mod_wsgi#856]
I am running Manjaro Linux version 23.0
Running Python 3.11.5

I installed mod_wsgi version 4.9.4 using command
```
pamac build mod_wsgi
```
phpinfo() reports that this is the apache version
```
Apache/2.4.57 (Unix) PHP/8.2.10 mod_wsgi/4.9.4 Python/3.11
```

I've also tried installing mod_wsgi into the virtual environment (pip install mod_wsgi)

Configured an apache virtual environment with the following configuration:
```
<VirtualHost 127.0.0.1:80>
        ServerName  flask-app.com
        ServerAlias www.flask-app.com
        ServerAdmin webmaster@localhost
        DocumentRoot /srv/flask-app
 
        WSGIDaemonProcess flaskapp threads=5
        WSGIScriptAlias / /srv/flask-app/flaskapp.wsgi
        WSGIApplicationGroup %{GLOBAL}
        <Directory /srv/flask-app>
             Require all granted
        </Directory>
 
        ErrorLog /var/log/httpd/flaskapp-error.log
        CustomLog /var/log/httpd/flaskapp-access.log combined
</VirtualHost>
```
flaskapp.wsgi
```

import sys 
import logging

sys.path.append('/srv/flask-app')
sys.path.append('/path/to/venv/python3.11/site-packages')

#setup logging
logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

print(sys.path)

#import and run the flask app
from app import app as application
```
I installed flask into the virtual environment and when it runs the following error happens.
```
[Fri Sep 15 11:51:58.510427 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] mod_wsgi (pid=4594): Failed to exec Python script file '/srv/flask-app/flaskapp.wsgi'.
[Fri Sep 15 11:51:58.510468 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] mod_wsgi (pid=4594): Exception occurred processing WSGI script '/srv/flask-app/flaskapp.wsgi'.
[Fri Sep 15 11:51:58.510616 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] Traceback (most recent call last):
[Fri Sep 15 11:51:58.512430 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]   File "/srv/flask-app/flaskapp.wsgi", line 11, in <module>
[Fri Sep 15 11:51:58.512443 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]     from app import app as application
[Fri Sep 15 11:51:58.512450 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]   File "/srv/flask-app/app.py", line 1, in <module>
[Fri Sep 15 11:51:58.512453 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]     from flask import Flask
[Fri Sep 15 11:51:58.512464 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] ModuleNotFoundError: No module named 'flask'
```
Installing flask to system python makes it work but i'd like for the installation to work with a virtual environment.
I've tried using python-home property to the WSGIDaemonProcess and it timesout.
I added TimeOut 600 to httpd.conf. It just sits there without response.
I've also tried using WSGIPythonHome and WSGIPythonPath to httpd.conf with same results.

This is my first time setting up this kind of installation so any help would be appreciated.
Thanks in advance!

**Comment by GrahamDumpleton** [comment]
As already mentioned in original issue you created....

You are missing the `WSGIProcessGroup` directive to tell it to use that daemon process group.

That is wrong but in itself shouldn't have caused the problem.

Instead of using:

```
sys.path.append('/srv/flask-app')
sys.path.append('/path/to/venv/python3.11/site-packages')
```

you are better off using:

```
        WSGIDaemonProcess flaskapp threads=5 python-home=/path/to/venv python-path=/srv/flask-app
        WSGIProcessGroup flaskapp
        WSGIApplicationGroup %{GLOBAL}

        WSGIScriptAlias / /srv/flask-app/flaskapp.wsgi

```

Also ensure have:

```
LogLevel info
```

set in Apache virtual host and not default of `warn` or `err`. Use of `info` will result in mod_wsgi better showing what it is doing.

I would need to see the Apache error logs at `info` level for when timeout occurs.

Also, does your application use a database? If yes, was sort? Sqlite, or a separate database where connections done by socket?

**Comment by njs236** [comment]
Hi thanks for the response.

This is the only line in the error log pertinent to the problem (this is loglevel debug. if it's put at info i only get a single line which is the error at the end of this log section)
```
[Tue Sep 19 23:13:37.532403 2023] [authz_core:debug] [pid 18328] mod_authz_core.c(815): [client 127.0.0.1:42958] AH01626: authorization result of Require all granted: granted
[Tue Sep 19 23:13:37.532442 2023] [authz_core:debug] [pid 18328] mod_authz_core.c(815): [client 127.0.0.1:42958] AH01626: authorization result of <RequireAny>: granted
[Tue Sep 19 23:13:37.532503 2023] [authz_core:debug] [pid 18328] mod_authz_core.c(815): [client 127.0.0.1:42958] AH01626: authorization result of Require all granted: granted
[Tue Sep 19 23:13:37.532509 2023] [authz_core:debug] [pid 18328] mod_authz_core.c(815): [client 127.0.0.1:42958] AH01626: authorization result of <RequireAny>: granted
[Tue Sep 19 23:14:37.590631 2023] [wsgi:error] [pid 18328] [client 127.0.0.1:42958] Timeout when reading response headers from daemon process 'flaskapp': /srv/flask-app/flaskapp.wsgi
```
I have changed the virtual host configuration to this
```
<VirtualHost 127.0.0.1:80>
        ServerName  flask-app.com
        ServerAlias www.flask-app.com
        ServerAdmin webmaster@localhost
        DocumentRoot /srv/flask-app
 
        WSGIDaemonProcess flaskapp threads=5 python-home=/path/to/venv python-path=/srv/flask-app
        WSGIScriptAlias / /srv/flask-app/flaskapp.wsgi
        WSGIProcessGroup flaskapp
        WSGIApplicationGroup %{GLOBAL}
        <Directory /srv/flask-app>
             Require all granted
        </Directory>
 
        LogLevel debug
        ErrorLog /var/log/httpd/flaskapp-error.log
        CustomLog /var/log/httpd/flaskapp-access.log combined
</VirtualHost>
```
No database at the moment.

**Comment by GrahamDumpleton** [comment]
What third party Python packages are you using? A timeout like that suggests you could have thread locking issues, causing a dead lock, or the request hangs on talking to some backend.

To test, try using:

```
WSGIDaemonProcess flaskapp threads=1 python-home=/path/to/venv python-path=/srv/flask-app request-timeout=15
```

That is, add `request-timeout=15` and set `threads=1`.

This will cause request to fail after 15 seconds and a Python stack trace should be dumped to the Apache error log file showing where the code was stuck.

**Comment by njs236** [comment]
That's pretty useful thanks for advice!
It's just a standard virtual environment where i've installed one package, flask, into.

When I add request-timeout and threads there's no extra information from before. 
Debug log level just reports the same line about timeout
I've tried out the test file with the following contents 
```
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!'

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]
```
And it does the same thing. no stack trace from python
```
[Wed Sep 20 09:35:56.900714 2023] [wsgi:error] [pid 22088] [client 127.0.0.1:48232] Timeout when reading response headers from daemon process 'flaskapp': /srv/flask-app/test.py
```
Running through mod_wsgi-express has no issues.

**Comment by njs236** [comment]
Oh there's something i should say..
I've installed postgres. i will shutdown postgres and see if anything changes.

**Comment by GrahamDumpleton** [comment]
I really need to see the log out before the timeout message, from the main Apache error logs. Since you set `debug` log level, there should be lots of output from mod_wsgi. That output will indicate whether a request even got delivered to the mod_wsgi daemon process.

You can also trying using:

```
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!'

    print("HANDLING REQUEST")

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]
```

to see if that print message even gets logged, indicating that the WSGI application was actually invoked.

**Comment by njs236** [comment]
Graham, I think i've stumbled on the cause.
It was working through the system python
this the daemon process line I use for that
```
WSGIDaemonProcess flaskapp threads=5
```
inspecting logs it looks like an instance of python is loaded when httpd restarts (as expected)
you get the following output when httpd loads.
```
[Wed Sep 20 12:12:08.190596 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Attach interpreter ''.
[Wed Sep 20 12:12:08.266677 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9180): mod_wsgi (pid=29255): Started thread 0 in daemon process 'flaskapp'.
[Wed Sep 20 12:12:08.266754 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9180): mod_wsgi (pid=29255): Started thread 1 in daemon process 'flaskapp'.
[Wed Sep 20 12:12:08.266768 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9180): mod_wsgi (pid=29255): Started thread 2 in daemon process 'flaskapp'.
[Wed Sep 20 12:12:08.266779 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9180): mod_wsgi (pid=29255): Started thread 3 in daemon process 'flaskapp'.
[Wed Sep 20 12:12:08.266790 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9180): mod_wsgi (pid=29255): Started thread 4 in daemon process 'flaskapp'.
```
Where as if I have this line
```
WSGIDaemonProcess flaskapp threads=5 python-home=/path/to/venv python-path=/srv/flask-app
```
As expected with a restart you get this
```
Wed Sep 20 12:13:15.628298 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Shutdown requested 'flaskapp'.
[Wed Sep 20 12:13:15.628408 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Stopping process 'flaskapp'.
[Wed Sep 20 12:13:15.628413 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Destroying interpreters.
[Wed Sep 20 12:13:15.628416 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Cleanup interpreter ''.
[Wed Sep 20 12:13:15.628427 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Terminating Python.
[Wed Sep 20 12:13:15.629949 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9161): mod_wsgi (pid=29255): Exiting thread 4 in daemon process 'flaskapp'.
[Wed Sep 20 12:13:15.630063 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9161): mod_wsgi (pid=29255): Exiting thread 3 in daemon process 'flaskapp'.
[Wed Sep 20 12:13:15.630081 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9161): mod_wsgi (pid=29255): Exiting thread 2 in daemon process 'flaskapp'.
[Wed Sep 20 12:13:15.630103 2023] [wsgi:debug] [pid 29255] src/server/mod_wsgi.c(9161): mod_wsgi (pid=29255): Exiting thread 1 in daemon process 'flaskapp'.
[Wed Sep 20 12:13:15.631302 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Python has shutdown.
[Wed Sep 20 12:13:15.631320 2023] [wsgi:info] [pid 29255] mod_wsgi (pid=29255): Exiting process 'flaskapp'.
```
Which has conspicuous absence of the Attaching interpreter line
and any threads that should be firing up.

**Comment by GrahamDumpleton** [comment]
To avoid confusing messages related to Python in Apache child worker processes, set:

```
WSGIRestrictEmbedded On
```

outside of any ``VirtualHost``.

This will ensure that Python is only initialised in the mod_wsgi daemon processes.

After doing that, also look in the main Apache error log file for anything strange and not just the `VirtualHost` error log.

**Comment by njs236** [comment]
Here we go... 

Thanks for the help. I've finally found what the error is... nothing related to mod_wsgi. The virtual environment python is causing an error which makes it not load.

My virtual environment doesn't have a module named 'encodings' which i can confirm is part of my system python. Now to work out how to fix the making of this virtual environment on manjaro.

**Comment by GrahamDumpleton** [comment]
Make sure your Python virtual environment is created using same Python version as mod_wsgi was compiled for. Can’t mix versions or Python distros. Could also be a permissions issue where Apache cannot read the virtual environment properly.

**Comment by njs236** [comment]
What's the best practice for location of virtual environments?
It appears because my environment is in the home folder, permissions are the issue here.

**Comment by njs236** [comment]
I finally got it! Thanks for the patience Graham!
