### ISSUE TITLE
Bad gateway apache + wsgi

### ISSUE THREAD

**Issue by klimovskis** [GrahamDumpleton/mod_wsgi#860]
I have a flask website running on ubuntu with apache and wsgi. 
All website pages work well expect for one that executes a long python script calling the api. 
When I open this page, the script executes (I see it in logs) but the page displays "bad gateway." 
No errors in logs. 

Here is my conf file:

```
<VirtualHost *:80>

        ServerName http://24.144.68.38

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html


        WSGIDaemonProcess flaskapp threads=5
        WSGIScriptAlias / /var/www/html/HR_sense/app.wsgi
        WSGIApplicationGroup %{GLOBAL}
        <Directory HR_sense>
             WSGIProcessGroup HR_sense
             WSGIApplicationGroup %{GLOBAL}
             Order deny,allow
             Allow from all
        </Directory>
        <Directory /var/www/html/HR_sense/static/uploads>
             Order allow,deny
             Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

Please assist.

**Comment by GrahamDumpleton** [comment]
Add:

```
LogLevel info
```

The default error level of `warn` means mod_wsgi will not log lots of stuff.

Besides that, your configuration is incorrect and you aren't using mod_wsgi daemon mode anyway. This leads me to think that the bad gateway error is coming from some proxy in front of the Apache instance and not this Apache instance or mod_wsgi.

Use the configuration:

```
<VirtualHost *:80>

        # XXX This is wrong. ServerName can't be a URL and should be a valid hostname.
        ServerName http://24.144.68.38

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        WSGIDaemonProcess flaskapp threads=5

        # XXX You should not put your WSGI script file under Apache document root as it could be downloaded if
        # XXX you messed up configurtation and was a way to map URL to it.
        WSGIScriptAlias / /var/www/html/HR_sense/app.wsgi

        WSGIApplicationGroup %{GLOBAL}

        # XXX You were missing this line to delegate to "flaskapp" daemon process group.
        WSGIProcessGroup flaskapp

        # XXX This should be where WSGI script file is, but as I said it shouldn't be under Apache document root.
        # XXX Because you had it under the Apache document root this wasn't actually needed, but will be if you move it.
        <Directory /var/www/html/HR_sense>
             Order deny,allow
             Allow from all
        </Directory>

        # XXX Uploads should also potentially not be under Apache document root if no need to download again.
        # XXX These files couldn't be downloaded again anyway, as not alias maps to directory.
        <Directory /var/www/html/HR_sense/static/uploads>
             Order allow,deny
             Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        LogLevel info

</VirtualHost>
```

As you can see there is a lot wrong with it. At least fix up the missing `WSGIProcessGroup` for delegating to `flaskapp`, as well as enable more logging info.

I would also suggest adding:

```
WSGIRestrictEmbedded On
```

outside of the `VirtualHost`.

This will ensure only mod_wsgi daemon mode can be used and you will get an error if isn't as would have been case in your original configuration.

**Comment by klimovskis** [comment]
Thanks for reply. I have added the edits. The problem persists. The script competes but I see only bad gateway. 
`[Fri Oct 06 21:33:40.260698 2023] [mpm_event:notice] [pid 15822:tid 139675547867008] AH00492: caught SIGWINCH, shutting down gracefully
[Fri Oct 06 21:33:40.748407 2023] [mpm_event:notice] [pid 28742:tid 139918042314624] AH00489: Apache/2.4.55 (Ubuntu) mod_wsgi/4.9.4 Python/3.11 configured -- resuming normal operations
[Fri Oct 06 21:33:40.748561 2023] [core:notice] [pid 28742:tid 139918042314624] AH00094: Command line: '/usr/sbin/apache2'
[Fri Oct 06 21:33:40.816788 2023] [wsgi:info] [pid 28743:tid 139918042314624] mod_wsgi (pid=28743): Attach interpreter ''.
[Fri Oct 06 21:33:43.400780 2023] [wsgi:info] [pid 28743:tid 139917986346688] [remote 185.2.28.104:52905] mod_wsgi (pid=28743, process='flaskapp', application=''): Loading Python script file '/var/www/html/HR_sense/app.wsgi'.
`
Thanks.

**Comment by GrahamDumpleton** [comment]
What API is your script calling? Is it a down stream HTTP API? Are you sure it isn't the downstream API which is returning that error and your WSGI application is just passing it through? Have you added debug code in your WSGI application to log the response from the downstream API to see if it returns and what it returns?

**Comment by klimovskis** [comment]
I submit a CV text to the api and get back the response. The response is logged. 
The response is correct. 
`[Fri Oct 06 21:33:56.795613 2023] [wsgi:error] [pid 28743:tid 139917986346688] [remote 185.2.28.104:64849] /var/www/html/HR_sense/static/uploads/Imaging.pdf
[Fri Oct 06 21:33:56.806276 2023] [wsgi:error] [pid 28743:tid 139917986346688] [remote 185.2.28.104:64849] /var/www/html/HR_sense/static/uploads/Lab_values.pdf
[Fri Oct 06 21:34:19.638888 2023] [wsgi:error] [pid 28743:tid 139917986346688] [remote 185.2.28.104:64849] Rejected.
[Fri Oct 06 21:34:19.638917 2023] [wsgi:error] [pid 28743:tid 139917986346688] [remote 185.2.28.104:64849] 
[Fri Oct 06 21:34:19.638923 2023] [wsgi:error] [pid 28743:tid 139917986346688] [remote 185.2.28.104:64849] The qualifications and experiences explained in the CV do not match the requirements for the junior python developer role. The candidate did not present any experience or skills related to programming, framework knowledge, problem-solving, or software development methodologies, which are critical to the role.
[Fri Oct 06 21:34:19.638965 2023] [wsgi:error] [pid 28743:tid 139917986346688] [remote 185.2.28.104:64849] 
[Fri Oct 06 21:34:19.639350 2023] [wsgi:error] [pid 28743:tid 139917986346688] [remote 185.2.28.104:64849] {'id': 1, 'name': 'Test', 'email': 'test@test.lv', 'cv_filename': 'Imaging.pdf', 'cover_filename': 'Lab_values.pdf', 'decision': 'rejected', 'result': 'Rejected.\\n\\nThe qualifications and experiences explained in the CV do not match the requirements for the junior python developer role. The candidate did not present any experience or skills related to programming, framework knowledge, problem-solving, or software development methodologies, which are critical to the role.', 'email_send': "Subject: Job Application Status for Junior Python Developer Role\\n\\nDear [Candidate's Name],\\n\\nI hope this message finds you well.\\n\\nI am pleased to inform you that we have had the opportunity to discuss at length and review your application for the position of the Junior Python Developer at our organization. After extensive consideration, I regret to inform you that we will not be proceeding with your application for this specific role.\\n\\nWhile we value your experience and qualifications, the specific requirements for this role demand a deeper familiarity with programming, particularly in Python, understanding of frameworks, proven problem-solving abilities, and knowledge of software development methodologies. These fundamental skills are vital in ensuring the effective execution of the responsibilities that come with the role.\\n\\nPlease do not let this discourage you. Remember that not being selected for this particular role does not classify you as not being proficient or valued in your field. It merely suggests that this specific role wasn't the perfect fit for your profile. We recommend marking your resume by clearly highlighting your real strengths, experiences, and talents against the job requirement for future applications.\\n\\nWe encourage you to keep checking our jobs page for future vacancies more aligned with your qualifications and expertise. We believe there will be roles that fit your skills and interests wherein you could make significant contributions.\\n\\nWe appreciate your interest in our organization and want to thank you for the time and efforts you put into the application process. \\n\\nBest of luck with your future endeavors, and thank you once again for your application.\\n\\nWarm Regards,\\n\\n[Your Name]\\n[Your Job Title]\\n[Your Email]\\n[Your Phone Number]\\n"}
[Fri Oct 06 21:39:36.150590 2023] [wsgi:error] [pid 28745:tid 139917862618816] [client 61.152.193.73:23504] mod_wsgi (pid=28745): Request data read error when proxying data to daemon process: Partial results are valid but processing is incomplete.
[Fri Oct 06 23:47:42.400799 2023] [reqtimeout:info] [pid 28744:tid 139917736728256] [client 34.239.159.44:51432] AH01382: Request header read timeout
[Fri Oct 06 23:47:42.400977 2023] [reqtimeout:info] [pid 28744:tid 139917994739392] [client 34.239.159.44:51424] AH01382: Request header read timeout
[Sat Oct 07 04:47:42.355357 2023] [reqtimeout:info] [pid 28744:tid 139917778691776] [client 3.83.32.171:37996] AH01382: Request header read timeout
[Sat Oct 07 04:47:42.355548 2023] [reqtimeout:info] [pid 28745:tid 139917837440704] [client 3.83.32.171:37988] AH01382: Request header read timeout`

**Comment by GrahamDumpleton** [comment]
What Apache directives are you setting for the mod_reqtimeout module?

https://httpd.apache.org/docs/2.4/mod/mod_reqtimeout.html

Settings for that may be interfering with things.

**Comment by klimovskis** [comment]
Thanks. 
`[Sat Oct 07 09:45:08.070369 2023] [reqtimeout:info] [pid 60512:tid 139704640972480] [client 138.199.55.180:24723] AH01382: Request header read timeout
`
I guess I should specify longer timeout in cons file?

**Comment by GrahamDumpleton** [comment]
I have no idea. As I asked, can you provide any directives you are setting for the mod_reqtimeout module so I can see what you are using? I actually don't understand why setting those directives would cause a problem in the proxy connection with the daemon process. Thus why I need to see what combination of directives you are using and compare it with what have used before and know works in mod_wsgi-express.

**Comment by klimovskis** [comment]
Thanks. I do not have them explicitly stated in conf file. Therefore, I believe they are default ones. While the script is loading, there is timeout. So once in flask I call render page, it results in bad gateway, because the address does not exist anymore or so. 
How should I specify the timeout?

**Comment by GrahamDumpleton** [comment]
Try not loading mod_reqtimeout in Apache then. Usually it wouldn't be loaded by default, so not sure how it has been added in your case.

The other possible problem if this is the only handler affected by this problem is that the way the WSGI application response is returned is wrong, and a response not actually returned.

What does the Flask handler for this endpoint actually look like?

**Comment by GrahamDumpleton** [comment]
Thinking about this some more, the problem looks more to be how the HTTP client is sending data to your WSGI application.

What calls your WSGI application for this request? Is it some sort of POST request with a file upload? Is that HTTP client trying to do something strange like compress the POST request data?

**Comment by klimovskis** [comment]
Thanks. 
"Try not loading mod_reqtimeout in Apache then" - how can I do that? 

Flask code:

We get files and send them through the API. API gives a response. We store it in database and retrieve all needed info from the database. Then, we render the page with this data. 

Locally it worked. 

`@app.route('/candidate/<int:candidate_id>')
def candidate(candidate_id):
    cv_link, cover_link, position_description = get_document_link(candidate_id)
    cv = extract_pdf(cv_link)
    cover = extract_pdf(cover_link)
    result = elis.candidate_analysis(cv, cover, position_description)

    # Check if the word "accepted" is in the text
    if 'accepted' in result.lower():
        decision = "accepted"
    else:
        decision = "rejected"

    email_send = elis.email_end(cv, cover, result)

    update_database(candidate_id, decision, result, email_send)

    print(result)
    application = get_application_by_id(candidate_id)
    print(application)
    if application:
        return render_template('application_detail.html', application=application)
    else:
        print("test")
        return "Application not found", 404
`

**Comment by klimovskis** [comment]
The thing is that the script works fine, you may see from the logs all print statements.

**Comment by GrahamDumpleton** [comment]
How you disable an Apache module depends on how your Linux distribution configures Apache. So you will need to try and work that out from Linux distro docs.

The problem is those errors relate to when mod_wsgi is trying to copy the body of the request from the HTTP request received by Apache. That there is an error at that point sort of indicates there is something wrong with the HTTP request. The headers may well get through to your WSGI application and so it processes the request, but there is perhaps a content length set with no actual body sent or something like that and so an error occurs.

Is the HTTP request a normal browser page request, or is it done using Javascript to make the request.

All I can suggest is using something like as described in:

https://modwsgi.readthedocs.io/en/master/user-guides/debugging-techniques.html#tracking-request-and-response

to log what the raw request and response is as seen by the WSGI application to try and work out what is amiss.
