### ISSUE TITLE
The server doesn't work with Python 3.12 on Fedora Linux

### ISSUE THREAD

**Issue by befeleme** [GrahamDumpleton/mod_wsgi#865]
I use mod_wsgi to test our Python containers.
In a container with Fedora Linux 39 and Python 3.12, I can't use mod_wsgi's server with Apache.
The name of the so library that is created by the program is incorrect:
```
mod_wsgi-express module-config
LoadModule wsgi_module "/opt/app-root/lib64/python3.12/site-packages/mod_wsgi/server/mod_wsgi-py312.so"
```
Reality: `mod_wsgi-py312.cpython-312-x86_64-linux-gnu.so`

It looks like the culprit is here - Python 3.12 doesn't come with distutils, so the whole code block which should set the name parts is skipped and the execution continues after the exception:
https://github.com/GrahamDumpleton/mod_wsgi/blob/ac1a8e6cfffda292f688de1a6628835887be6e63/src/server/__init__.py#L36-L38

**Comment by GrahamDumpleton** [comment]
Can you try:

* https://pypi.org/project/mod-wsgi/5.0.0rc1/

**Comment by befeleme** [comment]
This does work in my use case, indeed!

**Comment by GrahamDumpleton** [comment]
Version 5.0.0 has now been released.

**Comment by befeleme** [comment]
Thank you
