### ISSUE TITLE
 [wsgi:error] [pid 1956743] [remoteserver -ip] ImportError: No module named django.core.wsgi

### ISSUE THREAD

**Issue by Abhinavwani3141** [GrahamDumpleton/mod_wsgi#866]
website is hosted on ec2 apache web server after checking error log this error is shown  [wsgi:error] [pid 1956743] [remoteserver -ip] ImportError: No module named django.core.wsgi  but django is already intalled

**Comment by GrahamDumpleton** [comment]
Impossible to give any advice without seeing what mod_wsgi configuration you used and details about where Django was installed to, plus where your project code is. If you are using a Python virtual environment to install Django into, you need to configure mod_wsgi to tell it where the Python virtual environment is. The Django documentation provides example of how to do this for mod_wsgi so make sure you are interpreting the Django documentation correctly.
