### ISSUE TITLE
SELinux enabled environment info has broken links. 

### ISSUE THREAD

**Issue by EndermanAPM** [GrahamDumpleton/mod_wsgi#877]
Hi,

I am currently in the process of deploying a Django application using mod_wsgi on a Rocky Linux 9 system. During this process, I encountered issues related to SELinux, which were temporarily resolved by disabling SELinux. However, I recognize that disabling SELinux is not a sustainable or secure solution. I believe the optimal approach would be to maintain SELinux in an enabled state and configure appropriate exceptions to accommodate the deployment.

In my efforts to find a solution, I attempted to consult the documentation for guidance on configuring SELinux exceptions for this purpose. Unfortunately, I discovered that the links to the relevant sections of the documentation were not functional.

https://github.com/GrahamDumpleton/mod_wsgi/blob/f54eadd6da8e3da0faccd497d4165de435b97242/docs/user-guides/application-issues.rst#L165-L170

Could you please direct me to up-to-date resources or documentation that could assist me in resolving the SELinux configuration issues I am facing with my Django deployment? Any assistance or guidance you can provide on this matter would be greatly appreciated.

Thank you for your time and support.

**Comment by GrahamDumpleton** [comment]
Sorry, am not aware of any links at this time to replace them with and am not knowledgable on SELinux. Can only suggest you use Google to search for "mod_wsgi httpd SELinux" to see what you can find. If you find any that look relevant please let me know.
