### ISSUE TITLE
Python needs to be compiled with the `-fPIC` flag set

### ISSUE THREAD

**Issue by chaosflaws** [GrahamDumpleton/mod_wsgi#879]
I tried compiling mod_wsgi for Python 3.12 on a Debian Bullseye machine. With the default settings, I ran into linking issues the likes of:

``/usr/bin/ld: /usr/local/lib/libpython3.12.a(import.o): relocation R_X86_64_TPOFF32 against hidden symbol `pkgcontext' can not be used when making a shared object``

Recompiling python with the `-fPIC` flag set (`CFLAGS=-fPIC ./configure --enable-optimizations`) solved the problem.

This may be worth mentioning [in the docs](https://modwsgi.readthedocs.io/en/develop/user-guides/installation-issues.html).

**Comment by GrahamDumpleton** [comment]
Which is a variation of this documented issue.

https://modwsgi.readthedocs.io/en/master/user-guides/installation-issues.html#mixing-32-bit-and-64-bit-packages

There is a bunch of different error codes it can generate and they seem to keep changing. Never been able to keep track of them all.

Also see:

http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

which has a long description of what is required to try and emulate what would be standard Python install for a specific Linux environment.
