### ISSUE TITLE
Cannot load modules/mod_wsgi.so into server: /local/apps/tcapp/apache/modules/mod_wsgi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joythebest83** [GrahamDumpleton/mod_wsgi#881]
I am getting above mentioned error while restarting Apache. I have already entered 
LoadModule wsgi_module modules/mod_wsgi.so in httpd.conf. I have installed wsgi_module via yum install command so that I don't need to worry about dependencies.

sudo yum -y install mod_wsgi

![image](https://github.com/GrahamDumpleton/mod_wsgi/assets/13747372/091248eb-36fe-42c2-9d29-ff2881c7dafa)

**Comment by GrahamDumpleton** [comment]
Obvious thing is whether the file `/local/apps/tcapp/apache/modules/mod_wsgi.so` actually exists.

One can though also get that misleading error when any shared library linked to the mod_wsgi.so file cannot be found when the dynamic linker is run.

What do you get when you run:

```
ls -las /local/apps/tcapp/apache/modules/mod_wsgi.so
```

and:

```
ldd /local/apps/tcapp/apache/modules/mod_wsgi.so
```

**Comment by GrahamDumpleton** [comment]
Closing since no followup.
