### ISSUE TITLE
mod_wsgi (pid=11692): Failed to exec Python script file 'F:/bushu/code/django_yolox/django_yolox/wsgi.py'.

### ISSUE THREAD

**Issue by lllittleX** [GrahamDumpleton/mod_wsgi#885]
Hello everyone, I'm encountering an issue while starting the Apache service:

[Tue Apr 30 11:28:01.017701 2024] [mpm_winnt:notice] [pid 10072:tid 380] AH00455: Apache/2.4.59 (Win64) mod_wsgi/4.9.4 Python/3.6 configured -- resuming normal operations
[Tue Apr 30 11:28:01.017701 2024] [mpm_winnt:notice] [pid 10072:tid 380] AH00456: Apache Lounge VS17 Server built: Apr  4 2024 15:03:17
[Tue Apr 30 11:28:01.017701 2024] [core:notice] [pid 10072:tid 380] AH00094: Command line: 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe -d F:/bushu/code/Apache24'
[Tue Apr 30 11:28:01.020700 2024] [mpm_winnt:notice] [pid 10072:tid 380] AH00418: Parent: Created child process 11692
[Tue Apr 30 11:28:01.416496 2024] [mpm_winnt:notice] [pid 11692:tid 396] AH00354: Child: Starting 64 worker threads.
[Tue Apr 30 11:28:09.132970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610] mod_wsgi (pid=11692): Failed to exec Python script file 'F:/bushu/code/django_yolox/django_yolox/wsgi.py'.
[Tue Apr 30 11:28:09.132970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610] mod_wsgi (pid=11692): Exception occurred processing WSGI script 'F:/bushu/code/django_yolox/django_yolox/wsgi.py'.
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610] Traceback (most recent call last):\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "F:/bushu/code/django_yolox/django_yolox/wsgi.py", line 16, in <module>\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     application = get_wsgi_application()\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     django.setup(set_prefix=False)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     apps.populate(settings.INSTALLED_APPS)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\apps\\registry.py", line 114, in populate\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     app_config.import_models()\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\apps\\config.py", line 301, in import_models\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     self.models_module = import_module(models_module_name)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\contrib\\auth\\models.py", line 3, in <module>\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\contrib\\auth\\base_user.py", line 48, in <module>\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     class AbstractBaseUser(models.Model):\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\db\\models\\base.py", line 122, in __new__\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     new_class.add_to_class('_meta', Options(meta, app_label))\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\db\\models\\base.py", line 326, in add_to_class\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     value.contribute_to_class(cls, name)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\db\\models\\options.py", line 207, in contribute_to_class\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\utils\\connection.py", line 15, in __getattr__\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     return getattr(self._connections[self._alias], item)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\utils\\connection.py", line 62, in __getitem__\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     conn = self.create_connection(alias)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\db\\utils.py", line 204, in create_connection\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     backend = load_backend(db['ENGINE'])\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\db\\utils.py", line 111, in load_backend\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     return import_module('%s.base' % backend_name)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py", line 15, in <module>\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     from sqlite3 import dbapi2 as Database\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\sqlite3\\__init__.py", line 23, in <module>\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     from sqlite3.dbapi2 import *\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]   File "D:\\work_software\\ANA\\envs\\torch-env\\lib\\sqlite3\\dbapi2.py", line 27, in <module>\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610]     from _sqlite3 import *\r
[Tue Apr 30 11:28:09.134970 2024] [wsgi:error] [pid 11692:tid 1184] [client 127.0.0.1:49610] ImportError: DLL load failed: \xe6\x89\xbe\xe4\xb8\x8d\xe5\x88\xb0\xe6\x8c\x87\xe5\xae\x9a\xe7\x9a\x84\xe6\xa8\xa1\xe5\x9d\x97\xe3\x80\x82\r

I can't pinpoint where the problem is. Could you help me find a solution?

**Comment by GrahamDumpleton** [comment]
It looks like your Python installation is a bit broken with Windows registry entries or environment not being setup correctly. Since Python 3.6 is so old and no longer supported, I would suggest uninstalling Python 3.6 and upgrade to a more recent Python version and rebuild/reinstall everything for it. Alternatively, try reinstalling the same Python 3.6 distribution version, ensuring that it is installed for all users and not just your own user.

**Comment by lllittleX** [comment]
Thank you for your answer. I will switch to a newer version of Python. However, I still have a question. I'm using a Python virtual environment, and in my httpd.conf, I set the following code:

LoadFile "D:/work_software/ANA/envs/torch-env/python36.dll"
LoadModule wsgi_module "D:/work_software/ANA/envs/torch-env/lib/site-packages/mod_wsgi/server/mod_wsgi.cp36-win_amd64.pyd"
WSGIPythonHome "D:/work_software/ANA/envs/torch-env"
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / F:/bushu/code/django_yolox/django_yolox/wsgi.py
WSGIPythonPath F:/bushu/code/django_yolox
<Directory F:/bushu/code/django_yolox>
<Files wsgi.py>  
    Require all granted
</Files>
</Directory>
Alias /static F:/bushu/code/django_yolox/django_yolox/static
<Directory F:/bushu/code/django_yolox/django_yolox/static> 
    AllowOverride None 
    Options None 
    Require all granted
</Directory>

 but I'm getting an error:
Current thread 0x00003574 (most recent call first):
[Tue Apr 30 11:58:50.961696 2024] [mpm_winnt:crit] [pid 7796:tid 380] AH00419: master_main: create child process failed. Exiting.
[Tue Apr 30 12:02:32.331020 2024] [mpm_winnt:notice] [pid 18232:tid 384] AH00455: Apache/2.4.59 (Win64) mod_wsgi/4.9.4 Python/3.6 configured -- resuming normal operations
[Tue Apr 30 12:02:32.331020 2024] [mpm_winnt:notice] [pid 18232:tid 384] AH00456: Apache Lounge VS17 Server built: Apr  4 2024 15:03:17
[Tue Apr 30 12:02:32.331020 2024] [core:notice] [pid 18232:tid 384] AH00094: Command line: 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe -d F:/bushu/code/Apache24'
[Tue Apr 30 12:02:32.422977 2024] [mpm_winnt:notice] [pid 18232:tid 384] AH00418: Parent: Created child process 1432
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

 I'm on a Windows system, and my Apache version is 2.4.59.

**Comment by GrahamDumpleton** [comment]
You must recreate the Python virtual environment and rebuild mod_wsgi with the newer Python version. Messages indicate things still using Python 3.6.

**Comment by GrahamDumpleton** [comment]
And you would need to update the LoadFile line etc in Apache configuration to refer to new version you built.

**Comment by lllittleX** [comment]
Okay, I installed a new virtual environment, which is Python 3.8, but I'm still getting an error：
[Tue Apr 30 14:30:47.157293 2024] [mpm_winnt:notice] [pid 6380:tid 380] AH00455: Apache/2.4.59 (Win64) mod_wsgi/5.0.0 Python/3.8 configured -- resuming normal operations
[Tue Apr 30 14:30:47.157293 2024] [mpm_winnt:notice] [pid 6380:tid 380] AH00456: Apache Lounge VS17 Server built: Apr  4 2024 15:03:17
[Tue Apr 30 14:30:47.157293 2024] [core:notice] [pid 6380:tid 380] AH00094: Command line: 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe -d F:/bushu/code/Apache24'
[Tue Apr 30 14:30:47.246608 2024] [mpm_winnt:notice] [pid 6380:tid 380] AH00418: Parent: Created child process 20240
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe'
  sys.base_prefix = 'D:\\work_software\\ANA\\envs\\pytorch_cpu_py38'
  sys.base_exec_prefix = 'D:\\work_software\\ANA\\envs\\pytorch_cpu_py38'
  sys.executable = 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe'
  sys.prefix = 'D:\\work_software\\ANA\\envs\\pytorch_cpu_py38'
  sys.exec_prefix = 'D:\\work_software\\ANA\\envs\\pytorch_cpu_py38'
  sys.path = [
    'D:\\work_software\\ANA\\envs\\pytorch_cpu_py38\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    'F:\\bushu\\code\\Apache24\\bin',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000035c4 (most recent call first):
<no Python frame>
[Tue Apr 30 14:30:47.614255 2024] [mpm_winnt:crit] [pid 6380:tid 380] AH00419: master_main: create child process failed. Exiting.

**Comment by GrahamDumpleton** [comment]
Was Python installed for all users of the system?

Apache usually runs as a special user and you can get this error when Python is not installed for all users as the configuration would only have been set up in the Windows registry for your user.

**Comment by GrahamDumpleton** [comment]
Also, you can get this problem if using Anaconda Python. That Python distribution has broken embedding as is done in Apache/mod_wsgi many times and most of the time it just will not work. It is recommended to use Python distro from the Python Software Foundation (PSF).

**Comment by lllittleX** [comment]
T-T, yes, I used Anaconda Python. I will try switching to another version.

**Comment by lllittleX** [comment]
Hello, I used the Python version you mentioned, but I'm still encountering an issue with encodings.
Starting the 'django_yolox' service
The 'django_yolox' service is running.
winnt:notice] [pid 6888:tid 380] AH00455: Apache/2.4.59 (Win64) mod_wsgi/4.9.2 Python/3.8 configured -- resuming normal operations
[Tue Apr 30 16:39:25.529457 2024] [mpm_winnt:notice] [pid 6888:tid 380] AH00456: Apache Lounge VS17 Server built: Apr  4 2024 15:03:17
[Tue Apr 30 16:39:25.529457 2024] [core:notice] [pid 6888:tid 380] AH00094: Command line: 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe -d F:/bushu/code/Apache24'
[Tue Apr 30 16:39:25.618242 2024] [mpm_winnt:notice] [pid 6888:tid 380] AH00418: Parent: Created child process 18076
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe'
  sys.base_prefix = 'F:\\bushu\\code\\Python38'
  sys.base_exec_prefix = 'F:\\bushu\\code\\Python38'
  sys.executable = 'F:\\bushu\\code\\Apache24\\bin\\httpd.exe'
  sys.prefix = 'F:\\bushu\\code\\Python38'
  sys.exec_prefix = 'F:\\bushu\\code\\Python38'
  sys.path = [
    'F:\\bushu\\code\\Python38\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    'F:\\bushu\\code\\Apache24\\bin',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001674 (most recent call first):
<no Python frame>
[Tue Apr 30 16:39:26.021214 2024] [mpm_winnt:crit] [pid 6888:tid 380] AH00419: master_main: create child process failed. Exiting.
