### ISSUE TITLE
AddHandler mod_python / PythonHandler mod_python.publisher analog in wsgi?

### ISSUE THREAD

**Issue by terrafrost** [GrahamDumpleton/mod_wsgi#886]
I was using libapache2-mod-python with `AddHandler mod_python` and `PythonHandler mod_python.publisher` in my .htaccess file to serve up *.py files. I'm trying to use libapache2-mod-wsgi now and am unsure of how to duplicate this functionality.

**Comment by GrahamDumpleton** [comment]
There is no direct equivalent. You are better off rewriting to use a basic WSGI framework such as Flask (https://flask.palletsprojects.com/en/3.0.x/). Modern day WSGI frameworks are much more powerful and more secure than mod_python.publisher ever was.
