### ISSUE TITLE
Option to enable log rotation in mod_wsgi express.

### ISSUE THREAD

**Issue by GrahamDumpleton** [GrahamDumpleton/mod_wsgi#9]
Add a `--rotate-logs` argument to have rotatelogs to be used with piped logger to enable log file rotation and ageing.

**Comment by sirfz** [comment]
I was wondering if there's a clean way to specify the count of log files to keep. For example, I specify the log size to 50 and log count to 5, this means Apache should only keep the latest 5 log files and delete older ones. I know this can be done using a cronjob but I'm trying to find a nicer solution directly through Apache. Maybe a way to specify a different rotatelogs-executable (as we currently can) with custom parameters (I'm thinking about [logrotate](http://www.linuxcommand.org/man_pages/logrotate8.html))

**Comment by GrahamDumpleton** [comment]
I don't know of any way with Apache to have it clean up older log files.

When using mod_wsgi-express you could always use the ``--rotatelogs-executable`` option to specify a compatible program to perform logging which is smart enough to remove older log files, but I don't know of a something which does that itself.

If you simply want to avoid cron, then with mod_wsgi-express you could hack something together using a service script which mod_wsgi would then manage the execution of for you.

To do this you would add the option ``--service-script cleanup-logs /some/path/cleanup-logs.py``.

In the ``/some/path/cleanup-logs.py`` you would then use something like:

```
import threading
import time

def check_logs():
    # Add code here which see whether old logs to remove and remove them.
   time.sleep(3600)

thread = threading.Thread(target=check_logs)
thread.setDaemon()
thread.start()
```

Basically it uses a mod_wsgi daemon process just to run your little Python script in a loop, but where the mod_wsgi daemon process doesn't actually run a WSGI application or handle any requests. The process will just sit their dormant while in the sleep, although it make have to be a bit more intelligent than what I have.

So you could code up the specific tasks you need to do, or see if you could find a decent in process Python based cron like execution system so you could just define a function and then attach a decorator to it with a schedule. I don't know whether there is a reputable such cron package or not.

The use of a background thread is currently preferred because in such a use case signals aren't getting handled properly if the work is done as part of the module important and so the process doesn't get shut down promptly when Apache is restarted, instead being killed after 3 seconds. I am still trying to work out what behaviour makes the most sense in this sort of service script situation, especially where the script import has an exception.

**Comment by sirfz** [comment]
I can use cron but I was looking for something similar to python's `RotatingFileHandler` which has the `backupCount` option. The `service-script` option is very interesting and I'm glad you mentioned it here (regardless if I'm going to use it for log cleanup). It's all clear now, thanks for your help :)
