### ISSUE TITLE
mod wsgi with python 3.9 & django 3.2.x just hanging

### ISSUE THREAD

**Issue by adityayudhi** [GrahamDumpleton/mod_wsgi#911]
hi, i have django project python3.9 django 3.2 and apache2.4.59, mod wsgi version 5.0.1
by the way, i'm using wamp to server apache

i've been config my project and apache to run with WSGI,

but if i hit localhost in address bar, it start hanging, not server anything not serve any error in apache error log
help me to handle it 
this is my config

**httpd.conf**

> LoadFile "c:/program files/python39/python39.dll"
LoadModule wsgi_module "C:/Users/handr/AppData/Roaming/Python/Python39/site-packages/mod_wsgi/server/mod_wsgi.cp39-win_amd64.pyd"
WSGIPythonHome "c:/program files/python39"

**vhost**

> <VirtualHost *:80>
    ServerName localhost 

    ErrorLog "D:/python_project/handrail_project/my_project.error.log"
    CustomLog "D:/python_project/handrail_project/my_project.access.log" combined

    WSGIScriptAlias /  "D:/python_project/handrail_project/handrail_cms/handrail_cms/wsgi.py"
    <Directory "D:/python_project/handrail_project/handrail_cms/handrail_cms">
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    Alias /static/ "D:/python_project/handrail_project/handrail_cms/assets_root"
    <Directory "D:/python_project/handrail_project/handrail_cms/assets_root">
        Require all granted
    </Directory>  
    
    Alias /media/ "D:/python_project/handrail_project/handrail_cms/media"
    <Directory "D:/python_project/handrail_project/handrail_cms/media">
        Require all granted
    </Directory>
</VirtualHost>

**wsgi.py**

> import site
import sys

import os

site.addsitedir("C:/Users/handr/AppData/Roaming/Python/Python39/site-packages")

sys.path.append("D:/python_project/handrail_project/handrail_cms")

from django.core.wsgi import get_wsgi_application

os.environ['DJANGO_SETTINGS_MODULE'] = 'handrail_cms.settings' 
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'handrail_cms.settings')

application = get_wsgi_application()

Thankyou...

**Comment by adityayudhi** [comment]
i'm using windows 11 machine

**Comment by GrahamDumpleton** [comment]
Add:

```
WSGIApplicationGroup %{GLOBAL}
```

You likely are using a third party Python package that does not work in Python sub interpreters.

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#python-simplified-gil-state-api

**Comment by adityayudhi** [comment]
Thankyou so much ,.. it works.. you saved me ...
