### ISSUE TITLE
Reinstall ModWSGI after upgrading to ElCapitan.  (Macbook)

### ISSUE THREAD

**Issue by davies-barnard** [GrahamDumpleton/mod_wsgi#98]
Hi Graham,

Just upgraded my Mac to El Capitan and killed my working Apache/Mod_WSGI installation.  Had to install Xcode Command Line tools and accept the Ts&Cs before it would .configure and now I'm getting the following error message.

**install: /usr/libexec/apache2/mod_wsgi.so: Operation not permitted
apxs:Error: Command failed with rc=4653056**

Output from my terminal is below and I include the Makefile contents at the bottom. Thanks for your time and any ideas on how I can fix this would be grateful.

Cheers

Chris

daviesc@orion:mod_wsgi-develop [0]$ sudo ./configure
checking for apxs2... no
checking for apxs... /usr/sbin/apxs
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for prctl... no
checking Apache version... 2.4.16
checking for python... /usr/bin/python
configure: creating ./config.status
config.status: creating Makefile

daviesc@orion:mod_wsgi-develop [0]$ sudo make
./apxs -c -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -Wc,-g -Wc,-O2  -Wc,'-arch x86_64' src/server/mod_wsgi.c src/server/wsgi_*.c -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config  -arch x86_64 -lpython2.7 -ldl  -framework CoreFoundation 
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/mod_wsgi.lo src/server/mod_wsgi.c && touch src/server/mod_wsgi.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_apache.lo src/server/wsgi_apache.c && touch src/server/wsgi_apache.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_buckets.lo src/server/wsgi_buckets.c && touch src/server/wsgi_buckets.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_convert.lo src/server/wsgi_convert.c && touch src/server/wsgi_convert.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_daemon.lo src/server/wsgi_daemon.c && touch src/server/wsgi_daemon.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_interp.lo src/server/wsgi_interp.c && touch src/server/wsgi_interp.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_logger.lo src/server/wsgi_logger.c && touch src/server/wsgi_logger.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_memory.lo src/server/wsgi_memory.c && touch src/server/wsgi_memory.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_metrics.lo src/server/wsgi_metrics.c && touch src/server/wsgi_metrics.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_restrict.lo src/server/wsgi_restrict.c && touch src/server/wsgi_restrict.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_server.lo src/server/wsgi_server.c && touch src/server/wsgi_server.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_stream.lo src/server/wsgi_stream.c && touch src/server/wsgi_stream.slo
./libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1  -g -O2 -arch x86_64 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE  -c -o src/server/wsgi_validate.lo src/server/wsgi_validate.c && touch src/server/wsgi_validate.slo
./libtool --silent --mode=link /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc    -o src/server/mod_wsgi.la  -rpath /usr/libexec/apache2 -module -avoid-version    src/server/wsgi_validate.lo src/server/wsgi_stream.lo src/server/wsgi_server.lo src/server/wsgi_restrict.lo src/server/wsgi_metrics.lo src/server/wsgi_memory.lo src/server/wsgi_logger.lo src/server/wsgi_interp.lo src/server/wsgi_daemon.lo src/server/wsgi_convert.lo src/server/wsgi_buckets.lo src/server/wsgi_apache.lo src/server/mod_wsgi.lo -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -arch x86_64 -lpython2.7 -ldl -framework CoreFoundation

daviesc@orion:mod_wsgi-develop [0]$ sudo make install
./apxs -i -S LIBEXECDIR=/usr/libexec/apache2 -n 'mod_wsgi' src/server/mod_wsgi.la
/usr/share/httpd/build/instdso.sh SH_LIBTOOL='./libtool' src/server/mod_wsgi.la /usr/libexec/apache2
./libtool --mode=install install src/server/mod_wsgi.la /usr/libexec/apache2/
libtool: install: install src/server/.libs/mod_wsgi.so /usr/libexec/apache2/mod_wsgi.so
install: /usr/libexec/apache2/mod_wsgi.so: Operation not permitted
apxs:Error: Command failed with rc=4653056
.
make: *** [install] Error 1
daviesc@orion:mod_wsgi-develop [0]$ 

**The Makefile looks like:**

APXS = ./apxs
PYTHON = /usr/bin/python

DESTDIR = 
LIBEXECDIR = /usr/libexec/apache2

CPPFLAGS =  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DENABLE_DTRACE -DMACOSX -DNDEBUG -DNDEBUG -DENABLE_DTRACE 
CFLAGS =  -Wc,-g -Wc,-O2  -Wc,'-arch x86_64'
LDFLAGS =  -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config  -arch x86_64
LDLIBS =  -lpython2.7 -ldl  -framework CoreFoundation 

SRCFILES = src/server/mod_wsgi.c src/server/wsgi_*.c

all : src/server/mod_wsgi.la

src/server/mod_wsgi.la : $(SRCFILES)
        $(APXS) -c $(CPPFLAGS) $(CFLAGS) $(SRCFILES) $(LDFLAGS) $(LDLIBS)

$(DESTDIR)$(LIBEXECDIR) :
        mkdir -p $@

install : all $(DESTDIR)$(LIBEXECDIR)
        $(APXS) -i -S LIBEXECDIR=$(DESTDIR)$(LIBEXECDIR) -n 'mod_wsgi' src/server/mod_wsgi.la

**Comment by davies-barnard** [comment]
Hi,

I have just tried to manually copy the .so file from the server/.libs folder to the /usr/libexec/apache2 folder but it was having none of it even with sudo!

**Comment by GrahamDumpleton** [comment]
Reinstalling command line tools and re accept T&C will be required on OS upgrades. So can't skip that unfortunately.

As for the error, it sort of suggests it doesn't like the .so file being replaced when in use, which have not seen before.

Can only suggest then you actually stop the Apache installation first and then do the install.

Can you let me know quickly if that works. I am off travelling again tomorrow and my El Capitan laptop will be staying home. So if I need to try anything I need to try it in next couple of hours before sleep.

**Comment by GrahamDumpleton** [comment]
BTW, don't recommend doing the configure/make as root. Do those as normal user. Only one you need to do as root is 'sudo make install'. Because you have built in the source code already as root, you should so 'sudo make distclean' to get it back to starting point. That may be a good idea anyway in case compilation output from older OS version was laying around.

**Comment by davies-barnard** [comment]
Hi Graham,

Thanks for quick response.  So I stopped apache, did sudo distclean and then re-ran ./configure and make (not sudo) before sudo make install but same error.  I'm using the develop zip from here.

**Comment by davies-barnard** [comment]
I should add that the SO file is no longer there, which is what alerted me to the problem.   When the install of El Capitan happened it seemed to remove the *mod_wsgi-py27.so* file as it no longer appears at the location suggested by the directive I had been using * LoadModule wsgi_module /usr/libexec/apache2/mod_wsgi-py27.so*    Is yours still OK?

**Comment by GrahamDumpleton** [comment]
If it is called ``mod_wsgi-py27.so``, it was not likely installed by ``configure; make; make install``, but:

```
pip install mod_wsgi
mod_wsgi-express install-module
```

I know doing a ``pip install mod_wsgi`` and running ``mod_wsgi-express start-server`` works okay as had to fix an issue with that and release a new version.

I thought I checked out the 'configure/make/make install' path as well, but will check again.

BTW, if issue only happens on install and before even try restarting Apache, ensure any use of mod_wsgi is commented out of Apache configuration. Reboot your system and then manually remove any mod_wsgi .so in modules directory and then try and reinstall. I can only think the error relates to some process holding the file open in a strange way or with a lock. A reboot should clear anything strange.

**Comment by davies-barnard** [comment]
I did not know that but that makes sense.  I think on my iMac I did it manually and then on the macbook via pip.  Have tried to pip it now and get this:

daviesc@orion:~ [0]$ sudo mod_wsgi-express install-module
Traceback (most recent call last):
  File "/usr/local/bin/mod_wsgi-express", line 9, in <module>
    load_entry_point('mod-wsgi==4.4.15', 'console_scripts', 'mod_wsgi-express')()
  File "/Library/Python/2.7/site-packages/mod_wsgi/server/__init__.py", line 3117, in main
    cmd_install_module(args)
  File "/Library/Python/2.7/site-packages/mod_wsgi/server/__init__.py", line 3075, in cmd_install_module
    shutil.copyfile(where(), target)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 1] Operation not permitted: '/usr/libexec/apache2/mod_wsgi-py27.so'
daviesc@orion:~ [0]$ 

So will reboot whilst apache is stopped with those lines uncommented.

**Comment by GrahamDumpleton** [comment]
I can replicate it. Odd. Time to work out why.

**Comment by GrahamDumpleton** [comment]
Am wondering whether this is the new stupid sandboxing rules in El Capitan.

Possible workaround is.

1. Use ``pip install mod_wsgi`` to install into either main Python installation or Python virtual environment.

2. Then run:

```
mod_wsgi-express module-location
```

3. Take the path that outputs and modify Apache configuration so it has a ``LoadModule`` line for ``wsgi_module`` with that path.

In other words, not trying to install module into Apache modules directory, but use it out of the Python installation.

**Comment by davies-barnard** [comment]
Phew!   At least I can put my dunces hat to one side on this occasion!

**Comment by GrahamDumpleton** [comment]
Related:

* https://en.wikipedia.org/wiki/System_Integrity_Protection

**Comment by davies-barnard** [comment]
Yes,  this seems to have made progress and my Apache install will now start with the Mod_WSGI modules enabled.  Now getting an 500 Internal Server Error relating to [Tue Oct 06 09:53:14.040894 2015] [wsgi:error] [pid 667] [client 127.0.0.1:49284]   Reason: unsafe use of relative rpath libmysqlclient.18.dylib in /Library/Python/2.7/site-packages/_mysql.so with restricted binary, referer: http://csmatrix.local/   but that is nothing to do with this module!

**Comment by GrahamDumpleton** [comment]
That one is likely going to be more fun. I don't know what the equivalent options for MacOS X are, but this is going to be the result of doing something similar to using ``-R ../some/path`` on a Linux box. This results in a relative directory location appearing in rpath, which is the compiled in set of directories searched for dynamic libraries at run time when loading them. A relative directory is somewhat evil and no surprise they are trying to stop it. Unfortunately, have seen some packages which use them to allow themselves to test stuff out of the source directories where they are built before they are installed.

**Comment by GrahamDumpleton** [comment]
For MySQL module issue:

* https://github.com/brianmario/mysql2/issues/646

**Comment by davies-barnard** [comment]
Thanks Graham.   Have a good break - hope its somewhere nice.

**Comment by GrahamDumpleton** [comment]
Not a holiday this time. Just got back from my 3+ week holiday. For work this time.

**Comment by davies-barnard** [comment]
Well hopes it a good trip - they can be the worst!   I fixed the MySQL problem by following http://stackoverflow.com/questions/31343299/mysql-improperly-configured-reason-unsafe-use-of-relative-path.

**Comment by jheasly** [comment]
When I ran
```bash
$ mod_wsgi-express install-module
```
I got the same error:
```bash
IOError: [Errno 1] Operation not permitted: '/usr/libexec/apache2/mod_wsgi-py27.so'
```
And this method to get the path for `httpd.conf` worked for me:
> 3 - Take the path that outputs and modify Apache configuration so it has a LoadModule line for wsgi_module with that path.

**Comment by GrahamDumpleton** [comment]
Yep, you can't use ``install-module`` in this case as it is still copying it into the Apache modules directory. The ``module-location`` approach is using it from where the ``mod_wsgi.so`` was installed into the Python installation or virtual environment and isn't copying anything into the Apache modules directory.

**Comment by ngbgithub** [comment]
For whatever it's worth-- I had the same problem after upgrading to El Capitan, and using the suggested workaround of explicitly specifying the location of mod_wsgi.so in its compilation directory worked for me.  That is, I could start Apache by changing the relevant line in my httpd.conf file to:

    LoadModule wsgi_module /opt/packages/mod_wsgi-4.4.13/src/server/.libs/mod_wsgi.so

The Wikipedia article to which Graham linked also suggests there's a boot parameter one could tweak in order to get write access to /usr/libexec, but I didn't pursue that because I prefer to keep my installation of El Capitan as "vanilla" as possible.

(I'm also not a fan of having to futz with some boot parameter in order to get functional root access on my own laptop, but that's neither here nor there.)

Thanks so much for the great software package, Graham.

**Comment by jheasly** [comment]
Yes, just reporting it "worked for me" was my main motivation too.

And YES!, thanks so much for the great software @GrahamDumpleton !

**Comment by GrahamDumpleton** [comment]
I haven't tested it still, but if using the 'configure/make/make install' method, another way is to create a separate modules directory in a location such as ``/usr/local/apache/modules`` and then do:

```
make install LIBEXECDIR=/usr/local/apache/modules
```

Then when setting up Apache configuration, point ``LoadModule`` at the ``mod_wsgi.so`` in that directory.

**Comment by thijstriemstra** [comment]
`sudo make install LIBEXECDIR=/opt/mod_wsgi` worked here on OSX 10.11.1.

**Comment by UlfKronman** [comment]
Hi all, 
since I had good help by this discussion, I want to add my experience to it.

I had the same problem running Django on Apache through mod_wsgi after upgrading to OS X El Capitan. I reinstalled XCode with command line tools and tried to recompile mod_wsgi, but the sudo make install failed with the above mentioned error:
[Errno 1] Operation not permitted: '/usr/libexec/apache2/mod_wsgi-py27.so'

I then remembered that I had a problem with the new System Integrity Protection when I migrated my BootCamp installation into Parallels Desktop after upgrading to El Capitan, and I then solved the problem by turning off the System Integrity Protection.

I tried the same solution here and it worked! 

This is how to do it:
http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

1. Reboot the Mac and hold down Command + R keys simultaneously after you hear the startup chime, this will boot OS X into Recovery Mode
2. When the “OS X Utilities” screen appears, pull down the ‘Utilities’ menu at the top of the screen instead, and choose “Terminal”
3. Type the following command into the terminal then hit return:
csrutil disable; reboot
4. You’ll see a message saying that System Integrity Protection has been disabled and the Mac needs to restart for changes to take effect, and the Mac will then reboot itself automatically, just let it boot up as normal

Then redo the sudo make install in the mod_wsgi source code directory.

If you want to enable System Integrity Protection again, reboot with cmd-R and go into terminal as described above and then write:
csrutil enable

Regards,
Ulf

**Comment by qpoisson** [comment]
Hi Graham,

I followed your suggestion of "(1) pip install mod_wsgi (2) mod_wsgi-express module-location  (3)... Take the path that outputs and modify Apache configuration so it has a LoadModule line for wsgi_module with that path."

However, "apachectl configtest" still reported the following syntax error:

httpd: Syntax error on line 67 of /private/etc/apache2/httpd.conf: Cannot load /Users/Q/anaconda/lib/python2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so into server: dlopen(/Users/Q/anaconda/lib/python2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so, 10): Library not loaded: libpython2.7.dylib\n  Referenced from: /Users/Q/anaconda/lib/python2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so\n  Reason: unsafe use of relative rpath libpython2.7.dylib in /Users/Q/anaconda/lib/python2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so with restricted binary

Any suggestion ?

Thanks
q.

**Comment by qpoisson** [comment]
Alos tried "sudo make install LIBEXECDIR=/opt/mod_wsgi", similar error:


httpd: Syntax error on line 68 of /private/etc/apache2/httpd.conf: Cannot load /opt/mod_wsgi/mod_wsgi.so into server: dlopen(/opt/mod_wsgi/mod_wsgi.so, 10): Library not loaded: libpython2.7.dylib\n  Referenced from: /opt/mod_wsgi/mod_wsgi.so\n  Reason: unsafe use of relative rpath libpython2.7.dylib in /opt/mod_wsgi/mod_wsgi.so with restricted binary

**Comment by GrahamDumpleton** [comment]
Anaconda Python keeps breaking stuff on different platforms around how library linking or Python initialisation works.

In this case can only suggest you play with ``install_name_tool`` to override the name/path it looks the library up as. I don't know the exact command you would need to use, plus on a holiday right now so no time to experiment, but you might find the following helpful.

* http://osiris.laya.com/coding/dylib_linking.html
* http://thecourtsofchaos.com/2013/09/16/how-to-copy-and-relink-binaries-on-osx/

Let us know if you work out a command to fix the library reference in ``mod_wsgi.so`` using ``install_name_tool``.

**Comment by soupcon** [comment]
Here is a solution to [qpoisson's problem](https://github.com/GrahamDumpleton/mod_wsgi/issues/98#issuecomment-231426658) of the "unsafe use of relative rpath" error in loading `libpython*.dylib`. It was inspired by a [similar problem](http://stackoverflow.com/questions/33281753/unsafe-use-of-relative-rpath-libboost-dylib-when-making-boost-python-helloword-d/33300738#33300738) with Boost Python in El Capitan.

The specific error I observed on running `mod_wsgi-express start-server` was:

httpd (mod_wsgi-express) : Syntax error on line 155 of /tmp/mod_wsgi-localhost:8000:502/httpd.conf: Cannot load /Users/soupcon/anaconda/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so into server: dlopen(/Users/soupcon/anaconda/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so, 10): Library not loaded: libpython3.5m.dylib\n  Referenced from: /Users/soupcon/anaconda/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so\n  Reason: unsafe use of relative rpath libpython3.5m.dylib in /Users/soupcon/anaconda/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-darwin.so with restricted binary

First, I located the problematic SO file in my Anaconda distribution:
`cd /Users/soupcon/anaconda/lib/python3.5/site-packages/mod_wsgi/server/`
`ls mod_wsgi-py35.cpython-35m-darwin.so`

Next, I saved a copy of the SO file as a precaution:
`cp -a mod_wsgi-py35.cpython-35m-darwin.so mod_wsgi-py35.cpython-35m-darwin.so.original`

Then I used `install_name_tool` to modify the SO file so that it uses the absolute path for `libpython*.dylib`, rather than a relative path (a symlink was ineffective):
`install_name_tool -change libpython3.5m.dylib /Users/soupcon/anaconda/lib/libpython3.5m.dylib mod_wsgi-py35.cpython-35m-darwin.so`

`mod_wsgi-express start-server` worked immediately afterwards.
